### ISSUE TITLE
Connections creates a `nodes` field as well as an `edges` and `pageInfo` field

### ISSUE THREAD

**Issue by SorenHolstHansen** [async-graphql/async-graphql#1001]
I am not really sure if this is intentional, but it seems weird.

When i use the built in cursor connection, i expect to have two top-level fields to query, namely `edges` and `pageInfo`, however, it seems that a new `nodes` field has been added that returns, well, the list of nodes. Is this intentional?

## Specifications

- Version: 4.0.4, using actix-web

**Comment by sunli829** [comment]
This is intentional, see #952 🙂

**Comment by xoac** [comment]
According to the documentation linked in #952 

> This leads to a potential usability improvement for connections; instead of just exposing the edges list, we **could** also expose a dedicated list of just the nodes, to avoid a layer of indirection.

So this means that `nodes` should be optional the simplest solution I came up would be to add feature "connection-without-nodes"  that will disable this endpoint from schema. @sunli829  would you accept nodes to be optional? Is my solution acceptable so I could prepare PR?

**Comment by sunli829** [comment]
@xoac welcome to PR 🙂
