### ISSUE TITLE
Usage without derive macros

### ISSUE THREAD

**Issue by joepio** [async-graphql/async-graphql#1003]
I have a project ([atomic-server](https://github.com/atomicdata-dev/atomic-data-rust)) that would benefit greatly from GraphQL support. However, part of this project is that the data models / schemas are defined by the end-user, at runtime. This means that using `derive` macros to generate schema objects (and queries) are not an option. I _expect_ that `async-graphql` could also be used without compile-time derives for data models, but I'm not entirely sure where to start. Thanks!

**Comment by sunli829** [comment]
I understand what you want, unfortunately `Async-graphql` does not support this.😄

**Comment by joepio** [comment]
I fully understand that this is not support! But I think it may be _possible_ to re-use parts of this repo, such as `async-graphql-parser`. I think I'll start there!

**Comment by sunli829** [comment]
https://github.com/async-graphql/graphgate

You can take a look at this, I think it'll help you.
