### ISSUE TITLE
Support `#[graphql(flatten)]` when deriving both `SimpleObject` and `InputObject`

### ISSUE THREAD

**Issue by bvanneerven** [async-graphql/async-graphql#1004]
## Description of the feature
Right now, using `#[graphql(flatten)]`  when deriving both `SimpleObject` and `InputObject` results in an error, because multiple `create_type_info` are found.
It would be nice if the example below could be supported.

## Code example

```rs
use async_graphql::*;

#[derive(SimpleObject, InputObject)]
#[graphql(input_name = "ABCInput")]
#[graphql(name = "ABC")]
struct ABC {
    a: String,
    #[graphql(flatten)]
    bc: BC,
}

#[derive(SimpleObject, InputObject)]
struct BC {
    b: String,
    c: String,
}
```

should lead to

```gql
type ABC {
    a: String!
    b: String!
    c: String!
}

input ABCInput {
    a: String!
    b: String!
    c: String!
}
```

**Comment by sunli829** [comment]
Here is the test:

https://github.com/async-graphql/async-graphql/blob/f0dc85495b25f98664419405d59676f309cd9aab/tests/input_object.rs#L453
