### ISSUE TITLE
Cast usize values to u64

### ISSUE THREAD

**Issue by secretfader** [async-graphql/async-graphql#101]
In order to resolve compilation errors in my application, I needed to [cast usize values to u64](https://github.com/secretfader/async-graphql/commit/61b3cf705032b688272ddc3fe6bffc4a8e13c813). I also encounter this error when compiling this repository locally with `rustc 1.43.1 (8d69840ab 2020-05-04)`.

**Comment by sunli829** [comment]
Thank you, this is because of multer breaking changes, please upgrade async-graphql to 1.12.18.
