### ISSUE TITLE
Support registering the same type multiple times

### ISSUE THREAD

**Issue by dspicher** [async-graphql/async-graphql#1015]
## Description of the feature
It can be useful to have multiple structs in Rust code that should resolve to the same GraphQL type, for example because they are associated with different representations in a database schema.

Registering an object of the same name twice currently always fails. This is overly restrictive, as the second registration could be a no-op if the second type is identical in its shape to the already registered one.

**Comment by sunli829** [comment]
Not allowing multiple Rust types to map to same GraphQL type avoids hard-to-find bugs, so for now I think it's fine. 🙂
