### ISSUE TITLE
Build script added back in parser 4.0.7

### ISSUE THREAD

**Issue by djc** [async-graphql/async-graphql#1024]
I noticed that the 4.0.7 release for async-graphql-parser added back the build script that I had removed in #901. I was surprised to notice that the dependencies were added back, and it seems weird that these changes are tucked into a release/version bump commit with no further description.

**Comment by sunli829** [comment]
Generated parser via `test` will give an error when running on CI, but I don't know how to fix it, so I changed back to `build.rs`. 😂
