### ISSUE TITLE
Discussion: DBDataSource

### ISSUE THREAD

**Issue by sunli829** [async-graphql/async-graphql#103]
The performance of stream-based DataSource is somewhat slow, because it requires users to fetch all records from the database. However, it is very convenient to use and has certain practicality in certain scenarios.
In order to improve query performance, can we add another DBDataSource and then pass `after`,` before`, `limit` to the database query, is this possible?

@IcanDivideBy0 @phated @nicolaiunrein

**Comment by IcanDivideBy0** [comment]
This is possible for sure but how would you abstract the database? I think this should be user code cause it's a trade off between functionalities and performances: for example: have totalCount or fetch from DB with a limit ?

**Comment by phated** [comment]
I will be testing the new stream DataSource with `sqlx`, which returns a stream from a database query. I assume I can use `LIMIT`, `OFFSET` and other sql in my queries before receiving my stream.

**Comment by sunli829** [comment]
Yes, we may need to abstract the query operations of the database, create a `DBDataSource` trait, and then implement `SqlXDataSource` and `DieselDataSource`.

**Comment by IcanDivideBy0** [comment]
I'm pretty sure you cannot conform to the spec with SQL only.

The main problem is that if the cursor does not exist, the whole dataset sould be used.

Let's assume some data

|ID
|---
|1
|3
|5

Now try a simple example: `after: "2", first 2`.

To fetch only the needed DB records, you have to sort by cursor (whatever it is) so you can filter with something like `WHERE ID > $AFTER`, the where clause will incorrectly filter out the ID 1

**Comment by IcanDivideBy0** [comment]
I like how the relay connection work, but this specific part of the spec makes it a nightmare to implement. In real world, I've always ignored this and used an **almost** relay connection due to this.

**Comment by sunli829** [comment]
Implementing a `DataSource` is too cumbersome, and the complex `QueryOperation` enum makes me never want to use this function.
We require cursor to always correspond to a sorted field in the database, which should be the majority of cases, so at least we don’t have to deal with `QueryOperation`, right?

**Comment by IcanDivideBy0** [comment]
> Implementing a DataSource is too cumbersome, and the complex QueryOperation enum makes me never want to use this function

Agreed, this enum is a bit convoluted, things would have been cleaner and easier to handle if we passed the `Pagination` struct directly to the `query_operation`

```rust
struct Pagination {
    after: Option<Cursor>,
    before: Option<Cursor>,
    first: Option<i32>,
    last: Option<i32>,
}
```

**Comment by phated** [comment]
The pagination struct is mirroring the algorithm that Relay specs 🤷

**Comment by phated** [comment]
I've not actually reviewed if the way you pattern matched actually follows the spec...

**Comment by IcanDivideBy0** [comment]
> The pagination struct is mirroring the algorithm that Relay specs
It's more the `QueryOperation` enum that we are questioning here

**Comment by phated** [comment]
Yes, that's what I meant. I'm on mobile right now. That enum represents the operations that should be performed. The old version didn't follow the spec and if pattern matching on struct fields is very unclear.

**Comment by IcanDivideBy0** [comment]
https://relay.dev/graphql/connections.htm#sec-Pagination-algorithm
The specs doesn't define 12 possible different operations but an algorithm with branching path such as if, else, loops.
The enum represent all the possible outcome of this branching, hence loosing any code factoring possibility

**Comment by IcanDivideBy0** [comment]
For instance implementing this step
> If first is set:
is easier with
```rust
if let Some(first) = pagination.first {
    // ...
}
```
than with
```rust
match operation {
    QueryOperation::First { limit }
    | QueryOperation::FirstAfter { limit, .. }
    | QueryOperation::FirstBefore { limit, .. }
    | QueryOperation::FirstBetween { limit, .. } => {
        // ...
    }

    _ => {}
}
```

**Comment by IcanDivideBy0** [comment]
Anyways, we're diverging from the topic, I don't think we can solve the whole pagination problem in a generic way. Most people will end up implementing their own logic, our job is more to provide an easy way to do so, that's at least what I'm trying to achieve her :)

**Comment by phated** [comment]
🤷 when trying to implement this with an RDBMS, the enum made things easier to work with for it.

But my other projects have me buried, so I can't spend every day working on this stuff. I guess my opinion doesn't matter.

The 1 night of week I can usually spend on this stuff requires me to spend the whole time upgrading.

**Comment by sunli829** [comment]
Probably whether ·QueryOperation· is complex is not the key to the problem. Even if we decompose it, it is still very complicated.😂 It is not easy to implement a fully compatible Relay connection, but if this implementation is universal, we can complete these tasks at the `DBDataSource`.

**Comment by IcanDivideBy0** [comment]
@phated I'd be curious to see how you implemented it for RDBMS if you can provide a code sample :)

There seems to be 2 different use case:
- generate a database query from pagination inputs
- apply pagination algorithm to a dataset
So may be `DBDataSource` is the way to go after all!`

**Comment by sunli829** [comment]
If you don't want to use `QueryOperation`, you can implement the `DataSource::query` method, which may be more convenient in some cases.

**Comment by IcanDivideBy0** [comment]
> If you don't want to use QueryOperation, you can implement the DataSource::query method, which may be more convenient in some cases.

Didn't even thought of it 😂, It still requires to add an empty `query_operation` as well but still simplify things for me :D

**Comment by IcanDivideBy0** [comment]
So what do you think about something like this ?
```rust
trait DataSource {
    fn query(&mut self);
}

trait DBDataSource {
    fn query_operation(&mut self);
}

impl DataSource for dyn DBDataSource {
    fn query(&mut self) {
        self.query_operation()
    }
}
```

**Comment by sunli829** [comment]
This is my initial thought. This `DBDataSource` is not related to the original `DataSource`.

```rust
trait DBDataSource {
    type Record;
    type Element: OutputValueType;
    type EdgeFieldsObj: ObjectType + Send;

    fn get_key(item: Self::Item) -> Cursor;

    fn record_to_element(item: Self::Record) -> (Self::Item, Self::EdgeFieldsObj);

    fn do_query(
        &self,
        ctx: &Context<'_>,
        after: Option<Cursor>,
        before: Option<Cursor>,
        first: Option<i32>,
        last: Option<i32>,
    ) -> FieldResult<Vec<Self::Item>>;

    fn query(
        &self,
        ctx: &Context<'_>,
        after: Option<Cursor>,
        before: Option<Cursor>,
        first: Option<i32>,
        last: Option<i32>,
    ) -> FieldResult<Connection<Self::Element, Self::EdgeFieldsObj>> {
        for record in self.do_query(ctx)? {
            ...
        }
    }
}
```

**Comment by sunli829** [comment]
I feel this is ugly and needs improvement. 😂

**Comment by sunli829** [comment]
I'll learn how to use SQLX and see how to pass query parameters to SQL.

**Comment by sunli829** [comment]
Maybe we only need this?
```rust
impl ToSQL for QueryOperation { ... }
```

**Comment by IcanDivideBy0** [comment]
I personally use mongodb, so my only concern right now is how I will opt-out this :/

**Comment by sunli829** [comment]
I rewrote the code of DatsSource.
The DataSource implemented for Stream has been temporarily removed, and this modification will be added after everyone agrees.

**Comment by phated** [comment]
I should have my implementation pushed "soon" using the new DataSource. We can use that to inform if DBDataSource is helpful.

**Comment by sunli829** [comment]
Great, look forward to it! 😁

**Comment by ruseinov** [comment]
> I should have my implementation pushed "soon" using the new DataSource. We can use that to inform if DBDataSource is helpful.

Curious where to look at it once pushed!
