### ISSUE TITLE
Missing feature in Cargo.toml: `bson-uuid` ?

### ISSUE THREAD

**Issue by jonahseguin** [async-graphql/async-graphql#1032]
Hi, first issue here.  I'm using async-graphql@4 in combination with thedodd/wither@0.9 and uuid@0.8 (via bson::uuid)

Obviously, I'd like to have `ScalarType` etc. implemented for the `Uuid` type, and also be able to use it with the `wither` model types.

I noticed that in [src/types/external/bson.rs#L25](https://github.com/async-graphql/async-graphql/blob/master/src/types/external/bson.rs#L25) there are the trait implementations I need for `Uuid`, enabled by the feature-flag `bson-uuid`, however the `bson-uuid` feature isn't included in the Cargo.toml for async-graphql and thus I can't use it.

(and yes, I tried using the uuid08 feature to no success for my use case, since the type I am using is nested in bson::uuid)

I'm wondering if this is intentional?  If not, I'll gladly open a PR to add the feature to the Cargo.toml.

Thanks!

**Comment by jonahseguin** [comment]
PR that added the `bson-uuid` feature: https://github.com/async-graphql/async-graphql/pull/875

**Comment by maraisr** [comment]
Im not sure we need to be doing this, the crate knows about the features simply by specifying them in the code see ~> https://docs.rs/crate/async-graphql/latest/features#bson

That being said though; not sure if doing this `bson-uuid = ["dep:bson"]` would enable the optional dep on `bson` for us?

@sunli829 what do you think, probably we can close this issue.

**Comment by sunli829** [comment]
I've removed the `bson-uuid` feature, which feels unnecessary.
