### ISSUE TITLE
Opaque cursor

### ISSUE THREAD

**Issue by plippe** [async-graphql/async-graphql#1033]
Hi,

GraphQL.org suggests having opaque cursors for pagination. They encourage a base 64 encoding.
> As a reminder that the cursors are opaque and that their format should not be relied upon, we suggest base64 encoding them.
> \- https://graphql.org/learn/pagination/

I currently use the following for my pet project

```rust
pub struct Base64Cursor<A>(pub A);

impl<A: CursorType> CursorType for Base64Cursor<A> {
    type Error = String;

    fn decode_cursor(s: &str) -> Result<Self, Self::Error> {
        base64::decode_config(s, base64::URL_SAFE_NO_PAD)
            .ok()
            .as_ref()
            .and_then(|s| std::str::from_utf8(s).ok())
            .and_then(|c| A::decode_cursor(c).ok())
            .map(|a| Base64Cursor(a))
            .ok_or_else(|| "Unable to parse cursor".to_owned())
    }

    fn encode_cursor(&self) -> String {
        self.0
            .encode_cursor()
            .pipe(|cursor| base64::encode_config(cursor, base64::URL_SAFE_NO_PAD))
    }
}
```

My implementation builds on top of `CursorType`, but it could use Serde's `Serialize` and `Deserialize`. Possibly something like the following:

```rust
// WIP, won't compile
impl<A: Serialize + Deserialize> CursorType for A {
    type Error = ???;

    fn decode_cursor(s: &str) -> Result<Self, Self::Error> {
        base64::decode_config(s, base64::URL_SAFE_NO_PAD)
            .and_then(|s| serde_json::from_str(s))
    }

    fn encode_cursor(&self) -> String {
        serde_json::to_string(self)
            .and_then(|json| base64::encode_config(json, base64::URL_SAFE_NO_PAD))
    }
}
```

While this is one idea, another option is to use [cbor](https://cbor.io/) as it is already included in this project.

Would there be any objections if I opened a PR to change `CursorType`'s `encode_cursor` and `decode_cursor`? I am open to any encoding if base64 isn't preferred.

**Comment by onx2** [comment]
I [posted](https://github.com/async-graphql/async-graphql/issues/563) about this a while back and one of the folks at Vector, @leebenson,  posted a link to their open source code that solved 99% of the problems I was trying to solve. Maybe this will help you?

https://github.com/vectordotdev/vector/blob/master/src/api/schema/relay.rs

I just came back to this trying to update my `async-graphql` v3 -> v4 relay spec and they did it already 😂 Literally life savers doing the best work.

**Comment by plippe** [comment]
Hey,

Thank you for the link. While I saw the code previously, I wasn't particularly happy with the hard coded type, `usize`. I preferred a generic approach.

I also believe that a bundled solution would allow everyone to benefit from it.

Anyways, I have a solution for my problem. If someone wishes, I can easily create a PR.

**Comment by onx2** [comment]
I would be interested in seeing your solution 😄  While I'm not a maintainer of this repo, I think PR's are always welcome and at the very least provide a searchable resource for people in similar situations.

**Comment by plippe** [comment]
This feature has been released
