### ISSUE TITLE
Concurrency with redis

### ISSUE THREAD

**Issue by salva-imm** [async-graphql/async-graphql#1034]
Hi there
i re-implemented `starwars` example (actix) with redis:
https://github.com/salva-imm/starwars
I moved the models/data into Redis
I ran a few benchmarks, and it was terrible : )
my implementation is not the best one yet, I'm using `clone` and `move` heavily, for the sake of `serde`
but yet, I didn't expect to see this result:

<img width="869" alt="Screen Shot 2022-08-22 at 3 33 04 AM" src="https://user-images.githubusercontent.com/32010748/185814526-a75a14a3-95d0-4aec-ad17-2262016d05ab.png">

400 req/s !!

is this how far we can go? 

---
I ran some other benchmarks after changing response to hardcoded data(mostly None) to see if its Redis or my code that makes it slow
and I achieved 2k req/s , but yet its not what I'm getting while using REST and raw actix ( ~ 80k!)

I would appreciate it if you could give me some tips for performance and concurrency, I'm new in Rust : )

hardware:
Macbook m1/16G

query :
`{ humans{ edges{ node{ id friends{ id name } name }}}}`
(I chose this because its heavy, and I needed to retrieve `friends` as well)

benchmark tool:
https://github.com/hasura/graphql-bench + autocannon

redis data:

<img width="1094" alt="Screen Shot 2022-08-22 at 4 57 31 AM" src="https://user-images.githubusercontent.com/32010748/185817994-5bbd7b85-a428-409d-8a71-f59d91f566ad.png">

---------

EDIT:
by using actix_redis rather than bb8+redis-rs, I improved the result up to 4k/s
just don't know how far I can go : )

**Comment by sunli829** [comment]
Most of the time is spent fetching data from Redis.

**Comment by salva-imm** [comment]
@sunli829 indeed, if replacing redis driver(with actor model one) improved it a lot
but I got no more idea for going further 
I wonder what is best I could do with `async-graphql` itself
I'm going to run this benchmark on your example directly, without any change : )
