### ISSUE TITLE
Caching/Live query support

### ISSUE THREAD

**Issue by maraisr** [async-graphql/async-graphql#1035]
There was recently a concept explored by Marc over at https://github.com/xuorig/graphql-cache-cdc-invalidation where the strategy of invalidations/data access id's are tracked.

Could there exist a world where this is explored within async-graphql, specifically around the notion of `@live` query support.

Sounds like every data piece is mapped back to queries that depend on them, and those queries would be documents subscribed to by a client (more https://twitter.com/__xuorig__/status/1561444162091847680?s=20&t=NiXK5aAmdcOitIK-cUZJxA).

Little new to the project, and just thought perhaps there would be adaptors or something to ease this for us a little. Or probably 100% user land code, and async-graphql already helps us.

Thanks again for the lovely project 🙏🏻

**Comment by sunli829** [comment]
It's not easy to support the `live` directive, and I've tried it before, but I still haven't found a good solution.

**Comment by satvikpendem** [comment]
Grafbase just [announced live query support](https://grafbase.com/blog/simplify-building-realtime-applications-with-graphql-live-queries), and they write [their entire backend in Rust](https://github.com/grafbase/grafbase), so it might be useful to look through their code for this.
