### ISSUE TITLE
Allow extra input with upload. (or provide examples?)

### ISSUE THREAD

**Issue by ruseinov** [async-graphql/async-graphql#104]
I have tried the following approach:
```
    async fn upload(&self, ctx: &Context<'_>, asset: crate::model::AssetInput, file: Upload) -> FieldResult<Vec<Asset>> {
        info!("{:?}", file.path);
        Ok(Vec::new())
    }
```
But I'm not sure yet what is expected in the body. 

I'm trying to send something along these lines:
```
curl --location --request POST 'localhost:8089/graphql?query=mutation%20upload%20($asset:%20AssetInput,%20$file:%20Upload)%20{upload%20(asset:%20$asset,%20file:%20$file)%20{id}}&variables={%22asset%22:%20{%22assetTypeId%22:%20%225eb41f8200e7577f00d2292b%22,%20%22data%22:%20{%22id%22:%20111},%22name%22:%20%22blah%22}}' \
--header 'Authorization: Bearer 1234' \
--form 'file=@/Users/romanuseinov/Desktop/test.jpeg'
```
But obviously it is wrong. 

What I get in return is
 ```
[2020-05-21T14:49:30Z DEBUG actix_web::middleware::logger] Error in response: MissingOperatorsPart
```

I am actually not sure if it's even possible to pass extra params, but I would assume so, cause we definitely can send the query. I'd appreciate an example, otherwise will keep digging in the source code to try and figure this out.

**Comment by sunli829** [comment]
Incorrect requested data.


https://github.com/jaydenseric/graphql-multipart-request-spec


https://github.com/async-graphql/async-graphql/blob/ebc6c80ddd982db21a3695b948d6e0b15e748c41/src/types/upload.rs#L39

**Comment by ruseinov** [comment]
yes, great, I didn't realise the example was there :/ Thanks a lot, I'll try this out soon!

**Comment by ruseinov** [comment]
Once I'm done with my implementation I will provide an example similar to what I have been looking for in this ticket, for whoever decides to search for this next.

**Comment by ruseinov** [comment]
It works beautifully, here's a sample that can be reused as needed:
Mutation Object:
```
#[Object]
impl MutationRoot {
    async fn upload(&self, ctx: &Context<'_>, asset: crate::model::AssetInput, file: Upload) -> FieldResult<Vec<Asset>> {
        info!("{:?}", file.path);
        Ok(Vec::new())
    }
}
```

and the request using CURL
```
curl --location --request POST 'localhost:8089/graphql' \
--form 'file=@/Desktop/test.jpeg' \
--form 'operations={"query": "mutation upload ($asset: AssetInput, $file: Upload) {upload (asset: $asset, file: $file) {id}}",
"variables": {"file": null, "asset": {"assetTypeId": "5eb41f8200e7577f00d2292b", "data": {"id": 111},"name": "blah"}}}' \
--form 'map={ "file": ["variables.file"] }'
```
