### ISSUE TITLE
WASI support

### ISSUE THREAD

**Issue by maraisr** [async-graphql/async-graphql#1050]
## Description of the feature

Bit of a long shot question, I'm in a position where im wanting to run async-graphql at the edge, in a Cloudflare worker.

However it compiles it down into WASM and consumed via WASI, a simple test `cargo build --target=wasm32-wasi` proved that ya well way out of knowledge if its even possible.

So the question;

1. is "at edge" compute within the scope of this project
2. would a no-std avenue be achievable?
3. ^ does that even help me for at edge compute

**Comment by sunli829** [comment]
`Async-graphql` should be able to compile to `WASM` since it doesn't depend on anything platform dependent, are you having any issues? 🙂

**Comment by maraisr** [comment]
🤦🏻  was actually me.... So sorry, didn't fully understand the problem and lazied raised this. again sorry! got it working!! 🚀

**Comment by sunli829** [comment]
Don't worry 😉

**Comment by omarabid** [comment]
@maraisr I'm using Juniper with CF workers. It works well but am considering to switch to async-graphql. Can you share your worker implementation if it's open and available online?

**Comment by maraisr** [comment]
@omarabid not something that is OSS yet, largely still just playing. But its up and running here https://play.graphql.online

```gql
{
  _debug {
    colo
  }
}
```

currently just returns the COLO the worker is running in.

**Comment by atali** [comment]
Hey @maraisr,

Do you have an example of async-graphql + cloudflare workers ?
Thx,

**Comment by omarabid** [comment]
@atali https://github.com/async-graphql/async-graphql/pull/1122

**Comment by atali** [comment]
> @atali https://github.com/async-graphql/async-graphql/pull/1122

Thank you so much, let me have a look
