### ISSUE TITLE
Support a potential no_cache

### ISSUE THREAD

**Issue by maraisr** [async-graphql/async-graphql#1051]
## Expected Behaviour

Given this structure:

```rs
#[Object]
impl Query {
    #[graphql(cache_control(max_age = 30))]
    async fn foo(&self) -> &str {
        "foo"
    }

    #[graphql(cache_control(max_age = 0))]
    async fn bar(&self) -> &str {
        "bar"
    }
}
```

there is no way for me to say, dont cache cache_control if bar is requested? the `0` seems to be ignored.

Wonder if a `no_cache` can be explicitly supplied here?? Or are we venturing into a territory here where its just too complex to do caching this way.

## Steps to Reproduce the Problem

1. run any example
2. apply directives as above

**Comment by maraisr** [comment]
looks like all that needs to happen is flick this to being an `Option<usize>`

https://github.com/async-graphql/async-graphql/blob/master/src/registry/cache_control.rs#L69

so you can disable caching all together but setting ` #[graphql(cache_control(max_age = None))]`, if its `Some(0)`, it'll still do the compare, but will be ripped out during the `value`. So seems like best solution.

**Comment by sunli829** [comment]
You are right, I will support this tomorrow.

**Comment by sunli829** [comment]
Update in `master` branch 🙂

https://github.com/async-graphql/async-graphql/blob/70049ae798ce015db9a41b637142af990bffaaf0/src/registry/cache_control.rs#L22
