### ISSUE TITLE
Access contents inside OpaqueCursor

### ISSUE THREAD

**Issue by yaroslavros** [async-graphql/async-graphql#1052]
## Description of the feature
Would be great to have a mechanism to access and modify contents of OpaqueCursor - through deref and/or getter/setter methods as well as ability to create a new OpaqueCursor from something that can be encoded by serde_json.

Today the only way to create OpaqueCursor is by manually creating a base64 encoded JSON string, and there is no way to access contents of the cursor.

It is supposed to be Opaque for the client, but should be meaningful for the server.

## Code example (if possible)

**Comment by sunli829** [comment]
You can do this by implementing the `Cursor trait` yourself.

**Comment by ns-yrosomakho** [comment]
Absolutely! However, having in-library built-in OpaqueCursor with mutable internals would reduce boilerplate and help others. I don't believe this will create any backwards compatibility issues.

I'll submit a PR in a bit.

**Comment by lasantosr** [comment]
There is already an `OpaqueCursor` impl in the library, so it should have pub T or at least a constructor so it can be useful... otherwise we can't use them in `Edge`

**Comment by sunli829** [comment]
Released in `v4.0.16` 🙂
