### ISSUE TITLE
Is it possible to dynamic name for Query? 

### ISSUE THREAD

**Issue by xoac** [async-graphql/async-graphql#1064]
I am writing service where name of "function" Query  depends on input parameters (that do not change during the whole program, it's loaded from ENV). The question is if this is possible to change the name this way? I am quite new to graphql so also workaround suggestion will be good.

```rust
pub struct Query;

#[Object]
impl Query {
    #[graphql(name = <NAME_LOADED_AT_AT_THE_BEGIN_OF_PROGRAM_START> )]
    async fn terra(&self) -> MyObj {
        MyObj{}
    }
}
```

**Comment by sunli829** [comment]
This is currently not possible. 🙂
