### ISSUE TITLE
cannot find type `T` when using generics in Unions

### ISSUE THREAD

**Issue by nmoutschen** [async-graphql/async-graphql#1069]
## Expected Behavior

The following code snippet should compile:

```rust
use async_graphql::{Union, SimpleObject, ContainerType};

pub trait MyTrait: ContainerType + Send + Sync {}

#[derive(Union)]
pub enum MyEnum<T>
    where T: MyTrait,
{
    VariantT(T),
    VariantO(MyObject),
}

#[derive(SimpleObject)]
pub struct MyObject {
    value: String,
}
```

## Actual Behavior

This fails with the following error, which should not arise since `T` is defined as a generic type parameter to the enum `MyEnum`.

```
error[E0412]: cannot find type `T` in this scope
 --> src/lib.rs:9:14
  |
9 |     VariantT(T),
  |              ^ not found in this scope
```

Looking into the expansion of the Union derive, it comes from the following line:

```rust
async_graphql::static_assertions::assert_impl_one!(T: async_graphql::ObjectType);
```

Which itself, when expanded, contains this line:

```rust
let _ = <T as AmbiguousIfMoreThanOne<_>>::some_item;
```

## Steps to Reproduce the Problem

1. Create a new lib crate
2. Add `async-graphql` as a dependency
3. Paste the code snippet above
4. Run `cargo check`

## Specifications

- Version: 4.0.13
- Platform: macOS
- Subsystem: N/A

**Comment by choco** [comment]
I think this is the same issue I ran into https://github.com/async-graphql/async-graphql/issues/978 maybe you can try https://github.com/async-graphql/async-graphql/pull/983 and see if it works for you
