### ISSUE TITLE
Question: How to mock GraphQL Subscriptions with `axum` integration

### ISSUE THREAD

**Issue by ryan-summers** [async-graphql/async-graphql#1070]
I'm looking to simulate a GraphQL subscription for integration testing by directly passing HTTP requests to the [`axum::Router`](https://docs.rs/axum/0.5.16/axum/struct.Router.html) object.

This router object then passes the HTTP request to the [`GraphQLSubscription`](https://docs.rs/async-graphql-axum/4.0.13/async_graphql_axum/struct.GraphQLSubscription.html) provided by the `axum`-integration. However, I'm struggling to understand how to get the WebSocket operational. All of my attempts at manually manipulating headers of the HTTP request result in a HTTP 426 response being provided.

For context, this is how I am constructing the HTTP request (simulating a websocket request) and passing it to the app, which is of type `axum::Router<axum::body::Body>`:
```rust
        // Set up the websocket connection for subscriptions
        let ws_request = Request::builder()
            .method(Method::GET)
            .uri("/ws")
            .header(header::CONNECTION, "upgrade")
            .header(header::UPGRADE, "websocket")
            .header(header::SEC_WEBSOCKET_VERSION, "13")
            .header(header::SEC_WEBSOCKET_PROTOCOL, "graphql-ws")
            .header(header::SEC_WEBSOCKET_KEY, base64::encode([0u8; 16]));

        let response = app
            .call(ws_request.body(Body::empty())?)
            .await?;
```

What would I need to pass to the `app.call()` function, which then forwards to [`GraphQLSubscription`](https://docs.rs/async-graphql-axum/4.0.13/async_graphql_axum/struct.GraphQLSubscription.html), to start a subscription?

Printing the response and response body from the provided requests gives the following:
```
// Response object
Response { status: 426, version: HTTP/1.1, headers: {"content-type": "text/plain; charset=utf-8", "content-length": "73", "vary": "origin", "vary": "access-control-request-method", "vary": "access-control-request-headers"}, body: UnsyncBoxBody }
// Response body
b"WebSocket request couldn't be upgraded since no upgrade state was present"
```

**Comment by sunli829** [comment]
I suggest you to test the subscription like this, independent of the web framework:

https://github.com/async-graphql/async-graphql/blob/26819bd1a58d37f4e179449dbbd2cb52298971fe/tests/subscription.rs#L37

**Comment by ryan-summers** [comment]
Thanks, this worked like a charm and is a nice workaround. Requires minor restructuring of our integration testing, but that's not a problem.

Thanks for the insight!
