### ISSUE TITLE
How can I respond with an error in my subscription handler?

### ISSUE THREAD

**Issue by onx2** [async-graphql/async-graphql#1075]
I'm not sure how to properly respond with an error / how to handle errors in the `ws` endpoint. Using `.expect("Unauthorized");` causes the following error in the playground which doesn't seem right.
<img width="938" alt="image" src="https://user-images.githubusercontent.com/23039725/190948599-ccb6abb8-c10b-4db6-9bd2-edc6fa92a341.png">

Here is my handler. I want to be able to respond with a friendlier message if possible but I haven't been able to find any docs/examples of this.
```rust
#[handler]
pub async fn ws(
    schema: Data<&RealSchema>,
    db: Data<&Db>,
    headers: &HeaderMap,
    protocol: GraphQLProtocol,
    websocket: WebSocket,
) -> impl IntoResponse {
    let mut conn = db
        .connect()
        .expect("Unable to establish database connection from pool.");

    let auth = Auth::new(&mut conn, headers).await.expect("Unauthorized");

    let schema = schema.0.clone();
    let mut data = async_graphql::Data::default();
    data.insert(auth);

    websocket
        .protocols(ALL_WEBSOCKET_PROTOCOLS)
        .on_upgrade(move |stream| {
            GraphQLWebSocket::new(stream, schema, protocol)
                .with_data(data)
                .serve()
        })
}
```

**Comment by sunli829** [comment]
Do it like follow example:

```rust
#[handler]
pub async fn ws(
    schema: Data<&RealSchema>,
    db: Data<&Db>,
    headers: &HeaderMap,
    protocol: GraphQLProtocol,
    websocket: WebSocket,
) -> poem::Result<impl IntoResponse> { // change to poem::Result
    let mut conn = db
        .connect()
        .expect("Unable to establish database connection from pool.");

    let auth = Auth::new(&mut conn, headers).await.map_err(poem::error::Unauthorized)?; // maps the error to 401

    let schema = schema.0.clone();
    let mut data = async_graphql::Data::default();
    data.insert(auth);

    Ok(websocket
        .protocols(ALL_WEBSOCKET_PROTOCOLS)
        .on_upgrade(move |stream| {
            GraphQLWebSocket::new(stream, schema, protocol)
                .with_data(data)
                .serve()
        }))
}
```

**Comment by onx2** [comment]
Thanks for the response! This seems to be closer to what I need to do but I'm still getting an error:

```
the trait bound `anyhow::Error: StdError` is not satisfied
the trait `StdError` is not implemented for `anyhow::Error`
```

<img width="636" alt="image" src="https://user-images.githubusercontent.com/23039725/191140031-a2dc3a18-2cb8-491b-8629-f88f69c72607.png">


I thought maybe I was missing a feature flag, but even with `anyhow` feature in `poem` turned on it has the same result. I can fix the compile error by removing the `map_err` but then I get the same output in my playground. I'm pretty rough around the edges for error handling still, do you have anymore pointers?

This line implies it is a design decision in anyhow to not allow this? Should I consider changing that library out?
```
the trait `StdError` is not implemented for `anyhow::Error`
```

**Comment by sunli829** [comment]
Since `anyhow::Error` does not implement `std::error::Error`, you can convert the error to a string.

```rust
 let auth = Auth::new(&mut conn, headers).await.map_err(|err| poem::Error::from_string(err.to_string(), StatusCode::UNAUTHORIZED))?;
```

**Comment by onx2** [comment]
I tested out the changes you suggested and the compile errors are gone, however I'm still getting that same output in my playground. I'm seeing in [this example](https://github.com/async-graphql/examples/tree/0c175213d4df3f401cbf11dc89d5e0ca9fa923cf/poem/token-from-header) there is a `on_connection_init` callback and this example seems to return what I was expecting. Perhaps I'm handling my auth in an incompatible way or I'm needing to pass along more data to `ws`, like DB pool so I can validate in `on_connection_init`. Here's what I'm trying to do:

- Block all access to the graphql API without a valid token
- Query a 3rd party tool and my database to verify the token and user/account

I'm going to play around with this example to see if I can pass along my db pool or connection and validate the token from within the `on_connection_init` fn. Otherwise I may need to just use `FieldGuard` everywhere 🤔

**Comment by onx2** [comment]
I'm not seeing a way to use `on_connection_init` with data that can't be serialized because it accepts `Value` which requires `Deserialize` and I don't think I'll be able to `Deserialize` a DB pool.

I also switched over to `graphiql` which gives me a different response using your original suggestion but it still doesn't seem to response with my `String` message 🤔 
<img width="288" alt="image" src="https://user-images.githubusercontent.com/23039725/191401035-11dbffdf-0893-4ced-8e8c-1c07c8d236fc.png">
However, the status code is in fact correct:
<img width="681" alt="image" src="https://user-images.githubusercontent.com/23039725/191401190-5aa092dc-aa25-4dd0-b33a-63e0f0505776.png">

**Comment by sunli829** [comment]
You should pass `dbpool` to `on_connection_init` with a closure.

```rust
   let dbpool = dbpool.clone();
   websocket
        .protocols(ALL_WEBSOCKET_PROTOCOLS)
        .on_upgrade(move |stream| {
            GraphQLWebSocket::new(stream, schema, protocol)
                .with_data(data)
                .on_connection_init(move |value: serde_json| {
                     #[derive(Deserialize)]
                         struct Payload {
                         token: String,
                     }

                    if let Ok(payload) = serde_json::from_value::<Payload>(value) {
                         let conn = dbpool.take_a_connection();
                         let user_id = check_the_token(conn, payload.token)?;
                         let mut data = Data::default();
                         data.insert(UserId(user_id));
                         Ok(data )
                    } else {
                        Err("token is required".into())
                    }
                })
                .serve()
        })
```

**Comment by onx2** [comment]
Great thank you - I think we can consider this one closed. 

My queries and mutations will return this if unauthorized
<img width="338" alt="image" src="https://user-images.githubusercontent.com/23039725/191558315-23d0ffe7-967d-464d-86d6-b3cbb5975e75.png">

and my subscriptions will return this
<img width="656" alt="image" src="https://user-images.githubusercontent.com/23039725/191558417-1f714430-16b8-4b87-bb1e-741e754994b7.png">

Thank you for the help debugging / fixing my problem 😄

**Comment by onx2** [comment]
For anyone interested in the full handler code I'm using:

```rust
#[handler]
pub async fn ws(
    schema: Data<&RealSchema>,
    db: Data<&Db>,
    headers: &HeaderMap,
    protocol: GraphQLProtocol,
    websocket: WebSocket,
) -> poem::Result<impl IntoResponse> {
    let token = token_from_headers(headers);

    let schema = schema.0.clone();
    let mut data = async_graphql::Data::default();
    data.insert(token);

    let db = db.clone();
    Ok(websocket
        .protocols(ALL_WEBSOCKET_PROTOCOLS)
        .on_upgrade(move |stream| {
            GraphQLWebSocket::new(stream, schema, protocol)
                .with_data(data)
                .on_connection_init(move |value: serde_json::Value| async move {
                    #[derive(serde::Deserialize)]
                    struct Payload {
                        token: Option<Token>,
                    }

                    // Require the payload to exist with the correct shape
                    let payload = match serde_json::from_value::<Payload>(value) {
                        Ok(payload) => payload,
                        _ => return Err("Unauthorized".into()),
                    };

                    // Require a valid token to exist in the payload
                    match payload.token {
                        Some(token) => {
                            let mut conn = match db.connect() {
                                Ok(conn) => conn,
                                Err(_) => return Err("Internal Server Error".into()),
                            };

                            let auth = match Auth::build_from_token(&mut conn, token).await {
                                Ok(auth) => auth,
                                Err(err) => return Err(err.to_string().into()),
                            };

                            let mut data = async_graphql::Data::default();
                            data.insert(auth);
                            Ok(data)
                        }
                        _ => Err("Unauthorized".into()),
                    }
                })
                .serve()
        }))
}

```

**Comment by onx2** [comment]
@sunli829 I'm noticing that the `token_from_headers` part of this isn't required to get the value inside the `on_connection_init` callback.

```rust
let token = token_from_headers(headers);

let mut data = async_graphql::Data::default();
data.insert(token);
websocket
        .protocols(ALL_WEBSOCKET_PROTOCOLS)
        .on_upgrade(move |stream| {
            GraphQLWebSocket::new(stream, schema, protocol)
            // this doesn't seem to be nessary
            .with_data(data)
            .on_connection_init(move |value: serde_json::Value| async move { 
                // I can parse `value` here no problem and get the token from the header
             })
            .serve()
         })
```

I'm able to parse the value and it has the token from the headers by default. I was a bit confused to see that, is that expected?

**Comment by sunli829** [comment]
They are not the same:

**Get Token from request header**

```rust
let token = token_from_headers(headers);
```

**Get Token from [`CONNECTION_INIT`](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#connectioninit) request**

```rust
  .on_connection_init(move |value: serde_json::Value| async move {
      #[derive(serde::Deserialize)]
      struct Payload {
          token: Option<Token>,
      }

      // Require the payload to exist with the correct shape
      let payload = match serde_json::from_value::<Payload>(value) {
          Ok(payload) => payload,
          _ => return Err("Unauthorized".into()),
      };
}
```

**Comment by onx2** [comment]
I see, so should that part of the example be removed? The data from `token_from_headers` is always `None` in the websocket endpoint because the headers passed in from the client never show up in the `HeaderMap`. 

The headers that are passed in from the client only show up in the `on_connection_init` fn, but I'm not seeing anything in the docs that says this should be the case. Is that just a known part of the spec / expected behavior to have headers show up as data? 

```
interface ConnectionInitMessage {
  type: 'connection_init';
  payload?: Record<string, unknown>;
}
```

Are headers considered the `connectionParams`? If so, I'd like to add some more information to the docs to help others who aren't as familiar (like me 😅 ).

Maybe something that would be helpful is to call `value` in the example `connectionParams`. For example, in this [apollo doc](https://www.apollographql.com/docs/apollo-server/data/subscriptions/#onconnect-and-ondisconnect) it shows the `connection_init` fn extracting `connectionParams`

**Comment by sunli829** [comment]
Here is the code in the example:

It supports getting token from headers and ConnectionInit payload, which may be confusing you.

```rust
#[handler]
async fn ws(
    schema: Data<&TokenSchema>,
    headers: &HeaderMap,
    protocol: GraphQLProtocol,
    websocket: WebSocket,
) -> impl IntoResponse {
    // get token from header, this code can be removed if not needed.
    let mut data = async_graphql::Data::default();
    if let Some(token) = get_token_from_headers(headers) {
        data.insert(token);
    }

    let schema = schema.0.clone();
    websocket
        .protocols(ALL_WEBSOCKET_PROTOCOLS)
        .on_upgrade(move |stream| {
            GraphQLWebSocket::new(stream, schema, protocol)
                .with_data(data)
                .on_connection_init(on_connection_init)
                .serve()
        })
}
```

```rust
pub async fn on_connection_init(value: serde_json::Value) -> Result<Data> {
    #[derive(Deserialize)]
    struct Payload {
        token: String,
    }

    // get token from connectioninit payload
    if let Ok(payload) = serde_json::from_value::<Payload>(value) {
        let mut data = Data::default();
        data.insert(Token(payload.token));
        Ok(data)
    } else {
        Err("Token is required".into())
    }
}
```

----

Maybe this code should indeed be removed, if you'd like to open a PR to help 🙂

```rust
    let mut data = async_graphql::Data::default();
    if let Some(token) = get_token_from_headers(headers) {
        data.insert(token);
    }
```

**Comment by onx2** [comment]
Of course! I'll open a PR today. Can you please explain how to get the token from headers in the websocket endpoint? In my tests there was no way to retrieve it, it always came up as `None`. 🤔
