### ISSUE TITLE
How to use `requires` in nested entities

### ISSUE THREAD

**Issue by dbanty** [async-graphql/async-graphql#1076]
I'm having trouble figuring out how to get `external` fields to the spot that `requires` them when it's a nested entity.

For example, if I have this:

```rust
#[derive(SimpleObject)]
#[graphql(complex)]
pub(crate) struct Thing {
    pub(crate) id: ID,
}

#[ComplexObject]
impl Thing {
    async fn other_thing(&self) -> OtherThing {
        // Compiler error here—no name field
        OtherThing { id: self.id.clone() }
    }
}

#[derive(SimpleObject)]
#[graphql(complex)]
pub(crate) struct OtherThing {
    pub(crate) id: ID,
    #[graphql(external)]
    pub(crate) name: String,
}

#[ComplexObject]
impl OtherThing {
    #[graphql(requires = "name")]
    async fn nick_name(&self) -> String {
        self.name.chars().take(3).collect()
    }
}
```

How does `OtherThing::name` get populated when resolving the `Thing` entity? I seem to be able to use an argument to the entity resolver when resolving `OtherThing` directly:

```rust
#[graphql(entity)]
async fn other_thing_entity_by_id(&self, #[graphql(key)] id: ID, name: Option<String>) -> Option<OtherThing> {
    // I trust that this is set if it's needed
    let name = name.unwrap_or_default();
    if id == "1" {
        Some(OtherThing {
            id,
            name,
        })
    } else {
        None
    }
}
```

But if I have an entity resolver for `Thing`, I'm not sure how I get `name` injected down the line:

```rust
#[graphql(entity)]
// I guess I could put an argument here, but what do I do with it?
async fn thing_entity_by_id(&self, id: ID) -> Option<Thing> {
    if id == "1" {
        Some(Thing {
            id,
        })
    } else {
        None
    }
}
```

I made a [simple repo](https://github.com/dbanty/async-graphql-requires-test) with this same general setup for easier testing.

**Comment by sunli829** [comment]
Maybe `OtherThing` should be the same object corresponding to different services?

ServerA:

```rust
#[derive(SimpleObject)]
#[graphql(complex)]
pub(crate) struct Thing {
    pub(crate) id: ID,
}

#[ComplexObject]
impl Thing {
    async fn other_thing(&self) -> OtherThing1 {
        OtherThing1 { id: self.id.clone() }
    }
}

#[derive(SimpleObject)]
pub(crate) struct OtherThing {
    pub(crate) id: ID,
}
```

ServerB:

```rust
#[derive(SimpleObject)]
#[graphql(complex)]
pub(crate) struct OtherThing {
    pub(crate) id: ID,
    #[graphql(external)]
    pub(crate) name: String,
}

#[ComplexObject]
impl OtherThing {
    #[graphql(requires = "name")]
    async fn nick_name(&self) -> String {
        self.name.chars().take(3).collect()
    }
}
```

**Comment by dbanty** [comment]
So it turns out that it doesn't matter what the upper resolver does, the query plan for the router will re-enter the subgraph with the required field.

So basically, it'll call `thing_entity_by_id` to get whatever fields it needs from that top level (not the `other_thing` field). _Then_ it will call `other_thing_entity_by_id` with the required field to get those and stick them on the `Thing` it already gathered.

The Rust code ends up looking a little funny because you have to stick empty/default values in the `requires` fields when they aren't going to be used. But it does work!

This example was really bad—I'm trying to produce some examples of Federation which demonstrate all the features, so it'll make more sense when I contribute that back (if you want them) to the `examples` repo.

**Comment by sunli829** [comment]
> so it'll make more sense when I contribute that back (if you want them) to the examples repo.

I really want it, the existing federation example is not perfect enough. 😀
