### ISSUE TITLE
[FR] Can we check at compile-time if everything is correctly injected?

### ISSUE THREAD

**Issue by frederikhors** [async-graphql/async-graphql#1081]
Since in Rust community it is used to say that "if it compiles it works" I'm trying to understand if it's me or the below code is a danger.

```rust
//...

fn create_schema(services: Arc<Services>) -> GraphqlSchema {
    Schema::build(QueryRoot::default(), EmptyMutation, EmptySubscription)
        .data(services.starwars.clone())
        .data(services.users.clone())
        // .data(services.players.clone()) // I can forget to add this and the below code panics at run-time
        .data(services.games.clone())
        .data(services.coaches.clone())
        .data(services.nations.clone())
        .data(services.leagues.clone())
        .finish()
}

#[Object]
impl PlayerQueryRoot {
    async fn player_name(&self, ctx: &Context<'_>) -> Result<String> {
        let res = ctx.data_unchecked::<Arc<PlayerService>>();

        let player = res.queries.player_by_id.handle(1).await?;

        Ok(player.name)
    }
}
```

As the comment explain, if I forget to add `.data(services.players.clone())` the above code panics at runtime.

Even if I use `ctx.data()` method, **there is no check at compile-time**, right?

If this is a danger _and if I'm not doing anything wrong_, **can we find a way to check at compile-time if everything is correctly injected?**

**Comment by sunli829** [comment]
Similar to #904, generics can detect problems at compile time, but also introduce a lot of complexity.

**Comment by frederikhors** [comment]
I think we must have this.

Is there another way without creating a lot of complexity? Although sometimes complexity is the price to pay. And I don't mind paying for it if I get what I want and I'm sure the compiled is 100% correct.

**Comment by sunli829** [comment]
It's a trade-off, and it's not worth introducing a lot of complexity for an easy-to-find bug. 🙂

**Comment by frederikhors** [comment]
I respect that. Thanks for your answer.
