### ISSUE TITLE
Is there a way to save headers/variable between page loads in GraphIQL?

### ISSUE THREAD

**Issue by onx2** [async-graphql/async-graphql#1084]
The `graphql_playground` implementation does it already, but it seems that `graphiql` does not. Is that by design or is it something that can be added? Or is this something that I should ask in another repo?

I like the `graphiql` interface a bit more and it handles subscriptions in a cleaner way IMO so it would be nice to switch over 😄

**Comment by sunli829** [comment]
I just tried GraphiQL v2 and it seems to support this.

**Comment by onx2** [comment]
It doesn't seem to do that for me? 🤔 I ran that Starwars example locally and it isn't saving them either. I tested in Firefox and Safari.

The code I use in my handler (v4.0.13 of async-graphql):
```rust 
#[handler]
pub async fn graphiql() -> impl IntoResponse {
    dotenv().ok();

    let protocol = env::var("PROTOCOL").unwrap_or_else(|_| "https".to_string());
    let ws_protocol = env::var("WS_PROTOCOL").unwrap_or_else(|_| "wss".to_string());
    let hostname = env::var("HOSTNAME").unwrap_or_else(|_| "localhost".to_string());
    let port = env::var("PORT").unwrap_or_else(|_| "3000".to_string());

    let endpoint = format!("{protocol}://{hostname}:{port}");
    let subscription_endpoint = format!("{ws_protocol}://{hostname}:{port}/ws");

    Html(
        GraphiQLSource::build()
            .endpoint(&endpoint)
            .subscription_endpoint(&subscription_endpoint)
            .finish(),
    )
}
```

**Comment by onx2** [comment]
Maybe this is just me somehow. Should I close it as a "can't reproduce"?

I tried multiple browsers, the star wars example, and my own project with no luck. Not sure what it could be so maybe I'll just stick with the playground and try again another day.

**Comment by frederikhors** [comment]
GraphiQL 2 works good for me.

**Comment by onx2** [comment]
Hmm, maybe I'm doing something wrong then. Is there a specific way to use GraphiQL 2 vs 1 or a setting you are using?

**Comment by frederikhors** [comment]
I'm using the same code as https://github.com/async-graphql/async-graphql/issues/1084#issuecomment-1256990999. Windows 10. Chrome 105. Everything default. No strange configuration.

**Comment by onx2** [comment]
No idea what is happening then. I'll just close for now and use playground 🤷🏼
