### ISSUE TITLE
[BUG/FR with REPRO] APQ, handling correct GET requests with both Apollo and Urql

### ISSUE THREAD

**Issue by frederikhors** [async-graphql/async-graphql#1085]
Hi guys!

I think this is [the same problem](https://github.com/async-graphql/async-graphql/issues/808) that @bbigras had (but the Stale BOT closed it without a proper fix).

I created a small reproduction here: https://github.com/frederikhors/iss-async-graphql-apq-urql.git.

In it's README.md you can read:

### To start

- `cargo run`
- in another tab `cd web && npm install && npm run dev`

### Problem

If you open the browser (http://localhost:5000) in the console you can read the error:

```
start.js:312          GET http://localhost:8000/?variables=%7B%7D&extensions=%7B%22persistedQuery%22%3A%7B%22sha256Hash%22%3A%22cde5de0a350a19c59f8ddcd9646e5f260b2a7d5649ff6be8e63e9462934542c3%22%2C%22version%22%3A1%7D%7D 400 (Bad Request)
```

The backend response is:

```
Io(Custom { kind: Other, error: "failed to parse graphql request from uri query: invalid type: string \"{}\", expected a map" })
```

If I remove the line `persistedFetchExchange({ preferGetForPersistedQueries: true })` from `index.svelte` it works (because it's using the `POST` method now and not the Automatic persisted queries anymore).

### Proposal

I think we should fix this because both Apollo & Urql (so the 90% of web projects) use the same API/functioning.

**Practically today it is not possible to use this method with async-graphql at all.**

### Ref

- Urql docs page about it: https://formidable.com/open-source/urql/docs/api/persisted-fetch-exchange

Thank you very much for your work on this amazing project!

**Comment by frederikhors** [comment]
@bbigras if you have some news, please help us! Thanks! 😃

**Comment by sunli829** [comment]
This problem is due to `async-graphql-axum` not supporting getting parameters other than `query` from the query string.

**Comment by sunli829** [comment]
Fixed in `master` branch 🙂

**Comment by frederikhors** [comment]
Wow. It was fast! Can you release so I can try it?

Or how can I try the master branch?

**Comment by sunli829** [comment]
Yes,you can try it on master branch,I'll release it later.😄

**Comment by frederikhors** [comment]
> Yes,you can try it on master branch,I'll release it later.😄

I asked HOW I can try it. Not if. But I think I found how to.

**Comment by sunli829** [comment]
```toml
{
async-graphql = { git="https://github.com/async-graphql/async-graphql.git" }
async-graphql-axum= { git="https://github.com/async-graphql/async-graphql.git", branch="master" }
}
```

**Comment by frederikhors** [comment]
I tried. I get in my real project many errors. I'll try in the reproduction project right now.

**Comment by frederikhors** [comment]
The reproduction repo works with master branch!

https://github.com/frederikhors/iss-async-graphql-apq-urql/commit/943214929f7fb5218be2d3fddf65dae4621d738a

Thank you very much!

**Comment by frederikhors** [comment]
I look forward to a new release and now I am also trying to understand the problems I have on my real project with the master branch.

**Comment by frederikhors** [comment]
Are you going to release soon?
