### ISSUE TITLE
Support expressions for argument defaults

### ISSUE THREAD

**Issue by mwilliammyers** [async-graphql/async-graphql#109]
I know it would be a breaking change (I am 99% sure at least), but it would be great if argument defaults supported arbitrary expressions instead of fixed strings. 

Apart from allowing dynamic argument defaults etc. (see below for some use cases), it allows for a much more natural syntax; `arg(default = 20)` feels better than `arg(default = "20")`.

These expressions would be evaluated when a client runs the introspection query.

(my) use case:
I generate some of my queries/mutations with a macro and call a function in each module that returns the default sort argument for the given query.

It would also allow for doing things like using the current day/time as an argument etc.

**Comment by sunli829** [comment]
The default value of the string type is a last resort, 
but I will consider adding `#arg (default_with =" ... ")`. 😁

**Comment by mwilliammyers** [comment]
So would it allow:

```rust
#[arg(desc = "Some int arg.", default_with = 20)]
```
and:
```rust
#[arg(desc = "Some string arg.", default_with = "hello, world!")]
```
and even:
```rust
fn get_default_arg() -> i32 {
   20
}
```
```
#[arg(desc = "Some int arg.", default_with = get_default_arg())]
```

**Comment by sunli829** [comment]
Maybe we can be the same as serde.

**Comment by sunli829** [comment]
The generated code will parse the default value of the `String` into a `Value`, and will parse this `Value` into the required `InputType` again when querying.

If we want to support the default value type such as `i32`, we need to support the conversion of rust type to `Value` type, which is equivalent to we need to do the implementation of `OutputType` on `InputType` again, **just for a default value**, i don’t think it ’s worth it.

I can add expressions to the default values, but this function can only return `String` or `Value`.

```rust
fn get_default_arg() -> &str {
   "20"
}

// or
fn get_default_arg() -> Value {
   20.into()
}


#[arg(desc = "Some int arg.", default_with = "get_default_arg")]
```

**Comment by IcanDivideBy0** [comment]
My 2 cents: default arguments for a function should be a language feature. IMO the `default` should be completely removed from the macro args, it makes things unclear and introduce some complexity in async_graphql while it's easy enouth for anyone to `unwrap_or` an option.

It makes sense for serde to have this due to the versatility of the json format versus the strongly typed nature of Rust structs, but in serde the default arg is used on struct fields, not methods.

**Comment by sunli829** [comment]
I wonder if it makes sense to implement type-safe defaults.

**Comment by sunli829** [comment]
The disadvantage of using unwrap_or to implement the default value is that you cannot see it in introspection.

**Comment by sunli829** [comment]
Maybe I can support type-safe defaults, but to support introspection, I need to add an `InputValueType::to_json` function.

**Comment by sunli829** [comment]
```rust
#[InputObject]
#[derive(Default)]
struct MyInput {
    a: i32,
}

struct Query;

#[Object]
impl Query {
    fn test(&self,
        #[arg(default_with="MyInput::default")
        input: MyInput) -> bool { ... }

    fn test2(&self,
        #[arg(default="MyInput { a: 10 }")
        input: MyInput) -> bool { ... }
}
```

**Comment by IcanDivideBy0** [comment]
> The disadvantage of using unwrap_or to implement the default value is that you cannot see it in introspection.

wait, introspection contains default values ???

**Comment by mwilliammyers** [comment]
While I agree with the sentiment, if clients are actually consuming an API, they *must* be able to view the default arguments in the docs etc. (via introspection), otherwise it could lead to some very unexpected behavior.

**Comment by sunli829** [comment]
How does this feel? @IcanDivideBy0  @mwilliammyers

**Comment by sunli829** [comment]
> > The disadvantage of using unwrap_or to implement the default value is that you cannot see it in introspection.
> 
> wait, introspection contains default values ???

Yes. 😂

**Comment by IcanDivideBy0** [comment]
Oooh, that make sense now :D

**Comment by mwilliammyers** [comment]
@sunli829 can you support expressions/raw tokens instead of strings?

**Comment by mwilliammyers** [comment]
something like this:

```rust
#[InputObject]
#[derive(Default)]
struct MyInput {
    a: i32,
}

struct Query;

#[Object]
impl Query {
    fn test(&self,
        #[arg(default)]
        input: MyInput) -> bool { ... }

    fn test2(&self,
        #[arg(default= MyInput { a: 10 })
        input: MyInput) -> bool { ... }
}
```

**Comment by sunli829** [comment]
This is not rust's standard syntax and cannot be formatted with rustfmt, which is unacceptable. 🙁

```rust
 fn test2(&self,
        #[arg(default= MyInput { a: 10 })
        input: MyInput) -> bool { ... }
```

**Comment by mwilliammyers** [comment]
I have never tried structs but rustfmt handles other raw tokens just fine... I use some other libraries that do it that way (https://github.com/idanarye/rust-typed-builder comes to mind)

**Comment by sunli829** [comment]
```rust
#[InputObject]
struct MyInput {
    a: i32,
}

#[Object]
impl Query {
    fn test1(&self, #arg(default = 10) a: i32) -> bool { ... }

    fn test2(&self, #arg(default = "abc") a: String) -> bool { ... }

    fn test2(&self, #arg(default_with = "MyInput::default") input: MyInput) -> bool { ... }
}
```

**Comment by mwilliammyers** [comment]
What about:
```
#[InputObject]
#[derive(Default)]
struct MyInput {
    a: i32,
}

#[Object]
impl Query {
    fn test1(&self, #arg(default = 10) a: i32) -> bool { ... }

    fn test2(&self, #arg(default = "abc") a: String) -> bool { ... }

    fn test2(&self, #arg(default_with = "MyInput::default") input: MyInput) -> bool { ... }

   fn test_default(&self, #arg(default) input: MyInput) -> bool { ... }
}
```

**Comment by mwilliammyers** [comment]
To be clear, it's actually `#[arg(default = "abc")]` etc., right?

**Comment by sunli829** [comment]
> What about:
> 
> ```rust
> #[InputObject]
> #[derive(Default)]
> struct MyInput {
>     a: i32,
> }
> 
> #[Object]
> impl Query {
>     fn test1(&self, #arg(default = 10) a: i32) -> bool { ... }
> 
>     fn test2(&self, #arg(default = "abc") a: String) -> bool { ... }
> 
>     fn test2(&self, #arg(default_with = "MyInput::default") input: MyInput) -> bool { ... }
> 
>     fn test_default(&self, #arg(default) input: MyInput) -> bool { ... }
> }
> ```
> 
> (same thing but support `#arg(default)`)

This can be done without compromising rustfmt while also having type safety.

**Comment by mwilliammyers** [comment]
Would that also work with free-standing functions?

```rust

fn my_input_default() -> Vec<MyInput> {
    vec![MyInput { a: 1 }, MyInput { a: 2 }]
}

#[Object]
impl Query {
    
    fn test_fn(&self, #[arg(default_with = "my_input_default' )] input: Vec<MyInput>) -> bool { ... }
}
```

**Comment by sunli829** [comment]
> Would that also work with free-standing functions?
> 
> ```rust
> fn my_input_default() -> Vec<MyInput> {
>     vec![MyInput { a: 1 }, MyInput { a: 2 }]
> }
> 
> #[Object]
> impl Query {
>     fn test_fn(&self, #[arg(default_with = "my_input_default" )] input: Vec<MyInput>) -> bool { ... }
> }
> ```

Yes.

**Comment by mwilliammyers** [comment]
Awesome! You have been very quick to respond and even implement features!

Thanks!

Exciting project!

**Comment by sunli829** [comment]
I'm going to do this now, and I think type-safe defaults are important. 😁

**Comment by sunli829** [comment]
I created a new issue. #111

**Comment by sunli829** [comment]
Async-graphql 1.13.3 already includes this change.
