### ISSUE TITLE
Panic: connections have the same GraphQL name

### ISSUE THREAD

**Issue by ClementNerma** [async-graphql/async-graphql#1090]
Here is an error I got today while trying to compile my app:

```
thread 'main' panicked at '

`async_graphql::types::connection::connection_type::Connection<usize, hify_server::index::data::Track>` and
`async_graphql::types::connection::connection_type::Connection<hify_server::index::data::TrackID, hify_server::index::data::Track>`
have the same GraphQL name `TrackConnection`

', /home/clement/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-4.0.13/src/registry/mod.rs:489:25
```

Which, with types simplified, gives the following panic message:

```
`Connection<usize, Track>` and `Connection<TrackID, Track>` have the same GraphQL name `TrackConnection`
```

It seems like having two connections with the same value type but different cursor types leads to a crash.

Is there any workaround for this problem?

Thanks in advance for your help!

**Comment by sunli829** [comment]
Not a bug, this panic is intentional. `async_graphql::types::connection::connection_type::Connection<usize, hify_server::index::data::Track>` and `async_graphql::types::connection::connection_type::Connection<hify_server::index: :data::TrackID, hify_server::index::data::Track>` have the same name `TrackConnection`, which is not legal because they are actually two different types, you should give them different names , like this:

https://github.com/async-graphql/async-graphql/blob/974f8ff21d9019bde138f11c4eb5b1aeae554aa0/src/types/connection/mod.rs#L139

**Comment by sunli829** [comment]
Your usage is wrong, it should be like this:

```rust
struct YourConnectionName;

impl ConnectionNameType for YourConnectionName{
    fn type_name<T: OutputType>() -> String {
        "YourConnection".to_string()
    }
}

type YourConnection = Connection<usize, MyObj, EmptyFields, EmptyFields, MyConnectionName>;
```

**Comment by ClementNerma** [comment]
Oh, I see.

The problem is that I use a generic pagination function to generate connections, wrapped in a `Result`. So I can't make a struct for a specific connection.

Is there another way to workaround this?

**Comment by sunli829** [comment]
Let me take a look at your code.

**Comment by ClementNerma** [comment]
Here you go: https://github.com/ClementNerma/Hify/blob/main/hify-server/src/graphql/pagination.rs

**Comment by sunli829** [comment]
You can add a generic parameter `N` to `raw_paginate` and pass it to `Connection::new`

```rust
pub fn raw_paginate<C: CursorType + Send + Sync, T, U: OutputType, N: ConnectionNameType>
```

**Comment by ClementNerma** [comment]
Just came across this issue again, the solution was indeed to do this, but also to add a custom edge name (otherwise edge names clashed too).

Which gives something like:

``rust
pub type Paginated<C, T, N = DefaultConnectionName, E = DefaultEdgeName> =
    Result<Connection<C, T, EmptyFields, EmptyFields, N, E, EnableNodesField>>;
```

Thanks for your help!
