### ISSUE TITLE
Connection refused when calling GraphQL endpoint (actix-web)

### ISSUE THREAD

**Issue by enheit** [async-graphql/async-graphql#1114]
I'm not sure if this issue is related to async_graphql but I hope you can point me in the right direction.

I have a async_graphql + actix-web server.

The initialization looks like this (taken from example folder of async_graphql)

```rust
#[actix_web::main]
async fn main() -> Result<(), std::io::Error> {
    dotenv().ok(); // Loads .env file into memory

    let client = initialize_connection().await; // database connection

    let schema = Schema::build(Query::default(), Mutation::default(), EmptySubscription)
        .register_output_type::<ExpectedError>()
        .data(client)
        .finish();

    HttpServer::new(move || {
        App::new()
            .app_data(Data::new(schema.clone()))
            .service(web::resource("/").guard(guard::Post()).to(index))
            .service(web::resource("/").guard(guard::Get()).to(index_playground))
    })
    .bind(("127.0.0.1", 8080))?
    .run()
    .await
}
```

Whenever I try to call `http://localhost:8080` e.g. from https://studio.apollographql.com/ or using `diagnose-endpoint` it shows me an error

![Screenshot 2022-10-22 at 21 03 14](https://user-images.githubusercontent.com/8645216/197355906-2f39feb9-1bf4-4718-97bc-faea36adedaa.png)

```
Last login: Sat Oct 22 20:22:00 on ttys003
➜  ~ npx diagnose-endpoint@1.1.0 --endpoint=http://localhost:8080/
Diagnosing http://localhost:8080/
⚠️  Connection refused (ECONNREFUSED)
Is the address correct?
Is the server running?
➜  ~
```

Did I miss something that needed to be added to my server configuration? 

P.S. GraphQL Playground (aka http://localhost:8080/graphql) works as expected. I am also able to use Postman to send a POST request to http://localhost:8080/ with GraphQL body for schema introspection

**Comment by sunli829** [comment]
@dbanty any suggestions? 🙂

**Comment by enheit** [comment]
Thank you guys, the problem was with CORS. I opened console during the executing query from apollo studio and it showe me the `CORS error`.

Following @dbanty recommendation I relaxed CORS rules and it now looks like this:

```rust
fn main() {
// cut
    HttpServer::new(move || {
        let cors = Cors::permissive();

        App::new()
            .wrap(cors)
            .app_data(Data::new(schema.clone()))
            .service(web::resource("/").guard(guard::Post()).to(index))
            .service(web::resource("/").guard(guard::Get()).to(index_playground))
// cut
}
```

Also, [this question](https://stackoverflow.com/questions/59351973/how-do-i-configure-actix-web-to-accept-cors-requests-from-any-origin) on StackOverflow helped me to find the `Cors::permissive()` options which is "a wildcard" for all origins. Please note, that this option [is not recommended for production usage](https://docs.rs/actix-cors/latest/actix_cors/struct.Cors.html#method.permissive).

I'm also closing this question as the issue is mostly resolved.

**Comment by dbanty** [comment]
Just for completeness, this seems to be the minimally permissive CORS settings to get sandbox working (written for Axum, I'm sure can be translated to all the other frameworks):

```rust
let cors = CorsLayer::new()
        .allow_methods([Method::POST])
        .allow_headers([CONTENT_TYPE])
        .allow_origin(
            "https://studio.apollographql.com"
                .parse::<HeaderValue>()
                .expect("Can enable sandbox CORS"),
        );
```
