### ISSUE TITLE
Interface fields name camelCasing

### ISSUE THREAD

**Issue by Amareis** [async-graphql/async-graphql#112]
```rust
#[Object]
impl PMChat {
    #[field(name = "created_at")]
    pub async fn created_at(&self) -> &String {
        &self.data.created_at
    }
}

#[Object]
impl Chat {
    #[field(name = "created_at")]
    pub async fn created_at(&self) -> &String {
        &self.data.created_at
    }
}

#[Interface(
    field(name = "created_at", type = "&String"),
)]
pub enum IChat {
    PMChat(PMChat),
    Chat(Chat),
}
```

And in resulting scheme interface field became camelCased:
```
interface IChat {
  createdAt: String!
}
```

There is no any compilation error nor way to disable name transformation.

**Comment by Amareis** [comment]
I think interface fields should not be transformed, since it's already strings, so if I want to make it camelCased, I can just wrote it. Or maybe add different argument to `field` attribute for disabling it.

**Comment by sunli829** [comment]
Let me think about how to solve it.

**Comment by sunli829** [comment]
I'll add an alias field, because the interface query is forwarded via name and must be the same as the function name of the corresponding instance.

I'll do it tomorrow. I'm ready for bed now. 😊

**Comment by Amareis** [comment]
May be also add disabling name mangling as a crate feature? I think it will be handy for projects with snake_case naming.

**Comment by sunli829** [comment]
Async-graphql 1.13.3 already includes this change.

**Comment by sunli829** [comment]
Here is the test code:

https://github.com/async-graphql/async-graphql/blob/afb2061392f5f54568a06ba464ac02593af08ee4/tests/interface.rs#L280

**Comment by Amareis** [comment]
> Async-graphql 1.13.3 already includes this change.

Oh, you really awesome! Thanks you! I'll test it now.

**Comment by Amareis** [comment]
Yep, it works. Maybe it should be mirrored in docs?

**Comment by sunli829** [comment]
Can you help update the book? I will translate it into Chinese later. 😁

**Comment by Amareis** [comment]
> Can you help update the book? I will translate it into Chinese later.

Ok, I can, but later. Currently I try to check performance of different server libraries for our production app. Can I contact you at email to discuss some questions about it?

**Comment by sunli829** [comment]
> > Can you help update the book? I will translate it into Chinese later.
> 
> Ok, I can, but later. Currently I try to check performance of different server libraries for our production app. Can I contact you at email to discuss some questions about it?

Yes.

**Comment by Amareis** [comment]
Added docs, PR in proccess.

BTW, `method` name is someway confusing, I think, may be in future it should be swapped? `method` is rust method name and `name` is "graphql" name, for consistency with `Object` fields.

**Comment by sunli829** [comment]
- When the `name` and `method` exist together, the `name` is the `graphql name` and the `method` is the `rust method name`.

- When only `name` exists, `name.to_camel_case()` is the `graphql name` and the `name` is the `rust method name`.

**Comment by Amareis** [comment]
Yep, that's really confusing :) May be there is better solution for 2.0, but currently I just update the docs.

**Comment by Venryx** [comment]
> May be also add disabling name mangling as a crate feature? I think it will be handy for projects with snake_case naming.

Any update on this, ie. a crate-wide way to disable name mangling/camel-casing?

If not, that's okay (there's the workaround of using `#[graphql(name = "dont_camel_case_me")]`), but just making sure I didn't miss it if it exists. (since my GraphQL api would preferably not use camel-casing for anything)
