### ISSUE TITLE
Compilation trouble with StringMinLength validator

### ISSUE THREAD

**Issue by kevinschoonover** [async-graphql/async-graphql#113]
I have been messing around with the `StringMinLength` validator and have been having compilation errors using the `warp-starwars` example. I changed just a random `#[field()]` macro to include validators and saw the following compilation error:
```
error: Value must be string literal
   --> models/starwars/src/model.rs:110:76
    |
110 |         #[arg(desc = "id of the human", validator(StringMinLength(length = 6)))] id: String,
```

I attempt to change it to a string to appease the compiler and see:
```
error[E0277]: the trait bound `usize: std::convert::From<i32>` is not satisfied
  --> models/starwars/src/model.rs:90:1
   |
90 | #[async_graphql::Object]
   | ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::convert::From<i32>` is not implemented for `usize`
   |
   = help: the following implementations were found:
             <usize as std::convert::From<bool>>
             <usize as std::convert::From<std::num::NonZeroUsize>>
             <usize as std::convert::From<u16>>
             <usize as std::convert::From<u8>>
   = note: required because of the requirements on the impl of `std::convert::Into<usize>` for `i32`
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

I tried the example validator from [the documentation](https://async-graphql.github.io/async-graphql/en/input_value_validators.html) and that does work so I am confused if it is something that I am doing wrong. The syntax is based on #11.

Please let me know if you need any more information or a more concrete example.

**Comment by nicolaiunrein** [comment]
Have you tried to pass in the arguments as strin literals? like `StringMinLength(length = "6")`. I am on mobile phone right now and can’t test but that is what your error is saying 😆 and what’s done in the documentation.

**Comment by kevinschoonover** [comment]
The second error is my attempt at making it a string literal using the follow line of code:
```
#[arg(desc = "id of the human", validator(StringMinLength(length = "6")))] id: String,
```

I also just copy and pasted the suggested line and got the same error.

**Comment by sunli829** [comment]
This is a bug, and I am solving it.

**Comment by sunli829** [comment]
This is a bug, and I'm working on it.
Changing the parameter 6 to 6usize can be compiled, and the next version will remove this restriction.

```rust
#[arg(desc = "id of the human", validator(StringMinLength(length = "6usize")))] id: String,
```

**Comment by kevinschoonover** [comment]
Perfect, thank you so much! If there is some code I can contribute such as extra tests please let me know.

**Comment by sunli829** [comment]
There are no available tests for InputValidators, which is why this bug has not been discovered. It would be great if you could help add some!

Add these tests here:
https://github.com/async-graphql/async-graphql/blob/master/tests/input_validators.rs

Thank you very much! 😁

**Comment by kevinschoonover** [comment]
I'll try to take a look at it this week. How in-depth are you hoping?

**Comment by sunli829** [comment]
I want to be able to test each validator to see if it works. 😁

**Comment by sunli829** [comment]
The input value validator can be applied to object field parameters, interface field parameters, and input objects.

**Comment by sunli829** [comment]
Async-graphql 1.13.3 already includes this change.

**Comment by kevinschoonover** [comment]
Can an interface be an input value for a Query/Mutation? I have some basic tests for StringMinLength running on my fork and I am struggling conceptually with how to test the Interface.

What I have set up looks like:
```rust
struct Interface {
  pub name: String,
};

#[Object]
impl Interface {
    async fn id(&self) -> String {
        "Test".to_string()
    }
}

#[Interface(field(name = "id", type = "String"))]
enum InterfaceValidator {
    TestInterface(Interface),
} 

#[Object]
impl QueryRoot {
    async fn interface_validator(&self, _input: InterfaceValidator) -> bool {
        true
    }
}                                  
```

which returns the error:
```
error[E0277]: the trait bound `test_string_min_length::{{closure}}#0::InterfaceValidator: async_graphql::base::InputValueType` is not satisfied
  --> tests/input_validators.rs:29:5
   |
29 |     #[Object]
   |     ^^^^^^^^^ the trait `async_graphql::base::InputValueType` is not implemented for `test_string_min_length::{{closure}}#0::InterfaceValidator`
   |
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

When you get the chance, can you give me some pointers on how to go about testing this particular aspect or if it is testable from this angle?

**Comment by phated** [comment]
@kevinschoonover funny you ask that. I was just discussing with another person writing a blog post about interfaces and he pointed out that interfaces are not allowed to exist on Input types in graphql.

**Comment by sunli829** [comment]
This is how the interface field parameter validator is defined.

```rust
#[Interface(field(name = "id", type = "String", validators(...)))]
enum InterfaceValidator {
    TestInterface(Interface),
} 
```
