### ISSUE TITLE
How to (de)serialize `ExecutableDocument`?

### ISSUE THREAD

**Issue by rieval** [async-graphql/async-graphql#1138]
[related issue](https://github.com/async-graphql/async-graphql/issues/919)

I want to be able to (de)serialize `ExecutableDocument` using [`serde_json`](https://docs.rs/serde_json/latest/serde_json/index.html) or [`bincode`](https://docs.rs/bincode/latest/bincode/index.html).

example:
```rust
// doc: ExecutableDocument

// serde_json
match serde_json::to_string(&doc) {
    // data: String
    Ok(data) => {
        println!("OK: {:?}", data);
    }
    Err(e) => println!("Err: {:?}", e),
}

// bincode
match bincode::serialize(&doc) {
    // data: Vec<u8>
    Ok(data) => {
        println!("OK: {:?}", data);
    }
    Err(e) => println!("Err: {:?}", e),
}
```

result:
```
Err: cannot serialize variable
```

**Comment by sunli829** [comment]
Fixed in `master` branch 🙂

**Comment by rieval** [comment]
> Fixed in `master` branch 🙂

Great works!
