### ISSUE TITLE
If using a managed supergraph how to publish

### ISSUE THREAD

**Issue by softeng71** [async-graphql/async-graphql#1143]
Sorry for what may be a dumb question.  
I am coming from a NodeJS background and am starting to very much get into doing everything with Rust.
However since the schema is code and not graphql files. 
Is it possible to publish using Rover (or another tool) the schema for a subgraph?
If so can you please advise as to how to accomplish this?

**Comment by vamshiaruru-virgodesigns** [comment]
you can use rover to introspect your graph and publish.  Something like 
```
rover graph introspect http://example.com/graphql
```
will give you the SDL of the graph.
