### ISSUE TITLE
Question: Implement multiple data types

### ISSUE THREAD

**Issue by ajosecueto** [async-graphql/async-graphql#1146]
In the async graphql book have a incomplete example of how to [Implement multiple data types](https://async-graphql.github.io/async-graphql/en/dataloader.html#implement-multiple-data-types)

struct PostgresLoader {
    pool: sqlx::Pool<Postgres>,
}

#[async_trait::async_trait]
impl Loader<UserId> for PostgresLoader {
    type Value = User;
    type Error = Arc<sqlx::Error>;

    async fn load(&self, keys: &[UserId]) -> Result<HashMap<UserId, Self::Value>, Self::Error> {
        // Load users from database
    }
}

#[async_trait::async_trait]
impl Loader<TodoId> for PostgresLoader {
    type Value = Todo;
    type Error = sqlx::Error;

    async fn load(&self, keys: &[TodoId]) -> Result<HashMap<TodoId, Self::Value>, Self::Error> {
        // Load todos from database
    }
}

What kind of type are TodoId and UserID ? 

Thanks

**Comment by sunli829** [comment]
The `Loader trait` has a generic parameter which is the type of the key.

```rust
#[async_trait::async_trait]
impl Loader<UserId> for PostgresLoader {
    type Value = User;
}

impl Loader<TodoId> for PostgresLoader {
    type Value = Todo;
}
```

**Comment by ajosecueto** [comment]
Thanks
