### ISSUE TITLE
Add description to enum fields in `export_sdl`

### ISSUE THREAD

**Issue by ValentinChouaf** [async-graphql/async-graphql#1147]
## Description of the feature

Have enum values' `description` field to appear when exporting the schema as a definition file. 

## Location

See https://github.com/async-graphql/async-graphql/blob/master/src/registry/export_sdl.rs#L393

---
Let me know if you want me to write a PR! Thanks in advance. :smile:

**Comment by sunli829** [comment]
Thank you, but this issue seems to be fixed in #1131 🙂

**Comment by ValentinChouaf** [comment]
Oh, sorry, I searched among issues but not PRs. Thanks a lot! :tada:
