### ISSUE TITLE
Allow to differentiate between null and undefined

### ISSUE THREAD

**Issue by IcanDivideBy0** [async-graphql/async-graphql#115]
Let's say I have a task object with an optional deadline
```rust
struct Task {
    text: String,
    deadline: Option<DateTime<Utc>>
}
```

Currently with my JS server I can update the task with some mutation:
```gql
mutation m1($id: ID!, $text: String!, $deadline: DateTime) {
  UpdateTask(id: $id, text: $text, deadline: $deadline ) {
    id
    text
    deadline
  }
}
```

The gql variable `$deadline` can takes 3 different types of values:
* a Date, which update the deadline
* `undefined`, which do not modify the deadline
* `null`, which clears the deadline

I can't find  a way to reproduce this with async_graphql, does anyone have an idea on how to handle this?

**Comment by sunli829** [comment]
`Option<Option<DateTime>>`, is this ok? 😁

**Comment by mwilliammyers** [comment]
Just to be clear:
- `None` -> `undefined`
- `Some(None)` -> `null`
- `Some(Some(x))` -> `x`

How would this look in graphql? Just an optional `DateTime`?

**Comment by phated** [comment]
Does graphql actually allow undefined? I vaguely remember only seeing null in the spec.

**Comment by mwilliammyers** [comment]
Don’t think so, http://spec.graphql.org/June2018/#sec-Value-Completion, but I know at least the Apollo Client/Server (in JS/node/TS) differentiate between null and undefined...

**Comment by sunli829** [comment]
I was wrong. Graphql doesn't support this type.😂

**Comment by mwilliammyers** [comment]
Waiiit a second, that won’t work because if a client passes `null` serde will treat that as `None` for the outer `Option`, which means `undefined` in our case, but we want it to mean `Some(None)` (null)

**Comment by sunli829** [comment]
I think this can only add one parameter.

**Comment by sunli829** [comment]
I'm thinking about adding something like this.

https://gqlgen.com/reference/changesets/

**Comment by phated** [comment]
@sunli829 I'm not sure I understand why you would use "changesets"

I wonder if @IcanDivideBy0's mutation is just too generic. My gut feeling here would be that `setDeadline` should be a separate mutation than `updateTaskTitle`, but I'm unsure.

**Comment by nicolaiunrein** [comment]
maybe one could construct something with `#[serde(deny_unknown_fields)]`

**Comment by sunli829** [comment]
The first field `value1` is nested `Option`, so I can handle `undefined`, how does this look?

# Input object definition

```rust
    #[InputObject]
    struct A {
        value1: Option<Option<i32>>,
        value2: i32,
        value3: Option<i32>,
    }
```

# GraphQL query

```GraphQL
{
    # value1 is Some(Some(1))
    t(input: { value1:1 })

    # value1 is Some(None)
    t(input: { value1:null })

    # value1 is None
    t(input: { value2: 10 })
}
```

**Comment by phated** [comment]
I don't like that. If you want to support `undefined` even though the spec doesn't allow it, I think we should add a new type that must be used.

**Comment by sunli829** [comment]
Let's add a `MaybeUndefined<T>` type?

**Comment by sunli829** [comment]
The current implementation does not conflict with `StreamDataSource` and can be easily added again. @IcanDivideBy0

**Comment by sunli829** [comment]
It's a big change, but it's not a breaking change.

**Comment by sunli829** [comment]
I finished this. 😁

https://github.com/async-graphql/async-graphql/blob/8afe5427e109f9987ed9ed0ab40024777e461165/tests/maybe_undefined.rs#L4
