### ISSUE TITLE
Dynamic ValueAccessor needs a bool method

### ISSUE THREAD

**Issue by Bjohnson131** [async-graphql/async-graphql#1152]
## Description of the feature
https://github.com/async-graphql/async-graphql/blob/bc4dfb503f36ca5a3d244b0346afaf0268e13a26/src/dynamic/value_accessor.rs

currently, Value Accessor has a large number of accessors, but bool values are excluded

## Code example (if possible)
```


    /// Returns the bool value
    pub fn bool(&self) -> Result<bool> {
        if let Value::Boolean(value) = self.0 {
            return Ok(*value);
        }
        Err(Error::new("internal: not a bool"))
    }
```

**Comment by sunli829** [comment]
Released in `5.0.1` thanks @spiegela
