### ISSUE TITLE
Flatten attribute doesn't compose well when flattening type with same name

### ISSUE THREAD

**Issue by DoumanAsh** [async-graphql/async-graphql#1154]
When attempting to flatten field of `SimpleObject` that has the same name as your wrapper object, SDL schema generator doesn't embed fields inside.

E.g.

```
#[derive(SimpleObject)]
pub struct Config {
    whatever: String
}

#[derive(SimpleObject)]
#[graphql(name = "Config")]
pub struct Wrapper {
    id: i64
    config: Config
}
```

Results in 
```
type Config {
  Id: Int
}
```

But if you remove or change name of wrapper to anything else, it will properly embed fields in schema.

I understand it might be inherent limitation, but let me know if it is actually bug.

**Comment by sunli829** [comment]
Don't let them have the same name, this problem is very difficult to solve. 😂

**Comment by DoumanAsh** [comment]
yeah, I would like to have the same name so that the same code could be used in both endpoints...
I suppose I will write my own proc macro to generate wrapper code then
