### ISSUE TITLE
Federation doesn't work

### ISSUE THREAD

**Issue by rkudryashov** [async-graphql/async-graphql#116]
In the latest versions `_service.sdl` can not be queried:

<img width="757" alt="1" src="https://user-images.githubusercontent.com/37952224/82998756-c730b380-a010-11ea-97ed-2ab935274321.png">

Repro-project: https://github.com/rkudryashov/async-graphql-reproducer

**Comment by sunli829** [comment]
Just a moment, I'm looking.

**Comment by sunli829** [comment]
Please upgrade to `1.13.5`.

The custom scalar definition has changed and needs to be modified as follows.

```rust
#[Scalar(name = "Decimal")]
impl ScalarType for CustomDecimal {
    fn parse(value: Value) -> InputValueResult<Self> {
        unimplemented!()
    }

    fn to_value(&self) -> Value {
        Value::String(self.0.to_string())
    }
}
```

**Comment by rkudryashov** [comment]
Thanks, after version upgrade I was exactly looking for how to do it
