### ISSUE TITLE
Build error instead of runtime if two `Object` have the same name

### ISSUE THREAD

**Issue by skhalymon** [async-graphql/async-graphql#1162]
## Description of the feature
It would be great to have build time error instead of runtime, while we have structs with same name marked with `Object` macro. 

Currently, we have the following panic when try to run app with issue:
```
thread 'main' panicked at '`types::Profile` and `mutation_types::Profile` have the same GraphQL name `Profile`', .cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-4.0.16/src/registry/mod.rs:666:25
``` 

But the right behavior should be to fail on build time if there is duplication.

**Comment by sunli829** [comment]
This error cannot be reported at build time.
