### ISSUE TITLE
Disable introspection, returns null in __typename

### ISSUE THREAD

**Issue by negezor** [async-graphql/async-graphql#1163]
## Expected Behavior

Unable to introspect schema with __typename working

```json
{
  "data": {
    "user": {
      "avatar": {
        "__typename": "Image"
      },
      "__typename": "User"
    }
  }
}
```

## Actual Behavior

Field __typename return null

```json
{
  "data": {
    "user": {
      "avatar": {
        "__typename": null
      },
      "__typename": null
    }
  },
}
```

## Steps to Reproduce the Problem

1. Use `schema.disable_suggestions()`
2. Do request with `__typename`

## Specifications

- Version: 5.0.2
- Platform: Windows
- Subsystem: Arch WSL

**Comment by sunli829** [comment]
Fixed in `v5.0.3`
