### ISSUE TITLE
Breaking change (semver adherance) policy?

### ISSUE THREAD

**Issue by mwilliammyers** [async-graphql/async-graphql#117]
It seems like breaking changes are being released and the crate is `>1.0.0`.

I am totally fine with breaking changes (and really appreciate the fast paced work and feature releases) but in accordance with [semantic versioning](https://semver.org/) (which the Rust community abides by), there should never be any breaking changes without a major version bump.

I am not entirely sure what to do about it, but in my opinion this crate is not at a stable point. I might even suggest doing something as drastic as yanking all versions over `1.0.0` on crates.io...

I understand what constitutes a breaking change is pretty hard to define, but I would consider the following occurring to be a breaking change:
1. Compile code **successfully**
1. **Bump** version of a library
1. **Not** change your code 
1. Compile code with **errors**

<br>
<br>

Here is an example of a breaking change (that was released in a patch release):

> The custom scalar definition has changed and needs to be modified as follows.

```rust
#[Scalar(name = "Decimal")]
impl ScalarType for CustomDecimal {
    fn parse(value: Value) -> InputValueResult<Self> {
        unimplemented!()
    }

    fn to_value(&self) -> Value {
        Value::String(self.0.to_string())
    }
}
```

_Originally posted by @sunli829 in https://github.com/async-graphql/async-graphql/issues/116#issuecomment-634575214_

**Comment by phated** [comment]
You are correct that this project doesn't currently abide by semver. I was just having this discussion with a friend that wants to use the project, but is uncomfortable that it doesn't version that way.

I don't think we need to yank versions, but we should add a big disclaimer to the README and documentation that <2.0.0 is unstable and that we will adopt semver after 2.0.0

This project got very popular, very quickly, and we are just trying to adapt to that popularity; however, I don't think we should enforce anything that breaks the amazing productivity of @sunli829.

**Comment by mwilliammyers** [comment]
> I don't think we should enforce anything that breaks the amazing productivity of @sunli829

100% agree! Many thanks to @sunli829 👏 

That sounds like a good plan, iff:
- We are careful about when we release 2.0.0
- Try to follow semver under 1.0.0 (i.e. pretend the leading 1 isn't there and only release breaking changes with minor version bumps (not patches))
- Make the disclaimer *very* prominent; the first thing I noticed about this project was that it was already at 1.0.0, which seemed odd because of the git history and it being just announced on Reddit...

Although, now that I type all of that, I still think it would be less confusing in the end if we yanked versions... If there happen to be any published crates that depend on this (I don't think there are) they will [continue to work](https://doc.rust-lang.org/cargo/commands/cargo-yank.html) and people will just have to adjust a version in their Cargo.toml...

**Comment by phated** [comment]
When you suggest yanking, I assume you want us to rewrite the git history to change all 1.0 versions to 0.x, which would be a huge hassle and slow the project down considerably.

**Comment by mwilliammyers** [comment]
I mean using [`cargo yank`] to yank versions from crates.io (and maybe removing a handful of git tags). The git history can stay how it is. That might be a little confusing to developers who are reading really old commit messages but far less confusing for users of the library (which are more important in my opinion :))

**Comment by phated** [comment]
How does someone continue *using* the package at yanked versions? Cargo seems to only resolve yanked versions for other published crates. My application uses this project and I won't have a version to use.

I think you are optimizing for the case where people don't understand the compiler. I have been able to upgrade my project very quickly when doing a version upgrade. 🤔

**Comment by phated** [comment]
@mwilliammyers I completely agree.

I am just trying to outline the amount of work required to drop the `1.x` as you are suggesting. Essentially, we'd need to rewrite all of the history to publish those versions to the `0.x` line, then we'd never be able to use `1.x` versioning ever again and would need to go from `0.x` to `2.x`.

Since this has already happened, I think we just contain the problems to the 1.x release line and make the note.

**Comment by mwilliammyers** [comment]
I forgot about the fact that we couldn't use `1.1.x` again, so we would have to go straight to `1.2.x`.

Would we need to rewrite the history? Can't we just `cargo publish 0.14.0` or whatever, remove the git tags and then continue as normal with `0.14.0` up to `1.0.0` and then skip to `1.2.x`?

If it really would be a lot of work, then we can just add a prominent disclaimer to the README...

**Comment by phated** [comment]
We are actually far past `1.1.x` because we are already at `1.13.x` so we would have to throw away the entire `1.x` versioning space.

I'm pretty sure cargo publish uses the versions in the manifest, so we'd need to rewrite all of those.

I'll work on the disclaimer later today.

**Comment by mwilliammyers** [comment]
haha my bad, I was thinking we were at `1.1.x` for some reason when I wrote that.

Sounds, good!

**Comment by sunli829** [comment]
I need to iterate quickly, and I can't stand bad APIs. This is why `async-graphql` was created instead of perfecting `juniper`. 😁

**Comment by mwilliammyers** [comment]
Yeah. I definitely don’t want to slow you down! Keep up the good work! Thanks.
