### ISSUE TITLE
Error in GraphiQL IDE client when using MergedObject

### ISSUE THREAD

**Issue by Dindaleon** [async-graphql/async-graphql#1180]
Whenever I try to merge objects with `MergedObject` I get the following error in the GraphiQL IDE client:

```
{
  "errors": [
    {
      "message": "Unexpected token 'M', \"Missing re\"... is not valid JSON",
      "stack": "SyntaxError: Unexpected token 'M', \"Missing re\"... is not valid JSON"
    }
  ]
}
```

This is part of my code:

```
#[derive(MergedObject, Default)]
struct Query(UsersQuery, TasksQuery);

let schema = Schema::build(Query::default(), EmptyMutation, EmptySubscription).finish();
```

What am I missing?

**Comment by sunli829** [comment]
Have you specified the correct endpoint url?

https://docs.rs/async-graphql/5.0.4/async_graphql/http/struct.GraphiQLSource.html#method.endpoint

**Comment by Dindaleon** [comment]
> Have you specified the correct endpoint url?
> 
> https://docs.rs/async-graphql/5.0.4/async_graphql/http/struct.GraphiQLSource.html#method.endpoint

If you mean in Axum (I am using Axum, sorry for not specifying), then yes:

```
Router::new()
    .route("/", get(graphiql).post(graphql_handler))
    .layer(Extension(schema))
```

If you mean something else, then no. Could you please give me an example?

**Comment by Dindaleon** [comment]
Sorry! I totally forgot to implement the `graphql_handler` function:

```
type ServiceSchema = Schema<Query, EmptyMutation, EmptySubscription>;

async fn graphql_handler(schema: Extension<ServiceSchema>, req: GraphQLRequest) -> GraphQLResponse {
    schema.execute(req.into_inner()).await.into()
}
```

Now it works!
