### ISSUE TITLE
A way to drastically reduce code in this situation

### ISSUE THREAD

**Issue by frederikhors** [async-graphql/async-graphql#1193]
I'm using async-graphql with no problem at all, thanks for your work!

I have a feature request (or, if it is already possible, just a request for clarification).

I have the `graphql` mod which has this code:

```rust
#[derive(InputObject)]
pub struct PlayerFilters {
    pub id: Option<String>,
    pub created_at: Option<time::OffsetDateTime>,
    pub name: Option<String>,
    pub name_night: Option<String>,
    pub team: Option<String>,
    pub team_night: Option<String>,
    // ... and many many others ...
}

impl From<PlayerFilters> for app::PlayerFilters {
    fn from(o: PlayerFilters) -> Self {
        Self {
            id: o.id,
            created_at: o.created_at.map(Into::into),
            name: o.name,
            name_night: o.name_night,
            team: o.team,
            team_night: o.team_night,
            // ... and many many others ...
        }
    }
}
```

and the `app` mod which has:

```rust
pub struct PlayerFilters {
    pub id: Option<String>,
    pub created_at: Option<time::OffsetDateTime>,
    pub name: Option<String>,
    pub name_night: Option<String>,
    pub team: Option<String>,
    pub team_night: Option<String>,
    // ... and many many others ...
}
```

as you can see they have exactly the same fields: I did this because I cannot edit the code in `app` mod.

But since they have the exact same fields, is there a way to tell async-graphql to use `app`'s struct as the `InputObject` rather than repeating all the code twice?

Something like:

```rust
#[derive(InputObject)]
pub struct PlayerFilters(pub app::PlayerFilters)
```

or 

```rust
#[derive(InputObject)]
#[graphql(from="app::PlayerFilters")]
pub struct PlayerFilters{}
```

Thank you again for this amazing project!

**Comment by sunli829** [comment]
This is not possible because procedural macros cannot get any information about `app::PlayerFilters`. 🙂

**Comment by frederikhors** [comment]
Thanks for the reply.

Don't you see an alternative way at all?

**Comment by sunli829** [comment]
can be like `serde`

https://serde.rs/remote-derive.html

**Comment by frederikhors** [comment]
I had thought of something like this, even if reading I saw that the fields are repeated anyway. Or am I wrong?

**Comment by sunli829** [comment]
Yes, these fields need to be defined again.

**Comment by frederikhors** [comment]
It doesn't worth it then.
