### ISSUE TITLE
Query errors when parsing `Float` argument variables

### ISSUE THREAD

**Issue by spiegela** [async-graphql/async-graphql#1198]
## Expected Behavior

When creating a field with a `Float` type argument and passing the value for the argument as a query variable, the request should succeed in parsing the query argument as a `Float`. I am executing the query with `Content-Type: application/json` to ensure that the variables are not send as _query params_ since this often leads to string serialization of floats.

## Actual Behavior

When passing a `Float` argument, the server returns an error indicating that the query can not be executed because the variable is not a `Float`:
```json
{
  "data": null,
  "errors": [
    {
      "message": "Invalid value for argument \"location.latitude\", expected type \"Float\"",
      "locations": [
        {
          "line": 2,
          "column": 24
        }
      ]
    }
  ]
}
```

## Steps to Reproduce the Problem

1. Create a schema containing a query accepting an `InputObject` type, which contains a `Float` field using dynamic schema.
2. Create a query passing the argument as a variable (passing the argument inline of the query works as expected):

<details>
<summary>Example Query</summary>

```graphql
query SearchNearbyQuery($location:ScoreLocationInput!) {
  allNearby(location:$location) {
    edges {
      node {
        score
      }
    }
  }
}
```
</details>

<details>
<summary>Example Variables</summary>

```json
{"location":{"latitude":39.8617,"longitude":-104.6732}}
```
</details>

3. To confirm that the query args are being sent over JSON, and that the issue is with variable parsing also test via `curl` with positive and negative cases:

<details>
<summary>Positive Case (serializing args into the query works as expected)</summary>

```bash
curl 'http://localhost:8080/' -H 'Accept-Encoding: gzip, deflate, br' \
  -H 'Content-Type: application/json' \
  -H 'Accept: application/json' \
  -H 'Connection: keep-alive' \
  -H 'DNT: 1' \
  -H 'Origin: http://localhost:8080' \
  --data-binary '{"query":"query SearchNearbyQuery { allNearby(location:{latitude:39.8617,longitude:-104.6732}) { edges { node { score } } }"}'

```

</details>

<details>
<summary>Negative Case (serializing args as query variables fails with error above)</summary>

```bash
curl 'http://localhost:8080/' -H 'Accept-Encoding: gzip, deflate, br' \
  -H 'Content-Type: application/json' \
  -H 'Accept: application/json' \
  -H 'Connection: keep-alive' \
  -H 'DNT: 1' \
  -H 'Origin: http://localhost:8080' \
  --data-binary '{"query":"query SearchNearbyQuery { allNearby(location:{latitude:39.8617,longitude:-104.6732}) { edges { node { score } } }","variables":{"location":{"latitude":39.8617,"longitude":-104.6732}}}'

```
</details>

## Specifications

- Version: `5.0.1` and `master`
- Platform: `macos` and `linux`
- Web Server Integration: tested with both `poem` and `axum`, producing the same behavior

**Comment by spiegela** [comment]
I started trying to isolate the problem. Since we're using the dynamic schema I created a unit test in `dynamic::schema` to ensure that float args work as expected.  This test passes:

```rust
    #[tokio::test]
    async fn variables() {
        let myobj = Object::new("MyObj")
            .field(Field::new("a", TypeRef::named(TypeRef::INT), |ctx| {
                let a = ctx.args.get("arg").unwrap().i64().unwrap();
                FieldFuture::new(async move { Ok(Some(Value::from(a))) })
            }).argument(InputValue::new("arg", TypeRef::named(TypeRef::INT))))
            .field(Field::new("b", TypeRef::named(TypeRef::STRING), |ctx| {
                let b = ctx.args.get("arg").unwrap().string().unwrap().to_string();
                FieldFuture::new(async move { Ok(Some(Value::from(Value::from(b)))) })
            }).argument(InputValue::new("arg", TypeRef::named(TypeRef::STRING))))
            .field(Field::new("c", TypeRef::named(TypeRef::INT), |ctx| {
                let c = ctx.args.get("arg").unwrap().f32().unwrap();
                FieldFuture::new(async move { Ok(Some(Value::from(c))) })
            }).argument(InputValue::new("arg", TypeRef::named(TypeRef::FLOAT))));
        let query = Object::new("Query")
            .field(Field::new(
                "valueObj",
                TypeRef::named_nn(myobj.type_name()),
                |_| FieldFuture::new(async { Ok(Some(FieldValue::NULL)) }),
            ));
        let req = Request::new("query($argA: Int!, $argB: String!, $argC: Float!) { valueObj { a(arg: $argA) b(arg: $argB) c(arg: $argC) } }")
            .variables(Variables::from_value(value!({
                "argA": 123,
                "argB": "abc",
                "argC": 3.140000104904175,
            })));
        let schema = Schema::build("Query", None, None)
            .register(query)
            .register(myobj)
            .finish()
            .unwrap();
        let result = schema
            .execute(req)
            .await
            .into_result()
            .unwrap()
            .data;
        if let Value::Object(obj) = result {
            if let Value::Object(obj) = obj.get("valueObj").unwrap() {
                assert_eq!(obj.get("a").unwrap(), &Value::from(123));
                assert_eq!(obj.get("b").unwrap(), &Value::from("abc"));
                if let Value::Number(n) = obj.get("c").unwrap() {
                    assert_eq!(math::round::floor(n.as_f64().unwrap(), 2), 3.14);
                } else {
                    panic!("c is not float");
                }
            } else {
                panic!("valueObj is not an object");
            }
        } else {
            panic!("result is not an object");
        }
    }
```

 so I believe the problem must be in the variable parsing prior to request execution.

**Comment by sunli829** [comment]
I'm working on this

**Comment by sunli829** [comment]
> @sunli829 awesome. Thanks. I narrowed it down to the `ConstValue` deserializer in the Variables, but didn’t have an immediate plan for a custom deserializer since `serde_json` deserializes the float as a string.

It should not be caused by deserialization.

**Comment by spiegela** [comment]
That matches up with what I saw, that same test-case passes for me, meaning I don't think the problem is in `Schema::execute`. A `Float` value passed via HTTP is being converted to a `String` when the HTTP request is converted into a `GraphQLRequest` -- which is why it doesn't exhibit when we manually create requests.

I believe the problem is in `value::variables` [in the deserialization code](https://github.com/async-graphql/async-graphql/blob/master/value/src/variables.rs#L42).

@Bjohnson131 has also been digging in, and found that `serde_json` uses a `String` for the inner-type of a `serde_json::Number` when `arbitrary_precision` is enabled. That matches up with what I was seeing in the debugger.

**Comment by sunli829** [comment]
I changed the `arg` type to an input object, still can't reproduce.



```rust
        let my_input = InputObject::new("MyInput")
            .field(InputValue::new("value", TypeRef::named_nn(TypeRef::FLOAT)));

        let query = Object::new("Query").field(
            Field::new("value", TypeRef::named_nn(TypeRef::FLOAT), |ctx| {
                FieldFuture::new(async move {
                    let value = ctx.args.try_get("arg")?.object()?.try_get("value")?.f64()?;
                    Ok(Some(Value::from(value)))
                })
            })
            .argument(InputValue::new(
                "arg",
                TypeRef::named_nn(my_input.type_name()),
            )),
        );

        let schema = Schema::build("Query", None, None)
            .register(query)
            .register(my_input)
            .finish()
            .unwrap();

        let request: Request = serde_json::from_str(
            r#"
            {
                "query": "query($arg: Float!) { value(arg: $arg) }",
                "variables": { "arg": { "value": 3.21 } }
            }
        "#,
        )
        .unwrap();
        assert_eq!(
            schema.execute(request).await.into_result().unwrap().data,
            value!({
                "value": 3.21,
            })
        );
```

**Comment by spiegela** [comment]
I'll create an MVCE today and post it to reproduce the problem. I think the test will require an HTTP implementation since it happens as the request body is deserialized into the `GraphQLRequest` struct

**Comment by spiegela** [comment]
Well, the MVCE didn't reproduce the issue, so we have some more digging to do on our side.

**Comment by tmarcu** [comment]
@sunli829 @spiegela I found the issue here, if you compile serde_json with arbitrary precision e.g `serde_json =  { version = "^1", features = ["preserve_order", "arbitrary_precision"] }`
serde_json creates a value **object** with a custom key of `{$serde_json::private::Number: "29.231"}`, so that it can parse the value out as a string and not lose any precision on conversions. This breaks async-graphql (and probably many other libs) because it comes in as an _object_ and not a float value 🤦 idk why this does not break when it's entered inline on the graphql query, but it breaks it when it's added as a variable argument.

*Fix is to compile serde_json _without_ arbitrary precision.

**Comment by spiegela** [comment]
Yep. that bears out in the MVCE: https://github.com/spiegela/async-graphql-float-mvce

Enabling `serde_json` `arbitrary_precision` does it.  In our use-case we can do without `arbitrary_precision`, but I imagine somebody will need it...

@sunli829  up to you if you want to reopen the issue to make `async-graphql` compatible with this feature.

**Comment by zbrox** [comment]
Is there a workaround without removing the `arbitrary_precision` feature? I have a hard dependency on a crate which has to enable it.
