### ISSUE TITLE
UUID doesn't work with SimpleObject?

### ISSUE THREAD

**Issue by phated** [async-graphql/async-graphql#121]
@sunli829 I'm adopting `new-datasource` into my project and I just noticed that `Uuid` doesn't work with the `SimpleObject` macro. Did this happen recently?

This is the compiler error I am seeing.
```
the trait `async_graphql::base::OutputValueType` is not implemented for `uuid::Uuid`
```

**Comment by sunli829** [comment]
I've solved this problem on the main branch, and now I'm going to merge the `new-datasource`.

**Comment by sunli829** [comment]
I have merged, `uuid` dependency was once an option, now it is a required option, but some `#[cfg(feature = "uuid")]` is not removed.

**Comment by phated** [comment]
I thought that might be the problem. My project is compiling now.

**Comment by mwilliammyers** [comment]
@sunli829 @phated should `uuid` be required?

**Comment by sunli829** [comment]
> @sunli829 @phated should `uuid` be required?

I used `uuid` in `Logger`. 😁

**Comment by BratSinot** [comment]
Greetings!

I'm bringing it back, because can't use `uuid::Uuid` with `SimpleObject`:
```toml
[dependencies]
uuid = { version = "1.0.0-alpha.1", features = ["v4", "serde"] }
async-graphql = { version = "3.0.18", features = ["uuid"] }
```

```rust
#[derive(async_graphql::SimpleObject)]
struct Foo {
    uuid: uuid::Uuid,
}

fn main() {
    //
}
```

```log
error[E0277]: the trait bound `Uuid: OutputType` is not satisfied
  --> src/main.rs:1:10
   |
1  | #[derive(async_graphql::SimpleObject)]
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `OutputType` is not implemented for `Uuid`
   |
   = note: required because of the requirements on the impl of `OutputType` for `&Uuid`
note: required by a bound in `async_graphql::OutputType::resolve`
  --> /Users/asinotov/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.18/src/base.rs:81:35
```

**Comment by BratSinot** [comment]
Ok, my mistake, falling back to `uuid = "0.8.2"` did all fine.
