### ISSUE TITLE
Documentation: `DataLoader` example is missing context setup code

### ISSUE THREAD

**Issue by chuanqisun** [async-graphql/async-graphql#1219]
## Expected Behavior

The example in the `Optimizing N+1 queries` should cover all necessary steps to set up a data loader. 

## Actual Behavior

The example is missing the code that adds dataloader into the context and choosing the spawner. The following code, for example, can be added. 

```rs
    let schema = Schema::build(QueryRoot, EmptyMutation, EmptySubscription)
        .data(DataLoader::new(
            UserNameLoader,
            async_std::task::spawn, // or `tokio::spawn`
        ))
        .finish();
```

I eventually found the solution in the example code folder. However, it isn't obvious how the DataLoader should be `new()`ed and a task spanwer should be provided. I think other users could  benefit from an improvement documentation.

This feels like a simple fix. Let me know if you'd like a PR.

**Comment by sunli829** [comment]
Sorry for the late reply, I really need PR. 😀

**Comment by chuanqisun** [comment]
Sorry @sunli829, this has fallen off my attention. I just created the PR.
