### ISSUE TITLE
Failed to compile async-graphql in rust 1.45 nightly

### ISSUE THREAD

**Issue by sunli829** [async-graphql/async-graphql#122]
I have only discovered this problem now, causing `docs.rs` to not display the project documentation properly.😡

**Comment by sunli829** [comment]
This is definitely a compiler bug, and can easily occur when procedural macros are used with macros. I can only solve this problem by removing the macro code.

**Comment by mwilliammyers** [comment]
Is this the same issue? https://github.com/rust-lang/rust/issues/72545

It might be in the process of being reverted?

**Comment by sunli829** [comment]
> Is this the same issue? [rust-lang/rust#72545](https://github.com/rust-lang/rust/issues/72545)
> 
> It might be in the process of being reverted?

Yes, that's it. 😁
