### ISSUE TITLE
Ignored MergedObject with the same name as root MergedObject

### ISSUE THREAD

**Issue by 1g0rkR** [async-graphql/async-graphql#1226]
## Expected Behavior
Expectation to have root MergedObject from different Objects includes another MergedObject with the same name as root MergedObject.

## Actual Behavior
MergedObject from another module with the same name as root MergedObject has been ignored.

## Example of code:
```
use async_graphql::{EmptyMutation, EmptySubscription, MergedObject, SimpleObject};
use graphql_server::Graphql;

mod example {
    use async_graphql::{MergedObject, SimpleObject};

    #[derive(SimpleObject, Default)]
    pub struct Obj {
        i: i32,
    }

    #[derive(MergedObject, Default)]
    pub struct Merged(Obj);
}

#[tokio::main]
async fn main() {
    #[derive(SimpleObject, Default)]
    pub struct Obj2 {
        j: i32,
    }

    #[derive(MergedObject, Default)]
    pub struct Merged(example::Merged, Obj2);

    Graphql::new(Merged::default(), EmptyMutation, EmptySubscription)
        .start(([127, 0, 0, 1], 8000))
        .await;
}
```

As the result schema:
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/90048102/216940621-0bdf4cf3-bf48-4a22-a0aa-7b36437e052e.png">

## Solving problem
Renaming example::Merged to example::Merged2 as an example can solve the issue.
As the result after renaming:
<img width="407" alt="image" src="https://user-images.githubusercontent.com/90048102/216941751-5449d314-bf11-48c8-8349-0dc5fb36a013.png">

## Specifications

- Version: rustc 1.68.0-nightly (cc47b0699 2023-01-08)
- Platform: macOS Venture 13.2
- Subsystem: ---

**Comment by sunli829** [comment]
fixed in `master` branch 🙂
