### ISSUE TITLE
Do validators just stop at the first failure?

### ISSUE THREAD

**Issue by biot023** [async-graphql/async-graphql#1227]
Hello -- I'm using custom validators on my input objects (so I can track which fields the issues arise in) but have rather belatedly realised that I only ever get one error message.
If I set an input up to fail with two invalid fields, only one ever gets reported because it seems the validators all stop with the first failure and just report that.
Is that in fact the expected behaviour?
Or am I doing something wrong that is stopping the rest of the errors from getting reported?
Thanks for any and all advice,
   Doug.

**Comment by sunli829** [comment]
Yes, it currently stops on errors.

**Comment by biot023** [comment]
Okay, thank you for that.
