### ISSUE TITLE
connection.append operates on Results

### ISSUE THREAD

**Issue by phated** [async-graphql/async-graphql#125]
I'm refactoring some of my code for the new DataSource and I noticed that the Iterator *must* contain `FieldResult<Edge<..>>`. 

Why do we do that? In my code, I'm able to generate the `Edge` type without using a `Result`. I think this might be required to have fallible Cursors, is that correct?

**Comment by sunli829** [comment]
I added `try_append` and `try_append_stream` functions. 😁

**Comment by phated** [comment]
Upgraded and this seems to be working in my project.
