### ISSUE TITLE
async-graphql-actix authorization?

### ISSUE THREAD

**Issue by elertan** [async-graphql/async-graphql#127]
I haven't seen any authorization related documentation for this crate yet. So this was my attempt for solving this:

```rs
async fn index(
    schema: web::Data<GraphQLSchema>,
    req: GQLRequest,
    http_req: HttpRequest,
) -> impl Responder {
    let headers = http_req.headers();
    if headers.contains_key("Authorization") {
        let auth = Authorization::<Bearer>::parse(&http_req);
        match auth {
            Ok(_) => {}
            Err(_) => {
                return HttpResponse::BadRequest().body("AUTHORIZATION_HEADER_INVALID");
            }
        }
    }
    let response: GQLResponse = req.into_inner().execute(&schema).await.into();
    response
}
```

However this does not work, as the GQLResponse is its own special type, but the return type has to be the same for both. That said, if this were to work, then there also would need to be a way to set the authorization data in the Context so it can be used.

How do I go about this?

**Comment by elertan** [comment]
Nevermind, I found the example repo https://github.com/async-graphql/examples/tree/master/actix-web/token-from-header

Would be great to add this to the book though!

**Comment by elertan** [comment]
I'm reopening this issue because this still does not cover a way to respond with a bad request in case the header is malformed for some reason. Is there a way to do so?

**Comment by sunli829** [comment]
> I haven't seen any authorization related documentation for this crate yet. So this was my attempt for solving this:
> 
> ```
> async fn index(
>     schema: web::Data<GraphQLSchema>,
>     req: GQLRequest,
>     http_req: HttpRequest,
> ) -> impl Responder {
>     let headers = http_req.headers();
>     if headers.contains_key("Authorization") {
>         let auth = Authorization::<Bearer>::parse(&http_req);
>         match auth {
>             Ok(_) => {}
>             Err(_) => {
>                 return HttpResponse::BadRequest().body("AUTHORIZATION_HEADER_INVALID");
>             }
>         }
>     }
>     let response: GQLResponse = req.into_inner().execute(&schema).await.into();
>     response
> }
> ```
> 
> However this does not work, as the GQLResponse is its own special type, but the return type has to be the same for both. That said, if this were to work, then there also would need to be a way to set the authorization data in the Context so it can be used.
> 
> How do I go about this?

HttpResponse and GQLResponse are different types, and solving this problem is simple. `GQLResponse` implements `actix_web::Responder`, so you can call` Responder::respond_to` to create a `HttpResponse`. The following is the example code.

```rust
     let headers = http_req.headers ();
     if! headers.contains_key("Authorization") {
         return Ok(HttpResponse::BadRequest().body("AUTHORIZATION_HEADER_INVALID"));
     }
     let response: GQLResponse = req.into_inner ().execute(&schema).await.into();
     response.respond_to(&http_req).await
```

**Comment by elertan** [comment]
Sweet. Thanks!

Keep up the good work, loving this library so far.
