### ISSUE TITLE
input value validator - not equal to some number is required

### ISSUE THREAD

**Issue by leefordjudes** [async-graphql/async-graphql#1289]
## Description of the feature
input value validator - not equal to some number is required.
need more validators like class validators in typescript.

## Code example (if possible)
#[graphql(validator(not_equal = 0))]

**Comment by sunli829** [comment]
you can implement you own validator 🙂

https://github.com/async-graphql/async-graphql/blob/a42da838124a477bc4744fcb92196cea48f68754/tests/validators.rs#L306
