### ISSUE TITLE
Field guard enhancement - Post condition guard after resolving field

### ISSUE THREAD

**Issue by neshanthan** [async-graphql/async-graphql#129]
The existing guard implementation is a precondition for resolving the field. 

It will be great if we can also support a **_postcondition guard_** after resolving the field. 

This will allow for the guard to be used in scenarios where the resolved field has the data that the guard will evaluate against.

The syntax below will also allow for masking of data within the guard by being able to manipulate the field result before it is returned.

For example:  

```rust
struct Comment {
    id: ID,
    content: String,
    authorized_viewers: Vec<ID>
}

struct CommentGuard {
    id: ID
}

#[async_trait::async_trait]
impl PostGuard for CommentGuard {
    async fn check(&self, ctx: &Context<'_>, field_result: Comment) -> FieldResult<Comment> {
        let user_id = ctx.data::<User>().id;
        if field_result.authorized_viewers.contains(user_id) {
            return field_result;
        }

        Err("Forbidden".into())
    }
}

#[async_graphql::Object]
impl QueryRoot {
    #[field(guard(CommentGuard(id = "@id")))]
    async fn get_comment(&self, ctx: &Context<'_>, id: ID) -> FieldResult<Comment> {
        // ...
    }
}
```

Another example with traits (not sure if this is possible):

```rust
trait HasOwner {
    fn get_owner_id(&self) -> String;
}

struct Comment {
    id: ID,
    content: String,
    owner: ID
}

impl HasOwner for Comment {
    fn get_owner_id(&self) -> ID {
        self.id
    }
}

struct OwnerGuard<T: HasOwner> {
    data: String
}

#[async_trait::async_trait]
impl <T: HasOwner> PostGuard for OwnerGuard<T> {
    async fn check(&self, ctx: &Context<'_>, field_result: T) -> FieldResult<T> {
        let user_id = ctx.data::<User>().id;

        if user_id == field_restult.get_owner_id(){
            return self.field_restult;
        }

        Err("Forbidden".into())
    }
}

#[async_graphql::Object]
impl QueryRoot {
    #[field(guard(OwnerGuard::<Comment>(data = r#""test""#)))]
    async fn get_comment(&self, ctx: &Context<'_>, id: ID) -> FieldResult<Comment> {
        // ...
    }
}
```

I am new to Rust, so the syntax may not be correct. However, I hope it explains the use case.
 
There might be a better idiomatic approach for the syntax. 

Also thanks for the awesome library.

**Comment by sunli829** [comment]
Do you want to use this feature to avoid repeated database queries?

**Comment by neshanthan** [comment]
Yes that is the main reason, and it will also allow for generic guards like the trait example (this can also be achieved with the current guard but the code will be more complex).

This feature is implemented in the JavaScript library [GraphQL Shield](https://github.com/maticzav/graphql-shield) under [Fragments](https://github.com/maticzav/graphql-shield#fragments). It is one that I usually find quite useful to use.

**Comment by sunli829** [comment]
I'll think about it.

**Comment by neshanthan** [comment]
Thank you, I appreciate it.

**Comment by sunli829** [comment]
I have added Post Guard. In exchange, I would like you to add the chapter 'Guard' to the English book.  😁

**Comment by sunli829** [comment]
Guard can be defined in SimpleObject fields, Object fields and Subscription fields.

https://github.com/async-graphql/async-graphql/blob/master/tests/guard.rs
https://github.com/async-graphql/async-graphql/blob/master/tests/post_guard.rs

**Comment by neshanthan** [comment]
Thank you so much 😃

That sounds good for me, I will open a PR once I am done.

**Comment by sunli829** [comment]
Thank you. 😁

**Comment by onx2** [comment]
I'm trying to implement authentication using graphql mutations but I'm struggling to understand how I can lock down the schema if the user isn't authenticated. Right now I'm using a cookie / redis session and REST endpoints and [manually handling](https://async-graphql.github.io/async-graphql/en/integrations_to_tide.html#manually-handle-the-request) the request and checking for a cookie to be present and match the session.

It would be great if I could get rid of the REST api part of this and authenticate via graphql mutations. Since there is only one endpoint and it is required for a `login` and `register` mutation, I don't understand how I can lock down all parts of the schema except for the auth. Is this possible with `async_graphql`?

**Comment by sunli829** [comment]
> I'm trying to implement authentication using graphql mutations but I'm struggling to understand how I can lock down the schema if the user isn't authenticated. Right now I'm using a cookie / redis session and REST endpoints for auth and checking for a cookie to be present / match the session for the `/graphql` endpoint by [manually handling](https://async-graphql.github.io/async-graphql/en/integrations_to_tide.html#manually-handle-the-request) the request. I'm pretty new to BE dev and especially Rust but from the reading I've done and the few people I've talked to, using a cookie is the preferred way unless working with micro-services or mobile apps, so hopefully I'm on track here 😄
> 
> It would be great if I could get rid of the REST api part of this and authenticate via graphql mutations. Because there is only one endpoint for graphql and it is required for a `login` and `register` mutation, I don't understand how I can lock down all parts of the schema except for the auth. Is this possible with `async_graphql`? Thanks I appreciate any advice you can give!

This example can help you.
https://github.com/async-graphql/async-graphql/blob/d537769c92a9d93a54d2c898c9ef73e345e06af7/tests/guard.rs#L64

**Comment by onx2** [comment]
Thanks for the suggestion and quick response! I read through the book but haven't seen a way to do this guard by schema or query struct. Is there a way to do this without having to guard each field on every Query struct? I imagine when the API scales to dozens of queries this is a lot of boilerplate and prone to bugs from forgetting to implement a field guards everywhere.

Something like this would be helpful:
```rust
#[derive(Eq, PartialEq, Copy, Clone)]
enum Role {
    Admin,
    Guest,
}

struct RoleGuard {
    role: Role,
}

#[async_trait::async_trait]
impl Guard for RoleGuard {
    async fn check(&self, ctx: &Context<'_>) -> Result<(), FieldError> {
        if ctx.data_opt::<Role>() == Some(&self.role) {
            Ok(())
        } else {
            Err("Forbidden".into())
        }
    }
}

#[derive(SimpleObject)]
#[graphql(guard(RoleGuard(role = "Role::Admin")))]
struct Query {
    value: i32,
}
```

I think my ideal solution would be the inverse of a field guard - so the entire schema is locked down _except_ specific fields. Or am I thinking about this wrong?

**Comment by sunli829** [comment]
This suggestion is very good, I will add it.

**Comment by onx2** [comment]
Thanks! I'll keep an eye out for the release
