### ISSUE TITLE
Sanitize input

### ISSUE THREAD

**Issue by Weasy666** [async-graphql/async-graphql#1292]
I'm looking for a way to sanitize input values from a mutation, lets say:
```rust
#[derive(InputObject)]
struct UserInput {
    username: String,
    email: String,
}
```
how can i now sanitize the `email` field, like trimming whitespaces?

I have tried to implement a custom directive, but when i am not sure how to use it, or if it is at all possible with `InputObject`s.
I tried to us it this way, but that's not working, the macro throws an ``Unknown field: `sanitize` `` error
```rust
pub struct SanitizeDirective {
    value: String,
}

#[async_trait::async_trait]
impl CustomDirective for SanitizeDirective {
    async fn resolve_field(&self, _ctx: &Context<'_>, resolve: ResolveFut<'_>) -> ServerResult<Option<Value>> {
        resolve.await.map(|value| {
            value.map(|value| match value {
                Value::String(str) => Value::String(self.value.trim().to_string()),
                _ => value,
            })
        })
    }
}

#[Directive(location = "field")]
pub fn sanitize(value: String) -> impl CustomDirective {
    SanitizeDirective { value }
}


#[derive(InputObject)]
struct UserInput {
    username: String,
    #[graphql(sanitize)]
    email: String,
}
```

**Comment by sunli829** [comment]
Currently custom directives are only used for client requests,  you can use the `process_with` attribute to do it.


https://github.com/async-graphql/async-graphql/blob/382d54d5817e1bd3259c01712c76f6edc50d1081/tests/input_object.rs#L614
