### ISSUE TITLE
Add ability to exclude Subscription from _service.sdl

### ISSUE THREAD

**Issue by rkudryashov** [async-graphql/async-graphql#131]
If I add just empty Subscription to the service:

```
pub struct Subscription;

#[Subscription]
impl Subscription {

}
```

Apollo Server will complain that:

```
[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node gateway.js`
� Server ready at http://localhost:4000/
This data graph is missing a valid configuration. [some-service] Subscription -> `Subscription` is an extension type, but `Subscription` is not defined in any service
```

(to test it `cd apollo-server`, `npm run start-gateway`)

This is a well-known issue: https://github.com/apollographql/apollo-server/issues/3357

My question is is it possible to use flag or something other to have an ability to exclude Subscription type definition from `_service.sdl` query. If so, subscriptions of async-graphql server would still work in a "standalone" mode, and Apollo Server would work without subscriptions.

Repro-project: https://github.com/rkudryashov/async-graphql-reproducer

**Comment by sunli829** [comment]
Please upgrade to `1.14.10`.
