### ISSUE TITLE
Discussion: Improve performance

### ISSUE THREAD

**Issue by Amareis** [async-graphql/async-graphql#132]
So, basically, async-graphql is already a great library, but it's performance isn't so great yet. I think some performance focus it's pretty good fit for rust GraphQL library :)

We had a discussion about it with @sunli829 via email and highlight some possible weak points.

> The performance problems of async-graphql are mainly due to the following reasons:
> 
> 1. Parser too much memory allocation, such as String.
>      In fact, I have optimized it with unsafe code, and the performance has been improved. Parsing a very complex query 40,000 times has improved by 100 milliseconds. I think that it is not worthwhile to exchange some unsafe factors for such a little performance improvement. So I changed it back.
> 
> 2. The performance loss caused by the Box future returned by the async-trait. (This may not be easy to solve)
>      I found a new library async-trait-ext, maybe it can avoid extra memory allocation, but I haven't tried it yet.
> 
> 3. Performance loss caused by asynchronous resolver function. (I have n’t thought of a method that is compatible with both synchronous and asynchronous, because it may mean that a lot of infrastructure needs to provide both synchronous and asynchronous)

Some solutions:

> According to my tests, replacing https://github.com/async-graphql/benchmark with jemalloc can bring great performance improvements.

>Query parsing/validation caching can be really great feature, especially because it's almost required for https://www.apollographql.com/docs/apollo-server/performance/apq/
>Our app clients have in total less than 1000 queries/mutations/subscriptions, and all of it purely static, only variables is changed. So, basically, caching all of this queries documents can get rid of parsing/validation phase entirely in whole server and it's not really hard to implement - fast string hashing, simple LRU cache and additional setting to enable/disable this feature. There is can be additional option - cache only persisted queries, when they will be implemented.

But, of course,
> We need a more complete benchmark test, we should first complete this work, and then first to improve the part with the greatest impact on performance.

We already have some benchmarks at https://github.com/async-graphql/benchmark but it should be improved. 

Maybe it's worth to move benchmark to main repo and add https://github.com/marketplace/actions/continuous-benchmark to have clear baseline and performance history.

**Comment by Amareis** [comment]
Currently I improves existing benchmarks, and for better coverage I need to understand main query processing phases. As I see, there is:

1. Parse a query
2. Validation against the schema
3. Recursive fields resolving

And extensions hooks everywhere, of course. Does it seems correct?

**Comment by sunli829** [comment]
Yes, exactly! 😃

**Comment by sunli829** [comment]
`serde_json::Value` is also quite slow, too much memory allocation, we may have to implement one ourselves.

**Comment by Amareis** [comment]
Oh, yep, if we consider JSON string as final result, there is

4. Serialization to string

But i doubt we can make faster serialization than serde :)

**Comment by Amareis** [comment]
Ok, there is some initial numbers, at my local machine. We also need to expose some methods to bench validation and resolve phases.

Serialize is not part of run, and wrapping results in serde_json::Value currently is part of resolve phase, not a serialize.

```
run                     time:   [247.00 us 249.60 us 252.41 us]                
                        change: [-4.4749% -2.0674% +0.3226%] (p = 0.09 > 0.05)
                        No change in performance detected.
Found 7 outliers among 100 measurements (7.00%)
  3 (3.00%) high mild
  4 (4.00%) high severe

parse                   time:   [63.374 us 64.054 us 64.770 us]                  
                        change: [-1.3206% +2.2938% +7.3555%] (p = 0.43 > 0.05)
                        No change in performance detected.
Found 18 outliers among 100 measurements (18.00%)
  10 (10.00%) high mild
  8 (8.00%) high severe

serialize               time:   [7.5581 us 7.6434 us 7.7338 us]                       
                        change: [-5.9858% -3.1854% -0.5511%] (p = 0.03 < 0.05)
                        Change within noise threshold.
Found 13 outliers among 100 measurements (13.00%)
  8 (8.00%) high mild
  5 (5.00%) high severe
```

**Comment by Amareis** [comment]
Should we include benchmarks into main repo? It will be easier to change thing & measure it.

**Comment by sunli829** [comment]
Well, move it to the main repo, then I will delete the benchmark repo. Tomorrow I will optimize the parser. 😄

**Comment by sunli829** [comment]
> Maybe it's worth to move benchmark to main repo and add https://github.com/marketplace/actions/continuous-benchmark to have clear baseline and performance history.

That's great!👏

**Comment by sunli829** [comment]
I added `gqlgen` benchmark test in `async-graphql-benchmark` and added `jemalloc` memory allocator. `async-graphql` is 40% faster than `gqlgen` on my macbook pro. If we do the optimization ourselves, it may only be a little faster than `jemalloc`. What do you think?

**Comment by sunli829** [comment]
I added gqlgen benchmark test in async-graphql-benchmark and added jemalloc memory allocator. async-graphql is 40% faster than gqlgen on my macbook pro. If we do the optimization ourselves, it may only be a little faster than jemalloc. What do you think?

**Comment by sunli829** [comment]
# async-graphq/benchmark

## Without jemalloc

```
run                     time:   [208.91 us 211.11 us 213.48 us]                
                        change: [-10.401% -9.3251% -8.2008%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild

parse                   time:   [35.218 us 35.324 us 35.434 us]                   
                        change: [-8.5952% -7.0866% -5.6535%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 9 outliers among 100 measurements (9.00%)
  3 (3.00%) low mild
  2 (2.00%) high mild
  4 (4.00%) high severe

serialize               time:   [6.4584 us 6.5017 us 6.5557 us]                       
                        change: [-4.4104% -3.1576% -1.7538%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 6 outliers among 100 measurements (6.00%)
  2 (2.00%) high mild
  4 (4.00%) high severe
```

## With jemalloc

```
run                     time:   [142.10 us 142.92 us 143.88 us]                
                        change: [-31.874% -31.086% -30.303%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 5 outliers among 100 measurements (5.00%)
  4 (4.00%) high mild
  1 (1.00%) high severe

parse                   time:   [28.329 us 28.539 us 28.773 us]                   
                        change: [-19.889% -19.340% -18.757%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 34 outliers among 100 measurements (34.00%)
  2 (2.00%) low severe
  15 (15.00%) low mild
  13 (13.00%) high mild
  4 (4.00%) high severe

serialize               time:   [6.4859 us 6.4973 us 6.5117 us]                       
                        change: [-2.2099% -1.0576% -0.1213%] (p = 0.05 < 0.05)
                        Change within noise threshold.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high severe
```

**Comment by Amareis** [comment]
Oh, that's really good change! I think, it's already can be added to book, as first step. 

I try to add our test to benchmark, there is many many objects with simple fields. Also we need some sort of concurrent testing, because throughput can be non linear from rps.

**Comment by Amareis** [comment]
Okay, so I added new benchmark, and there is its numbers:

```
cargo bench -- chat

Benchmarking chat run: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 77.7s or reduce sample count to 10.

chat run                time:   [11.698 ms 11.901 ms 12.163 ms]                      
Found 10 outliers among 100 measurements (10.00%)
  4 (4.00%) high mild
  6 (6.00%) high severe

chat parse              time:   [34.066 us 34.821 us 35.893 us]                       
Found 19 outliers among 100 measurements (19.00%)
  3 (3.00%) high mild
  16 (16.00%) high severe

Benchmarking chat serialize: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 6.0s or reduce sample count to 60.

chat serialize          time:   [1.1857 ms 1.1929 ms 1.2009 ms]                            
Found 17 outliers among 100 measurements (17.00%)
  3 (3.00%) high mild
  14 (14.00%) high severe
```

**Comment by Amareis** [comment]
It's sample of hundreds of resolvers per query. There is
(30 chats * 8 fields + 30 chats * 30 messages * 5 fields + 30 chats * 6 users * 11 fields) = 6720 async resolvers. There is not much a memory allocations, so I think it's mostly async resolvers overhead (plus serde Value creation).

With jemalloc there is some improvements, but not so big, as at small queries (about 10%):
```
chat run                time:   [10.367 ms 10.602 ms 10.887 ms]                      
                        change: [-29.034% -22.056% -15.382%] (p = 0.00 < 0.05)
                        Performance has improved.
```

**Comment by sunli829** [comment]
Can we add `chat_jemalloc` and `simple_jemalloc`, so that we can compare them easily? If there is a big performance gap, then it means that the bottleneck is in the memory allocation, otherwise it is not.

BTW: `Criterion` doesn't seem to work properly on Windows.

**Comment by Amareis** [comment]
Yep, ready.

On both `chat` and `simple` jemalloc reduces time about 10% in comparison with Linux system malloc. I think, your numbers is different because of Windows malloc implementaion is less efficient.

**Comment by sunli829** [comment]
I'll try it on Linux tomorrow. Thank you.😄

**Comment by sunli829** [comment]
The memory allocation performance of the MAC OS is really quite poor...

**Comment by Amareis** [comment]
After some digging, I saw that we really can do sync resolvers - functions or fields. That if mostly get rid of `resolve_field` method? Then we can generate efficient `resolve` method for user object types, which will use futures only for async fields and just collect values for other fields. It shouldn't be really heavy change (`resolve_field` have only 14 matches in whole codebase), but still can give us good performance boost and better API design.

Then we can try to split sync and async scalars - all builtins is sync, for example, but users can add some custom async scalars.

**Comment by sunli829** [comment]
In fact, I have tried this, but the performance improvement is not big.

**Comment by sunli829** [comment]
Can you do a performance test with Juniper 0.14.2 because it only supports synchronization?

**Comment by sunli829** [comment]
Now `async-graphql` isn't really slow, but it can be faster.
But database queries are the real bottleneck, aren't they? The performance loss of `async-graphql` is negligible compared to database queries.

**Comment by sunli829** [comment]
> Can you do a performance test with Juniper 0.14.2 because it only supports synchronization?

I've tested it and it's true that synchronization is fast, but with the complexity of the business, it's hard for synchronized code to take full advantage of multicore CPU.

**Comment by Amareis** [comment]
>it's hard for synchronized code to take full advantage of multicore CPU.

Yep, but if `ObjectType::resolve` is still async, this not an issue - code will run on all CPU cores, by default. Also, simple sync resolvers (for example - plain field getters) actually can be faster (if inlined) than creating future - but future should be runned yet. And user still can mark resolver async, to take advantage of less blocking tasks in big resolvers.

Biggest advantage of sync resolvers is lesser executor pressure. Currently in chat bench there is 7k futures per query (probably - more, because all scalars also async). And with all sync fields will be about 1k futures, so there CPU will run more user code, not an executor task-switching (per query, ofc).

**Comment by mwilliammyers** [comment]
I really think we should add plain `sync` resolvers support; I imagine this will improve performance by reducing executor pressure (like @Amareis said) **especially** on single/low core machines (e.g. Google Cloud Run/Functions or AWS lambda etc) which are common deployment scenarios...

We should benchmark it on low/slow/single core CPUs ( or via `cpulimit` etc.)...

If nothing else, it bothers me to see things like:
```rust
async fn id(&self) -> &ID {
    &self.id
}
```
sorta seems like a code smell 😄

**Comment by sunli829** [comment]
I'm going to try to make a few small changes today. 😁

**Comment by sunli829** [comment]
First of all, I want to solve the problem of interface function forwarding, it should be able to recognize async/sync.

**Comment by sunli829** [comment]
I've made a few improvements to the `sync-resolver` branch, but the performance improvements are small, it's hard to fully support both sync and async.

**Comment by mwilliammyers** [comment]
Did you benchmark with a single CPU core?

**Comment by sunli829** [comment]
Yes, I only tested it on a single-core CPU, and in fact a single GraphQL query because `await` can span more than one thread, but the execution is sequential.

**Comment by Amareis** [comment]
@sunli829 which scenario you're using for this test?

**Comment by sunli829** [comment]
> @sunli829 which scenario you're using for this test?
`sync-chat` and `async-chat`

**Comment by Amareis** [comment]
There is my benches (2 core CPU, jemalloc enabled)
```
Benchmarking async-chat run
async-chat run          time:   [9.6104 ms 9.6403 ms 9.6705 ms]                            

Benchmarking sync-chat run
sync-chat run           time:   [9.1370 ms 9.1672 ms 9.1987 ms]       
```

In fact, there is solid 5% speed up in sync resolvers. Not bad, I think!

But, still, for each field future is creating (because of `resolve_field` is still async and it's used by resolve). And for each returned value too (because of async `OutputValueType::resolve`). And although `resolve_field` is crucial in current architecture, return values can be casted to `serde_json::Value` easily, we know it's types and in all simple cases (string, number, bool or list/option/result) we can cast to `Value` directly inside of `resolve_field`. I bet, this'll give us additional 4-5% percent of performance. (I will name it "sync scalars" in future).

But `resolve_field` is still most important. If we can avoid it at `do_resolve` when it's not needed, it'll be really amazing - and it's not so hard! With sync scalars it's just additional condition, where all sync fields executed in `do_resolve` directly. And, this is additional 4-5% boost, I think, without much efforts.

**Comment by sunli829** [comment]
It is difficult to support sync scalars without generic specialization. 😕

**Comment by phated** [comment]
@sunli829 Would it be possible to implement a `#[SyncObject]` macro where **no** methods could be async?

**Comment by sunli829** [comment]
> @sunli829 Would it be possible to implement a `#[SyncObject]` macro where **no** methods could be async?

I'm currently using the `async` keyword, but the slowest one is actually `resolver.rs`. 
I think we should wait until the generic specialization support is in place, otherwise it will make the library more complex to use.

**Comment by Amareis** [comment]
>It is difficult to support sync scalars without generic specialization.

Why so? We always know field return type. It can be 
a) built-in scalar 
b) custom scalar 
c) object 
d) container (list/optional) of a, b, or c. 

And we have list of built-in scalars names, currently all of it is sync.

So algorythm is not so complex, it can be just small macro function:
1. Strip all containers, from return value type, let result be `MainType`.
2. If `MainType` is built-in scalar, directly convert return value to `serde_json::Value`.
3. Else use async `OutputValueType::resolve` with `.await`, as usual.

Built-in scalars list can be just compile-time vector, with checking (`#[Scalar(internal)]` checks if scalar name in this list). Custom scalars also can be marked as sync (in `field` attribute, i think), but this isn't necessary.

**Comment by sunli829** [comment]
> Built-in scalars list can be just compile-time vector, with checking (`#[Scalar(internal)]` checks if scalar name in this list). Custom scalars also can be marked as sync (in `field` attribute, i think), but this isn't necessary.

I think it's a good idea, and I'll try. 😁
