### ISSUE TITLE
Document `#[graphql(flatten)]` in the english version of the book

### ISSUE THREAD

**Issue by schitcrafter** [async-graphql/async-graphql#1335]
## Description of the feature

As per #1004 , async graphql supports the flatten attribute on Simple-/InputObject's, but this is not yet documented in the english version of the async-graphql book. I'd add it myself there, but I'm not sure which page to put it into, if someone tells me where to put it I'd be happy to add it myself. 

## Code example (if possible)

**Comment by sunli829** [comment]
add to these pages 🙂

https://github.com/async-graphql/async-graphql/blob/master/docs/en/src/define_input_object.md

https://github.com/async-graphql/async-graphql/blob/master/docs/en/src/define_simple_object.md
