### ISSUE TITLE
Support for multipart/mixed subscriptions.

### ISSUE THREAD

**Issue by semtexzv** [async-graphql/async-graphql#1348]
## Description of the feature
It'd be nice if implemented server could accept `multipart/mixed` requests,
This subscription transport is implemented in the apollo router: https://www.apollographql.com/docs/router/executing-operations/subscription-multipart-protocol/

**Comment by sunli829** [comment]
I'll add it later.

**Comment by sunli829** [comment]
released in `v6.0.4`

**Comment by sunli829** [comment]
If you use `poem`, `axum` or `actix-web`, then this feature will be supported by default.

**Comment by semtexzv** [comment]
Awesome man!
