### ISSUE TITLE
`FieldFuture` Improvements

### ISSUE THREAD

**Issue by tusharmath** [async-graphql/async-graphql#1354]
## Description of the feature
While doing benchmarks of async-graphql, I realized that all fields that have values that can be determined without performing any async operation, still pay the penalty of the runtime overhead involved in the async/await syntax (see attached screenshot). One potential optimization could look as follows —

**Current**
```rust
pub struct FieldFuture<'a>(pub(crate) BoxResolveFut<'a>);
```

**Proposed**
```rust
enum FieldFuture<'a> {
  Value(&'a Value),
  Future(BoxResolveFut<'a>)
}
```

This way the fields that can resolved immediately via `Value` will not have to pay the penalty of async/await, which could be a massive optimization over the current implementation. Let me know what you think, happy create a PR.

![flamegraph](https://github.com/async-graphql/async-graphql/assets/194482/605d6794-54f3-48f0-9957-009599c8829f)

**Comment by sunli829** [comment]
Welcome to PR😁

**Comment by tusharmath** [comment]
Made some basic changes in the way field future is written. I realized that there a lot of async nesting that is done while resolving fields. Unless we remove it completely for fields that don't need to be async, I don't think we will be able to achieve maximum performance. However, I will perform a few benchmarks to see if it has any visible impact on performance.

**Comment by sunli829** [comment]
This is definitely a huge change.
