### ISSUE TITLE
Server doesn't respond to _service.sdl query if it doesn't contain any #[entity] fn

### ISSUE THREAD

**Issue by rkudryashov** [async-graphql/async-graphql#136]
It is a possible situation when a server just includes isolated domain area which is not crossed with entities of any other service. For example, there may be two services with different domains, and it is only needed to create a single endpoint through which they can be accessed.

Repro-project: https://github.com/rkudryashov/async-graphql-reproducer

It contains such query:

```
pub struct Query;

#[Object]
impl Query {
    async fn some_query(&self, ctx: &Context<'_>) -> SomeType {
        ...
    }

    #[entity]
    async fn find_entity_by_id(&self, ctx: &Context<'_>, id: ID) -> SomeType {
        ...
    }
}
```

If you comment `#[entity]` line, `_service.sdl` query will disappear.

**Comment by rkudryashov** [comment]
I have this case in my pet-project. Let's suppose similar example which includes City service, Country service and Auth service. First contains City entity, second contains Country entity with `cities` field, and third contains only User entity with `createUser` and `signIn` methods.

**Comment by sunli829** [comment]
Well, I'm going to add the option that if there's no entity you can manually open federation support, right?😃

**Comment by rkudryashov** [comment]
Yes, great :)

**Comment by sunli829** [comment]
Please upgrade to `1.14.11`.
