### ISSUE TITLE
Extension hook with all data available prior to `execute` (for access-control)

### ISSUE THREAD

**Issue by cedtwo** [async-graphql/async-graphql#1360]
## Description
Currently async-graphql access is opt-out, in that any field where access is to be limited must be defined with a `Guard`. I would like an access enforcer to be called on all queries before being executed. In an [obj], [sub], [act] model, such as those supported by popular crates such as `oso` or `casbin` (the latter of which I am trying to integrate into my project), I need access to the user [sub], and the endpoit [obj]. Getting the user is trivial as it'll likely come from a JWT or such, but making assertions against the object is much more difficult. Let's take for example a call to `deleteArticle` To the best of my knowledge, my choices are to either:
- Put this logic in the router post handler, where I can deserialize variables and assert, for example, that the specified `article` belongs to the user. The drawback is that I am repeating logic that will be repeated once the request is executed (deserialize, validate scalars etc.).
- Put access-control enforcement in each and every resolver, or use Guards. Not only is there more room for error from forgotten or wrongly implemented access-enforcement, the access policy is no longer a single source of authorization. Certain changes to the access model would require **ALL** calls to an access enforcer to be updated, and in many cases a new addition to the policy would require changes in code too.

What would be ideal would be a hook prior to execution where I could get the user (not an issue), the parsed and validated variables, and the resolver and field queried (such as that which can be found in `ResolveInfo`), prior to the `execute` hook. Is this, or an alternative, possible?

**Comment by sunli829** [comment]
I think implementing an `Extension`, verifying permissions in `Extension::resolve`, and returning an error if it fails can meet your needs. 🙂

**Comment by cedtwo** [comment]
Sorry for the late reply. One of the reasons I believed `resolve` was not appropriate was that I found no way to access a passed in variable. Now that I've taken another look at it, I realize that arguments passed as `Value::Object` are readily available, while those of `Value::Variable` only contain the `Name`. Could you provide some insight into how I could access the value of `Value::Variable` within `resolve`? Or another such method that could get me the values of arguments passed as variables?

**Comment by cedtwo** [comment]
Given a little thought, I think using `resolve` is the correct answer, and I'll open a new issue clarifying using `resolve` for the specific circumstances above.
