### ISSUE TITLE
Connection Name Conflict

### ISSUE THREAD

**Issue by kennetpostigo** [async-graphql/async-graphql#1364]
Hi I have field resolvers on a GraphQL type that seem to be clashing because they each seem to define a type of Connection with the same name. I'm not sure how I can solve the error. I have the following:

```rs
#[derive(SimpleObject)]
pub struct ConnectionFields {
    /// Total result set count
    total_count: usize,
}

pub type ConnectionResult<T> = Result<Connection<Base64Cursor, T, ConnectionFields, EmptyFields>>;
pub type ConnectionOffsetResult<T> = Result<Connection<usize, T, ConnectionFields, EmptyFields>>;
```

Then in a field resolver on one graphql type:
```rs
    pub async fn produce(
        &self,
        ctx: &Context<'_>,
        input: GrowerProduceInput,
    ) -> Result<relay::ConnectionResult<Produce>> {
        ...
    }
```

Then on the second graphql type:
```rs
pub async fn produce(
        &self,
        ctx: &Context<'_>,
        input: ProduceSearchInput,
    ) -> Result<relay::ConnectionOffsetResult<Produce>> {
        ...
    }
```

These both seem to be causing the same GraphQL Connection `ProduceConnection` to be generated and then leading to a `have same name` error.

I'm not sure how to solve this as in my root schema.rs file I am using `MergedObject` on all my GraphQL types.

Do you know what I can do to work around this issue?

**Comment by sunli829** [comment]
Although `relay::ConnectionResult<Produce>` and `relay::ConnectionOffsetResult<Produce>` are two different Rust types, but they generate the same GraphQL type name by default, both are `ProduceConnection`, which is the cause of the conflict .

You may consider renaming one of them to solve the problem, here is an [example](https://docs.rs/async-graphql/6.0.5/async_graphql/types/connection/fn.query.html#custom-connection -and-edge-type-names)

**Comment by kennetpostigo** [comment]
@sunli829 from the example it seems that gives the connection a static name, is there a way to keep it Dynamic but have a different Prefix/PostFix in the name?
