### ISSUE TITLE
Unexpected literal type `unary` for negative number validator

### ISSUE THREAD

**Issue by hyche** [async-graphql/async-graphql#1381]
## Expected Behavior
Compile successfully

## Actual Behavior
Failed to compile and produce above error

## Steps to Reproduce the Problem
Make an input type with signed integer and validates using minimum validator with negative number.
Ex: 
```
#[graphql(validator(minimum=-100, maximum=100))] num: i32,
```

## Specifications

- Version: 6.*
- Platform: Mac M1
- Subsystem:

**Comment by sunli829** [comment]
When you change the order, it compiles successfully. I still don't know what the problem is. 😂

```rust
#[graphql(validator(maximum=100, minimum=-100))] num: i32,
```
