### ISSUE TITLE
Inaccessible trait bounds on OpenTelemetry extension

### ISSUE THREAD

**Issue by rtkay123** [async-graphql/async-graphql#1387]
## Expected Behavior
`opentelemetry` extension to work on current 6.0.7 version

## Actual Behavior
There's a trait bound on an inaccessible trait: `opentelemetry_api::trace::tracer::Tracer` seems to be a in a private module now. Also it seems `opentelemetry_api` has been collapsed into `opentelemetry` https://github.com/open-telemetry/opentelemetry-rust/commit/42e58fc356aea17811391e7127a07acd1d6720db

## Steps to Reproduce the Problem

1. `cargo add opentelemetry_api` -> v0.20.0
2. Try to add `opentelemetry_api::trace::tracer::Tracer` as a trait bound
3. `opentelemetry_api::trace::tracer` is not public

```rust
pub fn create_schema<T: Send + Sync + [requires a bound I can't seem to locate now]>(
    tracer: T,
) -> SomeSchema {
    Schema::build(Query::default(), EmptyMutation, EmptySubscription)
        .extension(OpenTelemetry::new(tracer))
        .finish()
}
```

## Specifications

- Version: 6.0.7

**Comment by yasamoka** [comment]
Use OpenTelemetry v0.19.0 instead.
