### ISSUE TITLE
Introduce the ability to supply a header for graphiql aka graphql playground.

### ISSUE THREAD

**Issue by ruseinov** [async-graphql/async-graphql#139]
Currently it's possible to hit secured graphql endpoints specifying the header value manually via browser html editor:
```
{
   "Authorization":"Bearer <token from request>"
}
``` 

It would help a lot if this could be done in a more convenient manner, like so:

```
    Ok(HttpResponse::Ok()
        .content_type("text/html; charset=utf-8")
        .body(playground_source("/graphql", None, Some(token)))
```

or even 

```
    Ok(HttpResponse::Ok()
        .content_type("text/html; charset=utf-8")
        .body(playground_source("/graphql", None, Some(header_map)))

```

which would be more generic.

**Comment by ruseinov** [comment]
I can also contribute this myself if that would be of interest, otherwise I defer to you guys how that api should look.

**Comment by IcanDivideBy0** [comment]
Ideally, we should be able to give a complete JSON object that will end up being serialized here https://github.com/async-graphql/async-graphql/blob/d95c0f23b8691f346e683ec78e38499e7a55a810/src/http/playground_source.rs#L540

**Comment by ruseinov** [comment]
> Ideally, we should be able to give a complete JSON object that will end up being serialized here
> 
> https://github.com/async-graphql/async-graphql/blob/d95c0f23b8691f346e683ec78e38499e7a55a810/src/http/playground_source.rs#L540
> 
> So we can fully specify the playground config

Yeah, that would also work. Just being able to pass anything serializable (struct/hashMap) would do the trick.

**Comment by IcanDivideBy0** [comment]
I guess a `serde_json::Value` would be fine:
```rust
playground_source("/graphql", json!({
    "endpoint": "...",
    "tabs": [{
        "headers": {
            "Authorization": format!("Bearer {}", token)
        }
    }]
}))
```

**Comment by ruseinov** [comment]
Yeah, that'd also work, although if the function accepts anything that's serializable - that would include serde_json::Value too with an added benefit of being able to specify your own strongly typed struct and pass it directly to the method. I have no preference here as it's basically an extra line of code to convert a struct to a json value, just seems more eloquent to use generics there.

**Comment by sunli829** [comment]
Playground is a testing environment, don't you notice that there is a place to set HTTP headers in the lower left corner?

**Comment by ruseinov** [comment]
> Playground is a testing environment, don't you notice that there is a place to set HTTP headers in the lower left corner?

It would be way more convenient to be able to secure the endpoint and pass whatever configuration/jwt token from Rust code rather than manually supplying it each time. If you google this - the issue is known and discussed in a variety if graphql implementation repos. 

It is indeed a testing environment, but that does not mean it should be inconvenient to use. I have seen this change done in some custom forks of the graphiql itself and would be glad to have the ability to supply auth here as well instead of maintaining a custom fork of the async-graphql library. 

Currently I’m using postman for all that, but it’s graphql support is poor. 

I am more than happy to contribute if this gets accepted.

**Comment by sunli829** [comment]
Welcome to PR. 😀

**Comment by ruseinov** [comment]
Will do!

**Comment by sunli829** [comment]
@ruseinov Are you going to pass JSON directly to the Playground or the rust type?

**Comment by ruseinov** [comment]
@sunli829 answering your removed question - I was thinking to pass a rust serializable as it seems like the most generic approach:
1. you can pass json!
2. you can pass a Rust struct with typed complex config
3. you can pass anything else that derives serialize.

**Comment by sunli829** [comment]
> @sunli829 answering your removed question - I was thinking to pass a rust serializable as it seems like the most generic approach:
> 
> 1. you can pass json!
> 2. you can pass a Rust struct with typed complex config
> 3. you can pass anything else that derives serialize.

That's great, I deleted that question because I mixed up headers and variables... 😁
