### ISSUE TITLE
_service { sdl } does not output Subscription type on a Federated Subgraph

### ISSUE THREAD

**Issue by cs-clarence** [async-graphql/async-graphql#1391]
## Expected Behavior
It should have a Subscription type

## Actual Behavior
Only Query and Mutation types are present
No Subscription is found when a search the result even when i have subscriptions in the subgraph
![image](https://github.com/async-graphql/async-graphql/assets/71768661/0016ca98-a118-4b21-bf0a-dd28b76a2089)

## Steps to Reproduce the Problem

1. Create a subgraph with subscriptions
2. Introspect it using 
```
curl -i -X POST http://localhost:3000/graphql -H "Content-Type: application/json"  -d "{ \"query\": \"{ _service { sdl } }\" }"
```
3. There is no type Subscription in the response of the query 

## Specifications

- Version: 6.0.7
- Platform: Linux
- Subsystem: Fedora

**Comment by cs-clarence** [comment]
@sunli829 sorry to mention you like this but can you help me?

**Comment by kukakuki** [comment]
@cs-clarence, I'm facing the same issue. Could you let me know what the solution was? :)

**Comment by cmtm** [comment]
@cs-clarence, I'm seeing this issue. How did you resolve it?

**Comment by cmtm** [comment]
I figured it out. You need to call [`enable_subscription_in_federation`](https://docs.rs/async-graphql/latest/async_graphql/struct.SchemaBuilder.html#method.enable_subscription_in_federation) on the SchemaBuilder. I feel this should probable be an `SDLExportOptions` flag instead.
