### ISSUE TITLE
How to merge object with fields?

### ISSUE THREAD

**Issue by nxy7** [async-graphql/async-graphql#1394]
Hello, I've found that one of my objects grew way too big and I'd like to split it (it's over 1k loc right now). I've used MergedObject to merge different parts of Graphql graph, but I've no idea how to use it on object that has fields and if that's even possible.
Here's basically what I'm working with
```rs
#[derive(Debug)]
pub struct Profile {
    pub user_id: Uuid,
    pub display_name: Option<String>,
    pub url_name: Option<String>,
   ..... many other fields,
    pub updated_at: NaiveDateTime,
}

#[Object]
impl Profile {
   ... 30+ resolvers
}
```
How do I split resolvers into multiple files here?

**Comment by xamgore** [comment]
Hi, Dawid. Try sharing the state between two sub-objects, like in the code below. Or move it to Box/Cow/Arc.

```rust
#[Object]
impl Query {
  async fn me(&self, ctx: &Context<'_>) -> Profile<'_> {
    let p = &ctx.data_unchecked::<..>().profile;
    Profile(DomainAProfile(p), DomainBProfile(p))
  }
}

// profile/mod.rs
#[derive(MergedObject)]
pub struct Profile<'a>(DomainAProfile<'a>, DomainBProfile<'a>)

// profile/a.rs
pub struct DomainAProfile<'a>(&'a InnerProfile);

#[Object]
impl DomainAProfile { ... }

// profile/b.rs
pub struct DomainBProfile<'a>(&'a InnerProfile);

#[Object]
impl DomainBProfile { ... }
```

**Comment by nxy7** [comment]
I've had to move InnerProfile into Arc in the end, as regular reference caused plenty of lifetime issues. Anyway that kind of solved my issue so thanks :-)
