### ISSUE TITLE
Defaults for Json<> wrapped values. 

### ISSUE THREAD

**Issue by ruseinov** [async-graphql/async-graphql#140]
I have managed to do this to cater for the need to supply defaults: 
```
    async fn records(
        &self,
        ctx: &Context<'_>,
        criteria: Option<Json<Criteria>>,
        #[arg(default)] skip: i32,

...
    ) 

    let criteria = criteria.unwrap_or_else(|| Json(Criteria::default()));

```

But it would be nice if I could use `#[arg(default)]` instead and it would magically assemble the above and make it optional, similar to `skip`. 

That would reduce the boilerplate amount and the extra `Option` wrapper could go as well.

**Comment by sunli829** [comment]
I added `Default` derive to the `Json` type.

**BTW: If an input value has a default value, it should not be optional, otherwise it looks very strange.**

**Comment by sunli829** [comment]
Please upgrade to `1.14.12`.

**Comment by ruseinov** [comment]
> I added `Default` derive to the `Json` type.
> 
> **BTW: If an input value has a default value, it should not be optional, otherwise it looks very strange.**

I know, but this was not possible without the default derive on JSON. Thanks!

**Comment by mwilliammyers** [comment]
> BTW: If an input value has a default value, it should not be optional, otherwise it looks very strange.

Is this true for any custom scalars that implement `Default`?

**Comment by ruseinov** [comment]
> > BTW: If an input value has a default value, it should not be optional, otherwise it looks very strange.
> 
> Is this true for any custom scalars that implement `Default`?
> 
> I wonder if this is causing: [imolorhe/altair#1256](https://github.com/imolorhe/altair/issues/1256)

Any value that has a default should work with ‘ #[arg(default)]’ I assume

**Comment by ruseinov** [comment]
works like a charm!

**Comment by ruseinov** [comment]
I'll post a sample here for others to understand how this could be used. Once we are at a later stage in our project that builds upon async-graphql among other things - I will introduce a repository with some meaningful usage examples extracted from it. 
Or if the project goes open-source it's going to be even easier.

There you go:
```rust
#[async_graphql::InputObject]
#[derive(Default)]
pub struct QueryInput {
    #[field(default)]
    pub criteria: Json<Criteria>,
    #[field(default = 20)]
    pub limit: i32,
    #[field(default)]
    pub skip: i32,
    #[field(default)]
    pub order: Json<SortCriteria>,
}

impl QueryRoot {
    async fn records(
        &self,
        ctx: &Context<'_>,
        #[arg(default)] query: QueryInput,
    ) -> FieldResult<Vec<Record>> {
        entity_by_criteria(ctx, &query).await
    }
}

```
