### ISSUE TITLE
Extension context sharing between different process steps

### ISSUE THREAD

**Issue by vstepanyuk** [async-graphql/async-graphql#1427]
I'm adding additional information to extension context via request data and would like to extract it in `Extension::resolve` method, but ctx.data_opt always returns `None`. Is there any option to pass information between different extension steps.

Code example:
```rust
pub struct Cache;

impl ExtensionFactory for Cache {
    fn create(&self) -> Arc<dyn Extension> {
        Arc::new(CacheExtension)
    }
}

struct CacheExtension;

#[async_trait::async_trait]
impl Extension for CacheExtension {
    async fn prepare_request(
        &self,
        ctx: &ExtensionContext<'_>,
        mut request: Request,
        next: NextPrepareRequest<'_>,
    ) -> ServerResult<Request> {
        let query = request.parsed_query()?.clone();
        request.data.insert(query);

        next.run(ctx, request).await
    }

    async fn resolve(
        &self,
        ctx: &ExtensionContext<'_>,
        info: ResolveInfo<'_>,
        next: NextResolve<'_>,
    ) -> ServerResult<Option<Value>> {
        let query = ctx.data_opt::<ExecutableDocument>();

// -----------------------------------------
        dbg!(&query); // - this is None
// -----------------------------------------

        next.run(ctx, info).await
    }
}```

**Comment by Miaxos** [comment]
The data you insert at this point is not the data that is present inside the context[^1].
At this point you shouldn't add new data inside the context, but what you could do is to insert a strcut with interior mutability before starting the request execution and then you get this struct ref and at the `prepare_request` you mutate it so you'll have access to this data later.

[^1]: https://github.com/async-graphql/async-graphql/blob/9297021ec4b29342cc75eb0d13a0b3c458a75a32/src/schema.rs#L737-L741

**Comment by kurotych** [comment]
> The data you insert at this point is not the data that is present inside the context[1](#user-content-fn-1-5453c6431656483cad869b76af9c5af8). At this point you shouldn't add new data inside the context, but what you could do is to insert a strcut with interior mutability before starting the request execution and then you get this struct ref and at the `prepare_request` you mutate it so you'll have access to this data later.
> ## Footnotes
> 
>     1. https://github.com/async-graphql/async-graphql/blob/9297021ec4b29342cc75eb0d13a0b3c458a75a32/src/schema.rs#L737-L741 [↩](#user-content-fnref-1-5453c6431656483cad869b76af9c5af8)

Hi, I have the same problem when I try to add a request duration logging. @Miaxos, as I understand you propose adding to CacheExtension something like `Mutex<..>` to make interior mutability.
But is it attached to a particular query?

Is it thread-safe (and/or race condition safe) if I add a unique ID to my "internal" struct in `prepare_request` step, and then use it in the next steps?

For example: 
1. I generate a unique request "ID" for Extension on `prepare_request` step 
2. Then in `parse_query` step I print the log message with this ID 
3. Then in `request` after `run` function calling I print duration time with request ID
```rust
    async fn request(&self, ctx: &ExtensionContext<'_>, next: NextRequest<'_>) -> Response {
        let start_time = Utc::now();
        let res = next.run(ctx).await;
        let duration = Utc::now() - start_time;
        // TODO Take request ID HERE
        log::info!("Duration: {}ms", duration.num_milliseconds());
        res
    }
```

**Comment by Miaxos** [comment]
> But is it attached to a particular query?
>Is it thread-safe (and/or race condition safe) if I add a unique ID to my "internal" struct in prepare_request step, and then use it in the next steps?

To put data at the beginning of each request you can do it like explained here[^1]. As this will be a new `Mutex` (for instance) for every request, you'll be able to use without any race condition, I suggest you use an async lock  as you will run in an async runtime and depending on the query kind you can have sequential or parallel compute of the query.

Then, if you have this struct with interior mutability for each request created, you can add data at the `prepare_request` it will only lives up for the duration of the request and you'll be able to use it on the next steps. Feel free to check this[^2] to understand how extensions are working and how every step are handled.

[^1]: https://async-graphql.github.io/async-graphql/en/context.html#request-data
[^2]: https://async-graphql.github.io/async-graphql/en/extensions_inner_working.html

**Comment by kurotych** [comment]
> > But is it attached to a particular query?
> > Is it thread-safe (and/or race condition safe) if I add a unique ID to my "internal" struct in prepare_request step, and then use it in the next steps?
> 
> To put data at the beginning of each request you can do it like explained here[1](#user-content-fn-1-837cf7e28af7dcaeb81e3b112f428c99). As this will be a new `Mutex` (for instance) for every request, you'll be able to use without any race condition, I suggest you use an async lock as you will run in an async runtime and depending on the query kind you can have sequential or parallel compute of the query.
> 
> Then, if you have this struct with interior mutability for each request created, you can add data at the `prepare_request` it will only lives up for the duration of the request and you'll be able to use it on the next steps. Feel free to check this[2](#user-content-fn-2-837cf7e28af7dcaeb81e3b112f428c99) to understand how extensions are working and how every step are handled.
> ## Footnotes
> 
>     1. https://async-graphql.github.io/async-graphql/en/context.html#request-data [↩](#user-content-fnref-1-837cf7e28af7dcaeb81e3b112f428c99)
> 
>     2. https://async-graphql.github.io/async-graphql/en/extensions_inner_working.html [↩](#user-content-fnref-2-837cf7e28af7dcaeb81e3b112f428c99)

Hello @Miaxos thank you for your help. It looks like I've solved my problem. 
If you are interested this is the result https://github.com/kurotych/async-graphql-logger
