### ISSUE TITLE
Improve connection/edge

### ISSUE THREAD

**Issue by mwilliammyers** [async-graphql/async-graphql#143]
This is a continuation of: https://github.com/async-graphql/async-graphql/issues/106...
Possibly related to: https://github.com/async-graphql/async-graphql/issues/103

I am reading the book/docs/code and it isn't clear if you can create an `async_graphql::connection::Connection` without iterating again (after I deserialize the results)...

Currently I use `serde` attributes etc. to transform the results from the database to something that fits the form of a Relay Cursor Connection e.g. `MyConnection<T>`/`MyConnection<User>` and then use a proc-macro to implement this generic `MyConnection<T>` for a concrete graphql type e.g. a `UserConnection`. While using proc-macros is less than ideal, this has the benefit of only iterating through the results once: when serde parses the JSON coming from my db to Rust types.

Is it possible to create an async-graphql connection like this, without iterating? e.g. deserialize directly into a `Connection` or provide `Connection` with something that is already in that format? 

If this is not possible, is there anyway we can lift the restriction that user types cannot end in `*Connection` (and `PageInfo`), so I can keep doing what I am doing without introducing breaking changes by having to rename my types to e.g. `UserConnectionCustom` (which is also really ugly haha)

**Comment by sunli829** [comment]
What you really need is json as the resolver's return value, right?

**Comment by sunli829** [comment]
I'm curious why the data you pull out of the database is a json array.

**Comment by mwilliammyers** [comment]
> What you really need is json as the resolver's return value, right?

I am not entirely sure what I want in terms of an API but, yeah giving you a `serde_json::Value`  with the appropriate structure would work for me... but I am not convinced that is the best way; I think a trait would probably work best.

> I'm curious why the query result from the database is a json array.

It is coming from Elasticsearch which is a document/JSON based db... The response looks like this:

```json
{
    ...
    "hits": {
        "total" : {
            "value": 1,
            "relation": "eq"
        },
        "max_score": 1.6011951,
        "hits": [
            {
                "_index": "twitter",
                "_type": "_doc",
                "_id": "1",
                "_score": 1.6011951,
                "sort": ["asdf"],
                "_source": {
                    "user": "test",
                    "message": "some message with the number 1",
                    "date": "2009-11-15T14:12:12",
                    "likes": 1
                },
                "highlight": {
                    "message": [
                        " with the <em>number</em> <em>1</em>"
                    ]
                }
            }
        ]
    }
}
```

where `sort` is basically just a cursor, `hits` is more or less edges, and `_source` is a `node`... The only extra logic I do is to determine `hasNextPage` by always querying for `N+1` docs and determining if I got back `<=N`. I also keep some of those extra fields (I *need* to keep highlight for clients...)

**Comment by sunli829** [comment]
`Elasticsearch Json results` -> `GQLObject` -> `async-graphql` -> `JSON`

You want to simplify it like this, right?

`Elasticsearch Json results` ->`async-graphql` -> `JSON`

**Comment by sunli829** [comment]
You want JSON to be an OutputObject, not a scalar, so you can filter the results inside of JSON, right?
```rust
async fn test(&self) -> Json {
    ...
}
```

**Comment by mwilliammyers** [comment]
Hmmm. I mean that would work but I don't know if that is a good API for `Connection`, or were you thinking that the API for `Connection` would stay the same and I could use your proposed solution as an alternative to the existing API?

**Comment by sunli829** [comment]
This is easy to implement, but the result is introspection where you can't see the data in Json, but you can query it.

```rust
async fn test(&self) -> Json {
    ...
}
```

**Comment by mwilliammyers** [comment]
That would be different form the `Json<T>` scalar, correct?

**Comment by sunli829** [comment]
Yeah, this is an ObjectType, not a scalar.

**Comment by sunli829** [comment]
But introspection doesn't see the fields in this object, which looks rather strange.

**Comment by sunli829** [comment]
I really don't recommend doing it this way, async-graphql is type-safe, it breaks all of this.

**Comment by mwilliammyers** [comment]
Yeah. I won’t do It that way; the fields need to be seen from introspection. Is there anyway we can make it so types can end in `Connection`? It should be fine as long as you don’t use both at the same time?

**Comment by sunli829** [comment]
If you don't need to see the fields in JSON in introspection, I can easily add this functionality.

**Comment by sunli829** [comment]
That's what you want, right?

```rust
async fn test(&self) -> OutputJson {
    serde_json::json!({
        "a": 1,
        "b": 2
    })
}
```

```graphql
   { test { a } } # { "test": { "a": 1 } }
   { test { a b } } # { "test": { "a": 1, "b": 2 } }
```

**Comment by mwilliammyers** [comment]
I need to see the fields in introspection, so this solution won’t work 😕

**Comment by mwilliammyers** [comment]
> Is there anyway we can make it so types can end in `Connection`?

I can open a PR for that if you are ok with it...

**Comment by sunli829** [comment]
> > Is there anyway we can make it so types can end in `Connection`?
> 
> I can open a PR for that if you are ok with it...

Thank you, but I want to know how you're going to do this?

**Comment by mwilliammyers** [comment]
I define a custom scalar named `ID` (that is constrained to be a V1 UUID for database sorting performance reasons) and I haven't had any trouble with it clashing with the `ID` defined in `async-graphql`... so I figured it be ok to remove the check for the name

**Comment by sunli829** [comment]
> I define a custom scalar named `ID` (that is constrained to be a V1 UUID for database sorting performance reasons) and I haven't had any trouble with it clashing with the `ID` defined in `async-graphql`, so I figured it would be ok to remove the check for names ending in `Connection`.
> 
> What happens if we get rid of this check?
> 
> https://github.com/async-graphql/async-graphql/blob/cfd652576f899d941f7a21882db021f24b6ec81a/async-graphql-derive/src/utils.rs#L16-L33

It can be removed without any problems... Just to conform to the GraphQL specification.
