### ISSUE TITLE
Support axum 7

### ISSUE THREAD

**Issue by ziimakc** [async-graphql/async-graphql#1430]
Axum was updated to [version 7](https://github.com/tokio-rs/axum/blob/main/axum/CHANGELOG.md) which doesn't work well with async-graphql.

## Expected Behavior
No errors.

## Actual Behavior
```
let app = Router::new().route( "/", get(playground).post_service(GraphQL::new(gql_schema.schema)));
/*
the trait bound `GraphQL<async_graphql::Schema<graphql::schema::Query, graphql::schema::Mutation, EmptySubscription>>: tower_service::Service<axum::http::Request<Body>>` is not satisfied
the trait `tower_service::Service<http::request::Request<B>>` is implemented for `GraphQL<E>` */
```

## Steps to Reproduce the Problem

1. Clone [example](https://github.com/async-graphql/examples/blob/966d899c65a1255be4a6f85d0a825a945e4bbb93/axum/starwars/src/main.rs).
2. Update to axum 7
3. Run cargo check

## Specifications

- Version: axum 0.7.1
- Platform: windows
- Subsystem: wsl 2/ubuntu 22

**Comment by azzamsa** [comment]
Then we need to update the example https://github.com/async-graphql/examples/tree/master/axum
