### ISSUE TITLE
Wrong type_name in EmptySubscription

### ISSUE THREAD

**Issue by TECHNOFAB11** [async-graphql/async-graphql#1435]
https://github.com/async-graphql/async-graphql/blob/9086ca7ef0bf89723bbfe6d054e7f086b0b1cbf0/src/types/empty_subscription.rs#L16

Got a panic because I used the EmptyMutation and EmptySubscription at the same time, is it intentional that EmptySubscription has "EmptyMutation" as type_name?

**Comment by xamgore** [comment]
Could you make a PR, please? The panic message as well as the minimal reproducible example would be helpful too.
