### ISSUE TITLE
How to rename a field on a async_graphql::Object?

### ISSUE THREAD

**Issue by elertan** [async-graphql/async-graphql#144]
I have a situation as shown below:
```rust
pub struct MyStruct;

#[async_graphql::Object]
impl MyStruct {
    // I want to rename this field to 'type' because the crate changes it into 'rType'
    pub async fn r#type(&self) -> i32 { 1337 }
}
```

I have tried applying `[arg(name="type")]` but that didn't work.

**Comment by sunli829** [comment]
p
```
pub struct MyStruct;

#[async_graphql::Object]
impl MyStruct {
   #[field(name="type")]
    pub async fn r#type(&self) -> i32 { 1337 }
}
```

`#[arg(name="..")]` is use for fields argument.

**Comment by sunli829** [comment]
> I want to rename this field to 'type' because the crate changes it into 'rType'

If so, it's a bug and I'll see how it works.

**Comment by sunli829** [comment]
This is a bug and you don't need to manually change the field name.

**Comment by sunli829** [comment]
`syn` gives me `rType` and doesn't tell me it's actually an `r#type`, you have to rename the field manually.

**Comment by elertan** [comment]
That's a bummer, that's lost information. But renaming it isn't too much of a hassle either. Thanks for taking a look 👍
