### ISSUE TITLE
Share data between guard and resolver

### ISSUE THREAD

**Issue by 4xy0m** [async-graphql/async-graphql#1456]
Hello, I need to auth a user in a guard to verify their permission. But, I also require user data in the resolver. How can I pass the authenticated user from the guard to the resolver without having to authenticate the user again? Note that I'm not using a middleware since not all my resolvers need authentication.

**Comment by Miaxos** [comment]
I suggest you put an `AuthContext` per request, which would be available in your `Guard` through the `Context`.

You put a auth function for the `AuthContext` with memoization to auth yourself in the guard and you can access it without any call inside your resolver if you need it.
