### ISSUE TITLE
Relay @defer requires a label in the second chunk

### ISSUE THREAD

**Issue by sync** [async-graphql/async-graphql#146]
Trying to use defer with relay and get the following error:

```
Invariant Violation: RelayModernQueryExecutor: invalid incremental payload, expected `path` and `label` to either both be null/undefined, or `path` to be an `Array<string | number>` and `label` to be a `string`
```

Found here: https://github.com/facebook/relay/blob/2859aa8df4df7d4d6d9eef4c9dc1134286773710/packages/relay-runtime/store/RelayModernQueryExecutor.js#L1267

<img width="1122" alt="Screen Shot 2020-06-04 at 5 44 56 pm" src="https://user-images.githubusercontent.com/21725/83729673-47978a00-a68b-11ea-92a4-22ea0096dde8.png">

This is what my chunk look like:

```

---
Content-Type: application/json
Content-Length: 1113

{"data":{"room":{"title":"28 Elizabeth Street, Malvern","host":{"contactIq":null}}}}
---
Content-Type: application/json
Content-Length: 61

{"path":["room","host","contactIq"],"data":{"fullName":null}}
-----
```

Looking at what facebook.com does with their @defer they definitely have label in their response payload

```
{"data":{"node":{"__typename":"User","id":"726995694","timeline_list_feed_units":{"edges":[{"node": 
.....
{"label":"ProfileCometTimelineFeed_user$stream$ProfileCometTimelineFeed_user_timeline_list_feed_units","path":["node","timeline_list_feed_units","edges",1],"data":{"node":
```

**Comment by sync** [comment]
I can see that your example works with apollo but I was super keen to get this also working with relay and it seems that there is a label missing in the second chunk. Do you have any idea of what it could be ?

**Comment by sunli829** [comment]
I'll see how to RelayModernQueryExecutor compatible.

**Comment by sync** [comment]
it seems that it is happy with any label, i've hacked around on the client 
```
        console.log('parts: ', parts);
        if (parts[1].path) {
          parts[1] = {
            ...parts[1],
            label: 'fake',
          };
          console.log('has path');
        }
```

and as soon as i add a label it is fine

**Comment by sync** [comment]
so basically if the server would add a path from:
```
{"path":["room","host","contactIq"],"data":{"fullName":null}}
```

to

```
{"label": "SOMETHING_HERE", "path":["room","host","contactIq"],"data":{"fullName":null}}
```

it stops complaining, i don't understand how those labels are computed tough and if adding a random label has any consequences.

**Comment by sync** [comment]
as an example facebook.com label look like this:
```
ProfileCometTimelineFeed_user$stream$ProfileCometTimelineFeed_user_timeline_list_feed_units
```

**Comment by sync** [comment]
but then i don't get my second chunk in the client side, it is always null

**Comment by sunli829** [comment]
Can you provide an example by opening a PR in the `async-graphql-examples` repo?

**Comment by sync** [comment]
Give me 2 hours, will do this right after dinner

**Comment by sunli829** [comment]
Thank you. 😁

**Comment by sync** [comment]
still working on it, will come soonish :-)

**Comment by sync** [comment]
Did a little bit more digging, if you look at this they have a very different way of doing @defer in relay:

https://github.com/facebook/relay/blob/bec2bb31d47b5cb247825ad81eac297b8b4c87c0/compiler/crates/graphql-transforms/tests/defer_stream/fixtures/fragment-with-defer-if-arg.expected

```
{
  books {
    title
    ...BookFragment @defer(label: "DeferredFragmentLabel")
  }
}

fragment BookFragment on Book {
  comments {
    text
    user
  }
}
```

But when i try to do this i get:

<img width="722" alt="Screen Shot 2020-06-05 at 8 45 13 am" src="https://user-images.githubusercontent.com/21725/83817744-eadab480-a708-11ea-97ac-ee0877c69f15.png">

**Comment by sunli829** [comment]
The use of the `@defer`directive on fields is currently only supported.

**Comment by sync** [comment]
https://github.com/async-graphql/async-graphql/pull/150 gave it a shot, it works now

**Comment by sync** [comment]
still need to test it with relay

**Comment by sync** [comment]
and need to add the possibility to specify a label

**Comment by sync** [comment]
Now that defer works on the server, relay automatically trying to add a label to defer

```
query pagesQuery {
  books {
    ...pages_book
  }
}

fragment pages_book on Book {
  title
  author
  ...pages_comments_book @defer(label: "pages_book$defer$pages_comments_book")
}
fragment pages_comments_book on Book {
  comments {
    text
    user
  }
}
```

**Comment by sync** [comment]
So i think if we add support to label to defer it should then become compatible with relay !

**Comment by sunli829** [comment]
I just got up and was about to check this out. 😁

**Comment by sunli829** [comment]
@sync I added this in the master branch, could you please test it?

**Comment by sync** [comment]
amazing testing this now!!

**Comment by sunli829** [comment]
I forgot to say, please update `async-graphql/examples`.

**Comment by sync** [comment]
I am a little confused, do I have to rebase master on top of #150  ? if now it complains i can't use defer of top of a fragment ....

**Comment by sync** [comment]
i'll push a udpate to the graphql example so you should be able to run it yourself

**Comment by sunli829** [comment]
I've already run it, but I don't know if it's the right result.

**Comment by sync** [comment]
see https://github.com/async-graphql/examples/pull/14 i think it it is working

**Comment by sync** [comment]
I am rebase my pr #150 on top of 150 but i don't think it's streaming when ...fragment @defer

**Comment by sync** [comment]
we should stop using `@defer` it's a person on github

**Comment by sunli829** [comment]
Currently, @defer only supports field, I will consider how to solve the problem.

**Comment by sync** [comment]
ok cool sorry i misunderstood. I appears that relay only does the magic if deferring a fragment. Apollo might have gone a different way.

**Comment by sync** [comment]
but i'll check if it also works when not deferring a fragment, give me 5

**Comment by sync** [comment]
yes it doesn't work. I can see there is label now. Thank you. 

The funny thing is when i spread defer on a fragment the relay client adds a label on the defer automatically, changing the original request.

original request
```
query pagesQuery {
  books {
    ...pages_book
  }
}

fragment pages_book on Book {
  title
  author
  ...pages_comments_book @defer
}
fragment pages_comments_book on Book {
  comments {
    text
    user
  }
}
```

modified by the relay client
```
query pagesQuery {
  books {
    ...pages_book
  }
}

fragment pages_book on Book {
  title
  author
  ...pages_comments_book @defer(label: "pages_book$defer$pages_comments_book")
}
fragment pages_comments_book on Book {
  comments {
    text
    user
  }
}
```

**Comment by sync** [comment]
There is so much magic and you can see those in their test suite but not really documented :-(

**Comment by sunli829** [comment]
I guess this label can't be repeated, it's an ID.

**Comment by sync** [comment]
Found more info:

https://github.com/graphql/graphql-spec/issues/704

Note that @defer can only be applied to fragment spreads and inline fragments, not to fields, and @stream can only be applied to fields. So they can't co-exist on a selection.

**Comment by sunli829** [comment]
This is just a proposal, and once the defer specification is formally confirmed I'll add it very quickly.

**Comment by sunli829** [comment]
Is everything all right now? 😁 @sync

**Comment by sync** [comment]
After more experiments I realised that relay only supports deferring on a fragment. Is it something you would be interested supporting ? I wonder if I could help, or do you reckon adding support for defer on a fragment is quite complicated ? I looked everywhere and don’t see any other library supporting that feature. But I know it’s used on Facebook.com. Probably using their own graphql server implementation. But I don’t think it should be your priority you certainly have more things to work on. If you don’t think it’s important I am happy to close this issue and add it in a roadmap somewhere for later on.

**Comment by sunli829** [comment]
This feature is easy to add, but I don’t know which specification should be followed, is it https://github.com/graphql/graphql-spec/issues/704?
But I see `@deferrable` instead of `@defer`.

**Comment by sync** [comment]
its @defer

**Comment by sync** [comment]
any comment from `josephsavona` is good, he is on the relay team 

from him:
```
Note that @defer can only be applied to fragment spreads and inline fragments, not to fields, and @stream can only be applied to fields. So they can't co-exist on a selection.
```

**Comment by sunli829** [comment]
I'm going to remove the previous `@defer` implementation, and the new version is only compatible with `Relay`.

**Comment by sync** [comment]
Sounds awesome 👏 also remember the label is provided on defer from the client. The relay project in the sample repo is all setup and let me know if you want me to test anything

**Comment by sync** [comment]
btw this is the client PR: https://github.com/async-graphql/examples/pull/14 for defer on the fragment
