### ISSUE TITLE
Has anyone does any benchmarks because im getting extremely poor results and I do not know why?

### ISSUE THREAD

**Issue by Haaroon** [async-graphql/async-graphql#1477]
I am benchmarking async-graphql to see how well it peforms.  I use the simple "poem/starwars" example and built and run the server via `cargo run -r`. Its running on an AWS S3 box with 64 cores and 128GBs of ram. I first tried to replicate this benchmark https://github.com/graphql-crystal/benchmarks/ but i suspect they do not actually check the result of the json object to see if it has any errors or not. 

I used bombardier to test the async-graphql server, the starwars example, with a very simple query to get the name of id 1000, which is luke skywalker, and bombadier shows very impressive numbers of about 300k requests with almost all HTTP 200. but these HTTP 200 are responses from the server, but the server has thus timed out and sends HTTP 200 with an error message inside of it....

I then wrote another benchmark with the "locust" python tool which does the same thing however it can check the result and my suspicious are indeed correct, there are plenty of failures. Running the request remotely to the server. with 1000 users and a 100 user ramp up, after a few seconds it starts to fail.

I also then wrote yet another benchmark using artillery and again, the server starts to fall over.

Has anyone done any benchmarks to see how well this peforms?

Have i done anything wrong in my build?

**Comment by Miaxos** [comment]
Hello,

> Have i done anything wrong in my build?

Can you provide a repository of your benchmarks?

>Has anyone done any benchmarks to see how well this peforms?

Yes, you have some benches in the repository, there are benchmarks available in the wild, for instance one in the tailcall repository (tailcall is built on top of `async-graphql`).[^1].

[^1]: https://github.com/tailcallhq/graphql-benchmarks

**Comment by Haaroon** [comment]
yes here is my repo https://github.com/Pometry/Raphtory/tree/feature/even-more-benchmarks/comparison-benchmark/graphql-benchmark/async_graphql_benchmarks

**Comment by Haaroon** [comment]
@Miaxos i cant figure out if the tailcallhq benchmark actually checks the result of the json they are calling?

**Comment by Haaroon** [comment]
Your completely mistaken. I am not talking about HTTP 200. It is completelly incorrect to return a HTTP 200 if the actual underlying request for data fails. Please do a test and check if the actual contents of the response are valid or not. Because returning a HTTP 200 assumes the request was correct and the response was valid. When in fact the GQL server is timing out and its being wrapped in a HTTP 200.

**Comment by Haaroon** [comment]
When adjusted I can hit much higher numbers, but still not in the hundreds, only around 5-6k a second before it starts timing out again. The error its showing now is errors.ECONNRESET. This is with 30 users doing 200 requests each.
