### ISSUE TITLE
Get mutable referenece to the global data defined in the `Context` or `Schema`

### ISSUE THREAD

**Issue by obeis** [async-graphql/async-graphql#1478]
## Description of the feature

Add `data_mut()` method similar to [`data()`](https://docs.rs/async-graphql/latest/async_graphql/context/trait.DataContext.html#tymethod.data) for getting mutable reference.

## Code example

```rust
#[Object]
#[async_trait]
impl Queries for RootQuery {
    async fn resolver(&self, _ctx: &Context<'_>) -> Result<bool> {
            ctx.data_mut::<MyType>().unwrap();
           // ...
            Ok(true)
    }
}
```

**Comment by Miaxos** [comment]
Due to the way `async-graphql` is working, you could have multiple queries executed at the same time, so you will need to implement the locking yourself.

Related: https://github.com/async-graphql/async-graphql/issues/326

**Comment by obeis** [comment]
@Miaxos Can you please provide me an example.
