### ISSUE TITLE
Custom directive

### ISSUE THREAD

**Issue by sunli829** [async-graphql/async-graphql#148]
**I want to replace the existing `Guard` and `InputValidator` implementations with custom directives.**

# On Field definition

## Definition

```rust
use async_graphql::*;
use async_graphql::directives::*;

enum Role {
    Guest,
    Member,
    Admin,
}

#[Directive]
struct Auth {
    role: Role,
}

#[async_trait::async_trait]
impl<'a, T: OutputValueType + Sync + Send + 'a> OnFieldDefinition<'a, T> for Auth {
    async fn before_field_resolve(&'a self, ctx: &Context<'_>) -> FieldResult<()> {
        if let Some(role) = ctx.data_opt::<Role>() {
            if *role == self.role {
                return Ok(());
            }
        }
        Err("forbidden".into())
    }
}

struct Query;

#[Object]
impl Query {
    #[field(directive(Auth(role = "Role::Admin")))]
    async fn value(&self) -> i32 {
        10
    }
}
```

- [X] OnFieldDefinition
    - [X] Object
    - [x] SimpleObject
    - [x] Subscription
- [x] OnInputValue
    - [x] Object field arguments
    - [x] Subscription field arguments
    - [x] InputObject fields

**Comment by neshanthan** [comment]
This sounds good, if we are moving to directives, should I hold off from writing the field guard documentation?

**Comment by sunli829** [comment]
> This sounds good, if we are moving to directives, should I hold off from writing the field guard documentation?

Yes. 😀

**Comment by sunli829** [comment]
I ran into some problems implementing this feature, and I'll turn it on again when I find a solution.
