### ISSUE TITLE
Question about #[SimpleObject] and #[InputObject]

### ISSUE THREAD

**Issue by tonis2** [async-graphql/async-graphql#149]
I would like to to use `#[SimpleObject]` and `#[InputObject]` on a same struct, so i could use same data for query's parameters and output.

For example i would like to build a query

`fn filter_data(&self, data: DataSchema) -> Vec<DataSchema> {`

   _here_ i filter database entries based on data params and spew out the _results.._
`}`

Thanks

**Comment by sunli829** [comment]
Currently, only two structures can be defined.

**Comment by tonis2** [comment]
Okay thanks, using Json(DataSchema) as input type helped me out too.

**Comment by AurelienFT** [comment]
Hello,

Keep two different structures is a choice or it will evolve in the future to allow us  to have one structure ?
@sunli829

**Comment by sunli829** [comment]
I thought about it, I can support this feature, I am trying.

**Comment by AurelienFT** [comment]
This will be awesome because Juniper do not support it at all.

**Comment by zicklag** [comment]
@tonis2 could you explain a bit more about how you used `Json(DataSchema)` to help you problem? I'm in the same situation, but I don't understand exactly what type you specified for the input type.

**Comment by zicklag** [comment]
I'm experimenting with a way to automatically generate the input and output types with an attribute macro here:

https://github.com/katharostech/async_graphql_extras

```rust
/// Information about the user
#[graphql_object(
    // Custom doc string for generated `UserDataInput` struct
    input_object_doc = "Input for user information data",
)]
pub struct UserData {
    username: String,
    display_name: String,

    // Indicate that this is also a `graphql_object`
    #[graphql_object(nested)]
    favorites: UserFavorites,
}

/// A user's favorite stuff
#[graphql_object]
pub struct UserFavorites {
    food: String,
}

#[Object]
impl Query {
    /// Ping endpoint that returns the same object as the input
    async fn ping(&self, user_input: UserDataInput) -> UserData {
        user_input.into()
    }
}
```

Rather simple and straight-forward for now. I'm trying to see if I can also automatically generate an input type that can be used to patch fields so that you can trivially create an "update" endpoint that allows you to pass only the fields that you want changed.

**Comment by Acidic9** [comment]
This feature would be great! My project is quite dependant on it :(
