### ISSUE TITLE
Guard trait lifetime

### ISSUE THREAD

**Issue by mishaszu** [async-graphql/async-graphql#1497]
Hello,

I have been using Guards for some time with no problem as defined in [documentation](https://async-graphql.github.io/async-graphql/en/field_guard.html).

I recently made Rust workspace instead of a single project and discovered that the same code stopped compiling.

With rustc v1.76, edition "2021" and resolver "2":
```
#[async_trait::async_trait]
impl Guard for AdminGuard {
    async fn check(&self, ctx: &Context<'_>) -> Result<()> {
        todo!()
    }
}
```

I got:
> lifetime parameters or bounds on method `check` do not match the trait declaration
> lifetimes do not match method in trait (rustc E0195)
> https://doc.rust-lang.org/error-index.html#E0195

The same code works fine if not placed in the workspace project.
I'm a bit puzzled by this, is there any way to fix it?

#### Update
After cleaning up `target` dir it seems I have this problem in all kind of projects not only for workspaces.

**Comment by mishaszu** [comment]
I solved it.

The problem occurred because I added:
`#[async_trait::async_trait]`
It shouldn't be there when implementing the Guard trait.

**Comment by humb1t** [comment]
Thank you @mishaszu — I upgraded to new async graphql and axum 0.7 and was figuring out what's wrong with async-trait. My eye didn't catch that now we don't need to use it for traits like Guard or Loader.

For those who will search by my error message, will paste it here so they will jump into that solution in this issue:

```
error[E0195]: lifetime parameters or bounds on method `load` do not match the trait declaration
```
