### ISSUE TITLE
UploadValue should be async

### ISSUE THREAD

**Issue by mwilliammyers** [async-graphql/async-graphql#151]
We should make `UploadValue.content` be async. It is probably not already async because we didn't want to depend on tokio vs async-std etc., but could we: 
- make the `content` field store a `Box<dyn futures::io::AsyncRead>`?
- have different implementations for tokio vs async-std etc. behind feature gates? 
- do something else?

**Comment by sunli829** [comment]
You can use `futures::io::AllowStdIo`.

**Comment by mwilliammyers** [comment]
But that will block the event loop:

> If these types issue an error with the kind `io::ErrorKind::WouldBlock`, it is expected that they will notify the current task on readiness. Synchronous std types should not issue errors of this kind and are safe to use in this context. However, using these types with `AllowStdIo` will cause the event loop to block, so they should be used with care.

**Comment by sunli829** [comment]
Do you have a big file?

**Comment by sunli829** [comment]
Why not use synchronization API to process files, they have higher performance.

**Comment by sunli829** [comment]
Now whether `tokio` or `async-std`, their asynchronous file IO is actually running in the thread pool.
I think asynchronous file IO has value only after `io-uring` support.

**Comment by mwilliammyers** [comment]
Yes fairly large, my files will be 20 MB to 1-2 GB (they will be several hours of audio).

This is a big reason why I switched from juniper (they are still working on async support)...

> Now whether tokio or async-std, their asynchronous file IO is actually running in the thread pool.
Yeah, I want all async code to run on a thread pool...

**Comment by sunli829** [comment]
> Yes fairly large, my files will be 20 MB to 1-2 GB (they will be several hours of audio).
> 
> This is a big reason why I switched from juniper (they are still working on async support)...
> 
> > Now whether tokio or async-std, their asynchronous file IO is actually running in the thread pool.
> > Yeah, I want all async code to run on a thread pool...

This feature is easy to add, but you don't want depend on `tokio` or `async-std`, which makes it hard for me.

**Comment by mwilliammyers** [comment]
I already depend on `tokio`, I am saying I am not sure `async-graphql` should force users into choosing a runtime.

**Comment by mwilliammyers** [comment]
it doesn't matter a ton to me, I am currently using `base64` inlined into the request body but I was thinking about refactoring to use `Upload`, but I was surprised to find that it was sync, which seemed weird to me given that that the crate is called `async-graphql` 😄

**Comment by sunli829** [comment]
> it doesn't matter a ton to me, I am currently using `base64` inlined into the request body but I was thinking about refactoring to use `Upload`, but I was surprised to find that it was sync, which seemed weird to me given that that the crate is called `async-graphql` 😄

This requires the introduction of a separate thread pool, which I don't think is a good idea.

**Comment by mwilliammyers** [comment]
Ok, well we might want to benchmark it. Regardless, we should make it very obvious in the documentation that file uploads are synchronous; I just happen to catch it because it was `Read` and not `AsyncRead`. 

I would be happy to open a PR adding the documentation if you think that is a good idea.

**Comment by sunli829** [comment]
https://users.rust-lang.org/t/file-reading-async-sync-performance-differences-hyper-tokio/34696/5

> I would be happy to open a PR adding the documentation if you think that is a good idea

Welcome to PR. 😁

**Comment by sunli829** [comment]
Rust's asynchronous code is slow, much more than synchronous...

**Comment by mwilliammyers** [comment]
I am going to close this for now, although I think we should benchmark different solutions in the future...
