### ISSUE TITLE
Question: is there a way I can use the `async-graphql` machinery to serialize `Objects`, `SimpleObjects` into JSON?

### ISSUE THREAD

**Issue by trevorbernard** [async-graphql/async-graphql#1519]
I have an GQL API and REST API and I would like to reuse my GQL objects and return them as JSON in the REST API. I could sprinkle `serde::Serialize` on each object but I figured I would ask here first.

**Comment by xamgore** [comment]
For `InputType` that is easy: `input.to_value().into_json()`.

For `OutputType` it is not, as each field must be _resolved_ into `async_graphql::Value`, and those depend on a _selection set_ `{ field1 field3 }` and the current _context_. If you do this by yourself, you reimplement the GraphQL server spec. Instead, you may use the current implementation: `schema.execute(Request { query, .. }).data.into_json()`.

**Comment by trevorbernard** [comment]
@xamgore Thanks for the answer
