### ISSUE TITLE
Return vector of interface implementation

### ISSUE THREAD

**Issue by nikolim** [async-graphql/async-graphql#1536]
Question: how to return a vector of an interface implementation instead of a vector of the interface?

This question/bug was raised before [here](https://github.com/async-graphql/async-graphql/issues/512). Are there any updates?

**Comment by xamgore** [comment]
Well, the obvious workaround is a dynamic schema extension.

**Comment by nikolim** [comment]
@xamgore thanks for your answer. Do you have an example or reference how this would work? Thanks a lot

**Comment by xamgore** [comment]
As far as I remember, `async_graphql` does not ensure resolvers' implementation satisfies the schema, thus you may re-register a different type for `B0`. I can't show how exactly, but the idea is following: you load schema from #[macros] defined structs and resolvers, then do `let schema = schema.a_method_that_registers_new_type("B0", ...)` and that's it.
