### ISSUE TITLE
Use custom filter with Connection type

### ISSUE THREAD

**Issue by bnjjj** [async-graphql/async-graphql#154]
My issue is that I want to use a Relay Connection so I have my resolver like this:
```rust
pub async fn all_users(
        &self,
        context: &Context<'_>,
        after: Option<String>,
        before: Option<String>,
        first: Option<i32>,
        last: Option<i32>,
        filter: users::Filter,
    ) -> FieldResult<Connection<usize, User, EmptyFields, EmptyFields>> {
...
}
```

So I have a `filter` but if I want to implement `Datasource` over my struct under the hood I can't pass my filters to the `execute_query` (https://docs.rs/async-graphql/1.14.15/async_graphql/connection/trait.DataSource.html#tymethod.execute_query) from the `Datasource` trait. Do you have an idea how I can implement it ?

**Comment by sunli829** [comment]
You can use the `connection::query` function to move the `filter` into the closure.

**Comment by sunli829** [comment]
This can be done, depending on which one you prefer.

```rust
struct MyDataSource {
    filter: users::Filter,
}

impl DataSource for MyDataSource {
   ...
}
```

**Comment by bnjjj** [comment]
Hmm I have some troubles. Why is it `FnMut` https://github.com/async-graphql/async-graphql/blob/master/src/types/connection/mod.rs#L256 ? Due to this it seems I can't move my filter inside this closure

**Comment by sunli829** [comment]
My fault. This should be FnOnce，can you fix it for me? I'm ready for bed...

**Comment by bnjjj** [comment]
Done https://github.com/async-graphql/async-graphql/pull/156 let me know if I forgot something. It’s also very late for me haha

**Comment by sunli829** [comment]
Released `v1.14.19`

**Comment by bnjjj** [comment]
Will check this on Monday. If it resolves my issue I will close it

**Comment by bnjjj** [comment]
Ok it's much better and usable now ! We can close it :) Thank you
