### ISSUE TITLE
request-scoped DataLoader

### ISSUE THREAD

**Issue by lasantosr** [async-graphql/async-graphql#1567]
On the [documentation](https://async-graphql.github.io/async-graphql/en/dataloader.html#dataloader), `DataLoader` is mentioned as a _request-scope batch and caching solution_, but in the [example](https://github.com/async-graphql/examples/blob/master/tide/dataloader/src/main.rs) it's loaded right into the schema itself, rather than the request.

This is not ideal, as we're missing the authenticated subject and we're using the same DL across all requests, meaning that if a request gets 800 records and another request gets 1 record at the same time, they both will share the delay of loading 801 records.

I'd like to use per-request dataloaders, to be able to use the authenticated subject on the context (related to #1002 and #1317).

Ideally, the `Loader` impl is the same but it receives some kind of context, that it's forwarded from the `DataLoader`.

Maybe we could have some kind of data loader registry on the schema, and a new dataloader is created per-request when first requiring it (maybe with the just-stabilized _LazyLock_, i'm not sure about the performance penalty of creating every DL for every request even if not used vs the lazy lock).

¿Is there some example on how to achieve this that doesn't require to extend the key with the authenticated subject?

**Comment by SvetlinZarev** [comment]
I've also noticed that the cache is global. It would be nice to have per-request data-loaders/cache.

**Comment by sunli829** [comment]
Create `DataLoader` for each request like this.

```rust
let resp = schema.execute(Request::new("...").data(DataLoader::new(MyLoader, tokio::spawn))).await;
```

https://docs.rs/async-graphql/latest/async_graphql/struct.Request.html#method.data

**Comment by lasantosr** [comment]
I was hoping to avoid creating all (for example 10) dataloaders for every request, even if a particular request doesn't need all of them.

But maybe that's better than having a single dataloader that receives the request context.
