### ISSUE TITLE
Subscription panics when unsubscribing from exhausted stream

### ISSUE THREAD

**Issue by nicolaiunrein** [async-graphql/async-graphql#157]
consider this endpoint:
```rust
#[gql::Subscription]
impl SubscriptionRoot {
    async fn test(&self, _: &gql::Context<'_>) -> impl Stream<Item = bool> {
        futures::stream::once(async move { true })
    }
}
```

when I do a subscription query in playground I get a value as expected and when I then stop the subscription my application panics with `thread 'actix-rt:worker:0' panicked at 'invalid key', <::std::macros::panic macros>:2:4`.
However I can resolve this issue by chaining a pending stream:
```rust
futures::stream::once(async move { true }).chain(futures::stream::pending())
```
Besides the bug I wonder what the spec says about exhaustive streams. Shouldn't the subscription be terminated server-side somehow when there are no more values to come?

**Comment by sunli829** [comment]
I fixed this problem on the master branch, could you test it for me?

**Comment by sunli829** [comment]
I deleted the exhausted stream here, but when unsubscribing from the client, I didn't check it already removed.

https://github.com/async-graphql/async-graphql/blob/aa1b2b61cc0d3fd2da9114b34cae1e14c906473a/src/subscription/connection.rs#L182
