### ISSUE TITLE
`OneofObject` rejects empty object

### ISSUE THREAD

**Issue by frederikhors** [async-graphql/async-graphql#1575]
If I have this oneOf object:

```graphql
input PlayerFilter {
    name: StringFilter
}

input StringFilter @oneOf {
    eq: String
    startWith: String
    endWith: String
}
```

And I send to backend this:

```js
{ name: {} }
```

`async-graphql` errors with:

```
Oneof input objects requires have exactly one field
```

And I think that's not correct.

What do you think?

**Comment by fiadliel** [comment]
From https://github.com/graphql/graphql-spec/pull/825

> OneOf Input Objects are a special variant of Input Objects where the type system asserts that exactly one of the fields must be set and non-null, all others being omitted.

Also:
>To make this change minimally invasive I wanted: ...
> ...
> To accomplish this, we add the "exactly one value, and that value is non-null" as a validation rule that runs after all the existing validation rules - it's an additive change.

What do you think the behavior should be, and why?

**Comment by frederikhors** [comment]
Sorry, I know this is the spec. What I'm saying is that using `{ name: {} }` in javascript is better than:

```js
let filters = if (something) {
    { name: { eq: something } }
} else {
    undefined
}
```

or

```js
let filters = something ? { name: { eq: something } } : undefined
```

each time.

I would like `async-graphql` to be able to discard empty objects as if they were undefined.
