### ISSUE TITLE
Json<T>  scalar with a default value causes GraphQL Playground to fail the introspection query.

### ISSUE THREAD

**Issue by ruseinov** [async-graphql/async-graphql#158]
```
#[async_graphql::InputObject]
pub struct AssetInput {
    pub asset_type_id: ObjectId,
    pub data: Json<JsonMap>,
}
```
A definition like this results in 
```
{
  "error": "Cannot convert value to AST: {}."
}
```

Queries work fine though, so I assume that this is some sort of problem with ObjectId Scalar definition.

**Comment by hapcode** [comment]
I've same problem if I use `#[field(default)]` for a field with a scalar value that is serialized to an object:

```rust
#[InputObject]
struct AddTopicInput {
    #[field(default)]
    attrs: TopicAttrs,
}

#[derive(Clone, Serialize, Deserialize)]
#[serde(transparent)]
pub struct TopicAttrs {
    attrs: IndexMap<String, Vec<String>>,
}

impl Default for TopicAttrs {
    fn default() -> Self {
        Self {
            attrs: IndexMap::default(),
        }
    }
}

#[Scalar(name = "TopicAttrs")]
impl ScalarType for TopicAttrs {
    fn parse(value: Value) -> InputValueResult<Self> {
        let json = serde_json::Value::from(value);
        Ok(serde_json::from_value::<Self>(json)?)
    }

    fn to_value(&self) -> Value {
        serde_json::to_value(&self).unwrap().into()
    }
}
```
My workaround is to use `attrs: Option<TopicAttrs>` in `AddTopicInput` and then `input.attrs.unwrap_or_default()` in a mutation.

**Comment by sunli829** [comment]
> ```
> #[async_graphql::InputObject]
> pub struct AssetInput {
>     pub asset_type_id: ObjectId,
>     pub data: Json<JsonMap>,
> }
> ```
> 
> A definition like this results in
> 
> ```
> {
>   "error": "Cannot convert value to AST: {}."
> }
> ```
> 
> Queries work fine though, so I assume that this is some sort of problem with ObjectId Scalar definition.

I tried and didn't meet the problem you described.

**Comment by sunli829** [comment]
> I've same problem if I use `#[field(default)]` for a field with a scalar value that is serialized to an object:
> 
> ```rust
> #[InputObject]
> struct AddTopicInput {
>     #[field(default)]
>     attrs: TopicAttrs,
> }
> 
> #[derive(Clone, Serialize, Deserialize)]
> #[serde(transparent)]
> pub struct TopicAttrs {
>     attrs: IndexMap<String, Vec<String>>,
> }
> 
> impl Default for TopicAttrs {
>     fn default() -> Self {
>         Self {
>             attrs: IndexMap::default(),
>         }
>     }
> }
> 
> #[Scalar(name = "TopicAttrs")]
> impl ScalarType for TopicAttrs {
>     fn parse(value: Value) -> InputValueResult<Self> {
>         let json = serde_json::Value::from(value);
>         Ok(serde_json::from_value::<Self>(json)?)
>     }
> 
>     fn to_value(&self) -> Value {
>         serde_json::to_value(&self).unwrap().into()
>     }
> }
> ```
> 
> My workaround is to use `attrs: Option<TopicAttrs>` in `AddTopicInput` and then `input.attrs.unwrap_or_default()` in a mutation.

Can you open a PR and provide a minimal test case? 😀

**Comment by ruseinov** [comment]
> I tried and didn't meet the problem you described.

Yeah, I have a much larger schema and this was just the field I had a hiccup on, but maybe the cause is a variety of factors as described by @hapcode

**Comment by hapcode** [comment]
It seems like my problem is caused by a bug in `graphql-js` of GraphQL Playground: #[1817](https://github.com/graphql/graphql-js/issues/1817). I think @ruseinov has same problem with `pub data: Json<JsonMap>`.

**Comment by ruseinov** [comment]
That is unfortunate, gonna have to wait for them then :/

**Comment by sunli829** [comment]
@ruseinov Would you like to provide a minimal test? Maybe I did something wrong.

**Comment by ruseinov** [comment]
@sunli829 I will create a dummy repo with minimal setup that reproduces the test.

**Comment by ruseinov** [comment]
There you go: https://github.com/ruseinov/graphql-introspection-test .

This would complain about fields in Criteria when you open the playground. I guess that is related to Json scalar. 

ObjectId seems to be alright here though.

**Comment by ruseinov** [comment]
It seems like the ObjectId error was random and it occurred due to ObjectId being in the same input object as a Json scalar. I have tried adding ObjectId as a field in "QueryInput" and that did not fail the AST parsing.

**Comment by sunli829** [comment]
Because `graphql-js` makes some limitations, my current recommendation is that `JSON` types don't have default values.

https://github.com/graphql/graphql-js/blob/5be7ce3bbc3c73392f871b0de66782a39958c9c6/src/utilities/astFromValue.js#L105

**Comment by ruseinov** [comment]
yeah, but that does not work for me, so I guess I'll have to live with that :/

**Comment by ruseinov** [comment]
I can probably make it optional and assign a default elsewhere. Is this issue on file at graphql-js repo?

**Comment by sunli829** [comment]
Yes, because the `Json` type does not conform to the GraphQL specification.

**Comment by ruseinov** [comment]
Curious if we could work around this by making all the Json types with default values optional under the hood. 

I did try using an option in each place the `Json` is currently used and that contributes to a bunch of ugly boilerplate, unfortunately :(

**Comment by sunli829** [comment]
Maybe you should do it like this.

```rust
type Json<T> = Option<Json<T>>;
```

**Comment by ruseinov** [comment]
Yeah, but then that introduces a bunch extra operations due to wrap/unwrap etc. I will experiment, although it would make sense to make an attribute of some sort or make Json values with defaults optional as they would break AST parsing for anyone who uses that feature. Just saying.

**Comment by ruseinov** [comment]
Also if a Json<T> has a default and marked as arg(default) it’s kind of optional already.

**Comment by ruseinov** [comment]
I have done 
```rust
pub type OptionalJson<T> = Option<Json<T>>;
```
which kinda works, but I'm forced to work with it like this:
```rust
optional_json.as_ref().unwrap().deref()
```
which is fine as I have reduce the usage to one line in the whole codebase, but the issue is I can't force 
```rust
    #[field(default)]
```
to fail when the Default trait is not implemented for an underlying type, because it is wrapped into an option. 

So when I go 
```rust
    #[field(default)]
    pub criteria: OptionalJson<Criteria>,
```
that will compile and run nicely even if `Criteria` does not implement default.

**Comment by ruseinov** [comment]
Actually no, it does not work, because 
```rust   
#[field(default)]
```
does not seem to work for 
```rust 
OptionalJson<T>
``` 
it results in None.

**Comment by ruseinov** [comment]
The final solution for this, for the time being, is removal of
```rust
    #[field(default)]
```

and this type of usage: 
```rust
query.criteria.clone().unwrap_or_default().deref()
```

It is not ideal due to extra allocations, but it will do for now. I'm expecting that type of use-case to be pretty common for anyone who uses `Json` scalar, so it might be worth optimising.

**Comment by sunli829** [comment]
I need to think about how to solve this problem gracefully.

**Comment by ruseinov** [comment]
Thanks for looking into this, I appreciate it! I also think that this is a very powerful feature, no matter how small it seems and it'll make a whole lot of difference going forward.
