### ISSUE TITLE
`name` struct breaks `#[Object]` macro

### ISSUE THREAD

**Issue by musjj** [async-graphql/async-graphql#1598]
## Expected Behavior

The presence of a struct called `name` should not break `#[Object]` macro.

## Actual Behavior

`#[Object]` macro breaks under the presence of a struct called `name`.

## Steps to Reproduce the Problem

```rust
use async_graphql::Object;

struct name; // remove to fix error

pub struct Query;

#[Object] // mismatched types expected `Name`, found `name`
impl Query {
    ...
}
```

This seems like a very niche issue, but with [`diesel`](https://github.com/diesel-rs/diesel), you often need to import structs generated and named from your database columns. Like this:

```rust
use schema::users::dsl::{name /* <- this is a struct */, username};
```

Is there a workaround to this, other than refactoring your database?

## Specifications

- Version: `v7.0.9`
- Platform: `Linux`
- Subsystem: `NixOS 24.11`

**Comment by sunli829** [comment]
fixed in `v7.0.11`
