### ISSUE TITLE
query(): The "first" and "last" parameters should be allowed to exist at the same time

### ISSUE THREAD

**Issue by simnalamburt** [async-graphql/async-graphql#1601]
## Expected Behavior
In [`async_graphql::types::connection::query`](https://docs.rs/async-graphql/7.0.10/async_graphql/types/connection/fn.query.html) function, the "first" and "last" parameters should be allowed to exist at the same time, as per [GraphQL Cursor Connection Specification](https://relay.dev/graphql/connections.htm#sec-Pagination-algorithm).

## Actual Behavior
The "first" and "last" parameters cannot exist at the same time.

https://github.com/async-graphql/async-graphql/blob/04558c6b252d036e064c3461a0b72f6d2b930eac/src/types/connection/mod.rs#L355-L357

**Comment by sunli829** [comment]
It doesn't seem to make sense that `first` and `last` exist at the same time?

**Comment by simnalamburt** [comment]
I also agree with you that having both `first` and `last` doesn't make sense. However, the Relay's GraphQL Cursor Connection Specification explicitly allows this behavior and describes exactly how it should function.
