### ISSUE TITLE
ObjectId <-> ID conversion is broken after an update to 0.14.20

### ISSUE THREAD

**Issue by ruseinov** [async-graphql/async-graphql#161]
```  
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `async_graphql::base::OutputValueType` is not implemented for `bson::oid::ObjectId`
```

for
```
impl RecordType {
    async fn id(&self) -> Option<ObjectId> {
        self.id.clone()
    }
}
```

and

```
the trait bound `bson::oid::ObjectId: std::convert::From<async_graphql::scalars::id::ID>` is not satisfied
```
for 
```
    let id: ObjectId = id.try_into()?;
```

where `id: ID`

**Comment by sunli829** [comment]
Can you help me look around here?

https://github.com/async-graphql/async-graphql/blob/215922ee1f4fb8bf1d4d9429bbef55ba69fc3ec5/src/scalars/id.rs#L61

**Comment by ruseinov** [comment]
It's strange, because this file has not changed for 12 days, yet the error only popped up in 0.14.20. 
I will definitely look into that, but it seems like the problem lies elsewhere, I'm going to try cleanup cache first..

**Comment by ruseinov** [comment]
Yeah, I have tried rebuilding the project to exclude any kinds of glitches - the problem only pops up in `1.14.20` and not the `1.14.19`.

**Comment by sunli829** [comment]
> Yeah, I have tried rebuilding the project to exclude any kinds of glitches - the problem only pops up in `1.14.20` and not the `1.14.19`.

Maybe that's the reason. #159

**Comment by ruseinov** [comment]
I’ll investigate this next week unless somebody beats me to it.

**Comment by ruseinov** [comment]
Maybe if I upgrade the bson package in my project it’d help. Will keep you updated.

**Comment by ruseinov** [comment]
That does not help, gotta keep investigating.

**Comment by ruseinov** [comment]
Actually it does @sunli829 , I was testing a 1.14.19 and forgot to change it back.
So the version has to be consistent.

The fix is: the bson crate version should be consistent with that in async-graphql.

**Comment by ruseinov** [comment]
```
async-graphql = { version = "1.15.0", features = ["bson"] }
bson = { version = "0.15.0", features = ["u2i"] }

```

That works just fine!
