### ISSUE TITLE
Make merging subscriptions with the same name a compile time error

### ISSUE THREAD

**Issue by sebtomba** [async-graphql/async-graphql#1625]
## Description of the feature
The section [Merging Subscriptions](https://async-graphql.github.io/async-graphql/en/merging_objects.html#merging-subscriptions) describes how to merge several subscriptions into one root subscription. The chapter also mentions that
> Like merging Objects, each subscription block requires a unique name.

However, this description does not indicate what a unique subscription name is. A unique name might include module names, which is not the case here. Even worse, code that merges identical subscription names compiles without any errors or warnings. But the program panics later with a runtime error caused by the subscription's not unique GraphQL name.

First, it needs to be clarified why the merged subscriptions don't use qualified names, including module names. But if this is a hard technical requirement, it would be great if the `MergedSubscription` derivation macro could detect this problem at compile time instead of panicking at runtime.

## Code example (if possible)
```rust
#[derive(MergedSubscription, Default)]
pub struct Subscription(other::Subscription);
```

**Comment by sunli829** [comment]
The derive macros cannot detect this problem, so the panic occurs at schema creation time.
