### ISSUE TITLE
Breaking change in patch release in MetaType::Scalar

### ISSUE THREAD

**Issue by tpoliaw** [async-graphql/async-graphql#1645]
## Expected Behavior
Updating between patch releases (`7.0.11` and `7.0.12`) should not break existing code.

## Actual Behavior
Previously working code now breaks due to addition of `directive_invocations` field to `MetaType::Scalar` variant.

## Steps to Reproduce the Problem
1. `cargo init demo`
2. `cd demo`
3. Add the following dependencies

  ```
  async-graphql = "=7.0.11"
  async-graphql-derive = "=7.0.11"
  ```
4. Replace `main.rs` with 
<details><summary>Example main.rs</summary>

```rust
use std::sync::Arc;

use async_graphql::{
    registry::{MetaType, MetaTypeId, Registry},
    InputType, Value,
};

fn main() {
    println!("Hello, world!");
}

struct Foo;
struct Bar;

impl InputType for Foo {
    type RawValueType = Bar;

    fn type_name() -> std::borrow::Cow<'static, str> {
        "Foo".into()
    }

    fn create_type_info(registry: &mut Registry) -> String {
        registry.create_input_type::<Self, _>(MetaTypeId::Scalar, |_| MetaType::Scalar {
            name: Self::type_name().into(),
            description: None,
            is_valid: Some(Arc::new(|v| matches!(v, Value::String(_)))),
            visible: None,
            inaccessible: false,
            tags: vec![],
            specified_by_url: None,
        })
    }

    fn parse(_: Option<async_graphql::Value>) -> async_graphql::InputValueResult<Self> {
        Ok(Foo)
    }

    fn to_value(&self) -> async_graphql::Value {
        Value::Null
    }

    fn as_raw_value(&self) -> Option<&Self::RawValueType> {
        None
    }
}
```

</details>

5. `cargo build` -> it builds
6. Bump both dependencies to `7.0.12`
7. `cargo build` -> build fails

## Specifications

- Version: 7.0.11 -> 7.0.12
- Platform: Linux

**Comment by sunli829** [comment]
In principle, each update can only ensure that the macros can be used normally.

**Comment by callumforrester** [comment]
@sunli829 So are the macros the only "API" for this library (i.e. the thing that shouldn't break between patch releases)? 

If so I think that should be more clearly stated in docs.
