### ISSUE TITLE
slice support

### ISSUE THREAD

**Issue by bnjjj** [async-graphql/async-graphql#165]
Hello @sunli829 it seems there is a bug with slices. In fact here is some snippets:
```
pub struct XXX {
    coords: Vec<LatLng>,
}

#[async_graphql::Object]
#[rustfmt::skip]
impl Bubble {
    pub async fn coords(&self) -> &[LatLng] { &self.coords }
}
```

and when I check at my generated schema in docs I have `coords: LatLng!`

Do you have an idea where is the issue ? Maybe I made something wrong ?

**Comment by sunli829** [comment]
Let me check. This was good before.

**Comment by sunli829** [comment]
Upgrade to `v1.15.1`.

**Comment by bnjjj** [comment]
Fixed ! Thank you !
