### ISSUE TITLE
Would You Use This in Production ( If You Didn't Mind Keeping Up With Changes )?

### ISSUE THREAD

**Issue by zicklag** [async-graphql/async-graphql#167]
Hey there, I'm really liking this project, and I know that it is considered unstable from an API perspective, but how do you count it currently from a security perspective? In other words, would you trust it with production if you didn't mind keeping up with the API instability ( like I don't )? :smiley:

**Comment by sunli829** [comment]
I use it in production. 😁

**Comment by mwilliammyers** [comment]
I am going to deploy it to production in the next few weeks. I have been using it in a dev/staging environment for a few weeks now without issues. Keeping up with the API hasn’t been bad either.

**Comment by sync** [comment]
Have it running in prod no problems with it, only thing is to setup dependabot or renovate so your ci can build and update to the newer version every time there is a change. Have an e2e test for it and report issues as soon as you you can the author is very responsive

**Comment by zicklag** [comment]
Thanks for the notes y'all. :smiley:

**Comment by ruseinov** [comment]
I'm building a project using this that's going to be a distributed service deployed across many nodes, I have high hopes and I definitely like that it evolves quickly. 

There are some api changes and some dependency updates that need to be accounted for when updating the library version, but they are minimal and well worth it.

**Comment by ruseinov** [comment]
@zicklag feel free to close the issue if your question was answered:)

**Comment by zicklag** [comment]
Yeah, I think so. :)

The only thing I would wonder is how possible it could be to construct a malicious request that would cause the API to surrender secret information in the `Query` root object, but for now I haven't put any super secret info in there and I'm OK with it, and I might just take a look at the code sometime to double-check the code paths.

Cool part about Open Source is that the code is publicly visible for review!

**Comment by ruseinov** [comment]
> Cool part about Open Source is that the code is publicly visible for review!

Sure is, but the async-graphql codebase is not the easiest to follow, because it relies on lots of macros among other things. And so is pretty much any big enough library. But then again - you get to learn a lot by reading it!

I don't think there's anything unsafe happing in the parser that would allow you to inject stuff. Also take a look at field Guards - you can actually set all sorts of permissions for every field in an object and every route in the query/subscription/mutation. That allows you to implement custom "views" depending on user roles, for example.

**Comment by zicklag** [comment]
> That allows you to implement custom "views" depending on user roles, for example.

Wow that's very neat. I discovered GraphQL itself three days ago and I'm loving it. This library makes it so nice to create a server with Rust, too. Can't wait to start use it more!

**Comment by ruseinov** [comment]
Yeah, this library is great and getting greater every day. The amount of boilerplate is minimal. I have to invest some time and publish a generic project derived from a stripped down version of the stuff I'm currently working on. That includes some MongoDB boilerplate and some cool stuff like criteria.
