### ISSUE TITLE
Latest release 1.15.5 build issue

### ISSUE THREAD

**Issue by sync** [async-graphql/async-graphql#168]
My ci run is failing either the following errors:

```
 unresolved import `async_graphql_derive::GQLEnum`

 no `GQLInputObject` in the root

no `GQLSimpleObject` in the root

```

Etc... is there something I need to change on my end ?

**Comment by sync** [comment]
I am on mobile sorry 😐

**Comment by mwilliammyers** [comment]
I am pretty sure this is a result of us introducing breaking changes above `1.0.0`; it does not play nicely with `cargo` because `cargo` assumes different update heuristics when packages are above `1.0.0`.

TL;DR: `cargo update` should pick up the latest `async-graphql-derive` dependency...

**Comment by mwilliammyers** [comment]
@sunli829 we should pin the async-graphql dependencies (`async-graphql-derive`,  `async-graphql-parser`) to specific exact versions with `=1.15.1` or at least `1.15.*` etc.)

This should help minimize issues... I would open a PR for it but I am not entirely sure how the CI/deploy pipeline is setup 🙃

**Comment by sync** [comment]
running cargo update worked thank you
