### ISSUE TITLE
Pin async-graphql-* dependencies to minimize >1.0.0 issues

### ISSUE THREAD

**Issue by mwilliammyers** [async-graphql/async-graphql#172]
We should pin the `async-graphql-*` dependencies (`async-graphql-derive`, `async-graphql-parser`, etc.) to specific exact versions with `=1.15.1` or at least `1.15.*`/ `>= 1.15.0, < 1.16.0` to minimize breaking change related issues like https://github.com/async-graphql/async-graphql/issues/168 because `cargo` dependency resolution heuristics are different for crates above `1.0.0`.

See also: #117 and https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

**Comment by sunli829** [comment]
Maybe release a new version should use `cargo workspaces version patch --exact`.

**Comment by mwilliammyers** [comment]
Yeah, I think it definitely should, until we get to 2.0.0 and then we can go back to the current method.

**Comment by mwilliammyers** [comment]
@sunli829 Also can we really try to make an effort to limit breaking changes to minor version bumps at least (e.g. `1.15.0` -> `1.16.0`?

It is really hard to pin `async-graphql`, `async-graphql-parser` and `async-graphql-warp` etc.  to specific versions without compile issues, so I currently do `1.15.*` etc. and that seems to work well but then if I run `cargo update` (not expecting breaking changes on a patch release) I have to fix stuff...

I am fine updating stuff frequently, but I would prefer if I can control *when* that happens by adjusting my dependency versions accordingly...

In general cargo is *really* not set up to handle breaking changes after `1.0.0` 😆

**Comment by mwilliammyers** [comment]
Also, we don't need to release 2-4x a day (or even daily), unless you really want to... If people want bleeding edge releases, they can depend on git revisions instead of a crates.io release.

(just my two cents)

**Comment by sunli829** [comment]
Because I often release a version and then find a bug and then release a patch. 😂
