### ISSUE TITLE
Question/Suggestion: is there a way to intercept a query/mutation/subscription "route"

### ISSUE THREAD

**Issue by ruseinov** [async-graphql/async-graphql#173]
This issue is meant to start a discussion which might or might not end up being something viable that could be implemented. 

I'm currently working on a somewhat complex RBAC kind of thing for the GraphQL api that's being built, field guards kinda solve the issue I'm trying to solve, but I'm not yet sure whether it's going to be too verbose for what I'm trying to do or not. 

Although I could just implement a macro that would apply a default guard of some sort it might be cool to actually have a container-level guard that could be overridden/supplemented field-level. 

Which leads me to the next one: is there a way to have multiple "impl" blocks for Query/Mutation/Subscription currently? That would allow for grouping routes into smaller chunks and also apply different container-level "default" guards if that feature ever sees the light of day.

**Comment by sunli829** [comment]
It's not possible to support multiple impl blocks. 
Maybe you could do something like this?

```rust

#[Object]
impl Users {
   ...
}

#[Object]
impl Roles {
   ...
}

#[Object]
struct Query {
    #[field(guard(...))]
    async fn users(&self) -> Users {
    }

    #[field(guard(...))]
    async fn roles(&self) -> Roles {
    }
}
```

**Comment by ruseinov** [comment]
Are you suggesting something like [that](https://stackoverflow.com/a/42021115)?
That'll do, so basically in order to nest/group queries by type I would just introduce an intermediate struct that would do all the queries for `Users` or some other entity.

**Comment by sunli829** [comment]
I will think about how to solve this problem better these days.

**Comment by sunli829** [comment]
#231 #243

**Comment by ruseinov** [comment]
@sunli829 Good job! That's a really cool and useful feature, very few graphql frameworks in any language support this and I'm super happy to see that async-graphql got this covered.
