### ISSUE TITLE
Allow access to raw query in either Extensions or from the GQLRequest 

### ISSUE THREAD

**Issue by MidasLamb** [async-graphql/async-graphql#174]
Allow access to raw query String in either Extensions or from the GQLRequest.

Some context: Currently my Graphql server is a wrapper around an existing API (which is out of my control), which has zero documentation and is a pain in the ass to work with. Sometimes stuff goes awry inside a resolver, which will then return an error, but this most of the time means that an extra case needs to be added somewhere or something like that. The error will only contain information locally from the resolver, but in order to understand what went wrong, the entire query would be useful.

Currently if you want to log the entire query (for in actix), you need to deconstruct the entire payload, which is not straightforward (take a look at [FromRequest](https://docs.rs/async-graphql-actix-web/1.14.14/src/async_graphql_actix_web/lib.rs.html#38)). 

My suggestion/request is to expose `query_source` (with a getter function) on `QueryBuilder` in order to be able to easily retrieve the query string once it's parsed.

If this proposal finds support, i'm more than willing to create a PR for it myself

**Comment by sunli829** [comment]
I added the `QueryBuilder::query_source` function. 😀

**Comment by sunli829** [comment]
Released `v1.15.7`.

**Comment by MidasLamb** [comment]
Great, thanks!
