### ISSUE TITLE
DataSource is too hard to use without context

### ISSUE THREAD

**Issue by phated** [async-graphql/async-graphql#176]
While trying to upgrade async-graphql, I found that you removed the context from the DataSource.

When trying to move something like a database pool into the struct implementing DataSource, it requires lifetimes be added. This makes the datasource unnecessarily complicated to use.

**Comment by phated** [comment]
Nevermind, I discovered the `async_graphql::connection::query` method that removes the need for DataSource completely.

Are you planning to remove DataSource?

**Comment by sunli829** [comment]
> Nevermind, I discovered the `async_graphql::connection::query` method that removes the need for DataSource completely.
> 
> Are you planning to remove DataSource?

I think the DataSource is useful because it makes it easier to reuse code. 😁

**Comment by phated** [comment]
@sunli829 how is it easier than using the `query` function directly? I will push up my usage soon and show how it is good to use for implementing on Enum and other data structures.

**Comment by sunli829** [comment]
This is what I think is the correct use of `DataSource`.

```rust
Schema::build(...).data(UserDataSource{db: ...}).finish()
```

**Comment by phated** [comment]
@sunli829 in your example, you could end up with many database pools for an entire application, which would not work well

**Comment by sunli829** [comment]
No, the same connection pool should be shared.

**Comment by phated** [comment]
I tried implementing the same as you showed, but sharing a database pool required a lifetime, which is more complex than my solution.

**Comment by sunli829** [comment]
For example, the same `r2d2::Pool` should be shared.

**Comment by sunli829** [comment]
No, no, the connection pool should be shared with Arc.

**Comment by phated** [comment]
You still can't implement DataSource on an Enum, so my solution is better for me. I will link shortly.

**Comment by sunli829** [comment]
Yes, implement your own `DataSource`, or just use `connection::query`, whichever is more convenient for you.

**Comment by phated** [comment]
This is the way I used `connection::query` to implement a "data source" on a GraphQL Union (rust Enum): https://github.com/phated/twentyfive-stars/blob/f4a704f2ee2d93b2c50e7abc0e7c57b818cff030/server/src/data/card.rs

**Comment by sunli829** [comment]
Let me think about it. 😂

**Comment by sunli829** [comment]
I think `connection::query` is the best option in your case. 😁

**Comment by sunli829** [comment]
You can change `Cards::query`  to  `connection::query` so that you can at least check for invalid values.

**Comment by sunli829** [comment]
After careful consideration, `connection::query` is more flexible than the `DataSource`, so I decided to delete the `DataSource`.

**Comment by phated** [comment]
Looks great! Thanks @sunli829!
