### ISSUE TITLE
Question about federation

### ISSUE THREAD

**Issue by bnjjj** [async-graphql/async-graphql#180]
Hello, I'm currently trying to implement federation with apollo gateway. And the gateway tells me this:
```
This data graph is missing a valid configuration. [schema] User.uid -> is marked as @external but is not used by a @requires, @key, or @provides directive.

[users] User -> A @key selects id, but User.id could not be found
```

In fact I have 
```rust
pub struct User {
    pub created_at: DateTime<Utc>,
    pub uid: UserUID,
    pub name: String,
}
```
which is identified by UserUID which is a personal scalar.

And then when I want to extend User in another service I have:
```rust
#[derive(Clone)]
pub struct User {
    pub uid: UserUID,
}

#[async_graphql::Object(extends)]
impl User {
    #[field(external)]
    pub async fn uid(&self) -> &UserUID {
        &self.uid
    }

    pub async fn top_friends(
        &self,
        context: &Context<'_>,
        page_size: Option<i32>,
    ) -> FieldResult<Vec<TopFriend>> {
        ...
    }
}
```

Can you tell me where I'm wrong ? Where I forgot something ?

**Comment by bnjjj** [comment]
Ok got it ! The issue wasn't displayed in my examples but in my query extended I added an `entity` like this:
```rust
#[entity]
    pub async fn find_user_by_uid(
        &self,
        context: &Context<'_>,
        id: UserUID,
    ) -> FieldResult<Option<User>> {
...
}
```

and in fact the name `id` here has to be named `uid`.

**Comment by bnjjj** [comment]
Another question @sunli829 do you know how I can do when I need to access data from another service to resolve a field located in another service. Here is an example : 
```
impl User {
   pub async fn friends(&self, uid: UserUID) -> Vec<User> {...}
}
```

 and I have another service with
```rust
impl Place {
    pub async fn friends_places(&self, uid: UserUID) -> Vec<Place> {
        // First I need to fetch my friends from User schema. Here is my issue
        Place::fetch....
    }
}

**Comment by sunli829** [comment]
Each service should be independent, so you shouldn't do this, you can look at this example, it's simple enough.

https://github.com/async-graphql/examples/tree/master/federation

**Comment by sunli829** [comment]
> Ok got it ! The issue wasn't displayed in my examples but in my query extended I added an `entity` like this:
> 
> ```rust
> #[entity]
>     pub async fn find_user_by_uid(
>         &self,
>         context: &Context<'_>,
>         id: UserUID,
>     ) -> FieldResult<Option<User>> {
> ...
> }
> ```
> 
> and in fact the name `id` here has to be named `uid`.

If your service has no entity, you can manually enable federation support with `SchemaBuilder::enable_federation`.

**Comment by bnjjj** [comment]
Can you provide me some documentation about this https://github.com/async-graphql/examples/blob/master/federation/federation-reviews/src/main.rs#L59 ?

**Comment by sunli829** [comment]
Notice the return type of the `Obj::value` function.

```rust
#[SimpleObject]
struct Obj {
    value: i32,
}

// equivalent to

#[Object]
implement Obj {
    async fn value(&self) -> i32 {
        self.value
    }
}
```

```rust
#[SimpleObject]
struct Obj {
    #[field(ref)]
    value: i32,
}

// equivalent to

#[Object]
implement Obj {
    async fn value(&self) -> &i32 {
        &self.value
    }
}
```

**Comment by bnjjj** [comment]
Great thank you !

**Comment by bnjjj** [comment]
Hello again @sunli829 haha ! I have a new question. If I want to make this https://www.apollographql.com/docs/apollo-server/federation/entities/#defining-a-compound-primary-key

For now I have 
```rust
pub struct Place {
    pub id: i32,
    pub user_uid: UserUID,
}

#[async_graphql::Object(extends)]
impl Place {
    #[field(external)]
    pub async fn id(&self) -> i32 {
        self.id
    }

    #[field(external)]
    pub async fn user_uid(&self) -> &UserUID {
        &self.user_uid
    }
}
```

and in my query:

```rust
 #[entity]
    pub async fn find_place_by_id_and_user_uid(
        &self,
        _context: &Context<'_>,
        id: i32,
        user_uid: UserUID,
    ) -> Place {
        Place { id, user_uid }
    }
```

I can see that the entity is good, I have a `@key(fields : "id userUid") but I think my issue i with the `external` field. Do you know How I can make a compound for `external` fields ? Gateway just drop me this error `This data graph is missing a valid configuration. [users] Place.userUid -> is marked as @external but is not used by a @requires, @key, or @provides directive.`

**Comment by sunli829** [comment]
Because other types are not dependent on this external field. 
When you extend a type, you do not need to mark all fields as `#[external]` unless the field is used by a type in another service.

**Comment by bnjjj** [comment]
Ok, in fact I need `user_uid` to resolve in another resolver so I just added `requires` on this field. Is it correct ?
```rust
#[async_graphql::Object(extends)]
impl Place {
    #[field(external)]
    pub async fn id(&self) -> i32 {
        self.id
    }

    #[field(external)]
    pub async fn user_uid(&self) -> &UserUID {
        &self.user_uid
    }

    #[field(requires = "userUid")]
    pub async fn owner(&self, context: &Context<'_>) -> FieldResult<User> {
    //Do stuff that need self.user_uid
    }
```

**Comment by sunli829** [comment]
### This is an example of extending the `User` object.

https://github.com/async-graphql/examples/blob/c6eb3f56f55b2f09586102f020e86e9ba0000c76/federation/federation-reviews/src/main.rs#L17

https://github.com/async-graphql/examples/blob/c6eb3f56f55b2f09586102f020e86e9ba0000c76/federation/federation-reviews/src/main.rs#L68

### Federation doc

https://www.apollographql.com/docs/apollo-server/federation/introduction/

**Comment by sunli829** [comment]
Can you provide an example repo?  😁

**Comment by sunli829** [comment]
> Hello again @sunli829 haha ! I have a new question. If I want to make this https://www.apollographql.com/docs/apollo-server/federation/entities/#defining-a-compound-primary-key
> 
> For now I have
> 
> ```rust
> pub struct Place {
>     pub id: i32,
>     pub user_uid: UserUID,
> }
> 
> #[async_graphql::Object(extends)]
> impl Place {
>     #[field(external)]
>     pub async fn id(&self) -> i32 {
>         self.id
>     }
> 
>     #[field(external)]
>     pub async fn user_uid(&self) -> &UserUID {
>         &self.user_uid
>     }
> }
> ```
> 
> and in my query:
> 
> ```rust
>  #[entity]
>     pub async fn find_place_by_id_and_user_uid(
>         &self,
>         _context: &Context<'_>,
>         id: i32,
>         user_uid: UserUID,
>     ) -> Place {
>         Place { id, user_uid }
>     }
> ```
> 
> I can see that the entity is good, I have a `@key(fields : "id userUid")` but I think my issue i with the `external` field. Do you know How I can make a compound for `external` fields ? Gateway just drop me this error `This data graph is missing a valid configuration. [users] Place.userUid -> is marked as @external but is not used by a @requires, @key, or @provides directive.`

This may be a bug and I'm checking it out.

**Comment by sunli829** [comment]
Sorry, `async-graphql` doesn't support this right now, I'm adding it. 😂

https://www.apollographql.com/docs/apollo-server/federation/entities/#extending-an-entity-with-computed-fields-advanced

**Comment by sunli829** [comment]
Extending Product object

```rust
#[Object(extends)]
impl Product {
    #[field(external)]
    async fn upc(&self) -> &String {
        &self.upc
    }

    #[field(external)]
    async fn name(&self) -> &String {
        &self.name
    }

    #[field(external)]
    async fn price(&self) -> i32 {
        self.price
    }

    #[field(requires = "name price")]
    async fn price2(&self) -> String {
        format!("{}: {}", self.name, self.price)
    }
}
```

Query

The key of the `Product` is `upc`, and the `name` and `price` are external fields.

```rust
#[Object]
impl Query {
    #[entity]
    async fn find_product_by_upc(
        &self,
        #[arg(key)] upc: String,
        name: String,
        price: i32,
    ) -> Product {
        Product { upc, name, price }
    }
}
```

**Comment by sunli829** [comment]
Please upgrade to `v1.15.15`. 😁

**Comment by bnjjj** [comment]
Great ! Thank you !

**Comment by bnjjj** [comment]
Just to be sure, in case I don't write `#[arg(key)]` the behavior stay the same as before ? Is `#[arg(key)]` only interesting in case of multiple arguments ?

**Comment by sunli829** [comment]
Yes. 😀

**Comment by sunli829** [comment]
https://async-graphql.github.io/async-graphql/en/apollo_federation.html

**Comment by bnjjj** [comment]
Thanks for your hard work ! Keep going guy ! If you need help, feel free :)
