### ISSUE TITLE
Traits to implement without macros

### ISSUE THREAD

**Issue by phated** [async-graphql/async-graphql#182]
@sunli829 I've been thinking that I would like the flexibility of implementing my own resolver logic instead of using the macros. Have you considered adding traits that can be implemented instead of using the macros?

**Comment by nicolaiunrein** [comment]
I thought about this as well and have a specific use-case: All my services need to implement a set of resolvers in order to provide some shared functionality. It would be awesome if I could just provide a supertrait for this but it only works if I have access to whatever the macros produce. I also think exposing a trait like this would give people the ability to write libraries/frameworks on top of async-graphql whether it be open source or domain-specific.

**Comment by sunli829** [comment]
Do you mean using generics instead of macros to do everything?

**Comment by phated** [comment]
@sunli829 No, I mean that this project should allow consumers to implement a trait directly if they don't (or can't) use the macro. If you look at the Diesel library, they allow you to implement the `Queryable` trait if you cannot use `derive(Queryable)`

**Comment by nicolaiunrein** [comment]
@phated Good example. I think this boils down to my use-case. @sunli829 I **do not** want to change the internals of async-graphql. Nor do I want to change the external API of async-graphql. I just think about how we could improve it to make it more flexible for library authors. Consider the below example.

As I said all my services need to provide a set of resolvers with the same signature. What I did for now is this: 

```rust
// library.rs
#[gql::SimpleObject]
pub struct ServiceInfo {
  #[field]
  uptime: u64,
}

// client.rs
struct MyServiceInfo {
  uptime:u64,
}

impl From<MyServiceInfo> for ServiceInfo {
  ...
}
```

Of course I could further simplify this...
```rust
// library.rs
#[gql::SimpleObject]
pub struct ServiceInfo {
  #[field]
  uptime: u64,
}

pub trait ServceInfoTrait {
  async fn uptime(&self) -> u64;

  async fn into_graphql(&self) -> ServiceInfo {
    ServiceInfo { update: self.uptime().await }
  }
}
```

But what I would really prefer...

```rust
// library.rs
#[async_trait]
pub trait ServiceInfo {
    async fn uptime() -> u64;
}
// ...is something like this...
impl<T> gql::Object for T where T: ServiceInfo {
   async fn uptime(&self) -> u64 {
    self.uptime()
  }
}

// client.rs
#[derive diesel::Queryable] // ...this is now possible because client owns the struct.
struct MyInfo {
  some_other_info: String,
}

#[async_trait]
impl ServiceInfo for MyInfo {
  // ...also this does not need to be stored in a struct anymore...
  async fn uptime(&self) -> u64 {
    APPLICATION_START.elapsed().as_millis()
  }
}
```

I think this demonstrates how I would like to **zero-cost** abstractions around async-graphql. If I had a way to construct Objects without macros I could do it. But for now I have to create intermediate structs to annotate with macros which I feel is not ideal.

**Comment by sunli829** [comment]
I export the type `ObjectType` so that I can implement a GraphQL Object without a macro.
But I need to modify the API to make it easier to use.

`Edge` is a GraphQL Object implemented without macros.
https://github.com/async-graphql/async-graphql/blob/master/src/types/connection/edge.rs

**Comment by phated** [comment]
> But I need to modify the API to make it easier to use.

Yes, I think that is important. Right now, I think it is too complex to implement the ObjectType right now.

**Comment by sunli829** [comment]
> > But I need to modify the API to make it easier to use.
> 
> Yes, I think that is important. Right now, I think it is too complex to implement the ObjectType right now.

Yes, the API needs to be simplified.
