### ISSUE TITLE
Compilation error after version update

### ISSUE THREAD

**Issue by rkudryashov** [async-graphql/async-graphql#184]
In the repro-project (https://github.com/rkudryashov/async-graphql-reproducer) I have the following structure:

```
#[Interface(
field(name = "some_field", type = "i32", context),
)]
#[derive(Clone)]
enum Interface {
    Successor1(Successor1),
}

#[SimpleObject]
#[derive(Clone)]
struct Successor1 {
    some_field: i32,
}
```

After update from "1.14.11" to "1.16.0" I get the following error:

```
error[E0308]: mismatched types
  --> some-service\src\graphql.rs:85:1
   |
85 | / #[Interface(
86 | | field(name = "some_field", type = "i32", context),
87 | | )]
   | |__^ expected `i32`, found `&i32`
   |
   = note: expected enum `std::result::Result<i32, _>`
              found enum `std::result::Result<&i32, _>`

error: aborting due to previous error; 1 warning emitted
```

But in both places the field is defined as `i32`, not a reference. Is it a bug or I just missed some code changes while version update?

**Comment by phated** [comment]
Hey @rkudryashov, it looks you ran into the same issue as https://github.com/async-graphql/async-graphql/issues/183#issuecomment-648078572

Hope that helps!
