### ISSUE TITLE
Context improvements

### ISSUE THREAD

**Issue by phated** [async-graphql/async-graphql#185]
I've been working with `ctx.data()` and sometimes data doesn't exist (e.g. there might not be a `User`), but if I don't explicitly make it an `Option<User>`, the `data()` function panics.

I think we should always return an `Option` from the method so it doesn't panic. This would make it the same as Tide's `ext()` method: https://docs.rs/tide/0.11.0/tide/struct.Request.html#method.ext

If the consumer knows the data will exist, they can use `.unwrap()` on the Option.

**Comment by phated** [comment]
I see that we have `data_opt` for the Option version. Is there a reason we want to provide the version that panics?

**Comment by sunli829** [comment]
Because most of the time data of the specified type will always exist, it is more convenient to use `Context::data`.

**Comment by phated** [comment]
But you can unwrap. I think that Rust libraries shouldn't have the risk to panic.

**Comment by Koxiaet** [comment]
But panicking is what people want anyway. The purpose of panicking is when there is a programmer error or an unrecoverable error; unless the user has _explicitly stated_ they can recover, it's very unlikely they will want to. Additionally, in pretty much all cases it will be a programmer error so it makes sense for the defaults to follow that.

**Comment by sunli829** [comment]
> But panicking is what people want anyway. The purpose of panicking is when there is a programmer error or an unrecoverable error; unless the user has _explicitly stated_ they can recover, it's very unlikely they will want to. Additionally, in pretty much all cases it will be a programmer error so it makes sense for the defaults to follow that.

Yes, that's why this function exists.

**Comment by sunli829** [comment]
Like `Index::index`, when it panics, it's usually an unrecoverable programming error.

**Comment by phated** [comment]
Panics from a crate should only happen at program startup. This is a bad pattern we have implemented.

End users can always unwrap if they want to be unsafe.

**Comment by sunli829** [comment]
In fact, I just hate too much `unwrap`, and I think `Context::data` is easier to use. 😀

**Comment by phated** [comment]
> In fact, I just hate too much unwrap

Since you are very concerned with the type safety of this project, it is weird that you'd want to have this panic.

I am working on a replacement to this API that will avoid the panic, while avoiding Option in many cases. Please leave this open until I can finish.

**Comment by ruseinov** [comment]
I tend to agree with @sunli829 that the current api is super convenient to use and would prefer to avoid any extra complexity in this api, even if there is a danger of panic. The main reason for that is that one is forced to put a bunch of stuff that always exists into the context, like a database handle, for example. Having to do extra unwraps there would definitely ruin the simplicity of the api. 

If you don't want that to panic - use `Option`. If you don't care - you SHOULD have the ability to override. This is basically dependency injection, similar to what you have in `actix-web` and there is no way around panics here.

**Comment by ruseinov** [comment]
One other thing that would be cool to have as an option is the ability to embed context data directly into method declarations similar to that in actix-web. 

```rust
    async fn records(
        &self,
        ctx: &Context<'_>,
        db: ContextData<Database>,
        record_type: Option<String>,
        #[arg(default)] query: QueryInput,
    ) -> FieldResult<Vec<Record>> {
        db.query...
    }
```

**Comment by phated** [comment]
@ruseinov That is pretty much what I was thinking. Though I don't think we need to separate the Context and the ContextData. I think we could provide an API like Tide's `req.state()` method (https://docs.rs/tide/0.11.0/tide/struct.Request.html#method.state)

@sunli829 could this API be implemented? I have been trying today but I keep having trouble with lifetimes (I still don't fully understand them).

```rust
struct ContextState {
    db: DbConnection
}

struct Query;

[Object]
impl Query {
    async fn records(
        &self,
        ctx: &Context<ContextState>
    ) -> FieldResult<Vec<i32>> {
        let ContextState { db } = ctx.state();
        db.query()
    }
}

let schema = Schema::build(Query, EmptyMutation, EmptySubscription)
    .with_state(ContextState { db })
    .finish();
```

**Comment by ruseinov** [comment]
@phated 👍🏿 This is a good middle-ground, supporting both this and the current approach should make everyone happy.

**Comment by sunli829** [comment]
I don't think this generic state makes any sense other than a negligible performance boost, and it makes the API more difficult to use.

**Comment by sunli829** [comment]
This `state` can become a kind of pollution that is everywhere in the library. Look at Juniper.

**Comment by sunli829** [comment]
https://github.com/graphql-rust/juniper/issues/655

Look at this. I think this is the right thing to do.

**Comment by ruseinov** [comment]
> [graphql-rust/juniper#655](https://github.com/graphql-rust/juniper/issues/655)
> 
> Look at this. I think this is the right thing to do.

That sounds good

**Comment by phated** [comment]
@sunli829 wow, just read that proposal and it sounds great! Do you think it will be hard to change?

**Comment by sunli829** [comment]
No, async-graphql is already using HashMap<TypeId, Box<dyn Any>>.

**Comment by ruseinov** [comment]
> I don't think this generic state makes any sense other than a negligible performance boost, and it makes the API more difficult to use.

I mainly provided this example because I like this type of approach
```rust
pub async fn graphql(
    schema: web::Data<Schema<QueryRoot, MutationRoot, EmptySubscription>>,
    db: web::Data<Database>,
    claims: RequestData<Claims>,
    ipfs_client: web::Data<IpfsClient>,
    _req: HttpRequest,
    gql_request: GQLRequest,
) -> Result<web::Json<GQLResponse>> {
```

more than this
```rust
pub async fn graphql(
    ctx: Context,
) -> Result<web::Json<GQLResponse>> {
let db = ctx.data::<Database>(); 
```

The latter results in plenty of boilerplate, which could arguably be brought to library level. The ability to have it both ways would also work, similar to that in actix.

**Comment by ruseinov** [comment]
While thinking about this I must also say that it would be nice to be able to optimize on:

```rust
    let mut query = gql_request.into_inner();
    query = query.data(user);
    query = query.data(db);
...
```


The problem with current approach is that one needs to do extra allocations on each request to the graphql, because it is being set up on a per-request basis. It might be cool if we could use some bootstrapped version of this, so that the `query.data` setup didn't have to happen on each request, or rather not all of it, because there's going to be stuff like currently authenticated users or JWT claims that would need to be set on a per-request basis.

**Comment by sunli829** [comment]
This doesn't seem to make much sense.

**Comment by phated** [comment]
@sunli829 I wanted to give you an update. I tried implementing the `FromContext` trait, and if you use that, you block people from using core data types for Context.

I still think we should have a concrete type that Context wraps, and then allow additions with `data()` for per-request data.

**Comment by sunli829** [comment]
How does this `FromContext` work?

**Comment by phated** [comment]
@sunli829 I implemented the same was as the Juniper issue you linked. It is a good idea, but it cannot be done without specialization to provide a blanket implementation for core types.

**Comment by sunli829** [comment]
How about this?

```rust
    pub fn data_ok<D: Any + Send + Sync>(&self) -> FieldResult<&D> {
        self.data_opt::<D>()
            .ok_or(format!("Data `{}` does not exist.", std::any::type_name::<D>()).into())
    }
```

**Comment by phated** [comment]
@sunli829 for what?

**Comment by sunli829** [comment]
`FromContext` doesn't seem very convenient to use, it complicates a very simple thing.

**Comment by phated** [comment]
> Look at this. I think this is the right thing to do.

Have you changed your mind?

I think we should implement:

```
struct MyData {
    user_ids: Vec<i32>
};

type Context = async_graphql::Context<MyData>
```

**Comment by sunli829** [comment]
> > Look at this. I think this is the right thing to do.
> 
> Have you changed your mind?
> 
> I think we should implement:
> 
> ```
> struct MyData {
>     user_ids: Vec<i32>
> };
> 
> type Context = async_graphql::Context<MyData>
> ```

This is not good, this `State` parameter will be everywhere, very inconvenient to use.

**Comment by sunli829** [comment]
I know `tide` is like this, but I don't think this is a good design because it's really inconvenient to use.

**Comment by phated** [comment]
@sunli829 my suggestion is much easier than the anonymous lifetime we currently require. We just recommend to users that they should alias the type. This is a very reasonable API to have.

**Comment by phated** [comment]
> I know tide is like this, but I don't think this is a good design because it's really inconvenient to use.

How are type aliases inconvenient to use?

**Comment by sunli829** [comment]
The entire library needs a massive refactoring to support generic `Context`.

**Comment by phated** [comment]
> The entire library needs a massive refactoring to support generic Context.

Yes, I started on it and the lifetime makes it **extremely** difficult to refactor to add the generic to type type signature.

**Comment by sunli829** [comment]
But the end result is no different from the following, and of course, one less memory allocation cost that is almost negligible.

```rust
struct MyData {
    user_ids: Vec<i32>
};

let schema = Schema::build(...).data(MyData{...});
```

use

```
ctx.data::<MyData>()
```

**Comment by phated** [comment]
>  one less memory allocation cost that is almost negligible.

This is not the point in making the change. We should not have a library that panics at runtime. I have asked the others in my Rust group and they think our panic is **very bad**

**Comment by sunli829** [comment]
So, here's my solution, maybe you could use the `data_ok` function.

```rust
pub fn data_ok<D: Any + Send + Sync>(&self) -> FieldResult<&D> {
        self.data_opt::<D>()
            .ok_or(format!("Data `{}` does not exist.", std::any::type_name::<D>()).into())
    }
```

**Comment by phated** [comment]
We already have `data_opt`, so that solution is not enough.

**Comment by sunli829** [comment]
Yes, I think the `data_ok` also makes no sense, and most of the time people return the error they want.

**Comment by phated** [comment]
The `Context` should contain data that is **guaranteed** to be there and is verified by the compiler, and we can also have an API `data()` like we have now, but it **always** returns option.

**Comment by sunli829** [comment]
The `Panics` section of the document states that this function is at risk of panic, and you might think that's not enough?

```rust
/// Gets the global data defined in the `Context` or `Schema`.
    ///
    /// If both `Schema` and `Query` have the same data type, the data in the `Query` is obtained.
    ///
    /// # Panics
    ///
    /// It will panic if the specified data type does not exist.
    pub fn data<D: Any + Send + Sync>(&self) -> &D {
        self.data_opt::<D>()
            .expect("The specified data type does not exist.")
    }
```

**Comment by sunli829** [comment]
> The `Context` should contain data that is **guaranteed** to be there and is verified by the compiler, and we can also have an API `data()` like we have now, but it **always** returns option.

What you're saying can only be done by adding generic arguments to the Context, which requires massive refactoring, and I wonder if that's really necessary.

**Comment by phated** [comment]
> which requires massive refactoring, and I wonder if that's really necessary.

Yes, it needs a lot of refactoring, but I thought we wanted the best GraphQL library? Am I mistaken?

**Comment by sunli829** [comment]
Like `actix-web`, I think it's much easier to use than tide's `State`.

https://github.com/actix/actix-web/blob/23c8191cca7264076d58816923b6f25eb89e6107/src/app.rs#L103

**Comment by phated** [comment]
@sunli829 isn't that introducing a generic? The example looks to have a concrete type.

**Comment by sunli829** [comment]
Because I know exactly what data types are in my `Data`, I'll just use `Context::data`. If I know that a data type may exist, I use `Context::data_opt`.
If the `Context::data` causes panic, it's the people using the library that cause the problem, not the library, right?

**Comment by phated** [comment]
> If the Context::data causes panic, it's the people using the library that cause the problem, not the library, right?

No, you don't have an issue because you **wrote** those methods. I used the APIs and my application had a panic. That is a bad API. Rust type signatures do not let you indicate panics, so you rely on written documentation that doesn't show in editor tooling.

You brag that this library's safety, but have a panic API, which is very unsafe.

**Comment by sunli829** [comment]
Since this is not the right thing to do, why is there such a function in the standard library?

```rust
impl<'_, K, Q, V, S> Index<&'_ Q> for HashMap<K, V, S>
where
    K: Eq + Hash + Borrow<Q>,
    Q: Eq + Hash + ?Sized,
    S: BuildHasher, 
[−]

type Output = V

fn index(&self, key: &Q) -> &V
[−]

Returns a reference to the value corresponding to the supplied key.

Panics

Panics if the key is not present in the HashMap.
```

**Comment by phated** [comment]
Panics are usually a legacy issue that can't be changed because they are in the standard library or underlying system libraries can crash.

**Comment by Koxiaet** [comment]
Panics are _not_ a legacy issue. They are intentionally there to make writing code easier and avoid having to write unwrap everywhere, which looks really ugly. If your code is panicking it means that you have a bug, and you can't expect Rust to protect you from all bugs without dependent types. Especially here it is an extremely rare case in which this implementation would cause you to panic. Yes, if you type in the wrong type or forget to add the data then it will panic, but it is super easy and fast to fix.

**Comment by phated** [comment]
@Koxiaet The entire point of the Hindley-Milner type system that Rust uses is that a program that type checks is **sound** and will not crash if it compiles. Rust has panics because it interops with C code that can panic, but async-graphql does not use any C code and removed all unsafe code, so a program using it should be **sound**

**Comment by phated** [comment]
Let's be clear: the only reason I'm being argued against is that it would require development effort to support the API I'm suggesting, not that we should have a panicking API in the project... So there's no point in arguing about the panic. We should discuss how we improve the API

**Comment by Koxiaet** [comment]
> Rust has panics because it interops with C code that can panic, but async-graphql does not use any C code and removed all unsafe code, so a program using it should be **sound**

That's not true. Panics are an entirely Rust thing. C code can't panic. Panics are designed to be a sound replacement of UB, and idiomatic Rust code _will_ panic if it needs to.

At least in my opinion, whether we use a generic type parameter or dynamic types really doesn't matter. The performance is basically identical for both, they are almost equally easy to use, and while compilation errors are better than panics in general a consistent panic at first request is basically a compilation error anyway, since it happens 100% of the time and soon after running the program.

**Comment by ruseinov** [comment]
@sunli829 have you thought of being able to propagate the "data" supplied to actix-web into the async-graphql context in a more convenient way than just 
```rust
    let mut query = gql_request.into_inner();
    query = query.data(user);
    query = query.data(db);
```

?
Since we already have a plugin it might make sense to have some sort of helper that'd just propagate all the objects stored in actix-data to graphql-context as it is a very common use-case, which introduces potential room for error as you need to add data to both actix and graphql manually.
