### ISSUE TITLE
Use fully qualified paths in macro expansion

### ISSUE THREAD

**Issue by Koxiaet** [async-graphql/async-graphql#186]
Currently, this fails to compile:

```rust
mod std { }

#[async_graphql::SimpleObject]
struct Something { }
```

If the macro expansion used `::std::` instead of `std::` then it would (at least in the 2018 edition). This applies to `async_graphql::` too - writing `mod async_graphql {}` breaks it.

**Comment by sunli829** [comment]
This is a hard bug to spot. 😂

**Comment by phated** [comment]
@sunli829 can that be caught by enabling: https://doc.rust-lang.org/unstable-book/language-features/proc-macro-hygiene.html#proc_macro_hygiene ?

**Comment by sunli829** [comment]
> @sunli829 can that be caught by enabling: https://doc.rust-lang.org/unstable-book/language-features/proc-macro-hygiene.html#proc_macro_hygiene ?

This should only support the nightly version, right?

**Comment by phated** [comment]
@sunli829 we can run tests with +nightly to check in CI

**Comment by sunli829** [comment]
I don't think this will solve the above problem because the stable version doesn't work. Maybe I misunderstood?
