### ISSUE TITLE
Add Transparent macro

### ISSUE THREAD

**Issue by Koxiaet** [async-graphql/async-graphql#187]
Add a `Transparent` attribute macro which allows for transparent GraphQL objects. Its use case is avoiding clones with locked data. For example, the query section of [the books example](https://github.com/async-graphql/examples/blob/master/models/books/src/lib.rs) could be rewritten as:

```rust
pub type Storage = Arc<Mutex<Slab<Book>>>;
pub type LockedStorage = MutexGuard<'a, Slab<Book>>;

pub struct QueryRoot;

#[async_graphql::Transparent]
impl QueryRoot {
    async fn get(&self, ctx: &Context<'_>) -> LockedQueryRoot<'_> {
        LockedQueryRoot(ctx.data::<Storage>().lock().await)
    }
}

pub struct LockedQueryRoot<'a>(LockedStorage<'a>);

#[async_graphql::Object]
impl<'a> LockedQueryRoot<'a> {
    async fn books(&self) -> &Vec<&Book> {
        self.0.iter().map(|(_, book)| book).collect()
    }
}
```

This new version completely avoids cloning the books and so is much more efficient, but is currently impossible to implement.

**Comment by sunli829** [comment]
It would be simpler to use `Arc` to avoid deep Clone, don't you think? 😀

```rust
pub type Storage = Arc<Mutex<Slab<Arc<Book>>>>;
```

**Comment by Koxiaet** [comment]
@sunli829 That's true, but this method results in better performance, and since this is the hot path for most applications it might be worth allowing it. But maybe only as a long-term goal since using `Arc` isn't _that_ bad.

**Comment by sunli829** [comment]
It's not a good idea, it's too complicated to use, and it can actually cause more serious performance problems.

**Comment by Koxiaet** [comment]
I agree on it being complicated to use. Since you think it doesn't suit the current API I'll close this issue.

Out of curiosity what are those other performance issues you mentioned?

**Comment by sunli829** [comment]
In general, we should minimize the duration of locks to achieve better concurrency.
