### ISSUE TITLE
Interface/union input types

### ISSUE THREAD

**Issue by Koxiaet** [async-graphql/async-graphql#188]
As far as I can tell, `async-graphql` doesn't currently support making interface/union input types; there's `SimpleObject`, `InputObject`and `Interface` but no `InputInterface`.

**Comment by phated** [comment]
The GraphQL spec doesn't allow interfaces for input types: https://stackoverflow.com/a/45554361

**Comment by Koxiaet** [comment]
That's such a shame! I just assumed it would :(.
