### ISSUE TITLE
Implement Type for more stdlib collection types

### ISSUE THREAD

**Issue by Koxiaet** [async-graphql/async-graphql#189]
Currently `Type` (and other hidden traits) are only implemented for a few stdlib types - however, it would make sense to implement it for these ones too:

* `Cow<T> where &T: Type`
* `HashMap<String, T>`, `HashMap<&str, T>`, `HashMap<Cow<str>, T>`
* Same as above for `HashSet`
* Same as above two for `BTreeMap` and `BTreeSet`
* `VecDeque`
* `LinkedList`
* `NonZero*` types
* `char` (which could be converted into a string)

**Comment by sunli829** [comment]
There is no corresponding definition in GraphQL's type system, and if you want to use these types, I suggest you use `async-graphql::Json` instead.

**Comment by Koxiaet** [comment]
But it can still be implemented for types other than the map and set types, right?

**Comment by Koxiaet** [comment]
You could also implement it for `u128` and `i128`, since you serialize it as a string.

**Comment by sunli829** [comment]
I think these can be implemented using custom scalar types, rather than being provided by this library.

**Comment by phated** [comment]
@sunli829 should we create another repository with community custom scalars? Maybe @Koxiaet would want to contribute.

**Comment by sunli829** [comment]
No, `async-graphql` is already using `HashMap<TypeId, Box<dyn Any>>`.

**Comment by sunli829** [comment]
Maybe we can consider adding these types of support? @Koxiaet

**Comment by sunli829** [comment]
[ ] HashSet

[ ] BTreeSet

[ ] VecDeque

[ ] LinkedList

[ ] NonZero*

[ ] char

[ ] HashMap

**Comment by Koxiaet** [comment]
Sounds like a good idea. By the way use `- [ ]` for a checklist.

**Comment by loafofpiecrust** [comment]
These additions are great but I'm finding that I want to use `Cow<T>` for some fields where I need to either return a reference to a struct field or data allocated within the resolver function. Could we add a `Type` impl for `Cow`?

**Comment by sunli829** [comment]
Yes, we can! I missed this. 🙂

**Comment by sunli829** [comment]
Release in `v2.1.0`.

**Comment by loafofpiecrust** [comment]
Thanks for the quick response and fix! I've successfully compiled my project using `Cow<'_, str>` for field return types. It doesn't look like I have the power to close this issue though.
