### ISSUE TITLE
ScalarType for i/u64 represented as integer instead of string

### ISSUE THREAD

**Issue by danielSanchezQ** [async-graphql/async-graphql#196]
In previous versions the `ScalarType` trait relied in a `to_json` method. It was possible to represent an int (i/u64) as a integer instead of a string for responses.
Right now the `ScalarType` relies on a `to_value` method in where any integer can be represented as a number just up to i32 (`Value(i32)`).  Completely invalidating the other possibility. 
Maybe can be a good idea to keep the `to_json` method with a default implementation. This way the standard can be kept as `Value(i32)` but it will still be possible to override that behavior for other purpouses.

This implementation is not possible anymore:
```rust
use async_graphql::{InputValueError, InputValueResult, ScalarType, Value};

// Wrapper around `i64` to force graphql to format it as a number (JSON) instead of a string
pub struct ScalarI64(pub i64);

#[async_graphql::Scalar]
impl ScalarType for ScalarI64 {
    fn parse(value: Value) -> InputValueResult<Self> {
        match value {
            Value::Int(n) => Ok(ScalarI64(n)),
            Value::String(s) => Ok(ScalarI64(s.parse()?)),
            _ => Err(InputValueError::ExpectedType(value)),
        }
    }

    fn to_json(&self) -> Result<serde_json::Value, async_graphql::Error> {
        Ok(serde_json::Value::Number(self.0.into()))
    }
}
```

A tiny example of troublesome is that if someone want to keep the responses from some REST endpoint and GraphQL offering the same results for an object, lets say: `struct Foo { bar : i64 }`:
The response object would look like,
REST:
```json
{
    "bar" : 1000000
}
```
GraphQL
```json
{
    "bar" : "1000000"
}
```

And the deserialization can be troublesome.

I'm down to try it and open a PR if it is something that can be considered.

Thanks

**Comment by phated** [comment]
I'm pretty sure the JSON spec doesn't support BigInts, so I think you have a bug in your API

**Comment by danielSanchezQ** [comment]
Maybe I was unfortunate. I meant big ints (i64, u64), not really BigInt. 
Referencing the JSON limit there is an interesting [post](https://stackoverflow.com/questions/13502398/json-integers-limit-on-size). 
I don’t think is really a bug since it was working as expected with plain json_serde (and it was working as expected before the change in the ScalarType trait). But I’m completely open to suggestions.

**Comment by danielSanchezQ** [comment]
@sunli829 , the new `OutputJson` should fix this too. Since an `OutputJson<i64>` would encode the number as `999999`, instead of `"999999"` for example. So, one stone, two birds. I'll test it tomorrow. Thanks!

**Comment by Stanislav-Lapata** [comment]
In browser console  
```javascript
let i64Max = JSON.parse(9_223_372_036_854_775_807)
=> 9223372036854776000
Number.isSafeInteger(i64Max)
=> false
i64Max === i64Max + 1
=> true
```
JavaScript doesn't support i64

**Comment by sunli829** [comment]
> In browser console
> 
> ```js
> let i64Max = JSON.parse(9_223_372_036_854_775_807)
> => 9223372036854776000
> Number.isSafeInteger(i64Max)
> => false
> i64Max === i64Max + 1
> => true
> ```
> 
> JavaScript doesn't support i64

Agree, although the JSON standard allows BigInt, I recommend that i64 be stored as a string, which is safer.

**Comment by danielSanchezQ** [comment]
I tested it and it also solve "that problem".  
Some considerations here:

I understand that _JS_ do not support it and if you want to stick for it for the standard types I think it is ok. But, being flexible looks like a good option for me. In some (maybe many) cases _JS_ will not be the final consumer of the data. And I think it is **useful** to have this possibility.

Thanks for everything @sunli829 !

**Comment by sunli829** [comment]
You can actually customize the scalar to solve this problem, which I think is better than using OutputJSON.

**Comment by danielSanchezQ** [comment]
I did it with the old `trait`. Couldn't do it with the new one. I'll take another look though.

**Comment by sunli829** [comment]
Int64 is now supported.

**Comment by danielSanchezQ** [comment]
@sunli829 , I updated and it works great! Thanks!
