### ISSUE TITLE
Add Relay Global Object Identification to the project

### ISSUE THREAD

**Issue by leesiongchan** [async-graphql/async-graphql#197]
Since we have added Relay Connection to the project, do you think is a good idea to add Global Object Identification to the project as well? 

References:
- https://relay.dev/graphql/objectidentification.htm
- https://github.com/graphql/graphql-relay-js/blob/master/src/node/node.js

**Comment by phated** [comment]
@leesiongchan this already exists as `async_graphql::ID`

**Comment by Ericnr** [comment]
I'm confused, what is equivalent of `nodeDefinitions` in the [node.js implementation](https://github.com/graphql/graphql-relay-js/blob/8f4ed1ad35805ef233ad9fd1af33abb9c0cad35a/src/node/node.js#L34)? `async_graphql::ID` seems to be just the scalar. 

A global object identification is supposed to be an id which lets you extract the actual database id + the graphql type that object represents. The node implementation does that by simply encoding the type and id into a base64 string. @phated your solution for this in your example repo was to have a `node` db table that is referenced by all other tables id column, which isn't I've seen tbh.

**Comment by oscartbeaumont** [comment]
I have just published a package that builds on top of `async-graphql::Interface` to allow the Relay `node` query to be implemented. It works using Rust macros. You can check it out [here](https://github.com/oscartbeaumont/async-graphql-relay). It's still in active development so the documentation needs some work but it has an example project in the repository.

**Comment by frederikhors** [comment]
@Ericnr did you find a way?

**Comment by Ericnr** [comment]
@frederikhors havent really used graphql in rust

**Comment by satvikpendem** [comment]
@oscartbeaumont is that still supported? I saw you've been working more on rspc so just curious about the status of https://github.com/oscartbeaumont/async-graphql-relay

**Comment by oscartbeaumont** [comment]
Not really as I haven't been actively using it. I would be happy to promote a new maintainer if someone wants to keep maintaining in but I don't have the free time to support it at the moment.

I had some comments about the main branch having better DX than the current crates.io release but I have completely forgotten the specifics. 

It's been on my todo list to update the README to document it as such but I just haven't found time.
