### ISSUE TITLE
Apollo batch request support

### ISSUE THREAD

**Issue by msdinit** [async-graphql/async-graphql#198]
Hi!
Do you have any interest in supporting [batch requests](https://www.apollographql.com/blog/batching-client-graphql-queries-a685f5bcd41b)?

**Comment by sunli829** [comment]
I think this feature is useful. Would you like to provide a PR?

**Comment by msdinit** [comment]
Sure, although might take some time.
Deserializing the request is pretty straightforward:

```
#[derive(Deserialize, Clone, PartialEq, Debug)]
#[serde(untagged)]
pub enum BatchGQLRequest {
    Single(GQLRequest),
    #[serde(deserialize_with = "deserialize_non_empty_vec")]
    Batch(Vec<GQLRequest>)
}

fn deserialize_non_empty_vec<'de, D, T>(deserializer: D) -> std::result::Result<Vec<T>, D::Error>
    where
        D: de::Deserializer<'de>,
        T: Deserialize<'de>,
{
    use de::Error as _;

    let v = Vec::<T>::deserialize(deserializer)?;
    if v.is_empty() {
        Err(D::Error::invalid_length(0, &"a positive integer"))
    } else {
        Ok(v)
    }
}
```
Mostly need to look through the codebase to deside how the resulting `BatchGQLRequest` should be used

**Comment by sunli829** [comment]
This is where the request is processed.

https://github.com/async-graphql/async-graphql/blob/0e4cf8688441ba2f1f01c40ad49f494f096f5d5f/src/http/into_query_builder.rs#L129

**Comment by sunli829** [comment]
I have a suggestion about renaming.

BatchGQLRequest -> GQLRequest
GQLRequest -> GQLRequestPart
IntoBatchQueryDefinition -> IntoQueryDefinition
IntoQueryBuilderOpts -> IntoQueryDefinitionOpts

What do you think?

**Comment by Koxiaet** [comment]
This issue should be closed now, but I wanted to ask whether it's even worth _not_ supporting batch requests in GraphQL integrations. Is there a use case for that or should everything use batching by default?

**Comment by sunli829** [comment]
> This issue should be closed now, but I wanted to ask whether it's even worth _not_ supporting batch requests in GraphQL integrations. Is there a use case for that or should everything use batching by default?

Convenient functions like`tide::Endpoint`, I think `receive_batch` can be used by default, what do you think?

**Comment by Koxiaet** [comment]
@sunli829 I agree but I was asking for all of them. In general users will want to enable batch requests but having separate `_batch` functions I think has the risk of them not using it.

**Comment by sunli829** [comment]
> @sunli829 I agree but I was asking for all of them. In general users will want to enable batch requests but having separate `_batch` functions I think has the risk of them not using it.

I haven't used the batch requests. In fact, this function doesn't have much advantage under http2. (Just my personal opinion.) 😁

**Comment by Koxiaet** [comment]
Oh that's true, I didn't think of it. I'm just unhappy with the code duplication that supporting both batch and non-batch causes. Maybe it can be done generically over a request trait? I don't want to do that if there's only two though, I'm trying to think if there are any other possible uses of the trait.

**Comment by sunli829** [comment]
> Oh that's true, I didn't think of it. I'm just unhappy with the code duplication that supporting both batch and non-batch causes. Maybe it can be done generically over a request trait? I don't want to do that if there's only two though, I'm trying to think if there are any other possible uses of the trait.

It is very strange to let the user choose `BatchRequest` or `Request`. We let the user understand a feature that he may not use at all, so I think he needs to understand `BatchRequest` when he needs batch request. Maybe we only provide `async_graphql ::http::receive_batch_body` and `async_graphql::http::receive_batch_json` are completely sufficient. I don't want to make the integration difficult to understand in order to support batch requests, what do you think?

**Comment by Koxiaet** [comment]
I was able to avoid code duplication implementing the regular and batch functions by always deserializing batch and then erroring if it there's multiple in the batch. Maybe we could repeat this pattern whereever both single and batch requests can be used, so the function dependency graph would look like

```
Batch Single
  |
  •-----•
  |
  •-----•
```

Instead of 

```
Batch Single
  •     •
  |     |
  •     •
```
Which would have more code duplication.

**Comment by sunli829** [comment]
> I was able to avoid code duplication implementing the regular and batch functions by always deserializing batch and then erroring if it there's multiple in the batch. Maybe we could repeat this pattern whereever both single and batch requests can be used, so the function dependency graph would look like
> 
> ```
> Batch Single
>   |
>   •-----•
>   |
>   •-----•
> ```
> 
> Instead of
> 
> ```
> Batch Single
>   •     •
>   |     |
>   •     •
> ```
> 
> Which would have more code duplication.

Do you mean to implement the `Request` trait for `BatchRequest` and `SingleRequest`?

**Comment by Koxiaet** [comment]
@sunli829 No, no request trait - just always putting the real logic in batch functions and having all other functions call their batch equivalents and fail if it's batch. Has the disadvantage of failing far later than necessary if a batch request is sent but not supported, however that's such a cold path it's fine.
