### ISSUE TITLE
Put a cfg attribute on a resolver

### ISSUE THREAD

**Issue by bnjjj** [async-graphql/async-graphql#200]
Is there a way to put a cfg attribute on a resolver. For example : 

```
#[async_graphql::Object(extends)]
impl Query {
    #[cfg(feature = "all_users")]
    pub async fn all_users(
        &self,
        context: &Context<'_>,
        filter: user_models::Filter,
    ) -> FieldResult<Vec<User>> {
         ...
    }
}
```

But it's not working. I already know the option `feature` for field attribute but what I want here is to not include this into my schema. It's not working for now rustc tells me the method `all_users` is not found :(

**Comment by sunli829** [comment]
This is not possible due to the limitations of procedural macros.
