### ISSUE TITLE
Update documentation on `#[arg(default)]`

### ISSUE THREAD

**Issue by Koxiaet** [async-graphql/async-graphql#201]
The [documentation for `#[arg(default)]`](https://docs.rs/async-graphql/1.16.5/async_graphql/attr.Object.html#field-argument-parameters) just says that it takes a string, and doesn't at all mention that it takes a literal, can call `::default()` and `default_with` - this behaviour is only documented in [the book](https://async-graphql.github.io/async-graphql/en/default_value.html).

**Comment by sunli829** [comment]
It would be better if you could help me to add this document. 😁
