### ISSUE TITLE
Can we add it to the doc?

### ISSUE THREAD

**Issue by Danue1** [async-graphql/async-graphql#205]
Can we add that the #[Object] impl per object can only be used once?

First, I am a Rust beginner.
I tried to use #[Object] impl multiple times in one struct, but later realized that I couldn't.
I know now why it doesn't, but I think it's often the case for others.

* write with google translation

[define_complex_object](https://async-graphql.github.io/async-graphql/en/define_complex_object.html)

**Comment by sunli829** [comment]
I updated the document. 😀

**Comment by Danue1** [comment]
WOW, COOOOOOOOOL!!!
THANK YOU VERY MUCH!!!
