### ISSUE TITLE
VERSION 2.0  IS COMING SOON

### ISSUE THREAD

**Issue by sunli829** [async-graphql/async-graphql#208]
I think the current API is basically stable, so I plan to release version 2.0 in the next few days.

**Comment by phated** [comment]
@sunli829 Will you begin to follow https://semver.org after the 2.0 release?

**Comment by sunli829** [comment]
Yes, there should be no major changes. 😀

**Comment by mwilliammyers** [comment]
Personally I think we should wait a few more days/weeks just to make sure everything is all settled and we don't notice any other breaking changes...

**Comment by adrian-wechner** [comment]
Anybody already tested it with actix-web version 3.0.0-beta.1? actix-web will soon release a new major version. They fixed up a bunch of stuff etc, and with that version async-graphql-actix-web doesnt seem to be compatible anymore. I bumped up the version dependency in async-graphql and async-graphql-actix-web to see if it would fix itself (by magic).... no luck no magic :) 
I think it would be a good idea to investigate at least if it were possible to make it actix-web 3 compatible before bumping to version 2.0. What do folks think?

**Comment by sunli829** [comment]
This is easy, and it will be supported soon after actix-web 3.0 is released.

**Comment by nicolaiunrein** [comment]
I just saw that on graphql.org page juniper is listed and async-graphql is not. I think with the release of v2 we should promote async-graphql to be listed there as an official server framework as well.

**Comment by sunli829** [comment]
I opened a PR to graphql.org a long time ago, but there was no response. 😒

**Comment by nicolaiunrein** [comment]
Where is your PR? Cannot find it. Has it been closed?

**Comment by sunli829** [comment]
This PR is here. 😠

https://github.com/graphql/graphql.github.io/pull/865

**Comment by Koxiaet** [comment]
Before we release 2.0 we should probably replace `File` in `UploadValue` with something else, probably `Box<dyn AsyncRead + Send + Sync + 'static>`? This however has the disadvantage of not being clonable like `File` is.

**Comment by sunli829** [comment]
> Before we release 2.0 we should probably replace `File` in `UploadValue` with something else, probably `Box<dyn AsyncRead + Send + Sync + 'static>`? This however has the disadvantage of not being clonable like `File` is.

Yes, the Upload parameter can correspond to multiple files. 🙂

**Comment by sunli829** [comment]
Released `2.0.0-alpha1`

**Comment by mwilliammyers** [comment]
I think we should wait even more before releasing `2.0.0` just to be sure we have everything all set for following [semver](https://semver.org/).

**Comment by Koxiaet** [comment]
Is there a possibility of removing `Lookahead` entirely? It doesn't seem too useful and is fairly complex to implement.

**Comment by sunli829** [comment]
> Is there a possibility of removing `Lookahead` entirely? It doesn't seem too useful and is fairly complex to implement.

Please don't, `LookAHead` is very useful. It can optimize the corresponding SQL query according to the query field. It is very convenient. Many of my projects rely on it. 😂

**Comment by Koxiaet** [comment]
Ok, I guess `Lookahead` should be kept.

`SimpleBroker` doesn't seem too useful though, it's just a wrapper around a static channel. Is that possible to remove? We also shouldn't be encouraging people to use global data.

**Comment by sunli829** [comment]
> Ok, I guess `Lookahead` should be kept.
> 
> `SimpleBroker` doesn't seem too useful though, it's just a wrapper around a static channel. Is that possible to remove? We also shouldn't be encouraging people to use global data.

SimpleBroker is not really useful, it has nothing to do with GQL and was simply a convenient pub/sub implementation to support subscription. I think we can delete it. 😃

**Comment by mwilliammyers** [comment]
I haven't done anything with subscriptions yet, does removing `SimpleBroker` make implementing subscriptions harder?

**Comment by Koxiaet** [comment]
I want to consider redesigning `Error` to reflect GraphQL's error type rather than this library's error type. It will lose information, but maybe a more opaque type is more suitable for something as complex as GraphQL. Is there any major disadvantage to this?

**Comment by sunli829** [comment]
> I want to consider redesigning `Error` to reflect GraphQL's error type rather than this library's error type. It will lose information, but maybe a more opaque type is more suitable for something as complex as GraphQL. Is there any major disadvantage to this?

When the validation mode is ValidationMode::Fast, most of the QueryError will never occur, because the error has been checked during the validation phase, unless the validation mode is ValidationMode::Strict.
The difference between ValidationMode::Fast and ValidationMode::Strict is that ValidationMode::Fast only validates queries that affect security, such as infinitely recursive fragments.

Some object implementations rely on QueryError, such as MergedObject, which will determine whether the current error type is QueryError::FieldNotFound.

I think it is better to have a clear type of error than nothing, what do you think?

**Comment by sunli829** [comment]
> I haven't done anything with subscriptions yet, does removing `SimpleBroker` make implementing subscriptions harder?
> 
> But yeah, I agree, let's keep `LookAhead` 🙂 . We might want to change it to be a little easier to use, but it is a great feature.

I think there are two reasons for removing SimpleBroker:
1. Usually the event should be sent by the message queue, not a stand-alone pub/sub model like SimpleBroker. Although it will be easier to use in very simple situations, it conveys a bad design concept.
2. SimpleBroker and GraphQL are not related.

**Comment by Koxiaet** [comment]
@sunli829 I think we should keep `QueryError` the same; I was proposing changing the outer `Error` type; it will allow us to change the inner implementation more freely without breaking compatibility.

**Comment by sunli829** [comment]
> @sunli829 I think we should keep `QueryError` the same; I was proposing changing the outer `Error` type because it will allow us to change the inner implementation more freely without breaking compatibility.

Add a wrapper to the error type. Is it possible to have an into_error function converted to Error type?

**Comment by sunli829** [comment]
# Performance improvement

1. Change `Name(String)` to `struct Name(Arc<String>)`.
2. Implement `Serialize` for `ConstValue`.
3. All resolver function return values use `ConstValue` instead of `serde_json::Value`.
4. All test codes used to generate `serde_json::Value` are all unavailable. We need a macro like `serde_json::json` to fix the test code.

This will avoid a large amount of memory allocation, what do you think? @Koxiaet

**Comment by Koxiaet** [comment]
@sunli829

`Arc<str>` would be even better than `Arc<String>` since there's one less allocation and layer of indirection.

I think that we should even aim to make `serde_json` an optional feature (GraphQL is supposed to be format-independent after all). We'd have to make our own `Number` type but that isn't too hard. The `const_value!`/`value!` macro might even be better if we don't forward to `serde_json` because we can use GraphQL's actual value syntax instead of JSON-like. To support embedded expressions we can just wrap them in () as that's not valid GraphQL value syntax I think. Additionally if we make it a proc macro we can validate at compile time that the keys are valid `Name`s.

**Comment by phated** [comment]
I was doing some research on str's and found https://fasterthanli.me/articles/small-strings-in-rust - I believe using `smol_str` would be the best for use and performance.

**Comment by sunli829** [comment]
> @sunli829
> 
> `Arc<str>` would be even better than `Arc<String>` since there's one less allocation and layer of indirection.
> 
> I think that we should even aim to make `serde_json` an optional feature (GraphQL is supposed to be format-independent after all). We'd have to make our own `Number` type but that isn't too hard. The `const_value!`/`value!` macro might even be better if we don't forward to `serde_json` because we can use GraphQL's actual value syntax instead of JSON-like. To support embedded expressions we can just wrap them in () as that's not valid GraphQL value syntax I think. Additionally if we make it a proc macro we can validate at compile time that the keys are valid `Name`s.

`Arc<str>` does not seem to be instantiated?

**Comment by sunli829** [comment]
I thought about it, this does not improve performance, because ExecuteDocument is newly created every time a query. 😂

**Comment by sunli829** [comment]
> I think that we should even aim to make serde_json an optional feature (GraphQL is supposed to be format-independent after all). We'd have to make our own Number type but that isn't too hard. The const_value!/value! macro might even be better if we don't forward to serde_json because we can use GraphQL's actual value syntax instead of JSON-like. To support embedded expressions we can just wrap them in () as that's not valid GraphQL value syntax I think. Additionally if we make it a proc macro we can validate at compile time that the keys are valid Names.

This means we can support this? #247

**Comment by Koxiaet** [comment]
> I thought about it, this does not improve performance, because ExecuteDocument is newly created every time a query. 😂

Using smol str it would because it avoids heap allocating names that are 22 bytes or under, which is most names so that's fairly significant

**Comment by sunli829** [comment]
I am trying...

**Comment by sunli829** [comment]
> I changed the `Name(String)` to `Name(SmolStr)`, and then tested the performance.It is almost the same as the original. The main reason is that the output is still `serde_json::Value` and there is additional memory allocation.
> 
> We need to remove the dependency on `serde_json` first, and it should be able to significantly improve performance.

I don't know if it is necessary to improve the performance. Now the performance of async-graphql is faster than `juniper (master)` and `gqlgen (golang)`. 😂

**Comment by meh** [comment]
> > I changed the `Name(String)` to `Name(SmolStr)`, and then tested the performance.It is almost the same as the original. The main reason is that the output is still `serde_json::Value` and there is additional memory allocation.
> > 
> > We need to remove the dependency on `serde_json` first, and it should be able to significantly improve performance.
> 
> I don't know if it is necessary to improve the performance. Now the performance of `async-graphql` is faster than `juniper (master)` and `gqlgen (golang)`. 😂

The more the better tho.

**Comment by meh** [comment]
Is #261 going to be dealt with before 2.0? I find the `GQL` prefix for derives quite ugly, I always alias `async_graphql` to `graphql` and just do `#[graphql(Object)` pre 2.0-alpha.

**Comment by Koxiaet** [comment]
> Is #261 going to be dealt with before 2.0? I find the `GQL` prefix for derives quite ugly, I always alias `async_graphql` to `graphql` and just do `#[graphql(Object)` pre 2.0-alpha.

@meh It has already been implemented, it didn't touch the macro names. But I agree, the macros should probably be renamed. (also did you mean to write `#[graphql::Object]`?)

**Comment by sunli829** [comment]
Add `#[macro_use] extern crate async_graphql` to main.rs then find that the prefix is necessary. 😃

**Comment by Koxiaet** [comment]
> Add `#[macro_use] extern crate async_graphql` to main.rs then find that the prefix is necessary. 😃

I don't think it's worth supporting 2015 edition, everyone should be using 2018 edition by now.

**Comment by sunli829** [comment]
> > Add `#[macro_use] extern crate async_graphql` to main.rs then find that the prefix is necessary. 😃
> 
> I don't think it's worth supporting 2015 edition, everyone should be using 2018 edition by now.


So you think we should remove the prefix and write it as `gql::Object`?

**Comment by Koxiaet** [comment]
Yes. Users can also reexport it as `use async_graphql::Object as GQLObject` if they want to - importantly we shouldn't duplicate "GraphQL" in the crate name and item name, it's not like there's _also_ going to be a `RestObject` there or something.

**Comment by meh** [comment]
> > Is #261 going to be dealt with before 2.0? I find the `GQL` prefix for derives quite ugly, I always alias `async_graphql` to `graphql` and just do `#[graphql(Object)` pre 2.0-alpha.
> 
> @meh It has already been implemented, it didn't touch the macro names. But I agree, the macros should probably be renamed. (also did you mean to write `#[graphql::Object]`?)

I did mean that, sorry, writing from mobile. I'd really like the macros to be renamed while we're at it, if they could be made to not need to repeat GQL it'd make me happy.

**Comment by sunli829** [comment]
I removed all the `GQL` prefixes, are you happy now? 😎

**Comment by sunli829** [comment]
When can we release version 2.0?

**Comment by Koxiaet** [comment]
Here's a list of things I'd like to change before 2.0.

- [ ] Replace `File` in `UploadValue` with something async.
- [ ] Remove JSON dependency.
- [ ] Rewrite some of the integrations and do things like remove the GQL prefixes in them.
- [ ] There are some potential performance improvements to be made with avoiding cloning `Context` by passing around `&'a Context<'a>` instead of `&Context<'a>` in the resolver logic.
- [ ] `Schema` bounds Query and Mutation by the hidden type `ObjectType`, so either we publicize that or work around it somehow.

These next ideas are lot more vague. I don't know exactly what to do yet, just that something needs to change.

- [ ] Error handling. I think at the moment the library has too many error types.
- [ ] Context. I understand why it's the way it is, but it's still very complex and I'm sure with enough thought some simplifications can be made, such as removing the generic parameter and reducing lifetime usage.
- [ ] Validation; the trait-based system doesn't sit right with me because it makes each validation rule feel like an addon and not part of the core GraphQL logic. Each validation rule also stores some internal state some of which is duplicated between validation rules, which is less efficient than it could be. In general I dislike the callback trait pattern because it's entirely based on side effects.
- [ ] Maybe add an extra pass over the query that does things like inline fragments and variables so we don't have to duplicate that logic later; doing so would also remove the need for resolvers and validators to access request-global state.

**Comment by sunli829** [comment]
Can we use `Value` instead of `ConstValue`? This makes the code simpler. @Koxiaet

**Comment by Koxiaet** [comment]
> Can we use `Value` instead of `ConstValue`? This makes the code simpler. @Koxiaet 

Does it?  I don't think it makes much sense for resolvers to return and variables to contain variables, so wouldn't ConstValue be easier?

**Comment by sunli829** [comment]
> > Can we use `Value` instead of `ConstValue`? This makes the code simpler. @Koxiaet
> 
> Does it? I don't think it makes much sense for resolvers to return and variables to contain variables, so wouldn't ConstValue be easier?

These two types are actually similar. Of course, it is strange that ConstValue contains variables, but it looks simpler. We don't need to implement two sets of methods with similar functions for Value and ConstValue. What do you think? 🙂

**Comment by Koxiaet** [comment]
@sunli829 It's a tough question, but I still think that keeping them separate will be better. It's a bit complex on the implementation side, but it's worth it as it can be less confusing for users.

**Comment by mwilliammyers** [comment]
@Koxiaet RE: async `UploadValue`, see: https://github.com/async-graphql/async-graphql/issues/151

(I still 100% agree, it should be async)

**Comment by mwilliammyers** [comment]
Can we expose a public API for `async-graphql-parser` so we don't need to depend on that crate directly? 

I had to depend on that crate to:
```
use async_graphql_parser::query::{Definition, Document, OperationDefinition, Selection};
```
In order to make a custom `Logger` extension.

I don't know if that has been addressed, because I am about 1-2 months behind on updates.

**Comment by sunli829** [comment]
> Can we expose a public API for `async-graphql-parser` so we don't need to depend on that crate directly?
> 
> I had to depend on it to:
> 
> ```
> use async_graphql_parser::query::{Definition, Document, OperationDefinition, Selection};
> ```
> 
> In order to make a custom `Logger` extension.
> 
> I don't know if that has been addressed, because I am about 1-2 months behind on updates.

`async_graphql::parser`

It's actually hidden.😃

**Comment by Koxiaet** [comment]
@mwilliammyers I've made `async_graphql::parser` public now.

**Comment by mwilliammyers** [comment]
We should rename `GQLResponse` and everything that starts with `GQL` everywhere (e.g. the integrations crates) to match the rename that happened the other day.

**Comment by sunli829** [comment]
I removed all GQL prefixes, but now there is a very annoying problem, we now have async_graphql::Request, async_graphql_actix_web::Request, async_graphql_warp::Request, async_graphql_rocket::Request, which makes me very confused.

**Comment by mwilliammyers** [comment]
You will only (99% of the time) ever have two requests in a single project `async_graphql::Request` and one of the integrations, so it is not that confusing. It might be confusing for async-graphql devs, but it is the end user that matters 🙂 

Also, the style guide [recommends to avoid redundant prefixes](https://doc.rust-lang.org/1.0.0/style/style/naming/README.html#avoid-redundant-prefixes-[rfc-356]), recommending:
> Library clients can rename on import to avoid clashes.

I commonly do: 
```rust
use serde_json::Value as JsonValue;
use graphql::Value as GraphqlValue;
```

(and yes I do: `graphql = { ..., package = "async-graphql-warp" }` 🙃 )

**Comment by mwilliammyers** [comment]
Was it intentional that all the `DateTime*` types are now named `DateTime`? e.g. `DateTimeUtc` was renamed to `DateTime`.

**Comment by sunli829** [comment]
> Was it intentional that all the `DateTime*` types are now named `DateTime`? e.g. `DateTimeUtc` was renamed to `DateTime`.

Yes, I think time zone doesn't seem to make much sense to GraphQL?

**Comment by mwilliammyers** [comment]
While I agree this is much cleaner, it was explicit that the datetime needed to be in UTC, especially if the underlying Chrono type requires UTC. (or a fixed offset)

**Comment by sunli829** [comment]
> While I agree this is much cleaner, it was explicit that the datetime needed to be in UTC, especially if the underlying Chrono type requires UTC. (or a fixed offset)

In fact, the time passed in the GraphQL query is always rfc3339, which has its own time zone information, and async-graphql can convert it to Utc, Local or FixedOffset.

**Comment by mwilliammyers** [comment]
So if a user passes in `2020-09-20T07:00:00-07:00`, I will get `2020-09-20T14:00:00+00:00` (not `2020-09-20T07:00:00+00:00`) even if it is a `chrono:: DateTime<Utc>` (not `chrono:: DateTime<FixedOffset>`) in my code?

**Comment by sunli829** [comment]
> So if a user passes in `2020-09-20T07:00:00-07:00`, I will get `2020-09-20T14:00:00+00:00` (not `2020-09-20T07:00:00+00:00`) even if it is a `chrono:: DateTime<Utc>` (not `chrono:: DateTime<FixedOffset>`) in my code?

Yes, now it seems more reasonable for the type name to be DateTime?

**Comment by mwilliammyers** [comment]
Yup! Perfect name and behavior. Thanks!

**Comment by mwilliammyers** [comment]
What does `2020-09-20T07:00:00` default to? Local timezone of the server?

**Comment by sunli829** [comment]
> What does `2020-09-20T07:00:00` default to? Local timezone of the server?

I don't know, I will try. . . 😂

**Comment by phated** [comment]
@Koxiaet I'm super excited for the work on Context! The difficulties with working with it are what caused me to put my project on hold. 

Something else that I noticed wasn't mentioned was an investigation on whether GraphQL interfaces could be supported as traits instead of enums. I believe the issues with it previously were tied to the current implementation of macros. What do you think?

**Comment by Koxiaet** [comment]
@phated What would you in particular like to change about `Context`? I have no real ideas atm so anything would be helpful.

The main complication with allowing traits is that all types need to be registered in the registry but you can't know at compile time all the implementors of a trait. You'd have to list the implementors of the trait when you define it, but that would make it very easy to accidentally create an incomplete schema if you add a new implementor but forget to list it.

A solution to this would be to make manual implementations of the trait fake and force all real implementations to be listed next to the trait itself, with aa sealed trait. So you can implement it all you like but it won't _actually_ implement until you list it next to the trait.

**Comment by Koxiaet** [comment]
Actually I've just discovered the [inventory](https://github.com/dtolnay/inventory) crate which may just allow us to support trait-based interfaces without having to statically declare all implementations of the trait.

**Comment by mwilliammyers** [comment]
Are we going to keep the ability to define interfaces using enums too? I like the flexibility of having both choices.

**Comment by Koxiaet** [comment]
> Are we going to keep the ability to define interfaces using enums too? I like the flexibility of having both choices.

Yes, of course!

**Comment by sunli829** [comment]
My opinion is that unless it can be easier to use than the current `Interface`, it is better not to change it.

**Comment by Koxiaet** [comment]
I think it can be. Traits are a lot easier to write out than the custom attribute syntax, and duplicating the list of implementations isn't ideal. It also allows for crates to extend other crate's interfaces (I don't know if this will be useful or not though). Additionally it's far more intuitive than enums.

But since it's a non-breaking addition we should probably focus on 2.0 first.

**Comment by phated** [comment]
@Koxiaet yeah, I was thinking the traits could use a macro that could then expand to something like the `inventory` registration (maybe that could just be done ourselves?).

> What would you in particular like to change about Context? I have no real ideas atm so anything would be helpful.

After using Context a bunch, I found that it's probably just a trap to support custom data being added to a global context at all. Once a project grows, you'll want custom dataloaders and other things that need to be scoped only to the request, which requires massive refactoring to make everything work.

I think that the global data can be removed from the context and it should just be scoped to a request. It then can be set up to be strongly typed, so you can do something like this:

```rust
struct Data {
  something_always_available: String,
  logged_in_user: Option<UserDataloader>,
  ...
}

type Context = async_graphql::Context<CtxData>;
```

This allows all the resolvers to import the custom Context provided to the app, but it will still be strongly typed while accessing your data and not a dynamic lookup. Someone in the team can modify the Context and everyone else will know that something new is available through the type system. This also allows leveraging the type system to inform devs when something might not be there and they can write appropriate code.

What do you think?

**Comment by sunli829** [comment]
> @Koxiaet yeah, I was thinking the traits could use a macro that could then expand to something like the `inventory` registration (maybe that could just be done ourselves?).
> 
> > What would you in particular like to change about Context? I have no real ideas atm so anything would be helpful.
> 
> After using Context a bunch, I found that it's probably just a trap to support custom data being added to a global context at all. Once a project grows, you'll want custom dataloaders and other things that need to be scoped only to the request, which requires massive refactoring to make everything work.
> 
> I think that the global data can be removed from the context and it should just be scoped to a request. It then can be set up to be strongly typed, so you can do something like this:
> 
> ```rust
> struct Data {
>   something_always_available: String,
>   logged_in_user: Option<UserDataloader>,
>   ...
> }
> 
> type Context = async_graphql::Context<CtxData>;
> ```
> 
> This allows all the resolvers to import the custom Context provided to the app, but it will still be strongly typed while accessing your data and not a dynamic lookup. Someone in the team can modify the Context and everyone else will know that something new is available through the type system. This also allows leveraging the type system to inform devs when something might not be there and they can write appropriate code.
> 
> What do you think?

I don't think this is a good idea, it greatly improves the difficulty of using the library, because the CtxData parameter will be passed everywhere, but only brings a negligible performance improvement.

**Comment by phated** [comment]
@sunli829 I did not mention performance. I am discussing working on large projects with a big team of developers. The issue remains that context is dynamic and the team does not know what is available.

**Comment by sunli829** [comment]
> @sunli829 I did not mention performance. I am discussing working on large projects with a big team of developers. The issue remains that context is dynamic and the team does not know what is available.

In fact, `Juniper` currently uses such a design, but it is not easy to use, which is why I will use a design similar to `Actix-web`.

**Comment by phated** [comment]
@sunli829 "easy" is fine until you actually need to work with large teams. I'd recommend the talk "Simple made easy" by Rich Hickey. If your desire is for async-graphql to be usable by large teams, you can't lean so heavily into dynamic features (that's not why they chose rust).

**Comment by sunli829** [comment]
> @sunli829 "easy" is fine until you actually need to work with large teams. I'd recommend the talk "Simple made easy" by Rich Hickey. If your desire is for async-graphql to be usable by large teams, you can't lean so heavily into dynamic features (that's not why they chose rust). There is too much "magic" in the way you previously designed Context (which I think @Koxiaet was picking up on by their desire to change it).

Regarding the shortcomings of generic CtxData, this issue(Juniper #655) has a more detailed explanation, you can refer to it.

**Comment by phated** [comment]
I've already reviewed that issue extensively and the user is just asking for MORE dynamic dispatch. If you research the people, they are just hobbyists building simple things where dynamic dispatch doesn't matter. Meanwhile, I am actively talking to large teams trying to build large GraphQL servers and they don't want to risk using the project currently. There are a lot of rough edges that don't scale teams.

It feels very terrible to try to contribute insights to this project when you continue to use one single argument to justify this API design. You don't even allow discussion to happen around ways to improve it.

**Comment by sunli829** [comment]
> I've already reviewed that issue extensively and the user is just asking for MORE dynamic dispatch. If you research the person, they are just hobbyists building simple things where dynamic dispatch doesn't matter. Meanwhile, I am actively talking to large teams trying to build large GraphQL servers and they don't want to risk using the project currently. There are a lot of rough edges that don't scale amongst large teams.
> 
> It feels very terrible to try to contribute insights to this project when you continue to use one single argument to justify this API design. You don't even allow discussion to happen around ways to improve it.

Any suggestions for amendments are welcome, like Koxiaet's #261, this is a huge change.
But regarding CtxData, your suggestion to use generics also has its benefits, but I still have to think about whether it is worth making a lot of changes for this.

**Comment by sunli829** [comment]
So, we wait for @Koxiaet  to give his thoughts, if he also thinks this change is necessary, then I will do it immediately. 😁

**Comment by Koxiaet** [comment]
Is it possible to give users the choice? So `Context` would become an alias for `???<Data>` but you could also use `???<SomeUserType>`. I don't know what ??? should be named yet. It's more complex than either of the two other solutions but only by a small amount, and is more modular so may even be easier but I don't really know. Thoughts?

**Comment by phated** [comment]
@Koxiaet that would fit along with my idea of re-exporting context as an alias of the more complex type, so I like it! I think the way you access the internal data would need to change though, is that correct?

**Comment by sunli829** [comment]
@Koxiaet Is it really necessary to remove the dependency on `serde_json`?

**Comment by Koxiaet** [comment]
> @Koxiaet Is it really necessary to remove the dependency on `serde_json`?

Ideally we would - GraphQL is transport agnostic. What's the problem?

**Comment by sunli829** [comment]
> > @Koxiaet Is it really necessary to remove the dependency on `serde_json`?
> 
> Ideally we would - GraphQL is transport agnostic. What's the problem?

It's a lot of work.😂

**Comment by mwilliammyers** [comment]
Something that came up in Juniper semi-frequently, and something that will inevitably come up here is: should there be a public parser API/crate?

I am already running into issues trying to create a custom logger extension... I have made it through a few rounds of updates but I think I hit a wall with  `ExecutableDefinition` being renamed to `DefinitionItem` and made private. I think? It is really hard to keep up 😂

**Comment by Koxiaet** [comment]
@mwilliammyers There is. [async-graphql-parser](https://crates.io/crates/async-graphql-parser), although its version numbers are kept in sync with `async-graphql`, is a standalone crate.

**Comment by mwilliammyers** [comment]
Ahh, I thought that wasn't being published anymore because things got shuffled around. 👍

**Comment by smmoosavi** [comment]
> Actually I've just discovered the inventory crate which may just allow us to support trait-based interfaces without having to statically declare all implementations of the trait.

maybe we can use the "inventory" idea instead of MergeObject API.
