### ISSUE TITLE
Question: `BigDecimal` rendering

### ISSUE THREAD

**Issue by rkudryashov** [async-graphql/async-graphql#212]
In the repro-project (https://github.com/rkudryashov/async-graphql-reproducer) I have `CustomDecimal` - wrapper for BigDecimal to use it as scalar:

```
#[derive(Clone)]
pub struct SomeType {
...
    test_field: CustomDecimal,
...
}
```
```
#[derive(Clone, Serialize)]
pub struct CustomDecimal(pub BigDecimal);

#[Scalar(name = "Decimal")]
impl ScalarType for CustomDecimal {
    fn parse(value: Value) -> InputValueResult<Self> {
        unimplemented!()
    }

    fn to_value(&self) -> Value {
        // Value::String(self.0.to_string())
        Value::Float(self.0.to_f64().unwrap())
    }
}
```

Such implementation introduces an issue with precision, for example, this (https://github.com/rkudryashov/async-graphql-reproducer/blob/master/some-service/src/graphql.rs):

```
        SomeType {
            ...
            test_field: CustomDecimal(BigDecimal::from(2439.3)),
            ...
        }
```

will be displayed as:

```
{
  "data": {
    "someQuery": {
      "testField": 2439.2999999999997
    }
  }
}
```

if I perform
```
{
  someQuery {
    testField
  }
}
```

I can use `String`:

```
    fn to_value(&self) -> Value {
        Value::String(self.0.to_string())
        // Value::Float(self.0.to_f64().unwrap())
    }
```
But it is not the best approach either (quotes and excessive zeroes):

```
{
  "data": {
    "someQuery": {
      "testField": "2439.300000000000"
    }
  }
}
```

What is the best approach to do that?

**Comment by sunli829** [comment]
I recommend representing `Decimal` as a string, and the problem you're having now I think is caused by `BigDecimal`.

**Comment by sunli829** [comment]
Int64 is now supported.

**Comment by rkudryashov** [comment]
@sunli829 if I understand correctly I should still use 

```rust
    fn to_value(&self) -> Value {
        Value::String(self.0.to_string())
    }
```

for this?

**Comment by rkudryashov** [comment]
Also, for another case I have tried to use `Value::Number`:

```rust
    fn to_value(&self) -> Value {
        Value::Number(self.0.to_f64().expect("Can't get f64"))
    }
```

but that code stopped compiling:

```
cargo run
   Compiling async-graphql v1.16.14
error[E0599]: no variant or associated item named `Number` found for enum `async_graphql_parser::value::Value` in the current scope

error[E0599]: no variant or associated item named `Number` found for enum `async_graphql_parser::value::Value` in the current scope
  --> C:\Users\notba\.cargo\registry\src\github.com-1ecc6299db9ec823\async-graphql-1.16.14\src\scalars\id.rs:80:20
```

I use the following dependencies:

```toml
async-graphql = "1.16.14"
async-graphql-actix-web = "1.16.10"
```

**Comment by sunli829** [comment]
> Also, for another case I have tried to use `Value::Number`:
> 
> ```rust
>     fn to_value(&self) -> Value {
>         Value::Number(self.0.to_f64().expect("Can't get f64"))
>     }
> ```
> 
> but that code stopped compiling:
> 
> ```
> cargo run
>    Compiling async-graphql v1.16.14
> error[E0599]: no variant or associated item named `Number` found for enum `async_graphql_parser::value::Value` in the current scope
> 
> error[E0599]: no variant or associated item named `Number` found for enum `async_graphql_parser::value::Value` in the current scope
>   --> C:\Users\notba\.cargo\registry\src\github.com-1ecc6299db9ec823\async-graphql-1.16.14\src\scalars\id.rs:80:20
> ```
> 
> I use the following dependencies:
> 
> ```toml
> async-graphql = "1.16.14"
> async-graphql-actix-web = "1.16.10"
> ```

```rust
Value::Number(serde_json::Number::from_f64(self.0.to_f64().expect("Can't get f64")))
```

**Comment by rkudryashov** [comment]
Still is not compiled. It seems like `Value::Number` is not in the scope. Repro: https://github.com/rkudryashov/graphql-federation-rust, `cargo run`

**Comment by rkudryashov** [comment]
Still is not compiled. It seems like Value::Number is not in the scope. Repro: https://github.com/rkudryashov/async-graphql-reproducer, `cargo run`

**Comment by sunli829** [comment]
```rust
fn to_value(&self) -> Value {
        Value::Number(
            self.0
                .to_f64()
                .and_then(|value| async_graphql::Number::from_f64(value))
                .expect("Can't get f64"),
        )
    }
```

**Comment by rkudryashov** [comment]
Thanks
