### ISSUE TITLE
How to handle duplicate definition

### ISSUE THREAD

**Issue by ilaborie** [async-graphql/async-graphql#214]
I've got a compilation error : `error[E0592]: duplicate definitions with name `id` for something like:

```rust
#[SimpleObject]
pub struct Session {
  id: String,
}
impl Session {
  pub fn id() -> String { self.id.clone }
}
```

I've try to use a `#[field(skip)]` on the field, but, it's remove the `id` into the Schema 

How can I fix that issue ?

**Comment by sunli829** [comment]
I suggest changing the name of the `id` function, which is the only solution at present. 😁

**Comment by ilaborie** [comment]
Thanks, for the quick answer.
