### ISSUE TITLE
panic in async-graphql-parser

### ISSUE THREAD

**Issue by nicolaiunrein** [async-graphql/async-graphql#215]
`query_parser::parse_value2` panics on unwrap if you pass in an overflowing integer. I was about to fix it myself but I'm not sure how the PositionCalculator works and don't want to introduce a new bug.

**Comment by sunli829** [comment]
I have fixed it on the master branch, please confirm whether the problem has been solved. 😁

**Comment by nicolaiunrein** [comment]
Seems good. I added tests in eb04dcd, please review.  I discovered that parsing overflowing floats results in values parsed to infinity. Since it is the "Rust way" of handling this I guess the second test is obsolete. Feel free to remove it! :laughing:

**Comment by sunli829** [comment]
Thank you! 😀
