### ISSUE TITLE
Discussion: share struct as Object and InputObject

### ISSUE THREAD

**Issue by nicolaiunrein** [async-graphql/async-graphql#218]
I have a couple of `InputObjects` which I would like to expose as `Objects` as well.  At the moment this results in code duplication since I cannot use `Object` and `InputObject` at the same time. Maybe this would be possible if we could define an `InputObject` on an impl block. How do you all deal with this kind of issue?

**Comment by sunli829** [comment]
You mean, define `SimpleObject` and `InputObject` for the same struct?

```rust
#[derive(InputObject, SimpleObject)]
struct MyObj {
    a: i32,
    b: 32,
}
```

**Comment by nicolaiunrein** [comment]
I was trying this  which doesn’t work:

```rust
#[InputObject]
struct MyObject {
  a: u32
}

#[Object]
impl MyObject {
  async fn a(&self) -> u32 {
    self.a
  }
}
```

**Comment by sunli829** [comment]
Due to the current limitations of program macros, adding more parameters can solve this problem, but it will make the API use more complicated.

**Comment by nicolaiunrein** [comment]
But does your example above work? Using the derive?

**Comment by sunli829** [comment]
Same problem. 😅
