### ISSUE TITLE
Can't conditionally exclude a query (as well as mutation)

### ISSUE THREAD

**Issue by rkudryashov** [async-graphql/async-graphql#219]
I tried to conditionally compile a query:

```
pub struct Query;

#[Object]
impl Query {

    #[cfg(target_os = "linux")]
    async fn query_that_should_be_excluded(&self) -> &str {
        ""
    }
```

(My host machine is running Windows.)

That produces:

```
error[E0599]: no method named `query_that_should_be_excluded` found for reference `&graphql::Query` in the current scope
  --> some-service\src\graphql.rs:21:14
   |
21 |     async fn query_that_should_be_excluded(&self) -> &str {
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `&graphql::Query`

```

It is compiled successfully when I change `target_os` to `windows`.

Is it possible to conditionally compile queries/mutations/subscriptions? Some scenarios for that I can imagine are when you need some queries only in debug mode or stage environments, but not in production.

Repro: https://github.com/rkudryashov/async-graphql-reproducer

**Comment by rkudryashov** [comment]
Also, if there is any other ability to conditionally "hide" a query, it would be nice.

**Comment by sunli829** [comment]
Due to the limitation of procedural macros, this cannot be supported.

**Comment by nicolaiunrein** [comment]
You could have two mods with different subqueries and toggle the mods. Not very elegant but pretty sure this would work.

**Comment by sunli829** [comment]
That's one way to do it.

```rust
pub struct Query;

#[Object]
impl Query {
    async fn query_that_should_be_excluded(&self) -> &str {
            #[cfg(target_os = "linux")]
            {
                 .....
            }
    }
```

**Comment by rkudryashov** [comment]
I thought I had found an elegant solution for my case:

```
    #[cfg_attr(target_os = "windows", field(guard(BlockingGuard())))]
    async fn query_that_should_be_excluded(&self) -> &str {
        ""
    }

struct BlockingGuard;

#[async_trait::async_trait]
impl Guard for BlockingGuard {
    async fn check(&self, ctx: &Context<'_>) -> FieldResult<()> {
        Err("Forbidden".into())
    }
}
```

But this is not compiled: `error: cannot find attribute `field` in this scope`

Is it by the same reason that was in the first comment?

**Comment by sunli829** [comment]
> I thought I had found an elegant solution for my case:
> 
> ```
>     #[cfg_attr(target_os = "windows", field(guard(BlockingGuard())))]
>     async fn query_that_should_be_excluded(&self) -> &str {
>         ""
>     }
> 
> struct BlockingGuard;
> 
> #[async_trait::async_trait]
> impl Guard for BlockingGuard {
>     async fn check(&self, ctx: &Context<'_>) -> FieldResult<()> {
>         Err("Forbidden".into())
>     }
> }
> ```
> 
> But this is not compiled: `error: cannot find attribute `field` in this scope`
> 
> Is it by the same reason that was in the first comment?

Due to the limitation of procedural macros, this cannot be supported. 😁

**Comment by sunli829** [comment]
Only `derive` can handle `cfg_attr` properly at the moment.
