### ISSUE TITLE
Return result for validators

### ISSUE THREAD

**Issue by olanod** [async-graphql/async-graphql#221]
A small thing that triggered a bit of OCD, wouldn't it be more appropriate conceptually if the return type of a  
`InputValueValidator::is_valid(&self, value: &Value)` is a `Result<(), String>` instead of an `Option<String>`? A failed validation is an error isn't it? and something going as expected `Ok`? `Result` can represent that better than "the absence of value" `None` :)

**Comment by sunli829** [comment]
I think you're right, so I've changed the function's return value to be of type Result. 😁
