### ISSUE TITLE
Clean up crate root

### ISSUE THREAD

**Issue by Koxiaet** [async-graphql/async-graphql#223]
Currently the crate root contains a lot of items, which can be quite intimidating to new users. I propose that two new modules are created, `types` which contains commonly used GraphQL types and `protocol` which contains lower-level GraphQL types (this name is up for debate) that the user won't typically use. The following items should be moved:

```
Any -> types::Any
EmptyMutation -> types::EmptyMutation
EmptySubscription -> types::EmptySubscription
ID -> types::Id
Json -> types::Json
Lookahead -> protocol::Lookahead
Number -> types::Number
OutputJson -> types::OutputJson
Pos -> protocol::Pos
Positioned -> protocol::Positioned
QueryPathNode -> protocol::QueryPathNode
RuleError -> protocol::RuleError
Upload -> types::Upload
Variables -> protocol::Variables
WebSocketTransport -> http::WebSocketTransport
ParseRequestError -> protocol::ParseRequestError
Value -> types::Value
```

And of course the crate will also `pub use types::*` and `pub use protocol::*` so it won't be a breaking change. However, it will make it easier for people to read the library docs as the types will be better organized.

`types` could also be called `scalars` and just contain scalars.

**Comment by sunli829** [comment]
> Currently the crate root contains a lot of items, which can be quite intimidating to new users. I propose that two new modules are created, `types` which contains commonly used GraphQL types and `protocol` which contains lower-level GraphQL types (this name is up for debate) that the user won't typically use. The following items should be moved:
> 
> ```
> Any -> types::Any
> EmptyMutation -> types::EmptyMutation
> EmptySubscription -> types::EmptySubscription
> ID -> types::Id
> Json -> types::Json
> Lookahead -> protocol::Lookahead
> Number -> types::Number
> OutputJson -> types::OutputJson
> Pos -> protocol::Pos
> Positioned -> protocol::Positioned
> QueryPathNode -> protocol::QueryPathNode
> RuleError -> protocol::RuleError
> Upload -> types::Upload
> Variables -> protocol::Variables
> WebSocketTransport -> http::WebSocketTransport
> ParseRequestError -> protocol::ParseRequestError
> Value -> types::Value
> ```
> 
> And of course the crate will also `pub use types::*` and `pub use protocol::*` so it won't be a breaking change. However, it will make it easier for people to read the library docs as the types will be better organized.
> 
> `types` could also be called `scalars` and just contain scalars.

It looks great! 😁
