### ISSUE TITLE
Question: representation of very big int

### ISSUE THREAD

**Issue by rkudryashov** [async-graphql/async-graphql#225]
For very big numbers, for example `4870000000000000000000000` it is more convenient to represent that number as value with mantissa and exponent: `4.87e+24`. I managed to do this as follows (https://github.com/rkudryashov/async-graphql-reproducer/blob/master/some-service/src/graphql.rs):

```rust
#[derive(Clone)]
struct CustomBigInt(BigInt);

#[Scalar(name = "BigInt")]
impl ScalarType for CustomBigInt {

    fn to_value(&self) -> Value {
        self.0.to_f64()
            .and_then(|value| async_graphql::Number::from_f64(value))
            .map(|value| Value::Number(value))
            .expect("Can't convert BigInt")
    }
}
```

```graphql
{
  "data": {
    "someQuery": {
      "testInt": 4.87e+24
    }
  }
}
```

But I didn't manage to get rid of using `f64`: the following is compiled but fails at runtime:

```rust
    fn to_value(&self) -> Value {
        self.0.to_i64()
            .and_then(|value| Some(async_graphql::Number::from(value)))
            .map(|value| Value::Number(value))
            .expect("Can't convert BigInt")
    }
```

Representation as String:

```rust
Value::String(self.0.to_string())
```

 is not suitable for my case, because in this way the value will be represented as follows:

```graphql
{
  "data": {
    "someQuery": {
      "testInt": "4870000000000000000000000"
    }
  }
}
```

Perhaps my question is not directly related to `async-graphql`. The question is about how to replace `BigInt.to_f64()` with `to_i64` (just because it looks strange to use `to_f64` for `BigInt`) or something other and maybe other your thoughts on the subject.

**Comment by nicolaiunrein** [comment]
You can easily convert your large integer to a string with exponential/scientific notation by using `format!("{:e}", n)` or `format!("{:E}", n)` in fact this works for all types implementing `std::fmt::LowerExp` or `std::fmt::UpperExp` accordingly. I think with that you could easily create a custom Scalar eg. `ScientificInt`.

**Comment by rkudryashov** [comment]
Thanks, I'll try it
