### ISSUE TITLE
Forwards compatibility and the @if_def Directive

### ISSUE THREAD

**Issue by D1plo1d** [async-graphql/async-graphql#227]
###  Strawman Proposal

Add an `@if_def` field directive that allows GraphQL queries against fields that are not defined on the server to be excluded from the response.

For example:
```
query {
  @if_def name
  @if_def website
}
```

Where a `name` field is defined in a resolver but `website` is not would return:
```
{
  name: "D1plo1d",
  website: None,
}
```

#### Background

In my software many distributed 3D printers present GraphQL interfaces to a user's single centralized frontend. These servers are managed by users so each server may be running a different schema version. Also these servers talk directly to the frontend for end-to-end encryption.

#### The Problem

The issue I have is that I cannot add new fields to frontend queries without breaking compatibility with older servers which will error because the field is not defined on them

So in addition to the strong backwards compatibility of GraphQL I am looking to add a sort of "forwards compatiblity". `@if_def` is my thinking so far but I'd really like to hear alternative solutions or if/how this could be implemented outside of the core of async-graphql.

Reference: https://spec.graphql.org/June2018/#Directives

**Comment by sunli829** [comment]
Let me think about it.

**Comment by D1plo1d** [comment]
Appreciate it!

**Comment by sunli829** [comment]
I added the `@ifdef` directive in `v1.17.3`.


**Here is the test code.** 

https://github.com/async-graphql/async-graphql/blob/5cdb2a99b818ea0c601e6dd86b52f9ef6d94811d/tests/directive.rs#L66

**Comment by D1plo1d** [comment]
Wow! That is beyond awesome. Thanks so much @sunli829!
