### ISSUE TITLE
How to combine union type with interface?

### ISSUE THREAD

**Issue by acelot** [async-graphql/async-graphql#228]
How to implement such types with `async-graphql`?

```graphql
type Article {
  id: Int!
  title: String!
}

interface ProblemInterface {
  message: String!
}

type NotFoundProblem implements ProblemInterface {
  message: String!
}

type InternalErrorProblem implements ProblemInterface {
  message: String!
}

union ArticleResult = Article | NotFoundProblem | InternalErrorProblem
```

**What I've done:**

`Article` type:
```rust
#[async_graphql::SimpleObject]
pub struct Article {
    pub id: i32,
    pub title: String,
}
```

`NotFoundProblem` type:
```rust
#[async_graphql::SimpleObject]
pub struct NotFoundProblem {
    pub message: String,
}
```

`InternalErrorProblem` type:
```rust
#[async_graphql::SimpleObject]
pub struct InternalErrorProblem {
    pub message: String,
}
```

`ProblemInterface` interface type:
```rust
#[async_graphql::Interface(
    field(name = "message", type = "&String")
)]
pub enum ProblemInterface {
    InternalErrorProblem(InternalErrorProblem),
    NotFoundProblem(NotFoundProblem),
}
```

`ArticleResult` union type:
```rust
#[async_graphql::Union]
enum ArticleResult {
    Article(Article),
    NotFoundProblem(NotFoundProblem),
    InternalErrorProblem(InternalErrorProblem),
}
```

## Main issue
The problem is that `ArticleResult` union type announces `NotFoundProblem` and `InternalErrorProblem` types as simple objects that do not implement the `ProblemInterface`.

![2020-08-05-21:23:10-screenshot](https://user-images.githubusercontent.com/1065215/89424557-24a85580-d762-11ea-92dc-c3d0307cc137.png)
![2020-08-05-21:24:33-screenshot](https://user-images.githubusercontent.com/1065215/89424550-22de9200-d762-11ea-8610-9bd8812bb36a.png)
![2020-08-05-21:23:37-screenshot](https://user-images.githubusercontent.com/1065215/89424555-240fbf00-d762-11ea-8e62-47629df2f36f.png)

**Comment by phated** [comment]
If you don't have an endpoint that returns the interface itself, automatic lookup doesn't work. You need to register the interface with the schema [`register_type`](https://docs.rs/async-graphql/1.17.2/async_graphql/struct.SchemaBuilder.html#method.register_type) like I did at https://github.com/phated/twentyfive-stars/blob/master/server/src/main.rs#L135-L136
