### ISSUE TITLE
Pushing metrics

### ISSUE THREAD

**Issue by jayy-lmao** [async-graphql/async-graphql#229]
This is such a cool project, really been loving the apollo support.

Just curious: 

> `in apollo_tracing.rs`
> It’s already supported by `Apollo Engine`, and we’re excited to see what other kinds of integrations people can build on top of this format.

What is `Apollo Engine` referring to here? Is it the tracing in GraphQL Playground / Graphiql, or is it able to trace-report to Apollo Engine / Studio?

If not, are there any plans to support it?

https://www.apollographql.com/docs/studio/setup-analytics/#third-party-support

**Comment by sunli829** [comment]
I haven't tried it in Apollo Studio, but this tracing log can be recognized by GraphQL Playground, so I guess Apollo Studio can also?

**Comment by jayy-lmao** [comment]
Thank's for the quick response! I've done a bit more of a dig, looks like studio requires pushing metrics (unless there's another way not referenced in docs). Think it would probably need to be a custom extension, all good :)
