### ISSUE TITLE
Merge Schemas

### ISSUE THREAD

**Issue by D1plo1d** [async-graphql/async-graphql#231]
## Strawman Proposal
A `merge_schemas` fn or macro to combine many schemas into one.

```rust
use std::iter::IntoIterator

pub fn merge_schemas(schemas: IntoIterator<Schema>) -> Schema {
    // [Magic]
}
```

## Motivation

I am trying to organize a growing number of mutation and query fields in order to keep my code base readable at a glance. Given that we can't split our Mutation and Query `#[Object]` into multiple impl blocks a `merge_schemas` fn could provide an alternative - allowing us to organize our resolvers into smaller, domain-oriented Schema objects (eg. `src/users/schema.rs`, `src/movies/schema.rs`) which could then be merged at the top of our application.

Reference: https://www.graphql-tools.com/docs/merge-schemas

**Comment by sunli829** [comment]
I'm trying.

**Comment by sunli829** [comment]
This feature is not as easy to implement as it seems, but I thought of a more elegant way.

You can use the following procedure macro to create a merged object.

```rust
#[MergeObject]
struct MyObj(ObjA, ObjB, ObjC);
```

Construct a merged object.

```rust
MyObj(ObjA{ ... }, ObjB{ ... }, ObjC{ ... })
```

**Comment by sunli829** [comment]
I added `MergedObject` in `v1.17.4`.

**Comment by D1plo1d** [comment]
Wow, Awesome! Ok, I'm trying this out today and I've noticed that this works:

```
#[MergeObject]
struct Mutation(A::MutationA, B::MutationB);
```

but using the same name for merged objects results in drops fields:

```
#[MergeObject]
struct Mutation(A::Mutation, B::Mutation);
```

**Comment by D1plo1d** [comment]
I'm finding that I am writing the same Default impl for each of my unit struct MergeObjects. This may be unnecessary boilerplate. I wonder if we could reduce repetition by skipping unit structs in `MergeObject::new()` or adding automatic MergeObject Default implementations where appropriate.

```
#[MergedObject]
pub struct Mutation(
    LegacyMutation,
    PrintQueueMutation,
);

impl Default for Mutation {
    fn default() -> Self {
        Self::new(
            LegacyMutation,
            PrintQueueMutation::default(),
        )
    }
}

let mutation: Mutation = Default::default();
Schema::new(query, mutation, subscription)
```

**Comment by sunli829** [comment]
> Wow, Awesome! Ok, I'm trying this out today and I've noticed that this works:
> 
> ```rust
> #[MergeObject]
> struct Mutation(A::MutationA, B::MutationB);
> ```
> 
> but using the same name for merged objects results in drops fields:
> 
> ```rust
> #[MergeObject]
> struct Mutation(A::Mutation, B::Mutation);
> ```

This problem is not easy to solve, you can give different type names, or different GQL names.

```rust
mod a {
        use super::*;

        #[derive(GQLSimpleObject)]
        #[graphql(name = "QueryA)]
        pub struct Query {
            pub a: i32,
        }
    }

    mod b {
        use super::*;

        #[derive(GQLSimpleObject)]
        #[graphql(name = "QueryB")]
        pub struct Query {
            pub b: i32,
        }
    }
```

**Comment by sunli829** [comment]
Add `Default` implementation for `MergedObject` in `v1.17.5`.

Here is the test code.

https://github.com/async-graphql/async-graphql/blob/bd706fb1741ab643029b2d5c0e0a1f67ff2bcfd9/tests/merged_object.rs#L86

**Comment by D1plo1d** [comment]
> This problem is not easy to solve, you can give different type names, or different GQL names.

That works well enough for me. The impl Default look great btw - looking forward to trying that out.

**Comment by sunli829** [comment]
Could you please help me add a chapter to the book to explain the usage of `MergedObject`? @D1plo1d

**Comment by sunli829** [comment]
I modified the way of creating `MergedObject` objects and removed the `new` constructor, which looks more reasonable.

**Comment by D1plo1d** [comment]
> Could you please help me add a chapter to the book to explain the usage of `MergedObject`? @D1plo1d

Happy to. I'll try and write up a draft after work.

**Comment by D1plo1d** [comment]
> ```rust
> #[derive(GQLMergedObject])
> struct MyObj(ObjA, ObjB, ObjC);
> 
> MyObj(ObjA{ ... }, ObjB{ ... }, ObjC{ ... })
> ```

Ah interesting, so the idea is that `GQLMergedObject` could be combined with other Derive Macros eg. derive_new? I'd definitely prefer the flexibility of this:

```rust
use derive_new;

#[derive(GQLMergedObject, new])
struct MyObj(
  #[new(default)]
  ObjA,
  #[new(default)]
  ObjB,
  #[new(default)]
  ObjC
);

MyObj::new()
```

**Comment by sunli829** [comment]
> ```rust
> ```rust
> #[derive(GQLMergedObject])
> struct MyObj(ObjA, ObjB, ObjC);
> 
> MyObj(ObjA{ ... }, ObjB{ ... }, ObjC{ ... })
> ```
> 
> 
> 
> Ah interesting, so the idea is that GQLMergedObject could be combined with other Derive Macros eg. derive_new?
> I definitely prefer the flexibility of this:
> ```rust
> use derive_new;
> 
> #[derive(GQLMergedObject, new])
> struct MyObj(
>   #[new(default)]
>   ObjA,
>   #[new(default)]
>   ObjB,
>   #[new(default)]
>   ObjC
> );
> 
> MyObj::new()
> ```
> ```

Yes, and support `#[cfg(...)]` . 😁

**Comment by leebenson** [comment]
Does this work with merging subscriptions? Are there any examples please?
