### ISSUE TITLE
no `MergedObject` in the root error

### ISSUE THREAD

**Issue by TsumiNa** [async-graphql/async-graphql#235]
Hi, I updated to v1.17.6, and got this and **no `GQLMergedObject` in the root** error when compiling.
I think these errors are from the version dependencies in `async-graphql/Cargo.toml`.

The current workaround is to add `async-graphql-derive` as dependence.

**Comment by sunli829** [comment]
I fixed the dependency issue in `v1.17.6`.

**Comment by TsumiNa** [comment]
Works like a charm! 😃
