### ISSUE TITLE
chrono::NaiveDateTime as a scalar?

### ISSUE THREAD

**Issue by Bajix** [async-graphql/async-graphql#237]
Could you demonstrate how to make chrono::NaiveDateTime a scalar?

**Comment by sunli829** [comment]
I have added scalar type for NaiveDateTime. 😁

https://github.com/async-graphql/async-graphql/blob/e596a27e05cca0a492602f54524580d3ec87a6c9/src/scalars/naive_time.rs#L34

**Comment by sunli829** [comment]
Here is a tutorial for make scalars.

https://async-graphql.github.io/async-graphql/en/custom_scalars.html

**Comment by Bajix** [comment]
Thanks for adding this!
