### ISSUE TITLE
Don't send data with 'complete' WebSocket message

### ISSUE THREAD

**Issue by Koxiaet** [async-graphql/async-graphql#238]
According to the [protocol](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md), the `GQL_COMPLETE` message does not contain any payload, however async-graphql currently sends the final data with the complete message instead of with the last `GQL_DATA` message.

**Comment by sunli829** [comment]
I fixed this problem in version `v1.17.8`, thank you! 😁
