### ISSUE TITLE
Add the IntoFieldError trait

### ISSUE THREAD

**Issue by hapcode** [async-graphql/async-graphql#242]
I want to use my own `type ApiResult<T> = std::result::Result<T, ApiError>` instead of `async-graphql::FieldResult`. This allows me to avoid calls like `.map_err(ApiError::from)` inside resolvers. The `?` will do it automatically. Something like [here](https://github.com/paullgdc/csj-recommandations/blob/e63d5feb3c402cd3a872b9915cb061fed45ef15d/backend/src/main.rs#L358) via Juniper.

Could you add this feature? I think this approach helps to make the application API cleaner.

**Comment by sunli829** [comment]
In fact, you don't need to map the error type yourself, you should use the `?` operator, as shown below.

```rust
fn create_recommandation(ctx: &Ctx, new: NewRecommandation) -> FieldResult<Recommandation> {
      let db = ctx.0.get()?;
      let new_todo = Recommandation {
            id: db.new_id(),
            name: new.name,
            link: new.link,
            created_by: "paul".to_string(), // TODO: use user id passed by authentificationx
            media: new.media.to_u8().unwrap(),
        };
        db.create_recommandation(&new_todo)?;
        Ok(new_todo)
}
```

**Comment by hapcode** [comment]
It's okay for a simple case. What if I have the two modules `store` and `database` with appropriate results:

```rust
pub enum ApiError {
    StoreError(StoreError),
    DatabaseError(DatabaseError),
}

impl From<StoreError> for ApiError ...
impl From<DatabaseError> for ApiError ...

pub enum StoreError {
    EngineError(rusqlite::Error),
    PoolError(r2d2::Error),
}

pub enum DatabaseError {
    EngineError(mysql::error::Error),
}

pub type StoreResult<T> = std::result::Result<T, StoreError>;
pub type DatabaseResult<T> = std::result::Result<T, DatabaseError>;
```

I need to convert a special module error to generic `ApiError` via `.map_err(ApiError::from)` for every call to a module method.

```rust
fn create_topic(ctx: &Ctx, topic: Topic) -> FieldResult<Topic> {
     let store = ctx.data::<Arc<Store>>();
     let database = ctx.data::<Arc<Database>>();

     // here `has_topic` returns `DatabaseResult<bool>`
     let exists: bool = database.has_topic(&topic).map_err(ApiError::from)?;

     // ... some logic

     // here `create_topic` returns `StoreResult<Topic>`
     Ok(store
         .create_topic(&topic)
         .map_err(ApiError::from)?);
}
```

**Comment by sunli829** [comment]
I made some attempts, because of other reasons, it is more difficult to add this function.

**Comment by hapcode** [comment]
Okay. Thanks anyway for your attempts.
