### ISSUE TITLE
Merge subscriptions

### ISSUE THREAD

**Issue by leebenson** [async-graphql/async-graphql#243]
Just surfacing [this comment](https://github.com/async-graphql/async-graphql/issues/231#issuecomment-680863034) as a separate issue for visibility.

I believe the current `#[derive(GQLMergedObject)]` approach only works for structs annotated as `#[Object]`. I've tried various combinations to get it working with `#[Subscription]`, but I don't think that's currently possible.

Having an equivalent merge tool for subscriptions would give it parity with query/mutation types.

Many thanks for the excellent lib!

**Comment by sunli829** [comment]
Let me try to support this. 😁

**Comment by sunli829** [comment]
Release in `v1.17.11`.

Here is test code: https://github.com/async-graphql/async-graphql/blob/1ad2a32f442276176e48de8244e4bcdf1c6a7a17/tests/merged_object.rs#L162

**It would be great if you can help me add a chapter on MergedSubscription to the book.**😂

**Comment by leebenson** [comment]
You're the best! Thank you. I'd be happy to submit a PR to add a chapter-- will work on that today.

Btw, async-graphql is being used in [Vector](https://vector.dev), for our upcoming API server and UI visualization tooling 👍

**Comment by sunli829** [comment]
> You're the best! Thank you. I'd be happy to submit a PR to add a chapter-- will work on that today.
> 
> Btw, async-graphql is being used in [Vector](https://vector.dev), for our upcoming API server and UI visualization tooling 👍

Vector is my favorite project! 😁

**Comment by leebenson** [comment]
Added subscription merging to the docs in #244

**Comment by nicolaiunrein** [comment]
Subscription Merging will simplify my code a lot! Great job!

**Comment by leebenson** [comment]
Closing, since this was added in v1.17.11. Thanks again @sunli829!
