### ISSUE TITLE
Feature request: support for #[serde(flatten)] // #[diesel(embed)]

### ISSUE THREAD

**Issue by Bajix** [async-graphql/async-graphql#255]
It would make it vastly simpler to compose input objects if one could leverage #[serde(flatten)] on input objects. Imagine for instance this use case:

```
#[derive(Insertable, AsChangeset, Serialize, Deserialize)]
#[table_name = "users"]
pub struct UpdateUser {
  pub id: i32,
  #[column_name = "familyName"]
  pub family_name: Option<String>,
  #[column_name = "givenName"]
  pub given_name: Option<String>,
}

#[derive(Insertable, AsChangeset, Serialize, Deserialize)]
#[table_name = "tags"]
struct Tag {
  pub id: i32,
  pub name: String
}

#[InputObject]
struct PatchUser {
 [serde(flatten)]
 user: UpdateUser,
 tags: Option<Vec<Tag>>
}
```

As you can see, doing flatten here makes this more composable as one can flatten the input for each of the related types and those types can have their own derives. Otherwise this input type would need to be split such that it had all of the fields of the base type and all of the related types and would need to then extract the base type. Ideally you could define a patch struct as an input object and flatten the insertable for that table and then add on each owned type and this would also flatten the GraphQL type

The current implementation would forces either multiple inputs or types such as:

```
#[InputObject]
struct PatchUser {
  pub id: i32,
  #[column_name = "familyName"]
  pub family_name: Option<String>,
  #[column_name = "givenName"]
  pub given_name: Option<String>,
 tags: Option<Vec<Tag>>
}
```

**Comment by sunli829** [comment]
Let me think about it.

**Comment by sunli829** [comment]
Release in `v1.17.19`. 

If you are free, I hope you can help me improve the chapter on `InputObject` in the book and add an introduction to the new `flatten` attribute. 🙂

**Comment by Bajix** [comment]
Amazing thanks so much! This makes it so much easier to compose using insertable building blocks.

I'll look into doing a PR for documentation soon

**Comment by sunli829** [comment]
Here is test code

https://github.com/async-graphql/async-graphql/blob/b7163d4f9217d7ed61b7147f67f6ef5a713893a3/tests/input_object.rs#L108

**Comment by Bajix** [comment]
Oh nice! I don’t see it shown on the tests, but this works with multiple flatten calls?

**Comment by sunli829** [comment]
> Oh nice! I don’t see it shown on the tests, but this works with multiple flatten calls?


I missed this test scenario and will add it now.

**Comment by sunli829** [comment]
I added this test.

https://github.com/async-graphql/async-graphql/blob/f87435b96c43d18b9fef9bc837c4fb23a345ce1c/tests/input_object.rs#L236

**Comment by Bajix** [comment]
Awesome sauce! Good work! Such an awesome project
