### ISSUE TITLE
Performance vs Juniper

### ISSUE THREAD

**Issue by AurelienFT** [async-graphql/async-graphql#265]
Hello,

I'm currently working on a project which use `Juniper`. I'm really interesting to switch to `async-graphl` but I would have some more precisions about performances. You said [here](https://github.com/async-graphql/async-graphql/issues/208#issuecomment-693244653) that you have better perfomance than Juniper. Can you provide more explanations about it please ?

Anyway, your repository is really cool and well maintained keep going up, you doing great !

Have a nice day

**Comment by sunli829** [comment]
Here is a simple benchmark. 🙂
In fact, whether it is `juniper` or `async-graphql`, the performance is quite good.

https://github.com/async-graphql/benchmark

**Comment by AurelienFT** [comment]
Oh didn't see the juniper file. Thank you.
