### ISSUE TITLE
Not compatable with Actix v3

### ISSUE THREAD

**Issue by longfellowone** [async-graphql/async-graphql#268]
Receiving the following error when trying to use with actix-web 3.0

```
error[E0277]: the trait bound `fn(actix_web::web::Data<async_graphql::Schema<QueryRoot, async_graphql::EmptyMutation, async_graphql::EmptySubscription>>, async_graphql_actix_web::GQLRequest) -> impl std::future::Future {index}: actix_web::dev::Factory<_, _, _>` is not satisfied
   --> todo\src\main.rs:168:43
    |
168 |                     .route(web::post().to(index))
    |                                           ^^^^^ the trait `actix_web::dev::Factory<_, _, _>` is not implemented for `fn(actix_web::web::Data<async_graphql::Schema<QueryRoot, async_graphql::EmptyMutation, async_graphql::EmptySubscription>>, async_graphql_actix_web::GQLRequest) -> impl std::future::Future {index}`
```

**Comment by sunli829** [comment]
Do you use async-graphql 2.0？

**Comment by longfellowone** [comment]
No I am using version 1.18, do I need to use version 2? Is there anyway to access the book for v2?

**Comment by longfellowone** [comment]
No I am using version 1.18, do I need to use version 2? Is there anyway to access the book for v2?

**Comment by longfellowone** [comment]
No I am using version 1.18, do I need to use version 2? Is there anyway to access the book for v2?

**Comment by longfellowone** [comment]
No I am using version 1.18, do I need to use version 2? Is there anyway to access the book for v2?

**Comment by longfellowone** [comment]
No I am using version 1.18, do I need to use version 2? Is there anyway to access the book for v2?

**Comment by longfellowone** [comment]
No I am using version 1.18, do I need to use version 2? Is there anyway to access the book for v2?

**Comment by longfellowone** [comment]
No I am using version 1.18, do I need to use version 2? Is there anyway to access the book for v2?

**Comment by sunli829** [comment]
Examples repo and book has been replaced for Async-graphql v2.😃

**Comment by longfellowone** [comment]
Thanks! 👍
