### ISSUE TITLE
enum strings in query variables are not converted to proper enums

### ISSUE THREAD

**Issue by danjenson** [async-graphql/async-graphql#270]
If you use variables for queries and mutations, you have to use strings for enums. These don't appear to be parsed into the proper enums server-side:
![image](https://user-images.githubusercontent.com/4793438/93691879-756cd700-faa0-11ea-8d01-ed1051cecb0e.png)

Running the query without variables and _not_ quoting GOOGLE works just fine.

**Comment by sunli829** [comment]
Fixed in `v2.0.0-alpha.14`.

**Comment by kop** [comment]
Is it possible to somehow backport this to v1? I'm hitting same issue in v1.18.

**Comment by sunli829** [comment]
Released `v1.18.2`. @kop
