### ISSUE TITLE
Still possible to add extensions after schema is finalized?

### ISSUE THREAD

**Issue by mwilliammyers** [async-graphql/async-graphql#271]
I used to be able to add my custom logger extension after an HTTP request came in like this:
```rust
let graphql_post = warp::any()
    .and(auth)
    .and(warp::any().map(move || Arc::clone(&ctx_config)))
    .and(graphql_warp::graphql(schema.clone()))
    .and_then(
        |claims: Option<Claims>, ctx_config, (schema, mut builder): (_, QueryBuilder)| async move {
            let requester_id = claims.as_ref().map(|c| c.id().into());
            builder = builder.extension(move || Logger::new(requester_id.clone()));

            builder = builder.data(ContextData::new(claims, ctx_config));

            let response = builder.execute(&schema).await;
            Ok::<_, Infallible>(GQLResponse::from(response))
        },
    );
```

Is that not possible anymore? I have spent the past hour looking but can't seem to find anything...

It looks like my only option is to build the schema afresh for each request?

**Comment by Koxiaet** [comment]
Yes, we removed it because we didn't realize that it would be used. We will add it again now :)

**Comment by mwilliammyers** [comment]
THANK YOU, THANK YOU! 🙏

**Comment by sunli829** [comment]
If this problem is resolved, please close it. @mwilliammyers

**Comment by sunli829** [comment]
I removed the `Request::extension` function, because now the extension has a context object through which context `data` can be accessed. I think this is better.

**Comment by mwilliammyers** [comment]
Can I still create an extension with that though? I need to create my `Logger` extension.

**Comment by sunli829** [comment]
> Can I still create an extension with that though? I need to create my `Logger` extension.

Add the extension when creating the schema, add `requester_id` to `data` when executing the query, and then you can access it through the `ExtensionContext`. 🙂

**Comment by mwilliammyers** [comment]
Was this implemented in https://github.com/async-graphql/async-graphql/commit/af2e480b70d8e00dd0d64c01d648d7ddef7bd6d0 ?

**Comment by sunli829** [comment]
> Was this implemented in [af2e480](https://github.com/async-graphql/async-graphql/commit/af2e480b70d8e00dd0d64c01d648d7ddef7bd6d0) ?

Yes.😃

**Comment by mwilliammyers** [comment]
I am going to for things to settle down before I re-implement my custom Logger... I can't keep up with all the changes 😂  Once I can re-implement my custom Logger I can figure out if this will work for me or not.

**Comment by mwilliammyers** [comment]
Side-note: the primary reason I am implementing a custom logger is so I don't accidentally log passwords (I have a `login` mutation). I just log the query/mutation name instead of the entire document. The docs might want to mention that the logger is potentially insecure depending on your schema?

**Comment by mwilliammyers** [comment]
I am having quite a difficult time updating my custom Logger (that just logs the operation name, instead of the whole query/mutation) to accommodate the parser changes.

Do you have any pointers? This is what it used to be:
```rust
    fn parse_end(&mut self, document: &ExecutableDocument) {
        if !log::log_enabled!(log::Level::Info) {
            return;
        }

        for definition in document.definitions.iter() {
            if let ExecutableDefinition::Operation(operation) = &definition {
                let op = &operation.node;
                let selection_set = &op.selection_set.node;

                for selection in selection_set.items.iter() {
                    if let Selection::Field(field) = &selection.node {
                        let name = &field.node.name.node;
                        if name != "__schema" {
                            log::info!(
                                "{}, requester={}, id={}",
                                name, self.requester_id_display, self.id
                            );
                        }
                    }
                }
            }
        }
    }
```

**Comment by mwilliammyers** [comment]
Actually, this is much easier:

```rust

fn resolve_start(&mut self, context: &ExtensionContext<'_>, info: &ResolveInfo<'_>) {
    if info.path_node.parent.is_none() && &info.path_node.to_string() != "__schema" {
        log_with_ctx(log::Level::Info, context, info.path_node);
    }
}
```

But I am not sure if I am setting the extension context correctly, because when I call `context.data()` it is an `Err`:
```rust
let graphql_post = warp::any()
    .and(auth)
    .and(warp::any().map(move || Arc::clone(&ctx_config)))
    .and(graphql_warp::graphql(schema.clone()))
    .and_then(
        |claims: Option<Claims>,
            ctx_config,
            (schema, mut request): (Schema, graphql::Request)| async move {
            
            // this does not seem to set the correct context?
            request = request.data(ContextData::new(claims, ctx_config));

            let response = schema.execute(request).await;
            Ok::<_, Infallible>(Response::from(response))
        },
    )
    .with(warp::compression::gzip());
```

**Comment by sunli829** [comment]
> Actually, this is much easier (not sure if it is slower to incur the overhead of 1-2 branches for every field, but 🙃 ):

This is a good way.

> But I am not sure if I am setting the extension context correctly, because when I call context.data() it is an Err:

I am writing a test case to confirm whether this problem exists.

**Comment by sunli829** [comment]
Where did you call `context.data()`?

**Comment by sunli829** [comment]
Here is the test case, it works well.

https://github.com/async-graphql/async-graphql/blob/75107413111aa55a8f93f0b7c93f5f95de253606/tests/extension.rs#L7

**Comment by mwilliammyers** [comment]
I finally figured it out.

I had:
```rust
ctx.data::<&context::Data>()
```
but it worked once I removed the reference.

This happened because I mindlessly lifted it from elsewhere in my code where I have:
```rust
let ctx: &context::Data = context.data()?;
```

I wish that could be caught at compile time... I guess this is an example where type safety is important even if `context` is a single type 😉   https://github.com/async-graphql/async-graphql/issues/302#issuecomment-708907031
