### ISSUE TITLE
Allow invalid graphql keys in JSON scalars represented as objects

### ISSUE THREAD

**Issue by mwilliammyers** [async-graphql/async-graphql#273]
For various reasons I won't get into here, I have my own custom `Map` scalar that is a JSON object that serializes to an object for clients (`async_graphql::Value::Object`). I sometimes get data with invalid graphql `Names` in it (e.g. with `.` in them). I use `Name::new_unchecked` and everything is good for `release` builds, but it means I have to remember not to query that field during `debug` builds while testing. I am fine with keeping it, if we have a good reason, but I would prefer it to be an unchecked escape hatch even in debug builds. Thoughts?

**Comment by Koxiaet** [comment]
I think the best thing to do is to replace the output type of resolvers and scalars to an associated type of `OutputValueType` which implements `Serialize`.

**Comment by mwilliammyers** [comment]
Would that allow me to use a custom JSON scalar (`Map`) and put keys in it that violate the graphql spec (e.g. kebab-case fields?) The issue is that `async_graphql::Value::Object` requires valid keys, I believe?

**Comment by Koxiaet** [comment]
@mwilliammyers It's not in the normal format because it's not a GraphQL error, it's a transport error. But we are working on this in #295.

**Comment by mwilliammyers** [comment]
I saw in #295 that `Name::new_unchecked` is being completely removed. Is there anyway I will be able to support arbitrary JSON as a graphql scalar represented by a JSON object (ie plain ol Javascript object) *with* invalid graphql keys/names?

**Comment by sunli829** [comment]
@mwilliammyers This problem has been resolved in `2.0.0-alpha.28` version.
