### ISSUE TITLE
Examples of generic impl

### ISSUE THREAD

**Issue by chipsenkbeil** [async-graphql/async-graphql#274]
Hi there! I've recently tried `2.0.0-alpha.14` and have a variety of structs and enums that I've applied derives or implemented objects. However, I seem to be misunderstanding how to use `async-graphql` with a generic struct.

When trying to apply `async_graphql::Object` to a variety of specific implementations of a generic, it seems like only the first application sticks. In my case, I have a struct called `LC` that takes a `Region` and an arbitrary type `T`. Various other structs and enums can be provided to `LC`. My top level is `LC<Page>` which comprises two fields: components of `Vec<LC<BlockComponent>>` and comments of `Vec<LC<Comment>>`. It seems that the result of the generated code and schema does not capture those other types. The components return an array of `LC` which has a component of type `Page`. I was expecting something different like generating types like `LC_Page` and `LC_BlockComponent` to handle generics.

Is there an example of how to work with generics? Maybe I'm doing it wrong and I've included what I'm seeing and a snippet of the code I produced to handle generics.

![A35A930E-C3C7-49C8-96D3-A9C4CA5458AD](https://user-images.githubusercontent.com/2481802/93965305-6cda0200-fd27-11ea-8a06-e6d63c33655d.jpeg)

Here is a snippet of source code that highlights what I'm trying to do:

```rust
/// Represents a page of `BlockComponent` instances and `Comment` instances
pub struct Page {
    components: Vec<LC<BlockComponent>>,
    comments: Vec<LC<Comment>>,
}

/// Represents a "Located Component" that wraps some object `T` and a region being its location in a file
/// Can contain a `Page`, `BlockComponent`, `Comment`, or other object
pub struct LC<T> {
    pub component: T,
    pub region: Region,
}

macro_rules! impl_lc_graphql {
    ($type:ty) => {
        #[cfg(feature = "graphql")]
        #[async_graphql::Object]
        impl LC<$type> {
            async fn component(&self) -> &$type {
                &self.component
            }

            async fn region(&self) -> &Region {
                &self.region
            }
        }
    };
}

// Implement async_graphql::Object for various instances of LC<...>
impl_lc_graphql!(Page);
impl_lc_graphql!(BlockComponent);
impl_lc_graphql!(InlineComponent);
impl_lc_graphql!(Comment);
impl_lc_graphql!(Header);
```

For a query like this:

```graphql
// Query that returns an mocked LC<Page>
page {
  component {
    components {
      // Is supposed to be an array of LC<BlockComponent>, but is LC<Page>
    }
    comments {
      // Is supposed to be an array of LC<Comment>, but is LC<Page>
    }
  }
}
```

The output schema seems to only be comprised of LC, Page, and some other types:

![C4970187-2A71-46AF-B749-4202ED51A948](https://user-images.githubusercontent.com/2481802/93965301-6ba8d500-fd27-11ea-84c4-0d1d20093b87.jpeg)

**Comment by sunli829** [comment]
Generics are currently not supported, and I haven't thought of a good way to support this. 🙂

**Comment by chipsenkbeil** [comment]
Bummer. I guess I can create proxy structs that my generics can transform into, but I'll have to manually define each of my structs.

For reference, Juniper requires an explicit name on top of each manual implementation: https://graphql-rust.github.io/juniper/current/advanced/objects_and_generics.html

**Comment by sunli829** [comment]
> Bummer. I guess I can create proxy structs that my generics can transform into, but I'll have to manually define each of my structs that has a field involving that generic.

This is a good compromise! 👍

> For reference, Juniper requires an explicit name on top of each manual implementation: https://graphql-rust.github.io/juniper/current/advanced/objects_and_generics.html

This async-graphql should also be supported.

**Comment by chipsenkbeil** [comment]
> > For reference, Juniper requires an explicit name on top of each manual implementation: https://graphql-rust.github.io/juniper/current/advanced/objects_and_generics.html
> 
> This async-graphql should also be supported. 
> 

Are you saying that async-graphql already supports this? Or might eventually support this?

I'll rewrite my work tomorrow with the newtype wrappers since it'll give a clean break between my data and graphql impl, but curious on future support :)

**Comment by sunli829** [comment]
> > 
> 
> Are you saying that async-graphql already supports this? Or might eventually support this?
> 
> I'll rewrite my work tomorrow with the newtype wrappers since it'll give a clean break between my data and graphql impl, but curious on future support :)

Yes, it is supported now, for this I just added a test case.
