### ISSUE TITLE
Best practices for foreign enums

### ISSUE THREAD

**Issue by chipsenkbeil** [async-graphql/async-graphql#276]
I've got a couple of enums that come from other crates. While I see how I can go about wrapping foreign structs and enums that have variants with arguments in a newtype and defining those manually, the only way I see to handle a foreign enum is to explicitly write a new enum that has all of the exact values as the original and add the annotation to its impl.

### foreign crate

```rust
pub enum ForeignEnum {
    One,
    Two,
    Three,
}
```

### my crate

```rust
use foreign_crate::ForeignEnum;

#[derive(async_graphql::Enum)]
pub enum MyEnumWrapper {
    One,
    Two,
    Three,
}

impl From<ForeignEnum> for MyEnumWrapper {
    fn from(x: ForeignEnum) -> Self {
        match x {
            ForeignEnum::One => Self::One,
            ForeignEnum::Two => Self::Two,
            ForeignEnum::Three => Self::Three,
        }
    }
}
```

Not sure if, like with `async_graphql::Object`, I can provide a custom name to my wrapper enum like `#[async_graphql::enum(name = "ForeignEnum")`. I could always have the same enum name used and reference the foreign enum through an explicit path like this, I supposed:

```rust
#[derive(async_graphql::Enum)]
pub enum ForeignEnum {
    One,
    Two,
    Three,
}


impl From<foreign_crate::ForeignEnum> for ForeignEnum {
    fn from(x: foreign_crate::ForeignEnum) -> Self {
        match x {
            foreign_crate::ForeignEnum::One => Self::One,
            foreign_crate::ForeignEnum::Two => Self::Two,
            foreign_crate::ForeignEnum::Three => Self::Three,
        }
    }
}
```

### thoughts

Would be nice if we had a fancy expansion macro that could be a friendly wrapper for a foreign enum.

```rust
use async_graphql::wrap_foreign_enum;

wrap_foreign_enum!(MyWrapperName, foreign_crate::ForeignEnum);
```

**Comment by sunli829** [comment]
Let me think about it. 😁

**Comment by sunli829** [comment]
```rust
#[derive(async_graphql::Enum)]
#[graphql(remote = "ForeignEnum")]
pub enum MyEnumWrapper {
    One,
    Two,
    Three,
}
```

With the above definition, automatically generating the following conversion function is the only thing I can do.

```rust
impl From<ForeignEnum> for MyEnumWrapper {
    fn from(x: ForeignEnum) -> Self {
        match x {
            ForeignEnum::One => Self::One,
            ForeignEnum::Two => Self::Two,
            ForeignEnum::Three => Self::Three,
        }
    }
}
```

**Comment by sunli829** [comment]
> Not sure if, like with async_graphql::Object, I can provide a custom name to my wrapper enum like #[async_graphql::enum(name = "ForeignEnum")

This is of course possible. Derive macros are not allowed to take parameters, but you can write them like this.

```rust
#[derive(async_graphql::Enum)]
#[graphql(name = "ForeignEnum")]
pub enum MyEnumWrapper {
    One,
    Two,
    Three,
}
```

**Comment by chipsenkbeil** [comment]
Would certainly be handy in the future! I wrote all of mine by hand, which was quite painful. Maybe something like this as an optional extension that can be applied for those that want it?

**Comment by sunli829** [comment]
I added a `remote` attribute to the `Enum` macro, it can automatically implement the conversion functions of `impl From<Local> for Remote` and `impl From<Remote> for Local` enumeration types.
If you are free, please help me add a paragraph describing this feature in `define_enum.md`. 🙂

**Here is test code**

https://github.com/async-graphql/async-graphql/blob/397650bb0df210e22d16eb0d711d0255c3a93663/tests/enum.rs#L75

**Comment by chipsenkbeil** [comment]
> I added a `remote` attribute to the `Enum` macro, it can automatically implement the conversion functions of `impl From<Local> for Remote` and `impl From<Remote> for Local` enumeration types.
> If you are free, please help me add a paragraph describing this feature in `define_enum.md`. 🙂
> 
> **Here is test code**
> 
> https://github.com/async-graphql/async-graphql/blob/397650bb0df210e22d16eb0d711d0255c3a93663/tests/enum.rs#L75

Cool. Added a little info to the book per your description. See #285.
