### ISSUE TITLE
Example of context

### ISSUE THREAD

**Issue by AurelienFT** [async-graphql/async-graphql#277]
Hello,

I try to find example of the implementation of a simple context but I didn't find one in tests or examples. I want to implement a simple context to keep a connection open to my database and a simple example as this one could be useful.

Examples to build a context from integrations like warp could be cool too if we want to build a context with a userID which is in a JWT token in a header of the request. (Yes I want to do it and I didn't find how with async-graphql ahah)

Thanks for your help.

**Comment by sunli829** [comment]
Maybe this example will help you.

https://github.com/async-graphql/examples/tree/master/warp/token-from-header

**Comment by AurelienFT** [comment]
Thanks a lot. I'm really blind.
