### ISSUE TITLE
Can not make Tracing extension work

### ISSUE THREAD

**Issue by kop** [async-graphql/async-graphql#278]
Hello,
I'm trying to set up the Tracing extension to report execution traces to Jaeger.
Whatever I do I can not make it work - spans from extension never get to the dispatcher.
I don't think it's `tracing` problem, because spans from other places (e.g. `actix-web` middleware) are working.
Maybe I'm doing something wrong and there is some working example exists somewhere?

**Comment by sunli829** [comment]
Can manually call the `tracing::event` macro output the correct content?

**Comment by kop** [comment]
@sunli829 in other places of the program - yes. All traces/events are properly logged and delivered to jaeger.
But in `Tracing` extension, any calls to span/event seem to be completely ignored.

**Comment by sunli829** [comment]
Do you enable the Tracing extension? 😂

**Comment by kop** [comment]
Lol. Of course. Other extensions are working. I also have a custom Logging extension that uses `tracing::event`s and they are working just fine.

**Comment by kop** [comment]
So I assume that it's somehow related to the fact that `Tracing` is using `tracing::dispatcher::get_default()`. Maybe it's not available in that context for some reason...

**Comment by sunli829** [comment]
Could you help us solve this problem? 🙂

**Comment by kop** [comment]
I was trying to solve it for the last 4 hrs with no luck.
That's why I created issue instead of PR :) But I will work on it more.

**Comment by sunli829** [comment]
Could you provide the simplest example project?

**Comment by sunli829** [comment]
Maybe you need to call `tracing_core::dispatcher::set_global_default`?

**Comment by kop** [comment]
I have prepared an example project here: https://github.com/kop/async_graphql_tracing

> Maybe you need to call tracing_core::dispatcher::set_global_default?

It is done at https://github.com/kop/async_graphql_tracing/blob/master/src/main.rs#L75.

**Comment by kop** [comment]
Ok, I managed to get tracing working. I wrote a custom extension that is using `opentelemetry` directly instead of relying on `tracing` and this did the trick.

However, in the end, I realized that it's not what I want. The resulting image looks like this:

<img width="839" alt="jaeger_1" src="https://user-images.githubusercontent.com/645148/94188311-ddad2580-feb1-11ea-8197-97e2c32bf1f1.png">
<img width="836" alt="jaeger_2" src="https://user-images.githubusercontent.com/645148/94188317-df76e900-feb1-11ea-88f4-414aad53b70c.png">

After digging some more into library internals, I now understand that no matter what I'll do in extension, I can not get the desired picture when the spans of child requests belong to the corresponding resolver span. There is just no easy way to propagate it to resolvers.

I think this can be done by storing a map of the field path to corresponding span in `Context` and extracting it in every resolver... But that sounds like tons of stupid extra work.

So I was thinking, maybe it makes sense to just move the tracing from extension to the library itself and create spans for `execute_once` and `resolve_field`?

**Comment by sunli829** [comment]
@kop Good news! I solved the problem of tracing extension, and now it is very cool to use!

**Comment by kop** [comment]
@sunli829 just tried the master branch, still not works for me :(
Do you have some test project where you are testing this? Maybe I'm doing something wrong.

**Comment by sunli829** [comment]
> @sunli829 just tried the master branch, still not works for me :(
> Do you have some test project where you are testing this? Maybe I'm doing something wrong.

https://github.com/tokio-rs/tracing/blob/6f0122657009e47077c9a2207d592e1fc38c910f/examples/examples/opentelemetry.rs#L19

I just used this function to do initialization Tracing.

**Comment by sunli829** [comment]
> I have prepared an example project here: https://github.com/kop/async_graphql_tracing
> 
> > Maybe you need to call tracing_core::dispatcher::set_global_default?
> 
> It is done at https://github.com/kop/async_graphql_tracing/blob/master/src/main.rs#L75.

I tried the example you provided and it works fine.

![image](https://user-images.githubusercontent.com/20092316/94329234-fae60f00-ffeb-11ea-8122-be0aea9e82fc.png)

**Comment by sunli829** [comment]
If the problem has been resolved, please close it.

**Comment by kop** [comment]
@sunli829 please give me a couple of days. I will return to this issue once I'll have a chance. I want to understand why it was not working in my setup and maybe add corresponding instructions to the book.
