### ISSUE TITLE
Tips on diagnosing runtime errors with schema and execution

### ISSUE THREAD

**Issue by chipsenkbeil** [async-graphql/async-graphql#282]
I've successfully written out a first draft of my entire data model, wrapped in async_graphql. Yay!

Now I seem to be hitting errors at runtime when trying out graphiql or the graphql playground. With graphiql, I get errors about schema and execution. With graphql playground, I can execute a query and it works, but I cannot view and docs or schema with the interface constantly stuck at polling schema.

Looking for any guidance you might have on ways to troubleshoot these issues.

I don't have a simple example for this one, but you can see the project at [vimwiki-server](https://github.com/chipsenkbeil/vimwiki-server/tree/master/vimwiki_server) where `cargo run` and then accessing via http://localhost:8000/graphiql encounters these issues.

### Expected ... to be a GraphQL Object type. (on first loading graphiql)

I have a graphql union defined as the following:

```rust
#[derive(async_graphql::Union)]
pub enum Placeholder {
    Title(PlaceholderTitle),
    NoHtml(PlaceholderNoHtml),
    Template(PlaceholderTemplate),
    Date(PlaceholderDate),
    Other(PlaceholderOther),
}
```

where each inner variant contains a single struct with a derive of `async_graphql::SimpleObject`.

![Screen Shot 2020-09-26 at 11 59 10 PM](https://user-images.githubusercontent.com/2481802/94356455-77acd380-0054-11eb-9451-6c73d247d59b.png)

### response is not defined (on execution in graphiql)

For a valid request, I get an error about the response not being defined. The network response indicates a 500 server error with the message:

> Unhandled rejection: Invalid request: data did not match any variant of untagged enum BatchRequest

![Screen Shot 2020-09-26 at 11 58 53 PM](https://user-images.githubusercontent.com/2481802/94356475-b5a9f780-0054-11eb-9b58-53f39cd70c25.png)

### stuck polling schema (for graphql playground)

Seems to be constantly polling the schema and cannot load the docs or schema, even though the network response seems to reflect receiving something matching parts of my overall schema and documentation.

![Screen Shot 2020-09-27 at 12 13 31 AM](https://user-images.githubusercontent.com/2481802/94356633-5d73f500-0056-11eb-8283-6d9458702911.png)

**Comment by sunli829** [comment]
I am looking at this problem.

**Comment by chipsenkbeil** [comment]
> I am looking at this problem.

Added more clarity where possible. Graphiql fails on schema, docs, and execution. Graphql playground fails on schema and docs, but execution works!

I'm using `2.0.0-alpha19` at the moment.

**Comment by sunli829** [comment]
> Note that members of a union type need to be concrete object types; you can't create a union type out of interfaces or other unions.

This definition does not conform to the GraphQL specification because `Placeholder` is also a union.

```rust
BlockComponent::Placeholder(Placeholder)
```

**Comment by sunli829** [comment]
I will impose restrictions on `Union` procedural macro.

**Comment by chipsenkbeil** [comment]
> > Note that members of a union type need to be concrete object types; you can't create a union type out of interfaces or other unions.
> 
> This definition does not conform to the GraphQL specification because `Placeholder` is also a union.
> 
> ```rust
> BlockComponent::Placeholder(Placeholder)
> ```

Ah, missed that disclaimer. Interesting that it compiles despite it not conforming. I've got several similar situations, so I guess the best fix is to make an object in between?

**Comment by sunli829** [comment]
> > > Note that members of a union type need to be concrete object types; you can't create a union type out of interfaces or other unions.
> > 
> > 
> > This definition does not conform to the GraphQL specification because `Placeholder` is also a union.
> > ```rust
> > BlockComponent::Placeholder(Placeholder)
> > ```
> 
> Ah, missed that disclaimer. Interesting that it compiles despite it not conforming. I've got several similar situations, so I guess the best fix is to make an object in between?

Yes. 😁

**Comment by chipsenkbeil** [comment]
@sunli829 going to close this. Is there anything I can do to thank you for the help? You've been fast, friendly, and helpful on multiple occasions. Would love to show thanks in some way. Donation?

**Comment by Koxiaet** [comment]
There's additionally a bug where `Variables` cannot deserialize from `null` which was causing the 500 error, that'll also have to be fixed.

**Comment by sunli829** [comment]
> @sunli829 going to close this. Is there anything I can do to thank you for the help? You've been fast, friendly, and helpful on multiple occasions. Would love to show thanks in some way. Donation?

Thank you, but I am not doing this for money, I am very happy to be able to help you. 😁

**Comment by sunli829** [comment]
> There's additionally a bug where `Variables` cannot deserialize from `null` which was causing the 500 error, that'll also have to be fixed.

I will solve it now. 😁

**Comment by Koxiaet** [comment]
@sunli829 Yes - Clients do send `null` in the `variables` option and I tested it and currently `#[serde(default)]` does not account for `null`.

**Comment by sunli829** [comment]
> @sunli829 Yes - Clients do send `null` in the `variables` option and I tested it and currently `#[serde(default)]` does not account for `null`.

This problem has been resolved. 🙂
