### ISSUE TITLE
Apollo Federation doesn't work

### ISSUE THREAD

**Issue by rkudryashov** [async-graphql/async-graphql#283]
In the latest alpha versions, I encountered the following error at Apollo Server startup:

```
[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node gateway.js`
http://localhost:8001
http://localhost:8002
http://localhost:8003
� Server ready at http://0.0.0.0:4000/
Error checking for changes to service definitions: Couldn't load service definitions for "auth-service" at http://localhost:8003: Syntax Error: Expected Name, found "}".
This data graph is missing a valid configuration. Couldn't load service definitions for "auth-service" at http://localhost:8003: Syntax Error: Expected Name, found "}".
```

As you can see, my project contains 3 services, and `auth-service` can't be loaded. I didn't manage to reproduce the error in my repro-project, but the schema looks like:

```graphql
{
  _service {
    sdl
  }
}
```

```
{
  "data": {
    "_service": {
      "sdl": "type Query {\n}\ntype Mutation {\n\tcreateUser(user: UserInput!): ID!\n\tsignIn(signInData: SignInInput!): String!\n}\ninput UserInput {\nusername: String!\npassword: String!\nfirstName: String!\nlastName: String!\nrole: String!\n}\ninput SignInInput {\nusername: String!\npassword: String!\n}\n"
    }
  }
}
```

I don't know what GraphQL types led to this error. Only can notice that type system contains empty Query and doesn't contain any federated type.

The schema is created by the following code:

```rust
fn create_schema(pool: PgPool) -> Schema<Query, Mutation, EmptySubscription> {
    Schema::build(Query, Mutation, EmptySubscription)
        .enable_federation()
        .data(pool)
        .finish()
}

```

**Comment by sunli829** [comment]
Thank you for helping us test the alpha version, I have fixed this problem. 🙂

**Comment by sunli829** [comment]
If the problem has been resolved, please close it.

**Comment by rkudryashov** [comment]
Can't test the project because of compilation errors:

```
error: cannot find attribute `entity` in this scope
error: cannot find attribute `field` in this scope
```

**Comment by sunli829** [comment]
> Can't test the project because of compilation errors:
> 
> ```
> error: cannot find attribute `entity` in this scope
> error: cannot find attribute `field` in this scope
> ```

There is a major modification.

https://github.com/async-graphql/async-graphql/issues/288

**Comment by rkudryashov** [comment]
next error

```
error: Unknown field: `desc`
   --> some-service\src\graphql.rs:109:30
    |
109 |     #[graphql(name = "type", desc = "some desc")]
    |                              ^^^^

```

**Comment by sunli829** [comment]
```rust
/// some desc
#[graphql(name = "type")]
async fn a() { ... }
```

**Comment by rkudryashov** [comment]
Thank you, now the issue has been resolved

**Comment by rkudryashov** [comment]
But such a comment is not shown in GraphQL IDE. How to show it?

**Comment by sunli829** [comment]
> But such a comment is not shown in GraphQL IDE. How to show it?

If not, it is certainly a bug.

**Comment by rkudryashov** [comment]
I just change this

```
    #[field(name = "type", desc = "some desc")]
```

to this

```
    /// some desc
    #[graphql(name = "type")]
```

**Comment by rkudryashov** [comment]
Previously `desc` value was shown as GraphQL comment

**Comment by rkudryashov** [comment]
My mistake, comments are not shown only in Apollo Server playground

Standalone app shows them
