### ISSUE TITLE
Feature to flatten nested GraphQL unions

### ISSUE THREAD

**Issue by chipsenkbeil** [async-graphql/async-graphql#286]
Per discussion in #282 where GraphQL doesn't allow nested unions, I wonder if it is possible and would make sense to support a **flatten** attribute on a variant of a union that could add all of the sub-union's variants to the top-level union.

```rust
#[derive(async_graphql::Union)]
pub enum TopLevelUnion {
    A(A),
    B(B),

    #[graphql(flatten)]
    C(C),
}

#[derive(async_graphql::SimpleObject)]
pub struct A {
    // ...
}

#[derive(async_graphql::SimpleObject)]
pub struct B {
    // ...
}

#[derive(async_graphql::Union)]
pub enum C {
    D(D),
    E(E),
    F(F),
}

#[derive(async_graphql::SimpleObject)]
pub struct D {
    // ...
}

#[derive(async_graphql::SimpleObject)]
pub struct E {
    // ...
}

#[derive(async_graphql::SimpleObject)]
pub struct F {
    // ...
}
```

would yield the equivalent of

```rust
#[derive(async_graphql::Union)]
pub enum TopLevelUnion {
    A(A),
    B(B),
    D(D),
    E(E),
    F(F),
}

#[derive(async_graphql::SimpleObject)]
pub struct A {
    // ...
}

#[derive(async_graphql::SimpleObject)]
pub struct B {
    // ...
}

#[derive(async_graphql::SimpleObject)]
pub struct D {
    // ...
}

#[derive(async_graphql::SimpleObject)]
pub struct E {
    // ...
}

#[derive(async_graphql::SimpleObject)]
pub struct F {
    // ...
}
```

**Comment by sunli829** [comment]
I added this feature, please help me improve the book. 😂 @chipsenkbeil

**Comment by chipsenkbeil** [comment]
@sunli829 any chance of another alpha release so I can try out the new feature?

**Comment by sunli829** [comment]
`InputObject` also supports the `flatten` attribute. Could you add it to the book when you are free? 😁

#255

**Comment by sunli829** [comment]
> @sunli829 any chance of another alpha release so I can try out the new feature?

Released `2.0.0-alpha.20`. 😁

**Comment by sunli829** [comment]
If the problem has been resolved, please close it.

**Comment by chipsenkbeil** [comment]
It works! I haven't had time to write the updates to the documentation, though. Did you want me to go ahead and close this one?

**Comment by sunli829** [comment]
> It works! I haven't had time to write the updates to the documentation, though. Did you want me to go ahead and close this one?

It's okay, wait until you have time to add documents before closing it.
