### ISSUE TITLE
Deserialization failure when request variables are not present.

### ISSUE THREAD

**Issue by stevenxie** [async-graphql/async-graphql#287]
Hello! I've been using `async-graphql` with `warp`, and I noticed after testing out my `graphiql` endpoint that `serde` fails to  deserialize a `BatchRequest` when a query with null or missing `variables` are made (likely because `Request.variables` are of type `Variables`, rather than `Option<Variables>`).

I'm open to work on a PR to change the type of `Request.variables` an `Option<Variables>`, but I'm wondering if anybody has any ideas on whether this is the best approach (for example, I believe I could also manually implement `Deserialize` for `Variables` in order to handle the null case).

I'm a bit of a newbie to Rust, so advice is appreciated!

**Comment by Koxiaet** [comment]
@stevenxie Are you using version `alpha.20`? It was fixed in [this commit](https://github.com/async-graphql/async-graphql/commit/bf42c4e9156a8c67ac56815b5b1b3748ef897de9).

**Comment by stevenxie** [comment]
Oh, didn't notice that `alpha.20` was out! Thanks :)
