### ISSUE TITLE
Add "flatten" attribute to field

### ISSUE THREAD

**Issue by nicolaiunrein** [async-graphql/async-graphql#29]
As discussed in #28, it would be nice to have a flatten attribute on fields. Note: This does not seem to be possible as of now! This issue is just a reminder to implement it when it becomes possible. Here is a very basic example of what we want to accomplish: 

```rust
#[SimpleObject]
struct Info {
    #[field]
    base_field: String
}


#[SimpleObject]
struct MyInfo {
    #[field(flatten)] // <<<-------------------------
   info: Info,

    #[field]  
    additional_field: String,
}

pub struct QueryRoot;

impl QueryRoot {
    async fn info(&self) -> MyInfo {
        unimplemented!()
    } 
}
```

Instead of getting this:
```graphql
{
    info {
        info {
            baseField
        }
        additionalField
    }
}
```

You would be getting this:
```graphql
{
    info {
         baseField,
         additionalField
    }
```

**Comment by sunli829** [comment]
This is pretty easy to implement, but I can't make an object that contains the flatten fields support `Interface`.😭

**Comment by nicolaiunrein** [comment]
I think having flatten would kind of sort #35 in that you can combine a SimpleObject with an Object. Does that mean you cannot support the flatten attribute on interfaces or objects that use flatten cannot implement an interface?

**Comment by sunli829** [comment]
Yes, it's the same problem. I can't pass data between macros, which makes it impossible. But all of these problems can be solved with generic specialization, so let's wait for this feature to stabilize. 😂

**Comment by nicolaiunrein** [comment]
So I poked around a little in the code base. I tried to manually (without macros) implement an "Object" by implementing ObjectType, OutputValueType and Type on a struct. I can't quite get `create_type_info` to work correctly but I thought it should be possible to create a `trait Merge` with required methods `async fn base(&self) -> impl ObjectType` and `async fn extend(&self) -> impl ObjectType` and then implement `impl<T> ObjectType for T where T: Merge { ... }` so that it registers all fields on the object returned from a call to `self.base()` and `self.extend()`.  Or maybe even a method like `async fn objects(&self) -> Vec<Box<dyn ObjectType>>`. Could that work or have I hit a dead end?

**Comment by sunli829** [comment]
The main reason is that `Interface` cannot be supported. The field of `Interface` is  function forwarding, which can achieve the purpose of type safety.

**Comment by sunli829** [comment]
If I don't need to support the `Interface`, I've actually implemented it.😁

**Comment by sunli829** [comment]
Unless you abandon the type-safety of the interface, which is not what this library is for.

**Comment by sunli829** [comment]
The `Edge` type actually does that, it moves the `extra_type` to a higher level, but the field inside the `extra_type` doesn't support interface.

`fn Edge::node()` and `fn Edge::cursor()`  are actually intended to support the interface.

**Comment by sunli829** [comment]
Branch `dynamic-interface` supports the `flatten` property, we may need sufficient validation to merge to the `master`, because this will break the type safety of the interface.

Here are all the tests:

https://github.com/async-graphql/async-graphql/blob/8714185ae139dc42d57b89c3174112188c49c880/tests/object.rs#L4

https://github.com/async-graphql/async-graphql/blob/8714185ae139dc42d57b89c3174112188c49c880/tests/object.rs#L41

https://github.com/async-graphql/async-graphql/blob/8714185ae139dc42d57b89c3174112188c49c880/tests/object.rs#L73

**Comment by nicolaiunrein** [comment]
That is very nice! 👍
