### ISSUE TITLE
Streaming uploads?

### ISSUE THREAD

**Issue by Bajix** [async-graphql/async-graphql#290]
How does one accomplish streaming uploads? My use case is to directly upload an incoming file to Cloudinary using a POST request such that this can be uploading to cloudinary as the file is uploading to the API.

**Comment by sunli829** [comment]
https://github.com/async-graphql/async-graphql/issues/255#issuecomment-686790291

**Comment by Bajix** [comment]
Touché. Coming soon!

**Comment by sunli829** [comment]
Use `Upload` type to support file upload, the following is an example.

https://github.com/async-graphql/examples/tree/master/models/files

**Comment by phungtranminh** [comment]
Hi, I have been looking around how to do streaming upload but haven't seen an easy way.

The example does not mention about streaming upload but rather regular upload of the file.

**Comment by Bajix** [comment]
Oof I forgot about the PR.

Anyway, you need to convert to an AsyncRead and then a FramedRead and so this is going to depend on which async runtime you're using. I use Actix and so until 4.0 is released I'm stuck on Tokio 0.2.x but someone on Warp or Tide could maybe be using Tokio 1.x which would make the below slightly different. 

```
  use tokio_util::{codec, compat::FuturesAsyncReadCompatExt};
  use bytes::Bytes;
  let upload = file.into_async_read().compat();
  let stream = codec::FramedRead::new(upload, codec::BytesCodec::new());
```
...
```
bytes = "0.5.6"
tokio = "0.2.25"
tokio-util = {version = "0.3.1", features = ["codec", "compat"]}
```

**Comment by phungtranminh** [comment]
Thanks a lot @Bajix 

I read somewhere people doing something like this

```
tokio::fs::File::from(upload.content);
```

I am not sure what the differences between the 2 approaches?

Another issue I have is that I don't seem to figure out how to link that uploaded stream to send to 3rd party service like s3 or cloudinary like your case.

**Comment by phungtranminh** [comment]
I managed to do this as `tokio::fs::File` is just `AsyncRead` and I can convert to `FramedRead` as suggested.

However to write data to S3, somehow I need `content-length`.

Is there a way to get `content-length` of the file reliably from `async-graphql`?

**Comment by sunli829** [comment]
> I managed to do this as `tokio::fs::File` is just `AsyncRead` and I can convert to `FramedRead` as suggested.
> 
> However to write data to S3, somehow I need `content-length`.
> 
> Is there a way to get `content-length` of the file reliably from `async-graphql`?

https://docs.rs/async-graphql/2.5.13/async_graphql/types/struct.UploadValue.html#method.size

**Comment by phungtranminh** [comment]
Thanks it works!

**Comment by phungtranminh** [comment]
Just out of curiosity, this method shouldn't break the streaming/async read intention of the API right?

**Comment by Bajix** [comment]
The method I described gives you a stream so you can upload to S3 or to some external service in a streaming fashion. Tokio::fs::File shouldn’t be used if you want to bypass the file system.

**Comment by wileybaba** [comment]
Can anyone provide a working example of uploading to s3 using async-graphql ? I don't need a streaming upload, just a simple one.  I'm running into the issue of not having `Copy` implemented on the `UploadValue` struct so its proving difficult to extract a Vec<u8> from upload.content to pass to s3.

Here is my upload function: 
```rust 
pub struct File {
    id: ID,
    pub filename: String,
    pub content: Vec<u8>,
    pub mimetype: Option<String>,
}


pub async fn upload_to_s3(file: File) -> Result<u16, Error> {
    dotenv().ok();
    let accesss_key = std::env::var("AWS_ACCESS_KEY")?;
    let secret_key = std::env::var("AWS_SECRET_KEY")?;

    let bucket_name = "some-s3-bucket";
    let region = "us-east-2".parse()?;
    let credentials = Credentials::new(
        Some(&accesss_key.to_owned()),
        Some(&secret_key.to_owned()),
        None,
        None,
        None,
    )?;
    let bucket = Bucket::new(bucket_name, region, credentials)?;
    let (_, code) = bucket
        .put_object_with_content_type(
            file.filename,
            &file.content,
            &file.mimetype.unwrap_or("".to_string()),
        )
        .await?;
    println!("{}", code);
    Ok(code)
}
```

and my upload mutation
```rust
async fn upload_thumbnail(
        &self,
        ctx: &Context<'_>,
        file: &Upload,
    ) -> Result<u16, Error> {
        let upload = file.clone().value(ctx).unwrap();
        let mut content = Vec::new();
        upload.into_read().read_to_end(&mut content).unwrap(); 
        let file_info = File {
            id: ID::from(uuid::Uuid::new_v4()),
            filename: upload.filename.clone(),
            content, 
            mimetype: upload.content_type,
        };
        Ok(upload_to_s3(file_info).await?)
    }
```

running into a "use of moved value: `upload.content_type`" compiler error.  What is the best way to get the upload content as a Vec<u8> to pass to s3? 


I'm a rust noob so please forgive me if I'm missing something simple, still wrapping my head around the ownership model.
