### ISSUE TITLE
Remove the dependency on `serde_json`.

### ISSUE THREAD

**Issue by sunli829** [async-graphql/async-graphql#295]
@Koxiaet I am doing this. 😁

**Comment by sunli829** [comment]
I am considering whether it is worth removing the dependency on `serde_json`, because the only difference between `serde_json::Value` and `async_graphql::Value` is the addition of a `Name` type. Custom transfer coding, this is an optimization point, because Name is usually fixed.

**Comment by Koxiaet** [comment]
I opened [this issue](https://github.com/graphql/graphql-spec/issues/785), and that presents a problem for us - what should the type of `Variables` be? It can't be `serde_json::Value` _or_ `async_graphql::Value`, it would ideally be some transport-agnostic type that can represent any value.

**Comment by Koxiaet** [comment]
I am currently replacing `InputValueType` with a supertrait of `Deserialize` and `ScalarType` with a supertrait of `Serialize` and `Deserialize`. This has other benefits too like removing the potentially confusing `InputValueError` and supporting automatic implementations.

**Comment by Koxiaet** [comment]
I encountered a problem with this approach: How to differentiate null and undefined. There are 3 options:
1. Treat arguments as `Option<Value>`. However this would fail to deserialize `null` to `Option<i32>` since the value is present but `null` isn't an `i32` so is not a good idea.
1. Swap null and undefined and use an `Option<Value>`. This way `Option<i32>` matches `null` and `5` but not undefined. For `Option<Option<i32>>`, `5` becomes `Some(Some(5))`, `null` becomes `None` and undefined becomes `Some(None)`; for `Option<Value>` `5` becomes `Some(Value::I32(5))`, `null` becomes `None` and undefined becomes `Some(Value::Null)`. This isn't very intuitive in some cases like `Option<Value>` but supporting nested options instead of a custom type is an advantage. It's also simpler to implement.
1. Add a method to `InputValueType` `fn handle_undefined() -> bool { false }`. If the implementor overrides this to `true` then the deserializer will deserialize from an `Option<Value>` (where `None` is undefined), otherwise it will deserialize from an `Option<Value>`. `MaybeUndefined` will be the only type supplied by the library to override this. This is fairly complex but it is the least surprising approach.

What do you think is best?

**Comment by Koxiaet** [comment]
Oh dear, I just realized another major problem - uploads. Since variables are no longer `async_graphql::Value`s, they can no longer contain files. We'll have to completely rethink our approach to supporting file uploads. This isn't something introduced by this change by the way, before the implementation wasn't spec-compliant since it only supported `async_graphql::Value`s in variables.

After some thinking, I think the best way to support this is to have `Request`s contain an additional filemap (`HashMap<String, UploadFile>`) which can be accessed from `Context` (`UploadFile` can contain the filename, content type and `async_fs::File`). The `Upload` scalar will become a wrapper around a string. Then in resolvers, servers will find the corresponding file in the file map and use it. It will be the job of the `http::multipart` module to convert the `null` variable values to the multipart fields.

This approach has the disadvantage of being "hackable" by the client - they could send a string identical to the multipart field name and we'd have no way of knowing it's not a real file as we can't tell the difference between a string set by the `http::multipart` module and a string sent by the client. But this is not harmful to the server in any way, so I think it's an acceptible quirk to have. We could prefix files with `__async_graphql_file` or something if we really didn't want this.

What do you think of this?

**Comment by AurelienFT** [comment]
Hello @Koxiaet 

About your first comment, even if I did understand all very well, I find out some resources about this that could help you : 
- A SO post about (I think) your second option : https://stackoverflow.com/questions/44331037/how-can-i-distinguish-between-a-deserialized-field-that-is-missing-and-one-that
- A issue on github with an answer of the maintenainer of serde which show an example of your option 2 : https://github.com/serde-rs/serde/issues/984
- A attribute on Deserialize to use default on null : https://docs.rs/serde_with/1.5.0/serde_with/rust/default_on_null/index.html. If I understand well how it works :[ the default of an option](https://doc.rust-lang.org/beta/src/core/option.rs.html#1248-1261) is `None` so null will by deserialize to None and fix your problems. But seems too easy to be that. :joy:

**Comment by Koxiaet** [comment]
I've [committed to the `scalar-serde` branch now](https://github.com/async-graphql/async-graphql/commit/32bb69f1b6f8d466b51b7c871ee779c9d5decb98). It doesn't compile yet (obviously) but it's a start. I'll be back in 10 hours so if you want to continue work in the meantime you can :).

**Comment by AurelienFT** [comment]
I don't know enough about the code base of the project that's why I currently working on #293 . But I tried to help you with resources that can be useful. I think the third that I linked could be very cool (if I understood well your problem)

**Comment by sunli829** [comment]
Do we need to deserialize `Json` to `Variables` according to the type definition in the schema?

`Value::Name` cannot be deserialized from `Json`, causing the enum of `async-graphql` to actually allow two types of values, `string` and `Name`.

**Comment by Koxiaet** [comment]
@sunli829 What do you mean? `Variables` will be a map of `Name`s to `serde_value::Value`s, and those `Value`s can't contain `Name`s - they just contain strings. With this new implementation `async_graphql::Value` really won't be used at all any more - it will just be an opaque `Deserializer`.

**Comment by sunli829** [comment]
`Variables::parse_json` cannot recognize `enum` type values.

So there will be the following code, but this does not actually comply with the GraphQL specification.

```rust
pub fn parse_enum<T: EnumType + InputValueType>(value: Value) -> InputValueResult<T> {
    let value = match &value {
        Value::Enum(s) => s,
        Value::String(s) => s.as_str(),
        _ => return Err(InputValueError::expected_type(value)),
    };
}
```

**Comment by sunli829** [comment]
I have studied GraphQL implementations in other languages, and they actually have a function like `ScalarType::parse_json(value:serde_json::Value)` that is specifically used to deserialize scalars.
Then `Variables::parse_from_json` does not directly parse the `Json` and convert it to the internal `Value`, but calls the `parse_json` function of the corresponding scalar type.

**Comment by Koxiaet** [comment]
@sunli829 So variables would become a `BTreeMap<Name, Box<dyn Any>>`, and we'd downcast it to the correct type when it's needed? That could work, it would avoid deserializing the variables multiple times. It would require input values to implement `Deserializer` though, as `Value`s can contain variables.

I actually removed EnumType and replaced it with a generated implementation of Deserialize for enums (which deserializes from strings, the exact same way Serde's derive works on an enum without data).

**Comment by sunli829** [comment]
Maybe we need to be more considerate.😃

**Comment by sunli829** [comment]
But this means that we cannot completely remove the dependency on `serde_json`, at least `Variables::from_json` also x...

**Comment by Koxiaet** [comment]
@sunli829 `Variables::from_json` would be removed, we'd just deserialize straight into it.

**Comment by sunli829** [comment]
> I encountered a problem with this approach: How to differentiate null and undefined. There are 3 options:
> 
> 1. Treat arguments as `Option<Value>`. However this would fail to deserialize `null` to `Option<i32>` since the value is present but `null` isn't an `i32` so is not a good idea.
> 2. Swap null and undefined and use an `Option<Value>`. This way `Option<i32>` matches `null` and `5` but not undefined (since `null` isn't an `i32`). For `Option<Option<i32>>`, `5` becomes `Some(Some(5))`, `null` becomes `None` and undefined becomes `Some(None)`; for `Option<Value>` `5` becomes `Some(Value::I32(5))`, `null` becomes `None` and undefined becomes `Some(Value::Null)`. This isn't very intuitive in some cases like `Option<Value>` but supporting nested options instead of a custom type is an advantage. It's also simpler to implement.
> 3. Add a method to `InputValueType` `fn handle_undefined() -> bool { false }`. If the implementor overrides this to `true` then the deserializer will deserialize from an `Option<Value>` (where `None` is undefined), otherwise it will deserialize from a `Value`, flattening undefined to `Value::Null`. `MaybeUndefined` will be the only type supplied by the library to override this. This is fairly complex but it is the least surprising approach.
> 
> What do you think is best?

The third option looks good, don't you think?😃

**Comment by sunli829** [comment]
> Oh dear, I just realized another major problem - uploads. Since variables are no longer `async_graphql::Value`s, they can no longer contain files. We'll have to completely rethink our approach to supporting file uploads. This isn't something introduced by this change by the way, before the implementation wasn't spec-compliant since it only supported `async_graphql::Value`s in variables.
> 
> After some thinking, I think the best way to support this is to have `Request`s contain an additional filemap (`HashMap<String, UploadFile>`) which can be accessed from `Context` (`UploadFile` can contain the filename, content type and `async_fs::File`). The `Upload` scalar will become a wrapper around a string. Then in resolvers, servers will find the corresponding file in the file map and use it. It will be the job of the `http::multipart` module to convert the `null` variable values to the multipart fields.
> 
> This approach has the disadvantage of being "hackable" by the client - they could send a string identical to the multipart field name and we'd have no way of knowing it's not a real file as we can't tell the difference between a string set by the `http::multipart` module and a string sent by the client. But this is not harmful to the server in any way, so I think it's an acceptible quirk to have. We could prefix files with `__async_graphql_file` or something if we really didn't want this.
> 
> What do you think of this?

I actually did this a long time ago, and I thought it was ok.😃

**Comment by sunli829** [comment]
Sorry, I'm in a small city where access to Github is so slow, it takes me 5 minutes to open a page, and I only have my phone. So my reply was rather slow, but fortunately I will be able to go home tomorrow. 😂

发自我的iPhone

**Comment by sunli829** [comment]
Now all types that can be supported by `serde` automatically become scalars, right? @Koxiaet

**Comment by mwilliammyers** [comment]
Will `MaybeUndefined` no longer derive `Serialize`?

**Comment by sunli829** [comment]
The changes in the `serde-scalar` branch are too large, just to completely remove the dependency of `serde_json`, I feel that this is unnecessary. 
I hope to stabilize version 2.0 soon.😂 @Koxiaet

**Comment by Koxiaet** [comment]
Ok, pehaps we could just replace `serde_json::Value` and `async_graphql::Value` with `serde_value::Value` across the library instead. Serde traits are the ideal solution for performance and ease of use, but I agree that the churn is possibly too much.

**Comment by sunli829** [comment]
> Ok, pehaps we could just replace `serde_json::Value` and `async_graphql::Value` with `serde_value::Value` across the library instead. Serde traits are the ideal solution for performance and ease of use, but I agree that the churn is possibly too much.

There is not much difference between `serde_json::Value` and `serde_value::Value`, are they? I even think `serde_json::Value` is better to use. 😁

**Comment by sunli829** [comment]
I first removed the `Name::new_uncheck` function to support parsing variables:

```json
{
     "a": {
      "a-b": 123
     }
}
```

**Comment by Koxiaet** [comment]
@sunli829 Well `serde_value::Value` supports things not supported by JSON like non-string keys and raw byte sequences.

But after some thought switching to `serde_value::Value` will cause about as much breakage as switching to serde traits. If you're concerned about whether we can get it implemented soon, I will have much more time to work on it this week than last.

Also, don't use `Arc<String>` - that's two layers of pointers! `Arc<str>` is also usable and faster.

**Comment by sunli829** [comment]
> @sunli829 Well `serde_value::Value` supports things not supported by JSON like non-string keys and raw byte sequences.
> 
> But after some thought switching to `serde_value::Value` will cause about as much breakage as switching to serde traits. If you're concerned about whether we can get it implemented soon, I will have much more time to work on it this week than last.
> 
> Also, don't use `Arc<String>` - that's two layers of pointers! `Arc<str>` is also usable and faster.

I tested it, and now there is a 30% performance improvement.

> Also, don't use Arc<String> - that's two layers of pointers! Arc<str> is also usable and faster.

I am going to change this now.

**Comment by sunli829** [comment]
`serde_value` does not support arbitrary precision `Number`, I think this is a big problem.

**Comment by Koxiaet** [comment]
@sunli829 `serde-value` doesn't support it because `serde` doesn't support it - there's no way for `serde_json` to represent something `serde-value` doesn't, as `serde-value` is strictly a superset of `serde_json`.

**Comment by sunli829** [comment]
- [ ] Change Name(String) to Name(Arc<str>). @Koxiaet Could you help me with this, I really don't know how to create 
- [ ] Implement Serializer/Deserializer for `ConstValue`.

**Comment by sunli829** [comment]
> @sunli829 `serde-value` doesn't support it because `serde` doesn't support it - there's no way for `serde_json` to represent something `serde-value` doesn't, as `serde-value` is strictly a superset of `serde_json`.

We don't need to use `serde_value`, just use `ConstValue`, which has better performance, now the field name does not need to be deep cloned. 😁

**Comment by Koxiaet** [comment]
@sunli829 `ConstValue` has the major problem of being way too restrictive though. We should support non-`Name` object keys.

**Comment by sunli829** [comment]
> `ConstValue` has the major problem of being way too restrictive though. We should support non-`Name` object keys.

In fact, I removed the Name constraint. 😂

**Comment by Koxiaet** [comment]
@sunli829 But there's still going to be the issue of non-string keys. IMO ConstValue should just be a parsing construct and nothing else - using it for anything else is overloading it's purpose too much. Everything should go through Serde or serde value.

**Comment by sunli829** [comment]
> @sunli829 But there's still going to be the issue of non-string keys. IMO ConstValue should just be a parsing construct and nothing else - using it for anything else is overloading it's purpose too much. Everything should go through Serde or serde value.

Do you mean that GraphQL actually supports non-string keys?

**Comment by Koxiaet** [comment]
@sunli829 Yes - [see the issue I linked earlier](https://github.com/graphql/graphql-spec/issues/785). GraphQL is also protocol-agnostic so if it supports non-`Name` values it supports non-JSON values.

**Comment by hapcode** [comment]
I'm trying to migrate my project from async-graphql `1.17.14` to `2.0.0-alpha.24`. I've the scalar which doesn't work in a new version:

```rust
#[derive(Clone, Serialize, Deserialize)]
#[serde(transparent)]
pub struct LocalizedString {
    translations: IndexMap<Language, String>,
}

#[Scalar(name = "LocalizedString")]
impl ScalarType for LocalizedString {
    fn parse(value: Value) -> InputValueResult<Self> {
        let json = serde_json::Value::from(value);
        Ok(serde_json::from_value::<Self>(json)?)
    }

    fn to_value(&self) -> Value {
        serde_json::to_value(&self).unwrap().into()
    }
}
```
```rust
#[derive(Enum, Copy, Clone, Eq, PartialEq, Hash, Debug, Deserialize, Serialize)]
#[serde(rename_all = "UPPERCASE")]
pub enum Language {
    En,
    Ru,
    De,
    Fr,
}
```
What is the correct way to rewrite the code? Do I've to do the conversion manually like [here](https://github.com/async-graphql/async-graphql/blob/78341f23927893cfcb4ead88727c86fc17a289df/src/types/external/json_object/btreemap.rs#L17)?

**Comment by sunli829** [comment]
> I'm trying to migrate my project from async-graphql `1.17.14` to `2.0.0-alpha.24`. I've the scalar which doesn't work in a new version:
> 
> ```rust
> #[derive(Clone, Serialize, Deserialize)]
> #[serde(transparent)]
> pub struct LocalizedString {
>     translations: IndexMap<Language, String>,
> }
> 
> #[Scalar(name = "LocalizedString")]
> impl ScalarType for LocalizedString {
>     fn parse(value: Value) -> InputValueResult<Self> {
>         let json = serde_json::Value::from(value);
>         Ok(serde_json::from_value::<Self>(json)?)
>     }
> 
>     fn to_value(&self) -> Value {
>         serde_json::to_value(&self).unwrap().into()
>     }
> }
> ```
> 
> ```rust
> #[derive(Enum, Copy, Clone, Eq, PartialEq, Hash, Debug, Deserialize, Serialize)]
> #[serde(rename_all = "UPPERCASE")]
> pub enum Language {
>     En,
>     Ru,
>     De,
>     Fr,
> }
> ```
> 
> What is the correct way to rewrite the code? Do I've to do the conversion manually like [here](https://github.com/async-graphql/async-graphql/blob/78341f23927893cfcb4ead88727c86fc17a289df/src/types/external/json_object/btreemap.rs#L17)?

Need to add functions similar to `serde_json::to_value` and `serde_json::from_value`, I am working on this.

**Comment by sunli829** [comment]
@hapcode 

Upgrade to `v2.0.0-alpha.26`.

```rust
#[derive(Clone, Serialize, Deserialize)]
#[serde(transparent)]
pub struct LocalizedString {
    translations: HashMap<Language, String>,
}

#[Scalar(name = "LocalizedString")]
impl ScalarType for LocalizedString {
    fn parse(value: Value) -> InputValueResult<Self> {
        Ok(from_value(value)?)
    }

    fn to_value(&self) -> Value {
        to_value(self).unwrap().into()
    }
}

#[derive(Enum, Copy, Clone, Eq, PartialEq, Hash, Debug, Deserialize, Serialize)]
#[serde(rename_all = "UPPERCASE")]
pub enum Language {
    En,
    Ru,
    De,
    Fr,
}
```

**Comment by hapcode** [comment]
> @hapcode
> 
> Upgrade to `v2.0.0-alpha.26`.
> 
> ```rust
> #[derive(Clone, Serialize, Deserialize)]
> #[serde(transparent)]
> pub struct LocalizedString {
>     translations: HashMap<Language, String>,
> }
> 
> #[Scalar(name = "LocalizedString")]
> impl ScalarType for LocalizedString {
>     fn parse(value: Value) -> InputValueResult<Self> {
>         Ok(from_value(value)?)
>     }
> 
>     fn to_value(&self) -> Value {
>         to_value(self).unwrap().into()
>     }
> }
> 
> #[derive(Enum, Copy, Clone, Eq, PartialEq, Hash, Debug, Deserialize, Serialize)]
> #[serde(rename_all = "UPPERCASE")]
> pub enum Language {
>     En,
>     Ru,
>     De,
>     Fr,
> }
> ```

Parsing is okay, but `to_value` doesn't work with `Language` key. I got the following error: 
```bash 
thread 'actix-rt:worker:1' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("Key must be a string")'
```

**Comment by sunli829** [comment]
> @sunli829 Yes - [see the issue I linked earlier](https://github.com/graphql/graphql-spec/issues/785). GraphQL is also protocol-agnostic so if it supports non-`Name` values it supports non-JSON values.

I don't think it makes much sense to implement this feature, because there is no GraphQL client to support this, what do you think? 🙂

**Comment by sunli829** [comment]
> > @hapcode
> > Upgrade to `v2.0.0-alpha.26`.
> > ```rust
> > #[derive(Clone, Serialize, Deserialize)]
> > #[serde(transparent)]
> > pub struct LocalizedString {
> >     translations: HashMap<Language, String>,
> > }
> > 
> > #[Scalar(name = "LocalizedString")]
> > impl ScalarType for LocalizedString {
> >     fn parse(value: Value) -> InputValueResult<Self> {
> >         Ok(from_value(value)?)
> >     }
> > 
> >     fn to_value(&self) -> Value {
> >         to_value(self).unwrap().into()
> >     }
> > }
> > 
> > #[derive(Enum, Copy, Clone, Eq, PartialEq, Hash, Debug, Deserialize, Serialize)]
> > #[serde(rename_all = "UPPERCASE")]
> > pub enum Language {
> >     En,
> >     Ru,
> >     De,
> >     Fr,
> > }
> > ```
> 
> Parsing is okay, but `to_value` doesn't work with `Language` key. I got the following error:
> 
> ```shell
> thread 'actix-rt:worker:1' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("Key must be a string")'
> ```
> 
> Do I need to convert keys to string? I suppouse `to_value` can't do it automatically, since it requires `serde_json`.

Upgrade to `v2.0.0-alpha.27`. @hapcode  😂

**Comment by Koxiaet** [comment]
> I don't think it makes much sense to implement this feature, because there is no GraphQL client to support this, what do you think? 🙂

In that case there's no point in removing serde json, since that's all we're going to support.

`Name` was originally made for the invariant that it must be a GraphQL name - removing that makes it useless. Sure there's an optimization to be made but I don't think it's worth it.

Since we're only supporting JSON we should move `async_graphql::Value` and `Name` to just a parsing construct, it makes things a lot simpler. Then everything can deal in JSON values.

**Comment by sunli829** [comment]
> > I don't think it makes much sense to implement this feature, because there is no GraphQL client to support this, what do you think? 🙂
> 
> In that case there's no point in removing serde json, since that's all we're going to support.
> 
> `Name` was originally made for the invariant that it must be a GraphQL name - removing that makes it useless. Sure there's an optimization to be made but I don't think it's worth it.
> 
> Since we're only supporting JSON we should move `async_graphql::Value` and `Name` to just a parsing construct, it makes things a lot simpler. Then everything can deal in JSON values.

After switching the output value from `serde_json::Value` to `ConstValue`, the performance improved by 30%. In fact, this is my original intention to remove `serde_json`. 😂

**Comment by sunli829** [comment]
I admit that there is still a lot of room for improvement, but I hope to release the stable `v2.0.0` soon. 😂

**Comment by sunli829** [comment]
@hapcode Upgrade to `2.0.0-alpha.30`, I added a `scalar` macro, it will be more convenient to use this macro in your situation. 🙂

**Comment by hapcode** [comment]
> @hapcode Upgrade to `2.0.0-alpha.30`, I added a `scalar` macro, it will be more convenient to use this macro in your situation. 🙂

Great. I've two similar scalars and the `scalar!` allows me to avoid code duplication. Many thanks.

**Comment by fidGaib** [comment]
and how to use it now serde_json::to_string(&res); ?
