### ISSUE TITLE
Rename function

### ISSUE THREAD

**Issue by rkudryashov** [async-graphql/async-graphql#297]
I think `propogate` function should be renamed to `propagate`

```
    /// Propogate the error message to a different type.
    pub fn propogate<U: InputValueType>(self) -> InputValueError<U> {
        InputValueError::new(format!(
            r#"{} (occurred while parsing "{}")"#,
            self.message,
            U::type_name()
        ))
    }
```

**Comment by sunli829** [comment]
> I think `propogate` function should be renamed to `propagate`
> 
> ```
>     /// Propogate the error message to a different type.
>     pub fn propogate<U: InputValueType>(self) -> InputValueError<U> {
>         InputValueError::new(format!(
>             r#"{} (occurred while parsing "{}")"#,
>             self.message,
>             U::type_name()
>         ))
>     }
> ```

Yes, this is a spelling error.
