### ISSUE TITLE
[Help] Actix-web and federation has some weird behaviour

### ISSUE THREAD

**Issue by simoneromano96** [async-graphql/async-graphql#299]
Hello, I'm experimenting with this library in my public [repo](https://github.com/simoneromano96/federation-graphql-rust) for a future article.

So I noticed some weird behaviour when creating the queries and mutations in the services.

`accounts-services/src/graphql/query.rs`
```rust
use async_graphql::{Context, ID, Object, Result};

use crate::models::{User, UserInfo};

pub struct Query;

#[Object(extends)]
impl Query {
    /// Get current user info
    async fn me(&self, ctx: &Context<'_>) -> Result<UserInfo> {
        // let user = ctx.data::<User>();
        if let Ok(user) = ctx.data::<User>() {
            Ok(user.to_user_info())
        } else {
            Err("Not logged in".into())
        }
    }

    #[graphql(entity)]
    async fn echo(&self, username: String) -> UserInfo { UserInfo { id: None, username } }
}
```

In this query I only have to expose the "me" query, but I had to add the "echo" query otherwise it was empty on the gateway, the `graphql(entity)` macro is unclear to me what it does or how it should be used.

This is the UserInfo struct
`accounts-service/src/models/user.rs`
```rust

/// Available User info
#[derive(Debug, Serialize, Deserialize, Apiv2Schema)]
pub struct UserInfo {
    /// The ID of the user.
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub id: Option<ObjectId>,
    /// The username.
    pub username: String,
}

#[Object]
impl UserInfo {
    async fn id(&self) -> String {
        if let Some(id) = &self.id {
            id.clone().to_string()
        } else {
            String::from("")
        }
    }

    async fn username(&self) -> &str {
        &self.username
    }
}
```

The same goes for the mutations, without a `#[graphql(entity)]` mutation placeholder for each type of input the mutations are not visible from the gateway.
`src\graphql\query.rs`
```rust
pub struct Mutation;

#[Object(extends)]
impl Mutation {
    /// Creates a new coffee
    async fn create_coffee(&self, ctx: &Context<'_>, input: CreateCoffeeInput) -> Result<Coffee> {
        let db: &Database = ctx.data()?;
        create_coffee(db, input).await
    }

    /// Updates a coffee
    async fn update_coffee(&self, ctx: &Context<'_>, input: UpdateCoffeeInput) -> Result<Coffee> {
        let db: &Database = ctx.data()?;
        update_coffee(db, input).await
    }

    /// Deletes a coffeee
    async fn delete_coffee(&self, ctx: &Context<'_>, id: String) -> Result<Coffee> {
        let db: &Database = ctx.data()?;
        delete_coffee(db, id).await
    }

    #[graphql(entity)]
    async fn echo_create_input(&self, _input: CreateCoffeeInput) -> Result<String> {
        Ok("ok".into())
    }

    #[graphql(entity)]
    async fn echo_update_input(&self, _input: UpdateCoffeeInput) -> Result<String> {
        Ok("ok".into())
    }

    #[graphql(entity)]
    async fn echo_delete(&self, _id: String) -> Result<String> {
        Ok("ok".into())
    }
}
```

**Comment by sunli829** [comment]
> In this query I only have to expose the "me" query, but I had to add the "echo" query otherwise it was empty on the gateway, the graphql(entity) macro is unclear to me what it does or how it should be used.

`#[graphql(entity)]` is used to mark an entity lookup method. It should only be used in the `Query` object. The parameter of the method is the `key` of the returned object.

https://www.apollographql.com/docs/federation/entities/#defining

```graphql
type Product @key(fields: "upc") {
   upc: String!
   name: String!
   price: Int
}
```

The above schema defines that `upc` is the key of `Product`, so a lookup method must be provided for `Product`.

```rust
#[Object]
impl Query {
     #[graphql(entity)]
     async fn find_product_by_upc(&self, upc: String) -> Product {
       ....
     }
}
```

> The same goes for the mutations, without a #[graphql(entity)] mutation placeholder for each type of input the mutations are not visible from the gateway.

`#[graphql(entity)]` should not be used in `Mutation`.

**Comment by simoneromano96** [comment]
> 
> 
> > In this query I only have to expose the "me" query, but I had to add the "echo" query otherwise it was empty on the gateway, the graphql(entity) macro is unclear to me what it does or how it should be used.
> 
> `#[graphql(entity)]` is used to mark an entity lookup method. It should only be used in the `Query` object. The parameter of the method is the `key` of the returned object.
> 
> https://www.apollographql.com/docs/federation/entities/#defining
> 
> ```graphql
> type Product @key(fields: "upc") {
>    upc: String!
>    name: String!
>    price: Int
> }
> ```
> 
> The above schema defines that `upc` is the key of `Product`, so a lookup method must be provided for `Product`.
> 
> ```rust
> #[Object]
> impl Query {
>      #[graphql(entity)]
>      async fn find_product_by_upc(&self, upc: String) -> Product {
>        ....
>      }
> }
> ```
> 
> > The same goes for the mutations, without a #[graphql(entity)] mutation placeholder for each type of input the mutations are not visible from the gateway.
> 
> `#[graphql(entity)]` should not be used in `Mutation`.

Hi, thanks for the help, It's a bit clearer now, there is one thing though, I want to expose to the gateway a query to get a single item by its ID, does this mean that I have to duplicate the logic? 
If I put only the `#[graphql(entity)]` I can't find the `find_coffee_by_id` query, if I eliminate the `find_coffee_by_id` there are, of course now that it is clearer, no queries. Is there some kind of attribute that I can pass to `entity` to expose the query to the gateway?
From what I can see no, I must duplicate it because _entities are only for the "internal" services (the ones behind the gateway)

`products-service/src/graphql/query.rs`
```rust
#[Object]
impl Query {
    /// Returns a coffee by its ID, will return error if none is present with the given ID
    async fn coffee(&self, ctx: &Context<'_>, id: ID) -> Result<Coffee> {
        let db: &Database = ctx.data()?;
        fetch_coffee_by_id(db, id.to_string()).await
    }

    /// Returns a coffee by its ID, will return error if none is present with the given ID
    #[graphql(entity)]
    async fn find_coffee_by_id(&self, ctx: &Context<'_>, id: String) -> Result<Coffee> {
        let db: &Database = ctx.data()?;
        fetch_coffee_by_id(db, id).await
    }
}
```

**Comment by sunli829** [comment]
> > > In this query I only have to expose the "me" query, but I had to add the "echo" query otherwise it was empty on the gateway, the graphql(entity) macro is unclear to me what it does or how it should be used.
> > 
> > 
> > `#[graphql(entity)]` is used to mark an entity lookup method. It should only be used in the `Query` object. The parameter of the method is the `key` of the returned object.
> > https://www.apollographql.com/docs/federation/entities/#defining
> > ```graphql
> > type Product @key(fields: "upc") {
> >    upc: String!
> >    name: String!
> >    price: Int
> > }
> > ```
> > 
> > 
> > The above schema defines that `upc` is the key of `Product`, so a lookup method must be provided for `Product`.
> > ```rust
> > #[Object]
> > impl Query {
> >      #[graphql(entity)]
> >      async fn find_product_by_upc(&self, upc: String) -> Product {
> >        ....
> >      }
> > }
> > ```
> > 
> > 
> > > The same goes for the mutations, without a #[graphql(entity)] mutation placeholder for each type of input the mutations are not visible from the gateway.
> > 
> > 
> > `#[graphql(entity)]` should not be used in `Mutation`.
> 
> Hi, thanks for the help, It's a lot clearer now, there is one more thing though, I want to expose to the gateway a query to get a single item by its ID, does this mean that I have to duplicate the logic?
> If I put only the `#[graphql(entity)]` I can't find the `find_coffee_by_id` query, if I eliminate the `find_coffee_by_id` there are, of course now that it is clearer, no queries. Is there some kind of attribute that I can pass to `entity` to expose the query to the gateway?
> From what I can see no, I must duplicate it because `_entities` are only for the "internal" services (the ones behind the gateway).
> Sorry for bothering you.
> 
> `products-service/src/graphql/query.rs`
> 
> ```rust
> #[Object]
> impl Query {
>     /// Returns a coffee by its ID, will return error if none is present with the given ID
>     async fn coffee(&self, ctx: &Context<'_>, id: ID) -> Result<Coffee> {
>         let db: &Database = ctx.data()?;
>         fetch_coffee_by_id(db, id.to_string()).await
>     }
> 
>     /// Returns a coffee by its ID, will return error if none is present with the given ID
>     #[graphql(entity)]
>     async fn find_coffee_by_id(&self, ctx: &Context<'_>, id: String) -> Result<Coffee> {
>         let db: &Database = ctx.data()?;
>         fetch_coffee_by_id(db, id).await
>     }
> }
> ```

Sorry, I was ill the other day, so I didn’t reply immediately.
In this case, maybe you can extract a common function to eliminate duplicate code. 😁

**Comment by simoneromano96** [comment]
Thank you very much
