### ISSUE TITLE
Cannot load playground if last route in warp Filter

### ISSUE THREAD

**Issue by mwilliammyers** [async-graphql/async-graphql#300]
I updated from 559e7c4 to 2.0.0-alpha.22 (and 2.0.0-alpha.23) and I opened my browser to my apollo playground and I get the following error:
```json
{
  "data": null,
  "errors": [
    {
      "message": " --> 1:1\n  |\n1 | \n  | ^---\n  |\n  = expected executable_definition",
      "locations": [{ "line": 1, "column": 1 }]
    }
  ]
}
``` 

I think the issue is happening because I have the `graphql_post` before the playground routes:
```rust
let service = warp::any()
    .and(graphql_post)
    .or(warp::path("altair").and(warp::get()).map(altair_html))
    .or(warp::path("docs").and(warp::get()).map(playground_html))
    .or(warp::path::end().and(warp::get()).map(playground_html))
    .with(cors_config(port, &origins))
    .with(warp::compression::gzip());

warp::serve(service).run(([0, 0, 0, 0], port)).await;
```

`graphql_post` is just a more complicated version of the one from the [warp example](https://github.com/async-graphql/examples/blob/1aa5151b113d265053ea36a855fe17562eec15d9/warp/token-from-header/src/main.rs#L37-L51).

If I just serve the playground without `graphql_post` it works fine. Actually executing the schema using the above routes and the `graphql_post` handler works fine (I think?).

It might have to do with the `IntrospectionQuery`?

I did not change my schema at all. I also did not change my code at all expect to refactor it to update it.

**Comment by sunli829** [comment]
> ```rust
> let service = warp::any()
>     .and(graphql_post)
>     .or(warp::path("altair").and(warp::get()).map(altair_html))
>     .or(warp::path("docs").and(warp::get()).map(playground_html))
>     .or(warp::path::end().and(warp::get()).map(playground_html))
>     .with(cors_config(port, &origins))
>     .with(warp::compression::gzip());
> ```

Did this code work before?

**Comment by mwilliammyers** [comment]
Yep! As of at least 559e7c4, that code worked. I have been using it for more than 6 months like that.

**Comment by sunli829** [comment]
The ʻasync_graphql_warp::graphql` function now handles `GET` requests, a long time ago it only handled `POST` requests.


```rust
let service = warp::any()
    .and(graphql_post)   // <------- .and(graphql_post.and(warp::post()))
    .or(warp::path("altair").and(warp::get()).map(altair_html))
    .or(warp::path("docs").and(warp::get()).map(playground_html))
    .or(warp::path::end().and(warp::get()).map(playground_html))
    .with(cors_config(port, &origins))
    .with(warp::compression::gzip());
```

**Comment by sunli829** [comment]
@mwilliammyers Has this problem been resolved?

**Comment by mwilliammyers** [comment]
I haven't had time to check yet, but I will re-open it if I run into more issues.
