### ISSUE TITLE
Discussion about new context

### ISSUE THREAD

**Issue by AurelienFT** [async-graphql/async-graphql#302]
Following this comment of @Koxiaet : https://github.com/async-graphql/async-graphql/issues/208#issuecomment-694711145 We need to think about a new way to manage the context.

I agree with the fact that the generic parameter is painful to understand and use.

It could be cool if we write the different proposal in this issue.

### My proposal

Make context a structure that can be defined by the user but the structure need to implement a trait to be a `Context`. The context will be pass to requests at integration level. Example:
```rust
pub struct Ctx {
    pub jwt: String,
}

impl async_graphql::Context for Ctx {}
```

Feel free to propose other ways to do it.

**Comment by phated** [comment]
I think the trait makes sense. What is an unbounded generic, exactly?

I thought context carried a lot of internals around with it?

**Comment by Koxiaet** [comment]
A generic without bounds, just `<T>`. Since the trait is empty there's no reason to have it.

**Comment by phated** [comment]
The trait would provide all of the default implementations for the internals used by the library, right?

**Comment by sunli829** [comment]
This trait seems useless? 😳

**Comment by phated** [comment]
So maybe this needs to be a macro?

```rust
#[derive(async_graphql::Context)]
pub struct Ctx {
    pub jwt: String,
}
```

**Comment by Koxiaet** [comment]
@phated What's wrong with a generic parameter though, it's a lot simpler. That method also can't really be done as the `Context` needs a lifetime parameter and generic parameter.

**Comment by phated** [comment]
I thought everyone hated the generic parameter when I proposed it? As for the lifetime, that could be solved with something like smolstr, right?

**Comment by sunli829** [comment]
There is no difference the following two:

```rust
struct Data {
    a: i32,
    b: i32,
}

async fn value(&self, ctx: &Context<'a, Data>) {
    ctx.data.a+ctx.data.b
}
```

```rust
struct Data {
    a: i32,
    b: i32,
}

async fn value(&self, ctx: &Context<'a>) {
    let data = ctx.data::<Data>;
    data.a+data.b
}
```

But the first one has a generic parameter that will spread everywhere.

**Comment by phated** [comment]
See?? Type safety and autocompletion, come to mind....

**Comment by sunli829** [comment]
When your data always has only one type, you don't need to consider type safety at all. Isn't this the same as adding generic parameters to `Context`?

**Comment by sunli829** [comment]
The first one has the type safety problem you mentioned.

```rust
struct ConnectionPool(..);

struct OtherData1(..);

struct OtherData2(..);

async fn value(&self, ctx: &Context<'a>) {
    let cp = ctx.data::<ConnectionPool>();
    let data1 = ctx.data::<OtherData1>();
    let data2 = ctx.data::<OtherData2>();
    ...
}
```

what about this?

```rust
struct MyData {
    connection_pool: ...,
    other_data1: ...,
    other_data2: ...
}

async fn value(&self, ctx: &Context<'a>) {
    let data = ctx.data::<MyData>();
    ...
}
```

**Comment by phated** [comment]
If I remember correctly, I believe you can't destructure values from that (but I haven't tested in 6 months).

**Comment by sunli829** [comment]
> If I remember correctly, I believe you can't destructure values from that (but I haven't tested in 6 months).

So, the second one can solve your question about type safety? 😂
