### ISSUE TITLE
Add templates issues

### ISSUE THREAD

**Issue by AurelienFT** [async-graphql/async-graphql#303]
The repository is growing and even if he is really well maintained the numbers of issues will increase too.

I would like to add issues templates for bug report/bug help.

The template must add the label bug each time he is used.

# Proposal of template : 

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem: 

This template looks good to you ?

**Comment by sunli829** [comment]
Thank you, this one looks great!

**Comment by AurelienFT** [comment]
Yep I din't had time those days I'll do it today or tomorrow.

**Comment by AurelienFT** [comment]
Made in https://github.com/async-graphql/async-graphql/pull/313
