### ISSUE TITLE
panic with IndexMap: key not found

### ISSUE THREAD

**Issue by chipsenkbeil** [async-graphql/async-graphql#308]
I seem to be hitting some unexpected errors again; this time with `async-graphql-alpha.24`. When adding this method to one of my GraphQL objects, I get different errors for graphiql and graphql playground:

```rust
#[derive(async_graphql::Union, Debug)]
pub enum Element {
    /// BlockElement is also a union
    #[graphql(flatten)]
    Block(BlockElement),

    /// InlineElement is also a union
    #[graphql(flatten)]
    Inline(InlineElement),
}

async fn element_in_page_at_pos(&self, path: String, line: i32, column: i32) -> Option<Element> {
    // ...
}
```

If you want the full source where this happens, this commit introduced the issue for me: https://github.com/chipsenkbeil/vimwiki-server/commit/8eed2d6ff107099b5ad6421195618e4e5be4838e

You can encounter the below errors by running `cargo run -- -vv` from the **vimwiki-server** directory and then visiting `http://localhost:8000/graphiql` or `http://localhost:8000/graphql_playground`.

![3BB37702-1A3C-4AD3-AF84-A91B606E3B1A](https://user-images.githubusercontent.com/2481802/95672311-5c1dee80-0b65-11eb-9a1f-96a4ddd84abc.png)
![5CB9D9AF-0780-4083-9564-E1C0F4A0931C](https://user-images.githubusercontent.com/2481802/95672322-6cce6480-0b65-11eb-9811-b59c86e67aed.png)
![39E78458-A32D-48DD-A988-0C4387C408FF](https://user-images.githubusercontent.com/2481802/95672324-6f30be80-0b65-11eb-95d7-0a04382c1cbf.jpeg)

**Comment by sunli829** [comment]
Upgrade to `v2.0.0-alpha.28`. 😁

**Comment by chipsenkbeil** [comment]
Fixed :)
