### ISSUE TITLE
Integrate GraphQL subscription and Kafka consumer

### ISSUE THREAD

**Issue by rkudryashov** [async-graphql/async-graphql#309]
I didn't manage to do this, the example below is not compiled:

```rust
#[Subscription]
impl Subscription {
    async fn test<'a, 'b, 'c>(&'a self, ctx: &'b Context<'c>) -> impl Stream<Item=String> + 'b {
        let consumer = ctx.data::<StreamConsumer>().expect("Can't get Kafka consumer");
        let stream = consumer.start();
        stream.map(|result| {
            match result {
                Ok(message) => {
                    let payload = message.payload().expect("Message should contain payload");
                    String::from_utf8_lossy(payload).to_string()
                }
                Err(e) => panic!("Error while Kafka message processing: {}", e)
            }
        })
    }
}
```

Error message:

```
error[E0261]: use of undeclared lifetime name `'b`
   --> test-service\src\graphql.rs:129:93
    |
129 |     async fn test<'a, 'b, 'c>(&'a self, ctx: &'b Context<'c>) -> impl Stream<Item=String> + 'b {
    |                                                                                             ^^ undeclared lifetime
```

I asked for help in a Rust chat, and one of assumptions was that this is a strange behavior of `Subscription` macro, because without the macro  the example is compiled without errors.

Explicit lifetimes was needed just for clarification; they will be removed when the example is compiled.

**Comment by sunli829** [comment]
`MergedObject` cannot be placed in `Interface` and will not be supported in the future. 😁

**Comment by sunli829** [comment]
Upgrade to `v2.0.0-alpha.29`.

In fact, you only need to look like the following.

```rust
#[Subscription]
impl Subscription {
    async fn test<'ctx>(&self, ctx: &Context<'ctx>) -> impl Stream<Item=String> + 'ctx {
        let consumer = ctx.data::<StreamConsumer>().expect("Can't get Kafka consumer");
        let stream = consumer.start();
        stream.map(|result| {
            match result {
                Ok(message) => {
                    let payload = message.payload().expect("Message should contain payload");
                    String::from_utf8_lossy(payload).to_string()
                }
                Err(e) => panic!("Error while Kafka message processing: {}", e)
            }
        })
    }
}
```

**Comment by rkudryashov** [comment]
> 
> 
> Upgrade to `v2.0.0-alpha.29`.
> 
> In fact, you only need to look like the following.
> 
> ```rust
> #[Subscription]
> impl Subscription {
>     async fn test<'ctx>(&self, ctx: &Context<'ctx>) -> impl Stream<Item=String> + 'ctx {
>         let consumer = ctx.data::<StreamConsumer>().expect("Can't get Kafka consumer");
>         let stream = consumer.start();
>         stream.map(|result| {
>             match result {
>                 Ok(message) => {
>                     let payload = message.payload().expect("Message should contain payload");
>                     String::from_utf8_lossy(payload).to_string()
>                 }
>                 Err(e) => panic!("Error while Kafka message processing: {}", e)
>             }
>         })
>     }
> }
> ```

Thanks, now it works, but with different lifetimes config:

```rust
#[Subscription]
impl Subscription {
    async fn test<'ctx>(&self, ctx: &'ctx Context<'_>) -> impl Stream<Item=String> + 'ctx {
        let consumer = ctx.data::<StreamConsumer>().expect("Can't get Kafka consumer");
        let stream = consumer.start();
        stream.map(|result| {
            match result {
                Ok(message) => {
                    let payload = message.payload().expect("Kafka message should contain payload");
                    String::from_utf8_lossy(payload).to_string()
                }
                Err(e) => panic!("Error while Kafka message processing: {}", e)
            }
        })
    }
}
```
