### ISSUE TITLE
Ability not to define a query

### ISSUE THREAD

**Issue by rkudryashov** [async-graphql/async-graphql#318]
After upgrading from 2.0.3 (not sure, maybe earlier version) to 2.0.7 one of my services stopped compiling:

```rust
error: An GraphQL Object type must define one or more fields.
  --> auth-service\src\graphql.rs:13:6
   |
13 | impl Query {}
   |      ^^^^^
```

It doesn't have any query, it contains just a couple of mutations. Is it possible to return this ability or maybe create `EmptyQuery` by analogy with mutation and subscription?

**Comment by rkudryashov** [comment]
That is a pet project, so I definitely can add some query :) And it is hard to imagine real service without a single query.

So just FYI.

**Comment by Koxiaet** [comment]
We _could_ allow this, but it is explicitly disallowed by the [GraphQL spec](https://spec.graphql.org/June2018/#sec-Objects):

> Object types have the potential to be invalid if incorrectly defined. This set of rules must be adhered to by every Object type in a GraphQL schema.
> 
> 1. An Object type must define one or more fields.

And I don't think that allowing invalid schemas is a good idea.

You might want to [fix this issue](https://github.com/graphql/graphql-spec/issues/568) if you would like this feature in GraphQL itself.

**Comment by rkudryashov** [comment]
I understand that an empty type is invalid. Earlier, that code could be compiled and final schema didn't include `Query` GraphQL type at all. Thank you for link, I found an answer:

> The query root operation type must be provided and must be an Object type.

(https://spec.graphql.org/June2018/#sec-Root-Operation-Types)
