### ISSUE TITLE
Re-introduce Rocket Fairing

### ISSUE THREAD

**Issue by Weasy666** [async-graphql/async-graphql#320]
In 7caff6beee391bbec60ba713aede674bc7bdce9f you removed GraphQL as a fairing.

I think it would be great if you put that back in. In Rocket additional features/functionsare mostly introduced as a fairing, as that is Rockets concept of a [middleware](https://rocket.rs/master/guide/fairings/#fairings). That is exactly why i initially did that. This allows a user to see in the logs on server startup, that GraphQL is running and configured. It also allowed to easily configure graphql with providing the schema as argument when attaching a fairing.

Was there a special reason why it was removed?

**Comment by Koxiaet** [comment]
I didn't feel the fairing added much to the integration. Attaching the schema, being one expression, is much easier done manually - `.attach(graphql)` is no shorter than `.manage(schema)`, and the latter makes it more clear to the user what's actually happening. The same applies to multipart options; `.manage(opts)`, while slightly more hard to discover, is equally concise as managing it through the GraphQL fairing.

I decided to remove logging as none of the other integrations have it, and I would like to make the integrations as consistent as possible. I'm not opposed to idea though, as long as it's feature-flagged and correctly documented in the [requirements](https://github.com/async-graphql/async-graphql/tree/master/integrations#requirements-for-an-http-integration).

**Comment by Weasy666** [comment]
But shouldn't a integration be consistend with the library/framework it integrates with? The whole point of the fairing and logging at the time when the fairing will be attached, was to make it consistent with the rest of the `Rocket` ecosystem. If you "need" to use `async-graphql` with `Rocket` the way it is now, then it does not feel consistent with other `Rocket` integrations. The logging is part of that consistency, as `Rocket` prints all routes and fairings on startup, i would also expect that `GraphQL` is printed at that point.

**Comment by Koxiaet** [comment]
Ah, I was not aware of Rocket's ecosystem conventions. But I still don't think a GraphQL fairing is a good idea - GraphQL fundamentally isn't middleware, it's an endpoint and adding a fairing can be confusing and unintuitive. Also, what would the logging represent? There is no action performed that requires logging, since it will be instantly and infallibly run on startup. The only place where logging would make sense would be the creation of the schema, but that's done outside of Rocket.

**Comment by Weasy666** [comment]
I personally think of a middleware as a piece of software that makes a specific task easier for me and that is ultimately what `async-graphql` does for me and what fairings in Rocket do, too. For example the database fairing, it makes it easy to create a connection pool for different databases, so that one can easily retrieve a connection and talk to the database. It would be easy to use r2d2 and add it to the managed state and then access it with the implemented request guard (FromRequest), nevertheless a fairing is provided to make setup as easy as possible, that is just the Rocket way of doing things.
Because of that, i think it is more confusing for someone using Rocket, that there is no fairing.

Regarding the logging. Rocket logs/prints its configuration, including routes and fairings, on startup, so that it is easy to see and follow with what configuraten a specific rocket instance was started with and is running with. See this screenshot:
![grafik](https://user-images.githubusercontent.com/11967542/96990859-f39d1d00-1527-11eb-9888-18cf39bb541d.png)
That is the only place the logging of the fairing would show up and i find it rather usefull to see, with what a rocket server starts. Not on a project i myself am developing, but on other projects i am just a user of.

**Comment by Koxiaet** [comment]
Yeah OK, I think we should reintroduce the GraphQL fairing.

Maybe you'll tell me this is common Rocket practice too, but it feels wrong to provide the user with the schema data and yet force them to execute the actual request with the schema manually - either we leave all the schema handling up to the user, or we handle everything automatically but a combination of both feels weird. I think the solution is to provide an implementation of the `Handler` trait, which would also be a lot easier for the user.

**Comment by Weasy666** [comment]
Hm...you have a point there. Let me think a bit about that.

When i implemented the integration i initially wanted to hide the routes from the user by implementing them in the integration. I have then decided not to do it, because a user could want additional arguments on a GraphQL route and would not be able to add them if the routes are hidden. I think the same problem would be present with a `Handler`, but...i am not sure if a user ever would need extra arguments on a GraphQL route 😅

**Comment by sunli829** [comment]
I will close this issue, if you have any questions, please feel free to open it. 😁
