### ISSUE TITLE
Mutable context data for mutation

### ISSUE THREAD

**Issue by chipsenkbeil** [async-graphql/async-graphql#326]
## Description of the feature

If a query can have a context where you can retrieve a reference to some data, I'd love to have the ability to have something similar for a mutation, but where the data can be accessed with a mutable reference.

The reason being is that I have a context that maintains the program's list of open files to be able to query. The client needs to be able to tell the server to open a new file, which is where a mutation would come into play. I need to call a method like `load_file(&mut self, path: impl AsRef<Path>)` on the data within the context to do this.

## Code example (if possible)

```rust
async fn load_page(&self, ctx: &mut async_graphql::Context<'_>, path: String) -> Option<Page> {
    let program: &mut Program = ctx.mut_data_unchecked::<Program>();
    program.load_file(&path)
}

**Comment by Koxiaet** [comment]
You'd have to implement locking yourself. The client's mutations are executed in series, but the server can execute several mutations at once. We _could_ add locks to `Context` but I think that's best left up to the user.

**Comment by chipsenkbeil** [comment]
> You'd have to implement locking yourself. The client's mutations are executed in series, but the server can execute several mutations at once. We _could_ add locks to `Context` but I think that's best left up to the user.

Makes sense. That's what I'll do. Thanks!
