### ISSUE TITLE
`SchemaBuilder::override_description` not working

### ISSUE THREAD

**Issue by Weasy666** [async-graphql/async-graphql#327]
I wanted to use the new function `SchemaBuilder::override_description` like this:

```rust
let schema = Schema::build(Root, EmptyMutation, EmptySubscription)
    .override_description::<chrono::DateTime<chrono::Utc>>("Some doc string.");
```
with `features = ["chrono", "chrono-tz"]` activated.
But the schema, generated with `Schema<Root, EmptyMutation, EmptySubscription>::sdl()`, still has 

```graphql
"""
Implement the DateTime<Utc> scalar

The input/output is a string in RFC3339 format.
"""
scalar DateTime
```

as doc string.

**Comment by sunli829** [comment]
> I wanted to use the new function `SchemaBuilder::override_description` like this:
> 
> ```rust
> let schema = Schema::build(Root, EmptyMutation, EmptySubscription)
>     .override_description::<chrono::DateTime<chrono::Utc>>("Some doc string.");
> ```
> 
> with `features = ["chrono", "chrono-tz"]` activated.
> But the schema, generated with `Schema<Root, EmptyMutation, EmptySubscription>::sdl()`, still has
> 
> ```graphql
> """
> Implement the DateTime<Utc> scalar
> 
> The input/output is a string in RFC3339 format.
> """
> scalar DateTime
> ```
> 
> as doc string.

I added a test case, but cannot reproduce the problem.

**Comment by Weasy666** [comment]
Introspection works as inspected, the problem occurs, when you write the SDL to a string or file.
```rust
let schema = Schema::build(Root, EmptyMutation, EmptySubscription)
    .override_description::<chrono::DateTime<chrono::Utc>>("Some doc string.");

std::fs::write("schema.graphql", Schema<Root, EmptyMutation, EmptySubscription>::sdl())
    .unwrap();
```

**Comment by sunli829** [comment]
This problem is because the `Schema::sdl` function creates a new `Registry`, so I modified the implementation of this function, and it now requires `&self`.

**Comment by Weasy666** [comment]
Thank you! Fast as always 😀

**Comment by sunli829** [comment]
> Thank you! Fast as always 😀

`Rocket` examples cannot be compiled, can you help solve it?

**Comment by Weasy666** [comment]
Yes, will take a look

**Comment by Weasy666** [comment]
It looks like the update of the `examples` submodule from my PR https://github.com/async-graphql/async-graphql/pull/324 did somehow not get merged.

**Comment by sunli829** [comment]
> It looks like the update of the `examples` submodule from my PR #324 did somehow not get merged. Resulting in an outdated Rocket dependency, which does not compile with the newer on of the integration.

Thanks, fixed. 🙂

**Comment by Weasy666** [comment]
You are welcome
