### ISSUE TITLE
When is data serialized/deserialized?

### ISSUE THREAD

**Issue by d4h0** [async-graphql/async-graphql#328]
Hi,

I'm building a static website generator and I'm thinking about using `async-graphql` as the data store.

I'm wondering what exactly happens between inserting and requesting data, when this happens in the same app where `async-graphql` lives.

Let's say, I read all files of a directory and insert these files as a struct into the GraphQL server (with fields like `path`, `file_extension`, and `file_content`), then later another components queries data.

Will `async-graphql` first serialize my file structs to strings and later, when I request them, from strings back to my file structs?

If so: is there a way to prevent needless serialization/deserializing?

Thanks for answering my question!

**Comment by Koxiaet** [comment]
Yes, if you store them as a file struct on the server they will be deserialized and serialized each time they're accessed through `async-graphql` (I'm assuming you have some sort of collection of file types behind a lock on the server). If you want to avoid this you don't have to serialize/deserialize them at all; you could just store them as JSON strings in the server, and then the client can parse the JSON when it receives it.

**Comment by d4h0** [comment]
What I mean is, when I store an `i32` in the server, will it at any point be converted to a string – or will it just be converted to (and returned as) [Value::Number(Number)](https://docs.rs/async-graphql/2.0.9/async_graphql/enum.Value.html), which would be much cheaper than converting an `i32` into a string and then converting the string back into a number (server and client are in the same process).

> If you want to avoid this you don't have to serialize/deserialize them at all; you could just store them as JSON strings in the server, and then the client can parse the JSON when it receives it.

So the "client" (client and server are the same) needs Rust types, so using JSON would be the worst case scenario, I think.

Maybe I should have first read the docs to get a better understanding of what's going on... 😅

**Comment by Koxiaet** [comment]
If you store an `i32` on the server it will be converted into a `Number`, and then when data is sent to the client it will be serialized into a JSON string, so we do avoid stringifying the number at any point (unless of course you enable the `arbitrary_precision` feature of `serde_json`, in which case `Number` becomes a `String`).

**Comment by d4h0** [comment]
If I understand your message correctly, I think there are some misunderstandings, or I didn't explain my use-case understandable enough :)

Let's say, we have this code:

(The code is obviously not working and just to demonstrate what I mean)

```rust
use async_graphql::{Context, Enum, Object, Result, Schema, Subscription, ID};

#[derive(Clone)]
pub struct MyFile {
    id: ID,
    some_number: i32,
    path: String,
}

#[Object]
impl MyFile {
    async fn id(&self) -> &str {
        &self.id
    }

    async fn some_number(&self) -> i32 {
        &self.some_number
    }

    async fn path(&self) -> &str {
        &self.name
    }
}

// other setup stuff

#[Object]
impl MyFileRoot {
    async fn create_file(&self, ctx: &Context<'_>, path: String, some_number: i32) -> ID {
        // do what is needed
    }

    // more methods
}

fn main() {
    let ctx = get_context();
    let schema = get_schema();
    let my_file_root = get_my_file_root();

    // insert a `MyFile
    my_file_root.create_file(ctx, "some/path", 42);

    // immediately get the `MyFile` from the store
    let query = create_myfile_query("some/path");
    let my_file = schema.execute(query);
}
```

At the last line, will `MyFile` ever be converted to a JSON string (i.e. `{id: 1, path: "some/path", someNumber: 42}`), or will `MyFile` only be converted to `async_graphql::Value`?

**Comment by Koxiaet** [comment]
Oh right, I see what you mean. It will only be converted into a Value, JSON serialization is handled by the transport.

**Comment by d4h0** [comment]
That's great, thanks!

Is there an easy way to convert a `Value` back to the source type (`MyFile` in this example)?

I see that `Value` has `impl Serialize for ConstValue` – that means I can use `serde` to get back a `MyFile`, right?

**Comment by sunli829** [comment]
You can use ʻasync_graphql::from_value` to convert `Value` back to the source type.

**Comment by d4h0** [comment]
Ah, I missed that, thanks!

So that answers all of my questions for now.

If I have new questions, should I reuse this issue or create new ones?

If the latter, I will keep this issue open while I study GraphQL and async-graphql in detail during the next few days.

**Comment by sunli829** [comment]
When you have other issues, please create a new issue. 🙂
