### ISSUE TITLE
Name a connection

### ISSUE THREAD

**Issue by Weasy666** [async-graphql/async-graphql#329]
Sorry for yet another question, maybe you should open a [matrix.org](https://matrix.org/try-now/) room 😅.

Is it possible to explicitely name a connection, instead of the autogenerated name that depends on the returned struct?
As an example:
This Rust code
```rust
pub type EntityConnection = Connection<usize, Option<Entity>, EntityConnectionFields, EmptyFields>

#[derive(SimpleObject, Debug)]
pub struct EntityConnectionFields {
    pub total_count: i32
}

pub type SomethingElseConnection = Connection<usize, Option<Entity>, SomethingElseConnection, EmptyFields>

#[derive(SimpleObject, Debug)]
pub struct SomethingElseConnectionFields {
    pub total_count: i32
}
```
will result in
```graphql
type EntityConnection {
	pageInfo: PageInfo!
	edges: [EntityEdge]
	totalCount: Int!
}

type EntityEdge {
	node: Entity!
	cursor: String!
}
```

This means, that rust connections with the same return type and the same fields on the connection, result in the same SDL connection, which is named after the returned rust type. This results in a problem, if have differently named fields on the `...ConnectionFields` struct.
This Rust code
```rust
pub type EntityConnection = Connection<usize, Option<Entity>, EntityConnectionFields, EmptyFields>

#[derive(SimpleObject, Debug)]
pub struct EntityConnectionFields {
    pub total_count: i32
}

pub type SomethingElseConnection = Connection<usize, Option<Entity>, SomethingElseConnection, EmptyFields>

#[derive(SimpleObject, Debug)]
pub struct SomethingElseConnectionFields {
    pub average: i32
}
```
will result in
```graphql
type EntityConnection {
	pageInfo: PageInfo!
	edges: [EntityEdge]
	totalCount: Int!
}

type EntityEdge {
	node: Entity!
	cursor: String!
}
```
Meaning that the field `average` is silently ignored and does not appear in the SDL.

**Comment by sunli829** [comment]
Use `MergedObject` to change the name of the object. This is the easiest way I can think of temporarily.

**Comment by Weasy666** [comment]
How should i use it? What should i merge?
And... in my case `Entity` is a interface and that doesn't work according to the book.

**Comment by sunli829** [comment]
Is your `Entity` an interface? Now that `MergedObject` and `ConnectionType` are not supported, let me think about it.

**Comment by Weasy666** [comment]
Yes, `Entity` is an interface.

**Comment by sunli829** [comment]
@Weasy666 I added a `connection::query_with` function to help you solve this problem.

**Comment by sunli829** [comment]
@Weasy666 I added a connection::query_with function to help you solve this problem.

https://github.com/async-graphql/async-graphql/blob/2e6d40ab241aef3d182c4a10b0ba43de8882e9b3/src/types/connection/mod.rs#L195

**Comment by Sytten** [comment]
I am facing a similar issue, but I only care about the edge. I tried creating a `SimpleObject` type but it doesn't work because I use a custom cursor:
```
#[derive(SimpleObject)]
pub struct InterceptEntryEdgeFiltered {
    cursor: Cursor,
    node: InterceptEntry,
    matches_filter: bool,
}
```
```
the trait bound `api::resolvers::cursor::Cursor: async_graphql::Type` is not satisfied
the trait `async_graphql::Type` is not implemented for `api::resolvers::cursor::Cursor`
```
Is there a way to have to implement the `Type` trait for my `Cursor`?
Thanks :)

**Comment by sunli829** [comment]
> Cursor

All fields of the GraphQL object must implement the `Type` trait, so the [`Scalar`](https://docs.rs/async-graphql/2.11.2/async_graphql/attr.Scalar.html) macro may be able to help you.

**Comment by Sytten** [comment]
It is interesting because I didnt need to implement it before when I was using the default edge. So it was somehow autogenerated?

**Comment by sunli829** [comment]
> It is interesting because I didnt need to implement it before when I was using the default edge. So it was somehow autogenerated?

In fact, the default Edge already implements it.

https://github.com/async-graphql/async-graphql/blob/bd68b412f55099a339afb4f0c566e403fd28f2a7/src/types/connection/edge.rs#L43

**Comment by sunli829** [comment]
Do you want to define a new edge just because you want to extend new fields? If this is the case, you can do something like this:

https://github.com/async-graphql/async-graphql/blob/bd68b412f55099a339afb4f0c566e403fd28f2a7/tests/connection.rs#L5

**Comment by Sytten** [comment]
I want to create a new edge because I already have one with the default name and I need another one with more fields for another context but I cant control the name using this method.
