### ISSUE TITLE
Handling clients that send charset with content-type header

### ISSUE THREAD

**Issue by onelson** [async-graphql/async-graphql#332]
I ran into a problem using the [JS Graphql plugin for IntelliJ](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin) since it sends requests with a charset specified in the content-type header.

With the actix-web integration (and I assume others) this results in a 400 response:

```
Unknown content-type "application/json; charset=UTF-8"
```

I'm not sure if I should be looking for a way to strip the charset from the header before passing it along to async_graphql, or if the crate should allow this to run as-is.

Any ideas for how this should be handled?

**Comment by onelson** [comment]
I'm a little puzzled as to what's going on with this client since json is always meant to be utf-8, so I don't see what good requesting a charset would do.

- https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/123
- https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/181

Very confusing changes happening on the plugin side. Maybe there's nothing to be done here for async_graphql.

**Comment by sunli829** [comment]
This constraint has been removed, please upgrade to `v2.0.10`.

**Comment by onelson** [comment]
Will do. Thanks!
