### ISSUE TITLE
Does a MergedObject support merging objects with explicit lifetime parameters?

### ISSUE THREAD

**Issue by stevenxie** [async-graphql/async-graphql#333]
I am attempting to create a `MergedObject` from two objects (a `SimpleObject`, and an `Object`) with explicit lifetime parameters; however, this fails to compile with "implicit elided lifetime not allowed here". Removing the `#[derive(MergedObject)]` will allow the crate to compile. Does this mean that `MergedObjects` cannot support explicit lifetimes? (I checked the book, but I didn't see this as a restriction of `MergedObjects`, so I wonder if maybe I am just doing something wrong.)

Some example code:
```rust
#[derive(SimpleObject)]
struct ObjectA<'a> {
     field_a: &'a str
}

#[derive(SimpleObject)]
struct ObjectB<'a> {
    field_b: &'a str
}

#[derive(MergedObject)] # fails with "implicit elided lifetime not allowed here"
pub struct Object<'a>(ObjectA<'a>, ObjectB<'a>);
```

**Comment by sunli829** [comment]
I will solve this problem later.

**Comment by sunli829** [comment]
Fixed, here is the test code.

https://github.com/async-graphql/async-graphql/blob/7c62b10ebcda3df12cdfc91695286e362ae3bd58/tests/merged_object.rs#L341

**Comment by stevenxie** [comment]
Awesome! Thanks for the super quick resolution :)
