### ISSUE TITLE
Tracing extension: take currently active span as parent

### ISSUE THREAD

**Issue by frigus02** [async-graphql/async-graphql#337]
## Description of the feature

We're using `tracing` to build distributed tracing across a few services. We would like everything that happens for a request to appear inside a single trace. To do that service A calls service B and sends across tracing headers. We then extract those headers and create a new span with trace and span id from the headers. We're using a combination of `async-graphql`, `tide`, `opentelemetry`,`tracing`, and `tracing-opentelemetry` to achieve that.

The [Tracing extension](https://docs.rs/async-graphql/2.0.12/async_graphql/extensions/struct.Tracing.html) is super useful. It's very easy to use and reports everything we could every want through `tracing`. But at the moment it forces a new trace for every GraphQL query:

https://github.com/async-graphql/async-graphql/blob/79ab41487c914d9f5c7d4e72dbdeecf9d6dc05a0/src/extensions/tracing.rs#L42

Without `parent: None` the GraphQL spans would be part of the current trace.

It would be amazing if we could either emove `parent: None` altogether or make this behaviour configurable. I'm not sure what the best practice is for libraries with `tracing` support.

I'd be happy to submit a PR if we can agree on the solution 🙂

**Comment by sunli829** [comment]
Released `v2.0.14`.

**Comment by frigus02** [comment]
Thanks for working on this so quickly. Using `Tracing::with_parent`, is it possible to have a different parent span for each HTTP request?

A minimal sample of our code looks like this at the moment:

```rust
use async_graphql::{Context, EmptyMutation, EmptySubscription, Object, Schema};
use async_std::task;
use tide::{Middleware, Next, Request};
use tracing_futures::Instrument;
type Result<T> = std::result::Result<T, Box<dyn std::error::Error + Send + Sync>>;

struct TracingMiddleware;

#[async_trait::async_trait]
impl<State: Clone + Send + Sync + 'static> Middleware<State> for TracingMiddleware {
    async fn handle(&self, req: Request<State>, next: Mext<'_, State>) -> tide::Result {
        let span = tracing::info_span!(
            "request",
            http.method = req.method().as_ref(),
            http.target = req.url().as_ref()
        );
        let res = next.run(req).instrument(span).await;
        Ok(res)
    }
}

struct QueryRoot;

#[Object]
impl QueryRoot {
    async fn hello(&self, ctx: &Context<'_>) -> String {
        "World"
    }
}

#[derive(Clone)]
struct AppState {
    schema: Schema<QueryRoot, EmptyMutation, EmptySubscription>,
}

fn main() -> Result<()> {
    task::block_on(run())
}

async fn run() -> Result<()> {
    let schema = Schema::build(QueryRoot, EmptyMutation, EmptySubscription)
        .extension(async_graphql::extension::Tracing)
        .finish();

    let mut app = tide::with_state(AppState { schema });
    app.with(TracingMiddleware);
    app.at("/graphql").post(handle_graphql);
    app.listen("localhost:8000").await?;

    Ok(())
}

async fn handle_graphql(req: Request<AppState>) -> tide::Result {
    let schema = req.state().schema.clone();
    let req = async_graphql_tide::receive_request(req).await?;
    async_graphql_tide::respond(schema.execute(req).await)
}
```

We could move the schema builder into `handle_graphql` and construct a new tracing middleware. Would that be the right approach?

```rust
async fn handle_graphql(req: Request<AppState>) -> tide::Result {
    let schema = Schema::build(QueryRoot, EmptyMutation, EmptySubscription)
        .extension(async_graphql::extension::Tracing::with_parent(tracing::Span::current())
        .finish();
    let req = async_graphql_tide::receive_request(req).await?;
    async_graphql_tide::respond(schema.execute(req).await)
}
```

**Comment by sunli829** [comment]
Haha, I didn't think about it clearly, let me change it again.

**Comment by sunli829** [comment]
I added `TracingConfig` to the master branch, please help to see if it is what you want. @frigus02

**Comment by frigus02** [comment]
Yes, that looks great. Thanks again for working on this so quickly. 👍
