### ISSUE TITLE
#[Object] impl QueryRoot,when I pass a refrerence to the third parameter of the fn,the error info is "The Context must be the second argument"

### ISSUE THREAD

**Issue by warriorsfly** [async-graphql/async-graphql#339]
Hi,there.
When I passed the wrong param:id, the error msg is "The Context must be the second argument", this may be a little confusing?
``` rust
   async fn user(&self, ctx: &Context<'_>, id: &str) -> Result<User> {
        let pool = ctx.data_unchecked::<Pool>();
        sqlx::query_as::<_, User>("select * from jbxx_index where id = ?")
            .bind(id)
            .fetch_one(pool)
            .await
            .map_err(|error| Error::from(error))
    }
```

**Comment by sunli829** [comment]
Only types that implement `InputValueType` can be used as input parameters. Here you should use `String` instead of `&str`

**Comment by warriorsfly** [comment]
> Only types that implement `InputValueType` can be used as input parameters. Here you should use `String` instead of `&str`.

Yes, you are right. But I mean, the error message is "The Context must be the second argument", this is what makes me confusing, as your reply, I think some thing like " Only types that implement `InputValueType` can be used as input parameters. Here you should use `String` instead of `&str`." may be a better error message.

**Comment by sunli829** [comment]
I have modified this error message, thank you! 🙂
