### ISSUE TITLE
Translate the current Chinese document to English

### ISSUE THREAD

**Issue by sunli829** [async-graphql/async-graphql#34]

**Comment by Ejhfast** [comment]
I can help with this. I'll try to take a first pass over the weekend!

**Comment by sunli829** [comment]
Wow, you can read Chinese?😁

**Comment by Ejhfast** [comment]
I am learning and my spouse is a native speaker :) I will also have Google Translate help me.

**Comment by sunli829** [comment]
Thank you. It's so exciting. Let me know if you need anything. 😁

**Comment by DataCorrupted** [comment]
I am more than happy to help. @Ejhfast

**Comment by DataCorrupted** [comment]
I just started translating `TypeSystem`

**Comment by Ejhfast** [comment]
@DataCorrupted awesome! I just did the two sections after that

**Comment by sunli829** [comment]
Thank you for the help. 😁 @Ejhfast @DataCorrupted
