### ISSUE TITLE
async_graphql::Object does not work when inside macro after rust 1.48.0

### ISSUE THREAD

**Issue by takumib** [async-graphql/async-graphql#340]
I'm working on a project and when trying to create a macro, I am no longer able to use `async_graphql::Object` inside of a macro with `rust 1.48.0` and `async-graphql 2.0`. 

Example:

```
macro_rules! test_data {
    ($test_name:ident,
    ) => {
        #[derive(Debug, Clone)]
        pub struct $test_name {
            // struct
        }

        #[async_graphql::Object]
        impl $test_name {
            // impl
        }
};
```

Works with `rust 1.47.0` and `async-graphql 2.0`. Current error says `Invalid type`

**Comment by sunli829** [comment]
Fixed in `v2.1.13`. 🙂

**Comment by takumib** [comment]
Thank you!

Another issue I just noted was using an empty struct with `async_graphql::SimpleObject` is not working in `rust 1.48.0` as well.

**Comment by sunli829** [comment]
> Thank you!
> 
> Another issue I just noted was using an empty struct with `async_graphql::SimpleObject` is not working in `rust 1.48.0` as well.

Because the GraphQL specification does not allow empty objects.

**Comment by sunli829** [comment]
I will close this issue, please feel free to open it if you have any questions.
