### ISSUE TITLE
Issue with tokio when `cargo run` warp example

### ISSUE THREAD

**Issue by phungleson** [async-graphql/async-graphql#341]
It is very likely not the issue of `async-graphql` but anyway when I try `cargo run` on this folder:

https://github.com/async-graphql/examples/tree/d8906667a98cd26938906a546c583392195d030e/warp/starwars

I got this error message:

```
Playground: http://localhost:8000
thread 'main' panicked at 'there is no reactor running, must be called from the context of Tokio runtime', .../.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/io/driver/mod.rs:204:14
```

Really appreciate if someone can point me to some correct direction.

I kind of understand that the code need some sort of tokio rt but I thought it should be done via `#[tokio::main]`?

Update 1: actix example seems to be working so looks like it is `warp` issue?

**Comment by Koxiaet** [comment]
This is due to Warp still using Tokio 0.2, when we've upgraded to Tokio 0.3. It should be fixed now, I just had to use `tokio-compat-02`.

**Comment by phungleson** [comment]
Right thanks @Koxiaet warp repo and this [PR](https://github.com/seanmonstar/warp/pull/741) in particular seem dormant at the moment, looks like I should go give actix a whirl instead.

**Comment by phungleson** [comment]
Awesome thanks for this https://github.com/async-graphql/examples/commit/1ea38b62c83d35108071211abe193e1e75bde918 @Koxiaet
