### ISSUE TITLE
How to build customize GraphQL engine

### ISSUE THREAD

**Issue by phungleson** [async-graphql/async-graphql#342]
Hi,

I understand that this is out of the scope of this repo and the definition of GraphQL but I would like to build some thing a bit more flexible but also familiar to GraphQL.

For example I want to have a mutation

```graphql
mutation {
  create_{object_name}(object: { id: ''... }) {
  }
}
```

Where `{object_name}` is dynamic and I would like to access it via `async-graphql` somehow perhaps as a var `object_name` in a `create` function. Additional I would like to have object as flexible as a map of kv without predefined schema.

I wonder whether I can intercept `async-graphql` to do such thing while keeping everything else in tact. Thanks in advance!

**Comment by sunli829** [comment]
There is currently no way to support dynamic schema, which conflicts with the async-graphql architecture.

**Comment by phungleson** [comment]
Thanks, I had a look at few examples in `async-graphql` wonder if I can do something like this instead?

```
mutation {
  create(name: '', object: { id: ''... }) {
  }
}
```

Again `object` hopefully can be dynamic?

**Comment by phungleson** [comment]
Ok, I managed to get that code working with some code like this

```rust
async fn create(
    &self,
    ctx: &Context<'_>,
    #[graphql(desc = "name")] name: String,
    #[graphql(desc = "object")] object: HashMap<String, String>,
) -> Option<String> {
```

I wonder if there is way to map object to some sort of `struct` with some sort of validation, instead of `HashMap`?

**Comment by sunli829** [comment]
> Ok, I managed to get that code working with some code like this
> 
> ```rust
> async fn create(
>     &self,
>     ctx: &Context<'_>,
>     #[graphql(desc = "name")] name: String,
>     #[graphql(desc = "object")] object: HashMap<String, String>,
> ) -> Option<String> {
> ```
> 
> I wonder if there is way to map object to some sort of `struct` with some sort of validation, instead of `HashMap`?

If your type implements `Serialize`, then you can use the `Json` type.

```rust
async fn create(
    &self,
    ctx: &Context<'_>,
    #[graphql(desc = "name")] name: String,
    #[graphql(desc = "object")] object: Json<MyObj>,
) -> Option<String> {
```

**Comment by phungleson** [comment]
Awesome thanks for such a great library, it looks simple but yet does quite a lot of things.

Btw, as I am still exploring the library, just want to check for some ideas and gotchas.

As it does quite a lot of things automatically, is there any significant performance penalty or tweaks that I should be aware of?

Any recommendation in terms of libraries (servers, serialization, validation etc..) for `async-graphql`?

This can be a weird question but well anyway `async-graphql`seem to work with `json`, any chance this can work with other serialization standard like protobuf or flatbuffer...

**Comment by sunli829** [comment]
I'm sorry I don't know how to answer this question, but one thing is certain, this is currently the fastest asynchronous GraphQL library (not limited to Rust).

**Comment by phungleson** [comment]
No worries, thanks a lot, I still love to make the dynamic schema work, will read more about `async-graphql`

**Comment by phungleson** [comment]
Or at least rename the response to match with `name`

**Comment by sunli829** [comment]
> Or at least rename the response to match with `name`

This is not possible, `Async-graphql` is a performance-oriented static GraphQL framework. 🙂

**Comment by phungleson** [comment]
Thanks @sunli829 do you imply any dynamic binding will slowdown the system?

I mean in the end it probably boil down to networking and serialization, etc.. which probably be the same for both approaches?

Well unless something like models and routes are all statically compiled which might make the difference?

A bit long shot but any thoughts on anything like hot reload? apologies I have no idea where it is now in Rust.

**Comment by phungleson** [comment]
Hey @sunli829 , actually graphql specs do mention about [alias](https://graphql.org/learn/queries/#aliases) do we have similar concept here?

**Comment by phungleson** [comment]
Ok I managed to do the alias so it seems good enough for my use case.

I am still keen to understand the performance implications or any possible work around.

**Comment by sunli829** [comment]
> Ok I managed to do the alias so it seems good enough for my use case.
> 
> I am still keen to understand the performance implications or any possible work around.

In fact, the dynamic schema is completely different from the current static schema implementation, and it is difficult to merge them together.

**Comment by sunli829** [comment]
If I didn't understand it wrong, what you actually need is a dynamic schema, which can implement graphql queries like `Hasura`, but `Async-graphql` cannot.
