### ISSUE TITLE
Simple AWS Lambda example

### ISSUE THREAD

**Issue by danjenson** [async-graphql/async-graphql#344]
I know there used to be a simple AWS Lambda example -- is there current version of this? I haven't seen it in the codebase or on any other issues. Thanks!

**Comment by sunli829** [comment]
It is easy to integrate `Async-graphql` into Lambda, the following document has a very detailed guide.

https://github.com/async-graphql/async-graphql/blob/master/integrations/README.md

**Comment by danjenson** [comment]
Forgive me if I'm missing something, but I don't see anything in there in using the aws lambda runtime? I also have this issue open with aws-lambda-runtime for supporting async functions -- https://github.com/awslabs/aws-lambda-rust-runtime/issues/268. Apologies If I am completely missing something here

**Comment by danjenson** [comment]
One problem appears to be that with `tokio = { version = "0.2", features = ["macros"] }`, I get a core dump when trying to initialize the schema in a lambda: `let schema = Schema::new(QueryRoot, MutationRoot, EmptySubscription)`, but it works fine with async std and the tide integration as a  stand alone server.

**Comment by sunli829** [comment]
Can you provide a test case that can reproduce this problem?

**Comment by danjenson** [comment]
So it turned out that this was caused by futures::TryFutureExt, which was used in my mutations. Apparently this causes the runtime inside the lambda environment to crash (probably something to do with using tokio = 0.3 with a compatibility layer for tokio 0.2). Closing
