### ISSUE TITLE
How to access to GraphQLResolveInfo 

### ISSUE THREAD

**Issue by AurelienFT** [async-graphql/async-graphql#346]
Hello,

I would like to access to `GraphQLResolveInfo` it is specified in the graphql website here : https://graphql.org/learn/execution/#root-fields-resolvers

It should contains all informations about the query calls such the fields requested in the return. I want to access to it to fetch in database only fields that are required by the call.

Can I access to it and I missed how to do it ? Or it's not implemented in the crate ?

**Comment by sunli829** [comment]
I think it can be solved with `Context::look_ahead()`.

**Comment by AurelienFT** [comment]
Ok Thank you for the answer.

@sunli829 Do you think it will be a grate think to implement a method to retrieve the whole fields with a return type like this ? 
```rust
struct FieldReturned {
   name: String,
   subfields: Option<Vec<FieldReturned>>
```

**Comment by timcole** [comment]
Hello, this something I’m also very interested in. I would like to get a list of requested fields so I can query our cache and databases more effectively.  I do have a hack solution using look_ahead but it’s not really intuitive.

**Comment by sunli829** [comment]
You are right, I will add this feature as soon as possible. 🙂

**Comment by sunli829** [comment]
@AurelienFT @timcole I added the `Context::field` function in `v2.1.6` to get the current field and then get the current selection set through it.

https://github.com/async-graphql/async-graphql/blob/0346b18e2f6cad7525164d5f216b2059ce6f683c/src/context.rs#L617

**Comment by timcole** [comment]
Hey @sunli829, this is exactly what I was looking for.
Just tested it and it works great for what I need; Thank you! 😌

**Comment by AurelienFT** [comment]
Thanks a lot for your fast answer and implement. As always you are so available. @sunli829
