### ISSUE TITLE
GraphQL over websockets

### ISSUE THREAD

**Issue by fbucek** [async-graphql/async-graphql#348]
Assume there is server and client which is not accessible from server.
Client device in customer building. 

Server has GraphQL mutation `status` -> which every client send to server.
Frontend using `yaw`  is connected to `subscription` and every `status` send from client is shown in html page immediately thanks to `async_graphql` and its `subscription` implementation using `actix_web`.

So async_graphql works perfect for this purpose. 

But how to communicate back and to call GraphQL on client?

Is this approach possible?
- client connect to server using websockets.
- server sends GraphQL query/mutation to client using websockets, client execute GraphQL and sends result back?

**Comment by sunli829** [comment]
If I understand correctly, what do you hope is that the server can request data from the client?
The problem now is that `Async-graphql` needs to be compiled to `wasm`, but I have not tried this. If this can be solved, nothing else is a problem.

**Comment by fbucek** [comment]
Yes I want to request data from client/device. But it is not wasm client. I mixed more then needed. I have arm device, and server on x86 linux.
Communication device -> graphql -> server -> subscription -> browser ( user ): Works perferctly 👍 
Communication back: browser ( user ) -> server -> graphql -> client ( behind fw ) : does not work because of firewall.

To be able to communicate back and to control device/client from browser I need to setup websocket server-client connection. And communicate using this channel.

As I am investigating examples. Is this approach correct ( I have not done it yet / not enough time ) 
- Receive message using websocket
- do something like: `schema.execute(req.into_inner()).await.into()` ( from: https://github.com/async-graphql/examples/blob/71d7318ca5bd5f9b77ffc7136990c80db35a2b46/actix-web/subscription/src/main.rs#L9 )
- send results back.

Is that it? Or am I missing something? 

Thanks your time! `async_graphql` is really amazing! ( switched from juniper )

**Comment by sunli829** [comment]
In fact, you can define your own WebSocket-based protocol. When the server sends a request, the client calls the `Schema::execute` function to get the result of the query and returns the result to the server. This is easy.

**Comment by sunli829** [comment]
> In fact, you can define your own WebSocket-based protocol. When the server sends a request, the client calls the `Schema::execute` function to get the result of the query and returns the result to the server. This is easy.

Your understanding is completely correct. 👍🏻

**Comment by fbucek** [comment]
Thanks for help. Closing.

**Comment by leebenson** [comment]
In case it's helpful, we implemented a custom subscription client in [Vector](https://vector.dev).

You might be able to take some inspiration from it:

https://github.com/timberio/vector/blob/master/lib/vector-api-client/src/subscription.rs
