### ISSUE TITLE
The ability to collect fields from both SimpleObject and Object.

### ISSUE THREAD

**Issue by ruseinov** [async-graphql/async-graphql#35]
Here's an example: I have an object that has 10 fields, only one of which would need to be defined as a custom Scalar. But in order to expose this object's fields I would have to actually create a getter for each of it's fields. Or otherwise I'd have to use a gql scalar type within my business logic and the database layer, which would also be somewhat painful.

**Comment by ruseinov** [comment]
One other solution for that would be to have a macro that would autogenerate getters for each field with ability to override somehow?

**Comment by sunli829** [comment]
I haven't thought of a good way to generate getters automatically, the only way to do it now is use a procedural macro include `SimpleObject` and `Object` to get the information I need to generate the code,  I think it's pretty ugly.

```rust
gql_obj! {

#[SimpleObject]
struct MyObj {
   a: i32,
   b: i32,
}

#[Object]
impl MyObj {
    async fn c(&self) -> i32 {
      ...
    }
}

}
```


```

**Comment by ruseinov** [comment]
Yeah, it sure is. 

One other option would be to allow getting fields from both simpleObj and Obj with the ability to exclude and override I guess. Can't think of anything cleaner atm, but definitely worth investigating to avoid doing the getters thing every time.

One other thing that came to mind is the ability to switch default behaviour in terms of field inclusion/exclusion, for simple/objects. As in include all by default, but allow to optionally do exclude all and then do includes. This is not very important though if it makes the code way too complex.

**Comment by sunli829** [comment]
I doubt this is possible in the rust language unless I create a DSL with a macro, which would make the ide's auto-complete and formatting unavailable, which is not what I want.

**Comment by ruseinov** [comment]
Right, yeah, it's an interesting problem.

I'm wondering if the macro defined on `impl` has access to any of the fields in the struct? The idea here is that we might not even need to support using both macros at the same time as long as we can use #[Object] and tell it to do the struct work too.

**Comment by ruseinov** [comment]
Speaking of getters: this seems like a good enough solution for those types that automatically translate to graphql and back: https://docs.rs/crate/derive-getters/0.1.0 . The rest can be ignored and implemented manually.

**Comment by ruseinov** [comment]
So it is possible to generate getters and setters, I just with I could somehow manage to mark that `impl` that's being generated as `Object`. 

async-graphql might benefit from something like that, because that kinda solves this particular issue we are discussing here.

**Comment by nicolaiunrein** [comment]
Yeah had the same Idea as well. Well you could rewrite derive-getters that annotates the impl with Object but how are you going to extend that impl then? Can you have more than one impl block  at a time annotated with Object? Otherwise this is kinda pointless isn’t it?

**Comment by sunli829** [comment]
I have found a way to implement this feature and am trying it out.

**Comment by sunli829** [comment]
Sorry everyone, I still can't do it.
