### ISSUE TITLE
It does not correctly recognize the mime type of a file

### ISSUE THREAD

**Issue by benjamingb** [async-graphql/async-graphql#351]
## Expected Behavior

I am uploading images
```rust
let info = FileInfo {
            id: entry.key().into(),
            filename: upload.filename.clone(),
            mimetype: upload.content_type,
        };
```

I took an image and put it as a **.txt** extension, and when loading it the mimetype shows me ` "text/plain"`  I expected it to be
 `"image/jpeg"`

## Actual Behavior
```
{
  "data": {
    "multipleUpload": [
      {
        "filename": "test.txt",
        "id": "0",
        "mimetype": "text/plain",
      }
    ]
  }
}
 ```
## Steps to Reproduce the Problem
Upload image file with the extension changed, example **.txt**

## Specifications

- Version: rustc 1.48.0 (7eac88abb 2020-11-16)
- Platform: Linux

**Comment by sunli829** [comment]
Is this a bug? You have changed the file name to `.txt`, of course the mimetype will be `text/plain`. 😂

**Comment by benjamingb** [comment]
Excuse me, but I understand that the Mime types are not related to the extension.

Example in linux uses the mimetype to determine the type of file and not the extension 
```
$ file --mime-type -b image.txt 
image/jpeg

```
**In Java**
````
Path path = new File("product.txt").toPath();
String mimeType = Files.probeContentType(path);
 
assertEquals(mimeType, "image/png"); // true 
```

**In PHP**
```
echo mime_content_type('image.txt')  // image/jpg
``` 
Etc
 

Excuse me if i'm wrong

**Comment by sunli829** [comment]
In fact, `Async-graphql` only uses the `mimetype` reported by the HTTP client as the `mimetype` of the file, and does not parse the file header to obtain the true type of the file.

**Comment by sunli829** [comment]
I will close this issue, please feel free to open it if you have any questions.
