### ISSUE TITLE
Remove `From` impl for async_graphql::Error

### ISSUE THREAD

**Issue by cottinisimone** [async-graphql/async-graphql#354]
## Description of the feature
I was trying to use graphql extensions to specialize my errors. In order to use the `?` operator i need to implement a From<T> for async_graphql::Error, that is already implemented.
 
So would be cool for me to remove the `impl<T: Display> From<T> for Error` trait implementation in order to let the caller decide how to implement the trait. At the moment (of course) i get `conflicting implementations of trait` error

## Code example (if possible)
Simply remove
```rust
impl<T: Display> From<T> for Error {
    fn from(e: T) -> Self {
        Self {
            message: e.to_string(),
            extensions: None,
        }
    }
}
```
from `src/error.rs`

A code example to show the need:

```rust
#[derive(Debug, Error)]
pub enum MyErrorWithThiserror {
    #[error("{0} - {1}")]
    Error1(String, String),

    #[error(transparent)]
    Error2(#[from] std::io::Error),
}

impl MyErrorWithThiserror {
    pub fn message(self) -> String {
        match self {
            Self::Error1(description, _) => description,
            Self::Error2(err) => err.to_string(),
        }
    }

    pub fn extension<T: Into<String>, U: Into<async_graphql::Value>>(self) -> Option<Vec<(T, U)>> {
        match self {
            Self::Error1(_, reason) => Some(vec![("reason", reason)]),
            Self::Error2(_) => None,
        }
    }
}

impl From<MyErrorWithThiserror> for async_graphql::Error {
    fn from(error: MyErrorWithThiserror) -> Self {
        async_graphql::Error::new(error.message()).extend_with(|_, e| {
            error
                .extension()
                .map(|ext| ext.into_iter().for_each(|(key, value)| e.set(key.into(), value.into())));
        })
    }
}
```

Thank you in advance

**Comment by Koxiaet** [comment]
Removing it would be a breaking change and would make the library harder to use. Most code would have to change from `?` to `.map_err(async_graphql::Error::new)?` or something, which really isn't ideal.

You could make a method `MyErrorWithThiserror::into_graphql` and write `.map_err(MyErrorWithThiserror::into_graphql)?; until we get specialization I don't know if there's a better way.

**Comment by cottinisimone** [comment]
Thank you for the fast reply.

This is, at the end, exactly what i did. But IMHO this solution it's just a fix because not idiomatic, more verbose and more error prone being that a misuse of `?` wouldn't be marked as error by the compiler.

Maybe could be included in the next major release?

**Comment by Koxiaet** [comment]
I'm still opposed to removing it - making the general case so much more verbose simply isn't worth it in my opinion. If you know a way to keep supporting converting any error to `async_graphql::Error` while still allowing user types to both implement `Display` and `From` for `async_graphql::Error`, I'd definitely use it, but otherwise the benefits don't outweigh the costs.

**Comment by cottinisimone** [comment]
Ok. Thanks for your time

**Comment by Koxiaet** [comment]
Once Rust gets specialization in several years we might be able to reopen this, but since we can't do anything about it now I think it should be closed.

**Comment by nicolaiunrein** [comment]
As I'm the original author of the error extensions part of the crate let me explain my intend and give a possible solution. I’m on mobile so forgive if the below code is not working but it was originally supposed to be used something like this: 
```rust
Err(my_error.message().extend_with(my_error.extensions()))
```
or directly on results with `ResultExt`

So no need for manual implementation of the `From` trait. The downside of this is that one could forget to attach the extensions.

**Comment by nicolaiunrein** [comment]
I am reopening since I have an idea how to achieve what you want without breaking changes.

**Comment by nicolaiunrein** [comment]
`From<MyError> for Error` is not intended to be ever implemented by the user. Instead convert your error by calling extend on them. This works because `ErrorExtensions` is implemented for all `T where &T: Display` allowing custom implementations for owned `T`s. Check David Tolnay's [case-study](https://github.com/dtolnay/case-studies/blob/master/autoref-specialization/README.md) on the topic if you are interested.

You can achieve what you want like so:
```rust
use async_graphql::Error;
use async_graphql::ErrorExtensions;
use thiserror::Error;

#[derive(Debug, Error)]
pub enum MyErrorWithThiserror {
    #[error("{0} - {1}")]
    Error1(String, String),

    #[error(transparent)]
    Error2(#[from] std::io::Error),
}

#[derive(Debug, Error)]
pub enum MyErrorWithoutExtensions {
    #[error("{0}")]
    Simple(&'static str),
}

impl MyErrorWithThiserror {
    pub fn message(&self) -> String {
        match self {
            Self::Error1(description, _) => description.clone(),
            Self::Error2(err) => err.to_string(),
        }
    }

    // I removed the trait bounds as they are not neccessary and in fact lead to compilation issues
    // because `ErrorExtensionValues::set` is already generic over these types and thus the
    // compiler can not infer the types. If it is not neccessary to remove these bounds you need to
    // call into on them inside the implementation of the `ErrorExtensions` trait.
    pub fn extension(&self) -> Option<Vec<(&'static str, &str)>> {
        match self {
            Self::Error1(_, reason) => Some(vec![("reason", reason)]),
            Self::Error2(_) => None,
        }
    }
}

// Instead of manually implementing `From<MyErrorWithThiserror> for Error` just implement the
// `ErrorErrorExtensions` trait directly. It is designed to handle specialization for cases like
// yours.
impl ErrorExtensions for MyErrorWithThiserror {
    fn extend(&self) -> Error {
        let message = self.message();
        let extensions = self.extension();

        async_graphql::Error::new(message).extend_with(|_, e| {
            extensions.map(|ext| {
                ext.into_iter()
                    .for_each(|(key, value)| e.set(key, value.clone()))
            });
        })
    }
}

#[cfg(test)]
mod test {
    use std::fmt::Display;

    use super::*;
    use async_graphql::ErrorExtensionValues;
    use async_graphql::ErrorExtensions;

    #[test]
    fn it_has_extensions() {
        let orig = MyErrorWithThiserror::Error1("Message".to_owned(), "Extension".to_owned());

        // Now instead of converting the error with `Into` or `?` just call extend on it. Which
        // will do the conversion in the background.
        let converted: Error = orig.extend();

        let mut extensions = ErrorExtensionValues::default();
        extensions.set("reason", "Extension");

        assert_eq!(
            converted,
            Error {
                message: "Message".to_owned(),
                extensions: Some(extensions)
            }
        );
    }

    #[test]
    fn it_works_without_extensions() {
        let orig = MyErrorWithThiserror::Error1("Message".to_owned(), "Extension".to_owned());

        // The conversion is already implemented by `async_graphql`. So calling into (or using ?)
        // also works but gives an error without extensions.
        let converted: Error = orig.into();

        assert_eq!(
            converted,
            Error {
                message: "Message - Extension".to_owned(),
                extensions: None
            }
        );
    }
}
```

I hope it helps.
