### ISSUE TITLE
Mix of simple and complex object

### ISSUE THREAD

**Issue by AurelienFT** [async-graphql/async-graphql#355]
Hello,

I have a question about what is the best way to use the crate. I have an structure filled from my database so it's a `SimpleObject` because there is no complex operations to perform. Example : 
```
#[SimpleObject]
struct Author {
 id: String,
 username: String,
 password: String
}
```

I also have query and mutations for CRUD operations on this structure.

Now imagine that I want to allow the user of my API to get the books of the authors which are not linked in the database, I see two solutions but maybe I miss some : 

- Change the Simple Object to Object : 
```
#[Object]
impl Author {
 async fn id(&self) -> String {
  self.id
 }
 async fn username(&self) -> String {
   self.username
 }
 async fn password(&self) -> String {
  self.password
 }
 //new fetch : books
 async fn books(&self) -> String {
   get_database_books()
 }
}
```
Is that a valid solution ? But it add so much syntax just for 1 complex field.

- Add a check in the query

```
impl Query {
  async fn get_author(id: String) {
  get_author_database(id);
  if ctx.selection_field... == 'books' {
    get_database_books()
  }
}
``` 
Is that a valid solution ? But the problem is that I need to make it in all query ? And it don't break like [directive](https://github.com/async-graphql/async-graphql/blob/master/tests/directive.rs) ?

What do you think about the solutions and do you have a better one ?

Thanks for reading

**Comment by sunli829** [comment]
Adding a `getter` property to the `Object` macro is the best way I can think of so far. What do you think?

```rust
struct Author {
 id: String,
 username: String,
 password: String
}

#[Object(getter(id, username, password))]
impl Author {
 //new fetch : books
 async fn books(&self) -> String {
   get_database_books()
 }
}
```

**Comment by sunli829** [comment]
This cannot be achieved, and at the same time I did some other attempts, but still can't, so I will close this PR.

**Comment by sunli829** [comment]
I looked for a solution a few months ago, so if I find a solution to this problem in the future, I will open it again. 😁

**Comment by AurelienFT** [comment]
@sunli829 Hello, Thanks for your answer. I'm sad your answer can't be done it will be great.

But in my issue I was also asking what is the best to do with the actual state of the package. If you have an anwser on that it will be very cool.

**Comment by sunli829** [comment]
This is currently the most correct solution. 👍

```rust
#[Object]
impl Author {
 async fn id(&self) -> String {
  self.id
 }
 async fn username(&self) -> String {
   self.username
 }
 async fn password(&self) -> String {
  self.password
 }
 //new fetch : books
 async fn books(&self) -> String {
   get_database_books()
 }
}
```

**Comment by AurelienFT** [comment]
Ok thank you ! :)

**Comment by AurelienFT** [comment]
@sunli829 I have look at the expanded code of the macro and when we make a `SimpleObject` it expand to a declaration with a simple impl like if we writed the basic resolvers ourself  for example :
```
impl Author {
async fn id(&self) -> String {
  self.id
 }
 async fn username(&self) -> String {
   self.username
 }
 async fn password(&self) -> String {
  self.password
 }
}
```
Is that possible that we add a option in the `graphql` helper attribute for each field with a name like `complex_resolver` and if it is set by the user the macro don't add the method in the  implementation generated and it's the user that need to declare it himself. Is that possible to have a solution like that ? I could try to implement it if you think it's possible.

**Comment by sunli829** [comment]
> @sunli829 I have look at the expanded code of the macro and when we make a `SimpleObject` it expand to a declaration with a simple impl like if we writed the basic resolvers ourself for example :
> 
> ```rust
> impl Author {
> async fn id(&self) -> String {
>   self.id
>  }
>  async fn username(&self) -> String {
>    self.username
>  }
>  async fn password(&self) -> String {
>   self.password
>  }
> }
> ```
> 
> Is that possible that we add a option in the `graphql` helper attribute for each field with a name like `complex_resolver` and if it is set by the user the macro don't add the method in the implementation generated and it's the user that need to declare it himself. Is that possible to have a solution like that ? I could try to implement it if you think it's possible.

This is absolutely possible, the signature of the function must be like this:

```rust
fn(&impl OutputType, &Context<'_>) -> impl OutputType
```

Use it like this:

```rust
#[derive(SimpleObject)]
struct MyObj {
     a: i32,

     #[graphql(resolver = "get_b")]
     b: i32,
}

async fn get_b(obj: & MyObj, ctx: ctx: &Context<'_>) -> i32 {
     // returns resolved value
}
```

**Comment by AurelienFT** [comment]
@sunli829 Yes it's strange because we will need to add value but it will be returned because the resolver will be trigger. I think we can document it and maybe accept only field with `Option` and if the `Option` is set to None the resolver trigger otherwise it just return the value. What do you think about it ?

Moreover, I think you can reopen this because we can find a good solution to implement it.

**Comment by sunli829** [comment]
How does this look?

```rust
#[derive(SimpleObject)]
#[graphql(complex)]
struct MyObject {
    a: i32,
    b: i32,
}
```

#[derive(ComplexObject)]
impl MyObject {
    async fn c(&self) -> i32 {
        self.a + self.b
    }
}
```

**Comment by AurelienFT** [comment]
@sunli829 I definitively  like it ! It answer perfectly to my use cases.

**Comment by sunli829** [comment]
I will add this feature these days.

**Comment by sunli829** [comment]
Released in `v2.6.0`

**Comment by AurelienFT** [comment]
@sunli829 The context is not in the resolver prototype is that a forget in the example or it's not implemented ? Because the context  is useful to have I think.

**Comment by sunli829** [comment]
It's just that the example doesn't use context.😄

**Comment by AurelienFT** [comment]
Ok yes my bad thank you for your fast implementation you are really good !
