### ISSUE TITLE
Selection field nested fields

### ISSUE THREAD

**Issue by AurelienFT** [async-graphql/async-graphql#359]
## Expected Behavior
Have all nested fields in the selection_set.

## Actual Behavior
Got only the top level field

## Steps to Reproduce the Problem

1. Try this use case : https://github.com/async-graphql/async-graphql/blob/0346b18e2f6cad7525164d5f216b2059ce6f683c/src/context.rs#L611

This will give you only  `object` and not `object a b c`

## Specifications

- Version: 2.4.3
- Platform: PC/Linux
- Subsystem: Ubuntu

**Comment by sunli829** [comment]
This is not a bug, you can continue to call `SelectionField::selection_set` to get a deeper list of fields.

https://github.com/async-graphql/async-graphql/blob/0346b18e2f6cad7525164d5f216b2059ce6f683c/src/context.rs#L604

**Comment by AurelienFT** [comment]
I don't understand.

Imagine I have a query `getAllUsers { users { id name }}`.

How it's possible to have all fields and subfields in the same vec ?

**Comment by AurelienFT** [comment]
Ok I think I understood. I need to make a recursion. Now I need to figure out how xd
