### ISSUE TITLE
How to get the requested fields?

### ISSUE THREAD

**Issue by phungleson** [async-graphql/async-graphql#364]
Hi,

I have a query like this

```
{
    stores {
        id
        name
    }
}
```

How can I get `id`, `name` in the resolver so that I can use them to request to the database?

I also wonder if is even a good practice? It might be a bit more performant in terms of what to query from database but might introduce other complication like injection?

**Comment by sunli829** [comment]
This is a very common optimization, you can use `Context::look_ahead` or `Context::field` to get the fields in the selection set.

**Comment by phungleson** [comment]
Thanks Sunli, sorry one thing leads to another.

I am trying to use `look_ahead` and `field` but cannot print them out to test since they don't `impl` `Display` nor `Debug`, do you have anything suggestion for me to inspect the object to test further?

**Comment by sunli829** [comment]
> Thanks Sunli, sorry one thing leads to another.
> 
> I am trying to use `look_ahead` and `field` but cannot print them out to test since they don't `impl` `Display` nor `Debug`, do you have anything suggestion for me to inspect the object to test further?

`field` can support `Debug`, I will add it tomorrow. 🙂

**Comment by sunli829** [comment]
Release in `v2.4.4`.

**Comment by phungleson** [comment]
Thanks Sunil, I managed to use this by `ctx.lookahead().field().exists()` a bit tedious but it works.

One thing though, it looks like `field()` is accepting `camelCase` while most of the code is `snake_case` is there anyway to automatically allow `field("snake_case")`?

Or users need to DIY with some thing like `convert_case`?

Thanks again for all your help, cheers

**Comment by sunli829** [comment]
> One thing though, it looks like field() is accepting camelCase while most of the code is snake_case is there anyway to automatically allow field("snake_case")?

For some reasons, this cannot be achieved. 🙂

**Comment by phungleson** [comment]
Alright thanks @sunli829

**Comment by onx2** [comment]
Is there a way to get all fields from the request? 

@phungleson are you manually checking for each field in the resolver to build the query?

I'm trying to figure out if there is a way to do something like this:
- Get all fields from `ctx`
- Filter those fields into the defined struct
- Pass those fields into the query `select`

Though I'm not sure how this would work with relationship fields. 🤔 

Essentially I'm trying to prevent a `select * from table_name`, but rather use something like `select id, name, etc from some_table` based on the ctx fields.
