### ISSUE TITLE
Anonymous struct

### ISSUE THREAD

**Issue by phungleson** [async-graphql/async-graphql#365]
Sorry I have another question.

I am using `sqlx::query!` and it creates an anonymous struct based on the query.

https://github.com/launchbadge/sqlx/blob/1ed75ba5f03ad9e4ee04ffd362c8bda2b4857562/src/macros.rs#L278

Looks like I cannot use that struct directly in to the returned value of resolvers?

**Comment by sunli829** [comment]
> Sorry I have another question.
> 
> I am using `sqlx::query!` and it creates an anonymous struct based on the query.
> 
> https://github.com/launchbadge/sqlx/blob/1ed75ba5f03ad9e4ee04ffd362c8bda2b4857562/src/macros.rs#L278
> 
> Looks like I cannot use that struct directly in to the returned value of resolvers?

If it is a dynamic object and the internal fields are uncertain, you can only use `async_graphql::Json`.

**Comment by phungleson** [comment]
Yeah cool thanks! looks like `async_graphql::Json` needs a type parameter?

I still get an error even if I try to supply something, it still doesn't work.

```
mismatched types
expected struct `Vec<async_graphql::Json<Store>>`
   found struct `Vec<store::Query::stores::{closure#0}::Record>`rustcE0308`
```

I guess probably not a good idea to use anonymous struct.

**Comment by sunli829** [comment]
> Yeah cool thanks! looks like `async_graphql::Json` needs a type parameter?
> 
> I still get an error even if I try to supply something, it still doesn't work.
> 
> ```
> mismatched types
> expected struct `Vec<async_graphql::Json<Store>>`
>    found struct `Vec<store::Query::stores::{closure#0}::Record>`rustcE0308`
> ```
> 
> I guess probably not a good idea to use anonymous struct.

What you want should be a dynamic schema, this `async-graphql` is not supported.

**Comment by phungleson** [comment]
Yeah thanks, I will look around further
