### ISSUE TITLE
Skip in remote Enum

### ISSUE THREAD

**Issue by benjamingb** [async-graphql/async-graphql#368]
Is there a way to skip an element of a remote enum?

```
#[derive(Enum, Copy, Clone, Eq, PartialEq)]
#[graphql(remote = "PaymentStatus")]
enum PaymentStatus {
    Paid,
    InProcess,
    #[graphql(skip)]
    Withheld,
}
```

**Comment by sunli829** [comment]
> #[derive(Enum, Copy, Clone, Eq, PartialEq)]
> #[graphql(remote = "PaymentStatus")]
> enum PaymentStatus {
>     Paid,
>     InProcess,
>     #[graphql(skip)]
>     Withheld,
> }

This is not easy to implement, because it will cause inconsistent values in the two enumerations.
I recommend hiding this field in introspection.

```rust
#[derive(Enum, Copy, Clone, Eq, PartialEq)]
#[graphql(remote = "PaymentStatus")]
enum PaymentStatus {
    Paid,
    InProcess,
    #[graphql(visible = false)]
    Withheld,
}
```

**Comment by benjamingb** [comment]
it worked! thanks!
