### ISSUE TITLE
derive Copy for ID

### ISSUE THREAD

**Issue by phungleson** [async-graphql/async-graphql#369]
First of all Happy New Year to repo maintainers! Thank you for creating such easy to use library. Wish you all a great new year!

I am writing quite a bit of tests and need to pass `ID` around across different queries, I wonder if any technical reasons we don't have `derive Copy for ID` ? Currently I have to `id.to_string()` then `ID(string)`  back.

**Comment by sunli829** [comment]
> First of all Happy New Year to repo maintainers! Thank you for creating such easy to use library. Wish you all a great new year!
> 
> I am writing quite a bit of tests and need to pass `ID` around across different queries, I wonder if any technical reasons we don't have `derive Copy for ID` ? Currently I have to `id.to_string()` then `ID(string)` back.

Thank you and wish you a happy new year!

I implemented `From<T: Display>` for `ID` type, so there is no need to convert to `string` first, you can call `into` directly.

**Comment by phungleson** [comment]
Thanks @sunli829 `into` is nice.

I am a bit new here, just wondering what the reason for `ID(String)` instead of `ID(&str)`? i.e. feel wasteful to allocate a `String` all the time?

**Comment by sunli829** [comment]
Because it needs to support conversion from `i32`, `i64` and other types to `ID`, converting `&str` to `ID` does require additional memory allocation, but this will make the `ID` type easier to use.
