### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by phungleson** [async-graphql/async-graphql#371]
Hi,

I am trying to send data from server to client, probably through pagination or some sort of cursor limit or ws subscription. I wonder if the lib has some sort of built in functionalities or examples so that I can get as a reference to avoid any possible mistakes?

Thanks,

**Comment by sunli829** [comment]
The following example should help you:

https://github.com/async-graphql/async-graphql/blob/6cb80063e95e320ad9256ac12590e2503c138c1f/src/types/connection/mod.rs#L93
