### ISSUE TITLE
Custom input and output object

### ISSUE THREAD

**Issue by phungleson** [async-graphql/async-graphql#372]
Hi,

I am at the point where I would like to receive and send back some flexible data. I understand that Sunli has mentioned before that this lib is more for static typing. But I read some code and wonder if some sort of `Json` or `BTreeMap` type can work?

Ok for the output first, for example I have a query like this

```
{
  store {
    tags
  }
}
```

I expecting the data send back to be like this

```
{
  "data": {
    "store": {
      "tags": {
        "Location": "221B Baker Street",
        "Reviews": 4.5,
        "Opening Hours": "7am",
        "Bookmarked": true
      }
    }
  }
}
```

I fully understand that I can straighten this out and put this into a `struct` but I am really looking for a way to solve this dynamically.

I read through the code and see some areas might be related but my limited knowledge about this lib doesn't help much.

There some way to do it with custom scalars but looks like it is for input onl?y

https://github.com/async-graphql/async-graphql/blob/9f1de91b8a548ef71799acd1f86e5fe09f0d7a39/docs/en/src/custom_scalars.md

https://github.com/async-graphql/async-graphql/blob/e29b7a3627eb4598e8456dc40118e0cfb3aa9820/src/resolver_utils/scalar.rs#L94-L106

And there is a struct `Json` but what is `T` my `Tags` should always have string key so probably works?

https://github.com/async-graphql/async-graphql/blob/e29b7a3627eb4598e8456dc40118e0cfb3aa9820/src/types/json.rs#L14-L19

My `Store` looks like this

```
#[derive(SimpleObject)]
pub struct Store {
    ...
    tags: ...something...<String, Value>?,
}

# it asks me for impl Type and impl OutputType, but I don't know how to solve it yet
enum Value {
  Integer(i32),
  Text(String),
  Boolean(bool),
}
```

I also see something for `HashMap` and `BTreeMap` but couldn't find a way to use them without some examples.

https://github.com/async-graphql/async-graphql/blob/e29b7a3627eb4598e8456dc40118e0cfb3aa9820/src/types/external/json_object/hashmap.rs#L7-L12

https://github.com/async-graphql/async-graphql/blob/e29b7a3627eb4598e8456dc40118e0cfb3aa9820/src/types/external/json_object/btreemap.rs#L7-L12

Thanks in advance for any ideas you might have for this.

**Comment by sunli829** [comment]
You can define a scalar like this, and hope it can help you.

```rust
struct Values(HashMap<String, async_graphql::Value>);

scalar!(Values);
```

**Comment by phungleson** [comment]
Right on thanks @sunli829 it works well for now, I probably need some extended features but will ask them later, thanks

**Comment by phungleson** [comment]
Hi @sunli829 I have played with this a bit more.

Wonder why `f64` is treated differently from other types.

https://github.com/async-graphql/async-graphql/blob/master/value/src/lib.rs#L198-L208

**Comment by phungleson** [comment]
Another thing is that, I am trying to do the same with input but getting some errors, probably doing something wrongly

```rust
#[derive(InputObject)]
pub struct Input {
    store_id: ID,
    tag: Value,
}
```

```
the trait bound `async_graphql::Value: async_graphql::Type` is not satisfied
required by `create_type_info`
```

**Comment by phungleson** [comment]
@sunli829 sorry for the direct mention, hope you know the answer, thanks in advance.
