### ISSUE TITLE
Best practice for union as input

### ISSUE THREAD

**Issue by chipsenkbeil** [async-graphql/async-graphql#373]
I'm trying to figure out the best way to support an enum whose values are input objects (or other enums) as part of an input object.

This comes from building out a query type and associated fields for entity-rs ([see here](https://github.com/chipsenkbeil/entity-rs/blob/main/entity/src/ent/query/mod.rs)) that I want to use as an input filter.

```rust
#[simple_ent]
struct User {
    #[ent(field)]
    name: String,

    #[ent(field)]
    age: u8,

    #[ent(edge(type = "Address"))]
    address: Id,
}

#[simple_ent]
struct Address {
    #[ent(field)]
    street: String,

    #[ent(field)]
    city: String,

    #[ent(field)]
    country: String,
}
```

There are examples of extensions to GraphQL that provide filtering like [this complex example](https://grandstack.io/docs/graphql-filtering/) or [this other using Prisma](https://www.howtographql.com/graphql-js/8-filtering-pagination-and-sorting/). Seems like GraphQL's own spec still doesn't support this (https://github.com/graphql/graphql-spec/issues/488), although there's ongoing work described at https://github.com/graphql/graphql-spec/pull/733.

I'm trying to figure out the best way to build an input type that can be used for filtering. @sunli829, do you know of any way that async-graphql is being used today to provide general-purpose filtering as input?

E.g.

```graphql
user(filter: {
    or: [
        { country: { equals: "United States" } },
        { age: { greater_than: 21 } }
    ]
}) {
    name
    age
    address {
        city
        country
    }
}
```

I'm wanting to build an integration from entity-rs to async-graphql so I can auto-generate my graphql API based on my typed entity fields and edges, including filter support for each type of entity.

**Comment by chipsenkbeil** [comment]
The only thing I can think of right now is to transform a union (enum) into an input object where every field is optional. For example...

```rust
enum Condition {
    Equals(u8),
    GreaterThan(u8),
}

// becomes

#[derive(async_graphql::InputObject)]
struct Condition {
    equals: Option<u8>,
    greater_than: Option<u8>,
}
```

**Comment by sunli829** [comment]
> The only thing I can think of right now is to transform a union (enum) into an input object where every field is optional. For example...
> 
> ```rust
> enum Condition {
>     Equals(u8),
>     GreaterThan(u8),
> }
> 
> // becomes
> 
> #[derive(async_graphql::InputObject)]
> struct Condition {
>     equals: Option<u8>,
>     greater_than: Option<u8>,
> }
> ```

I don't have any good solutions, in fact I also use the following approach. 😂

```rust
#[derive(async_graphql::InputObject)]
struct Condition {
    equals: Option<u8>,
    greater_than: Option<u8>,
}
```

**Comment by chipsenkbeil** [comment]
Looks like I'll need to generate some input objects based on typed entities. That looks like the only way to make this work right now. 😄 Hoping to share my progress soon!

**Comment by frederikhors** [comment]
@chipsenkbeil any news about this?

**Comment by chipsenkbeil** [comment]
@frederikhors not beyond what I did three years ago 😄 The library and downstream project that I worked on have both been archived and haven't needed a GraphQL server since then.

**Comment by frederikhors** [comment]
@chipsenkbeil thanks.

However, it would be very nice if you could show me how you solved the structuring of `Condition`s in Rust - with or without graphql.

Right now I'm using a (very verbose) approach like the one with entgo: https://github.com/ent/contrib/blob/master/entgql/internal/todo/ent/category/where.go.

But I would like to migrate to one struct like yours: https://github.com/async-graphql/async-graphql/issues/373#issuecomment-753752520.

Can you help me / point me in a good direction?
