### ISSUE TITLE
InputObject no longer supports deprecated fields

### ISSUE THREAD

**Issue by bryanburgers** [async-graphql/async-graphql#374]
I'm upgrading from async-graphql@1.15 to async-graphql@2.4. In the process, I discovered that there is no longer a way to deprecate a field of an input object.

Previously:

```rust
/// An input used as an example
#[async_graphql::InputObject]
#[derive(Clone)]
pub struct ExampleInput {
    /// The field that should be used
    pub real_field:  Option<String>,
    /// The field that should no longer be used
    #[field(deprecation = "Use `id` instead. Deprecated 2020-01-31.")]
    pub deprecated_field: Option<String>,
}
```

Now

```rust
/// An input used as an example
#[derive(async_graphql::InputObject, Clone)]
pub struct ExampleInput {
    /// The field that should be used
    pub real_field:  Option<String>,
    /// The field that should no longer be used
    // #[graphql(...)] // No "deprecation" available.
    pub deprecated_field: Option<String>,
}
```

I can't find a definitive part of the GraphQL spec that says that input objects must support deprecated fields. However, the standard introspection query returns `isDeprecated` and `deprecationReason` on the fields of `INPUT_OBJECTS`s so I _assume_ that deprecation is supported on input object fields.

Is this an **intentional** change or a bug?

**Comment by bryanburgers** [comment]
Follow up. It appears that input object field deprecation was specified on 3 Dec 2020, which hasn't made it into even the latest draft spec yet. graphql/graphql-spec#525

**Comment by sunli829** [comment]
This is not a bug. `InputObject` fields never support the `deprecation` attribute. Although it is allowed to be specified in `async-graphql@v1`, it will not take effect. 😁

**Comment by juanscr** [comment]
In the current draft for the following `graphql` spec, this is already integrated and a pull request has been merged to the master branch in 2022 adding the behavior suggested in this issue. Here are the relevant links:

-  [Pull request](https://github.com/graphql/graphql-spec/pull/805)
- [Deprecated directive](https://spec.graphql.org/draft/#sec--deprecated)

I suggest this issue to be opened again and reintegrate this behavior to the library once again 😄
