### ISSUE TITLE
Object inheritance?

### ISSUE THREAD

**Issue by phungleson** [async-graphql/async-graphql#375]
Hi,

It is probably anti pattern in graphql but well regardless I wonder if it is possible to returns multiple object of a similar type in the same array?

For example, I would like to return

```
{
  "stores": [store1, store2]
}
```

Where `store1 { name description url }` is an `OnlineStore` whereas `store2 { name description address }` is like a `PhysicalStore`.

**Comment by sunli829** [comment]
You can use `Interface`. 😁

**Comment by phungleson** [comment]
Op snap didn't know Rust can do this, let me dust this off

![image](https://user-images.githubusercontent.com/93457/103617443-5d9f5d00-4f82-11eb-87ba-739dc9fc8ec5.png)

**Comment by phungleson** [comment]
Kidding aside what I am looking for is probably something like this https://graphql.org/learn/schema/#union-types

**Comment by sunli829** [comment]
Maybe this can help you.

https://async-graphql.github.io/async-graphql/en/define_union.html

**Comment by phungleson** [comment]
Oh okay async-graphql also have `Interface` I thought you were joking. 🤣

Yeah union seems to be closer to what I need, thanks I will play around.
