### ISSUE TITLE
Enable `Schema::sdl()` to return Apollo Federation schema

### ISSUE THREAD

**Issue by bdrobinson** [async-graphql/async-graphql#376]
## Description of the feature
My project uses `async-graphql` to implement an apollo federated service. I'm writing a script that requires the federation SDL for my schema, but when I run `Schema::sdl()` it returns a non-federated version of the schema (ie, without the `extend` keyword and `@key` directives) which is different to the schema returned when I run the query `{ _service { sdl } }` against my server (which *does* include those extra bits).

I had a look at the code and it looks like this line is the problem - it passes the `false` flag which I think looks like it's disabling some federation-related features: https://github.com/async-graphql/async-graphql/blob/8bc33cfd4494955690f48ef8cdd2d5193b7a0ff4/src/schema.rs#L333

Would it be possible to specify that boolean flag in the `sdl()` function? Or is there another solution that would allow me to do the same?

Thanks very much – love this library!

**Comment by sunli829** [comment]
I added the `Schema::federation_sdl` function, release in `v2.4.5`.

**Comment by bdrobinson** [comment]
Amazing, thanks very much!
