### ISSUE TITLE
Remove type safety from Interface

### ISSUE THREAD

**Issue by sunli829** [async-graphql/async-graphql#38]
The type safety of the interface causes some functionality to be unavailable. I'll remove the compile-time type safety of the interface and check it when I call `Schema::new`. It doesn't have any performance loss, but there is no guarantee that a compile-time type safety, I think it is worth to do so.

**Comment by sunli829** [comment]
The side effect is improved runtime performance.😂

**Comment by phated** [comment]
I'm not very happy with this idea.

**Comment by sunli829** [comment]
If the interface field types do not match, there is now a panic at `Schema::new` and a reason is given.

The following code didn't compile well before, but it does now.

```rust
struct MyObj;

#[Object]
impl MyObj {
    async fn a(&self) -> &str {}
}

#[Interface(field(name = "a", type = "String"))]
struct MyInterface(MyObj);
```

**Comment by phated** [comment]
Panic is not desirable. I believe there is a solution that involves traits but I'm unable to work on it currently.

**Comment by sunli829** [comment]
> Panic is not desirable. I believe there is a solution that involves traits but I'm unable to work on it currently.

Thanks for your suggestion.😁 I will make a version as soon as possible and see how it works.

**Comment by phated** [comment]
@sunli829 is it possible to use a macro to add additional methods to a trait, including a default implementation? That is the solution I am considering.

**Comment by sunli829** [comment]
@phated  I'm actually hoping to solve this problem #29. I think procedural macros may not be possible.

**Comment by phated** [comment]
I am hoping to find time to understand macros better, but my other open source responsibilities are requiring my time right now.

Tomorrow I am giving a presentation on `async-graphql` and I wanted to show type safety on interfaces.

**Comment by sunli829** [comment]
@phated I tried this on a new branch.

In addition, thank you very much for the support of `async-graphql`. I was even more excited when I found out that you are the main maintainer of `glup.js`.

**Comment by phated** [comment]
🙇 Thank you! Your work on this project is amazing and I very much appreciate it! I am excited to help out more.

**Comment by nicolaiunrein** [comment]
@sunli829 I think it is a great Idea especially when it panics at application start. I never really liked the implementation of Interface. I think it is somehow reversed. Isn’t there a more natural way where Interface behaves more like a trait? So that Objects and SimpleObjects can "implement" it rather than beeing passed into the interface as struct fields? It just feels wrong and doesn’t allow shareing an interface over crate boundaries. 

@phated Is your presentation being recorded? I would love to see it.

**Comment by sunli829** [comment]
@nicolaiunrein  The interface definition is not natural, but it is simple enough to use.😁
