### ISSUE TITLE
How to select specific part of context

### ISSUE THREAD

**Issue by kennetpostigo** [async-graphql/async-graphql#380]
Hi, i've been looking at source code from the examples and another repo, and I was wondering, how to specify the slice of data on context to select? 

I think the way it works now is you select the slice of data on context by the type like so:
```rust
ctx.data::<Arc<PgPool>>().expect("Can't get pool").get().expect("Can't get DB connection")
```

In the code above does `ctx.data` know which slice of data to pick by the type after `::`?

 what if multiple slices of data on context have the same type?

**Comment by sunli829** [comment]
> Hi, i've been looking at source code from the examples and another repo, and I was wondering, how to specify the slice of data on context to select?
> 
> I think the way it works now is you select the slice of data on context by the type like so:
> 
> ```rust
> ctx.data::<Arc<PgPool>>().expect("Can't get pool").get().expect("Can't get DB connection")
> ```
> 
> In the code above does `ctx.data` know which slice of data to pick by the type after `::`?
> 
> what if multiple slices of data on context have the same type?

You can wrap it with `newtype` pattern.

```rust
struct UserId(u64);

struct RequestId(u64);

ctx.data::<UserId>()
ctx.data::<RequestId>()
```

**Comment by kennetpostigo** [comment]
@sunli829 thanks! So thats was correct to assume that you select the slice by type?

**Comment by sunli829** [comment]
Sorry, I don't quite understand what you mean. 😁

**Comment by kennetpostigo** [comment]
@sunli829 basically that you select the slice of data on context by the type of the data, so if I did:

```
ctx.data::UserId() // gets the userId on context
ctx.data::Username() // gets the username on context
```
