### ISSUE TITLE
#[Object] on impl dyn TraitObj?

### ISSUE THREAD

**Issue by chipsenkbeil** [async-graphql/async-graphql#381]
Is it possible to create an object from a trait object using the `impl dyn TraitObj` syntax?

Right now, I was trying it for a trait of mine called `Ent` that has a variety of methods available. Normally, I've got instances of Box<dyn Ent>, so I wanted to be able to support methods that return one or more `Box<dyn Ent>`.

When I do this, I get the error message `Invalid type`:

```rust
pub trait MyTrait {
    fn name(&self) -> &str;
    fn favorite_number(&self) -> u8;
}

#[async_graphql::Object]
impl dyn MyTrait {
    async fn gql_name(&self) -> &str {
        self.name()
    }

    async fn gql_favorite_number(&self) -> u8 {
        self.favorite_number()
    }
}

```

**Comment by sunli829** [comment]
This seems very useful and I will implement it immediately. 🙂

**Comment by sunli829** [comment]
@chipsenkbeil
It would be great if you can help me add the description of this feature in the book when you are free.  🙂

**Comment by chipsenkbeil** [comment]
> @chipsenkbeil
> It would be great if you can help me add the description of this feature in the book when you are free. 🙂

Will do! I'm finishing up an integration with async-graphql to my own framework as an extension, so looking forward to being able to use this feature. 😄

**Comment by sunli829** [comment]
Here is an example, thanks! 🙂

https://github.com/async-graphql/async-graphql/blob/c547252121327cd636fe52b287db31b3896e579b/src/lib.rs#L369

**Comment by sunli829** [comment]
Released in `v2.4.6`.

**Comment by chipsenkbeil** [comment]
Going to pull in `v2.4.6` to finish my extension and then I'll tackle documentation here. 😄

**Comment by chipsenkbeil** [comment]
@sunli829, I seem to be getting the same issue as before with `v2.4.6`. Here's a screenshot showing me compiling `v2.4.6` with a trait that requires Send + Sync and my `#[Object]` definition. Did I miss anything?

<img width="1366" alt="Screenshot 2021-01-10 at 00 38 44" src="https://user-images.githubusercontent.com/2481802/104116219-40e58b00-52dc-11eb-99cc-815dd66e8612.png">

**Comment by chipsenkbeil** [comment]
Nevermind, my parent `Cargo.lock` was still pulling in `v2.4.5` for some of the dependency crates like `async-graphql-derive` even though `async-graphql` was pulling in as `v2.4.6`. Clearing my lock fixed it.

**Comment by chipsenkbeil** [comment]
@sunli829, I'm trying to test my implementation and I'm getting an error: `expected executable_definition`. There was only one other task that mentioned it and didn't see a resolution that would help me here. The error is so vague that I don't know if it's a problem with my query, my context, or the string I'm passing to the schema to execute.

Here's what I've got:
- A query called `TestQuery` with a single async fn to return an `Option<Box<dyn Ent>>` given an `Id` as input and `Ent` is the trait object from the earlier screenshot
- A schema created with the `TestQuery` and context data set to `Arc<Box<dyn Database>>` where `Database` is a trait object of mine that wraps an inmemory database or a sled database
- A manual execution of the async-graphql schema using `futures::executor::block_on` to run the async job and return the result

<img width="1366" alt="Screenshot 2021-01-10 at 13 44 47" src="https://user-images.githubusercontent.com/2481802/104133685-bc7e2100-534a-11eb-8176-b5751c6349b5.png">

**Comment by flisky** [comment]
Can we support `Scalar` and `scalar!` on `dyn trait`, @sunli829 ? Is that doable ?

I tried it but failed on `sized` bound, and a plain `impl {Type,Output} for dyn trait` works :)

**Comment by sunli829** [comment]
> Can we support `Scalar` and `scalar!` on `dyn trait`, @sunli829 ? Is that doable ?
> 
> I tried it but failed on `sized` bound, and a plain `impl {Type,Output} for dyn trait` works :)

Thank you, I will see why `Scalar` cannot support `dyn Trait`.

**Comment by sunli829** [comment]
It is not possible to implement a scalar for a `?Sized` type, but you can implement `Type` and `OutputType` for it (Note: this is not a scalar, a scalar should implement both `InputType` and `OutputType`).
