### ISSUE TITLE
Is InputObject with field of Box<InputObject> valid?

### ISSUE THREAD

**Issue by chipsenkbeil** [async-graphql/async-graphql#382]
I have a scenario like this:

```rust
#[async_graphql::InputObject]
pub struct Person {
    name: String,
    child: Option<Box<Person>>,
}

```

I'd expect you could use it like this:
```graphql
{
    PersonQuery(person: {
        name: "Bob",
        child: {
            name: "Jane",
            child: {
                name: "Drew"
            }
        }
    })
}
```

But I get an error that the trait bound `Box<Person>: InputType` is not satisified

**Comment by chipsenkbeil** [comment]
This comes from me trying to define an input object filter as outlined here: https://github.com/chipsenkbeil/entity-rs/issues/23#issuecomment-757105083

I've got some reusable input objects that can nest themselves as filters, but the nesting isn't working because I need to box a recursive type.

This seems tricky because if I had the input object **without** the `Option<...>`, it would be infinite, which wouldn't make sense for an input object.

```rust
#[async_graphql::InputObject]
pub struct Person {
    name: String,
    child: Box<Person>,
}
```

**Comment by sunli829** [comment]
I need to take a break, it took too much effort to implement `Object` for `dyn TraitObject`, will add this feature later. 😂

**Comment by sunli829** [comment]
Released in `v2.4.6`.

**Comment by chipsenkbeil** [comment]
That was quick! Do we need any documentation updates for this, @sunli829?

Going to pull in `v2.4.6` to finish my extension and then I'll tackle documentation here if needed.

**Comment by sunli829** [comment]
> That was quick! Do we need any documentation updates for this, @sunli829?
> 
> Going to pull in `v2.4.6` to finish my extension and then I'll tackle documentation here if needed.

I need documentation, thanks. 🙂

**Comment by lastmjs** [comment]
I just want to say how amazing this library is, I was putting in a good amount of slightly inelegant work to get around this issue...and then I just wrapped my types in boxes and I've got my recursive input types...so awesome
