### ISSUE TITLE
Implement conversion from serde_json::Value to Any

### ISSUE THREAD

**Issue by nicolaiunrein** [async-graphql/async-graphql#39]
I would like to implement `impl From serde-json::Value for Any` which is currently blocked by graphql-parsers inability to convert from `serde_json::Value` due to mismatch of underlying types for Number. Once this [Issue](https://github.com/graphql-rust/graphql-parser/issues/32) resolves I will implement the conversion for `Any`.

**Comment by sunli829** [comment]
Any type already exists and I have added it to support Federation. Is that what you want?

**Comment by nicolaiunrein** [comment]
Yes I know and I'm using it. I wanted to implement the From trait for being able to write something like this:
```rust
let test: Any = json!({ "a": 42 }).into()
```
Which is only possible if I construct a graphql_parser::Value by hand because there is no `impl From serde_json::Value for graphql_parser::Value`. But I think I can just add `impl<T> From T for Any where T: Into<graphql_parser::Value>` which does not let you write code like the above quite yet but when the functionality is added to graphql_parser and also gives you more flexibility for other use-cases. I solved this in my code by implementing a helper trait which is kind of ugly and unnecessary. I will commit the code and it becomes clear. :laughing:

**Comment by sunli829** [comment]
Sorry I misread it, it was `serde_json::Value`, in fact I've already written an `json_value_to_gql_value` for this ugly transformation function.

https://github.com/async-graphql/async-graphql/blob/26120e24e221193b51cc40383b9bcfc4209020ba/src/context.rs#L114

**Comment by nicolaiunrein** [comment]
Yes but this is the other way around. :laughing:  I opened an issue at graphql_parser for providing the conversion but as I wrote its not trivial because of different base types on Number. Anyway I think 26120e2 solves this issue now.

**Comment by sunli829** [comment]
Many AST nodes of the `graphql_parser` don't have a position property, and I might actually create a new parser later to solve this problem.😁

**Comment by nicolaiunrein** [comment]
I think removing the dependency on graphql_parser is a good Idea!

**Comment by nicolaiunrein** [comment]
Now with the dependency removed this should be possible.
