### ISSUE TITLE
Async Websocket Initializers?

### ISSUE THREAD

**Issue by D1plo1d** [async-graphql/async-graphql#393]
## Description of the feature

Currently `async_graphql::http::WebSocket` expects a synchronous initializer function however it would be useful to allow async results from that function so that asynchronous database calls can be made to authenticate the user based on a connection init payload.

## Code example (if possible)

I'm looking for something approximately like this:

```rust
impl<S, F, Query, Mutation, Subscription> Stream for WebSocket<S, F, Query, Mutation, Subscription>
where
    S: Stream,
    S::Item: AsRef<[u8]>,
    F: FnOnce(serde_json::Value) -> Future<Result<Data>>,
    Query: ObjectType + Send + Sync + 'static,
    Mutation: ObjectType + Send + Sync + 'static,
    Subscription: SubscriptionType + Send + Sync + 'static,
{
```

**Comment by sunli829** [comment]
I added this to the master branch, please help me test it, thank you. 🙂

**Comment by D1plo1d** [comment]
Thanks again @sunli829, I've updated my codebase to master and it's compiling fine after a little hacking.

Oddly I needed to increase my type length limit to `#![type_length_limit="15873664"]` in order for my future returning initialization closure to compile. I'm not familiar with type_length_limit although it sounds fairly self descriptive - I suspect that's more an issue in my code?

Oh btw a little note of possible interest: I'm using this for something a little novel here, AFAIK this is the first `async-graphql` over WebRTC data channel implementation anyone's put together:

https://github.com/tegapp/teg/blob/feature/rust_dec_2020/crates/server/src/main.rs#L123

**Comment by sunli829** [comment]
> Oddly I needed to increase my type length limit to #![type_length_limit="15873664"] in order for my future returning initialization closure to compile. I'm not familiar with type_length_limit although it sounds fairly self descriptive - I suspect that's more an issue in my code?

I will find out the cause of this problem.

> Oh btw a little note of possible interest: I'm using this for something a little novel here, AFAIK this is the first async-graphql over WebRTC data channel implementation anyone's put together:

This is amazing! 🙂

**Comment by D1plo1d** [comment]
> This is amazing! slightly_smiling_face

Thanks! ^_^

> I will find out the cause of this problem.

Even more thanks! I [read here](https://github.com/rust-lang/rust/pull/72412) that nesting closures can cause this kind of issue with long monomorphised type names causing `type_length_limit` issues in stable Rust.

One thing I noticed that might allow us to reduce the level of nesting - because I'm expected to instantiate the `async_graphql::Data` instance inside the `data_initializer` I pass in a closure so that I can capture relevant application-scoped / not-per-request variables such as my database connection.

If `WebSocket::with_data` took a data instance and then passed it to the `data_initializer` then I wouldn't need the closure and could pass a reference to a function for the `data_initializer` instead. My hope being that this would reduce the monomorphized type length and resolve our issue. Something like this:

#### WebSocket::with_data
```rust
    pub fn with_data(
        schema: Schema<Query, Mutation, Subscription>,
        stream: S,
        data: Data,
        data_initializer: impl FnOnce(Data, serde_json::Value) -> R + Send + 'static,
        protocol: Protocols,
    ) -> Self {
    }
```

#### Example Usage

```rust
async fn initializer(mut data: Data, connection_init: serde_json::Value) {
    // Per-request-scoped data goes here
    let user = User::auth(data, connection_init).await?
    data.insert(user)
    Ok(data)
}

let mut data = async_graphql::Data::default();
// Application-scoped data goes here
data.insert(db)
data.insert(jwt_private_key)

let connection = async_graphql::http::WebSocket::with_data(
    schema,
    message_stream,
    data,
    initializer,
    async_graphql::http::WebSocketProtocols::GraphQLWS,
)
```

**Comment by sunli829** [comment]
This seems to be a problem with the rust language itself, so I decided to observe it for a while. 😁
