### ISSUE TITLE
A Changelog would be nice

### ISSUE THREAD

**Issue by EdorianDark** [async-graphql/async-graphql#396]
As a user I only see, that the version number increased but I have no idea what is new.
I would recommend to add a `Changelog.md`.
And maybe a post for a new release to places like reddit.com/r/rust, so that others see this great project!

**Comment by sunli829** [comment]
This suggestion is very good, I will consider adding `CHANGELOG.md` from the next release. 😁

**Comment by SirWindfield** [comment]
Great idea! I want to chime in and recommend this: https://keepachangelog.com/en/1.0.0/
It is used all over by a lot of different projects that I have stumbled across and is genuinely a great guideline!

**Comment by D1plo1d** [comment]
Something like this could really help automate the process, not sure if it exists for Rust projects though: https://github.com/semantic-release/semantic-release#how-does-it-work

**Comment by SirWindfield** [comment]
Ye, there are tools that already do that. There was a cli on crates called "conv" I think. And there is @conventional-commits-rs. They all work. I use the changelog generator myself. But they're far from complete (and don't get me started on code quality). I sadly had no time lately to work on them for a longer amount of time.

**Comment by sunli829** [comment]
`CHANGELOG.md` has been added, so I will close this issue, if you have any questions, please feel free to open it again.
