### ISSUE TITLE
Question: avoiding stringly-typed api

### ISSUE THREAD

**Issue by shakyShane** [async-graphql/async-graphql#397]
First of all, thanks for a great library - I hope to be able to contribute to it myself :)

I have a situation where I want to expose the GraphQL endpoint to external consumers via http (the normal way) but then I also want to use that same endpoint internally (via ffi etc).

My issue is that I want to receive compile-time errors if the query is invalid, but I can't think of a way to achieve this?

essentially I don't want to resort to runtime errors if the query is incorrect like this

```rust
client
    .post(url.as_str())
    .header("User-Agent", "Actix-web")
    .send_json(serde_json::json!({
        query: "mutation { stop }" // this is what I want to avoid, in case it's incorrect
    }))
    .await
```

so, given something simple like the following - I'm wondering how we could construct `mutation { stop }` in a way that would result in a compile-time error if it's incorrect?

```rust
pub struct MutationRoot;

#[async_graphql::Object]
impl MutationRoot {
     async fn stop(&self) -> async_graphql::Result<Something> {
           // ... impl omitted for brevity
     }
}
```

love to hear any thoughts on this :)

**Comment by sunli829** [comment]
You might want to look at `graph-client` and `cynic`, which can validate queries at compile time.
