### ISSUE TITLE
Value for InputObject

### ISSUE THREAD

**Issue by phungtranminh** [async-graphql/async-graphql#398]
Hi,

I would like to send some flexible data (String, Integer, Bool..) to the server, I am thinking of using Value provided by `async-graphql`. But when I use it in an `InputObject`, I get some errors `the trait bound `async_graphql::Value: InputType` is not satisfied`.

Do you have any suggestion to work around this? or should I use different kind fo data structure?

Thanks,

**Comment by phungtranminh** [comment]
Another question similar to the previous one is that, I have an `enum` I want to use it in Input but it looks like `InputObject` can only apply for `struct`?

**Comment by sunli829** [comment]
> Hi,
> 
> I would like to send some flexible data (String, Integer, Bool..) to the server, I am thinking of using Value provided by `async-graphql`. But when I use it in an `InputObject`, I get some errors `the trait bound `async_graphql::Value: InputType` is not satisfied`.
> 
> Do you have any suggestion to work around this? or should I use different kind fo data structure?
> 
> Thanks,

You should use the JSON type.

**Comment by sunli829** [comment]
> Another question similar to the previous one is that, I have an `enum` I want to use it in Input but it looks like `InputObject` can only apply for `struct`?

Because GraphQL enum can be used as an input value.

**Comment by phungtranminh** [comment]
Thanks, I tried to use `Json<Value>` and it seems to work well.

I wonder why do you have to treat `Value::Number` quite differently as `u64, i64, f64`?

**Comment by sunli829** [comment]
> Thanks, I tried to use `Json<Value>` and it seems to work well.
> 
> I wonder why do you have to treat `Value::Number` quite differently as `u64, i64, f64`?

In fact, the `Number` type uses `serde_json::Number`, which I think is for security reasons.

**Comment by phungtranminh** [comment]
Thanks for the explanation!
