### ISSUE TITLE
InputObject and SimpleObject field renaming

### ISSUE THREAD

**Issue by phungtranminh** [async-graphql/async-graphql#400]
Hi,

I wonder if there is a way to rename a field of InputObject or SimpleObject.

I searched quickly, I can only see `rename_fields` not sure what is the equivalent of `rename` in `serde`.

Thanks,

**Comment by phungtranminh** [comment]
So it appears that I can use serde rename for `SimpleObject`, I will play around with `InputObject`, hopefully it works the same.

**Comment by sunli829** [comment]
If you only want to rename a single field, you can do it like this:

```rust
#[derive(SimpleObject)]
struct MyObj {
    #[graphql(name = "abc")
    a: i32,
}
```

**Comment by phungtranminh** [comment]
Thanks it works!
