### ISSUE TITLE
graphql_subscription_with_data initializer errors are not logged by tracing extension

### ISSUE THREAD

**Issue by D1plo1d** [async-graphql/async-graphql#405]
I just ran into an issue where a `graphql_subscription_with_data` initializer was resulting in an error but it was not visible in my tracing logs. It would be helpful in these scenarios to surface the initializer error to the logs.

**Comment by sunli829** [comment]
Errors that occur during WebSocket initialization are currently returned through websocket. Because this is not a query, it is not possible to call Extension to output errors.

**Comment by D1plo1d** [comment]
Hmm, ok. Yeah indescrimenently exposing errors through the websocket could give an attacker information. If I roll my own error filtering in the websocket this works. Longer term it would be nicer to have it handled with good defaults by some kind of integration (eg. Relay all errors to the user in development but only explicitly user facing errors in production - with logging for the errors that are hidden from users).

**Comment by sunli829** [comment]
Maybe you can judge the role of the current user in the `data_initializer` function to decide whether to hide the real error message.

**Comment by D1plo1d** [comment]
In my server it's less user-specific and more dev/production specific. I'd like to improve errors and logs out of the box but I don't have a concrete suggestion at the moment so I'll close this for now.
