### ISSUE TITLE
Allow testing graphql input

### ISSUE THREAD

**Issue by EdorianDark** [async-graphql/async-graphql#407]
In code first it is possible to accidentally break queries while changing something.
In an other graphql framework it is possible to [test queries](https://netflix.github.io/dgs/query-execution-testing/)
It would be cool, if it would be also possible in async-graphql to write a test asserting that a query 
```
{
  hero {
    name
    height  
  }
}
```
results in an answer like
```
{
  "hero": {
      "name": "Luke Skywalker",
      "height": 1.72
  }
}
```
This is only possible currently to start the whole server in an integration test.

**Comment by sunli829** [comment]
This is an example of a query test, is it what you want?

https://github.com/async-graphql/async-graphql/blob/2a245cce26f257848930115b9c4990b233ac06c3/tests/enum.rs#L4

**Comment by EdorianDark** [comment]
Yes, that looks like what I had in mind.
