### ISSUE TITLE
Look into approaching federation.

### ISSUE THREAD

**Issue by ruseinov** [async-graphql/async-graphql#41]
https://www.apollographql.com/blog/apollo-federation-f260cf525d21 This here is a very nice tool, also to help load-balancing as when the schema is split between services - it's easier to have several different entrypoints with different pools of servers.

Even if one does want to code a monolith - this is easily achievable by having features in the source code and just running the same service with different features enabled. 

But using the node library is suboptimal, so I've been thinking this might actually be worth implementing in Rust. It's not really an issue for that repo, but something to chew on. I'll be looking into prototyping this sometime soon.

**Comment by sunli829** [comment]
Async-graphql already provides excellent support for ferdeation, the first rust library to support ferdeation.

**Comment by sunli829** [comment]
I thought ferdeation was an important bridge to call the graphql microservices API, so I thought about supporting it early on.

**Comment by sunli829** [comment]
Don't you see async-graphql in the list of third-party libraries from Apollo ferdeation?😁

**Comment by sunli829** [comment]
Here's an example of how to integrate with ferdeation.

https://github.com/async-graphql/examples/tree/master/federation

**Comment by ruseinov** [comment]
Yeah, but the issue here I wouldn't ever want to use a node.js frontend for Rust apps, which leads me to believe that said frontend needs to be implemented in Rust.

**Comment by sunli829** [comment]
This is not currently possible because dynamic schema support is required, but I don't think gateways will ever be a performance bottleneck, and nodejs is not slow.
😁
