### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by phungtranminh** [async-graphql/async-graphql#413]
Hi,

I am thinking of adding an authentication layer to my graphql API, is this supported by async graphql or is there any direction that you might want to point me to?

Thanks,

**Comment by Bajix** [comment]
Take a look at biscuit. The general approach for authentication I used was to check bearer tokens in my actix middleware and to add my token claim via the req.data. To sign in you would use argon2i for password confirmation and when authenticated or registered you would return a TokenSet struct with field resolvers that generate token types such as access_token & refresh_token. To enforce authentication use guards and error types that use Unauthenticated/Unauthorized as cases (thiserror + error extensions). For OAuth2 I think it's best to use a separate service and to manage this via tokens, but obviously that entails a more complex architecture.

**Comment by phungtranminh** [comment]
Thanks a lot @Bajix I will play around with those libs. I probably keep this for a while in case any one has other ideas.

Since you seem to work on rust for a while, I would like to ask a side question.

I am looking at actix, warp, tide, and feel like actix is a bit over complicated for web+api application, warp syntax is kind of cool but hard to digest sometimes. I find tide is probably the simplest and cleanest but it is the youngest.

Wonder if you have any suggestion, I am building an api (via async-graphql of course) kind of thing but I probably will add more features like web (some web pages, SPA..) and app (not sure if async-graphql can support different serde) and hopefully some sort of realtime collaboration.

**Comment by AurelienFT** [comment]
If you want a more "raw" approach with `async_graphql` there is an example of using a token to authenticate and pass it to the context of all mutations/queries : https://github.com/async-graphql/examples/blob/master/warp/token-from-header/src/main.rs#L44

**Comment by phungtranminh** [comment]
Thanks @AurelienFT I checked that out, it seems to be also a very good way to intercept and wrap around `async_graphql`.

It is quite amazing that a strongly static typed language like rust can be quite flexible at the same time.

**Comment by phungtranminh** [comment]
Thanks @Bajix @AurelienFT 

I am closing this as I think I have enough idea to start working on this, it looks more like framework rather than async graphql thing.
