### ISSUE TITLE
Renaming look_ahead maybe?

### ISSUE THREAD

**Issue by phungtranminh** [async-graphql/async-graphql#414]
It might be a joke 🤣 but not sure if it is too late to rename `ctx.look_ahead()` to `ctx.lookahead()` since the object is `Lookahead` or there might be other limitation?

**Comment by sunli829** [comment]
> It might be a joke 🤣 but not sure if it is too late to rename `ctx.look_ahead()` to `ctx.lookahead()` since the object is `Lookahead` or there might be other limitation?

For forward compatibility, it may be better to keep the current name. 🙂

**Comment by phungtranminh** [comment]
Thanks @sunli829 out of my curiosity so `.lookahead()` is planned to be used for something else in the future?
