### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by phungtranminh** [async-graphql/async-graphql#415]
Hi,

I am looking at error of my application, currently whenever there is an error `async_graphql` return the error message with some extra fields, like `location`, `path`.

I am not sure that is the idiomatic way to do show error in graphql but those fields seem useless sometimes, i.e. for location I don't find a way to make sense of it.

I wonder if I use them correctly, or is there a way to just hide it from the response?

Regards,

**Comment by zicklag** [comment]
The `location` and `path` fields could be used by IDEs or other similar tools to show which part of your query produced an error. For instance if you had a very large query, it could trigger many different resolvers in your code, and maybe only one of them has an error. Those extra fields will tell which part of the query actually triggered an error.

The `location` for instance refers to the exact spot textually in your query that the error came from. For instance if I have the following query:

```gql
{ 
  example {
    test
  }
}
```

And I get an error:

```{
  "data": null,
  "errors": [
    {
      "message": "Unknown field \"example\" on type \"Query\".",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

The "line 2, column 3" means line 2 of my query, 3 places to the right caused the issue, which is exactly where I have the "example" field that doesn't exist.

**Comment by phungtranminh** [comment]
Thanks @zicklag makes sense

I got it now, probably just ignore it for now

**Comment by phungtranminh** [comment]
I mean ideally I still prefer to have a way to hide those field.

I guess people who are not using graphql with IDE or any playground don't really need them.

cc @sunli829
