### ISSUE TITLE
MergedObject with actix-web example

### ISSUE THREAD

**Issue by phungtranminh** [async-graphql/async-graphql#417]
## Expected Behavior

The server should return valid response

## Actual Behavior

It seems to return `App data is not configured, to configure use App::data()`

<img width="739" alt="image" src="https://user-images.githubusercontent.com/77000018/108559380-5e802880-734f-11eb-8edd-16d2ccd95967.png">

## Steps to Reproduce the Problem

1. Change actix-web example https://github.com/async-graphql/examples/blob/b36b5c44543b7323cb199ed229ea247e83b85d18/actix-web/starwars/src/main.rs#L21 to

```
#[derive(MergedObject, Default)]
pub struct MergedQueryRoot(
    QueryRoot,
);

#[actix_rt::main]
async fn main() -> std::io::Result<()> {
    let schema = Schema::build(MergedQueryRoot::default(), EmptyMutation, EmptySubscription)
        .data(StarWars::new())
        .finish();
```

2. Add `#[derive(Default)]` to `QueryRoot` as well

## Specifications

- Version: lastest master
- Platform: macOS
- Subsystem: NA

**Comment by sunli829** [comment]
Because the `Schema` type is wrong, here is `StarWarsSchema`.

https://github.com/async-graphql/examples/blob/b36b5c44543b7323cb199ed229ea247e83b85d18/actix-web/starwars/src/main.rs#L7

**Comment by phungtranminh** [comment]
Right thanks, I managed to compile a running code, cheers
