### ISSUE TITLE
Field Visibility Example

### ISSUE THREAD

**Issue by rhzs** [async-graphql/async-graphql#419]
Hi, 

I've played around with async-graphql. I am interested to use the visible notation as seen on https://async-graphql.github.io/async-graphql/en/visibility.html 

However, I can't make it work. 

My code (taken from federation example). See `password` field. 

```
use async_graphql_warp::graphql;
use async_graphql::*;

use std::convert::Infallible;
use warp::{Filter, Reply};

#[derive(SimpleObject)]
struct User {
    id: ID,
    email: String,

    #[graphql(visible = false)]
    password: String,
}

struct Query;

#[Object(extends)]
impl Query {
    async fn me(&self) -> User {
        User {
            id: "1234".into(),
            email: "Me".to_string(),
            password: "123".to_string()
        }
    }

    #[graphql(entity)]
    async fn find_user_by_id(&self, id: ID) -> User {
        let email = if id == "1234" {
            "Me".to_string()
        } else {
            format!("User {:?}", id)
        };
        User { id, email, password: "123".to_string() }
    }
}

#[tokio::main]
async fn main() {
    let schema = Schema::new(Query, EmptyMutation, EmptySubscription);

    warp::serve(graphql(schema).and_then(
        |(schema, request): (
            Schema<Query, EmptyMutation, EmptySubscription>,
            async_graphql::Request,
        )| async move {
            Ok::<_, Infallible>(warp::reply::json(&schema.execute(request).await).into_response())
        },
    ))
    .run(([0, 0, 0, 0], 4001))
    .await;
}
```

And the result when running it. 

<img width="759" alt="Screen Shot 2021-02-21 at 15 17 57" src="https://user-images.githubusercontent.com/5300674/108619522-008b3800-7458-11eb-85a4-9ec61ba4be33.png">
 

Any idea how can I make the "visible" introspection work?

**Comment by sunli829** [comment]
The `Visible` attribute only hides the field in introspection, and it still takes effect when querying.

**Comment by rhzs** [comment]
@sunli829 is there a way to hide when querying apart from removing it from struct? Otherwise, I might need to have two different structs for Graphql and Db Model. cmiiw.

**Comment by sunli829** [comment]
> @sunli829 is there a way to hide when querying apart from removing it from struct? Otherwise, I might need to have two different structs for Graphql and Db Model. cmiiw.

You can use `#[graphql(skip)]` attribute on fields of the struct.

**Comment by rhzs** [comment]
> > @sunli829 is there a way to hide when querying apart from removing it from struct? Otherwise, I might need to have two different structs for Graphql and Db Model. cmiiw.
> 
> You can use `#[graphql(skip)]` attribute on fields of the struct.

Thanks!
