### ISSUE TITLE
Interface implementation based on trait

### ISSUE THREAD

**Issue by sunli829** [async-graphql/async-graphql#42]
I have a new idea to implement a type-safe interface and make it look like rust. I will try it tomorrow.

**Comment by phated** [comment]
Excited to see this! Please let me know if I can help in any way

**Comment by sunli829** [comment]
I tried it and it worked. 

Here is the new interface definition.

```rust
#[Interface]
trait Node: Send + Sync {
    async fn id(&self) -> i32;
}

struct MyObj;

#[Implement]
impl Node for MyObj {
    async fn id(&self) -> i32 {
       10
    }
}

#[Object]
impl MyObj {
    async fn value(&self) -> i32 {
        20
    }
}

struct Query;

#[Object]
impl Query {
    async fn my_obj(&self) -> NodeInterface<MyObj> {
         // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
         // NodeInterface is generated automatically, which may cause the auto-completion of the ide to fail.
         MyObj.into()
    }
}
```

The following is a query that can be executed correctly.

```graphql
{
    id
    ... on Node {
         id1: id
    }
     ... on MyObj {
         value 
    }
}
```

**Comment by phated** [comment]
Wow! This looks great!!!!!

**Comment by sunli829** [comment]
I couldn't implement such a feature because I would lose the type information if I converted to a trait object.😭

```rust
#[Object]
impl Query {
    async fn my_obj(&self) -> NodeInterface<???> {
         vec![MyObjA.into(), MyObjB.into()]
    }
}
```

**Comment by nicolaiunrein** [comment]
I suppose NodeInterface is a struct?
I don’t think this compiles but wouldn’t that be the correct signature?
```rust
#[Object]
impl Query {
    async fn my_obj(&self) -> Vec<NodeInterface<dyn Node>> {
         vec![MyObjA.into(), MyObjB.into()]
    }
}

```

**Comment by sunli829** [comment]
I need to think again about whether this template parameter is really necessary.

**Comment by phated** [comment]
And we are unable able to do this? 

```rust
struct Query;

#[Object]
impl Query {
    async fn my_obj(&self) -> impl Node  {
         MyObj{}
    }
}
```

https://doc.rust-lang.org/edition-guide/rust-2018/trait-system/impl-trait-for-returning-complex-types-with-ease.html

**Comment by sunli829** [comment]
No, this is just type MyObj, which is missing the interface information, so need a wrapper.

**Comment by nicolaiunrein** [comment]
Correct me if I’m wrong but I think under the hood impl Query gets converted to a trait? and returning impl Trait is not supported on trait methods. 

But what about utilising the flatten attribute inside the generated Interface somehow to inline existing fields?

**Comment by phated** [comment]
> No, this is just type MyObj, which is missing the interface information, so need a wrapper.

If you `impl Node for MyObj`, why would it not fulfill the trait implementation type signature?

**Comment by sunli829** [comment]
Trait object are the only way to solve this problem, but I don't have a computer right now, so I'll think about it later.

**Comment by sunli829** [comment]
Cannot use a trait object, which is a run-time type, and generate Schema requires static type.
So let's go back to #38, is it worth sacrificing a little type safety for more flexible interface definitions?

**Comment by sunli829** [comment]
The generic list should solve all the problems. I'm still thinking about it.

**Comment by sunli829** [comment]
This is impossible, so I'm going to close it right now.

**Comment by sunli829** [comment]
I think #38 is the best solution, removing many of the limitations of function forwarding and making it easy to use. Panic at startup is acceptable.

**Comment by phated** [comment]
I discussed this at my presentation and everyone wanted static type checking. It takes a long time to start up the server to see that you made a mistake.

**Comment by sunli829** [comment]
Let's keep the original design the same.😂

**Comment by sunli829** [comment]
I'll try again.
