### ISSUE TITLE
Parsed query before schema.execute

### ISSUE THREAD

**Issue by phungtranminh** [async-graphql/async-graphql#421]
Hi,

Recently when I am building my app, I encounter a use case where I would like to know the parsed query before calling `schema.execute`. Specifically, somewhere before this line:

https://github.com/async-graphql/examples/blob/b36b5c44543b7323cb199ed229ea247e83b85d18/warp/token-from-header/src/main.rs#L48

Thank you for your help,

**Comment by sunli829** [comment]
Do you want to get the AST of the parsed query?

**Comment by phungtranminh** [comment]
Thanks for your reply @sunli829

```
mutation {
  createStore (...) {
    ...
  }
}
```

Currently I would like to know if a query is of type `createStore` or not.

**Comment by phungtranminh** [comment]
Basically I would like to do something before certain types of query.

i.e. access header, add data enhancement, etc.. very similar to authentication workflow.

**Comment by sunli829** [comment]
> Thanks for your reply @sunli829
> 
> ```
> mutation {
>   createStore (...) {
>     ...
>   }
> }
> ```
> 
> Currently I would like to know if a query is of type `createStore` or not.

This is too much trouble, I recommend you to refer to this example.

https://github.com/async-graphql/examples/blob/b36b5c44543b7323cb199ed229ea247e83b85d18/actix-web/token-from-header/src/main.rs#L25

**Comment by phungtranminh** [comment]
Yeah right, thanks @sunli829 

I thought about this after posting the question.

**Comment by phungtranminh** [comment]
Hi @sunli829 do you recommend a way if I want to write something back into the response headers?

**Comment by sunli829** [comment]
https://docs.rs/async-graphql/2.5.7/async_graphql/context/struct.ContextBase.html#method.append_http_header

**Comment by phungtranminh** [comment]
Great thanks @sunli829 👍
