### ISSUE TITLE
Borrow mut data in ctx

### ISSUE THREAD

**Issue by phungtranminh** [async-graphql/async-graphql#422]
Hi,

I have some data in ctx, I would like to borrow mut it so that I can make changes to it.

I haven't seen how to do it yet, wonder if it is even possible.

Thanks,

**Comment by naamancurtis** [comment]
Hey,

The schema context is something that's shared between threads, as such any data you would want to manipulate would have to be thread safe. That probably means wrapping your data in some kind of `Arc<Mutex<T>>` or some other thread safe interior mutability pattern, however you'd still have to be careful that your application is accessing it in the way you think it is.

Not sure if there's a better way, but it might be worth trying

**Comment by phungtranminh** [comment]
Hey @naamancurtis thanks for your quick reply.

Yep that's what I am testing what you suggested and it seems to work.

I will keep this open for little while to see if anyone has any other suggestion.

**Comment by phungtranminh** [comment]
Everything seems to work well, thanks again @naamancurtis
