### ISSUE TITLE
Is it possible to add request specific Context to subscriptions?

### ISSUE THREAD

**Issue by naamancurtis** [async-graphql/async-graphql#423]
Hey,

Just like this example: https://github.com/async-graphql/examples/blob/b36b5c44543b7323cb199ed229ea247e83b85d18/warp/token-from-header/src/main.rs but for GraphQL subscriptions.

Essentially I was wondering if I have some cookies/headers that I can parse from the initial websocket request, am I able to pass them through to the `Subscription` "handler" somehow?. I guess this is a fairly similar point to generating a request specific context to queries/mutations which are called via graphql-ws 

On a similar but slightly different side note with `graphql_subscription_with_data` do you have any thoughts on allowing updates to that data after initialisation from the client? The only way of working around that now that I can see would involve closing the subscription and re opening it?

**Comment by sunli829** [comment]
> Hey,
> 
> Just like this example: https://github.com/async-graphql/examples/blob/b36b5c44543b7323cb199ed229ea247e83b85d18/warp/token-from-header/src/main.rs but for GraphQL subscriptions.
> 
> Essentially I was wondering if I have some cookies/headers that I can parse from the initial websocket request, am I able to pass them through to the `Subscription` "handler" somehow?. I guess this is a fairly similar point to generating a request specific context to queries/mutations which are called via graphql-ws
> 
> On a similar but slightly different side note with `graphql_subscription_with_data` do you have any thoughts on allowing updates to that data after initialisation from the client? The only way of working around that now that I can see would involve closing the subscription and re opening it?

Sorry for the late answer, because I just saw this issue.
Currently `ContextData` is immutable, but you can use `Mutex` to achieve what you want. 😁

**Comment by sunli829** [comment]
> On the other hand, any thoughts about extracting data from the initial http upgrade request before initialising the web socket - the main reason for this would be to grab HttpOnly cookies. It's kind of hard to send them in the graphql-ws init payload if they're not accessible via JavaScript?

Now the `ContextData` of WebSocket can only be initialized from the `payload` in the `connection_init` message, and cannot be initialized according to the headers of Http upgrade. This is the problem you are encountering now, right?

**Comment by naamancurtis** [comment]
Essentially yeah.

My way around this at the moment is to have a custom implementation of `framework_integration::graphql_subscription_with_data` that essentially just wraps the `init_future` with a function that extracts the relevant cookies/headers and inserts them into the context returned from the `init_future`.

I'm not too sure how you would even go about building that functionality generically from a library perspective - so maybe that's not something you want to support, but I figured I'd ask.

**Comment by sunli829** [comment]
That's a very useful feature. I'll consider adding it.😄

**Comment by sarendsen** [comment]
Would be a great future.

**Comment by sunli829** [comment]
I forgot it.😅

**Comment by meh** [comment]
I also really need this, the authentication token is in an HTTP-only cookie so there's no way around it without doing what @naamancurtis is doing.
