### ISSUE TITLE
Type mismatch when return Result because of async_graphql::error::Error

### ISSUE THREAD

**Issue by MaxLuchs** [async-graphql/async-graphql#424]
Hello Im getting the following compiler error

```
expected `Result<PooledConnection<ConnectionManager<PgConnection>>, async_graphql::error::Error>`, found `Result<PooledConnection<ConnectionManager<PgConnection>>, r2d2::Error>` 
```

with my code:
```
#[async_graphql::Object]
impl Query {
  pub async fn user(&self, context: &Context<'_>, id: i32) -> QueryResult<Option<User>> {
          let con = context.data::<GraphqlContext>().and_then(|ctx| ctx.db.pool.get())?;
          schema::user::table.find(id).first(&con).ok().into()
  }
}
```

How can I transform an standard error from Diesel to an async_graphql-Error?

**Comment by sunli829** [comment]
> Hello Im getting the following compiler error
> 
> ```
> expected `Result<PooledConnection<ConnectionManager<PgConnection>>, async_graphql::error::Error>`, found `Result<PooledConnection<ConnectionManager<PgConnection>>, r2d2::Error>` 
> ```
> 
> with my code:
> 
> ```
> #[async_graphql::Object]
> impl Query {
>   pub async fn user(&self, context: &Context<'_>, id: i32) -> QueryResult<Option<User>> {
>           let con = context.data::<GraphqlContext>().and_then(|ctx| ctx.db.pool.get())?;
>           schema::user::table.find(id).first(&con).ok().into()
>   }
> }
> ```
> 
> How can I transform an standard error from Diesel to an async_graphql-Error?

You should return this type: 

https://docs.rs/async-graphql/2.5.7/async_graphql/type.FieldResult.html
