### ISSUE TITLE
async-graphql-actix-web and sessions

### ISSUE THREAD

**Issue by simoneromano96** [async-graphql/async-graphql#426]
Hi, I'm using cookies for authentication in one of my projects.
I had to split the authentication service in a REST server because I could not find a way to expose the (actix-web) session inside a resolver, this works in node/js graphql implementations (I think because of the weak typing or because node works on a single thread).
If I try to add the Session to the context it gives a lot of errors even by wrapping it in a `Mutex`.
I can expose the cookie inside the resolvers without any problem, I looked at the expose-header example.
I'd need this feature if it isn't currently implemented and I can try to work on it.

**Comment by sunli829** [comment]
Maybe this example can help you.😄

https://github.com/async-graphql/examples/tree/master/actix-web/token-from-header

**Comment by simoneromano96** [comment]
> 
> 
> Maybe this example can help you.😄
> 
> https://github.com/async-graphql/examples/tree/master/actix-web/token-from-header

Hello,
The problem is not reading the cookie but setting the cookie inside a resolver.
Here I can easily read the cookie since I have access to the original actix methods
https://github.com/simoneromano96/federation-graphql-rust/blob/main/products-service/src/graphql/routes.rs

The problem is how can I set the cookie in a resolver?

**Comment by simoneromano96** [comment]
```rust
pub struct Mutation;

impl Mutation {
    /// Logs in the user
    async fn login(&self, ctx: &Context<'_>, input: LoginInput) -> Result<Coffee> {
      // How can I do `session.set()`?
    }
}
```

**Comment by sunli829** [comment]
Sorry, I wasn't careful enough.😄

This function can help you.

https://docs.rs/async-graphql/2.5.9/async_graphql/context/struct.ContextBase.html#method.append_http_header

**Comment by sunli829** [comment]
And this issue:

https://github.com/async-graphql/async-graphql/issues/370

**Comment by simoneromano96** [comment]
Thanks! I'll see if I can fix my authentication service then

**Comment by oscartbeaumont** [comment]
I have come up with another solution to this which can directly access the [`actix_session`](https://docs.rs/actix-session/0.4.1/actix_session) from inside my GraphQL resolvers. It uses a shared wrapped type I created. I don't know if this is idiomatic Rust but it has been working for me so far.
<details>
  <summary>Shared Type</summary>
  
```rust
use send_wrapper::SendWrapper;
use std::ops::Deref;

#[derive(Clone, Debug)]
pub struct Shared<T>(pub Option<SendWrapper<T>>);

impl<T> Shared<T> {
    pub fn new(v: T) -> Self {
        Self(Some(SendWrapper::new(v)))
    }
}

impl<T> Deref for Shared<T> {
    type Target = T;

    fn deref(&self) -> &Self::Target {
        &*self.0.as_deref().clone().unwrap()
    }
}
```
</details>

Then in the GraphQL HTTP handler:
```rust
// session is the actix_session::Session which can be included as an argument to the HTTP handler.
let session = Shared::new(session);
schema.execute(req.into_inner().data(session)) // This is just to show its usage. You would have more code here to make this work.
```

And finally access the `actix_session` inside your GraphQL resolver:
```rust
let actix_session = ctx.data::<Shared<actix_session::Session>>()?;
actix_session.set("some_key", "some_value")?;
```

**Comment by Oyelowo** [comment]
@[oscartbeaumont](https://github.com/oscartbeaumont) Are you getting the `session` from the `index` argument or from `req.get_session`?

```rs
#[post("/graphql")]
pub async fn index(
    schema: web::Data<MyGraphQLSchema>,
    req: HttpRequest,
    db: actix_web::web::Data<Database>,
    gql_request: GraphQLRequest,
    session: Session,
) -> GraphQLResponse {
```

I tried your approach but getting the error below. My app is running as a deployment in kubernetes with replicas and I'm using redis as my session storage.
```rs
Search...
thread 'actix-server worker 1' panicked at 'opo', graphql-mongo/src/app/user/mutation_root.rs:70:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'actix-server worker 2' panicked at 'opo', graphql-mongo/src/app/user/mutation_root.rs:70:14
```

[simoneromano96](https://github.com/simoneromano96)
Were you able to figure out how to work with acitx-session and RedisSession in async-graphql without using REST API?
I have an issue opened [here](https://github.com/async-graphql/async-graphql/issues/867)

**Comment by oscartbeaumont** [comment]
I was using the `session: Session` as an argument as you showed. That should work. Can you share the code?

I am gonna take a guess from the information I have that the `mutation_root.rs` file on line `70` that you didn't wrap the `Session` in `Shared` when accessing it from the GraphQL context. It should be:
```rust
let actix_session = ctx.data::<Shared<actix_session::Session>>()?;
actix_session.set("some_key", "some_value")?;
```
If this doesn't help either share code or add me on Discord (on my GitHub profile page) and I can have a better look at it.

**Comment by Oyelowo** [comment]
Thanks to @[oscartbeaumont](https://github.com/oscartbeaumont), I just cross-checked following your message and it now works 🎉 . It looks like the issue was that I was using `session` from `req.get_session()` rather than the `session: Session` argument 🤔 

One thing though, I am concerned about using `SendWrapper` in `Send` as it seems to be intended for when a `process` should not move across threads? Since `actix-web` + `tokio` support multithreading and could potentially move `session` across threads, couldn't this lead to an issue down the road or am I misunderstanding something?

Would it be possible to use `Mutex` or `RwLock` wrapped in an `Arc` in this case? What was the rationale behind using `SharedWrapper`?

- This is what the code looks like now:
### My index for queries and mutations
```rs
#[post("/graphql")]
pub async fn index(
    schema: web::Data<MyGraphQLSchema>,
    _req: HttpRequest,
    // db: actix_web::web::Data<Database>,
    gql_request: GraphQLRequest,
    session: Session,
) -> GraphQLResponse {
    let mut request = gql_request.into_inner();
    let session = Shared::new(session);
    request = request.data(session);
    schema.execute(request).await.into()
}
```

### My mutation
```rs
    async fn signin(&self, ctx: &Context<'_>) -> anyhow::Result<Something> {

        let session = ctx
            .data::<Shared<actix_session::Session>>()
            .expect("Failed to get actix session Object");

        session.insert("user_id", "id1234").expect("poor insertion");
        let uid = session
            .get::<String>("user_id")
            .expect("Failed to get user_id session")
            .expect("Failed to get user_id session value");
        Ok(Something {
            name: "Mars".into(),
            user_id: uid,
        })
    }
```
Appreciate you for taking the time 👍

**Comment by Oyelowo** [comment]
@oscartbeaumont Yeah, that was my thought also. Having the change implemented upstream would be awesome! I wonder why Send is not supported already considering that actix supports multithreading. 
Perhaps, I should bring it up on their side also.

Since `request.data()` expects `Send`, session should probably be made as such since it's usually needed in the resolvers anyways. 

Wondering why there aren't tons of examples online related to this considering that session is fairly relatively popular and secure 🤔
Doing things in a stateless manner might end up causing more work with token revocation and whatnot.
Anyways, thanks for sharing and please do keep us updated if you find a new way out. I'll be sure to do the same

**Comment by hardywu** [comment]
Instead of access the session directly, passing a trivial Identity struct is more easy and stable. Doing so, we can just keep the authentication logic out of Graphql codes.
```rust
pub struct Identity {
    pub id: Option<String>,
}

/// GraphQL endpoint
#[route("/graphql", method = "GET", method = "POST")]
pub async fn graphql(
    schema: web::Data<gql::Schema>,
    req: GraphQLRequest,
    session: Session,
) -> GraphQLResponse {
    let uid = session.get::<String>("user_id").unwrap_or(None);
    let id = Identity { id: uid };
    schema.execute(req.into_inner().data(id)).await.into()
}
```

**Comment by hardywu** [comment]
@Oyelowo I keep the methods like renew of session before `schema.execute`  , i.e.

```rust
/// GraphQL endpoint
#[route("/graphql", method = "GET", method = "POST")]
pub async fn graphql(
    schema: web::Data<gql::Schema>,
    req: GraphQLRequest,
    session: Session,
) -> GraphQLResponse {
    /// session.renew();
    /// session.clear();
    let uid = session.get::<String>("user_id").unwrap_or(None);
    let id = Identity { id: uid };
    schema.execute(req.into_inner().data(id)).await.into()
}
```

**Comment by AJTJ** [comment]
> @Oyelowo I keep the methods like renew of session before `schema.execute` , i.e.
> 
> ```rust
> /// GraphQL endpoint
> #[route("/graphql", method = "GET", method = "POST")]
> pub async fn graphql(
>     schema: web::Data<gql::Schema>,
>     req: GraphQLRequest,
>     session: Session,
> ) -> GraphQLResponse {
>     /// session.renew();
>     /// session.clear();
>     let uid = session.get::<String>("user_id").unwrap_or(None);
>     let id = Identity { id: uid };
>     schema.execute(req.into_inner().data(id)).await.into()
> }
> ```

I think this is a great solution. How would you implement a login process?

**Comment by AJTJ** [comment]
@oscartbeaumont any news?

**Comment by AJTJ** [comment]
> I have come up with another solution to this which can directly access the [`actix_session`](https://docs.rs/actix-session/0.4.1/actix_session) from inside my GraphQL resolvers. It uses a shared wrapped type I created. I don't know if this is idiomatic Rust but it has been working for me so far.
> 
> Shared Type
> Then in the GraphQL HTTP handler:
> 
> ```rust
> // session is the actix_session::Session which can be included as an argument to the HTTP handler.
> let session = Shared::new(session);
> schema.execute(req.into_inner().data(session)) // This is just to show its usage. You would have more code here to make this work.
> ```
> 
> And finally access the `actix_session` inside your GraphQL resolver:
> 
> ```rust
> let actix_session = ctx.data::<Shared<actix_session::Session>>()?;
> actix_session.set("some_key", "some_value")?;
> ```

fwiw, I tried implementing a similar solution to this, but immediately started getting these errors:

```
Actix runtime found; starting in Actix runtime
thread 'tokio-runtime-worker' panicked at 'Dereferenced SendWrapper<T> variable from a thread different to the one it has been created with.',
```
do not recommend, without an extreme caution

**Comment by Elsoberanold** [comment]
I've tried previous approaches but unfortunately I could not getting it working. Compiler throws the following error: ``Rc<RefCell<actix_session::session::SessionInner>>` cannot be shared between threads safely
within `actix_session::Session`, the trait `Sync` is not implemented for `Rc<RefCell<actix_session::session::SessionInner>>``

I have been thinking about using a function that receives and analyses query or mutation response like so:
```
async fn index(
    schema: web::Data<AppSchema>,
    session: actix_session::Session, 
    req: GraphQLRequest
) -> GraphQLResponse {
    session_manager(&session, schema.execute(req.into_inner()).await.into());
}
```
The query output type had to include a defined structure to detect when we need to perform a session operation inside session_manager function. My only concern are security threats and extra logic being checked on every request... What are your thoughts on this?

**Comment by AJTJ** [comment]
> I've tried previous approaches but unfortunately I could not getting it working. Compiler throws the following error: ``Rc<RefCell<actix_session::session::SessionInner>>` cannot be shared between threads safely
> 
> within `actix_session::Session`, the trait `Sync` is not implemented for `Rc<RefCell<actix_session::session::SessionInner>>``
> 
> 
> 
> I have been thinking about using a function that receives and analyses query or mutation response like so:
> 
> ```
> 
> async fn index(
> 
>     schema: web::Data<AppSchema>,
> 
>     session: actix_session::Session, 
> 
>     req: GraphQLRequest
> 
> ) -> GraphQLResponse {
> 
>     session_manager(&session, schema.execute(req.into_inner()).await.into());
> 
> }
> 
> ```
> 
> The query output type had to include a defined structure to detect when we need to perform a session operation inside session_manager function. My only concern are security threats and extra logic being checked on every request... What are your thoughts on this?

Fwiw, I just created my own sessions auth with a redis store. It really isn't that hard to salt/encrypt the passwords and so forth. It was certainly a more interesting thing to work on than figuring out how to bend this single threaded crate to my needs.

**Comment by Elsoberanold** [comment]
I have cloned this crate into a local file and changed /src/session.rs type to "pub struct Session(Arc<RwLock<SessionInner>>)"
It seams to work fine. I am being able to pass actix_session into graphql context. I have not found any problem so far. Could this result in unexpected behavior in production?

```
use std::{
    //cell::{RefCell},
    collections::HashMap,
    error::Error as StdError,
    //mem,
    //rc::Rc, 
    sync::{Arc, RwLock}
};

use actix_utils::future::{ready, Ready};
use actix_web::{
    body::BoxBody,
    dev::{Extensions, Payload, ServiceRequest, ServiceResponse},
    error::Error,
    FromRequest, HttpMessage, HttpRequest, HttpResponse, ResponseError,
};
use anyhow::Context;
use derive_more::{Display, From};
use serde::{de::DeserializeOwned, Serialize};

/// The primary interface to access and modify session state.
///
/// [`Session`] is an [extractor](#impl-FromRequest)—you can specify it as an input type for your
/// request handlers and it will be automatically extracted from the incoming request.
///
/// ```
/// use actix_session::Session;
///
/// async fn index(session: Session) -> actix_web::Result<&'static str> {
///     // access session data
///     if let Some(count) = session.get::<i32>("counter")? {
///         session.insert("counter", count + 1)?;
///     } else {
///         session.insert("counter", 1)?;
///     }
///
///     Ok("Welcome!")
/// }
/// # actix_web::web::to(index);
/// ```
///
/// You can also retrieve a [`Session`] object from an `HttpRequest` or a `ServiceRequest` using
/// [`SessionExt`].
///
/// [`SessionExt`]: crate::SessionExt
#[derive(Clone)]
pub struct Session(Arc<RwLock<SessionInner>>);

/// Status of a [`Session`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SessionStatus {
    /// Session state has been updated - the changes will have to be persisted to the backend.
    Changed,

    /// The session has been flagged for deletion - the session cookie will be removed from
    /// the client and the session state will be deleted from the session store.
    ///
    /// Most operations on the session after it has been marked for deletion will have no effect.
    Purged,

    /// The session has been flagged for renewal.
    ///
    /// The session key will be regenerated and the time-to-live of the session state will be
    /// extended.
    Renewed,

    /// The session state has not been modified since its creation/retrieval.
    Unchanged,
}

impl Default for SessionStatus {
    fn default() -> SessionStatus {
        SessionStatus::Unchanged
    }
}

#[derive(Default)]
struct SessionInner {
    state: HashMap<String, String>,
    status: SessionStatus,
}

impl Session {
    /// Get a `value` from the session.
    ///
    /// It returns an error if it fails to deserialize as `T` the JSON value associated with `key`.
    pub fn get<T: DeserializeOwned>(&self, key: &str) -> Result<Option<T>, SessionGetError> {
        if let Some(val_str) = self.0.read().unwrap().state.get(key) {
            Ok(Some(
                serde_json::from_str(val_str)
                    .with_context(|| {
                        format!(
                            "Failed to deserialize the JSON-encoded session data attached to key \
                            `{}` as a `{}` type",
                            key,
                            std::any::type_name::<T>()
                        )
                    })
                    .map_err(SessionGetError)?,
            ))
        } else {
            Ok(None)
        }
    }

    /// Get all raw key-value data from the session.
    ///
    /// Note that values are JSON encoded.
    pub fn entries(&self) -> HashMap<String, String> {
        let inner = self.0.read().unwrap();
        inner.state.clone()
    }

    /// Returns session status.
    pub fn status(&self) -> SessionStatus {
        let inner = self.0.read().unwrap();
        inner.status.clone()
    }

    /// Inserts a key-value pair into the session.
    ///
    /// Any serializable value can be used and will be encoded as JSON in session data, hence why
    /// only a reference to the value is taken.
    ///
    /// It returns an error if it fails to serialize `value` to JSON.
    pub fn insert<T: Serialize>(
        &self,
        key: impl Into<String>,
        value: T,
    ) -> Result<(), SessionInsertError> {
        let mut inner = self.0.write().unwrap();

        if inner.status != SessionStatus::Purged {
            if inner.status != SessionStatus::Renewed {
                inner.status = SessionStatus::Changed;
            }

            let key = key.into();
            let val = serde_json::to_string(&value)
                .with_context(|| {
                    format!(
                        "Failed to serialize the provided `{}` type instance as JSON in order to \
                        attach as session data to the `{}` key",
                        std::any::type_name::<T>(),
                        &key
                    )
                })
                .map_err(SessionInsertError)?;

            inner.state.insert(key, val);
        }

        Ok(())
    }

    /// Remove value from the session.
    ///
    /// If present, the JSON encoded value is returned.
    pub fn remove(&self, key: &str) -> Option<String> {
        let mut inner = self.0.write().unwrap();

        if inner.status != SessionStatus::Purged {
            if inner.status != SessionStatus::Renewed {
                inner.status = SessionStatus::Changed;
            }
            return inner.state.remove(key);
        }

        None
    }

    /// Remove value from the session and deserialize.
    ///
    /// Returns `None` if key was not present in session. Returns `T` if deserialization succeeds,
    /// otherwise returns un-deserialized JSON string.
    pub fn remove_as<T: DeserializeOwned>(&self, key: &str) -> Option<Result<T, String>> {
        self.remove(key)
            .map(|val_str| match serde_json::from_str(&val_str) {
                Ok(val) => Ok(val),
                Err(_err) => {
                    tracing::debug!(
                        "Removed value (key: {}) could not be deserialized as {}",
                        key,
                        std::any::type_name::<T>()
                    );

                    Err(val_str)
                }
            })
    }

    /// Clear the session.
    pub fn clear(&self) {
        let mut inner = self.0.write().unwrap();

        if inner.status != SessionStatus::Purged {
            if inner.status != SessionStatus::Renewed {
                inner.status = SessionStatus::Changed;
            }
            inner.state.clear()
        }
    }

    /// Removes session both client and server side.
    pub fn purge(&self) {
        let mut inner = self.0.write().unwrap();
        inner.status = SessionStatus::Purged;
        inner.state.clear();
    }

    /// Renews the session key, assigning existing session state to new key.
    pub fn renew(&self) {
        let mut inner = self.0.write().unwrap();

        if inner.status != SessionStatus::Purged {
            inner.status = SessionStatus::Renewed;
        }
    }

    /// Adds the given key-value pairs to the session on the request.
    ///
    /// Values that match keys already existing on the session will be overwritten. Values should
    /// already be JSON serialized.
    pub(crate) fn set_session(
        req: &mut ServiceRequest,
        data: impl IntoIterator<Item = (String, String)>,
    ) {
        let session = Session::get_session(&mut req.extensions_mut());
        let mut inner = session.0.write().unwrap();
        inner.state.extend(data);
    }

    /// Returns session status and iterator of key-value pairs of changes.
    ///
    /// This is a destructive operation - the session state is removed from the request extensions
    /// typemap, leaving behind a new empty map. It should only be used when the session is being
    /// finalised (i.e. in `SessionMiddleware`).
    pub(crate) fn get_changes<B>(
        res: &mut ServiceResponse<B>,
    ) -> (SessionStatus, HashMap<String, String>) {
        if let Some(s_impl) = res
            .request()
            .extensions()
            .get::<Arc<RwLock<SessionInner>>>()
        {
            (s_impl.read().unwrap().status.clone(), s_impl.read().unwrap().state.clone())
            //let state = mem::take(&mut s_impl.borrow_mut().state);
            //(s_impl.borrow().status.clone(), state)
        } else {
            (SessionStatus::Unchanged, HashMap::new())
        }
    }

    pub(crate) fn get_session(extensions: &mut Extensions) -> Session {
        if let Some(s_impl) = extensions.get::<Arc<RwLock<SessionInner>>>() {
            return Session(Arc::clone(s_impl));
        }

        let inner = Arc::new(RwLock::new(SessionInner::default()));
        extensions.insert(inner.clone());

        Session(inner)
    }
}

/// Extractor implementation for [`Session`]s.
///
/// # Examples
/// ```
/// # use actix_web::*;
/// use actix_session::Session;
///
/// #[get("/")]
/// async fn index(session: Session) -> Result<impl Responder> {
///     // access session data
///     if let Some(count) = session.get::<i32>("counter")? {
///         session.insert("counter", count + 1)?;
///     } else {
///         session.insert("counter", 1)?;
///     }
///
///     let count = session.get::<i32>("counter")?.unwrap();
///     Ok(format!("Counter: {}", count))
/// }
/// ```
impl FromRequest for Session {
    type Error = Error;
    type Future = Ready<Result<Session, Error>>;

    #[inline]
    fn from_request(req: &HttpRequest, _: &mut Payload) -> Self::Future {
        ready(Ok(Session::get_session(&mut req.extensions_mut())))
    }
}

/// Error returned by [`Session::get`].
#[derive(Debug, Display, From)]
#[display(fmt = "{_0}")]
pub struct SessionGetError(anyhow::Error);

impl StdError for SessionGetError {
    fn source(&self) -> Option<&(dyn StdError + 'static)> {
        Some(self.0.as_ref())
    }
}

impl ResponseError for SessionGetError {
    fn error_response(&self) -> HttpResponse<BoxBody> {
        HttpResponse::new(self.status_code())
    }
}

/// Error returned by [`Session::insert`].
#[derive(Debug, Display, From)]
#[display(fmt = "{_0}")]
pub struct SessionInsertError(anyhow::Error);

impl StdError for SessionInsertError {
    fn source(&self) -> Option<&(dyn StdError + 'static)> {
        Some(self.0.as_ref())
    }
}

impl ResponseError for SessionInsertError {
    fn error_response(&self) -> HttpResponse<BoxBody> {
        HttpResponse::new(self.status_code())
    }
}
```
