### ISSUE TITLE
Question, How to Get the request context before schema.execute(request)

### ISSUE THREAD

**Issue by jescobar** [async-graphql/async-graphql#430]
I'm using actix_web, in the endpoint that actually  executes the GraphQL request I need extract the connection pool  from the request.data before executing the request  (schema.execute(request)) but I wasn't able to do it, I tried with:

let request = req.into_inner();

 let conn: PgPooledConnection = request.data.get(&TypeId::of::<Arc<PgPool>>())
        .and_then(|d| d.downcast_ref::<Arc<PgPool>>()).expect("can't get pool").get().expect("can't get Db connection");

but after some checks I noticed that at this point the request.data is empty, I verified with:
println!("data keys");
      for key in request.data.keys() {
        println!("{:?}", key);
        println!("{:?}", request.data.get(key))
      }
      println!("after data keys");

there is no keys in request.data at this point!

I'm wondering what I'm doing wrong and/or if it is not possible achieve this, could you help me please?

**Comment by sunli829** [comment]
> I'm using actix_web, in the endpoint that actually executes the GraphQL request I need extract the connection pool from the request.data before executing the request (schema.execute(request)) but I wasn't able to do it, I tried with:
> 
> let request = req.into_inner();
> 
> let conn: PgPooledConnection = request.data.get(&TypeId::of::<Arc>())
> .and_then(|d| d.downcast_ref::<Arc>()).expect("can't get pool").get().expect("can't get Db connection");
> 
> but after some checks I noticed that at this point the request.data is empty, I verified with:
> println!("data keys");
> for key in request.data.keys() {
> println!("{:?}", key);
> println!("{:?}", request.data.get(key))
> }
> println!("after data keys");
> 
> there is no keys in request.data at this point!
> 
> I'm wondering what I'm doing wrong and/or if it is not possible achieve this, could you help me please?

Do it like this:

```rust

// Create the app
App::new()
            .data(pool)
            .service(web::resource("/").guard(guard::Post()).to(index))

// Handler
async fn index(pool: web::Data<PgPooledConnection>, req: Request) -> Response {
   ...
}
```

**Comment by jescobar** [comment]
By the way thanks for all the hard work, I switch from juniper and it is great!

Thanks for your reply! I was doing this (your suggested code) before asking but I started to get too connections open issue due that when I create the schema I attach to the schema the conneciton pool using the data. so If I have both I got too connections open

let schema = Schema::build(QueryRoot::default(), MutationRoot::default(), EmptySubscription)
      .data(Arc::clone(&arc_pool))
      .finish();

So inside of each #[Object] fn I'm able to get the connection string from the context data, for example

 pub async fn list_data(
        &self, ctx: &Context<'_>,
        search_params: Option<SearchParams>,
    ) -> Result<ListDataModel> {
        let conn = get_conn_from_ctx(ctx);
        Ok(DataEntity::list(&conn, search_params)?)
    }

where get_conn_from_ctx is
pub fn get_conn_from_ctx(ctx: &Context<'_>) -> PgPooledConnection {
  ctx.data::<Arc<PgPool>>().expect("Can't get pool").get().expect("Can't get DB connection")
}

**Comment by sunli829** [comment]
I noticed that the generic parameter of the `ctx.data` function is incorrect, it should look like the following.

```
pub fn get_conn_from_ctx(ctx: &Context<'_>) -> PgPooledConnection {
    ctx.data::<Arc<PgPooledConnection>>().expect("Can't get pool").get().expect("Can't get DB connection")
}
```

**Comment by jescobar** [comment]
Oh sorry I have some pub type definitions that hides complexibility

pub type PgPool = Pool<ConnectionManager<PgConnection>>;
pub type PgPooledConnection = PooledConnection<ConnectionManager<PgConnection>>;

**Comment by sunli829** [comment]
You cannot get this object from `Request.data` because it belongs to `Schema.data`.

```rust
let conn: PgPooledConnection = request.data.get(&TypeId::of::<Arc>())
.and_then(|d| d.downcast_ref::<Arc>()).expect("can't get pool").get().expect("can't get Db connection");
```

**Comment by sunli829** [comment]
So you need to use `web::Data` to pass this object yourself.

```rust
// Create the app
App::new()
            .data(pool)
            .service(web::resource("/").guard(guard::Post()).to(index))

// Handler
async fn index(pool: web::Data<PgPooledConnection>, req: Request) -> Response {
   ...
}
```

**Comment by jescobar** [comment]
Oh I see, thanks a lot!, I will use that!

**Comment by sunli829** [comment]
There are many examples here, I hope it helps you.

https://github.com/async-graphql/examples

**Comment by jescobar** [comment]
Thanks, and is there a way to get access to the schema.data?

**Comment by sunli829** [comment]
> Thanks, and is there a way to get access to the schema.data?
> 
> I just ask because I'm implementing authentication, so before executing the request I'm trying to load the session from the request Authorization Bearer token, so I'm trying to call directly a fn that gets the session from the token and then use request.data(session) to pass the session to request

Need to use `Context::data` function.
This function first looks up from `Request.data`, if it does not exist, looks up from `Schema.data`.

The `fn Request.data` function is used to bind data to the Request, and the `fn SchemaBuilder::data` function is used to bind data to the Schema. The difference is that some data is global, such as `DbPool`. And some data is per request, such as `Cookie`.

**Comment by jescobar** [comment]
Thanks a lot! I will try with the examples!!
