### ISSUE TITLE
make Federation + description work

### ISSUE THREAD

**Issue by Boshen** [async-graphql/async-graphql#432]
`src/registry/export_sdl.rs` currently omits description text in exported sdl `{ _service { sdl }`, but it's actually supported by Apollo Gateway. 

relevant source code and test:
https://github.com/apollographql/federation/blob/main/federation-js/src/service/printFederatedSchema.ts#L384-L405
https://github.com/apollographql/federation/blob/main/federation-js/src/service/__tests__/buildFederatedSchema.test.ts#L76-L129

**Comment by sunli829** [comment]
Released in `v2.5.10`

**Comment by Boshen** [comment]
🌹
