### ISSUE TITLE
Extra information with file upload

### ISSUE THREAD

**Issue by phungtranminh** [async-graphql/async-graphql#435]
I managed to get file upload works with `async-graphql` I wonder if I can pass along some extra fields with the file, so that the server has more context of the file?

**Comment by sunli829** [comment]
> I managed to get file upload works with `async-graphql` I wonder if I can pass along some extra fields with the file, so that the server has more context of the file?

As shown below, `title` is the extra field of the file.

```rust
async fn upload_file(&self, title: String, upload: Upload) {
 ...
}
```

**Comment by phungtranminh** [comment]
Great thanks, I managed to make it work
