### ISSUE TITLE
A way to rename chrono graphql types ?

### ISSUE THREAD

**Issue by dhendrie91** [async-graphql/async-graphql#437]
Im currently using the provided graphql scalar output types for things like NaiveDate and NaiveDateTime, these work well however soon i will have to implement types which are compatible with an existing ruby/rails graphql service, for 99% of types this is fine but for inbuilt types like Datetimes it becomes problematic: 

An ISO8601 datetime type using the current async graphql chrono types is called `NaiveDateTime` however in ruby the equivalent type is called `ISO8601DateTime` this causes issues when using graphql mesh or schema stitching. 

I'm wondering if there is a way to rename the `NaiveDateTime` type to `ISO8601DateTime` in my codebase ? 

I have seen the documentation for custom scalar types using the `Scalar!` macro but not sure how this can be done for an external type like chrono `NaiveDateTime`

**Comment by sunli829** [comment]
I will add this feature later. 🙂

**Comment by sunli829** [comment]
Released in `v2.5.12`.

**Comment by sunli829** [comment]
> Im currently using the provided graphql scalar output types for things like NaiveDate and NaiveDateTime, these work well however soon i will have to implement types which are compatible with an existing ruby/rails graphql service, for 99% of types this is fine but for inbuilt types like Datetimes it becomes problematic:
> 
> An ISO8601 datetime type using the current async graphql chrono types is called `NaiveDateTime` however in ruby the equivalent type is called `ISO8601DateTime` this causes issues when using graphql mesh or schema stitching.
> 
> I'm wondering if there is a way to rename the `NaiveDateTime` type to `ISO8601DateTime` in my codebase ?
> 
> I have seen the documentation for custom scalar types using the `Scalar!` macro but not sure how this can be done for an external type like chrono `NaiveDateTime`

You can also use the `NewType` macro.

**Comment by dhendrie91** [comment]
Hi @sunli829 i got round to testing the new function, however it returns a compiler error, I'm using it as follows (simplified)

``` rust
 Schema::build(Query, EmptyMutation, SubscriptionRoot)
.override_name::<NaiveDateTime>("ISO8601DateTime")
.finish();
```

Compiler returns the following error 
```
error[E0632]: cannot provide explicit generic arguments when `impl Trait` is used in argument position
  --> src/graph/schema.rs:35:30
   |
35 |             .override_name::<NaiveDateTime>("ISO8601DateTime")
   |                              ^^^^^^^^^^^^^ explicit generic argument not allowed

error: aborting due to previous error
```

I also tried the new type marco, it doesn't seem to rename the actual output type on the schema. 
 so for something like 
 
 ``` rust

**Comment by sunli829** [comment]
Sorry, I found that my previous implementation was incorrect, and I realized that renaming a type is very difficult, so I will delete the `SchemaBuilder::override_name` function.

**Comment by sunli829** [comment]
Released in `v2.7.2` 🙂

**Comment by dhendrie91** [comment]
Tested the new macro options and works perfectly. Many Thanks :smile:  ... closing the issue

**Comment by namnm** [comment]
@dhendrie91 @sunli829 
Do we have any way to rename it without introducing a new struct?
