### ISSUE TITLE
field `loader` of struct `DataLoader` is private

### ISSUE THREAD

**Issue by ejez** [async-graphql/async-graphql#441]
In the root query, I have multiple resolver functions that use the database, some of them via a dataloader.

For now I needed to use two separate db pools:
```rust
    Schema::build(query, mutation, subscription)
        .data(pg_pool)
        .data(DataLoader::new(PgLoader(loader_pg_pool)))
        .finish()
```

One pool is used via the dataloader:
```rust
ctx
  .data::<DataLoader<PgLoader>>()?
  .load_one(MyModelKey(id))
  .await?
```

The other pool is used directly:
```rust
sqlx::query_as!(MyModel, db_query)
  .fetch_all(ctx.data::<PgPool>()?)
  .await?
```

So, instead of having two pools, I wanted to have only one and reuse the dataloader pool:
```rust
sqlx::query_as!(MyModel, db_query)
  .fetch_all(&ctx.data::<DataLoader<PgLoader>>()?.loader.0)
  .await?
```
However this does not work, because the `loader` field is private.

Would you think that making that field public might be useful?

**Comment by sunli829** [comment]
I recommend using `Arc` to wrap this pool object. 😁

```rust
 let pg_pool = Arc::new(pg_pool);
  Schema::build(query, mutation, subscription)
        .data(pg_pool.clone())
        .data(DataLoader::new(PgLoader(pg_pool)))
        .finish()
```

**Comment by ejez** [comment]
Thanks for the very quick answer! :smiley: 

Will do that...

I'm thinking that the `loader` field is provided anyway by the user via the `DataLoader::new(loader)` function... so there will be also no harm in making it visible to him...

Another side question, is making multiple pools vs one pool have any effects on the app or db performance...

**Comment by sunli829** [comment]
> I'm thinking that the `loader` field is provided anyway by the user via the `DataLoader::new(loader)` function... so there will be also no harm in making it visible to him...

You are right, but it seems unnecessary. 😁

**Comment by ejez** [comment]
> but it seems unnecessary

I see your point, hiding the internals will allow for flexible refactoring if needed :sunglasses: 

However, generally speaking, it seems a little weird to swallow something the user has provided and prevent him from accessing it :worried:

How about:
```rust
impl<T> DataLoader<T> {
    /// Get the loader.
    pub fn loader(&self) -> &T {
        &self.loader
    }
```
(still insisting :joy:)

**Comment by sunli829** [comment]
> > but it seems unnecessary
> 
> I see your point, hiding the internals will allow for flexible refactoring if needed 😎
> 
> However, generally speaking, it seems a little weird to swallow something the user has provided and prevent him from accessing it 😟
> 
> How about:
> 
> ```rust
> impl<T> DataLoader<T> {
>     /// Get the loader.
>     pub fn loader(&self) -> &T {
>         &self.loader
>     }
> ```
> 
> (still insisting 😂)

Well, I will add this. 😄

**Comment by ejez** [comment]
:+1: many thanks :tada:
