### ISSUE TITLE
How to pass some configuration

### ISSUE THREAD

**Issue by phungtranminh** [async-graphql/async-graphql#443]
I need to pass some configuration (String) from env to `Query` or `Mutation`.

How to achieve this, `data` is type bound so unless I wrap them in a struct, it is not possible?

**Comment by sunli829** [comment]
You can use JSON type.

https://docs.rs/async-graphql/2.5.13/async_graphql/types/struct.Json.html

**Comment by phungtranminh** [comment]
Thanks
