### ISSUE TITLE
Correct way to convert a struct to Value

### ISSUE THREAD

**Issue by phungtranminh** [async-graphql/async-graphql#444]
I have a struct like this

```
#[derive(Serialize, Deserialize)]
struct Store {}
```

I want to get `Value::Object` and am currently doing something like this

```
Value::from_json(serde_json::to_value(store).unwrap()).unwrap()
```

Is it correct? does it double handle the data?

**Comment by sunli829** [comment]
https://docs.rs/async-graphql/2.5.13/async_graphql/fn.to_value.html

**Comment by phungtranminh** [comment]
👏🙇‍♀️
