### ISSUE TITLE
Validator custom on the whole object.

### ISSUE THREAD

**Issue by AurelienFT** [async-graphql/async-graphql#445]
## Description of the feature

I would like to be able to create custom validator and will be able to have the others fields of the structure in this validator to make checks more complex

## Code example (if possible)

```rust

    fn ValidateUsername(user: User) -> bool {
      email.contains(username)
    }

    #[derive(InputObject)]
    struct User {
        pub id: String,
        #[graphql(validator(ValidateUsername)))]
        pub username: String,
        pub email: String
    }
```

Do you think it's possible ? Do you think it's a good idea to implement ? Do you have a better design ? I can help with implementation if needed.

**Comment by sunli829** [comment]
> ## Description of the feature
> I would like to be able to create custom validator and will be able to have the others fields of the structure in this validator to make checks more complex
> 
> ## Code example (if possible)
> ```rust
>     fn ValidateUsername(user: User) -> bool {
>       email.contains(username)
>     }
> 
>     #[derive(InputObject)]
>     struct User {
>         pub id: String,
>         #[graphql(validator(ValidateUsername)))]
>         pub username: String,
>         pub email: String
>     }
> ```
> 
> Do you think it's possible ? Do you think it's a good idea to implement ? Do you have a better design ? I can help with implementation if needed.

Good idea, looks very good!

**Comment by AurelienFT** [comment]
Ok I will work on it.

**Comment by rumanbsl** [comment]
On related not, what would be the best approach to integrate validation library like https://github.com/Keats/validator? Especially when functionality overlaps with  `async_graphql::validators`.

**Comment by AurelienFT** [comment]
Oh yes it could be cool instead of full recode the same thing.

**Comment by AurelienFT** [comment]
> Ok I will work on it.

I don't have time those days. If anyone wanna contribute on this, feel free.

**Comment by cptrodgers** [comment]
I'm trying to work on this (I need this in my project) but I prefer 2 things different:
- The validator not in field, should in the struct declaration (Correct Semantic). You validate whole object, you should declare on the struct instead of field.
- Return will be `Result<(), Error>` to compatible with existing mechanism of async-graphql and provide more powerful context for the error.

Maybe Example:

```rust
fn ValidateUsername(user: User) -> Result<(), async_graphql::Error> {
  if email.contains(username) {
    Ok(())
  } else {
    Err(async_graphql::Error::new("Incorrect data").with_extensions(|_, ext| ext.set("code", 400)))
  }
}

#[derive(InputObject)]
#[grapql(validator(ValidateUsername))]
struct User {
    pub id: String,
    pub username: String,
    pub email: String
}
```
