### ISSUE TITLE
Tracing with async-graphql

### ISSUE THREAD

**Issue by kennetpostigo** [async-graphql/async-graphql#446]
Are there any examples of how to use `OpenTracing`/`OpenTelemetry` with `async-graphql`?

**Comment by sunli829** [comment]
This should help you, you just need to initialize the `tracing_subscriber` correctly, and then add the `Tracing` extension when building the `Schema`.

https://github.com/open-telemetry/opentelemetry-rust/blob/main/examples/tracing-grpc/src/server.rs

**Comment by kennetpostigo** [comment]
Thank you @sunli829 , will look into it
