### ISSUE TITLE
Fragments on subscribtions nevers push data to client

### ISSUE THREAD

**Issue by IcanDivideBy0** [async-graphql/async-graphql#45]
Hello,
When using fragments in subscriptions, I never receive any notifications in the websocket

This works:
```gql
subscription s {
  order(id: "5eabbe77103ca80276efdf70") {
    id
    createdAt
  }
}
```
This doesn't:
```gql
subscription s {
  order(id: "5eabbe77103ca80276efdf70") {
    id
    ...orderFrag
  }
}

fragment orderFrag on Order {
  id
  createdAt
}
```

tested with both playground and an apollo client

**Comment by sunli829** [comment]
Thank you. Let me see what caused it.😁

**Comment by nicolaiunrein** [comment]
Just checked on my system running async-graphql 1.9.17 and async-graphql-actix-web 1.1.6
I ran the below code and it worked in playground:
```GraphQL
fragment clientFields on Client {
  id
  ip
  port
  name
}

subscription clients {
  clients {
    ...on ClientCreated { # a Union
      client {
        ...clientFields
      }
    }
  }
}
```

Could you specify which version you are running on and show some failing example code?

**Comment by sunli829** [comment]
The problem did exist, I tested it with `async-graphql/examples/actix-web/subscription`, and when I made the following request, I didn't get a message.

```graphql
subscription s {
  books {
    id
    ... bookFrag
  }
}

fragment bookFrag on BookChanged {
  id
  mutationType
}
```

**Comment by sunli829** [comment]
Upgrading to the latest version, I solved the problem.

**Comment by IcanDivideBy0** [comment]
Thanks! works like a charm now :ok_hand:
