### ISSUE TITLE
async graphql client

### ISSUE THREAD

**Issue by kennetpostigo** [async-graphql/async-graphql#450]
Hi! By any chance, do you know if there is a graphql client that is runtime agnostic? I was looking to call my `async_graphql` server from some rust code but couldn't find any clients that were easy to use

**Comment by leebenson** [comment]
We use [graphql-client](https://github.com/graphql-rust/graphql-client) at https://vector.dev/.

You can read a little about how we use it with async-graphql at https://vector.dev/blog/graphql-api/.

One feature it lacks is subscription support. We wound up building a subscription client based on tungstenite to connect to it. You can find our API client code in https://github.com/timberio/vector/tree/master/lib/vector-api-client

Hope that helps!

**Comment by kennetpostigo** [comment]
@leebenson it does, thanks for sharing :)
