### ISSUE TITLE
Logger extension doesn't seem to do anything

### ISSUE THREAD

**Issue by cortopy** [async-graphql/async-graphql#453]
## Expected Behavior

Enabling the Logger would result in one log entry per query

## Actual Behavior

Everything is working but I get no logs

## Steps to Reproduce the Problem

1. Install `log` crate
2. Enable `log` feature
3. Add logger like:

```rust

use async_graphql::{extensions::Logger, EmptySubscription, Schema};
...

Schema::build(RootQuery, RootMutation, EmptySubscription)
            .extension(Logger)
            .finish()
```

## Specifications

- Version: 2.5.9
- Platform: Linux
- Subsystem: with actix

**Comment by sunli829** [comment]
You should install a logger, such as: `env_logger`, `simple_logger`.

**Comment by cortopy** [comment]
I already tried with `env_logger` but same result. I get no output in terminal. If I use actix Logger it works for actix logs. I thought maybe they don't play well together, but async-graphql doesn't log anything even if I disable logs for actix server

**Comment by sunli829** [comment]
I tested it and the log can be output normally. Have you set this environment variable?

```
RUST_LOG=async-graphql
```

**Comment by cortopy** [comment]
That was the issue. I had this:

```rust
std::env::set_var("RUST_LOG", "async_graphql=info");
env_logger::init();
```

but it has to be

```rust
std::env::set_var("RUST_LOG", "async-graphql=info");
env_logger::init();
```

for actix web it's `actix_web` not `actix-web`

Now it's a different issue. With the snippet I posted I'm getting all logging levels. I'm even getting TRACE. Is this expected?

**Comment by cortopy** [comment]
It's all working now for me!!

Is there a way I can write a paragraph about this as docs somewhere. I'd do a PR but most links for the extensions in the README are broken

**Comment by sunli829** [comment]
The links to extensions in the README are not broken, but they need to be opened on `docs.rs`
If you want, you can use rustdoc to explain the `Logger` type in more detail.
Thank you very much!

https://github.com/async-graphql/async-graphql/blob/master/src/extensions/logger.rs

**Comment by cortopy** [comment]
just done a small PR
