### ISSUE TITLE
Feeding a `DataLoader`.

### ISSUE THREAD

**Issue by meh** [async-graphql/async-graphql#455]
## Description of the feature

Let's say I'm querying for something that is not the ID, I'd like to be able to feed to the `DataLoader` all the objects I got by their ID.

## Code example (if possible)

```rust
things = query("SELECT * FROM thing WHERE thing.is_good");
loader.feed(things.into_iter().map(|t| (t.id, t));
```

**Comment by jonaslimads** [comment]
I didn't quite get the question. You can query a data loader by any kind of data, as long as you implement the Loader trait with that type:

In the example below I'm implementing the trait to use a Uuid. The Value type can be anything, as long as **query and feed the hashmap by the type** you are working with.

```rust
impl Loader<Uuid> for PersonRepository {
    type Value = PersonEntity;

    type Error = RepositoryError;

    async fn load(
        &self,
        ids: &[Uuid],
    ) -> Result<HashMap<Uuid, Self::Value>, Self::Error> {
        let sql = format!(
            r#"
            SELECT
                person.id,
                person.name,
                person.user_id
            FROM person
            JOIN user ON user.id = person.user_id
            WHERE user.id IN ({})
            "#,
            ids
                .iter()
                .map(|id| format!("UUID_TO_BIN('{}')", id.to_string()))
                .join(",")
        );

        let rows = query_as::<_, PersonEntity>(sql.as_str())
            .fetch_all(&self.pool)
            .await
            .unwrap();

        Ok(rows
            .into_iter()
            .fold(HashMap::<Uuid, Self::Value>::new(), |mut acc, v| {
                &acc.entry(v.user_id).or_insert(v);
                acc
            }))
    }

}                
```

**Comment by sunli829** [comment]
> ## Description of the feature
> Let's say I'm querying for something that is not the ID, I'd like to be able to feed to the `DataLoader` all the objects I got by their ID.
> 
> ## Code example (if possible)
> ```rust
> things = query("SELECT * FROM thing WHERE thing.is_good");
> loader.feed(things.into_iter().map(|t| (t.id, t));
> ```

So you want to initialize the `DataLoader` with existing data before querying, right?

**Comment by meh** [comment]
Maybe I'm misunderstanding how dataloader works, my assumption was it would cache already queried stuff within the same request, is this not the case?

**Comment by meh** [comment]
https://docs.rs/dataloader/0.14.0/dataloader/cached/struct.Loader.html#method.prime_many this is what I'm asking for, but I think I will just use that crate instead.

**Comment by sunli829** [comment]
> Maybe I'm misunderstanding how dataloader works, my assumption was it would cache already queried stuff within the same request, is this not the case?

Yes, this is how it works, but since you have loaded all the data yourself, why do you need a `DataLoader`?

**Comment by meh** [comment]
Because it's not all the data for the entire query, it's just one field.

**Comment by sunli829** [comment]
Need to add a cache to `DataLoader`, I am doing this.

**Comment by meh** [comment]
Thanks!

**Comment by sunli829** [comment]
I added this feature to the `master` branch, you can try it.

**Comment by meh** [comment]
Nice, looks good, it would be nice if the hashmap cache was also generic over the hash state, so I could use an fnvmap for my use case.

**Comment by sunli829** [comment]
This is a good suggestion, I have already added this feature. 🙂

**Comment by meh** [comment]
Thanks! You're the best :D
