### ISSUE TITLE
Introspection Guards/Conditional Introspection

### ISSUE THREAD

**Issue by menixator** [async-graphql/async-graphql#456]
I was wondering if there was any way to conditionally disable introspection. I'm planning to completely disable introspection for users who are not logged in and only enabling it for logged in users who have administrative access. Is this currently possible with `async_graphql`? I skimmed through the source code and from what I can see, it doesn't look like it is possible unless I built two schema instances.

**Comment by sunli829** [comment]
Currently, you can only call `SchemaBuilder::disable_introspection` when building the Schema to disable introspection. I will add a `Request::disable_introspection` function to disable introspection based on the current logged in users.

**Comment by sunli829** [comment]
Released in `v2.7.1` 😁

**Comment by menixator** [comment]
Neat. I'll test it out and see if there are any issues. For now, I'm closing this ticket.
