### ISSUE TITLE
Create context for unit test

### ISSUE THREAD

**Issue by ctopher7** [async-graphql/async-graphql#458]
is there any simple way for creating context for unit test? thanks

**Comment by sunli829** [comment]
> @sunli829 thanks for your fast response, here are some examples
> 
> ```
> use async_graphql::{Context,SimpleObject};
> struct QueryRoot;
> 
> #[derive(SimpleObject,Default)]
> struct GqlResponse{
>     success: bool
> }
> #[Object]
> impl QueryRoot{
>     async fn gql_handler(ctx:Context<'_>) -> GqlResponse{
>          // do something with context
>          GqlResponse::default()
>     }
> }
> 
> #[cfg(test)]
> mod test{
>      #[tokio::test]
>      async fn test_gql_handler(){
>            let query_root = super::QueryRoot;
>            assert_eq!(query_root.gql_handler(NEED CONTEXT HERE).await, super::GqlResponse::default());
>      }
> }
> ```

You can't do this. Creating a `Context` involves many things. I suggest you create a `Schema` and then query it.

**Comment by ctopher7** [comment]
okay, thank you for your response @sunli829
