### ISSUE TITLE
https://async-graphql.github.io gives 404

### ISSUE THREAD

**Issue by nicolaiunrein** [async-graphql/async-graphql#461]
## Expected Behavior
I would expect `https://async-graphql.github.io/` to redirect to `https://async-graphql.github.io/async-graphql/en/index.html`

## Actual Behavior
It shows a 404 Error

**Comment by sunli829** [comment]
I don't know how to configure this. 😂

**Comment by nicolaiunrein** [comment]
You need to create a repository `async-graphql.github.io`. Its content of the master branch will be rendered on async-graphql.github.io. You could create a single file `index.html` with content
```html
<!DOCTYPE html>
<html>
   <head>
      <meta http-equiv = "refresh" content = "0; url = https://async-graphql.github.io/async-graphql/en/index.html" />
   </head>
</html>
```
in order to redirect to the book or put any content you like.

**Comment by sunli829** [comment]
I have done this, thank you! 🙂
