### ISSUE TITLE
What is the actual way to serialize to and deserialize from serde_json::Value?

### ISSUE THREAD

**Issue by jonaslimads** [async-graphql/async-graphql#462]
First of all, thanks for the awesome library! It has been a pleasure to work with your lib.

I'm trying to input and output some flexible JSON, which comes from/to JSON MySQL columns via sqlx. When I have a struct like this:

```rust
#[derive(Debug, Clone, SimpleObject)]
pub struct Address {
    pub extra: Option<serde_json::Value>,
}
```
it gives me the error:

```
the trait bound `serde_json::Value: async_graphql::Type` is not satisfied
required because of the requirements on the impl of `async_graphql::Type` for `Option<serde_json::Value>`
required by `create_type_info`rustcE0277
input.rs(18, 24): Exact error occurred here
the trait bound `serde_json::Value: OutputType` is not satisfied
required because of the requirements on the impl of `OutputType` for `Option<serde_json::Value>`
```

The only mention to JSON in the book was this:
https://async-graphql.github.io/async-graphql/en/quickstart.html?highlight=json#output-the-query-results-as-json

I know the goal is to have the GraphSQL schema as static as possible, but I couldn't find a clear way to make Value work with serde_json::Value. I ended up manually converting serde_json::Value to HashMap<String, Any>. but it does not look like the right solution.

Is there any straighforward way? Thanks a lot.

**Comment by sunli829** [comment]
> First of all, thanks for the awesome library! It has been a pleasure to work with your lib.
> 
> I'm trying to input and output some flexible JSON, which comes from/to JSON MySQL columns via sqlx. When I have a struct like this:
> 
> ```rust
> #[derive(Debug, Clone, SimpleObject)]
> pub struct Address {
>     pub extra: Option<serde_json::Value>,
> }
> ```
> 
> it gives me the error:
> 
> ```
> the trait bound `serde_json::Value: async_graphql::Type` is not satisfied
> required because of the requirements on the impl of `async_graphql::Type` for `Option<serde_json::Value>`
> required by `create_type_info`rustcE0277
> input.rs(18, 24): Exact error occurred here
> the trait bound `serde_json::Value: OutputType` is not satisfied
> required because of the requirements on the impl of `OutputType` for `Option<serde_json::Value>`
> ```
> 
> The only mention to JSON in the book was this:
> https://async-graphql.github.io/async-graphql/en/quickstart.html?highlight=json#output-the-query-results-as-json
> 
> I know the goal is to have the GraphSQL schema as static as possible, but I couldn't find a clear way to make Value work with serde_json::Value. I ended up manually converting serde_json::Value to HashMap<String, Any>. but it does not look like the right solution.
> 
> Is there any straighforward way? Thanks a lot.

You can use `Json` type to wrap `serde_json::Value`.

https://docs.rs/async-graphql/2.7.2/async_graphql/types/struct.Json.html

**Comment by sunli829** [comment]
I directly implemented `ScalarType` for `serde_json::Value`, so there is no need to wrap it again with `Json` type.

**Comment by jonaslimads** [comment]
Thanks for the quick response.

Yep, that worked great:

```rust
// output

pub struct QueryRoot;
#[Object]
impl QueryRoot {
    async fn output(&self, context: &Context<'_>) -> async_graphql::Json<serde_json::Value> {
        let john = serde_json::json!({
            "name": "John Doe",
            "age": 43,
            "phones": [
                "+44 1234567",
                "+44 2345678"
            ]
        });
        async_graphql::Json::from(john)
    }
}

// input

#[derive(Debug, Clone, InputObject)]
pub struct Input {
    pub address: Json<serde_json::Value>,
    pub extra: Option<Json<serde_json::Value>>,
}

pub struct Mutation;
#[Object]
impl Mutation {
    async fn add_address(&self, context: &Context<'_>, input: Input) -> Result<bool> {
        use std::ops::Deref;
        let Input { address, extra } = input;
        let address = address.deref();
        let extra = match extra {
            Some(ref v) => Some(v.deref()),
            None => None,
        };
        println!("{:?} {:?}", address, extra);
        Ok(true)
    }
}
```
