### ISSUE TITLE
Can the logger be redacted?

### ISSUE THREAD

**Issue by Bajix** [async-graphql/async-graphql#463]
We'd like to be able to use the logger extension but I'm not seeing anyway to redact information. How does one protect password from being logged in the below example?

```
async fn login(&self, email: String, password: String) -> FieldResult<TokenSet>;
```

**Comment by sunli829** [comment]
This is currently not supported, I need to think about how to implement this feature.

**Comment by meh** [comment]
Interested in this as well, maybe an option for the attributes to keep it secret?

**Comment by sunli829** [comment]
I am adding support for this feature.

**Comment by sunli829** [comment]
I added a `secret` attribute to the master branch.

**Comment by sunli829** [comment]
Here is the example:

https://github.com/async-graphql/async-graphql/blob/6aa191fba519b36978e546330d500edf195b7ce2/src/registry/stringify_exec_doc.rs#L290

**Comment by meh** [comment]
Looks good, thanks!

**Comment by scrogson** [comment]
Perhaps this should be called `redact`?
