### ISSUE TITLE
Cannot use tokio in subscription

### ISSUE THREAD

**Issue by reza-ebrahimi** [async-graphql/async-graphql#465]
Cannot use tokio in subscription resolvers.

**Version:**

```
async-graphql = "2.5.0"
tokio = { version = "1.4.0", features = ["full"] }
```

**Platform:**

 ```
Linux dev 5.4.0-70-generic #78~18.04.1-Ubuntu SMP Sat Mar 20 14:10:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Code:**
```rust
use tokio::process::Command;

#[Subscription]
impl TestSubscription {
  async fn test(&self, _ctx: &Context<'_>) -> Result<impl Stream<Item = String>> {
    let output = Command::new("cmd").output();
    let output = output.await;
    println!("{:?}", output); 

    // .....
  }
}
```

**Error:**

```console
thread 'actix-rt:worker:0' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime'
```

**Comment by nicolaiunrein** [comment]
I ran into the same problem today and did not have time to investigate any further but it seems that for me actix-cors depends on actix-rt 1.1 which depends on tokio pre 1.0. I think this might be the problem. Sorry I’m on mobile but thought it might help. Checking the output of `cargo tree` might help

**Comment by sunli829** [comment]
> I ran into the same problem today and did not have time to investigate any further but it seems that for me actix-cors depends on actix-rt 1.1 which depends on tokio pre 1.0. I think this might be the problem. Sorry I’m on mobile but thought it might help. Checking the output of `cargo tree` might help

It should be for this reason, `async-graphql` does not actually depend on any runtime.

**Comment by reza-ebrahimi** [comment]
@nicolaiunrein Thanks, I need a practical solution, The problem still exists.

**Comment by reza-ebrahimi** [comment]
I tested with `actix-web = "4.0.0-beta.5"` and it works! But I got a compile error:

```rust
error[E0308]: mismatched types
  --> src/main.rs:41:52
   |
41 |     WSSubscription::start(Schema::clone(&*schema), &req, payload)
   |                                                    ^^^^ expected struct `actix_web::request::HttpRequest`, found struct `HttpRequest`
```

**Comment by nicolaiunrein** [comment]
Yes that’s probably because of different versions of actix-http. aas @sunli829 said in #467 he wants to wait for actix-web 4.0 but maybe we should create a beta branch with updated dependencies until actix-web 4.0 is stable. So that people like you are not stuck. I personally switched to warp

**Comment by sunli829** [comment]
I added support for `actix-web-v4` on the branch of `actix-web-v4-beta`, so I will close this issue. If you have any questions, please reopen it.

**Comment by reza-ebrahimi** [comment]
@sunli829  Since your branch used `actix = "0.11.1"` instead of `actix = "0.10.0"` I have a compile error. related issue https://github.com/actix/actix-web/issues/2121

https://github.com/async-graphql/async-graphql/commit/d83fa2a81e2e3d34035f16bfe9a42065e54a5174#diff-aae064c60b31ffccd849f89d5e9b02add40f4ec0f39f5853674645c1c9dbab42R17

**Comment by sunli829** [comment]
I think you should switch to `actix-web-actors 4.0.0-beta.4`. 🙂

**Comment by reza-ebrahimi** [comment]
I tested that, Still I'm getting the compile error.

This is my Cargo.toml:

```toml
actix = "0.11.1"
actix-web = "4.0.0-beta.5"
actix-web-actors = "4.0.0-beta.4"
async-graphql = { git = "https://github.com/async-graphql/async-graphql", branch = "actix-web-v4-beta" }
async-graphql-actix-web = { git = "https://github.com/async-graphql/async-graphql", branch = "actix-web-v4-beta" }
```
