### ISSUE TITLE
fix async-graphql-actix-web dependency issues with different tokio versions

### ISSUE THREAD

**Issue by nicolaiunrein** [async-graphql/async-graphql#467]
## Expected Behavior
asnyc-graphql-actix-web should work within tokio 1.0 runtimes. 

## Actual Behavior
An error like in #465 most likely caused by the dependency on actix-http 2.2.0 which depends on tokio 0.2.6. 

## Steps to Reproduce the Problem
Depend on the newest version of actix-rt or tokio.

## Possible solutions 
Ideally async-graphql-actix-web should be runtime independent but that would mean dropping the dependency on actix-http. Alternatively update actix-http to the newest beta but that would force all users to upgrade their stack to tokio 1.0.

**Comment by sunli829** [comment]
I think we should wait for `actix-web-v4`. 😄

**Comment by nicolaiunrein** [comment]
For anyone reading this until actix-web 4.0 is stable: use the `actix-web-v4-beta` branch of this project.

**Comment by lionkeng** [comment]
> For anyone reading this until actix-web 4.0 is stable: use the `actix-web-v4-beta` branch of this project.

@nicolaiunrein do you have an example of what your `Cargo.toml` dependencies look like? I can't seem to get it to compile and run into issue #489. Thanks.
