### ISSUE TITLE
Subscription stream doesn't stop/drop when client unsubscribes

### ISSUE THREAD

**Issue by reza-ebrahimi** [async-graphql/async-graphql#478]
**Client side:**
React `useSubscription` hook in a simple component.

**Server side:** 
A `subscription` resolver, that returns an `integer` stream.

**Problem:**
When react component `unmount`s the `useSubscription` hook, It doesn't unsubscribe in server side. 
Related issue in client side https://github.com/apollographql/apollo-client/issues/7964.

It is not  clear which side (client or server) that the problem is coming from. It may be a low level protocol implementation problem IMO.

**Hint:** 
It works with `async-graphql` playground, With clicking on stop button of playground, the stream in server side is dropping, but with using react hook, it is not unsubscribe and still continue to stream values.
One of the reasons the playground works is, with clicking stop button it closes the underlying `websocket` session.

**Client side code:**

```javascript
const TestComponent = () => {
  const { loading, error, data } = useSubscription(SUBSCRIPTION);
  
  useEffect(() => {
    return () => {
      // unsubscribe here
    };
  }, []);

  return <div>TestComponent</div>;
};
```

**Server side code:**

```rust
struct TestInterval {
  interval: Option<tokio::time::Interval>,
}

impl TestInterval {
  pub fn new(millis: u64) -> Self {
    Self {
      interval: Some(tokio::time::interval(Duration::from_millis(millis))),
    }
  }
}

impl Stream for TestInterval {
  type Item = Option<i32>;
  fn poll_next(mut self: Pin<&mut Self>, cx: &mut std::task::Context<'_>) -> std::task::Poll<Option<Self::Item>> {
    if self.interval.as_mut().unwrap().poll_tick(cx) == std::task::Poll::Pending {
      return std::task::Poll::Pending;
    }
    std::task::Poll::Ready(Some(Some(0)))
  }
}

impl Drop for TestInterval {
  fn drop(&mut self) {
    if let Some(interval) = self.interval.take() {
      drop(interval);
    }

    println!("[DROP] TestInterval");
  }
}

#[derive(Clone, Default)]
pub struct StatSubscription;

#[Subscription]
impl StatSubscription {
  async fn stat(&self, ctx: &Context<'_>) -> impl Stream<Item = Option<i32>> {
    TestInterval::new(1000)
  }
}
```

**Comment by sunli829** [comment]
Thank you, I will start investigating this issue when I finish the work at hand.

**Comment by sunli829** [comment]
After my test, `async-graphql` seems to have no problem, so please confirm that when react component `unmount`, did the browser send a `stop` request to the server?

**Comment by reza-ebrahimi** [comment]
Unfortunately I didn't know what happens in client's lower levels.

**Comment by leebenson** [comment]
Look at the network tab and view WebSocket messages. That should make it clearer whether this is a client-side issue.

Also, when exactly are you unsubscribing? Your sample code doesn't make it clear when you're actually unmouting.

**Comment by reza-ebrahimi** [comment]
![mount](https://user-images.githubusercontent.com/11276982/114565386-e1e83700-9c79-11eb-8102-a3247e730d9b.png)

**Comment by reza-ebrahimi** [comment]
I have create a test project for both client and server, Check it out: https://github.com/reza-ebrahimi/TestSubscrtiptionBug

**Comment by reza-ebrahimi** [comment]
I have created a test project for both client and server, Check it out: https://github.com/reza-ebrahimi/TestSubscrtiptionBug

**Comment by sunli829** [comment]
I found that when the component was `mount`, the subscription request was sent twice, and when the component was `unmount`, the unsubscription request was sent only once. It seems that this is a client problem.


![image](https://user-images.githubusercontent.com/20092316/114639481-8f9e2900-9d00-11eb-9be6-55afb58ee1e5.png)

**Comment by reza-ebrahimi** [comment]
You are right, I have noticed this in my tests.

**Comment by reza-ebrahimi** [comment]
You are right, I noticed this in my tests.
