### ISSUE TITLE
Passing Tide request extension values into GraphQL request context

### ISSUE THREAD

**Issue by fominok** [async-graphql/async-graphql#480]
Hello, I have a question regarding async-graphql usage with Tide:

There is a middleware that sets request extension value, say, a `User` with `.ext(...)`, then using `async-graphql-tide` I convert a Tide request into GraphQL request and `async_graphql_tide::receive_request` takes it by value, so I cannot simply move `User` out of Tide request extensions and put it into GraphQL request context, so I need to make unnecessary clone.

Is there any clean way to make request extension values accessible in GraphQL handlers with `.data()` ?

**Comment by sunli829** [comment]
Maybe you can use `Arc<User>`?

**Comment by fominok** [comment]
This might work, but looks more like a workaround, as it could be solved just by moving from `ext` to `context` without shared ownership I suppose; is it possible to implement tide request -> graphql request conversion respecting the extension values?

**Comment by sunli829** [comment]
This seems impossible, `tide` does not provide a function such as `Request::remove_ext`.

**Comment by fominok** [comment]
Oh, I see, I'll ask on tide's repo regrading this, thank you
