### ISSUE TITLE
Validator rules as custom directives on introspected graphql schema?

### ISSUE THREAD

**Issue by bram209** [async-graphql/async-graphql#482]
Syncing the validation rules from the frontend to the backend is a tedious and time-consuming process, therefore I would like to be able to introspect the schema in such a way that I will be able to inspect the validation rules.  Would it be possible to emit custom directives for this purpose?

My plan is to generate forms including client-sided validation in React from the introspection result.

**Comment by bram209** [comment]
I saw https://github.com/async-graphql/async-graphql/issues/148 which looks related,

@sunli829 are you still planning to support custom directives and if so, could you describe the problems implementing that feature?
Maybe I can help/contribute with a PR

**Comment by sunli829** [comment]
> I saw #148 which looks related,
> 
> @sunli829 are you still planning to support custom directives and if so, could you describe the problems implementing that feature?
> Maybe I can help/contribute with a PR

I found that this feature doesn't make much sense. In fact, it can be replaced by `Extension`. I would love to hear your thoughts. 😁

**Comment by bram209** [comment]
I think I was ignorant about the spec, the [graphql spec](https://spec.graphql.org/June2018/#sec-Schema-Introspection) does not say anything about exposing the usage of directives on fields & types during introspection.

In that case, I will figure out another way to expose the `RoleGuard` and field validator metadata to the frontend for client-side validation. As of now, I cannot think of any valid use case to have "custom directives" and agree that with the current custom guards & validators you can pretty much cover everything.

Btw, thank you for this great library and the effort you have put into it!
