### ISSUE TITLE
2 structs with a same name

### ISSUE THREAD

**Issue by phungtranminh** [async-graphql/async-graphql#484]
I have 2 structs with a same name, but they have different fields.

Both are `SimpleObject`, it seems like `async_graphql` pick up one instead of the other when the struct is being used.

Renaming the struct slightly solves the issue. I wonder if it is intended behaviour? and is there a way to address it without renaming the structs?

Thanks in advance.

**Comment by sunli829** [comment]
Since their fields are different, they are two different objects and must use different names.

**Comment by phungtranminh** [comment]
Ok thanks, yeah it is not too hard to keep them in different names.
