### ISSUE TITLE
Derive simple union from enum (values with named fields) directly

### ISSUE THREAD

**Issue by bram209** [async-graphql/async-graphql#488]
## Description of the feature
When you have a rust enum where all values have named fields, it would be nice to be able to derive a graphql `Union` type from it.

## Code example
```rust
#[derive(SimpleUnion)]
pub enum Shape {
    Circle { radius: f32 },
    Square { width: f32 },
    Rectangle { width: f32, height: f32 },
}
```

**Comment by sunli829** [comment]
This looks very good, I will implement it immediately, when I finish this feature, I hope you can help me add the chapter on `SimpleUnion` in `Book`. 😁

**Comment by sunli829** [comment]
Sorry, I worked hard for a long time, but in the end this feature could not be completed due to an internal lifetime.

**Comment by sunli829** [comment]
Sorry, I worked hard for a long time, but in the end this feature could not be completed due to an internal lifetime.

**Comment by bram209** [comment]
> Sorry, I worked hard for a long time, but in the end this feature could not be completed due to an internal lifetime.

Ah too bad : (

What if this:
```rust
#[derive(SimpleUnion)]
pub enum Shape {
    Circle { radius: f32 },
    Square { width: f32 },
    Rectangle { width: f32, height: f32 },
}
```

would be expanded to this:

```rust
#[derive(SimpleUnion)]
pub enum Shape {
    Circle { radius: f32 },
    Square { width: f32 },
    Rectangle { width: f32, height: f32 },
}

impl From<Shape> for Union {
    .....map to `ShapeUnion`
} 

#[SimpleObject]
struct Circle {
    radius: f32,
}

#[SimpleObject]
struct Square {
    width: f32,
}

#[SimpleObject]
struct Rectangle {
    width: f32,
    height: f32,
}

#[derive(Union)]
enum ShapeUnion {
    Circle(Circle),
    Square(Square),
    Rectangle(Rectangle)
}
```
and then relax the trait bounds of resolvers to allow them to return things that can `Into` a graphql object type?

Feels a bit hacky tho...

**Comment by sunli829** [comment]
This is easy to implement, but it changes the structure of the original enum type, causing the IDE to be unable to recognize it. I don't think this is a good idea.

**Comment by bram209** [comment]
agree, should I close this issue or wanna keep it open?

**Comment by sunli829** [comment]
Close it first, and then open it after we find a better solution.
