### ISSUE TITLE
Why is Apollo Federation required to extend types?

### ISSUE THREAD

**Issue by KyleErhabor** [async-graphql/async-graphql#492]
Hello, I have a `Tag` type I wanted to extend to inherit default behavior across multiple inheritors. I could use an interface to provide the same functionality, but it feels weird since the interface needs to implement other interfaces (which is in a prerelease of GraphQL but I don't know if it works in async_graphql).

I noticed that the `extend` keyword is defined in the SDL generator, but it's restricted to the Apollo Federation. Why is that?

**Comment by sunli829** [comment]
> Hello, I have a `Tag` type I wanted to extend to inherit default behavior across multiple inheritors. I could use an interface to provide the same functionality, but it feels weird since the interface needs to implement other interfaces (which is in a prerelease of GraphQL but I don't know if it works in async_graphql).
> 
> I noticed that the `extend` keyword is defined in the SDL generator, but it's restricted to the Apollo Federation. Why is that?

Async-graphql does not currently support this, and the GraphQL specification does not explain the purpose of this keyword.

**Comment by jregistr** [comment]
On the `extend` keyword, I believe it's for people who define their schemas using SDL to be able to split the definition of a type or interface across multiple files. Ex:
filea.graphql
```gql
type Person {
  name: String!
}
```
fileb.graphql
```gql
extend type Person {
  purchases: [String]
}
```

But, if I under this framework (I'm new to experimenting w/ it), there isn't support for creating a schema via SDL; unlike a framework like [Netflix's DGS](https://netflix.github.io/dgs/getting-started/#creating-a-schema)

**Comment by cyberhck** [comment]
Hello @jregistr I'm not sure if you're still looking into this,

I've started working in graphql as well, and as far as I understand (I think I do, but I might be wrong) extend isn't for separate file there, it's for a completely different service to extend your type. That's what federation is.

That helps you write microservices which only care about domains.

In your example, `Person` type would be defined in accounts service, and the `extend type Person` would be defined in your payment service for example.

The way you reference correct entity is by using `@key` to define which field is your (like `id` is your identifier type)

**Comment by jregistr** [comment]
@cyberhck I think we might be talking about two different things here. `extend` has been a part of the [graphql spec](https://spec.graphql.org/June2018/#ObjectTypeExtension) for a while now; not a part of the federation spec. Far before federation, we used it to split the schema type defs by domain. But your point is well taken. `extend` is also used by federation to allow a different service to extend another's type.

`user.graphql`
```
type User {
  name: String!
  id: ID
}
```

`publishing data domain`
```gql
type Article {
  id: ID!
  summary: String!
}

extend type User {
  savedArticles: [Article]!
}
```
