### ISSUE TITLE
Disabling introspection  

### ISSUE THREAD

**Issue by Jerboas86** [async-graphql/async-graphql#494]
## Description of the feature
- Consider adding disabling introspection in [feature-comparison.md](https://github.com/async-graphql/async-graphql/blob/master/feature-comparison.md)
- Consider introspection disabled by default in released mode

**Comment by sunli829** [comment]
> Consider adding disabling introspection in feature-comparison.md
Welcome to PR. 😀

> Consider introspection disabled by default in released mode
I don't think this is necessary.

**Comment by Miaxos** [comment]
https://github.com/async-graphql/async-graphql/pull/581

**Comment by sunli829** [comment]
> https://github.com/async-graphql/async-graphql/pull/581

Thank you!😄
