### ISSUE TITLE
Supporting Dynamic, Programmatic Schema

### ISSUE THREAD

**Issue by GQAdonis** [async-graphql/async-graphql#495]
I love your library, but I need the ability to dynamically create a schema from metadata (e.g., JSON schema, a DSL, database reflection on tables, etc.) and update it when that metadata changes (e.g., tables are added to database, new JSON schema data is added, etc.).  In addition, I need a way to specify resolvers that can create the necessary query parameters for a database query (e.g., Mongo collections, Postgres JSON fields, whatever) to serve data back to the callers.  Is this possible in the current code base?  If not, what would you suggest?

The power to be able to allow for creating a schema that conforms to a business need at runtime is a huge differentiating factor for what I am building.  The [Netflix DGS Framework](https://netflix.github.io/dgs/advanced/dynamic-schemas/) provides a nice way to do this in Java, but I really want to use Rust for all the obvious reasons.

**Comment by sunli829** [comment]
No, Async-graphql is type-safe at compile time and cannot update the schema at runtime.

**Comment by ruseinov** [comment]
Yeah, we had a similar issue here: https://github.com/async-graphql/async-graphql/issues/30 .

The only way I see this working is if we could have a WASM runtime for dynamic schema similar to what they do in https://github.com/paritytech/substrate for runtime upgrades, but that's probably outside of scope for async-graphql. 

@sunli829 we are looking into something like this: https://netflix.github.io/dgs/advanced/dynamic-schemas/ .

**Comment by ruseinov** [comment]
One proposal here would be: how do we combine the type-safe schema defined within code and a schema possibly generate from json-schema coming from the database.
If we could achieve that - it'd be very powerful.

**Comment by sunli829** [comment]
I will close this issue because I have no plans to support dynamic schema.
