### ISSUE TITLE
proc macro returned error with InputObject 

### ISSUE THREAD

**Issue by bokuweb** [async-graphql/async-graphql#498]
I ran into following proc macro error when using `InputObject` with new type pattern.
Is this bug? If so, I'll try fix it later.

![image](https://user-images.githubusercontent.com/10220449/117250069-a35f2a00-ae7d-11eb-8428-0ecff4543f6c.png)

**Comment by sunli829** [comment]
This is a bug, `InputObject` is only allowed to take effect in struct containing named fields. 😁

**Comment by bokuweb** [comment]
@sunli829 Thanks for your quick response 😄 
Do you have any plan to support `tuple struct` ?
If not, How do I treat a tuple struct as an `InputObject`?

**Comment by sunli829** [comment]
Because InputObject must contain some fields, it doesn't seem to make sense to let it support `tuple`?

**Comment by bokuweb** [comment]
I see. I understand. I may have been mistaken.

**Comment by sunli829** [comment]
> I see. I understand. I may have been mistaken. I think I should use `async_graphql::scalar!` in this case.

Why don't you use the `usize` directly?

**Comment by leebenson** [comment]
@bokuweb - an input object is only for _objects_ -- it's for named fields, akin to `{"someField: "someData"}` in JSON.

If all you want is direct fields, you can define those on the resolver directly - e.g. from https://async-graphql.github.io/async-graphql/en/query_and_mutation.html:

```rust
#[Object]
impl Query {
    async fn user(&self, username: String) -> Result<Option<User>> { // <-- `username` is the direct field here
        // Look up users from the database
    }
}
```

**Comment by bokuweb** [comment]
@sunli829 

`Test(usize)` was an example. I used the new type pattern like `struct UserName(String)` because I wanted to handle the types strictly.

@leebenson Thanks I understand.

**Comment by bokuweb** [comment]
I confirm, the error message is improved by https://github.com/async-graphql/async-graphql/commit/bbf9b9bfb2fd3a05432a0cd232687e4551a3fb38. I close this issue. thanks.
