### ISSUE TITLE
using MergedObject over things with the same name as the new name cause a panic.

### ISSUE THREAD

**Issue by emeryc** [async-graphql/async-graphql#499]
## Expected Behavior
I expect the second print statement to return the same output as the first print statement.

## Actual Behavior
Second call to finish panics with an unwrap

## Steps to Reproduce the Problem
```Rust
use async_graphql::{EmptyMutation, EmptySubscription, MergedObject, Schema};
mod t {
    use async_graphql::Object;
    #[derive(Default)]
    pub struct Query;

    #[Object]
    impl Query {
        async fn test(&self) -> String {
            "Test".into()
        }
    }
}

#[derive(MergedObject, Default)]
struct Query(t::Query);

fn main() {
    let schema_a = Schema::build(
        t::Query::default(),
        EmptyMutation::default(),
        EmptySubscription::default(),
    )
    .finish();
    println!("{}", schema_a.sdl());
    let schema_b = Schema::build(
        Query::default(),
        EmptyMutation::default(),
        EmptySubscription::default(),
    )
    .finish();
    println!("{}", schema_b.sdl());
}

```

## Specifications

- Version: 2.4.8
- Platform: MacOS
- Subsystem: ?

**Comment by sunli829** [comment]
There are two objects named `Query` that are causing this problem.
It is difficult for me to detect this problem at compile time or run time, so I can only avoid it manually.
When there are two types with the same name, some unpredictable errors will occur.

```rust
#[derive(MergedObject, Default)]
struct Query(t::Query);
```

**Comment by emeryc** [comment]
So, the weird thing is that it was working, and then it stopped working. Though maybe that was just a fluke. 

It's mostly weird because the t::Query goes away, because of how MergeObject works, though I guess when you're building tables you only have two concepts called Query...

**Comment by sunli829** [comment]
> So, the weird thing is that it was working, and then it stopped working. Though maybe that was just a fluke.
> 
> It's mostly weird because the t::Query goes away, because of how MergeObject works, though I guess when you're building tables you only have two concepts called Query...

I will think of a way to solve this strange problem.

**Comment by m3rcuriel** [comment]
This was definitely working for the longest time.

**Comment by sunli829** [comment]
Haha, I still haven't found a good way.

**Comment by m3rcuriel** [comment]
@sunli829 now it doesn't panic but instead produces a garbage schema at runtime ^_^

that wasn't an attempt to be mean I just imagine this is some horrible proc macro mess that I don't envy you having to maintain.

**Comment by dustbort** [comment]
Hi, I spent some time today trying to figure out why my schema contained no fields. Then I found this issue and renamed my Query structs and it started working again. Could you put a note in the docs for MergedObject to let people know about this behavior? Thanks for this great crate!

**Comment by sunli829** [comment]
Now if a GraphQL name conflict is detected when creating schema, it will cause panic.
