### ISSUE TITLE
Eager Loading via tokio::sync::oneshot

### ISSUE THREAD

**Issue by Bajix** [async-graphql/async-graphql#502]
One of the challenges with the current design of this library is that it's very difficult to batch load effectively with a data loader. If each field uses a data loader to batch operations, then this will only batch as well as the runtime can do so co-operatively; in practice, if you're returning a suitably large dataset only so many fields will resolve at once and this results in a situation in which extra queries occur because optimal batching is only possible if all fields of a loader were to resolve simultaneously. I've been thinking over design patterns to address this, and the two best answers I've come up with so far are to use some sort of visitor pattern to trigger eager loading and then to have field resolvers that use tokio::sync::oneshot to resolve the eager loaded data, or alternatively there may be a way to make an alternative to the Object macro that is non-async but can return tokio::sync::oneshot receivers. Were I to make a dataloader crate designed to work for this library as an alternative to the one built in, I would do so entirely with channels and would explore a solution around look-ahead based eager loading that is non-async but uses resolvers that await oneshot receivers constructed during eager loading. Such a solution could be quite nice, but nothing would be as elegant as what could be done were resolvers to be able to return oneshot receivers as this would allow all resolvers to be called at once without co-operatively resolution messing up batching. I've only tried Tokio 0.2.25 and not Tokio 1.5 as Actix 4 isn't stabilized, so it could be plausible this is less of an issue on 0.3 and later.

**Comment by sunli829** [comment]
Is it possible to achieve more accurate loading behavior by using the `Context::field` function to obtain the selection set?

https://docs.rs/async-graphql/2.8.4/async_graphql/context/struct.ContextBase.html#method.field

**Comment by Bajix** [comment]
I can already use ctx.field(..).exists() to figure out selections. The
original design pattern I used was to use ctx.field(..).exists() as to
construct "params" structs that describe things like field selections, ids
and nested field selections and using this pattern I was able to make field
resolvers that loaded using optimal queries by batch loading related data
with try_joins and embedding this in wrapper "Node" types that embed the
original type and contain related data. This pattern works to a degree as
you can make relatively efficient queries, but it doesn't scale well with
complexity and as soon as you have any I/O bound resolvers this just means
you're waiting for batch loads before cycling through resolvers. On the
other end of the spectrum, there is the approach of using data loaders such
as the one in this library to batch operations and then using field
resolvers that query things everywhere but this becomes non-performant as
soon as the co-operative nature of resolution of fields starts to impair
batch loading. It just ends up loading a couple things, and then loading a
couple more things, and queries that could otherwise be batched end up not
batching. I wrote a flume-based alternative to your data loader already and
tweaked the shit out of the performance, but it didn't really matter
because the field resolvers wouldn't be called in quick enough succession
to batch optimally. So I think both of these design patterns are complete
duds.

Here's what I envision as an ideal solution to this:
- We use a data loader that's channel based and that returns
oneshot::Receivers instead of awaiting. This can be loosely based off of
https://gist.github.com/Bajix/48cf3905885213af387a649cb8d6ac4b
- Within #[Object], for any resolver that returns
oneshot::Receiver<Result<T, E>>, if that field is selected, then we make
the default behavior that this is called before resolution, and that the
during resolution this awaits the receiver.
- Since all fields that return receivers are visited first, optimal
batching is guaranteed to occur

I think I could probably pull off something like this with clever macros
that generate container structs to house receivers and that generate field
resolvers that read from such, and that this could be handled via type
conversions whilst using field selection, but it's just way better if we
can figure out a solution to have pre-resolution receiver visitors as it
really does a lot to reign in complexity.

**Comment by Bajix** [comment]
Take a look at this: https://github.com/Bajix/channel-loader-rs/tree/main/channel-loader

The next steps are to figure out the best way to kick off loads based off of field selection, and the simplest way to resolve them. What do you think is the best approach here? As I see it now, either there's some solution so that returning oneshot receivers can be eagerly read and be resolved, or the next best solution is to make magical macro things happen. The question now is if this is something that can be done as a change to how `#[Object]` works, or if this needs a generated wrapper type.

**Comment by Bajix** [comment]
I added in a deferment mechanism in my last push. With how my approach works, I'm using a separate static for each DataLoader<K, T: Loader<K>> that I then use when implementing the StaticLoaderExt trait and so this lets me be able to access the singleton static using the StaticLoaderExt<K, T: Loader<K>> trait from the types alone, and this also allows me to be able to submit this instance with inventory, which was how I was able to make a DeferralToken capable of visiting every DataLoader, and so now this single token can be passed around and used for every data loader as a to create a "deferral trap" whereby we pass deferral tokens via ctx and all loaders user the same token and the first use for a type starts a deferral and the drop or batch trigger ends a deferral.  Using this kind of approach, it can be deterministically known when the loader can expect more messages, and by virtue of this batch loading can be done without timeouts in a way that is optimal; there's no more dilemma of how finding the max deadline before loading a batch of requests because you can know if more requests are part of a batch. So long as more deferrals traps have been entered then have been exited, you can continue to batch in optimal batches and then when the last deferral trap is exited send right away. As written this has support for deadline based loading, but anything that is in a deadline that ends up coincidentally in a deferral trap will get optimally batched, and so under load this will basically be consistent wait free batch loading. I'm even thinking this could be taken a step farther by using a crossbeam deque that's associated with the loader so that I can add in work stealing that uses trait bounds to find the global task injector; this way I could make a Diesel-specific loader that awaits a thread, blocks for a connection, and then steals any available loading tasks to add to the current batch. So my sentiment here is that the next step should be to figure out how this can be integrated with async-graphql in a way that can facilitate optimal batching. It really seems like the only way this could integrate ergonomically is if there could be an alternative to the Object macro that visits oneshot receivers, but it's still unclear to me how a workable solution to deferral tokens could fit in without changing how async graphql works. I'm still thinking all this over, but I think I'm on to something that could make this library a lot better. What this does really is separate query batching from query resolution, and by doing so this can come about a solution to deterministically batch in an optimal and timeout free manor as my load_by doesn't need to be async, only the receiver resolution does. So I'm thinking that I'm really onto something here, and I'm going to build out some more capabilities for this, and but if you have any insights on integration or feedback on design that would be great

**Comment by Bajix** [comment]
Ok I've got the channel-based loader at a point ready for integration. The main thing I'm struggling with now is that there's no equivalent of embed for Object/SimpleComplex and so this limits my options on making a composition based solution , ie: `DataNode<T> { #[embed] data: T, ... }`. If embed were added for object types, then I could build a solution that wraps a type, embeds receivers optimally using field selects, and that wires up resolvers from the receivers. This way I could have something like User and DataNode<User> and then convert User to DataNode<User>, and then DataNode<User> could use field selects to embed receivers for related data during creation. Say DataNode<User> has a receiver for tags that's oneshot::Receiver<Vec<Tagging>>, now the resolver for tags would be Vec<Tagging> read from the tags receiver, and a list of DataNode<User> would auto-batch taggings by user_id.  It's an easy to use design pattern, and batches optimally.  So i think the only thing I really need to manage the rest of an integration on my own is just that one annotation. Without that, this becomes considerably more complex.

**Comment by Bajix** [comment]
After further consideration I've realized there are better design patterns to be had. This is still interesting as it doesn't require async_trait, but strictly speaking it's a optimization that can be foregone without affecting batching behavior
