### ISSUE TITLE
Interface usage causes 'mismatched-arg-count' Rust analyser error (ctx passed unnecessarily to methods)

### ISSUE THREAD

**Issue by oeed** [async-graphql/async-graphql#503]
## Expected Behavior
While writing this I've realise this isn't a compiler error as I'd initially thought this, it's just a Rust analyser error - so I guess it's actually not overly severe and probably not really a bug.
Nonetheless, I thought I'd done something wrong at first so it might be nice to suppress the warning in the macro output if possible?

## Actual Behavior
Using the example from the docs, I get an error `Expected 0 arguments, found 1` on the `Shape` enum.

<img width="630" alt="Screen Shot 2021-05-11 at 10 37 17" src="https://user-images.githubusercontent.com/3835991/117733781-3e714e80-b246-11eb-9f2b-4cb86692aadc.png">

The expanded macro passes `ctx` to all methods which is where the issue stems from. I'm not sure if it's possible to know if the method uses `ctx` or not. (as an aside, why does Rust actually allow that to compile?) 
```rust
pub async fn area<'ctx>(
    &self,
    ctx: &'ctx async_graphql::Context<'ctx>,
) -> async_graphql::Result<f32> {
    match self {
        Shape::Circle(obj) => obj
            .area(ctx)
            .await
            .map_err(|err| ::std::convert::Into::<async_graphql::Error>::into(err))
            .map(::std::convert::Into::into),
        Shape::Square(obj) => obj
            .area(ctx)
            .await
            .map_err(|err| ::std::convert::Into::<async_graphql::Error>::into(err))
            .map(::std::convert::Into::into),
    }
}
```

## Steps to Reproduce the Problem

1. Copy paste the [example code](https://async-graphql.github.io/async-graphql/en/define_interface.html) in an editor with Rust analyser.

## Specifications

- Version: 2.8.4
- Platform: macOS 11.1

**Comment by sunli829** [comment]
> I'm not sure if it's possible to know if the method uses ctx or not. (as an aside, why does Rust actually allow that to compile?)

In fact, all resolver functions are automatically added `ctx`.

**Comment by sunli829** [comment]
This seems to be a problem with Rust Analyser, but I haven't found a way to turn off this error message.
