### ISSUE TITLE
Creating unique ID for users

### ISSUE THREAD

**Issue by ArdyZ** [async-graphql/async-graphql#507]
For a project I am creating a web socket connection where I need an unique id for every websocket connection. I started with using `WSSubscription::start()`, but then I saw that I can use `WSSubscription::start_with_initializer` which requires an intializer of data type. I tried it with `WSSubscription::start_with_initializer(Schema::clone(&*schema), &req, payload, |_| {async { Ok(4 as UserID) }})`. This gave the following error:

`WSSubscription::start_with_initializer(Schema::clone(&*schema), &req, payload, |_| {async { Ok(4 as UserID) }})
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `async_graphql::Data`, found `u64``

How do I get that to a data type?

**Comment by sunli829** [comment]
This example can help you.

https://github.com/async-graphql/examples/blob/b5c8853e2dd10d88010c9756f375eea397d60dd2/actix-web/token-from-header/src/main.rs#L57

**Comment by ArdyZ** [comment]
Yes this solved my problem, I edited it in such a way that I create a unique UUID with every new connection based on the example. Thank you very much!
