### ISSUE TITLE
BatchRequest set per request data

### ISSUE THREAD

**Issue by oscartbeaumont** [async-graphql/async-graphql#509]
## Description of the feature

When using `async_graphql::Request` the `data()` method can be used to expose data to the GraphQL resolvers.

However, when using `async_graphql::BatchRequest` there does not seem to exist a similar method so that context data can still be exposed to the resolvers.

I understand that the `data()` method can be used on the GraphQL schema but this is not useful if you have context data that is coming from the HTTPRequest.

**Comment by sunli829** [comment]
`BatchRequest` consists of multiple `Request`, so you only need to attach the same `data` to each `Request`.

**Comment by cortopy** [comment]
I don't think `Schema::execute_batch` is compatible with using data, and it gets more complex if the headers are mutated by the request handler. If it helps anyone this is my take on adding headers to batch requests:

```rust
fn set_cookies(response: GraphQLResponse, jar: MutexGuard<CookieJar>) -> GraphQLResponse {
    let mut headers = HeaderMap::default();

    for cookie in jar.delta() {
        let val = cookie.to_string();
        headers.append(header::SET_COOKIE, val);
    }

    response.http_headers(headers)
}
```

```rust
let cookie_jar = Arc::new(Mutex::new(CookieJar::default()));

let response = match request {
    async_graphql::BatchRequest::Single(request) => {
        let mut response =
            schema.execute(request.data(cookie_jar.clone())).await;

        let cookie_jar = cookie_jar.clone();
        let cookie_jar = cookie_jar.lock().await;

        response = set_cookies(response, cookie_jar);

        async_graphql::BatchResponse::Single(response)
    }
    async_graphql::BatchRequest::Batch(requests) => {
        let reqs = requests.into_iter().map(|req| async {
            let response = schema.execute(req.data(cookie_jar.clone())).await;

            let cookie_jar = cookie_jar.clone();
            let cookie_jar = cookie_jar.lock().await;

            set_cookies(response, cookie_jar)
        });

        async_graphql::BatchResponse::Batch(join_all(reqs).await)
    }
};

Ok::<_, Infallible>(BatchResponse::from(response))
```

It's a bit verbose but it works with some caveats:
- only works with tokyo (so it wouldn't work with tide)
- uses tokyo::std::Mutex so that the request handler can add headers to the cookie jar
- batch requests are processed in parallel rather in sequence. This is different to `Schema::execute_batch`

**Comment by sunli829** [comment]
I will close this issue, if you have other questions, please feel free to open it.
