### ISSUE TITLE
Support the @defer directive in query

### ISSUE THREAD

**Issue by sunli829** [async-graphql/async-graphql#51]
Since the stable version of rust does not support generic specialization, this is a bit of a hassle to implement. I'm doing it in other ways, and I'm not sure if I can finish it.

**Comment by sunli829** [comment]
Wait until the generic specialization is available......

**Comment by sunli829** [comment]
Maybe I found a way to support this feature.

**Comment by sunli829** [comment]
Is there any other way to simulate specialization in the stable version of rust?

```rust
trait A {
    fn test();
}

impl<T: 'static> A for T {
    fn test() {}
}

impl<T> A for T {
    fn test() {}
}
```

@nicolaiunrein @IcanDivideBy0 @phated

**Comment by IcanDivideBy0** [comment]
I guess I can't help you on this one :/
Which trait are we  talking about ? maybe we can split implementation in different parts?

**Comment by sunli829** [comment]
I thought about it again, even if there are specializations, there are other problems. It is difficult to implement @defer without affecting the ease of use. This is not a problem in languages with GC. 🥺

**Comment by sunli829** [comment]
I thought of a compromise method and tried again. 😂
