### ISSUE TITLE
Change log level 

### ISSUE THREAD

**Issue by cortopy** [async-graphql/async-graphql#518]
## Description of the feature

In the default logger, any graphql that responds with errors is logged at error level: https://github.com/async-graphql/async-graphql/blob/master/src/extensions/logger.rs#L68

This is creating a lot of noise in my servers because I use [sentry-log](https://docs.rs/sentry-log/0.22.0/sentry_log/), which sends an error event to a sentry server each time something is logged at `error!` level. This wouldn't affect only this particular case, as any monitoring tool that parses and notifies on errors logged in stdout will suffer from the same amount of false positives.

As far as I understand logging levels, not every response with errors is an error in itself. Anything that in a HTTP server has status lower than 500 is not an error to be concerned about. For example:

- user submits form with invalid values
- someone tries to log in with wrong credentials
- etc.

Is changing the log level to `info!` something that could be considered? I could implement my own Logger extension but I guess other users may benefit from this change too

**Comment by sunli829** [comment]
You are right, I changed the error log level. 😁

**Comment by sunli829** [comment]
Released in `v2.10.1`
