### ISSUE TITLE
No Field rename

### ISSUE THREAD

**Issue by servonlewis** [async-graphql/async-graphql#519]
Can someone please show me how to retain my camel case fields when doing a query?  

I have an api that looks for the field name and when it transforms to camelcase, it breaks that functionality

**Comment by oscartbeaumont** [comment]
You can put `#[graphql(rename_fields = "camelCase")]` on your object [like shown here](https://gist.github.com/oscartbeaumont/a5bf6374ce4d81a572a521def66d59c4) to set the casing of the fields. The possible options for casing are [defined here](https://github.com/async-graphql/async-graphql/blob/cdd13ea1be1a0af421d915f3f2b7e11f647452be/src/lib.rs#L247).

**Comment by servonlewis** [comment]
> You can put `#[graphql(rename_fields = "camelCase")]` on your object [like shown here](https://gist.github.com/oscartbeaumont/a5bf6374ce4d81a572a521def66d59c4) to set the casing of the fields. The possible options for casing are [defined here](https://github.com/async-graphql/async-graphql/blob/cdd13ea1be1a0af421d915f3f2b7e11f647452be/src/lib.rs#L247).
> 
> 
> 
> 

You are my hero. Saved me many many many headaches ty!

**Comment by constantincerdan** [comment]
Sorry to post on an old issue, but is there a way to set this globally so you don't have to annotate every object in your schema?

**Comment by sunli829** [comment]
No, this attribute must be specified for each object.

**Comment by constantincerdan** [comment]
Would adding that ability be difficult to do? I'm willing to give it a shot if pointed in the right direction.

**Comment by sunli829** [comment]
Yes, each procedural macro call is independent and there is no way to customize their behavior using global variables.
As far as I know there are two ways to specify the behavior of procedural macros:

- access environment variables
- add some feature gates

But this adds complexity, which I don't really like. 🙂
