### ISSUE TITLE
Extending a non-root mutation

### ISSUE THREAD

**Issue by fominok** [async-graphql/async-graphql#521]
Hi,
using federation I've run into a dead end: I don't understand how I can extend a mutation, which is non-root.

Things I tried:
1. Define a root mutation as a `MergedObject`, this didn't work as merged mutations are "flattened" and their methods are under new root now, so no extending of an external object
2. Adding a method to my root mutation, which returns another mutation I treat as external. This creates an unwanted method, didn't investigate further
3. Using combinations of `entity` and `external`, this seemed to work and the schema became right, but on execution it worked only with methods from original mutation, for extension methods there was an error that I need to add nested query field which is not true

How can I extend a mutation, which origins in another service and nested somewhere?

(tried with Graphgate)

**Comment by sunli829** [comment]
Can you provide a simple example so that I can solve this problem more quickly.

**Comment by fominok** [comment]
Let's say we have two services: one manages users and another is about their working hours.
Example mutation available in users service:
```
mutation {
  users {
    edit(input: ...) {
      ...
    }
  }
}
```

Now I want to extend it from working hours service to do something like that:
```
mutation {
  users {
    addWorkingHours(input: ...) {
      ...
    }
  }
}
```
and both of them are behind Graphgate.
I have to clue how to extend this nested mutation as it has no id or something like it is done in federation examples

**Comment by sunli829** [comment]
All mutation operations should be located in the root, and nesting is a wrong usage.

I suggest you change the schema to something like the following.

```
mutation {
  usersEdit(input: ...) {
      ...
  }

  usersAddWorkingHours(input: ...) {
    ...
  }
}
```

**Comment by fominok** [comment]
Thank you @sunli829, I'll rethink the schema then
