### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by phungtranminh** [async-graphql/async-graphql#522]
Hi,

This might not be a async-graphql question. Nevertheless, my app under heavy load start to use lots of memory.

I wonder what is the best way to start looking into how the libraries in rust are using memory, and `async-graphql` in particular.

Thanks a lot.

**Comment by sunli829** [comment]
Maybe you should use `valgrind` to see how your memory is consumed.

**Comment by phungtranminh** [comment]
Thanks for advising, I will look into this
