### ISSUE TITLE
future created by async block is not `Send`<Title>

### ISSUE THREAD

**Issue by sail-sail** [async-graphql/async-graphql#527]
20 | #[async_graphql::Object]
   | ^^^^^^^^^^^^^^^^^^^^^^^^ future created by async block is not `Send`
   |
   = help: within `ReqContext`, the trait `Sync` is not implemented for `Rc<RefCell<PoolConnection<MySql>>>`
note: future is not `Send` as this value is used across an await

**Comment by sunli829** [comment]
RefCell is `!Sync`，you should use async `Mutex`(eg: `tokio::sync::Mutex`)

**Comment by sail-sail** [comment]
Thanks, Is OK!
