### ISSUE TITLE
Better guard ergonomics

### ISSUE THREAD

**Issue by meh** [async-graphql/async-graphql#536]
I've started using guards in my codebase and it would be nice if they could be a little more flexible.

Things I found a bit annoying so far:

1. Taking a `path` instead of an ident so I can fully/partially scope guards instead of having to import them.
2. Having to provide empty parentheses when the guard does not take any parameter.

What I'm going for is something like this:
```rust
#[graphql(guard(guard::Session))]
```

Instead of:
```rust
#[graphql(guard(SessionGuard()))]
```

Thanks!

**Comment by meh** [comment]
Oh also having to import `async_graphql::guard::Guard` for the proc macro to work is kind of annoying.

**Comment by sunli829** [comment]
> I've started using guards in my codebase and it would be nice if they could be a little more flexible.
> 
> Things I found a bit annoying so far:
> 
> 1. Taking a `path` instead of an ident so I can fully/partially scope guards instead of having to import them.
> 2. Having to provide empty parentheses when the guard does not take any parameter.
> 
> What I'm going for is something like this:
> 
> ```rust
> #[graphql(guard(guard::Session))]
> ```
> 
> Instead of:
> 
> ```rust
> #[graphql(guard(SessionGuard()))]
> ```
> 
> Thanks!

Because of the limitation of procedural macros, I haven't thought of a better way to remove this annoying empty parentheses. 🙂

**Comment by meh** [comment]
Ah, damn, that's understandable then, what about supporting paths instead of just an ident tho? :panda_face:

**Comment by sunli829** [comment]
It should work, I am trying.

**Comment by sunli829** [comment]
I have implemented it on the master branch. 🙂

**Comment by meh** [comment]
You're the best! Thanks!
