### ISSUE TITLE
Example from book does not compile because `sqlx::Error` is not `Clone`

### ISSUE THREAD

**Issue by cschmatzler** [async-graphql/async-graphql#537]
## Expected Behavior
In the book, under the dataloader section [here](https://async-graphql.github.io/async-graphql/en/dataloader.html), the following example is given:

```
#[async_trait::async_trait]
impl Loader<u64> for UserNameLoader {
    type Value = String;
    type Error = sqlx::Error;

    async fn load(&self, keys: &[u64]) -> Result<HashMap<u64, Self::Value>, Self::Error> {
        let pool = ctx.data_unchecked::<Pool<Postgres>>();
        let query = format!("SELECT name FROM user WHERE id IN ({})", keys.iter().join(","));
        Ok(sqlx::query_as(query)
            .fetch(&self.pool)
            .map_ok(|name: String| name)
            .try_collect().await?)
    }
}
```

This does not compile, because the `Error` type `sqlx::Error` does not implement `Clone`, which is required by `async_graphql::dataloader::Loader::Error` over [here](https://github.com/async-graphql/async-graphql/blob/4c98ad2c9219d01bd70d11319de91033da197cb4/src/dataloader/mod.rs#L144)

## Actual Behavior

Expected an example that does work with SQLx.

## Steps to Reproduce the Problem

1. Copy the example from the book and observe that it does not compile.

## Specifications

- Version: `2.9.1` on rustc `stable` with sqlx crate `0.5.2`
- Platform: Fedora 34
- Subsystem: n/a

**Comment by meh** [comment]
Easy solution is to return an `Arc<sqlx::Error>` instead.
