### ISSUE TITLE
Get query / subscription name in TracingExtension.

### ISSUE THREAD

**Issue by BratSinot** [async-graphql/async-graphql#538]
Greetings!

I need to find out execution time to query / mutation / subscription, but I don't want to copy-paste code to every query by hands. Can I extract some name from `TracingExtension`?

```rust
#[async_trait::async_trait]
impl Extension for TracingExtension {
    async fn execute(&self, ctx: &ExtensionContext<'_>, next: NextExecute<'_>) -> Response {
        let now = Instant::now();

        let resp = next.run(ctx).await;
        
        println!("{} elapsed: {}", <NAME>, now.elapsed());

        resp
    }
}
```

**Comment by sunli829** [comment]
Do you want to get the operation name?

```graphql
query OperationName {
   ...
}
```

**Comment by BratSinot** [comment]
No, I mean this:
```graphql
subscription {
   Name {
      ...
   }
}
```

**Comment by BratSinot** [comment]
Wow, thank you! I didn't expect so quick response =)

**Comment by BratSinot** [comment]
Thanks for quick response!
But any way to use name from request name?

**Comment by sunli829** [comment]
It looks like you want to get the execution time of each field, you can do it like this:

https://github.com/async-graphql/async-graphql/blob/4869b1aae2ef3eeb0e757b4e02ee3aaeb7f0c999/src/extensions/apollo_tracing.rs#L101

**Comment by BratSinot** [comment]
> get the execution time of each field, you can do it like th

Yeah, but I haven't come up with a way to link `resolve` and `execution` yet. Do they have some common id or something?

**Comment by BratSinot** [comment]
Hm, yeah, `self` is unique. I can do like this:
```rust
    async fn resolve(
        &self,
        ctx: &ExtensionContext<'_>,
        info: ResolveInfo<'_>,
        next: NextResolve<'_>,
    ) -> ServerResult<Option<Value>> {
        if ["Subscription", "QueryRoot", "MutationRoot"].contains(&info.parent_type) {
            *self.name.lock().await = info.path_node.to_string();
        }

<...>
    async fn execute(
        &self,
        ctx: &ExtensionContext<'_>,
        operation_name: Option<&str>,
        next: NextExecute<'_>,
    ) -> Response {
        let resp = next.run(ctx, operation_name).await;
        println!("{:?}", *self.name.lock().await);
        resp
    }
```

I tried with query, mutation and subscribe and seems that I got what I needed.
But I don't like `if` to every resolve and `Mutex`. But maybe it doesn't affect that much.

**Comment by BratSinot** [comment]
Hm... And how `execute` works for `subscription`?
```rust
#[Subscription]
impl Subscription {
    async fn foo(
        &self,
    ) -> impl Stream<Item = Option<String> {
        async_stream::stream! {
            loop {
                yield Some("qwe".to_owned());

                tokio::time::sleep(Duration::from_secs(2))
                .await;
            }
        }
    }
}
<...>
    async fn execute(
        &self,
        ctx: &ExtensionContext<'_>,
        operation_name: Option<&str>,
        next: NextExecute<'_>,
    ) -> Response {
        let now = Instant::now();

        let resp = next.run(ctx, operation_name).await;

        let elapsed = now.elapsed();

        println!("{}: {}", *self.name.lock().await, elapsed.as_secs());

        resp
    }
```

Return `0`.

**Comment by sunli829** [comment]
> Hm... And how `execute` works for `subscription`?
> 
> ```rust
> #[Subscription]
> impl Subscription {
>     async fn foo(
>         &self,
>     ) -> impl Stream<Item = Option<String> {
>         async_stream::stream! {
>             loop {
>                 yield Some("qwe".to_owned());
> 
>                 tokio::time::sleep(Duration::from_secs(2))
>                 .await;
>             }
>         }
>     }
> }
> <...>
>     async fn execute(
>         &self,
>         ctx: &ExtensionContext<'_>,
>         operation_name: Option<&str>,
>         next: NextExecute<'_>,
>     ) -> Response {
>         let now = Instant::now();
> 
>         let resp = next.run(ctx, operation_name).await;
> 
>         let elapsed = now.elapsed();
> 
>         println!("{}: {}", *self.name.lock().await, elapsed.as_secs());
> 
>         resp
>     }
> ```
> 
> Return `0`.

This seems to be a problem, I am confirming it.

**Comment by sunli829** [comment]
This is correct, `execute` resolves this object after an event occurs.

**Comment by BratSinot** [comment]
Oh, yeah, my mistake. I stored name into `Mutex` and got data from mutex before `let resp = next.run(ctx, operation_name).await;`.

Last question, how is stream in `pub fn subscribe<'s>(&self, stream: BoxStream<'s, Response>) -> BoxStream<'s, Response>` is polling? Can I get time passed between poll?

**Comment by sunli829** [comment]
> Last question, how is stream in `pub fn subscribe<'s>(&self, stream: BoxStream<'s, Response>) -> BoxStream<'s, Response>` is polling? Can I get passed time between poll?

This is correct, but since your stream returns a String type, it is resolved very quickly.

```rust
   async fn execute(
        &self,
        ctx: &ExtensionContext<'_>,
        operation_name: Option<&str>,
        next: NextExecute<'_>,
    ) -> Response {
        let now = Instant::now();

        let resp = next.run(ctx, operation_name).await;

        let elapsed = now.elapsed();

        println!("{}: {}", *self.name.lock().await, elapsed.as_secs());

        resp
    }
```

**Comment by sunli829** [comment]
> > Last question, how is stream in `pub fn subscribe<'s>(&self, stream: BoxStream<'s, Response>) -> BoxStream<'s, Response>` is polling? Can I get passed time between poll?
> 
> This is correct, but since your stream returns a String type, it is resolved very quickly.
> 
> ```rust
>    async fn execute(
>         &self,
>         ctx: &ExtensionContext<'_>,
>         operation_name: Option<&str>,
>         next: NextExecute<'_>,
>     ) -> Response {
>         let now = Instant::now();
> 
>         let resp = next.run(ctx, operation_name).await;
> 
>         let elapsed = now.elapsed();
> 
>         println!("{}: {}", *self.name.lock().await, elapsed.as_secs());
> 
>         resp
>     }
> ```
