### ISSUE TITLE
Discussion: Should ID support From<Uuid>?

### ISSUE THREAD

**Issue by phated** [async-graphql/async-graphql#54]
In my application, IDs are a custom scalar that wraps the Uuid type. Would it be valuable for the ID scalar provided here to have a `From<Uuid>` implementation?

**Comment by sunli829** [comment]
Since you have this requirement, I think this feature makes sense. I'll add it now.😁

**Comment by nicolaiunrein** [comment]
I use Uuids as well and I think it is quite common. Maybe implement it for `T: Into<Uuid>` so that it works well with the new type pattern?

**Comment by nicolaiunrein** [comment]
In fact this concerns all ID conversions. If that is something desirable I will give it a shot. Should not be breaking existing implementations because all types implement `From` and `Into` themselves.

**Comment by phated** [comment]
@nicolaiunrein I think that would be a good idea. When converting between ID and Cursor, I need to do `id.to_string().into()` which isn't ideal.

**Comment by sunli829** [comment]
@nicolaiunrein How is this feature going to be implemented?😁

**Comment by nicolaiunrein** [comment]
Sorry, I am pretty busy at the moment with other projects. I will look at it tomorrow or on monday.

**Comment by nicolaiunrein** [comment]
Well, we can't implement generic `From` implementation due to conflicting implementations but I would suggest to add two traits:

```rust
pub trait ToGraphqlCursor {
    fn to_graphql_cursor(&self) -> Cursor;
}

impl<T> ToGraphqlCursor for T
where
    T: std::fmt::Display,
{
    fn to_graphql_cursor(&self) -> Cursor {
        Cursor(self.to_string())
    }
}
```

and 

```rust
pub trait ToGraphqlID {
    fn to_graphql_id(self) -> ID;
}

impl<T> ToGraphqlID for T
where
    T: std::fmt::Display,
{
    fn to_graphql_id(self) -> ID {
        ID(self.to_string())
    }
}
```

which when imported give you two methods `to_graphql_cursor` and `to_graphql_id` on anything that implements `std::fmt::Display` and allows you to instead of calling `id.to_string().into()` just `id.to_graphql_cursor`. Now this can be quite handy when you implement your own ID type as well:
```rust
pub struct MyID(Uuid);
impl std::fmt::Display for MyID { ... }

// somewhere else
let id = my_id.to_graphql_id();
```

What do you think?

**Comment by sunli829** [comment]
I think it's good, it's really easier to use. 😁

In addition, can you add this error_extensions.md when you are free? I think you know more about this than me.

I have been working on a new parser for the past few days and it is now complete. You can upgrade to 1.11.0 to see if there is a problem with your current project.

Thanks again, `ToGraphqlID` and `ToGraphqlCursor` I will add later. 😁

**Comment by nicolaiunrein** [comment]
Cool. I will see what I can with error_extensions.md on monday.

**Comment by sunli829** [comment]
Thank you. 😁

**Comment by sunli829** [comment]
@nicolaiunrein  It has been implemented in version 1.11.1.

**Comment by IcanDivideBy0** [comment]
Correct me if I'm wrong but this feels unnecessary complicated.
By removing the `impl std::fmt::Display for Cursor`, we can then add
```rust
impl<T> From<T> for Cursor
where
    T: std::fmt::Display
{
    fn from(value: T) -> Self {
        Cursor(value.to_string())
    }
}
```
which removes the need for the `ToGraphQLCursor` trait ?

Same goes for ID, I don't think those types needs to implement display, Debug should be enough for general purpose

**Comment by IcanDivideBy0** [comment]
https://github.com/IcanDivideBy0/async-graphql/commit/0c582fa47023d55a613f5cc45e8ab7fe16c5d954

**Comment by IcanDivideBy0** [comment]
In the end it's even simpler
```
    let cursor: Cursor = "foo".into();

    let id = uuid::Uuid::parse_str("936DA01F9ABD4d9d80C702AF85C822A8").unwrap();
    let cursor: Cursor = id.into();
```

**Comment by sunli829** [comment]
@IcanDivideBy0  This suggestion is good, I change it. 😁

**Comment by sunli829** [comment]
@IcanDivideBy0 Seems to require generic specialization?



36 | impl<T: Display> From<T> for ID {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: conflicting implementation in crate `core`:
           - impl<T> std::convert::From<T> for T;

**Comment by sunli829** [comment]
@nicolaiunrein Is this the reason?

**Comment by sunli829** [comment]
Sorry, you actually answered the question. 😊@nicolaiunrein

**Comment by IcanDivideBy0** [comment]
@sunli829 let me send the PR

**Comment by sunli829** [comment]
Weird things, you can compile and pass. I want to see how your modification differs from mine.😳

**Comment by IcanDivideBy0** [comment]
@sunli829 you probably forgot to remove the `impl fmt::Display for ID` ?

**Comment by sunli829** [comment]
Thanks, I understand, because ID also implements Display, so it will conflict. I think the implementation of Display can indeed be removed, which is even simpler. Thank you for your PR. 😁

**Comment by IcanDivideBy0** [comment]
@nicolaiunrein `ID` and `Cursor` now properly implements `From<fmt::Display>` on master.
@sunli829 I let you decide if this worth a release :)

**Comment by sunli829** [comment]
Let me do it, just change the version number. 😂

**Comment by nicolaiunrein** [comment]
Brilliant! @IcanDivideBy0 I much prefer your solution! Didn't consider removing `Display` for those types an option.

**Comment by nicolaiunrein** [comment]
> In addition, can you add this error_extensions.md when you are free? I think you know more about this than me.
@sunli829 I wrote something but it got quite lengthy. Please review.

**Comment by sunli829** [comment]
Thank you so much. I translated the Chinese version later. 🍺

**Comment by sunli829** [comment]
@nicolaiunrein The documentation is too good, much better than mine. 😂
