### ISSUE TITLE
Access the DataLoader from Loader

### ISSUE THREAD

**Issue by meh** [async-graphql/async-graphql#543]
## Description of the feature

It would be nice if it were possible to access the `DataLoader` calling the `Loader` implementation to do nested/associated loads,
right now for example to implement [global object identification](https://graphql.org/learn/global-object-identification/) I have a Loader for this id type, that then has to create its own internal dataloader to call the loader on every type in the `Node`, which is kind of annoying.

I understand this might be hard due to locking and such, so I understand if it's not possible.

**Comment by Bajix** [comment]
You should actually just use a separate DataLoader for every key/value pair that you want to batch load against and have field resolvers for associated loads as necessary. This means you're going to end up with a loader types, but you could use `inventory::submit` to submit functions into a wrapper struct that has Box<dyn Fn(ctx: &<'_> Context)>; these could then be called for each request to construct and add the respective data loader when constructing the request in your integration layer. Later you could then use ctx.data_unchecked to get an instance by type, and it would be the instance you associated with this request. With the design of this, a static DataLoader would not be performant whatsoever, so it's really necessary to construct per instance.

**Comment by meh** [comment]
I have many different loader implementations already, this is for implementing the global object identification spec.

**Comment by meh** [comment]
Any update on this? I'm now once again really needing it, and having to copy paste a bunch of queries.
