### ISSUE TITLE
Any reason why receive_batch_multipart requires 'static for body?

### ISSUE THREAD

**Issue by XiNiHa** [async-graphql/async-graphql#544]
While updating the Rocket integration for `0.5.0-rc.1`, I found that it is not possible to use `async_graphql::http::receive_batch_body` since it requires `'static` lifetime for the data parameter and the recent Rocket version changed to require the lifetime of the body data to be the same with the lifetime of the request.

However, removing `'static` requirement from both `receive_batch_body` and `receive_batch_multipart` simply fixed all the issues without any errors. Is there any specific reason that `data` parameter of `receive_batch_multipart` should be marked as `'static`? Otherwise, I'll just make a pull request with the `'static` requirement removed.

**Comment by sunli829** [comment]
It seems that this `'static` is unnecessary. 😁

**Comment by sunli829** [comment]
I tried to remove the `'static` constraint on the body, and no problem was found.

**Comment by XiNiHa** [comment]
Great, just created the pull request as mentioned above(#545)
