### ISSUE TITLE
Make the object_type_name available in async_graphql::context::SelectionField

### ISSUE THREAD

**Issue by lastmjs** [async-graphql/async-graphql#546]
Currently `async_graphql::context::SelectionField` will give you access to the field name, alias, arguments, and child fields through the `selection_set`. This all works very well, and I am able to return arbitrarily complex selection sets for my project [Sudograph](https://github.com/sudograph/sudograph). Sudograph is a GraphQL database for the Internet Computer, it is designed in a particular way probably not common to how GraphQL is normally used with traditional databases like Postgres/MySQL/MongoDB. I just bring this up in case you're questioning why I need this functionality.

I am missing a key part of the selection set, which is the object type from the schema that the current selection set or field belongs to. I need this information to implement searching/filtering on relations within a selection set, and without it being available to me in `async_graphql::context::SelectionField` I believe I am going to have to get the SDL from the schema, parse it into an AST, and manually walk it to find the object types that I need. I think this will work fine, but it will be a lot of extra work and processing when a simple `object_type_name` method available on `async_graphql::context::SelectionField` would save me all of that trouble.

**Comment by sunli829** [comment]
The signature of this function is `SelectionField::object_type_name(&self) -> Option<&str>`. If the type of this field is not an `Object`, it will return None. What do you think?

**Comment by lastmjs** [comment]
I want to know the `object_type_name` of the object type that the field belongs to, so it should always have an `object_type_name`

**Comment by lastmjs** [comment]
Having a separate `type_name` which would be the type of that field would be interesting too, but not exactly necessary for my use case

**Comment by lastmjs** [comment]
You know what, I'm sorry, I do think that `object_type_name` and `type_name` would be nice to have, but I believe I was actually confused on how to achieve my use case. I actually need this type of information in the `pub fn arguments(&self) -> ServerResult<Vec<(Name, Value)>>` so that I can properly filter/search when resolving everything from Sudodb...having the `object_type_name` and `type_name` on a `selection_field` will not necessarily help me there, I will need to do an AST traversal no matter what it seems.

Though I think a case can be made for having the extra `object_type_name` and `type_name` anyway.

**Comment by sunli829** [comment]
After I added the `object_type_name` and `type_name` functions, can it solve the problem?

**Comment by lastmjs** [comment]
Adding those functions will not solve my problem, I have already solved my problem with an AST traversal based on inputs from the arguments...I was trying to explain that here: https://github.com/async-graphql/async-graphql/issues/546#issuecomment-862449423

So, I think it would be nice to have those two functions, but they don't solve my use case, sorry for the confusion :)

**Comment by sunli829** [comment]
Okay, these two functions will reduce query performance, so I won't add them. I will close this issue now. If you have any questions, please feel free to open it. 😁
