### ISSUE TITLE
SDL print is not stable

### ISSUE THREAD

**Issue by Sytten** [async-graphql/async-graphql#547]
## Expected Behavior
When printing the SDL it should sort the AST so the output is stable and can be used in diff of PRs.

## Actual Behavior
Currently it is all over the place, every time you run it changes unrelated stuff

## Steps to Reproduce the Problem

1. Output a large schema
2. Commit
3. Reoutput the same schema, you get a diff

**Comment by sunli829** [comment]
I can't reproduce this problem, if you can give me the SDL files, I can find the problem more easily. 😁

**Comment by Sytten** [comment]
Ho thats weird I will try to have a minimal repo for you. Could it be an OS difference? Or the usage of merged query/mutation root?

**Comment by Corb3nik** [comment]
I managed to reproduce this issue :)

1. git clone https://github.com/Corb3nik/async-graphql-sdl-sorting-issue
2. `cargo run` a few times

Notice the GraphQL `input` type ending up in different places from run to run.

Run 1:
```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/async-graphql-schema-issue`
type Query {
        a: Int!
}

type Mutation {
        a(input: SomeInput!): Boolean!
}
input SomeInput {
        inputA: Boolean!
}
schema {
        query: Query
        mutation: Mutation
}

```

Run 2:
```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/async-graphql-schema-issue`
type Query {
        a: Int!
}
input SomeInput {
        inputA: Boolean!
}
type Mutation {
        a(input: SomeInput!): Boolean!
}
schema {
        query: Query
        mutation: Mutation
}

```

Fwiw, I'm running these steps on macOS.

**Comment by Corb3nik** [comment]
I believe this might be related to the `MergedObject` derive. I'm unsure why, but when I take the `MergedObject` derive off of the `Query` type, I can't reproduce this anymore :

```diff
$ git diff
diff --git a/src/main.rs b/src/main.rs
index a1e34b7..a9b63a8 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -5,14 +5,11 @@ pub struct SomeInput {
     input_a: bool
 }

-#[derive(SimpleObject, Default)]
-pub struct A {
-    pub a: u8,
+#[derive(Default, SimpleObject)]
+pub struct Query {
+    pub a: u8
 }

-#[derive(Default, MergedObject)]
-pub struct Query(A);
-

 #[derive(Default)]
 pub struct B;
```

**Comment by sunli829** [comment]
Thank you, I will look at this tomorrow.

**Comment by sunli829** [comment]
Released in `v2.9.8`

**Comment by Sytten** [comment]
Thanks a lot @sunli829!

**Comment by oeed** [comment]
I'm afraid I think this is still an issue. My schema is fairly large at ~1.2k lines and I encountered it after adding a new mutation to a `MergedObject`, resulted in a number of unrelated schema items moving around.

Could the output perhaps be sorted?
