### ISSUE TITLE
Flow application error to client

### ISSUE THREAD

**Issue by phungtranminh** [async-graphql/async-graphql#549]
I would like to flow application errors to client.

For example if user doesn't have permission, I would like to send something like this back to client?

```
{
  "error": { "message": "Unauthorized", "code": "4xx" }
}
```

Currently, when it is errored, it is captured by async graphql and I cannot add something like code into it (or maybe I don't know).

**Comment by sunli829** [comment]
https://async-graphql.github.io/async-graphql/en/error_extensions.html

**Comment by phungtranminh** [comment]
Great thanks! @sunli829
