### ISSUE TITLE
Complex enum

### ISSUE THREAD

**Issue by phungtranminh** [async-graphql/async-graphql#554]
Hi, from the book looks like `async-graphql`  only support simple Enum.

https://async-graphql.github.io/async-graphql/en/define_enum.html

I wonder if there is a way to make `async-graphql` work with complex enum, such as enum of different structs.

```
pub enum Enum {
  Variant1(Struct1),
  Variant2(Struct2),
}
```

Thanks for helping out, cheers

**Comment by phungtranminh** [comment]
Or one way is for `async-graphql` to hand in a `Map` then the application can handle further conversion?

**Comment by sunli829** [comment]
Maybe you should at least understand the GraphQL specification before asking this kind of question.

**Comment by phungtranminh** [comment]
Hey @sunli829 don't worry, understand that I am trying to push the boundaries here but yeah the software is at the boundaries, it is at the point where all standard things are figured out and every small improvements, all edge cases do matter.

And there is practical usage of this too, related to:

https://github.com/async-graphql/async-graphql/issues/373

And from this discussion looks like we can use `Json`

https://github.com/async-graphql/async-graphql/issues/398

Feel like dejavu but at least worth a try, cheers
