### ISSUE TITLE
Possible issue with serializing int to async_graphql::Number

### ISSUE THREAD

**Issue by lastmjs** [async-graphql/async-graphql#565]
I am dealing with JSON strings that have arrays of integers. It seems as if the serialization process for async_graphql::Number is turning my JSON array of integers into an array of floats (they have `.0` at the end of them when printed out). This is causing me some issues, as I have test cases with equality checks that fail without me coercing the floats to ints or vice versa. I would expect ints to always serialize into a `Number` that is an integer under-the-hood.

Is this the expected behavior? Could I be seeing a bug? I can post more information if this seems like a possible bug, or doesn't quite make sense.

**Comment by sunli829** [comment]
Can you provide an example that can reproduce this problem? 😁

**Comment by sunli829** [comment]
I will close this issue, if you have other questions, please feel free to open it.
