### ISSUE TITLE
Setting cookies not working

### ISSUE THREAD

**Issue by oeed** [async-graphql/async-graphql#566]
I'm trying to set cookies on my response and it isn't showing up in the response headers. I've read issues such as #370 and follow their guidance to no avail. Am I doing something wrong or is there a bug?

Really simply mutation:

```rust
#[derive(Default)]
pub struct CookieMutation;

#[Object]
impl CookieMutation {
  async fn cookie(&self, ctx: &Context<'_>) -> bool {
    let example_cookie = actix_http::cookie::Cookie::build("example", "helloworld").finish();
    ctx.insert_http_header(actix_http::http::header::SET_COOKIE, example_cookie.to_string());

    ctx.http_header_contains(actix_web::http::header::SET_COOKIE)
  }
}
```

```gql
mutation {
  cookie
}

# response:
# {
#   "data": {
#     "cookie": true
#   }
# }
```

`ctx` indicates that it does indeed contain the header, but if I look in Postman you can see no cookie header is present.

<img width="784" alt="Screen Shot 2021-07-09 at 16 30 18" src="https://user-images.githubusercontent.com/3835991/125023423-0023ce80-e0d3-11eb-93f6-c627b8e7da8e.png">

**Comment by oeed** [comment]
After looking in to the source code I realised my mistake. I was using the fixed described [here](https://github.com/async-graphql/async-graphql/issues/489#issuecomment-846964579) to use actix v4, but it simply set the body value - not headers.

I tweaked it to this, could certainly be more efficient but given it's only short lived I didn't want to spend too much time on it:

```rust
  let mut response = HttpResponse::Ok();
  for (name, value) in &resp.http_headers {
    response.append_header((name, value.clone()));
  }

  Ok(
    response
      .content_type("application/json;charset=utf-8")
      .body(serde_json::to_string(&resp).unwrap()),
  )
```

**Comment by onx2** [comment]
Has this been resolved? Tide doesn't seem to be working for me. I've tried modifying the cookie name/value and most other options with no positive results. I have also tried setting additional headers for allow origin `*`.

Something that is weird is that it works for me on Ubuntu v20.x, Firefox v89.0.2, but not in Chrome, Edge, or FF 90.x on Windows or Linux. I'm not sure that is helpful or not - I'm pretty confused as to what might be happening.

Does this code look correct?

```rust
app.at("/graphql")
        .post({
            let schema = schema.clone();
            move |req: Request<()>| {
                let schema = schema.clone();
                async move {
                    let token = req
                        .cookie("testName")
                        .map(|value| value.value().to_string());

                    let mut req = async_graphql_tide::receive_request(req).await?;
                    if let Some(token) = token {
                        req = req.data(MyToken(token));
                    }
                    async_graphql_tide::respond(schema.execute(req).await)
                }
            }
        })
```

```rust
struct MutationRoot;

#[Object]
impl MutationRoot {
    async fn set_cookie(&self, ctx: &Context<'_>) -> Option<String> {
        ctx.insert_http_header("Set-Cookie", format!("testName=testValue"))
    }
}
```
It does show up in  the `cookies` tab of the `setCookie` network request
![image](https://user-images.githubusercontent.com/23039725/126182354-b5568834-f9b9-4a99-8bfb-ee5185dc0ae2.png)

The mutation returns `null`
![image](https://user-images.githubusercontent.com/23039725/126182382-bf8cf544-0fab-4717-9060-a2c4e39a3088.png)

The browser storage for cookies shows nothing though
![image](https://user-images.githubusercontent.com/23039725/126183645-1fb0e96a-ce3d-4ce3-a5f0-b713bff08d18.png)

**Comment by sunli829** [comment]
@onx2 The code looks okay, the header is also sent to the client, I think this should be caused by other problems.

**Comment by onx2** [comment]
Do you have any suggestions for where I can start debugging? I built a bare bones express app and I was able to set cookies without a problem.

**Comment by sunli829** [comment]
Give me some time and I will see why this happens.

**Comment by sunli829** [comment]
I didn't find the reason, @oeed do you have any suggestions?

**Comment by oeed** [comment]
Yeah I was rather stumped by that one. I would assume if the header is being set it's not a server issue.

Have you tried using Postman? Is there any JS that's potentially clearing the cookies? You could try an HTTP only cookie?

**Comment by onx2** [comment]
Thanks for the suggestions! I apologize in advance for the large post:


I tried a few more things including changing the cookie name, `HttpOnly`, and `Secure`, as well as removing the `expires` option. I also tried with postman. The response header shows `set-cookie` but in the Cookies tab it is showing "No cookies yet".

**Response headers tab**
![image](https://user-images.githubusercontent.com/23039725/126323265-07e1e44f-4ed3-4e0a-9e25-f4e8b72b202d.png)

**Cookies tab**
![image](https://user-images.githubusercontent.com/23039725/126322651-bc06dfdd-d629-4d81-b3af-41bca2155271.png)

**Cookies link in the top right**
![image](https://user-images.githubusercontent.com/23039725/126322043-ad45e464-acaa-44e3-918a-2a65076f4c6c.png)

I checked in my "/graphql" route and `req.cookie("sid")` unwrapped is `None`. 

Maybe there needs to be some special treatment for `Set-Cookie` header in https://github.com/async-graphql/async-graphql/blob/master/integrations/tide/src/lib.rs#L159-L173?

---

I also tested to see if a bare bones Tide app would set the cookies correctly, and it is working:

<details>
  <summary>Bare bones tide w/ cookies</summary>

```rust
use tide::{http::Cookie, Request, Response, StatusCode};

async fn retrieve_cookie(req: Request<()>) -> tide::Result<String> {
    Ok(format!("sid cookies: {:?}", req.cookie("sid").unwrap()))
}

async fn insert_cookie(_req: Request<()>) -> tide::Result {
    let mut res = Response::new(StatusCode::Ok);
    res.insert_header("Set-Cookie", "sid=foobar; HttpOnly; Secure");
    // append_header also works
    // res.append_header("Set-Cookie", "sid=foobar; HttpOnly; Secure");
    Ok(res)
}

#[async_std::main]
async fn main() -> Result<(), std::io::Error> {
    tide::log::start();
    let mut app = tide::new();
    app.at("/").get(retrieve_cookie);
    app.at("/set").get(insert_cookie);
    app.listen("127.0.0.1:8080").await?;

    Ok(())
}
```

</details>


And here is the async-graphql bare bones project I'm now testing with:

<details>
  <summary>Bare bones async-graphql w/ cookies</summary>

```rust
use async_graphql::{http::{playground_source, GraphQLPlaygroundConfig}, Context, Object, Schema, EmptySubscription};
use tide::{http::mime, Body, Request, Response, StatusCode};

type Result<T> = std::result::Result<T, Box<dyn std::error::Error + Send + Sync>>;

struct MyToken(String);

struct QueryRoot;

#[Object]
impl QueryRoot {
    async fn current_token<'a>(&self, ctx: &'a Context<'_>) -> Option<&'a str> {
        ctx.data_opt::<MyToken>().map(|token| token.0.as_str())
    }
}

struct MutationRoot;

#[Object]
impl MutationRoot {
    async fn set_cookie(&self, ctx: &Context<'_>) -> Option<String> {
        ctx.insert_http_header("Set-Cookie", format!("testName=testValue"))
    }
}

#[async_std::main]
async fn main() -> Result<()> {
    let schema = Schema::build(QueryRoot, MutationRoot, EmptySubscription).finish();
    let mut app = tide::new();

    app.at("/graphql")
        .post({
            move |req: Request<()>| {
                let schema = schema.clone();
                async move {
                    let token: Option<String> = match req.cookie("testName") {
                        Some(cookie) => Some(cookie.value().to_string()),
                        _ => None,
                    };

                    let mut req = async_graphql_tide::receive_request(req).await?;
                    if let Some(token) = token {
                        req = req.data(MyToken(token));
                    }
                    async_graphql_tide::respond(schema.execute(req).await)
                }
            }
        });

    app.at("/").get(|_| async move {
        let mut resp = Response::new(StatusCode::Ok);
        resp.set_body(Body::from_string(playground_source(
            GraphQLPlaygroundConfig::new("/graphql"),
        )));
        resp.set_content_type(mime::HTML);
        Ok(resp)
    });

    app.listen("localhost:8000").await?;

    Ok(())
}

```
</details>

**Comment by DenisAloner** [comment]
@sunli829 ,  are you planning to add the ability to set cookies via context (ctx.insert_http_header) for Poem?

**Comment by sunli829** [comment]
> @sunli829 , are you planning to add the ability to set cookies via context (ctx.insert_http_header) for Poem?

Sorry I missed this, it has been added now. 😁

**Comment by DenisAloner** [comment]
@sunli829 , many thanks!
