### ISSUE TITLE
Generics and InputObjects

### ISSUE THREAD

**Issue by jescobar** [async-graphql/async-graphql#567]
Hi thanks for all the great job!!! 

I'm trying to make a inputobject with a generict param, something like this:

#[derive(InputObject, Debug)]
pub struct Request<T: Serialize> {
    pub parameters: T,
}

#[derive(InputObject, Debug)]
pub struct ListRequest<T: Serialize> {
    pub page_number: Option<i64>,
    pub page_size: Option<i64>,
    pub parameters: Request< Option< T > >,
    pub order_fields: Option<Vec<OrderTerm>>,
    pub search_global: Option<String>,
    pub search_fields: Option<Vec<SearchTerms>>,
}

the plan is after do something like: 

#[derive(InputObject, Serialize)]
pub struct UserList(ListRequest< UserFilter >);

however when I tried to compile I'm getting this issue ?

error[E0412]: cannot find type `T` in this scope
 --> src/feature_modules/common_module/request.rs:6:21
  |
6 |     pub parameters: T,
  |                     ^ not found in this scope

error[E0412]: cannot find type `T` in this scope
  --> src/feature_modules/common_module/request.rs:59:36
   |
59 |     pub parameters: Request<Option< T >>,
   |                                    ^ not found in this scope

I just noticied that if I remove the derive to InputObject it works, so I don't know if that is supported and/or if I'm making something wrong, I will apreciate if you could give me a little bit of guidance with this please?

**Comment by cptrodgers** [comment]
You need to declare what type and name of type will be used with Generic.

You can try this code below.
```rust
#[derive(InputObject, Debug)]
#[graphql(concrete(name = "UserFilterListRequest", params(UserFilter)))]
pub struct ListRequest<T: Serialize> {
    pub page_number: Option,
    pub page_size: Option,
    pub parameters: Request< Option< T > >,
    pub order_fields: Option<Vec>,
    pub search_global: Option,
    pub search_fields: Option<Vec>,
}
```

Refs: https://async-graphql.github.io/async-graphql/en/define_input_object.html#generic-inputobjects
Please wrap your code with "```" and "```".

**Comment by jescobar** [comment]
Thanks a lot for your reply I will do that!! I will close this since it is exactly what I need,
