### ISSUE TITLE
Schema::build generates incorrect schema

### ISSUE THREAD

**Issue by Corb3nik** [async-graphql/async-graphql#568]
Hello :wave:

I've encountered an issue with async-graphql >= `2.9.4` where building a `Schema` object would result in a schema containing the wrong mutations and subscriptions.

## Expected Behavior
Given the following files : 

```rust
// src/mutations/a.rs
use async_graphql::SimpleObject;

#[derive(SimpleObject, Default)]
pub struct A {
    pub this_wont_show_up: u8,
}

```

```rust
// src/mutations/mod.rs
use a::A;
use async_graphql::MergedObject;

mod a;

#[derive(Default, MergedObject)]
pub struct Mutation(A);

```

```rust
// src/queries/a.rs
use async_graphql::SimpleObject;

#[derive(SimpleObject, Default)]
pub struct A {
    pub a: u8,
}
```

```rust
// src/queries/mod.rs
mod a;

use a::A;
use async_graphql::MergedObject;

#[derive(Default, MergedObject)]
pub struct Query(A);

```

```rust
// src/main.rs
mod mutations;
mod queries;

use mutations::Mutation;
use queries::Query;

fn main() {
    let schema = async_graphql::Schema::build(
        Query::default(),
        Mutation::default(),
        async_graphql::types::EmptySubscription::default(),
    )
    .finish();

    println!("{}", schema.sdl());
}
```

Running this code should display the following schema : 

```graphql
type Query {
        a: Int!
}
type Mutation {
        thisWontShowUp: Int!
}
schema {
        query: Query
        mutation: Mutation
}

```

## Actual Behavior

Running the code above instead displays : 
```graphql
type Query {
        a: Int!
}
type Mutation {
        a: Int!
}
schema {
        query: Query
        mutation: Mutation
}

```

Notice the `Mutation` type containing the `Query` type's `a` field.

## Steps to Reproduce the Problem

1. Clone the following repository:  https://github.com/Corb3nik/async-graphql-schema-issue
2. Run `cargo run`

## Specifications

- Version: >= 2.9.4
- Platform: macos

**Comment by Corb3nik** [comment]
This seems to be related to the fact that both the `Query` and `Mutation` types are composed from a struct with the same name. Changing the mutation's `A` struct to another name fixes the issue.

**Comment by sunli829** [comment]
Don't define any type with the same GraphQL name, this will cause some strange problems.
