### ISSUE TITLE
Binary Transmission

### ISSUE THREAD

**Issue by cloudybyte** [async-graphql/async-graphql#569]
We want to transmit a `Vec<u8>`. Because JSON does not support binary data we chose CBOR for transmittion, but it appears that binary transmission is [not supported](
https://docs.rs/async-graphql-value/2.9.8/src/async_graphql_value/lib.rs.html#126-142) in async-graphql? Or are we looking at the wrong place?

**Comment by sunli829** [comment]
Binary transmission requires you to implement it yourself, which is easy. You just need to `Response` serialized as binary format you want.

**Comment by cloudybyte** [comment]
I think you misunderstood what I meant. We want to transmit data like images and pgp keys...

**Comment by cloudybyte** [comment]
We basically want to encode the traffic in CBOR and use custom scalars to send binary data in the encoded response

**Comment by sunli829** [comment]
Ah, I see, you want `Value` to support binary types, so that CBOR can serialize binary values.

**Comment by sunli829** [comment]
I implemented this on the master branch, I hope you can help test it.

**Comment by cloudybyte** [comment]
We're currently trying to get cbor serializing to work in order to test the binary transmission, but aren't able to test our implementation because graphiql and graphql playground both don't support deserializing it...

**Comment by cloudybyte** [comment]
it seems like we can't just serialize the request in cbor, because the deserializing is done in async-graphql. I tried to implement a function, but it seems like the errors depending on it are hardcoded to `serde_json::Error`

**Comment by Miaxos** [comment]
Maybe if we could change the args to a dynamic impl of Error ?
https://github.com/async-graphql/async-graphql/compare/master...Miaxos:master

**Comment by cloudybyte** [comment]
We tried that, but that was causing many more problems... If it compiles and works I guess it's a good fix

**Comment by Miaxos** [comment]
>but that was causing many more problems

Can you elaborate on the problems?

**Comment by cloudybyte** [comment]
Basically just causing many 'mismatched type' errors

**Comment by Miaxos** [comment]
ok, it seems good with my change

**Comment by Erik1000** [comment]
Got it working for incoming cbor on [our branch](https://github.com/minkan-chat/async-graphql).

However, the whole way it is implemented doesn't look good to me. For the library I am thinking to decide which method to use based on the ``Accept-Encoding`` header. E.g. if it is set to ``application/json`` return json or if ``application/cbor`` return cbor. Also most if not all of the tests fail because of the strict use of serde_json. @sunli829 what do you think?

**Comment by sunli829** [comment]
I'll check this out in a few days. I don't have a computer on hand right now.😁

**Comment by Erik1000** [comment]
So I implemented my idea and got it working. A server implementation is available [here](https://github.com/minkan-chat/server/tree/42ea53fc7fae706eac7d30caf2857b6d8ccef8dd) with GraphQL Playground (uses json) enabled in debug builds and a rust client with cbor [here](https://github.com/minkan-chat/client/tree/52de1bb699c4d2e22b24738f99561b24fea88f10).

``cargo test --all-features`` seems to work but there's something wrong with the tide integration.

**Comment by Erik1000** [comment]
Also I suggest to use a Decoder Trait instead. It is a mess if everyone has to change the library code for their custom decoders.

**Comment by sunli829** [comment]
Let me think about it.🙂

**Comment by sunli829** [comment]
I will close this issue, if you have other questions, please feel free to open it.
