### ISSUE TITLE
Access query variables inside Guard?

### ISSUE THREAD

**Issue by benwis** [async-graphql/async-graphql#570]
I can't seem to figure out if I can access the query or mutation variables of the current query from inside the guard function.

Ideally I'd like to get the user_id variable from the query to match it against the one stored in context. So if the query is 
```
query {
user(id: "benwis"}{
id
}
```
I'd like to write this Guard: 
```
#[graphql(guard(or(RoleGuard(role = "Role::SuperAdmin"), UserGuard())))]
```
where UserGuard checks if the user queried equals the one decoded in the access token. The only thing hindering me is getting the value of the id variable.

Am I missing something or is there a better way?

**Comment by Mautriz** [comment]
I think guards are supposed to be query independent, this is clearly for this specific query only, you can just make a function and call it inside the resolver imo

**Comment by sunli829** [comment]
I forgot to document this feature, here is a test.

https://github.com/async-graphql/async-graphql/blob/80da563b2468dcb993ba803611bce3e251e18014/tests/guard.rs#L515

**Comment by benwis** [comment]
As it tuns out, this is totally possible. I was looking for the undocumented Context_Base param_value() function.
I know I can do it in the resolver itself, but it's a better developer experience to automate it with a guard!
Thanks for the help @Mautriz 
An example:
```rust        
let query_user_id = ctx.param_value::<Uuid>("id", None).ok();
```

@sunli829 Dang, I was just about to post this and close and you've already replied! Thanks!
