### ISSUE TITLE
Custom Headers Dropped on Error

### ISSUE THREAD

**Issue by benwis** [async-graphql/async-graphql#572]
I'd like to add some custom headers to an Error response from a Guard, but it appears to silently drop them. It works fine when the response is not an Error. Essentially, I'm trying to return new tokens if the refresh token is valid and the access is not, and Error out.

Not sure if this is a bug or a feature request, feel free to move it.

## Steps to Reproduce the Problem

1. Use ContextBase.insert_header("test", "value");
2. return Err("It's broken")
3. Look at API response, the headers are not there.
4. Return OK(()) instead, headers are set

## Specifications

- Version: 2.9.5
- Platform: Linux
- Subsystem: CTX/Errors

**Comment by sunli829** [comment]
You are right, it is indeed better to attach custom HTTP headers to the response when an error occurs.

**Comment by benwis** [comment]
Thanks for the commit! I updated async-graphql and async-graphql-actix-web to the latest  git commit, and tested it again. It still seems like the headers are not being added.

**Comment by sunli829** [comment]
Sorry, I have fixed it. 🙂

**Comment by benwis** [comment]
No need to apologize! Headers on Errors are now working as expected! Feel free to close this issue. 

Also, you should setup Github sponsor! I'd totally be willing to help fund development.

**Comment by sunli829** [comment]
Haha, thank you!
