### ISSUE TITLE
Structs imported with `use {Something as Another}` still use the original name in the GraphQL schema

### ISSUE THREAD

**Issue by mattoni** [async-graphql/async-graphql#576]
## Expected Behavior
I expect that importing as another name will use the new name, not the original. I'm sure this is more complex but my use case is that I have a generated struct from a gRPC backend I'm doing the `#[Object] impl` on, but the name isn't suitable to be exposed to the client. My only option so far seems to be recreating the struct which seems tedious and unnecessary.

Barring that, it'd be nice to have a `#[graphql(name = "blah")]` for an `impl`, but that seems to not work either currently.

## Actual Behavior
The struct shows up in the schema as the original name regardless of what it's imported as, or allow an override.

## Steps to Reproduce the Problem

1. import something as another name
2. Use in the schema
3. Observe the name in the playground is the original name, not the imported name.

## Specifications

- Version: 2.9
- Platform: Mac
- Subsystem:

**Comment by sunli829** [comment]
Attribute macros must pass parameters in the following way.

```rust
#[Object(name = "blah")]
```

**Comment by mattoni** [comment]
Ah I see, thank you!
