### ISSUE TITLE
SDL print is still not stable

### ISSUE THREAD

**Issue by oeed** [async-graphql/async-graphql#577]
I believe the issue mentioned in #547 is still present. I've made a failing test in my fork [here](https://github.com/oeed/async-graphql/commit/28f6c162f4bd2fb241504a4dae09367b315c697e).

For example, `schema_1` looks like this:

```gql
type Query {
  a: Int!
}
input InputD {
  value: Boolean!
}
type Mutation {
  d(input: InputD!): Boolean!
}
schema {
  query: Query
  mutation: Mutation
}
```

`schema_2` only adds `MutationD` and `QueryC`, but it results in line removals (notice that `InputD` is now after `Mutation`).

```gql
type Query {
  a: Int!
  c: Int!
}
type Mutation {
  d(input: InputD!): Boolean!
  f(input: InputF!): Boolean!
}
input InputF {
  value: Boolean!
}
input InputD {
  value: Boolean!
}
schema {
  query: Query
  mutation: Mutation
}
```

One potential option would be to simply sort the SDL output.

**Comment by sunli829** [comment]
Thank you, I will see it tomorrow.

**Comment by sunli829** [comment]
@oeed 

There is currently no guarantee that the SDL exported by two different schemas will follow a certain order. If you really need this feature, I can only output it after sorting by type name.

**Comment by oeed** [comment]
I see, that makes sense. For my use case I'm commuting the schema to my git and want the changes to be easily identifiable.

Without having delved too much in to the source, how complex would it be to implement? I'd be willing to make a PR if it's achievable.

**Comment by sunli829** [comment]
When I put the output types in order, but your test still fails.

**Comment by sunli829** [comment]
You can merge the latest version code to see the result.

**Comment by oeed** [comment]
Thanks, that does appear to be a step in the right direction. I believe the test is failing because `type Mutation` is still changing position though:

`schema_1`:
```gql
type Query {
        a: Int!
}
input InputD {
        value: Boolean!
}
type Mutation {
        d(input: InputD!): Boolean!
}
schema {
        query: Query
        mutation: Mutation
}
```

`schema_2`:
```gql
type Query {
        a: Int!
        c: Int!
}
type Mutation {
        d(input: InputD!): Boolean!
        f(input: InputF!): Boolean!
}
input InputF {
        value: Boolean!
}
input InputD {
        value: Boolean!
}
schema {
        query: Query
        mutation: Mutation
}
```

**Comment by sunli829** [comment]
This is my result.

schema1:

```gql
input InputD {
	value: Boolean!
}
type Mutation {
	d(input: InputD!): Boolean!
}
type Query {
	a: Int!
}
schema {
	query: Query
	mutation: Mutation
}
```

schema2:

```gql
input InputD {
	value: Boolean!
}
input InputF {
	value: Boolean!
}
type Mutation {
	d(input: InputD!): Boolean!
	f(input: InputF!): Boolean!
}
type Query {
	a: Int!
	c: Int!
}
schema {
	query: Query
	mutation: Mutation
}
```

**Comment by oeed** [comment]
🤦 sorry! My mistake, I didn't merge the changes on my local properly - getting the same as you now.

It appears the test should be passing, the diff crate is just being weird `[Rem("input InputD {"), Add("input InputD {")]`.

From my testing in general use it appears to be working properly now - thank you!! 🙏
