### ISSUE TITLE
Support for Apollo connectionParams

### ISSUE THREAD

**Issue by Ejhfast** [async-graphql/async-graphql#58]
Are there any plans to support `connectionParams` passed by an Apollo client? These are parameters passed by the client with its first websocket message and used to initialize a context object on Apollo Server ([example](https://www.apollographql.com/docs/react/data/subscriptions/#authentication-over-websocket
)): https://www.apollographql.com/docs/apollo-server/data/subscriptions/#authentication-over-websocket

I think this feature is specific to Apollo Client, but it would be very convenient!

**Comment by sunli829** [comment]
I think I already support this feature, please see example https://github.com/async-graphql/examples/blob/83103dbe32184d0ae6112a3e2b8e5b58245d8fd0/actix-web/token-from-header/src/main.rs#L57.
Is that what you want?😁

**Comment by Ejhfast** [comment]
Oh, great! Thanks for the super quick response. I had wondered why you changed `data(...)` before to take a closure and that now makes perfect sense.
