### ISSUE TITLE
Apollo Studio extension

### ISSUE THREAD

**Issue by Miaxos** [async-graphql/async-graphql#580]
Hello 👋,
I made an extension to connect my GQL to Apollo Studio to monitor everything and I just open-sourced it!

I was wondering if it was possible to add it on the README that an extension to monitor an async_graphql api is available for those who use Apollo Studio. (Or event add it to the async_graphql organisation, I think it's a little to big to just go into the crate repo, but tell me if I'm wrong).

( Implemented following: https://www.apollographql.com/docs/studio/setup-analytics/#sending-metrics-to-the-reporting-endpoint )

I'm eager to have your feedback!

https://github.com/Miaxos/async_graphql_apollo_studio_extension
https://crates.io/crates/async-graphql-extension-apollo-tracing

**Comment by sunli829** [comment]
This extension is very useful, thank you for everything! 👏🏻
As a related project, I also think it is very necessary to add a link to the README of `Async-graphql`, please create a PR😁.
If you transfer this repo to the Async-graphql organization, it may be easier for other people to find it. Of course, this requires your consent. 😁

**Comment by Miaxos** [comment]
Yep! It's fine for me to transfer it, it'll be easier put it in this organization, I would just like to keep maintaining it and contributing to it!

**Comment by sunli829** [comment]
Sorry, I have sent out the invitation now. 🙂

**Comment by Miaxos** [comment]
Done! :-)

**Comment by Miaxos** [comment]
https://github.com/async-graphql/async-graphql/pull/582
