### ISSUE TITLE
Playground settings can only be &str

### ISSUE THREAD

**Issue by tim-maddison-rnf** [async-graphql/async-graphql#583]
## Expected Behavior

Playground settings should be able to accept any JSON type (although maybe not Object or Array?).

## Actual Behavior

[`with_setting`](https://docs.rs/async-graphql/2.9.9/async_graphql/http/struct.GraphQLPlaygroundConfig.html#method.with_setting) can only accept a `&str` for the value, so any values passed are serialised into a JSON string. These then stay as a string while being inserted into the playground settings.

```rust 
playground_source(
      GraphQLPlaygroundConfig::new("/admin/api/graphql")
          .with_setting("schema.polling.enable", "false"),
)
```

![image](https://user-images.githubusercontent.com/74549686/126666290-234f1420-8b05-4f3e-b59b-b133d6a0dc80.png)

## Specifications

- Version: 2.9.9
- Platform: Linux

I think this could be solved by changing `GraphQLPlaygroundConfig`'s settings Hashmap into `Hashmap<&'str, Value>` and then changing `with_setting` to accept a Value. 

I'd be happy to put a PR together for this, let me know if you think this is viable.

**Comment by sunli829** [comment]
Good idea,welcome to PR.👏
