### ISSUE TITLE
Broaden impl ScalarType for HashMap to use ToString/FromStr

### ISSUE THREAD

**Issue by stijnfrishert** [async-graphql/async-graphql#585]
Currently `ScalarType` is [implemented](https://docs.rs/async-graphql/2.9.9/src/async_graphql/types/external/json_object/hashmap.rs.html) for `HashMap<String, T>`, which translates to a `Value::Object`.

Would it be possible to broaden this restriction to `HashMap<K, T> where K: ToString + FromStr`? I've got `HashMap`'s in my code that I could love to work out of the box, but because my `Key` type isn't `String` (but can convert from/to that), this wouldn't work.

**Comment by sunli829** [comment]
Good idea, but I don’t have a computer these days, would you like to send a PR?😅

**Comment by stijnfrishert** [comment]
Yeah, I think I might actually! Will see if I can find sometime this week :)

**Comment by sunli829** [comment]
Already supported on the `master` branch.
