### ISSUE TITLE
Beta Version with Support for Actix 4 beta

### ISSUE THREAD

**Issue by benwis** [async-graphql/async-graphql#590]
## Description of the feature
It's getting harder to pin all of our dependencies to a version that uses tokio v0.2 and not tokio v1. It'd be nice to be able to use a beta async-graphql and the actix v4 beta.

Thank you!

## Code example (if possible)

**Comment by Miaxos** [comment]
I don't understand what you means sorry (I do not use actix-web), are u meaning you can't use async-graphql with tokio 1 ?

**Comment by benwis** [comment]
I'm not sure about async-graphql and tokio plain, but if you use it with actix it depends on actix-web 3 (the latest stable version) which uses tokio 0.2.

So if you try to use something like sqlx, which uses tokio v1, it will panic and say that it must run in a tokio v1 reactor. 

So you can either make sure all your packages use tokio 0.2 or 1. Most of my dependencies have updated or have a beta that supports v1, except for async-GraphQL. So I'm forced to downgrade everything else to a version that supports tokio 0.2

I'd love to get a beta version of async-graphql to use with the actix 4 beta(which uses tokio v1) and save myself some effort :)

**Comment by Miaxos** [comment]
> Most of my dependencies have updated to v1, except for async-GraphQL

Thank you for the explaination!
I'm using it with tokio 1.0 without any trouble, but not with actix, with warp, it explains why I didn't understand ^^.

> Yeah if you use it with actix it depends on actix-web 3 (the latest stable version) which uses tokio 0.2.

Okay, I understand your issue: `async_graphql` has not a tokio dependency, it's only the integration `async-graphql-actix-web` with actix that does have one, it's only this part: https://github.com/async-graphql/async-graphql/blob/master/integrations/actix-web/Cargo.toml#L19 which you should be using with actix-web wich use actix-web 3 and so tokio 0.2.

Well, there is already a branch here by @sunli829: https://github.com/async-graphql/async-graphql/compare/actix-web-v4-beta to contribute (which may be working if you want to use actix 4 beta)

**Comment by sunli829** [comment]
`Actix-web-v4` already supported in branch `actix-web-beta`

**Comment by DenisAloner** [comment]
Benwis, you can add this to Cargo.toml:

[dependencies]
actix-files = "0.6.0-beta.6"
actix-http = "3.0.0-beta.8"
actix-service = "2.0.0"
actix-cors = "0.6.0-beta.2"
actix-web = { version = "4.0.0-beta.8", features = ["openssl"] }
async-graphql = { git = "https://github.com/async-graphql/async-graphql", rev = "a492db23fb55cc99a0acc4f85e44b998e4e3892b", features = [
    "dataloader",
] }

**Comment by benwis** [comment]
Yeah I started looking at that. I might need to get some of the more recent fixes merged into that branch. But that should work. Thanks guys!

**Comment by bottd** [comment]
Does anyone who has been using the branch have an example they can link to? I’m trying to get the actix beta working so I can update my sqlx version. With this branch my playground loads but it cannot load docs/schema, or successfully make a request. No errors while building or while requests fail.

**Comment by bottd** [comment]
I'm still a Rust noobie so I'm sure there is something I got wrong while upgrading, these will be a super helpful reference. Thank you!

**Comment by benwis** [comment]
This is fixed for us, and the examples make it a lot easier. Feel free to close unless you want to leave it a a reference for others.

**Comment by benwis** [comment]
It'd be kinda neat to have an official beta on cargo itself, that's where I looked at first and I didn't think to check the git branches :)

**Comment by kennetpostigo** [comment]
Hey @sunli829, 

I'm trying to target the actix beta branch with:
```toml
async-graphql-actix-web = { git = "https://github.com/async-graphql/async-graphql", branch = "actix-web-v4-beta" }
```

However, I'm getting this issue when I try to check/build:
```rust
cargo clippy
    Updating crates.io index
    Updating git repository `https://github.com/async-graphql/async-graphql`
error: cyclic package dependency: package `ahash v0.7.4` depends on itself. Cycle:
package `ahash v0.7.4`
    ... which satisfies dependency `ahash = "^0.7.0"` of package `hashbrown v0.11.2`
    ... which satisfies dependency `hashbrown = "^0.11"` of package `indexmap v1.7.0`
    ... which satisfies dependency `indexmap = "^1.5"` of package `serde_json v1.0.68`
    ... which satisfies dependency `serde_json = "^1.0"` of package `wasm-bindgen v0.2.78`
    ... which satisfies dependency `wasm-bindgen = "^0.2.78"` of package `js-sys v0.3.55`
    ... which satisfies dependency `js-sys = "^0.3"` of package `getrandom v0.2.3`
    ... which satisfies dependency `getrandom = "^0.2.0"` of package `ahash v0.7.4`
    ... which satisfies dependency `ahash = "^0.7"` of package `actix-http v3.0.0-beta.10`
    ... which satisfies dependency `actix-http = "^3.0.0-beta.10"` of package `actix-web v4.0.0-beta.9`
    ... which satisfies dependency `actix-web = "^4.0.0-beta.8"` of package `actix-cors v0.6.0-beta.2`
```

Not sure if this is a very difficult fix, but right now we're decoupling our core logic from our REST API and it currently uses the `actix-web` beta(sorry).  Has anyone else ran into this, or gotten this fixed?

**Comment by Guara92** [comment]
@sunli829 pls could you rebase the `actix-web-v4-beta` branch in the meantime?

**Comment by sunli829** [comment]
I have done it. 😁

**Comment by sunli829** [comment]
The branch `actix-web-v4-beta` has been updated, many thanks to @sergeysova

**Comment by Sytten** [comment]
We should keep an issue alive until it is merged I think.

**Comment by Sytten** [comment]
@sunli829 FYI when you rebase the branch for actix it changes the older commit so it is really hard to keep it working. Would you mind doing pre/beta-releases so we can use those? Otherwise merging back main into the branch (uglier git history I know :S) instead of rebasing it. Thanks a lot :)

**Comment by Sytten** [comment]
This should be closed
