### ISSUE TITLE
Stream upload

### ISSUE THREAD

**Issue by phungtranminh** [async-graphql/async-graphql#591]
Hi,

I recently read on `warp` about streaming upload. It seems that `warp` doesn't handle it currently, so I assume `async-graphql` has the same limitation?

Assume this PR in warp being merged in https://github.com/seanmonstar/warp/pull/846, I wonder if `async-graphql` need to update or something to make it work?

Thanks,

**Comment by sunli829** [comment]
Use `async_graphql_warp::graphql_opts` to limit the payload size.

**Comment by phungtranminh** [comment]
Hey Sunli,

Thanks, I probably wasn't very clear in the issue. I wasn't thinking about payload size. What I meant is to stream the uploaded file directly into a file (or to another socket) instead of loading into memory first. The intention is probably to reduce the memory and cpu usage.

**Comment by sunli829** [comment]
`Async-graphql` will write the uploaded content into a temporary file, so there is no need to worry about memory usage.

https://github.com/async-graphql/async-graphql/blob/c4cfa24e4172c1dad4e1148e87dd6cc4a6d8ca50/src/http/multipart.rs#L87

**Comment by phungtranminh** [comment]
Oh nice, that's handy, thanks let me read around
