### ISSUE TITLE
Dataloader Module not public

### ISSUE THREAD

**Issue by cloudybyte** [async-graphql/async-graphql#593]
The dataloder module is not accessible via the public api. I want to implement the [N+1 dataloader](https://async-graphql.github.io/async-graphql/en/dataloader.html) chapter of the async graphql book. Unfortunately the examples don't work because the `ctx` variable in the `dataloader` example is not declared and one cannot access the module from outside the crate.

**Comment by sunli829** [comment]
Make sure you have enabled the `dataloader` feature.

**Comment by sunli829** [comment]
I will close this issue, if you have other questions, please feel free to open it.
