### ISSUE TITLE
Interfaces not included if not explicitly returned

### ISSUE THREAD

**Issue by Erik1000** [async-graphql/async-graphql#595]
## Expected Behavior
If a query or a mutation returns a type that implements a interface in the source code, the type should implement the interface in the schema too. Of course, the interface should be in the schema too.

## Actual Behavior
If a query or mutation returns a type that implements a interface, the type does not implement it in the generated schema. Actually the interface is not even in the schema.

I noticed that this is the case with normal types too as long as they aren't used, which is not a problem but it is for interfaces.

## Steps to Reproduce the Problem

Minimal code needed to reproduce:

```graphql
use async_graphql::*;

pub type BugSchema = Schema<Query, EmptyMutation, EmptySubscription>;

pub struct Query;

#[Object]
impl Query {
    async fn some_query(&self) -> SomeType {
        SomeType { interface_field_i: "I dont implement Interface ``I``".to_string() }
    }
    /* Workaround:
    async fn return_interface_direct(&self) I {
        I::SomeType(SomeType P interface_field_i: "Now I implement Interface ``I``".to_string())
    }
    */
}

#[derive(SimpleObject)]
struct SomeType {
    interface_field_i: String,
}


#[derive(Interface)]
#[graphql(field(name = "interface_field_i", type = "String"))]
enum I {
    SomeType(SomeType)
}
```
I have a bit more code to show the bug [here](https://github.com/Erik1000/async-graphql-interface-bug). A way more complex example with an actual usecase can you find [here](https://github.com/minkan-chat/server).
## Specifications

- Version: Master (b1bdfb35ee26616be04377104e7f31e7a5a6e7cb)
- Platform:  
``Linux 5.8.0-63-generic #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021 x86_64 x86_64 GNU/Linux``
- Rust versions: 
```
nightly-x86_64-unknown-linux-gnu (default)
rustc 1.56.0-nightly (e3b1c12be 2021-08-02)
```
and
```
stable-x86_64-unknown-linux-gnu (default)
rustc 1.54.0 (a178d0322 2021-07-26)
```

**Comment by sunli829** [comment]
`Async-graphql` collects the type information directly referenced by `Schema` in the initialization phase. Although `SomeType` implements `I`, it is not directly referenced by `Schema`.
Use the `SchemaBuilder::register_type` function to manually register the `I` type.
