### ISSUE TITLE
Partial update and double `Option` types

### ISSUE THREAD

**Issue by nicolaiunrein** [async-graphql/async-graphql#598]
say I have an InputObject like so:
```rust
#[derive(gql::InputObject)]
struct PartialUpdate {
  name: Option<String>
  value: Option<Option<usize>>
}
```
I would expect `value` to be `None` if field is not defined, `Some(None)` if field is explicitly set to `null` and `Some(Some(...))` otherwise.

# Example

```gql
mutation {
  update(options: { name: "Hello" }) 
}
```
==>
```rust
PartialUpdate {
  name: Some(String::from("Hello")),
  value: None
}
```

=======================

```gql
mutation {
  update(options: { name: "Hello", value: null}) 
}
```
==>
```rust
PartialUpdate {
  name: Some(String::from("Hello")),
  value: Some(None)
}
```

=======================

```gql
mutation {
  update(options: { name: "Hello", value: 1}) 
}
```
==>
```rust
PartialUpdate {
  name: Some(String::from("Hello")),
  value: Some(Some(1))
}
```
Is this something which is possible already? Note: if I set default_with="Some(None)" I get a distinction but it is inverted.

**Comment by sunli829** [comment]
You can use `MaybeUndefined`.

https://docs.rs/async-graphql/2.9.10/async_graphql/types/enum.MaybeUndefined.html

**Comment by nicolaiunrein** [comment]
Maybe we should link this type to the `InputObject` section in then docs?! That's where I looked at the field parameters
