### ISSUE TITLE
Parse error - MultipleOperations

### ISSUE THREAD

**Issue by StarpTech** [async-graphql/async-graphql#602]
I faced this error during the benchmark of GraphQL parsers in the wild.

Query: https://github.com/StarpTech/graphql-parser-bench/blob/main/kitchen-sink.graphql
Code: https://github.com/StarpTech/graphql-parser-bench/tree/main/async-graphql-parser

```
❯ RUST_BACKTRACE=1 cargo run ./../kitchen-sink.graphql query
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/rust-async-graphql-parser ./../kitchen-sink.graphql query`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MultipleOperations { anonymous: Pos(56:1), operation: Pos(6:1) }', src/main.rs:12:53
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ae90dcf0207c57c3034f00b07048d63f8b2363c8/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/ae90dcf0207c57c3034f00b07048d63f8b2363c8/library/core/src/panicking.rs:93:14
   2: core::result::unwrap_failed
             at /rustc/ae90dcf0207c57c3034f00b07048d63f8b2363c8/library/core/src/result.rs:1617:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/ae90dcf0207c57c3034f00b07048d63f8b2363c8/library/core/src/result.rs:1299:23
   4: rust_async_graphql_parser::main
             at ./src/main.rs:12:9
   5: core::ops::function::FnOnce::call_once
             at /rustc/ae90dcf0207c57c3034f00b07048d63f8b2363c8/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by sunli829** [comment]
Thank you for the error report, I will start to solve this tomorrow. 🙂

**Comment by sunli829** [comment]
This is not a bug, because this query is illegal.

> If operations is a set of more than 1: anonymous must be empty.

https://spec.graphql.org/draft/#sec-Lone-Anonymous-Operation

**Comment by StarpTech** [comment]
This is interesting. All other parsers were able to handle it gracefully. Thanks for the check!

**Comment by StarpTech** [comment]
@sunli829, the query is according to the specification correct. The parser mustn't produce an error but the validation procedure.

**Comment by sunli829** [comment]
You are right, the query syntax is fine, but `async-graphQL` adds some validation during parsing.

**Comment by StarpTech** [comment]
I see! This might be sufficient for that project but doesn't allow us to use it as a general parser. I'd move that check to the validation step according to https://github.com/async-graphql/async-graphql/blob/d37495e43530278463bccf7aa60dc4b08aaa2261/ARCHITECTURE.md
