### ISSUE TITLE
ntex support?

### ISSUE THREAD

**Issue by sergeyshaykhullin** [async-graphql/async-graphql#606]
## Description of the feature
Does [ntex](https://github.com/ntex-rs/ntex) can be a good project for async-graphql built-in integration?

## Code example (if possible)

**Comment by sunli829** [comment]
I'm not sure. In fact, I haven't used `ntex`, but I think it should be very easy to make `async-graphql` support `ntex`.

**Comment by atik7** [comment]
please add ntex integration,
