### ISSUE TITLE
Publish async-graphql-axum to crates.io

### ISSUE THREAD

**Issue by Voxelot** [async-graphql/async-graphql#608]
## Description
Most of the integrations are published to crates.io, but axum currently isn't. It would be very helpful to have `async-graphql-axum` published.

**Comment by Miaxos** [comment]
It's not possible to publish a crate that relies on git dependencies. This PR https://github.com/async-graphql/async-graphql/pull/607 should remove the git dependency and allow the crate to be published.

**Comment by Voxelot** [comment]
Closing as this has now been published!
