### ISSUE TITLE
 Scoped context data

### ISSUE THREAD

**Issue by Dispersia** [async-graphql/async-graphql#611]
## Description of the feature
 Hello, looking into `context` it appears its only shared globally. Is there a safe way to guarantee that data is shared only on the same request? As an example:
 
 ```
 # Write your query or mutation here
mutation foo {
  bar

  fooBar
}
```

if bar adds a number to context, I would like to be able to use that number in fooBar. I could simply wrap it in an Arc<Mutex<i32>>, but there is a chance the data gets stolen by another request inbetween. Possibly a hash of thread id or something? But i'm not sure of the implementation details if that would even work, nor would i know when i could clean up that data (since my methods can be chained, so I don't know when the last one ends)

Any suggestions would be appreciated, or if clarification is needed let me know. Thanks!

**Comment by sunli829** [comment]
Yes, of course this is supported.

You can use [Request::data](https://docs.rs/async-graphql/2.9.12/async_graphql/struct.Request.html#method.data).

Here is the example:

https://github.com/async-graphql/examples/blob/fec86ff7383b64375fa1ca0a4e7fdcffd6417086/warp/token-from-header/src/main.rs#L46

**Comment by sunli829** [comment]
Sorry, I misunderstood what you meant.
I think it's weird to make the data in the context mutable, can you tell me why you do this, maybe I can help you. 🙂

**Comment by sunli829** [comment]
You want the field resolve to depend on a certain order, the result of the `fooBar` field depends on `bar`, which is not a good idea.

**Comment by Miaxos** [comment]
If you want to do this, I suggest you create an intra-request cache, which would be a cache initiated at the beginning of the request and would drop at the end of the processing of the request, it would live until the end of the request, you would share it with a Request::data accross all resolver, but be careful as you would expect multiple concurrency issues if it is not well managed (you do not really want to create a constraint where a part of the query has to be proceed before another one).

You could even imagine a more advanced use case like this one:
I know Airbnb use a cache like to avoid multiple calls accros multiple queries:
A service `A` call GraphQL to process a query
GraphQL create a request ID, call micro-services C & B to get some Data with the request ID
Service B call GraphQL to get some data from the Service C
GraphQL has already get some data over C and cached it behind a request ID, so it can give service B the cached result.

**Comment by Dispersia** [comment]
According to the graphql spec, mutations should always resolve in order, serially, so from a spec perspective this is correct. If you simply mean from a usability perspective, this is to attempt to hide a little complexity from the user, and it doesn't necessarily need to be fooBar that runs after bar, it could be the other way too, just that i can use the data that is created of the first mutation. These can all be multiple objects created in a ton of different ways, so i can't just accept say an `objects: [ ]`, as it would have to accept types Foo | FooBar | 100 different objects.

That makes sense with the Request::data cache, I will check that out. Thank you for the tip!

**Comment by Dispersia** [comment]
that seems to work perfectly, didn't realize you can add data on the request as well as global context. Thanks!
