### ISSUE TITLE
Request specific Context

### ISSUE THREAD

**Issue by Erik1000** [async-graphql/async-graphql#613]
In the book, there's an example using [field guards for authorization](https://async-graphql.github.io/async-graphql/en/field_guard.html). There you have an enum Role that is in the Context. The Role however is dependent on the "user" making the request and is therefore request specific. My question is, how would you set this request specific role? It would make sense to have that in the same part of the code there the [schema is executed](https://github.com/async-graphql/examples/blob/master/actix-web/starwars/src/main.rs#L8), but it seems there's no way to set something there.

**Comment by Miaxos** [comment]
> How would you set this request specific role?

Well, you have a route inside your application, which will take your body, your headers, and a bunch of other stuff, with your schema, and it'll process the request where you can put data which will be accessible only while the request is processing (with https://docs.rs/async-graphql/2.9.12/async_graphql/struct.Request.html#method.data), usually it's something like:

```
let graphql_post = warp::post()
  .and(warp::path("graphql'))
  .and(schema_filter)
  .and(a_warp_filter)
  ...
  .and_then( |schema: (Schema<Query, Mutation, Subscriptions>, async_graphql::Request), arg2: ArgType2 ...| {
    let (schema, request) = schema;
    let response = schema
      .execute(
        request
         .data(your_auth_data)
         .data(something_else)
      )
  });
```

It's inside this route you set the request depending on your users (which you know with the headers Authorization token for instance).

And if u put something with a type `Role` in it, inside your graphql queries, you'll be able to get that by calling `ctx.data_opt::<Role>()`

**Comment by Erik1000** [comment]
oh obviously, i should've looked into that too. Thanks! Didn't know what Request has this method.
