### ISSUE TITLE
Add documentation for scalars like UUID

### ISSUE THREAD

**Issue by Erik1000** [async-graphql/async-graphql#621]
Currently, if you use the provided types for e.g. UUID, there's no documentation in the generated schema. 

Since these are custom scalars, there should be some documentation like in the case of UUID a brief description and a link to [RFC4122](https://datatracker.ietf.org/doc/html/rfc4122) so clients know how to parse these.

I'll open a PR when I have the time and motivation for this. Maybe someone else wants to do it. Would be pretty simple.

**Comment by sunli829** [comment]
Documentation has been added for this, thanks @Miaxos .
