### ISSUE TITLE
Why are variants with named fields not supported?

### ISSUE THREAD

**Issue by Erik1000** [async-graphql/async-graphql#622]
The derive macro for union (and interface) does not allow named fields e.g. this does not work:
```rust
use async_graphql::*;

#[derive(Interface)]
#[graphql(
    field(name = "name", type = "String"),
)]
pub enum MyEnum {
    SomeVariant {
        name: String,
    }
}
```

I know that you could create an extra type for that (and that's probably what I'm gonna do with a macro), but I'm just curious. Related code:: https://github.com/async-graphql/async-graphql/blob/master/derive/src/union.rs#L58 @sunli829

**Comment by sunli829** [comment]
Because this will generate some new structures, the IDE can't recognize it. I don't like this kind of macro very much. That's why I don't support it.😃

**Comment by Erik1000** [comment]
Hm okay then
