### ISSUE TITLE
Accessing schema context within custom validator

### ISSUE THREAD

**Issue by i-dentify** [async-graphql/async-graphql#623]
I had a look at https://async-graphql.github.io/async-graphql/en/input_value_validators.html and also digged through the code (as far as I understood as a rookie).

So far so good - one question remains: how can I access the data I registered via `Schema::build(...).data(...)` within a custom validator. The comments on the data function say 

> You access it with Context::data.

Is this the way to go? If yes: how? If no: any chance?

Concrete example: let's say I have an input type with a "name" property. I want to ensure, that there is no record with the submitted name in my database. I registered my database client within the `Schema::build(...).data(...)`. I'd like to use the client in my validator to query my database...

**Comment by Miaxos** [comment]
>within a custom validator

Well, with a custom validator, right now, you just can't access to the Context, why ?

A Custom Validator is in fact, a `struct` where `InputValueValidator` trait is implemented. This trait is available here: https://github.com/async-graphql/async-graphql/blob/master/src/validators/mod.rs#L43 and if we check it, we can see it's only a function which, based on the input, will tell us if the value is valid for this validator:

```rust
    fn is_valid(&self, _value: &Value) -> Result<(), String> {
        ...
    }
```

When can you use a custom validator? When you want to represent a domain rule to your general type, when you need to know you are dealing with an `Email` in your code but for some reasons, you can't just create a new scalar with these rules, you have to keep using a `String` input type: you use a validator, so you can be sure in your query, your `String` will be, in fact an `Email`, and you will be able to cast it into an `Email` without checking for errors (or at least you should be able :-) )

> let's say I have an input type with a "name" property. I want to ensure, that there is no record with the submitted name in > my database. I registered my database client within the Schema::build(...).data(...). I'd like to use the client in my validator > to query my database...

You can't, but you'll be able to access to the context within a resolver, and inside your resolver, you have access to the `Context` like explained here: https://async-graphql.github.io/async-graphql/en/context.html#store-data (feel free to tell me if it's not clear enough)

But if you reaaaaaally want to check, inside a Database, each time you have an input type with a "name" property, you could create an `Extension`, which would implement the `Extension` trait, and you would have to add an step at the validation step to create this check. There you would be able to access to the `Context` and to your `Database`.

**Comment by i-dentify** [comment]
Hi - thanks for your answer... Well - I already examined the InputValueValidator code and got the impression there, that Context is not available there. I thought it would be globally accessible then... anyway...

Of course I can handle my kind of validation in the resolver. But to me this would mean, that I am mixing validation code with normal resolver code. This would be not a thing for me, if there was ONLY resolver code. But as validators exist, my assumption would be to place validation rules - and I mean all kind of validation rules - inside validators. Point is: if - like in your example - a submitted Email is not valid, I'd return an error message like "Not a valid email address". And if a name is already taken, I'd return an error message like "This name is already in use". Returning such validation error messages from two different types of code is what I usually try to avoid.

But good hint with the `Extension` trait - I'll have a look at this.

**Comment by Miaxos** [comment]
Well `async validation` could be awesome but there is two main issues IMO:

## First issue

Accessing the `Context` inside the validation process isn't possible right now, because it's created at the `execute` process.

The data shared across the Schema are accessible inside this step, so a change could be to allow an access to these data inside the `InputValueValidator` it's not a little change, but it's possible without having to change the workflow, we should just pass the reference to the `SchemaEnv` across the `prepare_request` workflow to the `InputValueValidator`s.

## Second issue

This change would means we would have to have an `InputValueValidator` with async functions (which is a breaking change) and would imply to rework the entire validation system with async functions.

So it's possible but it's starting to becoming a big change. It might be a possible feature for an 3.0.

What do you think about it @sunli829?

**Comment by sunli829** [comment]
I think the current validators implementation is not very elegant, so I am trying a new implementation in the `poem-openapi` project. If I finish it, I will use it for `Async-graphql`. 🙂
