### ISSUE TITLE
u64 rounding

### ISSUE THREAD

**Issue by Ech0riginal** [async-graphql/async-graphql#626]
## Expected Behavior
When presenting a u64 (or vector of) to a user/client, we expect to see the full u64 value.
```json
{
  "data": {
    "mockBug": {
      "indices": [
        644690432274950468,
        644690432274950467,
        644690432274950466
      ]
    }
  }
}
```

## Actual Behavior
The u64s seem to be rounded up to the 15th place, as shown here:
```json
{
  "data": {
    "mockBug": {
      "indices": [
        644690432274950500,
        644690432274950500,
        644690432274950500
      ]
    }
  }
}
```
## Steps to Reproduce the Problem
1. `git clone https://github.com/Ech0riginal/async_graphql_bug_report.git && cd async_graphql_bug_report`
2. `RUST_LOG=trace cargo run`
3. Navigate to the playground running on `localhost:8080` and submit the following query:
```graphql
{
  mockBug {
    indices
  }
}
```

## Specifications

- Version: actix-web-v4-beta#57dfaf62
- Platform: N/A
- Subsystem: async-graphql-actix-web

**Comment by sunli829** [comment]
This is not a bug of `Async-graphql`, it is because the JS integer in the browser only supports up to 53 bits. If it exceeds this limit, it will be converted to a floating point number (if I remember correctly).
I suggest you use `StringNumber`.

https://docs.rs/async-graphql/2.9.14/async_graphql/types/struct.StringNumber.html

```shell
> curl 'http://localhost:8080/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:8080' --data-binary '{"query":"{\n  mockBug {\n    indices\n  }\n}"}' --compressed
{"data":{"mockBug":{"indices":[644690432274950468,644690432274950467,644690432274950466]}}}
```

**Comment by Ech0riginal** [comment]
Ah, much appreciated. I must not have seen that, apologies for wasting any time and thank you for the explanation.
