### ISSUE TITLE
Is there any way to add extensions when input errors?

### ISSUE THREAD

**Issue by yoshi9930** [async-graphql/async-graphql#627]
For example, if validate the following input, return value is error object.
But extensions is None.
Is there any way to add extensions when input errors?

```
    #[derive(InputObject)]
    struct Input {
        number: i32,
    }

    struct Query;

    #[Object]
    impl Query {
        async fn execute(&self, input: Input) -> bool {
            true
        }
    }
```
```
Err(
    [
        ServerError {
            message: "Invalid value for argument \"input.number\", expected type \"Int\"",
            locations: [
                Pos(1:10),
            ],
            path: [],
            extensions: None,
        },
    ],
)
```

**Comment by cptrodgers** [comment]
Yes. You can. This is the related issue. https://github.com/async-graphql/async-graphql/issues/385
Code example: https://github.com/async-graphql/async-graphql/issues/385#issuecomment-877548158

**Comment by yoshi9930** [comment]
@cptrodgers Thanks for the feedback.
