### ISSUE TITLE
Vague languages in TypeSystem

### ISSUE THREAD

**Issue by DataCorrupted** [async-graphql/async-graphql#63]
This issue is used to track vague languages when translating TypeSystem in Async-graphql Book.

**Comment by DataCorrupted** [comment]
### ["用`Schema::data`函数附加一个全局类型的数据"](https://async-graphql.github.io/async-graphql/zh-CN/define_complex_object.html) 

1. `Schema::data` or `ContextBase::data`?
2. "全局类型的数据" 如何理解?  如何和样例中给出的`ctx.data::<DbPool>().take()` 协调?

**Comment by sunli829** [comment]
"用Schema::data函数附加一个全局类型的数据"

1.  应该是SchemaBuilder::data和Context::data函数。
2. SchemaBuilder::data设置schema data, Context::data设置context data，是否可以这样翻译？

"并且你还能扩展标准的错误输出"
1. 我认为合适。
2. 错误信息吧。

"InputObject"

应该是无空格版本。

---------------------

抱歉，中文文档写得很仓促，有很多疏漏。😁

**Comment by DataCorrupted** [comment]
Thx, 我会稍作修改
