### ISSUE TITLE
Support `tracing::instrument(err)` on functions returning `async_graphql::Result`

### ISSUE THREAD

**Issue by stoically** [async-graphql/async-graphql#632]
Currently when trying to add `err` tracing on functions that return an `async_graphql::Result` like so

```rust
#[tracing::instrument(err)]
async fn model(&self, ctx: &Context<'_>, id: Uuid) -> Result<bool> {
    Ok(true)
}
```

it'll fail to compile because of

```
error[E0277]: `async_graphql::Error` doesn't implement `std::fmt::Display`
```

Trying to `impl Display for Error` conflicts with the existing `impl<T: Display> From<T> for Error`, so not sure if this can be solved at all. Repro: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=64f7bec41e3a9eb9f085bb5720dd2228

```
  = note: conflicting implementation in crate `core`:
          - impl<T> From<T> for T;
```

**Comment by stoically** [comment]
It seems `anyhow` implements [`AsRef<dyn Error + 'static> for Error`](https://docs.rs/anyhow/1.0.44/anyhow/struct.Error.html#impl-AsRef%3Cdyn%20Error%20+%20%27static%3E) instead of `impl<T: Display> From<T> for Error` which works around this conflict.

In the future it might also be solvable by using [`negative_impls`](https://doc.rust-lang.org/beta/unstable-book/language-features/negative-impls.html).

**Comment by sunli829** [comment]
Maybe you can use the `tracing` extension to do this.😁

https://docs.rs/async-graphql/2.9.15/async_graphql/extensions/struct.Tracing.html

Error can't implement `Display`, this is more troublesome. 😂

**Comment by johannescpk** [comment]
Oh, `tracing` extension is a thing :sweat_smile: Have to look into it, thanks for the pointer!

**Comment by stoically** [comment]
Oh, `tracing` extension is a thing :sweat_smile: Have to look into it, thanks for the pointer!

**Comment by sunli829** [comment]
I will close this issue, if you have other questions, please feel free to open it.

**Comment by stoically** [comment]
@sunli829 Thanks.

Just a hint: issues can only get reopened by issue authors if they close it themselves, otherwise it needs to be reopened by owners/members/collaborators.

**Comment by sunli829** [comment]
> @sunli829 Thanks.
> 
> Just a hint: issues can only get reopened by issue authors if they close it themselves, otherwise it needs to be reopened by owners/members/collaborators.

Ah, thank you for telling me this. 😁

**Comment by frederikhors** [comment]
@stoically can you help me to use `tracing` extension? I have this issue: https://github.com/async-graphql/async-graphql/issues/1009
