### ISSUE TITLE
Please give me a suggestion? viz-async-graphql or async-graphql-viz

### ISSUE THREAD

**Issue by fundon** [async-graphql/async-graphql#634]
Hi, I'm the creator of https://github.com/viz-rs/viz.
I want to add async-graphql to the framework. So viz-async-graphql vs async-graphql-viz?

**Comment by sunli829** [comment]
Maybe `async-graphql-viz` would be better, because other integrations are also named in this way. 🙂

**Comment by fundon** [comment]
Ok, Thanks. Follow the you. 😄 `async-graphql-viz`

**Comment by fundon** [comment]
@sunli829 I bumped the crate https://github.com/viz-rs/async-graphql-viz.
But I dont want use multer for parsing Multipart. 
There is already another [https://github.com/viz-rs/form-data](parser) inside viz. 
There Can you set it as an optional switch?

**Comment by sunli829** [comment]
`Async-graphql` must use `multer` to parse multipart.

**Comment by fundon** [comment]
It can be set as the default option, but a disable switch is provided.

```toml
[features]
default = ["multer"]

[dependencies]
multer = { optional = true }
```

**Comment by sunli829** [comment]
I don't think it is necessary to do so.

**Comment by fundon** [comment]
Sometimes we need to control the size, and giving an option allows the user to have more granularity. There is already a function for this within viz, which I feel is quite repetitive.

**Comment by fundon** [comment]
I hacked it https://github.com/viz-rs/async-graphql-viz/blob/main/src/extract.rs#L106.
Please set it to optional. Thanks.

**Comment by sunli829** [comment]
> I hacked it https://github.com/viz-rs/async-graphql-viz/blob/main/src/extract.rs#L106.
> Please set it to optional. Thanks.

I don't think this is very good, and `receive_batch_multipart` may change. 😂

**Comment by fundon** [comment]
我是想，如果能够提供一个可选项，可以自定义 multipart，一方面我可继续使用内部的 multipart 组件，不管在体积还是维护上都会方便。

当然也确实会遇到 `receive_batch_multipart` 跟上游 `async-graphql` 行为脱钩、滞后的问题，我这边自行维护，及时跟进也可以。

需要 PR？
