### ISSUE TITLE
Add support for graphql-ws pings

### ISSUE THREAD

**Issue by jamesbirtles** [async-graphql/async-graphql#635]
## Description of the feature

The graphql-ws protocol defines [ping/pong messages](https://github.com/enisdenjo/graphql-ws/blob/43da515de8e42c30f045cb02a1bc979f2c6b1aa9/PROTOCOL.md#ping) that can be sent to and from either side. Currently trying to send a ping from the client will cause the connection to close as the server doesn't expect a ping message. It would be useful to support at least a client initiated ping, responding with pong, as currently my sockets close after about a minute of inactivity.

## Code example (if possible)

Enabling pinging on the client side with graphql-ws:
```js
import { createClient } from 'graphql-ws';

createClient({
  url: 'ws://localhost:8080',
  keepAlive: 30_000, // ping server every 30 seconds
});
```

**Comment by sunli829** [comment]
I will support it when I finish the work at hand.

**Comment by sunli829** [comment]
I added this to the `master` branch, can you help test it? 🙂 @jamesbirtles

**Comment by jamesbirtles** [comment]
Awesome, I'll give it a try

**Comment by jamesbirtles** [comment]
Hm, so I see it sending the pong back now, but for whatever reason the client is closing the connection when it receives the pong.

**Comment by jamesbirtles** [comment]
This is the pong message
```json
{"type":"pong","payload":null}
```

Looking through the graphql-ws source, it looks like it doesn't like the payload being null.

It validates the message:
https://github.com/enisdenjo/graphql-ws/blob/43da515de8e42c30f045cb02a1bc979f2c6b1aa9/src/common.ts#L288-L290

Which validates that the payload is either undefined, or an object
https://github.com/enisdenjo/graphql-ws/blob/43da515de8e42c30f045cb02a1bc979f2c6b1aa9/src/common.ts#L220-L226

Where isObject specifically checks its not null
https://github.com/enisdenjo/graphql-ws/blob/43da515de8e42c30f045cb02a1bc979f2c6b1aa9/src/utils.ts#L12-L14

**Comment by sunli829** [comment]
Thank you very much, I have changed it. 🙂

**Comment by jamesbirtles** [comment]
That's working now, thanks! :+1:

**Comment by onichandame** [comment]
@sunli829 Mind sharing how to setup customized pings? I have searched in the docs and examples but nothing alike is found.
