### ISSUE TITLE
Relay Persisted Queries

### ISSUE THREAD

**Issue by maraisr** [async-graphql/async-graphql#637]
## Description of the feature

With the new Relay Rust compiler — it'll post queries during compile time. Would be great to offer an endpoint here to receive those FormData and persist to a backplane of your choosing.

## Code example (if possible)

https://github.com/facebook/relay/blob/b25725dd51e4cca8693dc018b7eaf25e81846441/compiler/crates/persist-query/src/lib.rs#L39

**Comment by Miaxos** [comment]
Hello,

It seems a lot like the Apollo Persisted Queries: https://github.com/async-graphql/async-graphql/blob/master/src/extensions/apollo_persisted_queries.rs

I think we could create a similar extension to manage this relay feature.
I will have some time this week to look into it.

**Comment by sunli829** [comment]
> Hello,
> 
> It seems a lot like the Apollo Persisted Queries: https://github.com/async-graphql/async-graphql/blob/master/src/extensions/apollo_persisted_queries.rs
> 
> I think we could create a similar extension to manage this relay feature.
> I will have some time this week to look into it.

Thank you! 🙂

**Comment by maraisr** [comment]
Guess just pointing out, these queries are only posted once during their generation. So actually less like Apollo, in that it's not a cache. These queries need to persist somewhere cross runs.

May I suggest opening up an api to connect up Redis or alike?

**Comment by Miaxos** [comment]
>Guess just pointing out, these queries are only posted once during their generation. So actually less like Apollo, in that it's not a cache. These queries need to persist somewhere cross runs.

From my understanding, two modes are possible, either posted within their generation, or with the run time push. https://relay.dev/docs/guides/persisted-queries/

Not sure how the runtime mode in relay is working, so I'll just implement the first one right now.

>May I suggest opening up an api to connect up Redis or alike?

Yes ofc! It should be possible to do it inside an extension easily and not inside the `async-graphql` engine.

**Comment by maraisr** [comment]
> From my understanding, two modes are possible, either posted within their generation, or with the run time push. 

Ahhh that's missing it. With relay there is the existing javascript based compiler, that is documented in those docs. I was specifically speaking to the new rust based compiler, which isnt documented. 

But in anycase, when you ask the compiler to persist, it **WILL NOT** produce any query text — so there will be no query text to support the "apollo pattern". 

Relay is strictly generating the queries during build time — and persisting those then. At runtime, it ONLY has access to the id. No operation text. Both the old rust compiler, and the new one had this behavior.

Notice;

![image](https://user-images.githubusercontent.com/599459/134080662-6e8240d8-859d-4a03-9c14-2546f22c2188.png)
> https://relay.dev/docs/guides/persisted-queries/

The only difference between the javascript based compiler and the rust compiler is, the javascript one produced a json map file, from id to text, whereas the new one is 100% FormData post based (hence the asking of this feature).

**Comment by Miaxos** [comment]
Ah okay, I understand, you want an endpoint to store these persisted queries inside a DB.

>The only difference between the javascript based compiler and the rust compiler is, the javascript one produced a json map file, from id to text, whereas the new one is 100% FormData post based (hence the asking of this feature).

You are right, I didn't understand you. You want the endpoint to receive the compiled queries, but the `async-graphql` engine can't really do anything about it: It's a graphql engine, if you want an endpoint to manage it, it should be on the http layer part on top of async-graphql, like tide / warp.

What we could create is a crate for each http framework, to create a route to integrate it easily but it seems it doesn't belong to the `async-graphql`.

But even with this endpoint, you would need an extension like the one I proposed to manage the server-part workflow for the persisted queries for relay when a relay client ask to use a persisted query.

**Comment by maraisr** [comment]
ah yeah even better, that way the orchestration about "where to store" is 100% up to the consumer. 

Just there needs to be a method exposed from `async-graphql` to "get" the query text when an id comes in on the wire, as Relay will **never** send the query text. You could even be smart and _pre-parse_ to ast at server start time perhaps. Or JiT parse, and in-memory cache.

**Comment by maraisr** [comment]
Any progress here further?

**Comment by Miaxos** [comment]
Completely forgotten, I took a break from open-source, I'll look into it soon I'll have the opportunity to resume.

There was a draft PR from here available: https://github.com/async-graphql/async-graphql/pull/641
