### ISSUE TITLE
Shouldn't DataLoader::load_one/load_many's return type match that of the loader?

### ISSUE THREAD

**Issue by edude03** [async-graphql/async-graphql#638]
A minor "rough edge" I find when using async-graphql is that load_one/load_many always return `Result<Option<T::Value>>` which is slightly annoying when T is guaranteed to be returned by the loader. 

For example if you look at the example in the data loader here https://github.com/async-graphql/async-graphql/blob/master/src/dataloader/mod.rs#L15-L33

it shows that the Loader will always return a string, and yet, you still have to unwrap in to get to the string. Seems like we could say the return type of `Dataloader<T>` is `Result<T::Value, T::Error>` and move the `Option` into `T::Value` optionally.

**Comment by Miaxos** [comment]
> which is slightly annoying when T is guaranteed to be returned by the loader.
It never happens to me 😭 !

I think you are right but you can easily `unwrap` it as you said and it's a breaking change for the dataloader feature to change the function's signature 😕

**Comment by sunli829** [comment]
> which is slightly annoying when T is guaranteed to be returned by the loader.
Usually this is not possible. 😁

If I make the return value of `load_many` match its loader, the returned `HashMap` contains all the keys, which is more troublesome.
