### ISSUE TITLE
Enhancement From impl for async_graphql::Error 

### ISSUE THREAD

**Issue by Qinka** [async-graphql/async-graphql#652]
## Description of the feature

I think the From impl for async_graphql should be changed. 

If  I want to use  `?`  operator  for my own error which has it own From impl to process the Error defined in other crates, there is no problems. But if I want to use ErrorExtensions, I need to call `extend()` manually which means I can not use the `?` operator.

## Code example (if possible)

```rust
impl<T: Display + ErrorExtensions> From<T> for Error {
    fn from(e: T) -> Self {
        e.extend()
    }
}
```

```rust
impl<T: Display + !ErrorExtension> From<T> for Error {
    fn from(e: T) -> Self {
        Self {
            message: e.to_string(),
            extensions: None,
        }
    }
}
```

Or just use feature to disable the default impl if needs

**Comment by sunli829** [comment]
Rust currently does not support generic specialization, this should not be possible.🙁
