### ISSUE TITLE
Add test code for introspection.

### ISSUE THREAD

**Issue by sunli829** [async-graphql/async-graphql#66]

**Comment by krevativ** [comment]
Can you elaborate more on which parts should be tested?

**Comment by sunli829** [comment]
Sorry, I did not describe clearly.
GraphQL allows querying the definition of Schema, called introspection. Here is a description of the introspection. http://spec.graphql.org/June2018/#sec-Introspection
Now need to write some test code, define Schema with `async-graphql`, and then query it to see whether the correct output. 😁

**Comment by sunli829** [comment]
I'll write a boilerplate code today, it shows how to do this test.

**Comment by phated** [comment]
More detail also exists at https://github.com/graphql/graphql-spec#introspection, include a link to the introspection tests that the spec team use.

**Comment by sunli829** [comment]
@krevativ  I added a boilerplate test code. 😁

**Comment by krevativ** [comment]
Seems to be straight forward. Now I just need to understand all possible states :sweat_smile: But I'm new to GraphQL and it's a good way to learn more about introspection. Ok I do it and try to stay  close to the spec.

@sunli829 thanks for the boilerplate!

**Comment by krevativ** [comment]
Ok I've looked more deeply into the spec. So far, these are the tests I want to write:

```
pub async fn test_introspection_simple_object() {}
pub async fn test_introspection_object() {}
pub async fn test_introspection_input_object() {}
pub async fn test_introspection_documentation() {}
pub async fn test_introspection_depraction() {}
pub async fn test_introspection_typename() {}
pub async fn test_introspection_schema() {}
pub async fn test_introspection_enum() {}
pub async fn test_introspection_interfaces() {}
pub async fn test_introspection_union() {}
pub async fn test_introspection_mutation() {}
```

What do you think?

I've also some questions:

1. What about the fields `interfaces`, `possibleTypes`, `enumValues`? Do they suppose to work? Because they don't or I do something wrong. (I think also the `inputFields`, but I haven't  tested it yet). 

2. What about the `__schema` field? It is a part of introspection spec. Should it be tested too?

3. I think subscriptions should also be tested. But I don't know how? :)

**Comment by sunli829** [comment]
> 1. What about the fields interfaces, possibleTypes, enumValues? Do they suppose to work? Because they don't or I do something wrong. (I think also the inputFields, but I haven't tested it yet).

Yes, these need to be tested. For example, the specification defines that `interfaces` must return null, and` async-graphql` returns `[]`, `" "`, which is not correct.

> 2. What about the __schema field? It is a part of introspection spec. Should it be tested too?

I hope this can be tested.

> 3. I think subscriptions should also be tested. But I don't know how? :)

For introspection, there is no difference between `query`, `mutation`, and `subscription`.

-----------------

Thanks again. 😁
