### ISSUE TITLE
How to make Logger extension to utilize Debug implementation for my errors instead of Display?

### ISSUE THREAD

**Issue by gyzerok** [async-graphql/async-graphql#671]
Hello!

Recently I've started using `async-graphql` and it feels really great so far. Thank you for working on it!

When I use logger extension in my logs I see strings which come from `Display` trait implementation for my errors. From my perspective `Display` represents what consumers/users should see and `Debug` represents what developers should see when they look at the error.

There are cases where I want to hide some details from users/consumers and just output "unexpected error", but I would like to have full details in the logs for debugging purposes.

How can I achieve that?

**Comment by sunli829** [comment]
I believe I have solved this problem, here are some tests.

https://github.com/async-graphql/async-graphql/blob/e898998311a32ca2b55aef9ef81b9ceaaf58f93d/tests/error_ext.rs#L81

Hope to get your feedback.😁 @gyzerok

**Comment by gyzerok** [comment]
@sunli829 do I understand correctly that your solution is to pass debug message alongside regular message?

It will probably solve my problem, that's true. Otherwise I believe I don't have much experience in Rust to review.

Personally I would try to go for a solution which delays converting errors to `ServerError` until very last step. Basically do it at `schema.execute(request).await.into()`.

Now I started wondering if configuring schema with my own type of error would be a possible solution. Imagine something like the following. Bare with me, I do not know enough Rust to write actual code, so it's more like a pseudocode 😅 

```rust
impl From<T: Display> for ServerError {
    fn from(e: T) -> ServerError {
        format!("{}", e)
    }
}

pub trait MyCustomError: fmt::Debug + fmt::Display {}

// Not sure how to write it here.
// The idea is somehow force all the resolvers to resolve to MyCustomError.
pub type MySchema = Schema<Query<MyCustomError>, Mutation<MyCustomError>, Subscription<MyCustomError>>;
```

And then make it so that the extension is also parametrized with the error type. So in the end I can get my own errors inside extensions. This way I can define multiple arbitrary behaviors on my own trait and then do whatever I want.

With your solution I would be able only to get the debug string. Which does solve my problem while being not generic to support any other use cases.

Like what if I want to log different errors from different resolvers with various rates (not 100%). Some errors are more important than others, and those are 100% logged. But some are very frequent and would quickly overwhelm log database. And it's not such an imaginary case. In my company we are working with a lot of traffic, so we have to deal with this :)

With my suggestion you could do something like this:
```rust
pub trait MyCustomError: fmt::Debug + fmt::Display {
    pub fn log_rate(&self) -> u8 { 100 };
}

struct MyActualError {
  AuthError,
  ValidationError
}

impl MyCustomError for MyActualError {
  pub fn log_rate(&self) -> u8 {
    match self {
      MyActualError::AuthError => 100, // very important
      MyActualError::ValidationError => 10, // not that important
    }
  }
}

// now somewhere in my custom logger extension implementation
if random(0, 100) <= err.log_rate() { println("{:?}" err) }
```

**Comment by sunli829** [comment]
> pub type MySchema = Schema<Query<MyCustomError>, Mutation<MyCustomError>, Subscription<MyCustomError>>;

This is a breaking change, so I cannot use this solution.

> With your solution I would be able only to get the debug string. Which does solve my problem while being not generic to support any other use cases.

You are right, I thought of a better way, wait for my news. 🙂

**Comment by sunli829** [comment]
I'm done, now the only trouble is that you need to manually convert your error type to `Failure`, like the following:

```rust
let s = String::from_utf8(bytes).map_err(Failure)?;
```

Get concrete error from `ServerError`:

```rust
server_err.concrete_error::<FromUtf8Error>()
```

Here is the test:

https://github.com/async-graphql/async-graphql/blob/d62aca805269b40f2093042d7791188d24fe3074/tests/error_ext.rs#L80

**Because Rust does not support generic specialization, this `Failure` type is required.**

**Comment by gyzerok** [comment]
> This is a breaking change, so I cannot use this solution.

Is there any way to provide "default" behavior, so it won't be a breaking change? Like you can define default type parameters. You do it when you define your own `Result` in the library by providing your `Error` type as a default. Is there some black magic which can be used here to avoid breaking changes?

> I'm done, now the only trouble is that you need to manually convert your error type to `Failure`, like the following

You second iteration does address broader use-cases and is job well done! I understand that `Failure` seems unavoidable which makes for a less ergonomic API. And I am wondering if there is a hidden opportunity here to make one more iteration and twist the solution somehow else to provide more ergonomics? Maybe we can sit a bit more on it and think? Or there is literally no way around?

I have great time using your library so far and believe others feel the same. So in my opinion it's worth making extra effort to maintain that great feeling in terms of APIs.

**Comment by sunli829** [comment]
I improved again, and this time I think you should be satisfied. 🙂 @gyzerok 

https://github.com/async-graphql/async-graphql/blob/490cfec5f56f1d600b5ec8feeca0e04741fe94e9/tests/error_ext.rs#L183

**Comment by gyzerok** [comment]
Yeah, if I understand everything correctly it looks great now! Thank you a lot for all the iterations and being so responsive 👏 

May I suggest some subjective naming improvements?
1. Rename `Failure` to `ResolverError` so it's in like with `ServerError` and `Error`. I personally name errors as `Failure` just to avoid collision of my application errors with libs errors. But in the lib itself I think consistent naming should be made.
2. Rename `concrete_error` to `cause`. I think this way it the error conversion chain would be clear. Also personally I am not quite sure what "concrete" means here. Isn't `ServerError` concrete already? Feels a bit confusing.

Anyway I would be happy to try this out to see how it works in my app. Would you mind updating actix-web 4 branch after releasing this, so I can try it out?

**Comment by sunli829** [comment]
> Yeah, if I understand everything correctly it looks great now! Thank you a lot for all the iterations and being so responsive 👏
> 
> May I suggest some subjective naming alterations?
> 
> 1. Rename `Failure` to `ResolverError` so it's in like with `ServerError` and `Error`. I personally name errors as `Failure` just to avoid collision of my application errors with libs errors. But in the lib itself I think consistent naming should be made.
> 2. Rename `concrete_error` to `cause`. I think this way it the error conversion chain would be clear. Also personally I am not quite sure what "concrete" means here. Isn't `ServerError` concrete already? Feels a bit confusing.
> 
> Anyway I would be happy to try this out to see how it works in my app. Would you mind updating actix-web 4 branch after releasing this, so I can try it out?

Thank you for always helping to improve this feature, naming is very difficult for me. 🙂
BTW: Maybe you can try [poem](https://github.com/poem-web/poem).

**Comment by sunli829** [comment]
Released in `2.11.1`.

**Comment by gyzerok** [comment]
Thank you, gonna try it now 😄  And I actually found a case why the order of fields in the response do matter. The version before that fix breaks my tests. So your update is right on time!

> BTW: Maybe you can try poem.
Currently I am at my early stages of learning Rust. And most of the stuff I am doing is based on [Zero to Production book](https://www.zero2prod.com).

Author is using `actix-web` there so I am using it as well. However I've decided to diverge a bit and use GraphQL instead of writing REST. While working with your library simple simple and fun, I believe that enough of additional learning complexity for me now.

Perhaps once I feel confident with all the things I have now on my place I can give a try to `poem`. Thank you for suggestion!

**Comment by gyzerok** [comment]
Ok, I've tried the code and it looks like I misunderstood how it was supposed to work. My apologies, Rust is still new to me.

Here is an example code from my project:
```rust
#[derive(Default)]
pub struct UserQuery;

#[Object]
impl UserQuery {
    pub async fn viewer(
        &self,
        ctx: &async_graphql::Context<'_>,
    ) -> Result<UserObject, ResolverError> {
        Ok(viewer(ctx).await?)
    }
}

async fn viewer(ctx: &async_graphql::Context<'_>) -> Result<UserObject, Problem> {
    // some code to get viewer from context

    let user = UserRepo::get_user_by_id(pool, &viewer.id)
        .await
        .context("failed to get user from the repo")?
        .ok_or_else(|| Problem::UnexpectedError(anyhow!("user not found")))?;

    Ok(UserObject { user })
}
```

The following problems appeared:
1. It works the way it is written in a code sample. However if I inline code from `viewer` function into resolver it stops working.
2. Also I was expecting to define resolver type as `-> Result<UserObject, Problem>` and not as `-> Result<UserObject, ResolverError>`.

Nonetheless I think it is better already, since I don't have to repeat `tracting::error!()` everywhere. And I was able to implement my custom logger which does exactly what I wanted it to.

However at least for me as a Rust newbee it wasn't really clear why the things are not working.

Also now it looks like we have regular error (which is part of libraries `Result` type alias) and `ResolverError` (which is not). Those 2 can probably bring some confusion for others.

Given all this I am not sure what to suggest. Personally I would really love this feature to work great for everybody. So I would rather struggle without this feature myself then do disservice to the library. Maybe you have some ideas?

**Comment by gyzerok** [comment]
It seems also that `query` function which helps to create cursor connections is forced to return `async_graphql::Result`. So I am not sure how to use it with my custom error types.

**Comment by sunli829** [comment]
> It seems also that `query` function which helps to create cursor connections is forced to return `async_graphql::Result`. So I am not sure how to use it with my custom error types.

I changed the signature of the `query` function to allow the callback to use any type that implements `Into<Error>`.

**Comment by sunli829** [comment]
> Given all this I am not sure what to suggest. Personally I would really love this feature to work great for everybody. So I would rather struggle without this feature myself then do disservice to the library. Maybe you have some ideas?

At the moment I think this `ResolverError` is very useful, but maybe we should explain why `ResolverError` is necessary in the `book`. Would you like to do this for this project? 🙂

**Comment by sunli829** [comment]
I just think `ResolverError` is not a good name. 🙂

**Comment by Miaxos** [comment]
For referencee, I proposed 'ResolverError' first thinking of a previous implementation we did at work:

Errors are implemented by implementing a trait which will tell:

- Should we stop the whole query execution and return a 500, or something or Should we just return a None for the upper level resolver
- Describe the error message retured
- Describe the error message logged

The ResolverError was the error which return None for the upper optinal parent.

**Comment by sunli829** [comment]
The current implementation is more complicated, I decided to refactor in the `v3.0` to provide a simpler API. 🙂

**Comment by sunli829** [comment]
Since `Error` no longer implements `Display` (I just found out), there will be no more type conflicts, so I deleted `ResolverError`. @Miaxos @gyzerok 

https://github.com/async-graphql/async-graphql/blob/d33c9ce88bd7bc2f69332f9b415ffd139c84189d/tests/error_ext.rs#L80

It looks pretty good now!

**Comment by sunli829** [comment]
I can't design a more convenient API without generic specialization, so I can only keep `ResolverError`. 😒

**Comment by gyzerok** [comment]
I will definitely be interested to contribute to the package in some way. Maybe improving docs is a possible option.

Currently I am working on a project and trying to collect my thoughts around the library APIs and the ways things are not working that well for me. Will try to wrap all the experiences up and share, once I am ready. Hopefully we can take things forward from that point :)

**Comment by Miaxos** [comment]
>I can't design a more convenient API without generic specialization, so I can only keep ResolverError. 😒

Haha, I'm also looking forward to the specialization 😁!
I will try to take some time to look into what you did tonight, I have also some ideas to write for the v3!

**Comment by sunli829** [comment]
I added `Error::new_with_source` method in `v3`, so the `ResolverError` type is no longer needed.

**Comment by gyzerok** [comment]
Hello @sunli829!

I am a bit confused with `Error::new_with_source` and how I am supposed to use it. Does it mean that I need to wrap every error in every resolver with it, or is it possible to make this work generically somehow?
