### ISSUE TITLE
Directives - [GraphQL - October 2021]

### ISSUE THREAD

**Issue by Miaxos** [async-graphql/async-graphql#679]
## Description of the feature

There are some parts of the new spec which are directed to `Directives`, but before going with these changes we should work about custom directives on `async-graphql`.

There is actually no easy way to create a new directive with a custom behavior on your GraphQL server with `async-graphql`. Before implementing the 2021 Specifications, I think we should think on how we could implement a way to add custom directives to the schema.

## Thinking about custom directives

Directives can affect a lot of things, little list of what can be affected by a directive:

```
"QUERY"
"MUTATION"
"SUBSCRIPTION"
"FIELD"
"FRAGMENT_DEFINITION"
"FRAGMENT_SPREAD"
"INLINE_FRAGMENT"
"VARIABLE_DEFINITION"
"SCHEMA"
"SCALAR"
"OBJECT"
"FIELD_DEFINITION"
"ARGUMENT_DEFINITION"
"INTERFACE"
"UNION"
"ENUM"
"ENUM_VALUE"
"INPUT_OBJECT"
"INPUT_FIELD_DEFINITION"
```
A directive is only a function with possible side effects, so an asynchronous function.
I think we shouldn't implement a generic custom directive model but implement specified ones.
Depending on the type of the directives, we will be able to apply it differently.

We could have trait like  `DirectiveScalarResolver` which would allow the directive to be applied to a Scalar with a definition like:
```rust
#[directive(name = "acustomdirective")]
struct ACustomDirective {
  arg1: Option<String>,
};

impl DirectiveScalarResolver for ACustomDirective {
  async fn resolve<T: ScalarType>(&self, scalar: T) -> FieldResult<ScalarType> {
    // Logic code would be applied after the scalar has been resolved.
    // ...
  }
}
```

It would allow us to create custom directive with custom logic code at our schema creation. It's only an exemple of what could be done, it's not really easy to create a system like that as it would change many inner working of `async-graphql`.

## 2021 Specifications

Here I'll list the things the 2021 Spec changed:

### Documentation about custom directive

The spec add documentation about custom directives, we may should add documentation.

https://github.com/graphql/graphql-spec/commit/bce80208054cb1aaf7b9f9f513270ba413054da3

### Repeatable directives

Directives can now be repeated with a custom keyword.

https://github.com/graphql/graphql-spec/commit/be33a640a8d12eb177f7cce0c61a1fad770a3430

### Directives must be ordered for the schema

https://github.com/graphql/graphql-spec/pull/470/files

**Comment by sunli829** [comment]
I will open it again when I can see the directives in `GraphQL Playground`.

**Comment by sunli829** [comment]
Directive on fields have been implemented.

https://github.com/async-graphql/async-graphql/blob/ea25e4ae7c04334afe3fd17dbfaeda6522d5bb32/tests/directive.rs#L81
