### ISSUE TITLE
Tracking issue - [GraphQL - October 2021]

### ISSUE THREAD

**Issue by Miaxos** [async-graphql/async-graphql#682]
## Description of the feature

A new version of GraphQL has landed, with a whole brand of new features to implement, as mentioned in https://github.com/async-graphql/async-graphql/issues/675
To keep a good visibility, I created a tracking issues with all features needed to be fully compliant for the 2021 spec.

I may have missed some things to implement as it's a work I did based on the draft.

## References

[October 2021 spec](https://spec.graphql.org/October2021/)
[Blog post - Lee Byron](https://medium.com/@leeb/graphql-2021-868e07545b83)

## Tracking Features

- https://github.com/async-graphql/async-graphql/issues/677
- https://github.com/async-graphql/async-graphql/issues/678
- https://github.com/async-graphql/async-graphql/issues/679
- https://github.com/async-graphql/async-graphql/issues/680
- https://github.com/async-graphql/async-graphql/issues/681
- https://github.com/async-graphql/async-graphql/issues/685

**Comment by sunli829** [comment]
Lexical analysis does not seem to have changed, what am I missing?😁 @Miaxos

**Comment by Miaxos** [comment]
It was this commit: https://github.com/graphql/graphql-spec/commit/09cdaecf3a4d08c9c53092ce83b0dede40adcba6 I didn't have time to check if there was an impact on the parser side

**Comment by sunli829** [comment]
> It was this commit: [graphql/graphql-spec@09cdaec](https://github.com/graphql/graphql-spec/commit/09cdaecf3a4d08c9c53092ce83b0dede40adcba6) I didn't have time to check if there was an impact on the parser side

Thank you! 🙂
