### ISSUE TITLE
Tauri custom protocol integration support 

### ISSUE THREAD

**Issue by conanchen** [async-graphql/async-graphql#684]
## Description of the feature

1. follow the tauri custom-protocol example
https://github.com/tauri-apps/tauri/blob/next/examples/api/src-tauri/src/main.rs
```
    .register_uri_scheme_protocol("customprotocol", move |_app_handle, request| {
      if request.method() == "POST" {
        let request: HttpPost = serde_json::from_slice(request.body()).unwrap();
        return ResponseBuilder::new()
          .mimetype("application/json")
          .header("Access-Control-Allow-Origin", "*")
          .status(200)
          .body(serde_json::to_vec(&HttpReply {
            request,
            msg: "Hello from rust!".to_string(),
          })?);
      }
```
2. trying to update to support graphql query  
```
    .register_uri_scheme_protocol("graphql", move |_app_handle, request| {
      let request: GraphqlQuery = serde_json::from_slice(request.body()).unwrap();

      let res = graphql::gsample0(request.query);
      ResponseBuilder::new()
        .mimetype("application/json")
        .header("Access-Control-Allow-Origin", "*")
        .status(200)
        .body(serde_json::to_vec(&res)?)
    })


#[derive(Serialize, Deserialize)]
struct GraphqlQuery {
  query: String,
}

pub  fn gsample0(query:String)-> Response{
    let schema = Schema::new(Query, EmptyMutation, EmptySubscription);
    let res = schema.execute(query);
    block_on(res)
}

```
3. I could get graphql result with normal query e.g 
```
query {
  hello(name: "world") {
    message
  }
}
```
4. but failed to get graphql result with variables query e.g.
```
query($name:String){
 hello(name:$name){
 message
 }
}

variable:
{
"name": "world"
}
```

**Comment by Miaxos** [comment]
Hello @conanchen!

Sorry, I'm not sure to understand what `enhancement` you may want, can you explain it?

**Comment by conanchen** [comment]
maybe like Actix-web async-graphql-actix-web for tauri custom protocol.  basically I don't want to have embeded actix-web + async-graphql in tauri app, I want to have only async-graphql libray to support graphql request through tauri custom protocol .

**Comment by sunli829** [comment]
It looks like a variable is used in your query, but you didn't give the value of this variable.

You can refer to this:

https://github.com/async-graphql/async-graphql/blob/a250c21ef62f1af17425c533e1b6b3ddcb062db6/tests/variables.rs#L114
