### ISSUE TITLE
Best practices in role-based access

### ISSUE THREAD

**Issue by ToferC** [async-graphql/async-graphql#693]
First, thanks for the amazing work on this crate.

I'm wondering what the best way is to create role-based access on fields in async-graphql.

I'm looking to provide role-based access to certain fields so I can enable "open" access to the API in support of the Open Data focus in my organization, but also make sure that sensitive data is only available to authorized consumers. 

The `visible` graphql macro does a lot of what I'm looking for, but doesn't seem to accept values: `#[graphql(visible = "is_admin")]`. While it also limits introspection, hides the field and generates an error, it *does* return them when queried despite the error.

![image](https://user-images.githubusercontent.com/6226762/140365785-a41703cf-acdf-4298-b89b-3475dce541ff.png)

Guard provides the functionality to pass values: `AgeGuard(age = r#"21"#)`.

But Guard doesn't work because it returns an error to the query and makes it harder for the user to understand what queries are available to them.

It also seems like if I use `visible`, I can't also use `Guard`, so I can't make a field invisible and truly prevent access at the same time.

What I would love to see is the ability to use the macro like this: `#[graphql(visible = "is_authorized(AuthRole::Analyst")]` and then look in context to see if the user role is >= the access required. If the user shouldn't have access, they would see it *and* wouldn't be able to access that field.

This would be amazing because introspection and queries would be guided what the user should have access to.

Thanks in advance for any thoughts or guidance.

Link to my project (very much a work in progress): https://github.com/ToferC/health_rules_engine

Access to live MVP playground: https://health-rules-engine.herokuapp.com/playground

C

**Comment by Miaxos** [comment]
Hello!

>The visible graphql macro does a lot of what I'm looking for, but doesn't seem to accept values: #[graphql(visible = "is_admin")]

Yes you are right, it doesn't accept a value, but it allows functions.

If you want to create something based on Roles, what you could do is to create something like that:

```rust
enum Role {
  ANALYST,
  ADMIN,
}

fn check_admin<'ctx>(ctx: &'ctx Context<'_>) -> bool {
    ctx.data::<Role>()
        .map(|x| x.statut() == Role::ADMIN)
        .unwrap_or(false)
}

#[derive(Default)]
pub struct Query;

#[Object]
impl Query {
    #[graphql(visible = "check_admin")]
    async fn test<'ctx>(&self, ctx: &'ctx Context<'_>) -> FieldResult<Something> {
      // Your logic
    }
}


#[tokio::main(flavor = "multi_thread")]
async fn main() -> anyhow::Result<()> {
    let schema = Schema::build(Query::default(), EmptyMutation, EmptySubscription).finish();
    let graphql_post = warp::post()
        .and(warp::path("graphql"))
        .and(async_graphql_warp::graphql(schema))
        .and(warp::header::optional::<String>("Authorization")) // Your auth mecanism
        .and_then(
            |schema: (
                Schema<Query, EmptyMutation, EmptySubscription>,
                async_graphql::Request,
            ),
             auth_header: Option<String>| async move {
                let (schema, request) = schema;
                let role: Role = generate_role(auth_header); // Your authentification logic
                
                // Store the role inside the request
                let res = schema.execute(request.data(role)).await;

                Ok::<_, std::convert::Infallible>(async_graphql_warp::Response::from(res))
            },
        );

    let addr = std::net::SocketAddr::from(([0, 0, 0, 0], 8080));
    warp::serve(graphql_post).bind(addr).await;

    Ok(())
}
```

**Here is an example with just one role to understand the possible mechanism, it would be better to pass a structure such as an `AuthContext` with tokens such as [biscuit](https://github.com/CleverCloud/biscuit/).**

**Comment by ToferC** [comment]
Thanks @Miaxos. I've got that in place in my code (and just bundled different levels of access in different functions that access context). 

Do you know if being able to query non-`visible` fields is part of the intended functionality? It seems a bit counter-intuitive to me.

**Comment by Miaxos** [comment]
Yes sorry, I forgot to add the Guard when I wrote the answer.

**Comment by Miaxos** [comment]
The visible field is only for the introspection query, so yes you can query a non-visible field.

**Comment by ToferC** [comment]
Makes sense. Rust is generating an `Invalid guards` macro error without a lot of context when I add `#[graphql(visible = "check_admin", guard = "AssociatedGuardAdmin")]`. Is there a tweak to syntax needed? (Or just point me to the docs)...

**Comment by ToferC** [comment]
Figured it out. The correct syntax is:

```rust
#[graphql(visible = "check_admin", guard(AssociatedGuardAdmin())]
```

Thanks so much for your help, @Miaxos. Closing issue!

**Comment by Miaxos** [comment]
Ah yes sorry I didn't check when I wrote it! Nice :-)
