### ISSUE TITLE
Handle possible errors related to MergedObject at compile time

### ISSUE THREAD

**Issue by SadiinsoSnowfall** [async-graphql/async-graphql#694]
There is two kind of errors linked to `MergedObjects` which can compile but will cause a panic / unwanted behaviour at runtime.

#### Using an `EmptyMutation` in a `MergedObject` after another mutation
Example:
```rust
 #[derive(Default)]
pub struct Mutation;

#[Object]
impl Mutation {
    async fn test(&self) -> bool {
        true
    }
}

#[derive(MergedObject, Default)]
pub struct MutationRoot(EmptyMutation, EmptyMutation);  // is ok

#[derive(MergedObject, Default)]
pub struct MutationRoot(EmptyMutation, Mutation);  // is ok

#[derive(MergedObject, Default)]
pub struct MutationRoot(Mutation, EmptyMutation); // will panic at runtime

// using a schema built using a QueryRoot, mutation set to MutationRoot and subscription set to EmptySubscription
```

Using an `EmptyMutation` in a `MergedObject` at a later position compared to the mutation which will be executed during a request will result in a panic with the error `entered unreachable code` linked to this line [types/empty_mutation.rs](https://github.com/async-graphql/async-graphql/blob/master/src/types/empty_mutation.rs#L59); which executes the `unreachable!()` macro.

In this example, the server receive a query calling the `test` mutation.

#### Using multiple mutations with the same name in a `MergedObject`
Example:
```rust
pub mod mod1 {
    #[derive(Default)]
    pub struct Mutation;
}

pub mod mod2 {
    #[derive(Default)]
    pub struct Mutation;
}

#[derive(MergedObject, Default)]
pub struct MutationRoot(mod1::Mutation, mod2::Mutation);
```
If multiple mutation objects with the same name are attached to a `MergedObject`, only the first one will be resolved (in this example, the one from `mod1` although the program does compiles.

I think the `MergedObject` macros should prevent this example from compiling, to avoid weird behaviour at runtime.

**Comment by SadiinsoSnowfall** [comment]
It should be noted that while the second problem is documented, or at least mentioned in the book :
> Tip: Every #[Object] needs a unique name, even in a MergedObject, so make sure to give each object you're merging its own name.
I think it would be best to prevent code that has this problem from compiling.

**Comment by sunli829** [comment]
> It should be noted that while the second problem is documented, or at least mentioned in the book :
> 
> > Tip: Every #[Object] needs a unique name, even in a MergedObject, so make sure to give each object you're merging its own name.
> 
> I think it would be best to prevent code that has this problem from compiling.

There is no way to prevent this problem at compile time, maybe I don't know how to do it.

But I can find the conflicting names when creating the schema and panic.

**Comment by SadiinsoSnowfall** [comment]
Panicking when creating the schema might be better than not resolving the mutations in my opinion.
I'm not sure I understand how the MergedObject macro works, is it possible to extract the names of the modules passed to the macro during its execution?

Concerning the first problem, I think it would be better to remove une unreachable! macro and juste "do nothing" inside the EmptyMutation resolve code. Or check if `container::is_empty()` before attempting to resolve a container.

**Comment by sunli829** [comment]
Now if a GraphQL name conflict is detected when creating schema, it will cause panic.
