### ISSUE TITLE
How do I make queries/mutations authed by default?

### ISSUE THREAD

**Issue by gyzerok** [async-graphql/async-graphql#696]
Hello!

In my project I have almost all of my queries hidden behind authorization. Currently only one of them is not.

The way I authenticate users is as follows
```rust
#[Object]
impl UserQuery {
    pub async fn viewer(
        &self,
        ctx: &async_graphql::Context<'_>,
    ) -> Result<UserObject, ResolverError> {
        // we get the viewer, which is currently authed user or we fail
        let viewer = ctx.data_opt::<Viewer>().ok_or(Problem::Forbidden)?;

        // we do something
    }
}
```
In `async_graphql` things work so that by default all the queries/mutations are not secured by auth. The problem is - if you don't need `Viewer` object for any operations in the query it is very easy to forget to add the check.

And it seems that I can't do this in my `actix-web` handler, because then I will force all resolvers to be secured behind auth.

Is there any way to make it so that the default behavior would be reversed for my resolvers? So I would need to explicitly state which ones are open, rather than the opposite.

**Comment by sunli829** [comment]
I haven't thought of a good way yet. 😁

**Comment by gyzerok** [comment]
By looking at the extensions API I think I might be able to achieve what I want by writing custom extension which would then be able to autocheck queries and mutations based on the list of their names `let unauthed = ["health", "registerUser"]`.

I'll try the idea and will come back for help if needed :)

**Comment by wileybaba** [comment]
I'm also pretty keen on something like this. It would be super useful to be able to apply a blanket authentication requirement to a group of queries/mutations instead of having to authenticate with context data for every resolver.

**Comment by benwis** [comment]
I ended up setting up an authorization Guard that wraps any resolver and handles the user authentication checks for me. Not quite what you're looking for, but it's easy to check and reuse the auth code

**Comment by wileybaba** [comment]
> I ended up setting up an authorization Guard that wraps any resolver and handles the user authentication checks for me. Not quite what you're looking for, but it's easy to check and reuse the auth code

Would you be willing to provide a code sample? Curious how you went about implementing this.

**Comment by gyzerok** [comment]
Ah, no, this won't work. If I understand correctly the guard is very similar to the way I wrote in the original message.

**Comment by benwis** [comment]
It's definitely not exactly what you asked for, but I find it fairly easy to remember and maintain that a guard needs to be added to decorate the resolver.
For example, this is my user guard:
```rust
#[async_trait::async_trait]
impl Guard for UserGuard {
    async fn check(&self, ctx: &Context<'_>) -> Result<()> {
        let pool = get_pool_from_ctx(ctx);

        // Refresh tokens and Error out if tokens are not valid
        let access_claims = get_fresh_tokens_from_ctx(ctx).await?;

        //If a Role is provided and verified to override the user check, bypass the below validation
        if let Some(role) = &self.role {
            if Role::from_str(&access_claims.role)? == *role {
                return Ok(());
            }
        }

        //Get user from DB
        let user = db::get_user(
            &self.tenant_name,
            &self.id,
            &self.name.as_deref(),
            &self.email.as_deref(),
            &pool,
        )
        .await?;

        if user.id == access_claims.sub {
            Ok(())
        } else {
            Err(ServiceError::Unauthorized.into())
        }
    }
}
```

and then all resolvers that need to be authed get something like this
```rust
    #[graphql(guard = "UserGuard::new(Some(Role::SuperAdmin), &None, &tenant_name, &None, &None)")]
    async fn address(
        &self,
        ctx: &Context<'_>,
        tenant_name: String,
        address_id: Uuid,
    ) -> Option<Address> {
        // Get pool from ctx
        let pool = get_pool_from_ctx(ctx);
        tracing::info!(
            "Querying  address ID: {:#?} on tenant name: {}",
            address_id,
            tenant_name
        );
        db::get_address(&tenant_name, address_id, &pool).await.ok()
    }
```

It would be nice to be able to apply something to queries by default, but I think this is perfectly workable

**Comment by longfellowone** [comment]
Not sure I like using guards as IDE autocompletion is non existent. In most queries where I would have the guard, I would need access to the `Viewer` or `User` object anyway, so I would still have to write `ctx.data_opt::<User>()`

This is what I came up with. What do you think?

```rs
#[Object]
impl UserQueries {
    pub async fn me(&self, ctx: &Context<'_>) -> async_graphql::Result<User> {
        let user = User::from_ctx(ctx)?.and_has_role(Role::Admin)?;

        Ok(user.clone())
    }
}
```

```rs
#[derive(Debug, Clone)]
pub struct User {
    pub user_id: String,
    pub scopes: Vec<Role>,
}

#[Object]
impl User {
    async fn id(&self) -> String {
        self.user_id.to_string()
    }
}

#[derive(PartialEq, Debug, Clone)]
pub enum Role {
    Admin,
}

impl User {
    pub fn and_has_role(&self, scope: Role) -> Result<&Self> {
        if !self.scopes.contains(&scope) {
            return Err(Error::Forbidden);
        }
        Ok(self)
    }

    pub fn from_ctx<'a>(ctx: &'a Context) -> Result<&'a Self> {
        ctx.data_opt::<User>().ok_or(Error::Forbidden)
    }
}
```

**Comment by gyzerok** [comment]
I figured I would separate my backend layer from the GraphQL layer for looser coupling. So my auth logic just moved to my backend layer hence I don't have this problem anymore.

**Comment by umran** [comment]
issue with Next<B>: struct takes 0 generic arguments but 1 generic argument was supplied
expected 0 generic arguments
