### ISSUE TITLE
Automatically tree shake objects from schema only referenced in hidden queries

### ISSUE THREAD

**Issue by oeed** [async-graphql/async-graphql#698]
## Description of the feature
Say I have a mutation taking an input object `LoginInput` and returning an object `LoginResult`, and the only mutation that uses them is hidden via `is_admin`.

```rust
#[Object]
impl LoginMutation {
  #[graphql(visible = "is_admin")]
  async fn login(&self, ctx: &Context<'_>, input: LoginInput) -> LoginResult {
    // ...
  }
}
```

Currently, if `is_admin` returns false the mutation `login` will hide from the schema, but `LoginInput` and `LoginResult` will still be visible. They aren't referenced by anything else in the schema. I would like these to automatically be hidden too, rather than having to manually mark them as hidden. ☺️

**Comment by sunli829** [comment]
good idea! 👏🏻
