### ISSUE TITLE
s3 Uploads 

### ISSUE THREAD

**Issue by wileybaba** [async-graphql/async-graphql#702]
Can anyone provide a working example of uploading to s3 using async-graphql ? I don't need a streaming upload, just a simple one.  I'm running into the issue of not having `Copy` implemented on the `UploadValue` struct so its proving difficult to extract a Vec<u8> from upload.content to pass to s3.

Here is my upload function: 
```rust 
pub struct File {
    id: ID,
    pub filename: String,
    pub content: Vec<u8>,
    pub mimetype: Option<String>,
}


pub async fn upload_to_s3(file: File) -> Result<u16, Error> {
    dotenv().ok();
    let accesss_key = std::env::var("AWS_ACCESS_KEY")?;
    let secret_key = std::env::var("AWS_SECRET_KEY")?;

    let bucket_name = "some-s3-bucket";
    let region = "us-east-2".parse()?;
    let credentials = Credentials::new(
        Some(&accesss_key.to_owned()),
        Some(&secret_key.to_owned()),
        None,
        None,
        None,
    )?;
    let bucket = Bucket::new(bucket_name, region, credentials)?;
    let (_, code) = bucket
        .put_object_with_content_type(
            file.filename,
            &file.content,
            &file.mimetype.unwrap_or("".to_string()),
        )
        .await?;
    println!("{}", code);
    Ok(code)
}
```

and my upload mutation
```rust
async fn upload_thumbnail(
        &self,
        ctx: &Context<'_>,
        file: &Upload,
    ) -> Result<u16, Error> {
        let upload = file.clone().value(ctx).unwrap();
        let mut content = Vec::new();
        upload.into_read().read_to_end(&mut content).unwrap(); 
        let file_info = File {
            id: ID::from(uuid::Uuid::new_v4()),
            filename: upload.filename.clone(),
            content, 
            mimetype: upload.content_type,
        };
        Ok(upload_to_s3(file_info).await?)
    }
```

running into a "use of moved value: `upload.content_type`" compiler error.  What is the best way to get the upload content as a Vec<u8> to pass to s3? 

I'm a rust noob so please forgive me if I'm missing something simple, still wrapping my head around the ownership model.

**Comment by sunli829** [comment]
You can clone it directly.

Rust is hard to learn, but don't be discouraged.  🙂

```
let upload = file.clone().value(ctx).unwrap();
let mut content = Vec::new();
let filename = upload.filename.clone();
let mimetype = upload.content_type.clone();
upload.into_read().read_to_end(&mut content).unwrap(); //  Because you consumed `upload` here, you can no longer access it later.
let file_info = File {
      id: ID::from(uuid::Uuid::new_v4()),
      filename,
      content, 
      mimetype,
};
```

**Comment by wileybaba** [comment]
> Rust is hard to learn, but don't be discouraged. 🙂
> 
> ```
> let upload = file.clone().value(ctx).unwrap();
> let mut content = Vec::new();
> let filename = upload.filename.clone();
> let mimetype = upload.content_type.clone();
> 
> upload.into_read().read_to_end(&mut content).unwrap(); //  Because you consumed `upload` here, you can no longer access it below.
> let file_info = File {
>       id: ID::from(uuid::Uuid::new_v4()),
>       filename,
>       content, 
>       mimetype,
> };
> ```

Ahh, use upload to define the variables above first, then consume it to mutate the content.  Thank you @sunli829 !
