### ISSUE TITLE
Duplicate Object name

### ISSUE THREAD

**Issue by phungleson** [async-graphql/async-graphql#703]
## Description of the feature

When I merge multiple `Object`, using `MergedObject`, it seems that it won't register new `Object` if `Object` name exists.

It is probably better to throw some sort of compiling error (if possible) or run time error.

**Comment by sunli829** [comment]
Please use `v2.11.2`，if a GraphQL name conflict is detected when creating schema, it will cause panic.

**Comment by phungleson** [comment]
Hey thanks for quick response,

I updated to `v2.11.2` but I got a new error, maybe you know the recent changes better.

I was using `2.10.6` and I have code like this

```
let session = ctx.data::<Arc<Mutex<Session>>>()?;
session.lock()?...
```

It throws error at `lock()?`

```
`std::sync::MutexGuard<'_, Session>` cannot be sent between threads safely
```

**Comment by sunli829** [comment]
> Hey thanks for quick response,
> 
> I updated to `v2.11.2` but I got a new error, maybe you know the recent changes better.
> 
> I was using `2.10.6` and I have code like this
> 
> ```
> let session = ctx.data::<Arc<Mutex<Session>>>()?;
> session.lock()?...
> ```
> 
> It throws error at `lock()?`
> 
> ```
> `std::sync::MutexGuard<'_, Session>` cannot be sent between threads safely
> ```

Maybe you should switch to an asynchronous lock, such as `tokio::sync::Mutex`.

**Comment by phungleson** [comment]
Right thanks @sunli829 it works well. Do you know what might be the reason?

It seems like issue start to appear with `v2.11.1`

**Comment by phungleson** [comment]
Btw with the new name conflicting error, I have an issue where `Object` actually has the same name with a `Union`.

An object like this:

```
[#Object]
struct Tesla {
  motor: Motor;
}
```

And a `Interface` like this:

```
#[derive(Interface)]
pub enum Car {
  TESLA(object::Tesla)
}

#[derive(Interface)]
pub enum Tesla {
  TESLA(object::Tesla)
}
```

As I would like to support 2 resolvers like this

```
createTesla()
// which returns an actual Tesla
```

```
searchCar() {
  ... on Tesla {
    motor
  }
}
// which returns a Car
```

Not sure if it there is a better way to handle this usecase?

**Comment by sunli829** [comment]
Of course, this is supported.

**Comment by phungleson** [comment]
Hey, yeah thing is I have to register `Tesla (Interface)` and it throws error there.

I tried to use `Interface` only

```
createTesla() -> Tesla (Interface)
searchCar() -> Car (Interface)
```

But `createTesla` return object with all the `Car` fields to be `null`, only `Tesla (Interface)` fields are set. FYI I do a conversion from `Tesla (struct)` to `Tesla (Interface)` by using `try_into`, not sure if it causes any issues.

If I do something like this in `v2.11.1` then everything works as expected

```
createTesla() -> Tesla (struct)
searchCar() -> Car (Interface)
```

Then it works as expected.

**Comment by phungleson** [comment]
Thinking about this, for `Tesla (Interface)` I only specify its specific field, i.e. `motor`.

`#[graphql(field(name = "motor", type = "&Motor"))]`

Do I need to specify all the fields (including `Car`) for `Tesla (Interface)`, feel quite a bit redundant?

**Comment by phungleson** [comment]
I mean, ideally if the old scenario should still work, i.e. we should be able to have `Interface` and `struct` of the same name.

As they are just rust way of doing thing, from the consumer point of view, they should be the same thing, so ideally if they have the same name.

**Comment by sunli829** [comment]
Can you tell me why you need to define the `Tesla` object and interface at the same time? 🙂

```rust
#[derive(Interface)]
pub enum Tesla {
  TESLA(object::Tesla)
}
```

**Comment by phungleson** [comment]
Cool thanks @sunli829 

Yeah right so looks like I don't have to define `Tesla (Interface)`, I was under impression that it is necessary to register `motor` field.

In that case why do I need to specify any field in `Car (Interface)` at all if `async-graphql` knows what object and what field?

**Comment by sunli829** [comment]
The reason why `Interface` needs to specify all fields is to ensure that all objects that implement this interface must contain these fields, so this error can be found during the compilation phase.

**Comment by sunli829** [comment]
I don’t know for what purpose you want to define `Tesla` objects and interfaces at the same time. In fact, you can query the `Car` interface like this:

searchCar() -> Car (Interface)

```graphql
{
    searchCar {
        motor
        ... on Tesla {
          # here are the fields of Tesla
        }
    }
}
```

You don't need to define the `Tesla` interface.

**Comment by phungleson** [comment]
Yeah righto, not sure why I was under impression that I need that interface, everything seems to work fine without it, thanks as always! @sunli829
