### ISSUE TITLE
Panic on invalid number input, possible denial-of-service attack vector

### ISSUE THREAD

**Issue by obi1kenobi** [async-graphql/async-graphql#704]
## Expected Behavior
Invalid GraphQL number inputs return an `Err()` result value.

## Actual Behavior
Invalid GraphQL number inputs cause a panic, which can be abused to turn invalid input into a DoS attack.

## Steps to Reproduce the Problem

Call `parse_query()` with a GraphQL input with a number that is too large to be fit in an `f64`, and observe it panic.

Here's an example GraphQL input, courtesy of `cargo-fuzz`:
```
{r(a: [4e444])}
```

The above input causes a panic: `failed to parse number: Error("number out of range", line: 1, column: 5)` with the following stack trace:
```
[...]/async-graphql-parser-2.11.2/src/parse/mod.rs:153:31
stack backtrace:
   0: rust_begin_unwind
             at /rustc/936238a92b2f9d6e7afe7dda69b4afd903f96399/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/936238a92b2f9d6e7afe7dda69b4afd903f96399/library/core/src/panicking.rs:106:14
   2: core::result::unwrap_failed
             at /rustc/936238a92b2f9d6e7afe7dda69b4afd903f96399/library/core/src/result.rs:1613:5
   3: async_graphql_parser::parse::parse_number
   4: async_graphql_parser::parse::parse_value
   5: core::iter::adapters::map::map_try_fold::{{closure}}
   6: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
   7: async_graphql_parser::parse::parse_value
   8: async_graphql_parser::parse::parse_arguments::{{closure}}
   9: core::iter::adapters::map::map_try_fold::{{closure}}
  10: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
  11: async_graphql_parser::parse::parse_arguments
  12: async_graphql_parser::parse::utils::parse_if_rule
  13: async_graphql_parser::parse::executable::parse_field
  14: async_graphql_parser::parse::executable::parse_selection
  15: core::iter::adapters::map::map_try_fold::{{closure}}
  16: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
  17: async_graphql_parser::parse::executable::parse_selection_set
  18: async_graphql_parser::parse::executable::parse_operation_definition_item
  19: async_graphql_parser::parse::executable::parse_definition_item
  20: core::iter::adapters::map::map_try_fold::{{closure}}
  21: core::iter::adapters::filter::filter_try_fold::{{closure}}
  22: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
  23: core::iter::adapters::process_results
  24: async_graphql_parser::parse::executable::parse_definition_items
  25: async_graphql_parser::parse::executable::parse_query
  26: rust_fuzzer_test_input
  27: __rust_try
  28: LLVMFuzzerTestOneInput
  29: _ZN6fuzzer6Fuzzer15ExecuteCallbackEPKhm
  30: _ZN6fuzzer10RunOneTestEPNS_6FuzzerEPKcm
  31: _ZN6fuzzer12FuzzerDriverEPiPPPcPFiPKhmE
  32: main
  33: __libc_start_main
  34: _start
```

That seems to point to the `.expect()` call here: https://github.com/async-graphql/async-graphql/blob/master/parser/src/parse/mod.rs#L153

## Specifications

- Version: `2.11.2`, on Rust `1.58.0-nightly (936238a92 2021-11-11)` in a 2021 edition project
- Platform: Ubuntu 20.04.3 LTS running under WSL2 in Windows 10 x64

**Comment by sunli829** [comment]
Thank you for reporting this issue. 🙂

**Comment by obi1kenobi** [comment]
Thanks for looking into it, and for maintaining this awesome library!

**Comment by sunli829** [comment]
I don't know why this problem cannot be reproduced, but I now delete the `expect` call and return an error when the parsing fails.

**Comment by obi1kenobi** [comment]
> I don't know why this problem cannot be reproduced, but I now delete the `expect` call and return an error when the parsing fails.

Fascinating -- what happens on your end when you call `async_graphql_parser::parse_query` on the input I gave?

Here's a little program you can run to check:
```
use async_graphql_parser::parse_query;

fn main() {
    println!("{:#?}", parse_query("{r(a: [4e444])}"));
}
```

**Comment by obi1kenobi** [comment]
I'm seeing the same issue in both `2.10.3` and `2.11.2`.

**Comment by sunli829** [comment]
It has been fixed, thank you! 😁
