### ISSUE TITLE
failed to start async-graphql-actix-web server on tauri-apps

### ISSUE THREAD

**Issue by conanchen** [async-graphql/async-graphql#705]
## Expected Behavior
start server ok with tauri-apps

## Actual Behavior
start_gql_server GraphQL UI: http://localhost:8180
thread 'main' panicked at 'System is not running', /Users/conanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/system.rs:78:21
stack backtrace:
2021-11-14 11:47:40.228620 UTC       INFO actix_server::builder - Starting 4 workers
   0:        0x10e281a11 - std::backtrace_rs::backtrace::libunwind::trace::h590dfebec4e77697
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x10e281a11 - std::backtrace_rs::backtrace::trace_unsynchronized::h99fbb54ac12f3b33
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10e281a11 - std::sys_common::backtrace::_print_fmt::h98af9386233c17ac
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x10e281a11 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::had87307b6abc1c9a
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x10e2a473b - core::fmt::write::hf956bc155d959fe3
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/fmt/mod.rs:1150:17
   5:        0x10e27921a - std::io::Write::write_fmt::h8329f2ae528d83ac
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/io/mod.rs:1667:15
   6:        0x10e283835 - std::sys_common::backtrace::_print::h6e4389a954583108
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x10e283835 - std::sys_common::backtrace::print::h8e088905fb2c3553
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x10e283835 - std::panicking::default_hook::{{closure}}::ha89bc0c5c4e06dc0
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:210:50
   9:        0x10e283417 - std::panicking::default_hook::hf75121343f052de7
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:227:9
  10:        0x10e283f20 - std::panicking::rust_panic_with_hook::h86c7505050d2207f
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:624:17
  11:        0x10df8f507 - std::panicking::begin_panic::{{closure}}::hd54d9aa93fd3cc34
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:544:9
  12:        0x10df8f458 - std::sys_common::backtrace::__rust_end_short_backtrace::h77a1f0a3b9c75db7
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x10e2c4b5f - std::panicking::begin_panic::h89adfb531cb19e66
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:543:12
  14:        0x10d06210d - actix_rt::system::System::current::{{closure}}::h8145ace25d1463cb
                               at /Users/conanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/system.rs:78:21
  15:        0x10d062e07 - std::thread::local::LocalKey<T>::try_with::h3c9b7c80b300cfe0
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/local.rs:399:16
  16:        0x10d062a0d - std::thread::local::LocalKey<T>::with::hbce140026049d0c3
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/local.rs:375:9
  17:        0x10d06206b - actix_rt::system::System::current::h6b2963c493944454
                               at /Users/conanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/system.rs:76:9
  18:        0x10d054055 - actix_rt::arbiter::Arbiter::new::he5f312c30403654d
                               at /Users/conanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/arbiter.rs:108:19
  19:        0x10cf70548 - actix_server::worker::Worker::start::h7e64dea194cdaacc
                               at /Users/conanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-1.0.4/src/worker.rs:173:9
  20:        0x10cfb6190 - actix_server::builder::ServerBuilder::start_worker::h2ba379a40719446e
                               at /Users/conanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-1.0.4/src/builder.rs:304:9
  21:        0x10cfb5f57 - actix_server::builder::ServerBuilder::run::{{closure}}::h126d43c9bca4eb15
                               at /Users/conanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-1.0.4/src/builder.rs:268:34
  22:        0x10cff6460 - core::iter::adapters::map::map_fold::{{closure}}::h0ddeaa7d0acb1973
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/iter/adapters/map.rs:84:28
  23:        0x10cfb3b3b - core::iter::traits::iterator::Iterator::fold::h83475553f5f0153f
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/iter/traits/iterator.rs:2170:21
  24:        0x10cff04fd - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h566b1e48f511827e
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/iter/adapters/map.rs:124:9
  25:        0x10cff58ae - core::iter::traits::iterator::Iterator::for_each::h1d04a3eba5a5377f
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/iter/traits/iterator.rs:733:9
  26:        0x10cfd422b - <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend::he7b19cdeac50aefd
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/vec/spec_extend.rs:40:17
  27:        0x10cfccc68 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter::h5fdc23f242c67fb0
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/vec/spec_from_iter_nested.rs:56:9
  28:        0x10cfd427f - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h69e9476e035ce0ef
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/vec/spec_from_iter.rs:33:9
  29:        0x10cfd3291 - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::ha63d7845ea505bdd
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/vec/mod.rs:2486:9
  30:        0x10cff57af - core::iter::traits::iterator::Iterator::collect::he7ff9a296382a112
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/iter/traits/iterator.rs:1745:9
  31:        0x10cfb5a27 - actix_server::builder::ServerBuilder::run::h2e374cc23b2ea6b0
                               at /Users/conanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-1.0.4/src/builder.rs:266:27
  32:        0x10cfb57db - actix_server::builder::ServerBuilder::start::hf44134243c5460c2
                               at /Users/conanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-1.0.4/src/builder.rs:255:9
  33:        0x10c962e3d - actix_web::server::HttpServer<F,I,S,B>::run::h94ffcb1dcf541d66
                               at /Users/conanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-3.3.2/src/server.rs:636:9
  34:        0x10c941835 - actix_graphql::start_gql_server::{{closure}}::hb54253d1e415b3ed
                               at /Users/conanchen/github/moreadgroup/moread-dapp-ebmaster/src-tauri/actix-graphql/src/lib.rs:85:11
  35:        0x10cba8f7f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd928f55a99d72010
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
  36:        0x10ca7c5dd - ebmaster::main::{{closure}}::h584b30d6a45fb70e
                               at /Users/conanchen/github/moreadgroup/moread-dapp-ebmaster/src-tauri/src/main.rs:48:50
  37:        0x10cba255f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h09a5891215158a5c
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
  38:        0x10ca0834a - tokio::park::thread::CachedParkThread::block_on::{{closure}}::h719ec29aee360efb
                               at /Users/conanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/park/thread.rs:263:54
  39:        0x10ca541a3 - tokio::coop::with_budget::{{closure}}::h9502150bc0fed717
                               at /Users/conanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/coop.rs:106:9
  40:        0x10ca7b46b - std::thread::local::LocalKey<T>::try_with::he3396fc404d5a3ab
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/local.rs:399:16
  41:        0x10ca78c6c - std::thread::local::LocalKey<T>::with::h7c1b48c3b444c73f
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/local.rs:375:9
  42:        0x10ca0769c - tokio::coop::with_budget::h141d67c2991f9d80
                               at /Users/conanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/coop.rs:99:5
  43:        0x10ca0769c - tokio::coop::budget::hd56620baeb09d480
                               at /Users/conanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/coop.rs:76:5
  44:        0x10ca0769c - tokio::park::thread::CachedParkThread::block_on::h5ba5209359c891cd
                               at /Users/conanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/park/thread.rs:263:31
  45:        0x10c94341b - tokio::runtime::enter::Enter::block_on::h12265f3db44222b1
                               at /Users/conanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/enter.rs:151:13
  46:        0x10cb852b0 - tokio::runtime::thread_pool::ThreadPool::block_on::h93378cb71dcbb11f
                               at /Users/conanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/thread_pool/mod.rs:77:9
  47:        0x10ca23536 - tokio::runtime::Runtime::block_on::h8cc0e938f607857e
                               at /Users/conanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/mod.rs:463:43
  48:        0x10c9a6047 - tauri::async_runtime::block_on::h2ee91b0f28ccd33e
                               at /Users/conanchen/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-1.0.0-beta.8/src/async_runtime.rs:83:3
  49:        0x10c9648e0 - ebmaster::main::h25df236ddc18155b
                               at /Users/conanchen/github/moreadgroup/moread-dapp-ebmaster/src-tauri/src/main.rs:48:11
  50:        0x10c9b766e - core::ops::function::FnOnce::call_once::hbdec601f5183a410
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
  51:        0x10ca31851 - std::sys_common::backtrace::__rust_begin_short_backtrace::h41f3a209427cd7c2
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:125:18
  52:        0x10c933614 - std::rt::lang_start::{{closure}}::h163d1e460608415b
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:63:18
  53:        0x10e28444a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h69c4046776cff27f
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:259:13
  54:        0x10e28444a - std::panicking::try::do_call::hf29484cd182a8166
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  55:        0x10e28444a - std::panicking::try::h0dc079bc76330482
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  56:        0x10e28444a - std::panic::catch_unwind::hcdcc8b405dbc0e7c
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  57:        0x10e28444a - std::rt::lang_start_internal::{{closure}}::hc519fd4fe9bea07d
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:48
  58:        0x10e28444a - std::panicking::try::do_call::h47874b112ebb4df0
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  59:        0x10e28444a - std::panicking::try::h1bce813709a4c45c
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  60:        0x10e28444a - std::panic::catch_unwind::hfcbf753edbd8cf11
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  61:        0x10e28444a - std::rt::lang_start_internal::hf65df31c3ffe3b9a
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:20
  62:        0x10c9335de - std::rt::lang_start::h85f2b954532b22a7
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:62:5
  63:        0x10c967cc6 - <unknown>
                               at /Users/conanchen/github/moreadgroup/moread-dapp-ebmaster/src-tauri/src/main.rs:33:39

## Steps to Reproduce the Problem

1. src/main.rs
```
fn main() {
  let _ = tauri::async_runtime::block_on(async { actix_graphql::start_gql_server(8180).await });
}
```
2. src/actix_graphql.rs
```
pub async fn start_gql_server(port: u16) -> std::io::Result<()> {
  let schema: gql::schema::ActixSchema = build_schema().await;

  println!(
    "start_gql_server GraphQL UI: http://{}:{}",
    "localhost", //CFG.get("ADDRESS").unwrap(),
    port         // CFG.get("PORT").unwrap()
  );

  let _ = HttpServer::new(move || {
    let cors = Cors::default()
      .allow_any_origin()
      //.allowed_origin("https://www.rust-lang.org/")
      //.allowed_origin_fn(|origin, _req_head| {
      //    origin.as_bytes().ends_with(b".rust-lang.org")
      //})
      .allowed_methods(vec!["GET", "POST"])
      .allowed_headers(vec![http::header::AUTHORIZATION, http::header::ACCEPT])
      .allowed_header(http::header::CONTENT_TYPE)
      .max_age(3600);

    App::new()
      .wrap(cors)
      .data(schema.clone())
      .service(
        web::resource("v1" /*CFG.get("GQL_VER").unwrap()*/)
          .guard(guard::Post())
          .to(graphql),
      )
      .service(
        web::resource("v1i" /*CFG.get("GIQL_VER").unwrap()*/)
          .guard(guard::Get())
          .to(graphiql),
      )
  })
  .bind(format!("{}:{}", "localhost", port))?
  .run()
  .await;

  Ok(())
}
```
3.

## Specifications

- Version: 
```
async-graphql = { version = "2.10.4", features = ["chrono"] }
async-graphql-actix-web = "2.10.4"
```
- Platform: macos 
- Subsystem:

**Comment by sunli829** [comment]
This is not caused by `async-graphql`, it seems that you did not start `actix-runtime` correctly?
