### ISSUE TITLE
list validator can be bypassed

### ISSUE THREAD

**Issue by Grobycn** [async-graphql/async-graphql#706]
## Expected Behavior
list validator must be applied

## Actual Behavior
list validator can be bypassed sometime

## Steps to Reproduce the Problem

1. apply a list(Email) validator on a input value of type Vec<String>
2. send request with corresponding arg of value "not a email". (not ["not a email"])
3. validator is bypassed

## Specifications

- Version: 2.11.3 on rustc 1.56.0 (09c42c458 2021-10-18)
- Platform: wsl1 ubuntu 18.04 on windows 10 20H2

**Comment by sunli829** [comment]
Since the validators has been reworked in the `v3` version, I will close this issue. 😁
