### ISSUE TITLE
i64 gets corrupted when returned by a resolver

### ISSUE THREAD

**Issue by loxs** [async-graphql/async-graphql#709]
## Expected Behaviour
`823766058909761536` gets serialised to `823766058909761536` in the graphql reply

## Actual Behaviour
`823766058909761536` gets serialised to `823766058909761500`

## Steps to Reproduce the Problem

1. return a bigger i64 from some resolver (smaller ones get serialised properly)
2. it's wrong

## Specifications
```
├── async-graphql v2.11.3
│   ├── async-graphql-derive v2.11.3 (proc-macro)
│   │   ├── async-graphql-parser v2.11.3
│   │   │   ├── async-graphql-value v2.11.3
│   ├── async-graphql-parser v2.11.3 (*)
│   ├── async-graphql-value v2.11.3 (*)
├── async-graphql-warp v2.11.3
│   ├── async-graphql v2.11.3 (*)
```
- Version: 2.11.3
- Platform: stable-aarch64-apple-darwin (default)
- Subsystem: rustc 1.56.0 (09c42c458 2021-10-18)

**Comment by sunli829** [comment]
This is because JSON can only represent 53-bit integers, and you can use `StringNumber` to output i64 as a string.

**Comment by loxs** [comment]
Thanks, I guess this is good for closing then?

**Comment by sunli829** [comment]
Yes, please feel free to close it. 🙂
