### ISSUE TITLE
async-graphql v3 `graphql_subscription_upgrade_with_data` replacement.

### ISSUE THREAD

**Issue by BratSinot** [async-graphql/async-graphql#711]
Greetings!

`graphql_subscription_upgrade_with_data` used generic for websocket and I was able to use wrapper (https://github.com/async-graphql/async-graphql/pull/534#issuecomment-855689750). But now, `GraphQLWebSocket::new` doesn't use generic, and I can't use wrapper.

What should I do?

**Comment by sunli829** [comment]
Sorry, I forgot this, please upgrade to `3.0.3`, I also added `GraphQLWebsocket::new_with_pair`. 😁

**Comment by BratSinot** [comment]
Thanks!
