### ISSUE TITLE
v3: Empty Query and Mutation.

### ISSUE THREAD

**Issue by BratSinot** [async-graphql/async-graphql#712]
Greetings again!

Before `v3` I didn't have to declare Query or Mutation. But with v3 I got error:
```json
{
  "error": "Invalid schema Error:\nType MutationRoot must define one or more fields.\nType QueryRoot must define one or more fields."
}
```
```rust
// GraphQl schema definitions
#[derive(MergedObject, Default)]
pub struct QueryRoot();

#[derive(MergedObject, Default)]
pub struct MutationRoot();

#[derive(MergedSubscription, Default)]
pub struct SubscriptionRoot(FooSubscription);

<...>

pub fn build_schema() -> SchemaType {
    Schema::build(
        QueryRoot::default(),
        MutationRoot::default(),
        SubscriptionRoot::default(),
    )
    .extension(tracing_span::Tracing)
    .finish()
}
```

**Comment by sunli829** [comment]
This is correct, Query, Mutation and Subscription must all contain at least one field.

**Comment by BratSinot** [comment]
> This is correct, Query, Mutation and Subscription must contain at least one field.

But it worked in v2. For Mutation, I can use EmptyMutation, but for Query such trick doesn't work.
This is a limitation by design or by GQL protocol?

**Comment by sunli829** [comment]
Yes. 😁

> An Object type must define one or more fields.

https://spec.graphql.org/October2021/#sec-Objects.Type-Validation

**Comment by sunli829** [comment]
There is no field in MutationRoot, `Async-graphql` cannot find this error at compile time.

```
#[derive(MergedObject, Default)]
pub struct MutationRoot(EmptyMutation);
```

**Comment by BratSinot** [comment]
> Yes. 😁
> 
> > An Object type must define one or more fields.
> 
> https://spec.graphql.org/October2021/#sec-Objects.Type-Validation

Wait, but Subscription and Mutation are Objects too?

**Comment by sunli829** [comment]
> > Yes. 😁
> > > An Object type must define one or more fields.
> > 
> > 
> > https://spec.graphql.org/October2021/#sec-Objects.Type-Validation
> 
> Wait, but Subscription and Mutation are Object's too?

Yes, they are objects.
