### ISSUE TITLE
Usage of disable_introspection method.

### ISSUE THREAD

**Issue by arthurfiorette** [async-graphql/async-graphql#716]
I'm new to rust, but let's go to what matters:

How can i write something like that, if the `disable_introspection` function uses `(mut self)` parameter?

```rs
pub fn create_schema() -> GqlSchema {
  let schema = Schema::build(...);

  if my_condition {
    schema.disable_introspection();
  };

  schema.finish()
}
```

If the inner code is just `self.registry.disable_introspection = true`, could it be write as `schema.instrospection(true)` to enable some type of "external" configuration?

**Comment by sunli829** [comment]
Do it like this:

```rust
 let mut schema = Schema::build(...);

  if my_condition {
    schema = schema.disable_introspection();
  };

  schema.finish()
```

**Comment by arthurfiorette** [comment]
thanks!
