### ISSUE TITLE
Update Context from resolver

### ISSUE THREAD

**Issue by dbstratta** [async-graphql/async-graphql#717]
Hey!

## Description of the feature

I'd like to be able to modify the context data from a resolver. 

My motivation for this is that I have a `signIn` mutation and I would like to be able to ask for the user data in the response, even fields that require auth data in the context. Something like:

```graphql
mutation {
  signIn(email: "joe@example.com", password: "password") {
    viewer {
      # ... 
      fieldThatRequiresAuthDataInContext
      # ...
    }
  }
}
```

The problem is that the resolver of `fieldThatRequiresAuthDataInContext` checks the auth data from context to only allow users to see their own data. Example:

```rust
#[derive(SimpleObject)]
#[graphql(complex)]
pub struct User {
    pub id: i32,
    // ...
}

#[ComplexObject]
impl User {
    async fn fieldThatRequiresAuthDataInContext(&self, ctx: &Context<'_>) -> Result<i32> {
        let auth_data = ctx.data::<AuthData>()?;

        if auth_data.user_id != self.id {
            return Err(AuthenticationError);
        }

        // ...
    }
}
```

### Current solution

What I'm currently doing is asking for the auth-protected data in a separate query after the `signIn` mutation.

## Code example

The idea would be to set context data at resolve time:

```rust
pub struct Mutation;

#[Object]
impl Mutation {
    async fn sign_in(&self, ctx: &Context<'_>, email: String, password: String) -> Result<User> {
        let user = authenticate_user(email, password).await?;

        ctx.set_data(AuthData { user_id: user.id });

        Ok(user)
    }
}
```

What do you think?

I'm open for discussion :smile:

**Comment by sunli829** [comment]
You can do it like this:

```rust
let user = authenticate_user(email, password).await?;

let auth = ctx.data::<Mutex<Option<AuthData>>>()?;
*auth.lock().await = Some(AuthData { user_id: user.id });
```

**Comment by dbstratta** [comment]
I hadn't thought of that, but it makes sense! I'll do that. Thank you!
