### ISSUE TITLE
Merge async-graphql v3 changes into actix-web-v4 branch 

### ISSUE THREAD

**Issue by benwis** [async-graphql/async-graphql#718]
## Description of the feature
Congrats on the v3 release! I'd love to use the async-graphql v3 features with the actix web v4 beta.

Can we merge the changes in to that branch or create another branch based off of the v3 release?

**Comment by dbstratta** [comment]
The v3 already supports `actix-web` v4, I'm using both together.

**Comment by benwis** [comment]
Awesome, if this is already done, I'll close. Thanks @dbstratta
