### ISSUE TITLE
`Loader::Error` should not require `Clone`

### ISSUE THREAD

**Issue by Wopple** [async-graphql/async-graphql#722]
Lots of errors out there aren't `Clone`. In particular, `sqlx::Error` isn't. Whether they should be or not, the fact is `Clone` cannot be relied upon.

Wrapping in an `Arc` does work in some cases, but not all. It causes the `Loader` to work, but you can no longer own the error inside the `Arc`. Owning the error can be useful, for example: composing errors.

I propose the loaders not use channels for passing errors around and instead return errors up the stack in a `Result`.

**Comment by sunli829** [comment]
Since multiple requests need to reuse the results of the query, this `Error` must implement `Clone`. 😁

**Comment by Wopple** [comment]
I find that a little surprising. I would have expected a follow up request that ended in error to try again (and produce a new error if it fails again). Further, I would think that follow up requests are not very useful. If a GQL query encounters an error, the query cannot be satisfied and should be short circuited. As far as I know, the caching of a loader is specific to a GQL query. Can you explain the benefit of doing things the current way?

**Comment by Miaxos** [comment]
>I find that a little surprising. I would have expected a follow up request that ended in error to try again (and produce a new error if it fails again). Further, I would think that follow up requests are not very useful. If a GQL query encounters an error, the query cannot be satisfied and should be short circuited. As far as I know, the caching of a loader is specific to a GQL query. Can you explain the benefit of doing things the current way?

When there is fields errors, the query should not be short circuited, you may be able to use a partial response from Graphql. Here is how GraphQL errors should be managed according to the specification: https://spec.graphql.org/October2021/#sec-Handling-Field-Errors

**Comment by Wopple** [comment]
That's fair. In this case however we're trying to load a whole object at once since loaders are meant to optimize the n+1 queries scenario. If there's an error in the loader, it's an error loading the whole object, not a field within the object.
