### ISSUE TITLE
DataSource macro hides errors

### ISSUE THREAD

**Issue by phated** [async-graphql/async-graphql#73]
While using the `#[DataSource]` macro, any errors inside the implementation of the trait are marked on the trait itself (and in some weird cases, hoisted to line 1 of main).

I looked into the macro and found it is just adding `#[async_trait::async_trait]` so I used that directly and the errors are highlighted correctly in my code.

**Comment by sunli829** [comment]
Yes, it only adds # [async_trait::async_trait], I think if rust stable version supports async trait, we do not have to change the code. 😂

**Comment by phated** [comment]
@sunli829 maybe the error exists because the version async-graphql uses it 0.1.24, but the current version is 0.1.30

**Comment by phated** [comment]
Would you accept removing the macro and documenting that `async_trait` must be used with DataSource?

**Comment by sunli829** [comment]
I want to keep it for expansion, maybe one day we want to add something? 😂

**Comment by phated** [comment]
Ok, maybe we need to upgrade the dependency for now.

**Comment by sunli829** [comment]
> While using the `#[DataSource]` macro, any errors inside the implementation of the trait are marked on the trait itself (and in some weird cases, hoisted to line 1 of main).

Normally, the error message is not hidden. Can you give an example to reproduce the problem?

**Comment by phated** [comment]
If you use `#[DataSource]` and make a type error inside https://github.com/phated/twentyfive-stars/blob/master/server/src/data/card.rs#L38, you will see the error not display properly.

**Comment by sunli829** [comment]
Thanks, I will track this issue. 😁

**Comment by sunli829** [comment]
I still haven't figured out why this problem was caused, but I solved it in a way that seemed silly together. 😂
