### ISSUE TITLE
Error extensions

### ISSUE THREAD

**Issue by phungleson** [async-graphql/async-graphql#733]
Hi @sunli829,

Thanks a lot for implementing this! https://github.com/async-graphql/async-graphql/issues/671

Maybe I don't know how to handle this but basically I would like to achieve this:
* I want to add code to `error.extenstions`
* I also would like resolver to return `MyError` as I want to capture some types of errors (blanket using `From`) and do some special handling for them.

So I would like my resolver to look like this, but seems like the only way to add `error.extenstions` is to return `async_graphql::Error` instead? unless I create a separate method to return `MyError` and change my resolver to return `async_graphql::Error`?

```
#[Object]
impl TestMutation {
    async fn test(&self, ctx: &Context<'_>) -> Result<Test, MyError> {
```

**Comment by sunli829** [comment]
In `async-graphql v3`, you can use `graphql ::Error::new_with_source` to create `async-graphql::Error`, and then use `async-graphql::Error::source` or `async_graphql: :ServerError::source` gets the original error object.

Here is an example:

https://github.com/async-graphql/async-graphql/blob/f7b6e9820f68e1f4c70e730eae2143797a15f899/tests/error_ext.rs#L94

https://github.com/async-graphql/async-graphql/blob/f7b6e9820f68e1f4c70e730eae2143797a15f899/tests/error_ext.rs#L118

**Comment by phungleson** [comment]
Yeah I have been playing with source for a while but I got stuck when it comes to adding `error.extenstions`.

Basically I would like this to return `Result<i32, MyError>` but at the same time I would like to tell `async_graphql` to add `error.extenstions` based on `MyError`.

https://github.com/async-graphql/async-graphql/blob/f7b6e9820f68e1f4c70e730eae2143797a15f899/tests/error_ext.rs#L94

**Comment by sunli829** [comment]
No, it can only be `async_graphql::Error` after adding the extensions, so this function can only return `async_graphql::Result<T>` instead of `Result<T, MyError>`.

https://github.com/async-graphql/async-graphql/blob/f7b6e9820f68e1f4c70e730eae2143797a15f899/tests/error_ext.rs#L103

**Comment by phungleson** [comment]
Yeah I understand that by design it is not possible at the moment.

I will keep this alive for a while, maybe we/others can think of some solutions.

**Comment by sunli829** [comment]
Rust does not support generic specialization, which is the best I can do. 😁

**Comment by Arios16** [comment]
Why is

    impl<T: Display + Send + Sync + 'static> From<T> for async_graphql::Error

neccesary? If this generic impl didnt exist, what phungleson said would be possible by implementing 

    From<MyError> for async_graphql::Error

Note that this is already technically possible if `MyError` does not implement `Display + Send + Sync + 'static`, but its cumbersome to work with such an error type

**Comment by phungleson** [comment]
Someone mentioned about

```
impl<T: Display + Send + Sync + 'static> From<T> for async_graphql::Error
```

I think it is meant to be there so that `async_graphql` can convert any thing into `async_graphql::Error`. It is convenient but too general, leading to the need of specialization.

I have a shower thought this morning (haven't thought about it clearly), maybe `async_graphql` can consider putting it under a feature flag so that people can disable it when necessary?

**Comment by phungleson** [comment]
Generally speaking for better decoupling, maybe `async_graphql` can consider to leave resolver error handling to users, so that users can choose to use other crate specialised in error handling like `anyhow` or `thiserror` (am using `thiserror` btw) and user will need provide an `Into< async_graphql::Error>`.

**Comment by sunli829** [comment]
Yes, because most people don't need to get the original error object. 😁

**Comment by phungleson** [comment]
I am not sure, I just want to add `error.extenstions.code` uniformly.

For example if I get `MyError::Unauthorized`, I want `error.extenstions.code = UNAUTHORIZED`
For example if I get `MyError::NotFound`, I want `error.extenstions.code = NOT_FOUND`

Maybe `error.extensions` is a non-standard thing but well `error.extenstions.code` looks like probably a common way people work around standard, not sure if there are other common way to handle error code?

**Comment by sunli829** [comment]
Do it like this:

https://github.com/async-graphql/examples/blob/c0858747f6b8c39cb7b1a8d2bf6e15ba97299b0f/actix-web/error-extensions/src/main.rs#L25

**Comment by phungleson** [comment]
Thanks Sunli, yeah I am doing something like that.

I guess the difference between suggestion and current situation is very subtle:

With current situation, I have to litter my code with `map_err(|err| err.extend())`.

On the other hand without the blanket `From<T> for async_graphql::Error` I just need to do one `From<MyError> for async_graphql::Error` and let `?` do its thing.

It is not that it doesn't work, it is just a bit cumbersome when you have around 50 or so resolvers.

I guess we can keep this alive for a while to see if others have or don't have this issue. If no one runs into this, I am happy to close this, thanks!

**Comment by frederikhors** [comment]
> Thanks Sunli, yeah I am doing something like that.
> 
> I guess the difference between suggestion and current situation is very subtle:
> 
> With current situation, I have to litter my code with `map_err(|err| err.extend())`.
> 
> On the other hand without the blanket `From<T> for async_graphql::Error` I just need to do one `From<MyError> for async_graphql::Error` and let `?` do its thing.
> 
> It is not that it doesn't work, it is just a bit cumbersome when you have around 50 or so resolvers.
> 
> I guess we can keep this alive for a while to see if others have or don't have this issue. If no one runs into this, I am happy to close this, thanks!

I'm in the same situation @phungleson, did you find a way?

**Comment by phungleson** [comment]
Hey @frederikhors unfortunately I still have to do something like this `.map_err(|err| err.extend())`.

It would be nice if there is a feature flag.

**Comment by frederikhors** [comment]
> Hey @frederikhors unfortunately I still have to do something like this `.map_err(|err| err.extend())`.
> 
> It would be nice if there is a feature flag.

I'm trying to better understand how to do this CORRECTLY: https://github.com/async-graphql/async-graphql/discussions/1089.

**Comment by halldorrt** [comment]
> I guess the difference between suggestion and current situation is very subtle:
> 
> With current situation, I have to litter my code with `map_err(|err| err.extend())`.
> 
> On the other hand without the blanket `From<T> for async_graphql::Error` I just need to do one `From<MyError> for async_graphql::Error` and let `?` do its thing.

Same situation here, we are migrating from juniper so we already have quite a few resolvers. I would really prefer handling this in one place.

@sunli829 I just wanted to ask whether you would be willing to accept a PR that puts the blanket From implementation behind a default feature flag as @phungleson suggested?
Or, if you can think of another way to achieve this that you would prefer to a feature flag?

Also, thanks a lot for your work on async-graphql 🙂
