### ISSUE TITLE
SDL schema doesn't include InputObject when struct also have SimpleObject

### ISSUE THREAD

**Issue by EtienneProthon** [async-graphql/async-graphql#734]
## Expected Behavior
SDL schema should have the input object and the object if I derive it with `#[derive(SimpleObject, InputObject)]`
For the name of the struct you can do exactly the same as type-graphql for TypeScript. When you use 2 decorator on the struct it create MyStruct and MyStructInput and allow you to define the name of the input type if needed
```ts
@InputType('FHIRHospitalInput')
@ObjectType()
export class FHIROrganization {
  @Field(() => Boolean)
  active: boolean
}
```
Also i think 2 space indentation for sdl schema should be better.
I use async graphql to generate the sdl schema from my struct and send it to AppSync (that way my code is consitant with the structs i use in my lambdas)

## Actual Behavior
Only Object is created in SDL schema

## Steps to Reproduce the Problem

1. Create a struct with #[derive(SimpleObject, InputObject)]
2. Generate the sdl schema

## Specifications

- Version: 3.0
- Platform: Linux Mint 20.2 Cinnamon
- Subsystem: Linux Kernel 5.4.0-90-generic

**Comment by sunli829** [comment]
When you derive both `SimpleObject` and `InputObject` in a type, you must use the `input_name` attribute to specify the name of the InputObject.🙂

```
#[derive(SimpleObject, InputObject)]
#[graphql(input_name = "FHIROrganizationInput")
struct FHIROrganization {
}
```

**Comment by EtienneProthon** [comment]
Wow didn't saw that thank you very much !
