### ISSUE TITLE
Throw 'lifetimes do not match method in trait' when use CustomValidator trait

### ISSUE THREAD

**Issue by rieval** [async-graphql/async-graphql#736]
## Expected Behavior

No error throw here.

## Actual Behavior

![image](https://user-images.githubusercontent.com/22883406/144400306-85188749-25db-448f-bcfb-023f5a894ea1.png)

## Steps to Reproduce the Problem

[official docs](https://async-graphql.github.io/async-graphql/en/input_value_validators.html)

```rust
// main.rs
use async_graphql::*;

struct MyValidator {
    expect: i32,
}

impl MyValidator {
    pub fn new(n: i32) -> Self {
        MyValidator { expect: n }
    }
}

#[async_trait::async_trait]
impl CustomValidator<i32> for MyValidator {
    async fn check(&self, value: &i32) -> Result<(), String> {
        if *value == self.expect {
            Ok(())
        } else {
            Err(format!("expect 100, actual {}", value))
        }
    }
}

fn main() {
    println!("hello world.");
}
```

cargo.toml
```
[package]
name = "r"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "*"
async-graphql = "*"
```

## Specifications

- Version: 
  rustc: `1.56.0 (09c42c458 2021-10-18)`
  async-trait: `0.1.51`
  async-graphql: `3.0.10`
- Platform: Win10 21H1
- Subsystem: None

**Comment by sunli829** [comment]
I updated the book.

**Comment by rieval** [comment]
Work fine now, thank you.
