### ISSUE TITLE
Passing tonic grpc client through Context to resolvers

### ISSUE THREAD

**Issue by fulstaph** [async-graphql/async-graphql#738]
Hello! I've been trying to make a GRPC call inside the query resolver. To do this I need to pass [tonic](https://github.com/hyperium/tonic) generated client to `data(Data::new(...))`.
I tried to  
1) pass client itself (with and without `.clone()`
2) pass `Arc<Client>`
3) pass `tonic::transport::Channel` to `Context` to clone the channel and create the client in resolver
4) pass `Arc<tonic::transport::Channel>` to `Context`

yet all of these attempts failed :(

Every time I get this error in runtime:
```
Error { message: "Data `alloc::sync::Arc<tonic::transport::channel::Channel>` does not exist.
```

This is current grpc channel extraction code:

```rust
let conn = ctx
            .data::<Arc<UserChanConn>>()
            .expect("failed to extract user service conn")
            .deref();

let mut client = UsersServiceClient::new(conn.clone());
```

Function that creates `Schema<...>`
```rust
pub fn create_schema_with_context(
    auth_client_conn: Arc<AuthChanConn>,
    users_client_conn: Arc<UserChanConn>,
) -> Schema<Query, EmptyMutation, EmptySubscription> {
    Schema::build(Query, EmptyMutation, EmptySubscription)
        .data(Data::new(auth_client_conn.clone()))
        .data(Data::new(users_client_conn.clone()))
        .finish()
}
```

File `main.rs`
```rust
pub type AuthChanConn = Channel;
pub type UserChanConn = Channel;

...

    let auth_conn_chan = Channel::from_static(&"http://[::1]:4775")
        .connect()
        .await
        .expect("Can't create a channel");

    let users_conn_chan = Channel::from_static(&"http://[::1]:4772")
        .connect()
        .await
        .expect("Can't create a channel");

    let schema = routes::create_schema_with_context(
        Arc::new(auth_conn_chan.clone()),
        Arc::new(users_conn_chan.clone())
    );
```

I haven't published this code to GitHub yet, but I can if needed. 

# Specifications
Library versions:
```toml
[dependencies]
actix-web = { version = "^4.0.0-beta.13", default-features = false}
async-graphql-actix-web = "^3.0.7"
tonic = "0.6.1"
[dependencies.async-graphql]
features = ["chrono", "tracing", "dataloader"]
version = "3.0.11"
```
Rust version: `rustc 1.57.0-nightly`

# Helpful links
[Discussion of concurrent use of GRPC client](https://github.com/hyperium/tonic/issues/285)
 
**PS**: I'm pretty new to Rust so it might probably be a really dumb question, so sorry in advance 🙃 But I really can't google my way out of this one

**Comment by dbstratta** [comment]
You're wrapping the tonic client in `Data::new` when adding it to the context, but not when trying to get it.

Have you tried adding data to the context without `Data::new`? Something like:

```rust
Schema::build(Query, EmptyMutation, EmptySubscription)
        .data(auth_client_conn.clone())
        .data(users_client_conn.clone())
        .finish()
```

Or getting it with `Data`:

```rust
let conn = ctx
            .data::<Data<Arc<UserChanConn>>>()
            .expect("failed to extract user service conn")
            .deref();
```

**Comment by sunli829** [comment]
Don't use `actix_web::Data` to wrap your data, unless you also use the type `actix_web::Data<T>` when you get it.

```
 Schema::build(Query, EmptyMutation, EmptySubscription)
        .data(auth_client_conn.clone())
        .data(users_client_conn.clone())
        .finish()
```

**Comment by fulstaph** [comment]
@dbstratta @sunli829 thank you very much! Removing `actix_web::Data` helped 🙂 
Closing this issue.
