### ISSUE TITLE
How to add data to BatchRequest

### ISSUE THREAD

**Issue by phungleson** [async-graphql/async-graphql#739]
Hey @sunli829 

I am playing around with poem and I got `BatchRequest` from `GraphQLBatchRequest::from_request`.

I want to add `data` to all the requests, is there an easy way without pattern matching BatchRequest?

Thanks!

**Comment by sunli829** [comment]
I added some helper methods for `BatchRequest` on `master` branch. 🙂

- BatchRequest::iter
- BatchRequest::iter_mut
- BatchRequest::variables
- BatchRequest::data
- BatchRequest::disable_introspection
-

**Comment by phungleson** [comment]
Awesome @sunli829! You turned my spaghetti into a few lines of code!
