### ISSUE TITLE
Clarification on how to properly use DataLoader

### ISSUE THREAD

**Issue by SadiinsoSnowfall** [async-graphql/async-graphql#743]
I have a few question related to the use of dataloaders that I haven't found a complete answer to by browsing the documentation and github issues  :
* Should the DataLoader be created at the schema or request level ?
* When creating a DataLoader at the schema level, how is the cache managed ? 
* If there is a few data structs using the same ID type (ex: Snowflake-based IDs) is there a way to avoid creating one DataLoader per type ?
* If one DataLoader per type is needed, is there a way to avoid creating every DataLoader on each request / create them only when needed ?
* What is the performance difference between calling load_one multiple time (and joining the resulting futures) and calling load_many for a small number of keys ?

**Comment by sunli829** [comment]
> Should the DataLoader be created at the schema or request level ?

request level

> If there is a few data structs using the same ID type (ex: Snowflake-based IDs) is there a way to avoid creating one DataLoader per type ?

You need to define some newtypes to distinguish different IDs.

struct DogId(Id);
struct CatId(Id);

> If one DataLoader per type is needed, is there a way to avoid creating every DataLoader on each request / create them only when needed ?

Usually there is almost no cost to create a loader?

> What is the performance difference between calling load_one multiple time (and joining the resulting futures) and calling load_many for a small number of keys ?

In fact, `load_one` calls `load_many` internally. 🙂

**Comment by SadiinsoSnowfall** [comment]
Thank you for the answers 👍 

Regarding newtypes, do you think it would be possible to allow the loader trait to specialize on the Value type instead of / along side the Key type ?
eg:
```rust
// opaque type
struct Id;

#[derive(Debug, Clone)]
struct Dog {
    id: Id,
    name: String,
}

#[derive(Debug, Clone)]
struct Cat {
    id: Id,
    name: String,
    cat_stuff: String,
}

pub struct AnimalLoader;

impl Loader<Id, Dog> for AnimalLoader {
    fn load(&self, keys: &[Id]) -> Result<HashMap<Id, Dog>, Self::Error> {
      // ....
    }
}

// or `impl Loader<Dog> for AnimalLoader { ... }` with a `Self::Key` property

impl Loader<Id, Cat> for AnimalLoader {
    fn load(&self, keys: &[Id]) -> Result<HashMap<Id, Dog>, Self::Error> {
      // ....
    }
}
```

Wraping keys into newtypes can add some boilerplate, especially when using a few structs using the same key type.
This is even more apparent when dealing with Vec/slices of keys (because it's not possible to access a `Vec<Id>` as a `&[CatId]` slice without using `mem::transmute` afaik.

**Comment by Erik1000** [comment]
I have a question about this too. Is there some logic in the Dataloader which checks for the total size of items requested and splits them into multiple calls to the `Loader::load` implementation if they are above a specific size? I've just noticed some weird behaviour with multiple calls to the `Loader::load` trait implementation. Since I've done something quite cursed with the Dataloaders I just wanted to check if that's the case or if I have to investigate somewhere else.

If you're interested in the code, you can see it here https://github.com/suicidesquad1337/pctf/blob/7d524d14dea8c8beb5cad8bf7e6cacfac683da41/web/src/loaders/challenge_loaders.rs (but I dont think you want to, tho it's pretty incredible what can be done with sql).

**Comment by Erik1000** [comment]
Also another question:
>> Should the DataLoader be created at the schema or request level ?

> request level

So am I supposed to create a Dataloader for each request?  Like, for example, here in that part https://github.com/async-graphql/examples/blob/c8219078a4b7aa6d84d22e9b79f033088897be4b/rocket/starwars/src/main.rs#L21-L27 ? If so, how does the cache for work multiple requests?

**Comment by emwalker** [comment]
> If so, how does the cache work for multiple requests?

This data loader implementation is based on the Facebook example.  The Facebook design [is intended](https://github.com/graphql/dataloader#caching-per-request) to cache fetches within a single GraphQL request, but it's not intended to live longer than a single incoming GraphQL request.  So it's not a replacement for things like Redis and Memcache.
