### ISSUE TITLE
Result in subscription sends a Complete message on error

### ISSUE THREAD

**Issue by Sytten** [async-graphql/async-graphql#744]
## Expected Behavior
When creating a stream like `impl Stream<Item = Result<i32>>` and returning an `Err`, it should not send a `Complete` message as the stream might not be ended, just that it had an error.

## Actual Behavior

The server sends a complete message, closing the subscription.
<img width="638" alt="Screen Shot 2021-12-06 at 11 06 23 AM" src="https://user-images.githubusercontent.com/2366731/144880500-15581741-d1bd-462c-adc0-515496962346.png">

## Steps to Reproduce the Problem

1. Create a subscription that returns a `Result` 
2. Return an `Err`
3. The complete message is sent

## Specifications

- Version: Commit 3c6c93395d7c85ca2e034e76d56d37757e8f930f (actix-v4 branch)

**Comment by sunli829** [comment]
I think you are right, I shouldn't assume that the stream ends when it returns to `Err`. 😁

**Comment by sunli829** [comment]
Released in `v3.0.13`
