### ISSUE TITLE
Proposal: Create a actix-web-v4 crate

### ISSUE THREAD

**Issue by Sytten** [async-graphql/async-graphql#745]
## Description of the feature
I don't expect actix-web v4 to be merged anytime soon as there are still more than half the issues marked v4 that are opened.
The current way of dealing with this in async-graphql was with a branch that is forced push once in a while.
To alleviate some of the pain of the current approach,  I think we could create a new crate and merge it in main (even if it is a temporary one).

This would allow people to target a version on the integration that is tied to a particular beta version of actix.
We can then make sure that everybody gets the latest async-graphql features and don't break the builds because they target a particular commit.

I am happy to help maintain this crate!

**Comment by sunli829** [comment]
Thank you!

Now the `actix-web-v4` branch is obsolete because it has been merged into the `master` branch. 🙂

**Comment by Sytten** [comment]
Ha great thanks!
