### ISSUE TITLE
Field resolution time explode with result size

### ISSUE THREAD

**Issue by SadiinsoSnowfall** [async-graphql/async-graphql#747]
Hi,

I have noticed that when a GQL request returns a lot of JSON (hundreds to thousands of JSON objects), the time spent by async_graphql during the fields resolution (in [container_utils::resolve_container](https://github.com/async-graphql/async-graphql/blob/master/src/resolver_utils/container.rs#L65)) far outweighs the time it takes to query the data from a, SQL server and the total networking time (client -> backend (using GQL) -> sql server -> backend -> client).

For example, one of my GQL query looks like this : 
```graphql
{
   companies {
        nodes {
            sf
            address {
                countryCode cityCode city street
            }
            a {
                ...contactInfos
            }
            b {
                ...contactInfos
            }
            c {
                ...contactInfos
            }
        }
    }
}

fragment contactInfos on Contact {
    name fname phone fax email
}
```
This query returns about 1000 nodes (~120KB of JSON). The total execution time (from the client sending the query to receiving the data) is ~65ms, with field resolution alone taking ~35ms (and ~15ms for the underlying SQL queries).

How can I reduce the execution time of this function in this context?

**Comment by sunli829** [comment]
If you compare the performance of `async-graphql` and other libraries (in any language), you will find that `async-graphql` is fast enough. 🙂

**Comment by SadiinsoSnowfall** [comment]
Fast enough is not an objective measure.
But fair enough. I get what you are saying.

**Comment by Follpvosten** [comment]
I've hit this issue and it quickly becomes a real problem for my workload; I have one field in my query type which isn't requested very often, but it does return about 60,000 rows in one field.

async-graphql's way of constructing the result fields, specifically the `insert_value` function in `resolver_utils::container`, blows up my total request time from about three seconds to between 15 and 19 seconds.

What would you recommend me to do here @sunli829 ? Add a REST route for this one specific query, or maybe define the result type as a scalar?
