### ISSUE TITLE
actix-web-4.0.0-beta-14 changes Response types for Responder trait on GraphQLResponse

### ISSUE THREAD

**Issue by benwis** [async-graphql/async-graphql#749]
## Expected Behavior
I decided to run cargo update and was surprised to see an update for actix-web from beta 13 to 14 had add a new Body type for the Responder trait and changed the response from a couple of the functions. Looks like async-graphql will need to tweak it a bit once you decide to support the latest beta.

Perplexingly, it looks like Actix broke the builds for all other actix-web v4 betas, as they all give me about 200 different header errors, otherwise I'd downgrade. That's not your issue though.

## Steps to Reproduce the Problem

1. Try to use actix-web v4 beta 14 with async-graphql v3.0.6
2. Get error that GraphQLResponse doesn't implement Body
3. Attempt to redo GraphQLResponse

**Comment by sunli829** [comment]
Fixed in `3.0.15`
