### ISSUE TITLE
Release 3.0.15 uses unreleased version of futures-util

### ISSUE THREAD

**Issue by nileshmali** [async-graphql/async-graphql#752]
## Expected Behavior
Should use released version of futures-util crate.

## Actual Behavior
Using version 0.3.18 which is not yet released.

## Steps to Reproduce the Problem

1.
2.
3.

## Specifications

- Version:
- Platform:
- Subsystem:

**Comment by sunli829** [comment]
Fixed in `v3.1.16` 😁

**Comment by nileshmali** [comment]
Thanks
