### ISSUE TITLE
Updating to 3.0.15 from 3.0.2 is breaking change for data loader

### ISSUE THREAD

**Issue by mattoni** [async-graphql/async-graphql#753]
## Expected Behavior
No breaking changes

## Actual Behavior
<img width="564" alt="image" src="https://user-images.githubusercontent.com/5110855/146277969-61ab4ec4-2fd5-4a4a-a9d3-a47ecf9feee5.png">

Dataloader constructor now requires 3 arguments, the second of which I am having trouble finding any documentation on.

## Steps to Reproduce the Problem

1.
2.
3.

## Specifications

- Version:
- Platform:
- Subsystem:

**Comment by sunli829** [comment]
https://github.com/async-graphql/async-graphql/issues/555#issuecomment-985979321
