### ISSUE TITLE
Generic field on interface resulting in invalid schema

### ISSUE THREAD

**Issue by oscartbeaumont** [async-graphql/async-graphql#763]
I am working on an improved API for [`async-graphql-relay`](https://github.com/oscartbeaumont/async-graphql-relay) and have run across an issue when using generic fields on an interface. 

Essentially, Relay has a query that allows refetching of any object that has previously been fetched. It achieves this through globally unique IDs. The way [`async-graphql-relay`](https://github.com/oscartbeaumont/async-graphql-relay) achieves those unique IDs is by appending a string to the end of the database ID to represent its type. This new ID is then returned in all GraphQL queries and used in all GraphQL requests.

To easily add that object type to the end of the ID I introduced a type that is generic on the GraphQL Object. Eg. `pub id: RelayNodeID<Self>`, This is represented by `GenericID<Self>` in the example code.

I then create a GraphQL interface that contains all of the available types in the schema, the issue with this is that the ID field (which is shared between all of the types in the interface) is generic and the `#[graphql(field(name = "id", type = "..."))]` notation doesn't seem to support generics.

To work around this I created a type which in the example code is called `NonGenericID` which is able to parse the ID and due to the ID containing a suffix matching its type it is able to recreate the `GenericID<{object_type}>` (In practice a macro is used here to automate generating the matching code).

This all works in practice for doing actual queries but when opening the GraphQL playground in the browser an error is shown:
```
Invalid schema Error:
Interface field Node.id expects type NonGenericID! but Tenant.id is type GenericID!.
Interface field Node.id expects type NonGenericID! but User.id is type GenericID!.
```

I would like to know what can be done on my or your side to fix this issue in the schema. The expected result is for no error to be shown with the schema that is generated.

## Steps to Reproduce the Problem

I have included some demo code [here](https://gist.github.com/oscartbeaumont/8e03041c021d9a22de2b15edee9308ea). When downloaded you will have to put the Rust files in an `src/` subdirectory (as GitHub Gist's doesn't support subdirectories). Then open the GraphQL playground to see the error.

The example code is designed to show the problem and it is pretty useless/badly designed. If you want to understand why the code is designed the way it is checkout [`async-graphql-relay`](https://github.com/oscartbeaumont/async-graphql-relay)'s example project [here](https://github.com/oscartbeaumont/async-graphql-relay/tree/main/example). This project, however, makes use of macros so would be harder to debug hence why I provided the example project.

**Comment by sunli829** [comment]
I'm not sure if I really solved your problem, it seems you just need to rename `NonGenericID` to `GenericID` to solve it. 🙂

```rust
#[Scalar(name = "GenericID")]
impl ScalarType for NonGenericID
```

**Comment by oscartbeaumont** [comment]
That works perfectly. Thanks for your help!
