### ISSUE TITLE
`async-graphql` is breaking with `actix-http: v3.0.0-beta.17`

### ISSUE THREAD

**Issue by rieval** [async-graphql/async-graphql#769]
![image](https://user-images.githubusercontent.com/22883406/147577159-ce2a958a-415f-414c-85d9-821afbb27ac5.png)

![image](https://user-images.githubusercontent.com/22883406/147577264-b7a30dd2-dc66-4ebe-87fa-67a254944c89.png)

**Comment by PacoDu** [comment]
I've the same issue with `async-graphql-actix-web v3.0.18`

`PayloadStream` is still declared as deprecated here: https://github.com/actix/actix-web/blob/http-v3.0.0-beta.17/actix-http/src/payload.rs#L16 but as been removed from the `actix_web::dev` module https://github.com/actix/actix-web/pull/2545/files#diff-da17e7db207e483590bb92572e40b583f57b8737739a902946b46bc0d59b0465R17
