### ISSUE TITLE
How to forward Context?

### ISSUE THREAD

**Issue by nicolaiunrein** [async-graphql/async-graphql#77]
I updated to the current master branch and found out that in order to call methods defined on `Objects` I now need to pass in the `Context` as an argument. However I struggle to doing so because `Context` seems to store a reference and I need to pass in` Context` that does not get outlived by the returned stream. This is a simplified version of what I am struggling with at the moment:

```rust
use tokio::sync::mpsc::Receiver;

pub struct TestObject;

#[async_graphql::Object]
impl TestObject {
    #[field]
    async fn fetch(&self) -> i32 {
        1
    }
}


pub struct SubscriptionRootTest {
    channel: Receiver<i32>,
}

#[Subscription]
impl SubscriptionRootTest {
    #[field]
    async fn test(&self, ctx: &Context<'_>) -> impl Stream<Item = i32> {
        let ctx_clone = ctx.clone(); // even if I'm cloning here ...
        self.channel.filter_map(move |evt| {
            let ctx_clone = ctx_clone.clone(); // ...and here...
            async move {
                let ctx_clone = ctx_clone.clone(); // ...and here...
                TestObject.fetch(&ctx_clone).await.ok() // ...the compiler is not happy
            }
        })
    }
}
```
Wrapping Context in an `Arc` does not work either.

On the previous version it was unnecessary to pass in the `Context` as it was injected somewhere else by the library.

**Comment by sunli829** [comment]
Context cannot be cloned.

**Comment by sunli829** [comment]
Your usage is quite strange, why should you call TestObject::fetch directly?

**Comment by nicolaiunrein** [comment]
Well I don't think so but in the last version there was no requirement to pass in any Context to the method call.

**Comment by sunli829** [comment]
I added `Context` and `FieldResult` to each Field resolver, the purpose is to simplify the definition of interface.

**Comment by nicolaiunrein** [comment]
Well I basically want to reuse resolvers exposed in QueryRoot. Imagine TestObject exposed in QueryRoot.

**Comment by sunli829** [comment]
I understand, but now can not do so. 😂

**Comment by sunli829** [comment]
In fact, the function signature becomes this way, so that the field definition of the interface does not need to declare that the resolver of the object field has the Context parameter.FieldResult is the same reason.

```rust
async fn fetch(&self, Context<'_>) -> FieldResult<i32>
```

----------------

# Before

```rust
pub struct TestObject;

#[async_graphql::Object]
impl TestObject {
    #[field]
    async fn value(&self, ctx: &Context<'_>) -> FieldResult<i32> {
        1
    }
}

#[Interface(field(name="value", type = "FieldResult<i32>", context))]
struct Interface(TestObject);
```

# After

```rust
pub struct TestObject;

#[async_graphql::Object]
impl TestObject {
    #[field]
    async fn value(&self, ctx: &Context<'_>) -> FieldResult<i32> {
        1
    }
}

#[Interface(field(name="value", type = "i32"))]
struct Interface(TestObject);
```

**Comment by sunli829** [comment]
Why not just return the TestObject stream.

```rust
async fn test(&self) -> impl Stream<Item = TestObject> {
   ...
}
```

**Comment by nicolaiunrein** [comment]
Because I subscribe to an event-channel which only gives me IDs and I need to transform it to a Stream of enums where the variants are the fetched objects. But let me refactor my code I think I can simplify it.

**Comment by nicolaiunrein** [comment]
I worked it out thanks for the help! And good to know that Context is not Clone. :laughing:

**Comment by sunli829** [comment]
That `Clone` can only be used internally. 😁
