### ISSUE TITLE
Support `time` as alternative to `chrono`

### ISSUE THREAD

**Issue by jenanwise** [async-graphql/async-graphql#785]
Sadly it seems that `chrono` is [somewhat unmaintained](https://www.reddit.com/r/rust/comments/qamgyh/is_the_chrono_crate_unmaintained/). `time` appears to be a viable alternative and it'd be great if [`time::OffsetDateTime`](https://docs.rs/time/0.3.5/time/struct.OffsetDateTime.html) and [`time::PrimitiveDateTime`](https://docs.rs/time/0.3.5/time/struct.PrimitiveDateTime.html) worked out of the box with `async-graphql`.

Somewhat related to #664.

**Comment by sunli829** [comment]
I need to learn the use of the `time` crate first. 😁 Or even better if you can open a PR.

Refer here, it should be easy. 😁

https://github.com/async-graphql/async-graphql/blob/5c4289e442d6e56bcc3239b742e1534800adbe1b/src/types/external/datetime.rs#L13
