### ISSUE TITLE
.into_json() deserialize to T instead of serde_json::Value

### ISSUE THREAD

**Issue by longfellowone** [async-graphql/async-graphql#787]
## Description of the feature

For testing purpose it would be nice if we could deserialize to T instead of serde_json::Value. Currently the vale returned from `into_json()` is wrapped in an Object type so I have to wrap my own type `Vec<Project>`  to deserialize. I am still new to rust, so maybe I'm doing it the wrong way?

```rs
        #[derive(Debug, Deserialize)]
        struct Object {
            projects: Vec<Project>,
        }

        let response = schema.execute("query { projects { id, project } }").await;
        let json_value = response.data.into_json().unwrap();
        let object = serde_json::from_value::<Object>(json_value).unwrap();
```

## Code example (if possible)

Maby something along the lines of 

```rs
response.data.json::<T>().unwrap();
```

Where T is my own type. Not sure if this is possible? Similiar to [reqwest::Response.json()](https://docs.rs/reqwest/latest/reqwest/struct.Response.html#method.json
)

**Comment by sunli829** [comment]
Deserializing directly to type `Object` may not be a good idea, because the query may not always query all fields in this object.

You can do it like this:

https://github.com/async-graphql/async-graphql/blob/af9b78c732061293fc13101bc0a049006d25e643/tests/complex_object.rs#L420

**Comment by longfellowone** [comment]
Thanks! I wasn't aware you could index into serde_json::Value. 

`let id = left["createEstimate"]["estimate"]["id"].as_str().unwrap();`

https://github.com/longfellowone/est/blob/f7ed859784f1d0577c46a6d77e67986ace773b80/server/tests/estimate.rs#L103
https://docs.serde.rs/serde_json/value/enum.Value.html#method.get
