### ISSUE TITLE
Make `async_graphql::guard::Or`public

### ISSUE THREAD

**Issue by SorenHolstHansen** [async-graphql/async-graphql#794]
## Description of the feature
Right now, when i want to give access to both admins and users (i.e. anyone that is logged in), i write
```
#[graphql(guard = "RoleGuard::new(Role::Admin).or(RoleGuard::new(Role::User))")]
```
everywhere i need it.

However if we get access to the `Or` we could define the following
```
pub struct RoleGuard {
    role: Role,
}

impl RoleGuard {
    pub fn logged_in_user() -> async_graphql::guard::Or<RoleGuard, RoleGuard> {
        RoleGuard { role: Role::Admin }.or(RoleGuard::user())
    }
}
```
and then just write
```
#[graphql(guard = "RoleGuard::logged_in_user()")]
```
It is a minor inconvenience I know, but I don't see why why should not get access to the `Or`struct

**Comment by sunli829** [comment]
You can use `impl Guard` as the return type., which more convenient. 🙂

```rust
pub struct RoleGuard {
    role: Role,
}

impl RoleGuard {
    pub fn logged_in_user() -> impl async_graphql::Guard {
        RoleGuard { role: Role::Admin }.or(RoleGuard::user())
    }
}
```

**Comment by SorenHolstHansen** [comment]
Great, thanks!
