### ISSUE TITLE
Skip fields only on input when Struct derives both `SimpleObject` `InputObject`?

### ISSUE THREAD

**Issue by JRMurr** [async-graphql/async-graphql#797]
I have a type like
```rust
#[derive(SimpleObject, InputObject, Debug)]
#[graphql(input_name = "FooInput")]
pub struct Foo {
    id: String,
    name: String,
}
```

When used as an input i would like to not require the `id` field. I saw there is the `#[graphql(skip)` option but seems to skip it for both input and output.

I know it would need some default value if its skipped on input so the struct is valid but any ideas how i could accomplish that?

My next best guess would be a custom macro to split off `Foo` into separate input and output structs which isn't too bad but not sure if there's a better approach.

**Comment by sunli829** [comment]
I added `skip_input` and `skip_output` attributes to avoid conflicts in `v3.0.26`. 🙂

https://github.com/async-graphql/async-graphql/blob/22c7d40a6912c670e1cd5dc8104f10ad4da0f346/tests/input_object.rs#L411

https://github.com/async-graphql/async-graphql/blob/22c7d40a6912c670e1cd5dc8104f10ad4da0f346/tests/input_object.rs#L448

**Comment by JRMurr** [comment]
Awesome thank you!
