### ISSUE TITLE
support for modular graph

### ISSUE THREAD

**Issue by toxeus** [async-graphql/async-graphql#799]
## Background

I'm currently using juniper for GraphQL and am disappointed by the progress and maintenance of the project. That's why I want to migrate to async-graphql which seems to be actively developed and well-maintained. 

I have a modular graph structure with subgraphs and, therefore, depend on a feature to support that modular structure. I have checked the docs of async-graphql and came to the conclusion that this feature does not exist yet.

## Description of the feature

Each subgraph gets passed in its own context and has no access to contexts of other subgraphs. The toplevel node of the graph gets passed in a context that contains the contexts of all subgraphs. 

## Code example

See here https://docs.rs/juniper/latest/juniper/executor/trait.FromContext.html

I'm happy to elaborate more if the use-case is not fully clear.

**Comment by sunli829** [comment]
If I understand correctly, this `Context` is used to pass state?

In `Async-graphql` it looks like this:

#### Add the data:

https://github.com/async-graphql/examples/blob/c8219078a4b7aa6d84d22e9b79f033088897be4b/poem/starwars/src/main.rs#L17

#### Get the data 

https://github.com/async-graphql/examples/blob/c8219078a4b7aa6d84d22e9b79f033088897be4b/models/starwars/src/model.rs#L38

**Comment by toxeus** [comment]
@sunli829 thanks for the quick response. I seem to have missed that a concrete context can be fetched based on the type. I've seen a similar pattern before. That should work for me. I'll close the issue for now.
