### ISSUE TITLE
Missing security policy

### ISSUE THREAD

**Issue by quapka** [async-graphql/async-graphql#800]
Hi folks! Unfortunately, there is no [security policy](https://github.com/async-graphql/async-graphql/security/policy) for this project. This makes it difficult to report security vulnerabilities in case any are discovered in the future.

Adding a simple security policy (basically a secure channel to disclose findings) is [not difficult](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository).

**Comment by sunli829** [comment]
I don't know how to setup it, welcome to open a PR to do this. 🙂

**Comment by quapka** [comment]
Oh, right @sunli829. I'd be happy to help, but in this case, I can't do much :slightly_smiling_face:. What is needed is a file `SECURITY.md` that describes how a responsible disclosure should be carried out. For example, see [Python's security policy](https://github.com/python/cpython/security/policy).

The sole goal is to provide a way for an outsider of contacting the owners/maintainers responsible for the repository code in a discrete and secure manner. A security policy containing an e-mail address that is read only by trusted owners/maintainers can be enough for the start :)

Having such a policy helps keep the project healthy and should prevent people from using public issues for security issues or not disclosing them because there is no clear way how to do it.

**Comment by sunli829** [comment]
I checked several popular crates to try to replicate one, but none of them had a `SECURITY.md` file. 😂

**Comment by quapka** [comment]
Quite unfortunately true, yes. But see e.g. [apollo-server](https://github.com/apollographql/apollo-server/security/policy).

**Comment by sunli829** [comment]
Alright, I have add it. 😁

**Comment by quapka** [comment]
Ok, I suppose that's the case closed. :)
