### ISSUE TITLE
Field Still Show Even Have Visible = false

### ISSUE THREAD

**Issue by gho1b** [async-graphql/async-graphql#801]
## Expected Behavior
![image](https://user-images.githubusercontent.com/10357982/151452221-196e961a-24d4-4100-92bd-de7beef6de85.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/10357982/151452901-83ec5325-f101-48f7-ae64-4cc51144efea.png)

## Steps to Reproduce the Problem

1. Add derive macro `#[graphql(visible = false)]` in the field

## Specifications

- Version: 3.0.26
- Platform: Ubuntu 21
- Subsystem:

**Comment by sunli829** [comment]
The `visible` property only hides this field from introspection, but does not affect querying it.

**Comment by gho1b** [comment]
Thank you for the clarification
