### ISSUE TITLE
InputObject, SimpleObject, complex

### ISSUE THREAD

**Issue by callym** [async-graphql/async-graphql#802]
This code: 

```rust
#
#[derive(InputObject, SimpleObject)]
#[graphql(input_name = "AInput")]
#[graphql(complex)]
struct A {
  field: i32,
}

#[ComplexObject]
impl A {
  async fn field_two(&self) -> String {
    format!("This is a complex field: {}", self.field)
  }
}
```

Gives the following error: `unknown field 'complex'`.

I guess I want something similar to #797 for the `ComplexObject` macro?

**Comment by Oyelowo** [comment]
Also having this issue. I think there is a collision between the InputObject and ComplexObject. This would save duplications

**Comment by sunli829** [comment]
This issue has been resolved in previous releases.
