### ISSUE TITLE
thread 'tokio-runtime-worker' has overflowed its stack when using tokio & warp

### ISSUE THREAD

**Issue by ctopher7** [async-graphql/async-graphql#804]
## Expected Behavior
running well

## Actual Behavior
when gql method is being called by client (any registered gql method), server will produce error: thread 'tokio-runtime-worker' has overflowed its stack

## Steps to Reproduce the Problem

1. mutation root struct has more than 3 fields

## Specifications

- Version: 3.0.27
- Platform: macOS m1

related to #474

**Comment by sunli829** [comment]
Please provide a simple example that reproduces this issue.

**Comment by nickb937** [comment]
The time I have experienced this issue is when I've built a huge data structure that ends up allocated on the stack, exceeding the 2MB stack size.  I solved it by a liberal sprinkling of Box to the sub structures.
