### ISSUE TITLE
InputOutput type for Box<[T]>.

### ISSUE THREAD

**Issue by BratSinot** [async-graphql/async-graphql#805]
## Description of the feature

Greetings! Any way to have ability use `Box<[T]>` as input / output type? Same reason as `Box<str>`. `Box<[T]>` have only pointer and length and `Vec<T>` have pointer, length and capacity.

## Code example (if possible)
#[derive(SimpleObject)]
struct Data {
    ids: Box<[u64]>,
    username: Box<[Box<str>]>,
    password: Option<Box<[Box<str>]>>,
}

**Comment by sunli829** [comment]
Released in `v3.0.28` 🙂
