### ISSUE TITLE
MergedObject removes extends from sub-Query/Mutations that declare #[Object(extends)]

### ISSUE THREAD

**Issue by cawfeecoder** [async-graphql/async-graphql#806]
## Expected Behavior
When one (or more) sub-Query/Mutation object is created with #[Object(extends)] and then merged by #[MergedObject], I expect that the schema will still expose 'extend Query' in the SDL

## Actual Behavior
Currently, #[MergedObject] will strip off the #[Object(extends)], resulting in loss of Query/Mutation extension.

## Steps to Reproduce the Problem

1. Declare a query object (e.g. ExampleQuery) with a #[Object(extends)]
2. Use #[MergedObject] on a root query object that contains ExampleQuery
3. Examine the SDL and notice the lack of `extend Query`

## Specifications

- Version: 3.0.27 
- Platform: darwin_arm64
- Subsystem:

**Comment by sunli829** [comment]
You should add `extends` attribute on MergedObject.

```rust
#[derive(MergedObject)]
#[graphql(extends)]
struct MyObj(Object1, Object2, Object3);
```
