### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by sunli829** [async-graphql/async-graphql#81]
Can be compiled.

```shell
cd async-graphql
cargo build --all
```

Could not compile.

```shell
cd async-graphql/async-graphql-derive
cargo build
```

I don't know what makes this different.

**Comment by sunli829** [comment]
This issue prevented us from releasing a new version, because the `cargo package` cannot pass.

**Comment by nicolaiunrein** [comment]
compiles fine here...

**Comment by nicolaiunrein** [comment]
seems that the update of the syn crate breaks things. I get `std::cmp::Eq is not implemented for syn::ty::TypePath`

**Comment by sunli829** [comment]
But why “build all” works, it’s strange.

**Comment by nicolaiunrein** [comment]
If you put this in Cargo.toml it works
`syn = { version = "1.0.20", features = ["full", "extra-traits"] }`

**Comment by sunli829** [comment]
Tomorrow I try, I am now in drink. 😂

**Comment by nicolaiunrein** [comment]
Do you want me to commit?

**Comment by sunli829** [comment]
Yes.🤝

**Comment by nicolaiunrein** [comment]
Alright!
You would not think that there is more features than "Full" :laughing: My guess is that its a cargo bug when some other crate compiles this feature cargo does not re-compile the crate without the feature.

**Comment by nicolaiunrein** [comment]
@IcanDivideBy0 Now the tests faile with "async-graphql is not presetn in `Cargo.toml`. Could you look into? Its because of your latest commit.

**Comment by IcanDivideBy0** [comment]
@nicolaiunrein tests are fixed now

**Comment by nicolaiunrein** [comment]
I leave this issue open for further investigation

**Comment by krevativ** [comment]
Not sure if it relates to this issue. But unions seem to be broken. Union tests are working fine, but taking even the simple example from tests:

```rust
#[async_graphql::SimpleObject]
struct MyObj {
    id: i32,
    title: String,
}

#[async_graphql::Union]
enum Node {
    MyObj(MyObj),
}
```
and putting it somewhere else, gives me:

```
error: It should be a struct.
  --> tide/starwars/src/main.rs:24:1
   |
24 | / enum Node {
25 | |     MyObj(MyObj),
26 | | }
   | |_^
```
I tried it in my code using the latest version (1.11.3) and in the tide/starwars example (v 1.11.0). And I think interfaces are broken too.

**Comment by sunli829** [comment]
The published version of union is not defined that way.

**Comment by sunli829** [comment]
struct Node（ MyObj）
like this

**Comment by krevativ** [comment]
So it is how it will be defined in the future version or what do you mean by published version? But this is how it's stated in the book and the union tests. It's a bit confusing.

**Comment by nicolaiunrein** [comment]
They have been changed to Enums in #75 which got merged to the release branch after 1.11.3

**Comment by krevativ** [comment]
Ok thanks, I've missed that. So I was just at the wrong place at the wrong time.

**Comment by phated** [comment]
@krevativ I think you actually uncovered a problem with our current workflow. I'm going to look into updating the docs generation to only run when we tag

**Comment by sunli829** [comment]
@krevativ Upgrade async-graphql to `1.12.1`.
