### ISSUE TITLE
Dataloader: How to access request context?

### ISSUE THREAD

**Issue by Dig-Doug** [async-graphql/async-graphql#811]
Is there a way to get the current [context](https://async-graphql.github.io/async-graphql/en/context.html#request-data) from within a [dataloader](https://async-graphql.github.io/async-graphql/en/dataloader.html)?

Example use case: Get authentication data to do access control.

**Comment by sunli829** [comment]
You should create the data loader before executing the query and add the data loader to the `context` using the [`data`](https://docs.rs/async-graphql/3.0.28/async_graphql/struct.Request.html#method.data) method when executing the query.

```rust
#[handler]
async fn index(
    schema: Data<&StarWarsSchema>,
    headers: &HeaderMap,
    req: async_graphql_poem::GraphQLRequest,
) -> async_graphql_poem::GraphQLResponse {
    let jwt = headers.get("X-Token").unwrap();
    let loader = create_dataloader(jwt); // create your data loader
    schema.execute(req.0.data(loader)).await.into()
}
```

**Comment by Dig-Doug** [comment]
Got it, thanks!
