### ISSUE TITLE
ServerParseError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by azzamsa** [async-graphql/async-graphql#814]
I have built several app using Async-GraphQL and it is fantastic.

Now, I introduced new architecture, and I got this `ServerParseError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`. I have extracted a very small part from my application, and the error is still reproduced.

I attached the code as zip. But if putting it in git hosting will be easier to debug, I would.

``` bash
❯ exa --git-ignore -T -L 2
.
├── context.rs
├── errors
│  ├── core.rs
│  └── mod.rs
├── health
│  ├── mod.rs
│  ├── model
│  ├── resolver.rs
│  └── service
├── lib.rs
└── main.rs
```

![image](https://user-images.githubusercontent.com/17734314/152628089-b4ba8812-51b9-4dfe-8cd2-b308286db391.png)

```js
ServerParseError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    p bundle.esm.js:34
    promise callback*p/</</< bundle.esm.js:32
    promise callback*p/</< bundle.esm.js:74
    e Observable.js:197
    value Observable.js:279
    u bundle.esm.js:39
    u bundle.esm.js:38
    h SchemaFetcher.ts:138
    s middleware.js:98
    s middleware.js:98
    i middleware.js:98
    i middleware.js:98
    fetchSchema middleware.js:98
    h SchemaFetcher.ts:84
    s middleware.js:98
    s middleware.js:98
    i middleware.js:98
    i middleware.js:98
    fetch middleware.js:98
    I Playground.tsx:290
    s middleware.js:117
    s middleware.js:117
    s middleware.js:117
    s middleware.js:117
    schemaGetter middleware.js:117
    backoff Playground.tsx:166
    s middleware.js:117
    s middleware.js:117
    s middleware.js:117
    s middleware.js:117
    backoff Playground.tsx:164
    e middleware.js:124
```

```
❯ g l
314fe91 (HEAD -> master) 6 minutes ago remove serde from SimpleObject struct -- Error (azzamsa)
be6909f 8 minutes ago move routes to main (azzamsa)
144826c 11 minutes ago move schema to routes -- error (azzamsa)
f044541 14 minutes ago init -- error (azzamsa)
```

I tried to move everything to `main.rs` but the error still persists.

[gql.zip](https://github.com/async-graphql/async-graphql/files/8007343/gql.zip)

Maybe Related:
- https://github.com/async-graphql/async-graphql/issues/672
- https://github.com/nuxt-community/apollo-module/issues/293
- https://dev.to/ivkemilioner/i-can-t-find-where-is-error-syntaxerror-json-parse-unexpected-character-at-line-1-column-1-of-the-json-data-4g5i
- https://github.com/wp-graphql/wp-graphiql/issues/30

**Comment by sunli829** [comment]
```rust
#[handler]
pub async fn graphql_playground() -> impl IntoResponse {
    // Html(playground_source(GraphQLPlaygroundConfig::new("/")))
    Html(playground_source(GraphQLPlaygroundConfig::new("/graphql")))  // <<< Use the correct GraphQL endpoint.
}
```

**Comment by azzamsa** [comment]
Worked like a charm, turns out in old Rocket + Async-GrahpQL I use `/graphql`. That's why it works.

Should I open PR to change [this line](https://github.com/poem-web/poem/blob/2e113fcf51e13b35d18ad4bc998efe43cf3175bf/examples/poem/async-graphql/src/main.rs#L22)?

**Comment by sunli829** [comment]
> Should I open PR to change [this line](https://github.com/poem-web/poem/blob/2e113fcf51e13b35d18ad4bc998efe43cf3175bf/examples/poem/async-graphql/src/main.rs#L22)?

This is not necessary, just make sure that the path specified by `GraphQLPlaygroundConfig::new` matches the path of the endpoint. 😁
