### ISSUE TITLE
on_connection_init_with_data (for lack of a better name)

### ISSUE THREAD

**Issue by meh** [async-graphql/async-graphql#815]
## Description of the feature

It would be rad if `on_connection_init` could also receive the `Data` that's already present in the schema and websocket (or some `Context` equivalent), so as to be able to access things defined in there (like database connection and such) while handling the connection init payload.

## Code example (if possible)

```rust
let mut data = Data::default();
data.insert(loader);

Ok(ws.protocols(ALL_WEBSOCKET_PROTOCOLS).on_upgrade(move |socket| {
  GraphQLWebSocket::new(socket, schema, protocol)
    .with_data(data)
    .on_connection_init_with_data(|super: Data, init: json::Value| async move {
      #[derive(Deserialize)]
      struct Authorize {
        token: Token,
        csrf: Token,
      }

      let mut data = Data::default();

      if let Ok(Authorize { token, csrf }) = json::from_value(init) {
        // NOTE: this is part of the Schema data
        let env = super.get(&TypeId::of::<crate::Env>()).unwrap().clone();

        if let Ok(session) = session::Account::verify(env, &token, &csrf).await {
          data.insert(session);
        }
      }

      Ok(data)
    }))
    .serve()
}))
```

**Comment by sunli829** [comment]
`on_connection_init` accepts a closure, so there is no need to support getting data from the context, what do you think?

**Comment by meh** [comment]
The closure is Fn so I cannot move anything inside the closure, and dealing with references in futures gets impossible.

**Comment by sunli829** [comment]
> The closure is Fn so I cannot move anything inside the closure, and dealing with references in futures gets impossible.

```rust
let env = create_env();

GraphQLWebSocket::new(socket, schema, protocol)
    .on_connection_init(move |init: json::Value| {
    let env = env.clone();
    async move {
        let mut data = Data::default();

        if let Ok(Authorize { token, csrf }) = json::from_value(init) {
            if let Ok(session) = session::Account::verify(env, &token, &csrf).await {
                data.insert(session);
            }
        }

        data 
    }
})
```

I believe this works, you need to implement `Clone` for `crate::Env`, what do you think? 🙂

**Comment by meh** [comment]
Damn, you're right, I was using the `closure` crate and it wasn't properly moving the `Env` inside or some weird interaction with `async move` and the `closure` crate, sorry for the noise! :panda_face:
