### ISSUE TITLE
Is it possible to denote non-nullable fields?

### ISSUE THREAD

**Issue by danielcasler** [async-graphql/async-graphql#821]
This crate does not seem to use a GraphQL schema in the traditional sense. I'm used to defining a type (in a schema) and denoting which fields are non-nullable with an **!**.

I've gone through the core sections of the book and looked at the examples and can't see anything that talks about how this is accomplished with this crate, which is surprising as this is standard GraphQL stuff.

Likewise, I also looked at the field attributes in the docs and did not see anything. 

Can you please tell me if this crate supports a way to specify nullable and non-nullable fields?

**Comment by sunli829** [comment]
By default all fields are non-nullable, but you can use `Option<T>` to represent a nullable field.
