### ISSUE TITLE
Flattening of `Option<T>` in `Object`

### ISSUE THREAD

**Issue by danielalvsaaker** [async-graphql/async-graphql#823]
## Description of the feature
Would be nice if `Option<T>` could be flattened in an `Object`. Right now, it fails due to `Option<T>` not implementing `ObjectType`.
Should resolve every field of the flattened object to null if the object is null.

## Code example 
```rust
#[Object]
impl A {
    #[graphql(flatten)] // Does not compile
    async fn b(&self, ctx: &Context<'_>) -> Option<B> {
        // Get a key from the database, value might not exist
        ctx.data_unchecked::<Database>().get("key")
    }
}

**Comment by sunli829** [comment]
This cannot be achieved, `Object` macro does not ensure that all fields of the `B` object are nullable.
