### ISSUE TITLE
Playground not storing response cookie

### ISSUE THREAD

**Issue by GuigsEvt** [async-graphql/async-graphql#826]
## Expected Behavior

The playground should store the cookie response.

## Actual Behavior

The playground receives the cookie response from GraphQL handler but do not store it. Though when sending a new query/mutation not cookies is sent whithin the request.

I use async_graphql with axum and use the following code to send the response.
```
async fn log_in(
        &self,
        ctx: &Context<'_>,
        user_id: String,
        password: String,
    ) -> async_graphql::Result<User> {
        let service = ctx.data::<Service<P>>()?;
        let user = service.log_in(&user_id, &password).await?;
        if let Some(session) = user.session.clone() {
            ctx.insert_http_header(
                "Set-Cookie",
                format!("session={}; Domain=localhost; HttpOnly", session.id),
            );
            return Ok(User::from(&user));
        }
        return Err(async_graphql::Error::new(
            "could not create user",
        ));
    }
```
I got this on the Google Chrome browser on the Application browser

<img width="1432" alt="Screenshot 2022-02-17 at 13 54 27" src="https://user-images.githubusercontent.com/19888951/154551007-69097a14-dc49-4dae-b0d3-56daebd8c843.png">

But then when sending a new request the cookie is not send within the request. Is there a way to configure the playground to do it ? I don't think this is a server issue because we receive the correct answer and the process work correctly when using Postman.

**Comment by oscartbeaumont** [comment]
Refer to #508. You need to change the GraphQL playground setting `request.credentials` to `include` or `same-site`.

**Comment by GuigsEvt** [comment]
Ok thank you, I didn't think it was related to the cookies. It works fine.
