### ISSUE TITLE
Feat: Guards can apply to group of queries 

### ISSUE THREAD

**Issue by longfellowone** [async-graphql/async-graphql#838]
## Description of the feature

Guards can apply to group of queries as it can be tedious to apply to every query (and can also be forgotten)

## Code example (if possible)

In addition to this method

```rs
#[Object]
impl UserQueries {
    #[graphql(guard = "UserGuard")]
    pub async fn me(&self, ctx: &Context<'_>) -> async_graphql::Result<User> {
        let user = ctx.data_unchecked::<User>();

        Ok(user.clone())
    }
}
```

Option 1

```rs
#[derive(MergedObject, Default)]
pub struct QueryRoot(#[graphql(guard = "UserGuard")] UserQueries);
```

Option 2
```rs
#[derive(Default)]
#[graphql(guard = "UserGuard")]
pub struct UserQueries;

```

Option 3

```rs
???
```

**Comment by loafofpiecrust** [comment]
Just my 2c, Option 2 looks reasonable to me in terms of DX and I'd love to be able to define a guard on a whole Query type.

**Comment by tsing** [comment]
Option 2 seems to be handled by the changes in [e80e4c9](https://github.com/async-graphql/async-graphql/commit/e80e4c9af9b6176977416a164820010658423694).

But it would be greater if it could support the following use case:

```
#[derive(Default)]
#[graphql(guard = "UserGuard")]
pub struct UserQueries {
    #[graphql(guard = "AnotherGuard")]
    pub async fn me(&self, ctx: &Context<'_>) -> async_graphql::Result<User> {
        let user = ctx.data_unchecked::<User>();

        Ok(user.clone())
    }
}
```

With the code above, when resolving `me`, the `AnotherGuard` will be used and the `UserGuard` will be ignored. However, is it better if the guard behaves like `UserGuard.and(AnotherGuard)`?
