### ISSUE TITLE
Git tag releases

### ISSUE THREAD

**Issue by phated** [async-graphql/async-graphql#84]
I think it is very important that we use `git tag` to tag each release. We can then make certain workflows (like building the book) rely on a tag being created so our documentation aligns with the available release.

**Comment by IcanDivideBy0** [comment]
I totally agree.
Coming from JavaScript, I use Lerna to manage release on monorepos, does anyone know similar tools in rust ?

**Comment by nicolaiunrein** [comment]
I personally use cargo-bump which is quite nice but it‘s nowhere near lerna. Do you think it makes sense to serve the book from the release branch well?

**Comment by sunli829** [comment]
I also agree that this is important. 😁

**Comment by ruseinov** [comment]
I haven't seen a lot of repos so far relying on git tags to release the actual crate. One problem that I see with this approach if you want to do both book and the crate via tags is that when you only update the book you are forced to release a new version of the crate too, for no good reason. 

If you just do the book via tags it's going to be confusing too, because the tags won't align with crate release versions. One way to solve this is moving the book in a separate repo.

**Comment by phated** [comment]
You can release on tag too. I'm not sure I understand the point of the `release` branch.

**Comment by nicolaiunrein** [comment]
I just discovered the [cargo-workspaces](https://crates.io/crates/cargo-workspaces) crate. It is made by the developer of clap and is inspired by lerna. I haven’t had a chance to look into it but it looks interesting and might help in our case. Does anyone have experience with it?

**Comment by phated** [comment]
@nicolaiunrein that looks really great. I want to try using it here.

**Comment by sunli829** [comment]
I tried it and it feels pretty good. 😁

**Comment by phated** [comment]
@sunli829 it seems you are using that tool to make releases now. Is there anything else you'd like to do here? I'm happy to work on build process/CI/CD stuff 😄

**Comment by sunli829** [comment]
> @sunli829 it seems you are using that tool to make releases now. Is there anything else you'd like to do here? I'm happy to work on build process/CI/CD stuff 😄

This tool is quite easy to use, but I do n’t know how to use it in CI, so it would be great if you could help me! 😁

**Comment by sunli829** [comment]
Maybe we can execute `cargo workspaces version patch -y` after the code is merged into the release branch, then cargo publish?
