### ISSUE TITLE
Implement extractors for context

### ISSUE THREAD

**Issue by longfellowone** [async-graphql/async-graphql#840]
## Description of the feature

Would it make sense to use the extractor pattern to pull .data() from &Context<'_>

Not sure if its even possible?

Similar to the way actix and axum work

https://actix.rs/docs/extractors/
https://docs.rs/axum/latest/axum/extract/index.html

## Code example (if possible)

Current method

```rs
#[Object]
impl UserQueries {
    pub async fn me(&self, ctx: &Context<'_>) -> async_graphql::Result<User> {
        let user = ctx.data_unchecked::<User>();
        // ...
    }
}

```

With extractor (Instead of Data could be name anything, like `FromCtx<>` or `Ctx<>`

```rs
#[Object]
impl UserQueries {
    pub async fn me(&self, user: Data<User> ) -> async_graphql::Result<User> {
      //  ...
    }
}

```

**Comment by sunli829** [comment]
This is a big change, and since everything is working fine so far, I won't consider this for now. 😁

**Comment by longfellowone** [comment]
🤞🤞

## [4.0.0] 2022-??-??

- Add context extractors
