### ISSUE TITLE
how to use sse protocol for subscription ? 

### ISSUE THREAD

**Issue by muhammad-davatgar** [async-graphql/async-graphql#842]
is it possible to use warp's `sse` for doing one sided stream in async-graphql ? i looked it up a little bit and it seems like async-graphql-warp use websockets by default , is there a way i could change that or websocket is the only allowed protocol currently ? thanks in advance

**Comment by sunli829** [comment]
Easily, you can copy the stream returned by `Schema::execute_stream` to the `SSE` response.

**Comment by frederikhors** [comment]
@muhammad-davatgar did you find a way? can we add an example of this to the examples dir?

**Comment by jayy-lmao** [comment]
This looks like an example of someone doing this?

https://github.com/RustPanda/async-graphql-sse
