### ISSUE TITLE
Returning from subscription with error

### ISSUE THREAD

**Issue by fgadaleta** [async-graphql/async-graphql#845]
It could happen that a subscription fails and instead of returning something like 

```
impl Stream<Item = Option<MyThing>>
```

I would like to interrupt the stream or not start it at all.
How can this be done with the current implementation?

**Comment by Venryx** [comment]
I have the same question.

I tried changing my subscription resolver function to return `Result<impl Stream<Item = GQLSetVariant> + 'a, Error>`, but it gave the error:
```rust
#[Subscription]
   | ^^^^^^^^ the trait `Stream` is not implemented for `Result<impl Stream<Item = MyItem>, anyhow::Error>`
```

**Comment by Venryx** [comment]
Nevermind, I figured it out; you just have to return `impl Stream<Item = Result<GQLSetVariant, MyError>> + 'a`.

Though some things to note:
1) You have to use an error-type that has `Clone` implemented; in my case I just created a basic `SubError` struct:
```rust
use std::{error::Error, fmt};

// Clone is needed for it to be used under async-graphql's `#[Subscription]` macro
#[derive(Debug, Clone)]
pub struct SubError {
    message: String,
}
impl SubError {
    pub fn new(message: String) -> Self {
        Self { message }
    }
}

impl Error for SubError {}

impl fmt::Display for SubError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "GQLError:{}", self.message)
    }
}
```
2) In your subscription handler, you have to make sure that the errors returned are of your cloneable error-type. I didn't know how to do this while still using the `?` operator, so here was my workaround:
```rust
async fn my_items<'a>(&self, ctx: &'a Context<'_>) -> impl Stream<Item = Result<MyItem, SubError>> + 'a {
    let stream_for_error = |err: Error| {
        async_stream::stream! {
            yield Err(SubError::new(err.to_string()));
        }
    };

    // if you want to do this, in the code prior to your `async_stream::stream!` closure...
    //let temp = func_that_may_error()?;
    
    // do this instead...
    let temp = match func_that_may_error() { Ok(a) => a, Err(err) => return stream_for_error(err) };

    // and then inside the regular loop...
    async_stream::stream! {
        loop {
            // where you want to do this...
            //let temp = func_that_may_error()?;

            // do this instead... (untested, but it should work)
            let temp = match func_that_may_error() {
                Ok(a) => a,
                Err(err) => {
                    yield Err(SubError::new(err.to_string()));
                    break;
                }
            };

            // regular entry-yielding for the non-error case
            yield temp.get_next_entry().await;
        }
    }
}
```

**Comment by Venryx** [comment]
@sunli829 Would it maybe be worth adding some example like this to the async-graphql [error-handling docs](https://async-graphql.github.io/async-graphql/en/error_handling.html), for returning errors from subscription resolvers rather than only queries/mutations?

**Comment by sunli829** [comment]
@Venryx  Would you like to help improve it? 😁

**Comment by Venryx** [comment]
> @Venryx Would you like to help improve it? 😁

Haha, I was afraid you'd ask that. 😆

I'll see if I can find time to write something up.
