### ISSUE TITLE
Getting context in index function

### ISSUE THREAD

**Issue by oganexon** [async-graphql/async-graphql#847]
Hi there, really enjoying this library

I'm using the [actix-web/token-from-header](https://github.com/async-graphql/examples/blob/840fd0aa36f6fa4633047ef3000bb51b35e26b7b/actix-web/token-from-header/src/main.rs) template.
Sorry if it's a dumb question or considered as a bad practice, but how can I get context data from the `index` function ?

```rust
async fn index(schema: web::Data<TokenSchema>, req: HttpRequest, gql_request: GraphQLRequest) -> GraphQLResponse {
    let mut request = gql_request.into_inner();

   // here
   // request.data. ?
   // request = request.data.???.ldap.bind("user", "password");

    if let Some(token) = get_token_from_headers(req.headers()) {
        request = request.data(token);
    }
    schema.execute(request).await.into()
}
```

I know you can kind of access it with `request.data` but it's a raw HashMap and I would prefer having a nice `ContextData` object.

Is there another way of adding new context data from global data ?

**For more background**, I'm building an LDAP GraphQL API, and I need to bind to the correct user on each query. The LDAP connection is added when the schema is built.
```rust
Schema::build(Query, Mutation, EmptySubscription)
        .data(ldap)
        .finish()
```

**Comment by sunli829** [comment]
This doesn't seem to make sense, the context data is empty by default.

You should probably use the `Data` extractor from `Actix-web`?

```rust
async fn index(schema: web::Data<TokenSchema>,  ldap: web::Data<LDAP>, req: HttpRequest, gql_request: GraphQLRequest) -> GraphQLResponse {
   ...
}
```

**Comment by oganexon** [comment]
Turns out that I can't do that, since the data is hidden in the `SchemaInner`, and the context data is empty at this point in time.

Is there a simple solution to authenticate a user before the request is executed?
