### ISSUE TITLE
Cannot use query complexity limitations on graphql cursor connections, cause it's not a list

### ISSUE THREAD

**Issue by jrouaix** [async-graphql/async-graphql#848]
## Expected Behavior

Tried to use query complexity limitations on a field returning paginated nodes using cursor connections :

https://async-graphql.github.io/async-graphql/en/depth_and_complexity.html#limiting-query-complexity
https://async-graphql.github.io/async-graphql/en/cursor_connections.html

IMHO, we should be able to limit here based on some `first, last` parameters.

## Actual Behavior

the complexity computation `ComplexityType::Fn` is ignored in the complexity visitor here : https://github.com/async-graphql/async-graphql/blob/a278cc14123140a94ee57873b949261fe874dd13/src/validation/visitors/complexity.rs#L64

Because the result type of the query is of type `async_graphql::Result<Connection<usize, SomeOtherType, EmptyFields, EmptyFields>>`

## Steps to Reproduce the Problem

use some `#[graphql(complexity = "... some_function_call() ... * child_complexity")]`
https://async-graphql.github.io/async-graphql/en/depth_and_complexity.html#limiting-query-complexity
https://async-graphql.github.io/async-graphql/en/cursor_connections.html

both at the same time on a field.

the complexity will be ignored.

**Comment by jrouaix** [comment]
If I remove the condition, the expected behavior happens. 
Perhaps it's a quick fix ?
Is this condition really an expected limitation ?

**Comment by jrouaix** [comment]
Hello ? @sunli829 ?
Any idea about this one ?
Would you prefer a PR ?

**Comment by jrouaix** [comment]
Anyhow here with some thoughts about this ?
I strongly thinks it's a bug, and an easy one to kill, but no-one cares ?

**Comment by sunli829** [comment]
I'm so sorry to see this just now, I'll check tomorrow to see if this condition is really necessary. 🙂

**Comment by sunli829** [comment]
I was probably confused at the time. 😂
