### ISSUE TITLE
Make book and docs link to examples

### ISSUE THREAD

**Issue by nicolaiunrein** [async-graphql/async-graphql#85]
There is no links to the examples repo in the book and docs. I think we should add them. Not sure where though.

**Comment by sunli829** [comment]
Maybe we can add a new chapter to introduce each example?

**Comment by nicolaiunrein** [comment]
How would you introduce them? Like explaining what they demonstrate? I just thought of a simple link but a separate chapter seems to be even better.

**Comment by nicolaiunrein** [comment]
I added example and benchmark sections to the introduction of the book and docs

**Comment by sunli829** [comment]
Thank you. 😁
