### ISSUE TITLE
How to implement request cookies in test ?

### ISSUE THREAD

**Issue by GuigsEvt** [async-graphql/async-graphql#852]
Hello. 

I am trying to test my resolvers and some of them are behind some cookies validators. I am using the from_request features as seen below. 

```
#[async_trait]
impl<B> FromRequest<B> for SessionResponse
where
    B: Send,
{
    type Rejection = &'static str;

    async fn from_request(req: &mut RequestParts<B>) -> Result<Self, Self::Rejection> {
        match extract::TypedHeader::<Cookie>::from_request(req).await {
            Ok(cookies) => match cookies.get(COOKIE_NAME) {
                Some(c) => {
                    // Handle cookie
                },
                None => {
                    // Handle none error
                }
            },
            Err(_e) => {
                // Handle error
            }
        }
    }
}
```

I cannot access my resolvers because of the FromRequest that is looking for a cookie that it cannot find. I haven't been able to find tests setting cookies headers in the query. Is there a way to do that ?

Kind regards.

**Comment by sunli829** [comment]
It looks like this issue has nothing to do with `Async-graphql`.
