### ISSUE TITLE
graphql-ws sends "data" instead of "next"

### ISSUE THREAD

**Issue by stijnfrishert** [async-graphql/async-graphql#857]
## Expected Behavior
I'm connecting over a websocket to my `async-graphql` server with the subprotocol [`graphql-ws`](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md).

According to that standard, the reply to a `{ "type": "subscribe" }` message should be `{ "type": "next" }`. I've found, however, that my `async-graphql-poem`-based server sends back `{ "type": "data" }`. This seems like some left-over from the legacy `subscriptions-transport-ws` subprotocol?

## Actual Behavior
`async-graphql` sends a message with `{ "type": "data" }`.

## Specifications

- Version: async-graphql 3.0.31 (latest)
- Platform: macOS Monterey 12.2.1

**Comment by sunli829** [comment]
Note: The WebSocket sub-protocol for this specification is: `graphql-transport-ws`, not `graphql-ws`. 🙂

**Comment by stijnfrishert** [comment]
Hmm, when why does it acept `graphql-ws` (and it that listed in [`ALL_WEBSOCKET_PROTOCOLS`](https://github.com/async-graphql/async-graphql/blob/334307b2c23087243d297f92d734d7d3908a96ec/src/http/websocket.rs#L19))?

**Comment by sunli829** [comment]
[graphql-ws](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md) is another protocol. 🙂

**Comment by stijnfrishert** [comment]
Wait, so besides `graphql-ws` and `subscription-transport-ws`, there's also `graphql-transport-ws`? Sheesh, this is confusing! 😅 

Still, my question stands: apparently async-graphql [accepts both](https://github.com/async-graphql/async-graphql/blob/7d58bd814dcf91e4048c5f746e1773637abd209b/integrations/poem/src/subscription.rs#L97) `graphql-ws` and `graphql-transport-ws`. Is that correct?

- If not, and async-graphql only supports `graphql-transport-ws` it should flat-out refuse my subprotocol request to use `graphql-ws`. As of version `3.0.31` it gladly accepts `graphql-ws`.
- If it should indeed accept both, I'd expect `"next"` events for `graphql-ws` and `"data"` for `graphql-transport-ws`. Right now they're mixed up. I get `"data"` for `graphql-ws`.

**Comment by stijnfrishert** [comment]
Riiiiight, *now* I understand.

The repo that's called [https://github.com/enisdenjo/graphql-ws](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) describes a protocol called `graphql-transport-ws`. That's really confusing.

Using `graphql-transport-ws` _does_ give me `"next"`.

Thank you for being patient with me, @sunli829 🙏

**Comment by Adel-ak** [comment]
@stijnfrishert may i ask how did you get your web server to work with graphql-ws ?, when I ever try to connect with to subscriptions with graphql-ws using altair play ground it errors out.

I'm using actix web btw.

**Comment by stijnfrishert** [comment]
Erhm, I had to write my own `graphql-ws` client side implementation in C++, because I couldn't find a lib that worked out of the box. Never had issues with the server erroring out, nor do I have experience with Altair.

Sorry, afraid I can't help you out here much further :/
