### ISSUE TITLE
How to translate @derivedfrom to Rust async-graphql code?

### ISSUE THREAD

**Issue by al8n** [async-graphql/async-graphql#861]
Hi, I have an schema has `@derivedFrom` filed, I cannot find a way to translate it in native Rust async-graphql code.

For example:
```
type User @entity {
   ...
   loverRelateData:  [LoverRelateData!]! @derivedFrom(field: "user")
}
```

**Comment by sunli829** [comment]
Sorry, I don't know the behavior of the `derivedFrom` directive.
