### ISSUE TITLE
Treat &Type and Type in edge/connection as the same thing

### ISSUE THREAD

**Issue by Sytten** [async-graphql/async-graphql#864]
## Description of the feature

Currently if you try to use a ref sometimes and the owned object in another place, you will get the error:
```
thread 'main' panicked at '`async_graphql::types::connection::edge::Edge<proxy_backend::api::Cursor, proxy_backend::api::SitemapEntry, async_graphql::types::connection::EmptyFields>` and `async_graphql::types::connection::edge::Edge<proxy_backend::api::Cursor, &proxy_backend::api::SitemapEntry, async_graphql::types::connection::EmptyFields>` have the same GraphQL name `SitemapEntryEdge`', /home/sytten/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.34/src/registry/mod.rs:411:25
```

This error makes sense when the type are different, but for a ref not so much.
This forces you to use `Cow` everywhere and it complexifies your code for no real benefit.

**Comment by Sytten** [comment]
Otherwise maybe just add a feature to disable the panic?

**Comment by sunli829** [comment]
This is really cumbersome and I haven't figured out a good way to fix this, adding a flag to turn off this detection looks nice. 😁

**Comment by Sytten** [comment]
Fixed with the ignore name conflict
