### ISSUE TITLE
How are `PageInfo::{start_cursor, end_cursor}` set when using `Connection`?

### ISSUE THREAD

**Issue by meh** [async-graphql/async-graphql#868]
Or do I need my own `Connection` to be able to set them?

**Comment by sunli829** [comment]
Yes, you need to set them yourself, as described in this document.

https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo.Fields

**Comment by meh** [comment]
But do I need my own connection type and then use `query_with`? Or is there a setter for `Connection` I'm not seeing?

**Comment by meh** [comment]
Wait, I guess the start and end cursors come from the cursor in the first and last edges that are inserted?

**Comment by sunli829** [comment]
Sorry I was wrong. 😂

`PageInfo` is automatically generated from all edges within the `Connection`.

https://github.com/async-graphql/async-graphql/blob/b82186413b0accdf9903a9a5b4256512d1a36fde/src/types/connection/connection_type.rs#L132

**Comment by meh** [comment]
Ooh, that's where the PageInfo creation was hiding, I didn't notice it when looking around.
