### ISSUE TITLE
Discussion: Should we add logging?

### ISSUE THREAD

**Issue by nicolaiunrein** [async-graphql/async-graphql#87]
I sometimes have the desire to set `RUST_LOG=trace` and see what's going on under the hood. Do you think we should add some tracing to this library as well? I have setup the actix_web middleware for logging but that does not help all too much wenn using graphql because almost all lines look like this: `127.0.0.1:43558 "POST / HTTP/1.1" 200 603432 "http://localhost:5001/" 0.221888`.

**Comment by sunli829** [comment]
In fact, I really considered this issue, but I did n’t think about what to output. Are you willing to implement this feature? Just write an extension, it should be easy. 😁

**Comment by IcanDivideBy0** [comment]
At a `trace` level, I'd probably expect a log for each resolver call, guards, validators, so I think getting something similar to the ApolloTracing extension would be a good start.

**Comment by nicolaiunrein** [comment]
I will create a draft when I find some time. Do extensions get called on subscriptions?

**Comment by sunli829** [comment]
The subscription does not call the extension, because the subscription document does not explain how the extension results are output.

**Comment by ruseinov** [comment]
It seems like trace/debug level logging should actually reside in the library itself, not as an extension. It'd be nice if whoever is using the library is missing some info would suggest  /contribute the functionality needed for their particular use-case. I totally agree that the more debug info you can get - the better, I am not sure though this should be elaborate to implement on trace level, as long as the code is made a noop when the level is above trace/debug.

**Comment by mwilliammyers** [comment]
Logging e.g. all errors would be super handy to have as a catch all in case you forgot to log them in resolvers.

FYI: here is some discussion on logging in juniper:
- https://github.com/graphql-rust/juniper/issues/423
- https://github.com/graphql-rust/juniper/pull/370

**Comment by nicolaiunrein** [comment]
I think we should look at it from two perspectives: I really see two separate tasks at hand:

1. Logging during development.
We could add a couple of calls like this to the codebase which should provide decent logging out of the box during development: 
```rust
#[cfg(debug_assertions)]
log::trace!("Subscription started with ID: {}", id);
```

2. Logging in production.
This should be highly configurable because we should not force the user into a specific library or logging system. A user could already implement a custom logger by implementing the `Extension` trait as @sunli829 suggested. I think this approach is fine if the `Extension` trait had more event hooks. At the moment it is not possible to log certain important events like this at all because `Extension` was designed for a different purpose. So my suggestion would be to provide a `Middleware` trait which is much like `Extension` but gets called on every important event. We could implement this behind a feature-flag in order to avoid useless calls. This way a user could easily implement a custom logger for production by implementing `Middleware`. We could then also provide a `DefaultLogger` based on this trait.
I can imagine there are more use-cases than logging for a `Middleware` trait as well.

I imagine an API like this:
```rust
pub trait Middleware {
    async fn on_request_start(&self, request: serde_json::Value) -> Result<(), Error> {}
    async fn on_request_done(&self, request: serde_json::Value, response: serde_json::Value) -> Result<(), Error> {}
    async fn on_subscription_start(&self, id: usize, query: Query) -> Result<(), Error> {}
    async fn on_subscription_stop(&self, id: usize) -> Result<(), Error> {}
    ...
}
```

Returning Results would have the benefits of enabling the `Middleware` to abort certain requests. Not useful for logging but maybe for other things like auth.

**Comment by sunli829** [comment]
I have to think about it, because `Middleware` and `Extension` are very similar. 😁

**Comment by nicolaiunrein** [comment]
I know. Extending `Extension` might be a better solution.

**Comment by sunli829** [comment]
After I support `@stream`, let's see how to pass more information to `Extension`.

**Comment by sunli829** [comment]
I added a `Logger` extension.

```rust
let schema = Schema::build(QueryRoot, MutationRoot, SubscriptionRoot)
        .data(Storage::default())
        .extension(|| extensions::Logger::default())
        .finish();
```

**Comment by nicolaiunrein** [comment]
I used the `Logger` and it works Ok for now. I would like to add a flag to enable/disable introspection queries as they are very verbose and litter the logs. I am just not sure what should be the default. Any suggestions? I tend to have them disabled by default and have a flag `include_introspection`

**Comment by sunli829** [comment]
The `ResolveInfo` parameter of `Extension::resolve_start` can get the query path, and we can use it to filter out `root .__ schema`.
But `Extension::parse_start` does not have this information, so the introspection query will still display this log.

**Comment by nicolaiunrein** [comment]
We could pass the source and the parsed document to `parse_end` , filter and log the original query. This will only log after parsing but errors during parsing get logged anyway.

**Comment by sunli829** [comment]
I am thinking about how to configure this filter.

**Comment by sunli829** [comment]
How about this one?

```rust
Logger::new()
    .include("query.books")
    .include("mutation.createBook")
    .include("subscriptions.createBook")
    .exclude("query.__schema")
```

**Comment by nicolaiunrein** [comment]
Thanks for the change. In terms of the above filter: what does it match against? It seems practical but a little un-rustic to me. Could we instead derive a tag on the handlers like `#[log(include)]`?

**Comment by ruseinov** [comment]
That's a cool approach! It might be really helpful to also be able to specify these in a config file of sorts, similar to how you would configure log4j, for example. Could be a yaml/toml/whatever. That's nice, because one does not always want to change code, but instead configure logging externally depending on the deployment environment.

**Comment by sunli829** [comment]
I have now filtered the introspection query, because this is the easiest to do. 😀
Maybe we can use environment variables as the filtering configuration of logs.

**Comment by mwilliammyers** [comment]
How hard would be able to add access to `Context<'_>` inside the logger (and other extensions) and be able to configure logging with it? I want to add a few fields from `.data()` to logs...

**Comment by sunli829** [comment]
Let me think about it.

**Comment by mwilliammyers** [comment]
@sunli829 Did you decide how hard it would be to access `Context<'_>` in the logger?

**Comment by sunli829** [comment]
Not hard, but I don't have time for it right now.

**Comment by mwilliammyers** [comment]
Any mentoring tips? I might have time for it... At the very least I can open an issue for it so we don't forget about it...

**Comment by sunli829** [comment]
I don't think the ctx parameter is necessary. Can you explain why you need this parameter?

**Comment by mwilliammyers** [comment]
Logging without adding context like `user_id`, `company_id` etc. is mostly useless for my project. 

It is actually easier to log that context myself in my code rather than adding it to every `Err` type so that it can be logged by `async-graphl`. My other option is to `Box` all my errors/use `FieldError`, but I have custom error `enums` that I would like to keep.

**Comment by sunli829** [comment]
I see, but the `Context` is not easy to add, so I'll give you an `&Data` argument, ok?

**Comment by mwilliammyers** [comment]
The thing I get back from `context.data()`? Thats all I need :)

**Comment by sunli829** [comment]
How about I add a ctx at ResolveInfo?

**Comment by mwilliammyers** [comment]
As long as I can get access to my `context.data()`, then that works!

**Comment by mwilliammyers** [comment]
I can try to add it if you don't have time

**Comment by sunli829** [comment]
> As long as I can get access to my `context.data()`, then that works!

`ctx` is only available at `resolve_start` and `resolve_end`, which I think will satisfy your needs. I'm working on this. This is easy.

**Comment by sunli829** [comment]
Could you possibly need `Extension::error` to get `ctx`?

**Comment by mwilliammyers** [comment]
> Could you possibly need `Extension::error` to get `ctx`?

Oh, I haven't looked at `Extension::error`. But it might makes sense to add it to both `Extension::logger` and `Extension::error`? That seems useful and it keeps things the same.

**Comment by sunli829** [comment]
I think I should add `Extension::resolve_error(&self, info: &ResolveInfo< '_>)`

**Comment by mwilliammyers** [comment]
`ResolveInfo` does not have access to `ctx` though, right?

**Comment by sunli829** [comment]
> `ResolveInfo` does not have access to `ctx` though, right?

I can add, that's easy.

**Comment by sunli829** [comment]
You can only get data in these three places.

```rust
/// Called at the begin of the resolve field.
    fn resolve_start(&self, info: &ResolveInfo<'_>) {}

    /// Called at the end of the resolve field.
    fn resolve_end(&self, info: &ResolveInfo<'_>) {}

    /// Called when resolve field fails.
    fn resolve_error(&self, info: &ResolveInfo<'_>) {}
```

**Comment by mwilliammyers** [comment]
Perfect! Thank you!

**Comment by sunli829** [comment]
> Perfect! Thank you!

I'm almost there, but I was wondering why you didn't add this information when you created Extension?

**Comment by mwilliammyers** [comment]
I am confused... I didn't create `Extension`.

**Comment by sunli829** [comment]
```rust
let schema = Schema::build(QueryRoot, EmptyMutation, EmptySubscription)
        .data(StarWars::new())
        .extension(|| MyLogger { username: "..." })
        .finish();
```

**Comment by sunli829** [comment]
You should implement extensions yourself.

**Comment by sunli829** [comment]
Do you think it's better that way?

**Comment by mwilliammyers** [comment]
Shouldn't it be:
```
   fn resolve_error(&self, err: &Error, info: &ResolveInfo<'_>) {}
```

**Comment by sunli829** [comment]
Even if I added CTX to the ResolveInfo, you'll still have to implement Extension yourself.

**Comment by mwilliammyers** [comment]
The `user_id` etc. changes with every request, so I can't build it up front when I build the schema

I do something like:
```rust
let graphql_post = warp::any()
    .and(auth)
    .and(warp::any().map(move || Arc::clone(&ctx_config)))
    .and(graphql_warp::graphql(schema.clone()))
    .and_then(
        |claims, ctx_config, (schema, mut builder): (_, QueryBuilder)| async move {
            builder = builder.data(ContextData::new(claims, ctx_config));
            let response = builder.execute(&schema).await;
            Ok::<_, Infallible>(GQLResponse::from(response))
        },
    );
```

where `claims` come from the `Bearer: <token>` header for each request.

**Comment by sunli829** [comment]
> The `user_id` etc. changes with every request, so I can't build it up front when I build the schema
> 
> I do something like:
> 
> ```rust
> let graphql_post = warp::any()
>     .and(auth)
>     .and(warp::any().map(move || Arc::clone(&ctx_config)))
>     .and(graphql_warp::graphql(schema.clone()))
>     .and_then(
>         |claims, ctx_config, (schema, mut builder): (_, QueryBuilder)| async move {
>             builder = builder.data(ContextData::new(claims, ctx_config));
>             let response = builder.execute(&schema).await;
>             Ok::<_, Infallible>(GQLResponse::from(response))
>         },
>     );
> ```
> 
> where `claims` come from the `Bearer: <token>` header for each request.

Sorry, I made a mistake. I should have added an extension function to the `QueryBuilder`.

**Comment by mwilliammyers** [comment]
> Even if I added CTX to the ResolveInfo, you'll still have to implement Extension yourself.

That's fine 😄 , I would have probably anyway. It will be worth it; I will be able to get rid of *a lot* of logging code throughout my whole project 🎉

**Comment by sunli829** [comment]
```rust
builder = builder.data(ContextData::new(claims, ctx_config)).extension(|| MyLogger { username: "..." });
```

**Comment by mwilliammyers** [comment]
haha I didn't know you could do that 😆. I must have missed that somewhere in the docs...

**Comment by sunli829** [comment]
> haha I didn't know you could do that 😆. I must have missed that somewhere in the docs...

Actually, I didn't add it. I always thought the Extension was created in QueryBuilder. 😁

**Comment by mwilliammyers** [comment]
Oh, you haven't added it to `QueryBuilder`, yet?

**Comment by sunli829** [comment]
Yes, I'm adding.

**Comment by sunli829** [comment]
I have always thought that this function is available, so I feel strange when you need to add `ctx` to the `Extension`, sorry.

**Comment by sunli829** [comment]
@mwilliammyers Upgrade to `1.14.15`. 😁

**Comment by sunli829** [comment]
@mwilliammyers Please let me know if you can use it, because I have no test. 😁

**Comment by mwilliammyers** [comment]
@sunli829, yup its working! Thanks!

Two quick questions:

1. Does the `Extension` trait need a `'static` lifetime bound? It makes it so I can't do:

   ```rust
   struct Logger<'a> {
       id: Uuid,
       requester: &'a Option<Claims>,
   }

   impl<'a> Extension for Logger<'a> { ... }
   ```

1. Is this the easiest/fastest way to get the query/mutation name? I want to avoid logging the entire `query_source` so that I don't log passwords etc...

   ```rust
   for definition in document.definitions() {
       if let Definition::Operation(operation) = &definition.node {
           let selection_set = match &operation.node {
               OperationDefinition::Query(query) => &query.selection_set,
               OperationDefinition::Mutation(mutation) => &mutation.selection_set,
               OperationDefinition::SelectionSet(selection_set) => &selection_set.node,
               _ => continue,
           };

           for selection in selection_set.items.iter() {
               if let Selection::Field(field) = &selection.node {
                   info!("id: {}, {}", self.id, &field.name);
               }
           }
       }
   }
   ```

   I guess I could also do:

   ```rust
   if !query_source.contains("password") {
       info!("id: {}, {}", self.id, &query_source);
   }
   ```

   but that seems a little hacky...

**Comment by sunli829** [comment]
> 1. Does the `Extension` trait need a `'static` lifetime bound? It makes it so I can't do:

Yes, this has to be 'static 'for a lot of reasons

> Is this the easiest/fastest way to get the query/mutation name? I want to avoid logging the entire query_source so that I don't log passwords etc...

I think password shouldn't be in the query, it should be in HTTP Headers, don't you think?

**Comment by mwilliammyers** [comment]
1. Cool, no worries. I’ll just clone the id from the Claims. 

2. I have a login mutation that accepts a password. (After that, tokens are sent in the header). I also don’t want to log any other sensitive information (99% of the time this will be in variables though). Also, regardless I don’t want to log the whole query because it can clutter the logs with a lot of info. I just used that snippet ^ it seems to be working great!
