### ISSUE TITLE
Crashes when initializing schema with similar Connection types

### ISSUE THREAD

**Issue by djc** [async-graphql/async-graphql#870]
I have a `Domain`, `Post` and `Image` types. Both my `Domain` and my `Post` types have an `images()` resolver. `Domain::images()` creates a `Connection<i64, Image, DomainEdge, EmptyFields>`, while `Post::images()` returns a `Connection<i64, Image, PostEdgeFields, EmptyFields>`.

## Actual behavior

When I build the schema containing my types, I get the following panic:

'`async_graphql::types::connection::connection_type::Connection<i64, Image, PostEdgeFields>` and `async_graphql::types::connection::connection_type::Connection<i64, Image, DomainEdge>` have the same GraphQL name `ImageConnection`' in /Users/djc/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.35/src/registry/mod.rs:411:25.

Additionally, if I name the additional type `PostEdge` instead of `PostEdgeFields` I get a different panic:

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/djc/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.35/src/registry/mod.rs:435:45

## Actual Behavior

Since these types are different, I don't think this cause a failure. I was additionally surprised that this kind of thing causes a run-time failure rather than a compile-time failure.

## Specifications

- Version: 3.0.35
- Platform: macOS
- Subsystem: registry

**Comment by sunli829** [comment]
I'll try to fix it these days, maybe add a procedural macro, which can't be done with generics. 😁

**Comment by sunli829** [comment]
Fixed in `v4.0.0`
