### ISSUE TITLE
Expose access to Connection::edges

### ISSUE THREAD

**Issue by djc** [async-graphql/async-graphql#871]
## Description of the feature

Right now `Connection`'s `edges` field is private, and the only way to push edges into it is using several accessors. This approach makes it harder than necessary to add the edges. This makes adding edges a lot less flexible (and thus harder) than it would be if the `Vec` was exposed directly. The downside would be constraining the public API somewhat, but given that `Vec` seems to be a good match for exactly what `Connection` is trying to do, that doesn't seem to be a big deal IMO.

## Code example (if possible)

If you already have a `Vec` of edges, having to go through an iterator to get it into the `Connection` is inefficient. If you want to do some async operations in order to create the edges (for example, talking to the backing store in order to extend the edge's data), you now have to go through the `Stream` interface, which adds a bunch of complexity. If your creation of edge types is fallible, having to deal with the `try_()` methods also makes life harder than it could be (since you have to propagate the error out of any `map()` closures you might need).

**Comment by sunli829** [comment]
Fixed in `v3.0.36` 😁

**Comment by djc** [comment]
Thanks!
