### ISSUE TITLE
Relay Compliance Examples

### ISSUE THREAD

**Issue by kennetpostigo** [async-graphql/async-graphql#872]
Is there any examples showing how to make the server Relay compliant? I couldn't find any in the `examples` repo, are there any OSS projects that show how they've done this?

**Comment by sunli829** [comment]
Here is the example:

https://github.com/async-graphql/examples/blob/61384c8fa50e1395e50015b2be77b4bc6f5de4d2/models/starwars/src/model.rs#L133

**Comment by kennetpostigo** [comment]
Whats the point of the `query` usage there?
```rs
query(
    after,
    before,
    first,
    last,
    |after, before, first, last| async move {
        // ...
    }
)
```

Here is the definition in doc.rs:
https://docs.rs/async-graphql/latest/async_graphql/types/connection/fn.query.html#


Couldn't that logic just be written in a resolver?

**Comment by sunli829** [comment]
The `query` function can help you do some necessary checks.

https://github.com/async-graphql/async-graphql/blob/9318c0731d019da88d6d5666b1b3335a44d9e787/src/types/connection/mod.rs#L213

**Comment by kennetpostigo** [comment]
Thank you @sunli829
