### ISSUE TITLE
@deprecated not turning up in generated schema

### ISSUE THREAD

**Issue by djc** [async-graphql/async-graphql#874]
## Expected Behavior

If I mark some resolvers in an `#[Object]` impl with `#[graphql(deprecation = "Blah")]`, I would expect these to be marked with `@deprecated` in the generated schema. I could not find anything about this in the book but managed to find some mentions by searching the repository (and then looking for the reference documentation for the `#[Object]` attribute macro).

## Actual Behavior

I can add the attribute with or without reason and async-graphql will generate a schema for me, but it doesn't add `@deprecated` directives.

## Specifications

- Version: 3.0.35
- Platform: macOS

**Comment by sunli829** [comment]
I forgot to add this, will do it now. 😂

**Comment by sunli829** [comment]
Fixed in `v3.0.36` 😁

**Comment by djc** [comment]
Thanks!
