### ISSUE TITLE
Is it legitimate (a good idea) to pass global state via the root object itself?

### ISSUE THREAD

**Issue by loxs** [async-graphql/async-graphql#878]
I didn't see this in the documents and I wonder if it's a good idea that I do something this:

```rust
    let schema: CASchema = Schema::build(
        MyQueryRoot {
            db: Arc::clone(&db),
        },
        EmptyMutation,
        EmptySubscription,
    ).finish()
```

Later in the field handlers I can just use `self.db` to acces my global state.
I tested it and it works and I prefer it a lot more than the `ctx.data::<MyContext>()` way because it's enforced at compile time, and also `self.db` feels a lot cleaner than having to call `ctx.data` in every field, as per the docs.
Of course, this requires me to pass the data further down the nested query objects, but I still prefer this.

My question is, what is the catch? Am I doing something stupid?

**Comment by sunli829** [comment]
That's a good idea, and I do it sometimes, like here:

https://github.com/async-graphql/async-graphql/blob/2c4cfa17072a10e118d3ca403bcd127378dbd1c6/src/model/schema.rs#L6

**Comment by negezor** [comment]
How could this work with `MergedObject` 🤔
