### ISSUE TITLE
Add convenience method to `MaybeUndefined`

### ISSUE THREAD

**Issue by djc** [async-graphql/async-graphql#881]
## Description of the feature

It might be nice if `MaybeUndefined` knew how to update an `Option<T>` in place. Something like this:

```rust
fn update_if_defined(self, current: &mut Option<T>) {
    match self {
        MaybeUndefined::Value(new) => *current = Some(new),
        MaybeUndefined::Null => *current = None,
        MaybeUndefined::Undefined => {},
    };
}
```

What do you think? Worth thinking about whether this is a good name, too.

**Comment by sunli829** [comment]
This method is very useful. 🙂
