### ISSUE TITLE
Accessing context data from REST route

### ISSUE THREAD

**Issue by ClementNerma** [async-graphql/async-graphql#882]
Hi there!

I'm currently using Async-GraphQL for a personal project and so far I've been enjoying it a lot!

I have one little problem with the current API though: alongside my GraphQL API, I have a few REST routes (classical `#[rocket::get]`) which also need to access the GraphQL context. How can this be done?

The schema is build using `Schema::build().data(xxx).finish()` but I didn't find any method allowing to get the data from the `State<AppSchema>`, only from the `Context<'_>` itself (using `.data::<Type>().unwrap()`, which I cannot seem to get from the state either.

Thanks in advance for your help!

**Comment by sunli829** [comment]
You can use `Request::data` to pass state before each query, like below:

https://github.com/async-graphql/examples/blob/6a63808523f7e4995f9111a3497f06921cd3b11b/poem/token-from-header/src/main.rs#L31

**Comment by ClementNerma** [comment]
I don't get how this helps me, in the example `index` is a `#[handler]` mounted on one specific GraphQL route (if I understand correctly), while I need to get the state in REST routes.

**Comment by sunli829** [comment]
I'm sorry I didn't understand your question earlier.

Make your data cloneable(Usually you can use `Arc`), bind it both in the GraphQL schema and in Rocket's global state.

**Comment by ClementNerma** [comment]
> I'm sorry I didn't understand your question earlier.
> 
> Make your data cloneable(Usually you can use `Arc`), bind it both in the GraphQL schema and in Rocket's global state.

Oh that's clever! I didn't think of it.

So this means technically Async-GraphQL doesn't support getting the context in the REST routes, which is unfortunate. Sure using an `Arc` is a simple trick but wouldn't it be possible to simply expose a method from the `Schema` type to get the context's data in REST routes, just like we get it from the `Context`/`ContextBase` in GraphQL queries and mutations?

**Comment by sunli829** [comment]
You want `Context` to be able to borrow some data without needing to clone it, which sounds good.
It's just that `Async-graphql` was not designed that way at first. 🙂

**Comment by ClementNerma** [comment]
Indeed, but is there a reason why there isn't a simple getter method like we have on the GraphQL routes?

**Comment by sunli829** [comment]
Because I think the current solution works well. 🙂

**Comment by ClementNerma** [comment]
It does indeed, but it would be even more convenient to have a simple getter method, in order to avoid having to manually change the state's type and most importantly to take time to find a solution to this problem, as it was far from being obvious.

If you want I can dig in the codebase and open a PR for this as I think it would be quite convenient and save a bit of time for every person look on how to do the same thing I did.

**Comment by sunli829** [comment]
I'm sure this feature isn't easy to add.😂

**Comment by ClementNerma** [comment]
I'll close this issue for now and re-open it when I have to look at the codebase so see how much this would need ;)
