### ISSUE TITLE
Improve enums as query input parameters

### ISSUE THREAD

**Issue by alisenai** [async-graphql/async-graphql#886]
## Description of the feature
Unless I've misread the docs, or haven't managed to find the relevant source code from this library, there is currently no way to serialize an enum as a non-stringified scalar.

Related: https://github.com/async-graphql/async-graphql/issues/790

<br>

Consider the following enum and graphql query:
```rust
#[derive(Serialize, Deserialize)]
enum Letter { A, B }
scalar!(Letter);

async fn return_letter(&self, letter: Letter) -> Letter { letter }
```
This results in the following schema:
```gql
scalar Letter

returnLetter(letter: Letter!): Letter!
```

This means:
- No auto-complete by various schema parsers
- Stringified values within queries

<br>

## Code example
Ideally, I would like to be able to do:
```rust
// Note the `InputObjectEnum`!
#[derive(InputObjectEnum, Serialize, Deserialize, Enum, Copy, Clone, Eq, PartialEq, Debug)]
enum Letter { A, B }

async fn return_letter(&self, letter: Letter) -> Letter { letter }
```
Where `InputObjectEnum` would allow for "true" enums within gql queries.

<br>

## Possible Implementation
If this is not currently possible, I've written a derive macro to do just that:
```rust
#[proc_macro_derive(InputObjectEnum)]
pub fn input_object_enum(item: TokenStream) -> TokenStream {
    let enum_item: syn::ItemEnum = syn::parse(item).expect("Expected an enum");
    let enum_ident: syn::Ident = enum_item.ident;

    quote!(
        impl ScalarType for #enum_ident {
            fn parse(value: Value) -> InputValueResult<Self> {
                match value.clone() {
                    Value::String(string_value) => {
                        match serde_json::from_str(string_value.as_str()) {
                            Ok::<#enum_ident, _>(enum_value) => {
                                Ok(enum_value)
                            }
                            _ => Err(InputValueError::expected_type(value))
                        }
                    }
                    _ => Err(InputValueError::expected_type(value))
                }
            }

            fn is_valid(value: &Value) -> bool {
                matches!(value, Value::Boolean(_))
            }

            fn to_value(&self) -> Value {
                Value::from(serde_json::to_string(self).unwrap())
            }
        }
    ).into()
}
```

Which results in the following schema - which allows for non-stringification and autocomplete:
```gql
enum Letter {
  A
  B
  C
}

returnLetter(letter: Letter!): Letter!
```

Please note that:
- This does **not** solve enums in query responses being stringified - the solution is likely similar but for responses
- I've only been using rust for a few weeks now
- This is just how I've done it for my project, so it may not be optimal

<br>

Sorry this is so lengthy and thanks for any help 👍🏼

**Comment by sunli829** [comment]
I think you should use the `Enum` macro. 😂

https://docs.rs/async-graphql/3.0.38/async_graphql/derive.Enum.html

**Comment by alisenai** [comment]
Weirdly enough, I can't reproduce my issue. Oh well, thanks for the help 👍🏼
