### ISSUE TITLE
`OutputType` is not implemented for `PrimitiveDateTime`

### ISSUE THREAD

**Issue by leebenson** [async-graphql/async-graphql#887]
## Expected Behavior

https://github.com/async-graphql/async-graphql/pull/791 added support for the `time` feature, implementing (among other types) a scalar value for `time::PrimitiveDateTime`.

I would expect this to work with [sqlx](https://github.com/launchbadge/sqlx)'s `types::time::PrimitiveDateTime` re-export.

## Actual Behavior

```rs
use sqlx::types::time::PrimitiveDateTime;

#[derive(SimpleObject)]
pub struct SomeObject {
    created_at: PrimitiveDateTime,
    modified_at: PrimitiveDateTime,
}
```

Yields:

```
error[E0277]: the trait bound `PrimitiveDateTime: OutputType` is not satisfied
  --> src/db/configuration.rs:10:10
   |
10 | #[derive(SimpleObject)]
   |          ^^^^^^^^^^^^ the trait `OutputType` is not implemented for `PrimitiveDateTime`
```

## Specifications

- Version: 3.0.37

**Comment by sunli829** [comment]
Did you turn on the `time` feature?

**Comment by sunli829** [comment]
`sqlx` depends on `time 0.2`😂.

**Comment by leebenson** [comment]
Ah, thanks, I'll see if I can get them to bump 👍🏻

**Comment by leebenson** [comment]
Hmm https://github.com/launchbadge/sqlx/pull/1455
