### ISSUE TITLE
Preserve field order for introspection

### ISSUE THREAD

**Issue by hapcode** [async-graphql/async-graphql#89]
I've the following code:
```rust
pub enum ChangeStatus {
    Applied,
    Canceled,
    Handling,
    Pending,
    Rejected,
    Scheduled,
}
```

Resulting GraphQL SDL from playground:
```graphql
enum ChangeStatus {
  APPLIED
  CANCELED
  REJECTED
  PENDING
  SCHEDULED
  HANDLING
}
```
Is it possible to preserve declared order? I think this feature is important, especially for Interfaces with common fields, which should have a stable order for readability.

**Comment by sunli829** [comment]
Good suggestion, `enumValues`, `fields`, `possibleTypes`, `inputFields`, `args` have order problems, I will fix this problem now.
Thank you. 😁

**Comment by sunli829** [comment]
Please upgrade async-graphql to `1.12.8`. 😁

**Comment by hapcode** [comment]
Great. My scheme looks nice. Many thanks.
