### ISSUE TITLE
Field Guard for `InputObject`

### ISSUE THREAD

**Issue by oganexon** [async-graphql/async-graphql#890]
## Description of the feature

I really like the field guard and hidden content features. It is really useful to display additional data on the same schema.

Would it be possible to have those features on `InputObject` ? 

For example, we can think of a request in which we want to filter by ID, but this property is only visible to the admins. On the requested object, this field will not appear for the average user, but it will still appear in the input object which is annoying.

## Code example (if possible)

```rust
#[derive(InputObject)]
pub struct UserFilter {
    pub name: Option<String>,
    #[graphql(guard = "RoleGuard::new(Role::Admin)")]
    pub id: Option<String>,
}
```

**Comment by sunli829** [comment]
`InputObject` already supports the `visible` property.

**Comment by sunli829** [comment]
```rust
#[derive(SimpleObject)]
#[derive(InputObject)]
pub struct UserFilter {
    pub name: Option<String>,
    #[graphql(visible = "is_admin")]
    pub id: Option<String>,
}

pub fn is_admin(ctx: &Context<'_>) -> bool {
    ....
}
```

**Comment by oganexon** [comment]
Great, I don't know why it didn't work when I tried with the visible property.

I'm leaving the issue open for the guard feature, I think it's still very useful.

**Comment by xD3CODER** [comment]
Hi,

In addition to making the Guards available for the InputObject, it would be nice to be able to define guards when using SimpleObject and Inputobject simultaneously
