### ISSUE TITLE
Subscription resolvers are not polled reliably

### ISSUE THREAD

**Issue by Venryx** [async-graphql/async-graphql#892]
## Expected Behavior

When multiple clients connect to a subscription endpoint, all of the streams should be polled correctly, such that they successfully return all data available from the source that is polled.

## Actual Behavior

Instead what happens is that _most_ of the subscribers get the latest results. But for some reason, there is almost always one or a few of the subscribers who "lag behind" and aren't sent all the entries.

I've confirmed that the data is truly not being sent (using Chrome's dev-tools).

I've also confirmed that the data (in those cases) is "being delayed from being accessed" within the async resolver functions: The resolver function is always calling `my_broadcast_receiver.recv().await` in a loop, for all clients' instances, but for some reason, async-graphql is not "polling" some of the futures reliably, causing some of them to have delayed/unreliable access to the latest broadcasted entries (and thus the client inherits those delays as well).

Anyway, the reason I think the issue is in async-graphql (rather than in the [broadcast library](https://docs.rs/async-broadcast/latest/async_broadcast/index.html) I'm using or something), is that:
1) I have tried three different broadcast libraries ([tokio::sync::broadcast](https://docs.rs/tokio/latest/tokio/sync/broadcast/index.html), [flume](https://docs.rs/flume/latest/flume/), and [async-broadcast](https://docs.rs/async-broadcast/latest/async_broadcast/index.html)), and they all exhibit the same issue.
2) I can fix the issue merely by wrapping the future from `my_broadcast_receiver.recv()` in a call to this:
```rust
/// A weird but necessary workaround to resolve the issue of some futures not being polled reliably.
pub async fn make_reliable<T>(fut: impl Future<Output = T>) -> T {
    // Pin the future so it can be polled.
    let mut fut = Box::pin(fut);

    // Create a new context to be passed to the future.
    let waker = Arc::new(EmptyWaker).into();
    let mut cx = Context::from_waker(&waker);

    let mut interval = tokio::time::interval(Duration::from_millis(10));
    loop {
        // The next two lines are where the magic happens: every 10 milliseconds, poll the future...
        // ...even if the future-context "above" this function/future is not getting polled reliably
        interval.tick().await;
        match fut.as_mut().poll(&mut cx) {
            Poll::Pending => {},
            Poll::Ready(res) => {
                return res;
            },
        }
    }
}

struct EmptyWaker;
impl Wake for EmptyWaker {
    fn wake(self: Arc<Self>) {
        // do nothing; we merely need a context-object to pass to poll()
    }
}
```

I have taken screen captures, showing before and after with my hack/fix.

Without fix:
```rust
loop {
  let get_msg_future = msg_receiver.recv();
  let msg = get_msg_future.await.unwrap();
  send_msg_to_client(msg);
}
```
![](https://i.imgur.com/JJmPMZy.gif)

With fix:
```rust
loop {
  let get_msg_future = msg_receiver.recv()

  // added
  let get_msg_future_fixed = make_reliable(next_msg_future);
  
  let msg = get_msg_future_fixed.await.unwrap();
  send_msg_to_client(msg);
}
```
![](https://i.imgur.com/nK7mgax.gif)

## Steps to Reproduce the Problem

I have not yet put together a minimal reproduction case for this issue. I will likely do so at some point (if the issue is not already known), but I want to post it here first in case there's something simple I am overlooking that could resolve the issue. (I have spent several hours trying to narrow down this bug already)

## Specifications

- Version: 3.0.28
- Platform: Linux (Debian) [my host computer is Windows, but the server is running in a debian docker container (specifically, based on the docker image `debian:bookworm-slim`), in a local Docker Desktop kubernetes cluster]

**Comment by sunli829** [comment]
Thank you very much for your hard work, this problem happened before, but it was fixed later, maybe I missed something.

**Comment by sunli829** [comment]
Did you use `tokio::select!` to receive messages from `async_graphQL:: HTTP::WebSocket` stream?

**Comment by Venryx** [comment]
> Did you use `tokio::select!` to receive messages from `async_graphQL:: HTTP::WebSocket` stream?

Well, I am not interacting with `async-graphql`'s WebSocket struct directly, so I guess it depends on what the `async_graphql_axum` integration is doing: https://github.com/async-graphql/async-graphql/tree/master/integrations/axum/src

Specifically, here is the point at which I create a `GraphQLSubscription` instance, and hook it up to axum: https://github.com/debate-map/app/blob/3740b240c6f473cf35d3daa1630538934c1d466d/Packages/monitor-backend/src/gql_.rs#L134-L140

**Comment by sunli829** [comment]
I've been testing for a long time but can't reproduce this issue. 😂

**Comment by Venryx** [comment]
Okay, I will try to make a small reproduction case at some point. (Thank you for trying, even despite my repro-case laziness. 😅)

**Comment by sunli829** [comment]
Here is the test repo:

https://github.com/sunli829/test-async-graphql-subscription

**Comment by Venryx** [comment]
Ah nice, thanks for the starter. (I might use that and try to reproduce -- or alternately, I might start from my main project, and just keep cutting huge chunks out, to see how small I can get the repo while keeping the bug present.)
