### ISSUE TITLE
Have the same GraphQL name `MoreResult`

### ISSUE THREAD

**Issue by nieaowei** [async-graphql/async-graphql#895]
<img width="531" alt="image" src="https://user-images.githubusercontent.com/42961884/163976760-dc1f9e39-baab-4d48-ae45-130cd6a1b891.png">

**Comment by sunli829** [comment]
要不你说中文或者加我微信

**Comment by nieaowei** [comment]
> 要不你说中文或者加我微信

可以

**Comment by nieaowei** [comment]
同一个Query对象，两个不同的resolver，使用MoreResult<T> {more:bool,list:Vec<T>} 包装返回值。

**Comment by nieaowei** [comment]
```rust
struct MoreResult<T>{
more:bool,
list:Vec<T>,
}

struct Result1{
id:String
}

struct Result2{
id:String
}

struct Query;
impl Query{
async fn issues(&self)->Result<MoreResult<Result1>>{

}

async fn evaluations(&self)->Result<MoreResult<Result2>>{

}
}
```

**Comment by sunli829** [comment]
https://github.com/async-graphql/async-graphql/blob/613368097bfe82e9322f3341d75f8b506c6409a8/tests/generic_types.rs#L303
