### ISSUE TITLE
Guards on entire Object/SimpleObject etc. ?

### ISSUE THREAD

**Issue by kennetpostigo** [async-graphql/async-graphql#898]
I see there are [field guards](https://async-graphql.github.io/async-graphql/en/field_guard.html) available. However, is it possible to put guards more generally on:

- Object/SimpleObject/etc.
- queries
- mutations

Do you have any thoughts on these types of Guards?

**Comment by sunli829** [comment]
You can use the `guard` attribute on types.

https://github.com/async-graphql/async-graphql/blob/613368097bfe82e9322f3341d75f8b506c6409a8/tests/guard.rs#L352
