### ISSUE TITLE
Support for uuid::Uuid v >= 1.0.0

### ISSUE THREAD

**Issue by onx2** [async-graphql/async-graphql#902]
It looks like `uuid` just released version `1.0.0` and I tried switching and received this error:

```
the trait bound `uuid::Uuid: OutputType` is not satisfied
required because of the requirements on the impl of `OutputType` for `&uuid::Uuid`
```
on this struct I have with the derived SimpleObject
```
#[derive(SimpleObject, Serialize, Deserialize, Debug, FromDbModel)]
pub struct User {
    pub id: Uuid,
    pub email: String,
    ..
}
```
Two part question:

1. Could I temporarily resolve this by not using `SimpleObject`?
2. What would it take to support v1 of uuid / is this a good first issue for a Rust beginner?

**Comment by sunli829** [comment]
> What would it take to support v1 of uuid / is this a good first issue for a Rust beginner?

Yes, welcome. 😁

**Comment by onx2** [comment]
Cool, I can give it a shot when I get back home. Any pointers on what this might take / where to start?

**Comment by sunli829** [comment]
I guess just need to update the `uuid` version and then fix possible compile errors.

**Comment by cynecx** [comment]
Can we support both? There are still many crates that depend on < 1.0 and it might take a while until the ecosystem migrates to uuid 1.0.

**Comment by semanser** [comment]
@sunli829 I'm still getting the same error with the async-graphql `4.0.0` 

Repro code: https://github.com/semanser/uuid-test

```
error[E0277]: the trait bound `Uuid: OutputType` is not satisfied
 --> src/main.rs:4:10
  |
4 | #[derive(SimpleObject)]
  |          ^^^^^^^^^^^^ the trait `OutputType` is not implemented for `Uuid`
  |
  = note: required because of the requirements on the impl of `OutputType` for `&Uuid`
  = note: this error originates in the derive macro `SimpleObject` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `Uuid: OutputType` is not satisfied
 --> src/main.rs:4:10
  |
4 | #[derive(SimpleObject)]
  |          ^^^^^^^^^^^^ the trait `OutputType` is not implemented for `Uuid`
  |
  = note: this error originates in the derive macro `SimpleObject` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `uuid-test` due to 2 previous errors
```

**Comment by cynecx** [comment]
@semanser That's because the sqlx release you are on is still using uuid-0.8.x:

https://github.com/launchbadge/sqlx/blob/6be16b4d1b55b20985b8b762956ab443f9481c3d/sqlx-core/Cargo.toml#L161

**Comment by semanser** [comment]
Ah, you're right. I was checking it on `master` and it uses 1.0 already... thanks!

https://github.com/launchbadge/sqlx/pull/1821
