### ISSUE TITLE
GraphQL ID Conversions

### ISSUE THREAD

**Issue by kennetpostigo** [async-graphql/async-graphql#910]
Hi, I have a few questions about `ID` type from async_graphql.

1. How to convert to and from `uuid::Uuid`? I tried a few things `into()` but it wasn't working
2. How to enable support for `ID` when using cursor pagination? I get a trait bound error across the board for this.
3. Is it possible to have connection be `Result<Connection<ID, User, EmptyFields, EmptyFields>>` Where `ID` is used instead of `String`?

**Comment by sunli829** [comment]
You can convert `uuid` to `ID` with `ID::from(uuid)`.
