### ISSUE TITLE
How to test particular queries/mutations directly

### ISSUE THREAD

**Issue by Gricha** [async-graphql/async-graphql#912]
I have an axum service with async-graphql on top of it. Currently, if I want to run a test against my mutation/query, I can only do so via actually running a request against axum like this:
```
let query = r#"
    mutation {
        myMutation(input:{name: "test"}) {
          name
        }
    }
    "#;
    let body = Body::from(serde_json::to_string(&TestGraphQLRequestData::new(query)).unwrap());
    let namespace = Uuid::new_v4().to_string();

    let response = app
        .oneshot(
            Request::builder()
                .method(http::Method::POST)
                .uri("/")
                .body(body)
                .unwrap(),
        )
        .await
        .unwrap();
    let body = hyper::body::to_bytes(response.into_body()).await.unwrap();
    let body: serde_json::Value = serde_json::from_slice(&body).unwrap();
    assert_eq!(
        body,
        json!({"data":{"myMutation":{"name":"test"}}})
    );
```
This somewhat works, but I don't want to have to run a full end-to-end request here if I just want to ensure a proper state will be established upon running a particular mutation.

Ideally, I would want to just call a function directly. Something like this:
```
#[tokio::test]
    async fn test_my_mutation() {
        let ctx: Context<'static> = ???;
        let mutation = RootMutation {};
        mutation
            .my_mutation(
                &ctx,
                MyMutationInput {
                    name: "test".to_string(),
                },
            )
            .await
            .unwrap();
    }
```
Main reason I'm thinking that is the ergonomics of having to work with return types I've already defined as part of schema, so writing assertions will be no problem, in first example I have to deal with JSON blobs.

To achieve something like this I need to be able to construct a Context, and I find that very hard right now. There's no examples of how to do it, it seems unstable (`ContextBase` mentions it being unstable class). With that I'm curious:
* Do you have recommendations for how to actually create Context in the current state of codebase?
* Have you considered introducing helpers for Context creation specifically to aid testing?

And interesting alternative to that as well is to split the concept of Context from the concept of Data a little bit. The only reason why I need `Context` in my field resolvers/mutations is because I need to vend my own data off of it, but anything else that this Context carries is not relevant or useful to me, I assume it's mostly used for internals of async-graphql? If these are true, then interesting path would be to have this as InternalContext, whereas an actual Context object that is passed around fields resolvers/mutations is a Trait that a developer can implement themselves, or alternatively inject it by extension.

**Comment by Gricha** [comment]
Oh I forgot to add - for now I have a workaround, namely I can extract the actual mutation code to a separate function, and I use main mutation code only to extract whatever variables I need. It works, but it is a bit clunky and introduces a bunch of boilerplate. Here's an example:
```

#[Object]
impl Mutation {
    async fn my_mutation<'ctx>(
        &self,
        ctx: &Context<'ctx>,
        input: MyMutationInput,
    ) -> Result<bool> {
        let db_manager = ctx.data::<Arc<dyn DBManager>>()?;
        my_mutation(db_manager, input).await
    }
```

**Comment by sunli829** [comment]
It is not possible to test particular query directly, but at least it is possible to test without creating an HTTP server.

https://github.com/async-graphql/async-graphql/blob/8011b9a1206420cb5811f82e647bfd68826e6e0e/tests/input_object.rs#L185

**Comment by Gricha** [comment]
I see, this I think addresses big part of my problem with debuggability when crossing network boundary.

I think this will work for me now for majority of tasks, I think for me personally, I'd still love having the ability to create the Context object directly for tests, since that path allows me to have fully typed responses, but that already takes me places.

What's your general opinion of injecting data through extensions instead of Context? I can imagine this would be massive rehaul, of internal infrastructure, but am curious more generally.
