### ISSUE TITLE
Accessing values of parent object

### ISSUE THREAD

**Issue by constantincerdan** [async-graphql/async-graphql#914]
Is there a way to access the values of a parent object? I'm looking at porting over a JavaScript implementation of a GraphQL server to Rust and I've hit a bit of a wall. 

In the JavaScript version, I've got the following schema:

```graphql
type Product {
  id: String
  taxonomy: Taxonomy
}

type Taxonomy {
  brands: [TaxonomyItem]
  sub_brands: [TaxonomyItem]
}

type TaxonomyItem {
  name: String!
  slug: String!
}
```

With the following resolvers:

```javascript
module.exports = {
  Product: {
    async taxonomy(parent) {
      return parent;
    }
  },

  Taxonomy: {
    brands({ brand_ids }) {
      return brands.getByIds(brand_ids);
    },
    sub_brands({ sub_brand_ids }) {
      return subBrands.getByIds(sub_brand_ids);
    }
  }
};

```
And the following query:
```graphql
type Query {
  productById(id: String!): Product
}
```
...with its corresponding resolver:
```javascript
module.exports = {
  Query: {
    async productById(_, { id }) {
      return products.getById(id);
    }
  }
};
```
The `products.getById(id)` call in the `productById` query returns a `Product` from our DB that has some additional fields like `brand_ids` and `sub_brand_ids` not declared in the schema but needed by `Taxonomy`. 

With this setup, when either of the two fields in the `Taxonomy` object are requested, their resolvers will have access to the parent `Product` object (because I'm returning `parent` in the `taxonomy` field resolver on `Product`) and the `brand_ids` or `sub-brands` fields they need to query other DBs to get the data required for their `TaxonomyItem`s.

It is possible to do something similar with `async-graphql`?

**Comment by sunli829** [comment]
There is no need to access the parent object, when creating the child object, pass the properties it needs, like this:

https://github.com/async-graphql/async-graphql/blob/4e8128575697d22878624ec4e294f3287652c116/src/model/schema.rs#L51

**Comment by constantincerdan** [comment]
I've had a look at the code you've referenced and I'm not sure I fully understand. How would I do what you've suggested with this schema?
```rust
#[derive(SimpleObject, Serialize, Deserialize)]
struct Product {
    name: String,
    Taxonomy: Taxonomy
}

#[derive(SimpleObject, Serialize, Deserialize)]
struct Taxonomy {
    brands: Vec<TaxonomyItem>,
    sub_brands: Vec<TaxonomyItem>,
}

#[derive(SimpleObject, Serialize, Deserialize)]
struct TaxonomyItem {
    name: String,
    slug: i32,
}
```

**Comment by constantincerdan** [comment]
> There is no need to access the parent object, when creating the child object, pass the properties it needs, like this:
> 
> https://github.com/async-graphql/async-graphql/blob/4e8128575697d22878624ec4e294f3287652c116/src/model/schema.rs#L51

I've had a look at the code you've referenced and I'm not sure I fully understand. How would implementing what you've suggested look with a schema like this?
```rust
#[derive(SimpleObject, Serialize, Deserialize)]
struct Product {
    name: String,
    Taxonomy: Taxonomy
}

#[derive(SimpleObject, Serialize, Deserialize)]
struct Taxonomy {
    brands: Vec<TaxonomyItem>,
    sub_brands: Vec<TaxonomyItem>,
}

#[derive(SimpleObject, Serialize, Deserialize)]
struct TaxonomyItem {
    name: String,
    slug: i32,
}
```

**Comment by constantincerdan** [comment]
I understand now, @sunli829 . You meant something like this: 

```rust
#[derive(SimpleObject)]
#[graphql(complex)]
struct Product {
    name: String,
    #[graphql(skip)]
    brand_id: i16,
}

#[ComplexObject]
impl Product {
    async fn taxonomy<'a>(&'a self) -> Taxonomy<'a> {
        Taxonomy { product: self }
    }
}

struct Taxonomy<'a> {
    product: &'a Product,
}

#[Object]
impl Taxonomy<'_> {
    async fn brand(&self) -> TaxonomyItem {
        // do db stuff
    }
}
```
