### ISSUE TITLE
Update @oneOf directive implementation

### ISSUE THREAD

**Issue by bvanneerven** [async-graphql/async-graphql#915]
## Expected Behavior

Since #766, unfortunately the implementation of the `@oneOf` directive in the [proposed GraphQL spec update](https://github.com/graphql/graphql-spec/pull/825) (that moved from stage 1 to stage 2 recently) changed. The `@oneOf` directive is now only applicable to input objects.

## Actual Behavior

The correct SDL output should be
```gql
directive @oneOf on INPUT_OBJECT
```
Also, the features related to OneOf Fields are no longer spec compliant and should be deprecated.

**Comment by sunli829** [comment]
Well, I will delete the code related to OneOf fields later. . . 😂

**Comment by sunli829** [comment]
OMG, I deleted 1000+ lines of code. 😵
