### ISSUE TITLE
How to use LruCache?

### ISSUE THREAD

**Issue by al8n** [async-graphql/async-graphql#918]
Hi, I am confused about how to use a LruCache when using DataLoader. Are there any examples for me to learn?

**Comment by sutt0n** [comment]
For those who ran into a dead end like I did here, look at the unit tests for `with_cache`. 🙂 

https://github.com/async-graphql/async-graphql/blob/e99a6bb8af0313fdf470e605ba3ccd30a2988179/src/dataloader/mod.rs#L578
