### ISSUE TITLE
Auto hide for guards

### ISSUE THREAD

**Issue by urkle** [async-graphql/async-graphql#927]
## Description of the feature
currently you have guards on fields (e.g. a guard on a mutation). But if I want to hide those as well I have to setup two different ways of doing so.

```rust
fn is_admin(ctx: &Context<'_>) -> bool {
    todo!()
    // repeating same logic that RoleGuard does
}

struct MutationRoot;

#[Object]
impl MutationRoot {
    #[graphql(guard = "RoleGuard::new(Role::Admin)", visible = "is_admin")]
    async fn createUser(&self, input: CreateUserInput) -> Result<CreateUserPayload) {
      todo!()
    }
}
```

## Code example (if possible)

It would be nice if there was some generic way to have a simple "is_guarded" type check
```rust
#[Object]
struct MutationRoot {
    #[graphql(guard = "RoleGuard::new(Role::Admin)", visible = "is_guarded")]
    async fn createUser(&self, input: CreateUserInput) -> Result<CreateUserPayload) {
      todo!()
    }
}
```

**Comment by sunli829** [comment]
This is not possible because the two attributes appear to be the same, but they are in different phases of execution.
