### ISSUE TITLE
Sqlx::Uuid type not working with async-graphql Uuid anymore

### ISSUE THREAD

**Issue by Oyelowo** [async-graphql/async-graphql#937]
Thanks for creating this awesomest library 🙏 

## Expected Behavior
`sqlx::types::Uuid` was previously working with `async-graphql` as at version `3` but not anymore. Is there anyway to make it work easily with other versions of `Uuid`?

**Given a model User**,

```rs
#[derive(
    SimpleObject,  // ---> This now throws a compile time error mentioned below
    Serialize,
    Deserialize,
    FromRow,
    Validate,
    Debug,
    DeriveEntityModel,
    Clone,
    PartialEq,
)]
#[graphql(complex)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: sqlx::types::Uuid,     //  ---> This used to work before the update

    pub created_at: DateTime<Utc>,
  
}
```

## Actual Behavior

Error

```rs
async_graphql_derive
proc_macro SimpleObject
the trait bound `sqlx::types::Uuid: OutputType` is not satisfied
required because of the requirements on the impl of `OutputType` for `&sqlx::types::Uuid`rustc[E0277](https://doc.rust-lang.org/error-index.html#E0277)
the trait bound `sqlx::types::Uuid: OutputType` is not satisfied
the trait `OutputType` is not implemented for `sqlx::types::Uuid`rustc[E0277](https://doc.rust-lang.org/error-index.html#E0277)
```

## Steps to Reproduce the Problem

1. Create a struct model with the annotations as shown above
2. Use `sqlx::types::Uuid`

## Specifications

- Version:
- Platform:
- Subsystem:

**Comment by Oyelowo** [comment]
So, while I was digging to make a PR, I realised that the older `uuid` had been renamed to `uuid08`.
So, the solution is to simply add this as a feature in your `Cargo.toml`. e.g
```rs
async-graphql = {version = "4.0.1", features = [
  "apollo_tracing",
  "apollo_persisted_queries",
  "bson",
  "dataloader",
  "chrono",
  "chrono-tz",
  "log",
  "dataloader",
  "tracing",
  "opentelemetry",
  "unblock",
  "url",
  "uuid",
  "uuid08",  // ---> this should solve your problem. and u can switch after ur orm switches
  "string_number",
  "secrecy",
  "decimal",
  "smol_str",
]}
```

**Comment by Oyelowo** [comment]
Is this documented somewhere? Couldn't find it in the release not nor a migration guide. It's mentioned on the guides page but might not be obvious to existing users. I can add this if need be 🤔

**Comment by Oyelowo** [comment]
I'm closing this now as it is already resolved

**Comment by sunli829** [comment]
> Is this documented somewhere? Couldn't find it in the release not nor a migration guide. It's mentioned on the guides page but might not be obvious to existing users. I can add this if need be 🤔

I guess `uuid 0.8` should be deprecated soon, so not quite sure if this is necessary. 😂

**Comment by Oyelowo** [comment]
True, I'm just thinking this could affect those that are stuck with 0.8 for a while causing them to waste time on debugging 😂

Is there a migration guide for 4.0?
That might be useful
