### ISSUE TITLE
Custom scalar is not appeared in the `_service {     sdl   }` query

### ISSUE THREAD

**Issue by rkudryashov** [async-graphql/async-graphql#94]
Hi, thank you for this library. I encountered the following issue:

First, I add custom scalar as per doc (https://async-graphql.github.io/async-graphql/en/custom_scalars.html):

```
#[derive(Clone, Serialize)]
pub struct CustomDecimal(pub Decimal);

#[Scalar]
impl ScalarType for CustomDecimal {
    fn type_name() -> &'static str {
        "Decimal"
    }

    ...
}

```

Then I am starting Apollo Gateway (`npm run start-gateway`):
```
Server ready at http://localhost:4000/
This data graph is missing a valid configuration. Unknown type: "Decimal".
```

I think the issue is raised because `_service {     sdl   }` query doesn't return description of custom scalars:
```
{
  "data": {
    "_service": {
      "sdl": "type SomeType @key(fields: \"id\") {\n\tid: ID!\n\ttestField: Decimal!\n}\ntype Query {\n\tsomeQuery: SomeType!\n}\n"
    }
  }
}
```

Repro-project is here: https://github.com/rkudryashov/async-graphql-reproducer

PS: Is there a way to make a scalar from a third-party library's struct without using a wrapper?

**Comment by sunli829** [comment]
Thanks for your feedback, I will resolve this issue immediately. 😁

**Comment by sunli829** [comment]
> PS: Is there a way to make a scalar from a third-party library's struct without using a wrapper?

Because you need to implement `ScalarType` for the third-party library structure, due to orphan rules, rust does not allow you to do so. 😁

**Comment by sunli829** [comment]
Please upgrade to 1.12.12, I solved the problem.

**Comment by rkudryashov** [comment]
Thanks for the instant response, now it is working fine. But I encountered another issue: https://github.com/async-graphql/async-graphql/issues/95
