### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by Adel-ak** [async-graphql/async-graphql#942]
So I come from a nodejs background and decided to get on the rust train.

I've got a few questions about subscriptions in rust async graphql and to clarify them to move one.

1. Can I use rabbitmq to manage subscriptions instead redis, if so how?

2. In nodejs graphql subscriptions I have the option to filter out which user will receive the data based on some variables from the client, but can't seem to do in async graphql, how do I implement such thing ?

3. Apollo client v3 is using graphql-ws which works fine with my nodejs server but not async graphql, is there any plan to make it work async graphql?

I hope I'm clear with my questions 😅

**Comment by sunli829** [comment]
> 1. Can I use rabbitmq to manage subscriptions instead redis, if so how?

This is not much different from using `redis`, basically you need to subscribe to some topics and create a stream.

> In nodejs graphql subscriptions I have the option to filter out which user will receive the data based on some variables from the client, but can't seem to do in async graphql, how do I implement such thing ?

You can pass these variables to `Context` so that you can filter some data while executing the query.

> Apollo client v3 is using graphql-ws which works fine with my nodejs server but not async graphql, is there any plan to make it work async graphql?

`Async-graphql` also supports `graphql-ws`.

**Comment by Adel-ak** [comment]
@sunli829 Thank you for the quick response 🙏 😄.

I believe I managed to understand questions 1 and 3.

But I can't seem to make the filtering event work could you possibly show me a example.

Also I can't figure out how to publish a simple object, I keep on getting trait ToRedisArgs implementation is missing.

It works if I publish any primitive type.

Please and thank you

**Comment by Adel-ak** [comment]
@sunli829 I managed to get the error working but I can't figure out how will I implement filtering based on your variables
