### ISSUE TITLE
Does async-graphql support graphql over GET?

### ISSUE THREAD

**Issue by kennetpostigo** [async-graphql/async-graphql#944]
It seems like more clients are enabling the ability to send queries over `HTTP GET` and mutations over `HTTP POST`. Does `async-graphql` support this feature?

**Comment by sunli829** [comment]
This is actually related to integrating `Async-graphql`, like this:

https://github.com/async-graphql/async-graphql/blob/dc50049020a643098e3f52950a69e438243cde83/integrations/poem/src/extractor.rs#L71
