### ISSUE TITLE
Unknown field "_service" on type "Query".

### ISSUE THREAD

**Issue by rkudryashov** [async-graphql/async-graphql#946]
After update to latest 4-th version, it seems that `enable_federation` method (https://github.com/rkudryashov/graphql-rust-demo/blob/master/auth-service/src/lib.rs#L54) doesn't force generation of `_service` entry point. This is needed for services that don't have Federation stuff/distributed types, but nevertheless are used as downstream service behind Federation gateway.

## Expected Behavior
```
{
  _service {
    sdl
  }
}
```

Returns SDL

## Actual Behavior

Request above returns:

```
{
  "data": null,
  "errors": [
    {
      "message": "Unknown field \"_service\" on type \"Query\".",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

**Comment by KevinXdefi** [comment]
Any idea how to solve this ?

**Comment by sunli829** [comment]
Thank you @rkudryashov , I have fixed it. 🙂
