### ISSUE TITLE
How do I use an edge outside of the context of a connection?

### ISSUE THREAD

**Issue by emwalker** [async-graphql/async-graphql#947]
I'm new to Rust, so forgive my novice question.  I would like to use a Relay edge outside of the context of a connection:
```rust
pub type LinkEdge = Edge<String, Link, EmptyFields>;

#[derive(SimpleObject)]
pub struct UpsertLinkPayload {
    alerts: Vec<Alert>,
    link_edge: Option<LinkEdge>,
}
```

This is a common idiom that is used whenever you want the new edge to appear within an existing connection as a side effect of a successful mutation.

When I try to do this, I'm getting a runtime panic, presumably because I'm constructing connections elsewhere and letting `async-graphql` build the edge itself.

```sh
$ cargo run
...
backend  | thread 'main' panicked at '`async_graphql::types::connection::edge::Edge<usize, digraph::schema::link::Link, async_graphql::types::connection::EmptyFields>` and `async_graphql::types::connection::edge::Edge<alloc::string::String, digraph::schema::link::Link, async_graphql::types::connection::EmptyFields>` have the same GraphQL name `LinkEdge`', /home/walker/.cargo/registry/src/github.com-1ecc6299db9ec823/async-graphql-3.0.38/src/registry/mod.rs:467:25
backend  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

What is the idiomatic way to avoid this panic?

**Comment by sunli829** [comment]
This is because these two edge types have the same GraphQL name, please upgrade to `async-graphql v4.0`, you can specify different names for them.

**Comment by emwalker** [comment]
What is a little confusing to me is that the `LinkEdge` in this case should be the same type as the one used in connections; there's only one `LinkEdge` in my schema, sometimes used in connections and sometimes used outside of them, e.g., [here](https://github.com/emwalker/digraph/blob/master/schema.graphql#L140-L149) and [here](https://github.com/emwalker/digraph/blob/master/schema.graphql#L492-L495).  Conceptually, the edges are the same type.  Needing to model them as two separate types with different names feels like it departs from the GraphQL specification.  Am I mistaken?

**Comment by sunli829** [comment]
Their cursor types are not the same, one is an `integer` and the other is a `string`, but they have the same GraphQL name, so 
 it panics.

```rust
async_graphql::types::connection::edge::Edge<usize, digraph::schema::link::Link, async_graphql::types::connection::EmptyFields>
                                             ^^^

async_graphql::types::connection::edge::Edge<alloc::string::String, digraph::schema::link::Link, async_graphql::types::connection::EmptyFields>
                                             ^^^
```

**Comment by emwalker** [comment]
Yes — that was the issue.  Now I see what's going on.  Many thanks for your help.
