### ISSUE TITLE
Make `fast_chemail` dependency optional

### ISSUE THREAD

**Issue by iffy-validio** [async-graphql/async-graphql#949]
version: v4.0.2

Hi! We're running into licensing issues using this library unfortunately due to the inclusion of an MPL-2.0 licensed dependency

```sh
$ cargo-license
...
MPL-2.0 (2): ascii_utils, fast_chemail
```
Its brought in by the `fast-chemail` library used for email validation - (it in turn drags in `ascii_utils`).

In our case, we don't have a need for email validator but would still like to use the library so would you folks be open to making `fast_chemail` an optional dependency so that we can opt out of it? (If so we'd be happy to create a PR for this)

**Comment by sunli829** [comment]
Yes, welcome to PR. 🙂
