### ISSUE TITLE
InputObject description?

### ISSUE THREAD

**Issue by rex-remind101** [async-graphql/async-graphql#954]
How do I add a `description` to an `InputObject`?

**Comment by rex-remind101** [comment]
As well as the fields of an `InputObject`?

**Comment by penso** [comment]
You can just use rustdoc `/// your description` as included in https://github.com/async-graphql/async-graphql/issues/62 and sampled at https://github.com/async-graphql/examples/blob/master/models/starwars/src/model.rs#L14

**Comment by rex-remind101** [comment]
Oh wow, is that clearly documented somewhere and I just couldn't find it?
