### ISSUE TITLE
Type definition is dissapeared after adding field of enum type

### ISSUE THREAD

**Issue by rkudryashov** [async-graphql/async-graphql#96]
After I'm just adding a new field (`enum_field`) to the working example:

```
#[derive(Clone)]
pub struct SomeType {
    pub id: ID,
    test_field: CustomDecimal,
    test_field_2: Interface,
    enum_field: TestEnum,
}

#[Object]
impl SomeType {
    
    ...

    async fn enum_field(&self) -> &TestEnum {
        &self.enum_field
    }
}

#[Enum]
enum TestEnum {
    Value1,
}
```

`SomeType`'s definition will be disappeared from the `service.sdl` query's response.

Repro-project is here: https://github.com/rkudryashov/async-graphql-reproducer

**Comment by sunli829** [comment]
Please upgrade to `1.12.15`.  😂
