### ISSUE TITLE
Field Guard wrapping simple function

### ISSUE THREAD

**Issue by Gricha** [async-graphql/async-graphql#967]
Currently, to write a field guard, you have to implement an entire struct and implement single-function trait for it:
```
#[derive(SimpleObject)]
struct Query {
    /// Only allow Admin
    #[graphql(guard = "RoleGuard::new(Role::Admin)")]
    value1: i32,
    /// Allow Admin or Guest
    #[graphql(guard = "RoleGuard::new(Role::Admin).or(RoleGuard::new(Role::Guest))")]
    value2: i32,
}
```

For majority of my use cases, I'd imagine a bit simpler API where you can simply add guard over a function:
```
async fn foo<'ctx>(context: &Context<'ctx>) -> Result<()> {
  Ok(())
}
```
and use it as such:
```
#[derive(SimpleObject)]
struct Query {
    /// Only allow Admin
    #[graphql(guard = "foo")]
    value1: i32,
}
```

My main reason for this is verbosity and reducing the number of structs we need. In majority of my cases I don't actually have state for Guards and for some specific models, being able to colocate a simple function next to the model is beneficial for readability. While it can be achieved in current model, it's more boilerplate and potentially bigger hit to binary size/compilation times etc.

I've tried replicating this on top of the current system with this snippet: 
```
use async_graphql::{Context, Guard, Result};
use futures::Future;

pub type GraphQLVisibilityResolver<'a, 'ctx, T> = fn(&'a Context<'ctx>) -> T;

async fn allowed<'a, 'ctx>(ctx: &'a Context<'ctx>) -> Result<()> {
    Ok(())
}

pub struct ExampleGuard<'a, 'ctx, T>
where
    T: Future<Output = Result<()>> + 'static,
{
    resolver: GraphQLVisibilityResolver<'a, 'ctx, T>,
}

impl<'a, 'ctx, T> ExampleGuard<'a, 'ctx, T>
where
    T: Future<Output = Result<()>> + 'static,
{
    pub fn with(resolver: GraphQLVisibilityResolver<'a, 'ctx, T>) -> Self {
        ExampleGuard { resolver }
    }
}

#[async_trait::async_trait]
impl<'a, 'ctx, T> Guard for ExampleGuard<'a, 'ctx, T>
where
    T: Future<Output = Result<()>> + 'static + Send,
{
    async fn check(&self, context: &Context<'ctx>) -> Result<()> {
        let val = (self.resolver)(context).await;
        val
    }
}

async fn testit() {
    let g = ExampleGuard::with(allowed);
}

```
But sadly I can't make the lifetimes to agree due to `check` function requiring anonymous lifetime.

**Comment by sunli829** [comment]
It is easier to implement without support for asynchronous functions, which should also satisfy most use cases.

https://github.com/async-graphql/async-graphql/blob/e839ffafcce3b114289d61a54cb5edbe1377e1a0/tests/guard.rs#L589

**Comment by Gricha** [comment]
Good to know there exists the function syntax! Thank you for the pointer.

I have a use case where having the ability to run async function does help - specifically some permissions for the current actor are held in DB and require lookup depending on the actor, and all our DB connections require async execution.

This is not a blocker by any means given that I can use `Guard` trait to solve this, but having ability to use `async` function directly is a nice to have.

With that then two questions:
* Do you remember what was the issue with supporting asynchronous functions?
* Would you accept a PR if I were able to add a support for this?
