### ISSUE TITLE
Cursor pagination with SQLX

### ISSUE THREAD

**Issue by wileymc** [async-graphql/async-graphql#974]
Hi all! 

I'm wondering if anyone has had success in implementing cursor based pagination that integrates directly with SQLX queries.  I'm currently using the Relay implementation from Vector authored [here](https://github.com/vectordotdev/vector/blob/master/src/api/schema/relay.rs), but this implementation pulls everything into memory and then slices up the pages which is not ideal when querying a database. Wondering if anyone has an elegant solution to make staggered queries to the database using a async-graphql cursor connection and sqlx?

**Comment by azzamsa** [comment]
I try to find any example or boilerplate but had no luck. So I decided to implement it myself.

- https://github.com/azzamsa/rust-graphql/pull/2

In this PR, you can see each commit implementing the pagination step by step. From basic -> vector.dev like -> to implementation from scratch. The vector.dev implementation was great, however, it pulls all the data, and is not suitable for use with Database as maintainer [explained](https://github.com/async-graphql/async-graphql/issues/563#issuecomment-1049549051). 

To read more context see https://github.com/async-graphql/async-graphql/issues/563#issuecomment-1060073851

- https://github.com/azzamsa/rust-graphql/pull/5

In this PR, I tried to port the latter to async.

**Comment by frederikhors** [comment]
Please nope.

**Comment by frederikhors** [comment]
Nope

**Comment by azzamsa** [comment]
Related: 
- https://github.com/SeaQL/seaography/issues/58

**Comment by AJTJ** [comment]
For the next poor soul wandering this way, here's a pretty complete example:
```rs
pub async fn gql_query<
    O: OutputType,
    R: Future<Output = Result<Vec<(String, O)>, BigError>>,
    F: Fn(QueryParams) -> R,
>(
    query_params: QueryParams,
    db_retrieval_closure: F,
) -> Result<Connection<String, O, EmptyFields, EmptyFields>> {
    query(
        query_params.after,
        None,
        query_params.first.and_then(|n| Some(n as i32)),
        None,
        |after: Option<String>, _before, first, _last| async move {
            let vec_of_items = db_retrieval_closure(QueryParams { after, first }).await?;
            let mut connection = Connection::new(true, true);
            connection.edges.extend(
                vec_of_items
                    .into_iter()
                    .map(|(u, o)| Edge::with_additional_fields(u, o, EmptyFields)),
            );
            Ok::<_, async_graphql::Error>(connection)
        },
    )
    .await
}
```
