### ISSUE TITLE
Lifetime errors on SimpleObject

### ISSUE THREAD

**Issue by SorenHolstHansen** [async-graphql/async-graphql#975]
Recently came back to a project of mine, and now, whenever i compile, i get
```
lifetime may not live long enough
  --> src/errors/form_field_error.rs:10:10
   |
10 | #[derive(SimpleObject, Debug)]
   |          -^^^^^^^^^^^
   |          |
   |          let's call the lifetime of this reference `'2`
   |          let's call the lifetime of this reference `'1`
   |          associated function was supposed to return data with lifetime `'1` but it is returning data with lifetime `'2`
   |
   = note: this error originates in the derive macro `SimpleObject` (in Nightly builds, run with -Z macro-backtrace for more info)
```

## Specifications

- Version: 3
- Platform: Mac
- Subsystem: Actix-web

**Comment by SorenHolstHansen** [comment]
Nevermind, had forgotten to update to version 4 when using actix-web 4

**Comment by SorenHolstHansen** [comment]
You should use the `async-graphql-actix-web` package as well

**Comment by SadiinsoSnowfall** [comment]
But the crate I'm having a problem with doesn't use any actix crate.

**Comment by penso** [comment]
Same here with:

rustc 1.62
actix 4.0.4
async-graphql-actix-web 4.0

**Comment by SorenHolstHansen** [comment]
@SadiinsoSnowfall Have reopened it now

**Comment by SorenHolstHansen** [comment]
The problem arose for me when i created a new mutation. I had a UserQuery with one method and a UserMutation with one method. When i added one more method to the UserMutation, the error came

**Comment by bbigras** [comment]
Isn't this issue a duplicate of #900 ?

**Comment by Adel-ak** [comment]
This happened to me when i updated rust to version 1.62.0 this morning and it started throwing this error when i started adding a new feature.

It was fine when i tested it in the AM but started getting the error in the PM.

I downgraded to 1.61.0 and it seems to be working as expected.

**Comment by rongcuid** [comment]
Same issue. I am using `axum` instead.

**Comment by rongcuid** [comment]
Looks like `rustc 1.64.0-nightly (38b72154d 2022-07-11)` does not have this issue.

**Comment by floric** [comment]
> I have also the issue on 1.62 but the strange thing is that I can run `cargo clean` and then `cargo test` (and it works). Then I work with code and suddenly it stop working (I use `rust-analyzer` as lsp). It compile fine after cargo clean again. I do not have exact steps to reproduce. As it sometimes get error and sometimes not (but works always after `cargo clean`).

Yes, I can confirm this. After some changes in VS Code with the Rust Analyzer I get this error when running `cargo test`. The changes are completely unrelated to my GraphQL code. I'm not using any dedicated server but creating schemas natively in connection with a custom Lambda runtime. Running `cargo clean` and then `cargo test` again will fix it. 

I also checked Rust 1.61 in comparison and I can confirm it works there correctly.

Also agree with @bbigras the issues seem to be duplicates. Maybe we can continue the communication in one of them.

**Comment by bbigras** [comment]
> Also agree with @bbigras the issues seem to be duplicates. Maybe we can continue the communication in one of them.

My issue has a cooler number and was opened 86 days ago.

**Comment by floric** [comment]
> > Also agree with @bbigras the issues seem to be duplicates. Maybe we can continue the communication in one of them.
> 
> My issue has a cooler number and was opened 86 days ago.

Sounds reasonable. 👍 

I also now checked both versions 3 and 4 of async-graphql and also upgraded all deps to the latest versions and the bug still exists. :/

**Comment by SadiinsoSnowfall** [comment]
> I also checked Rust 1.61 in comparison and I can confirm it works there correctly.

> I also now checked both versions 3 and 4 of async-graphql and also upgraded all deps to the latest versions and the bug still exists. :/

The bug is only present in 1.62 it seems. I suggest anyone having this bug to either rollback temporarily to 1.61 or go to the nightly version.

I have found one issue on the rust github about a regression related to lifetimes in 1.62 but I don't know if it's exactly the same thing (I still didn't manage to get a small repro for this problem :/)

**Comment by emwalker** [comment]
Seeing this as well.

> I have also the issue on 1.62 but the strange thing is that I can run cargo clean and then cargo test (and it works). 

I suspect this is a hallmark of a rust bug (rather than an async-graphql bug).

**Comment by Oyelowo** [comment]
Having the same issue:
async-graphql: 4.0.4
rust version: 1.62
I'm using poem

Didn't have this issue with 1.61

**Comment by SadiinsoSnowfall** [comment]
This seems to be fixed in 1.62.1 can someone else check that using the [pre-release version](https://internals.rust-lang.org/t/17023) ?

**Comment by sunli829** [comment]
I also had this problem when I upgraded to Rust `1.62` 😂

**Comment by Oyelowo** [comment]
This seems sporadic for me - comes on and off. 

I upgraded to 1.62 and it's off for now but seems random

**Comment by mattoni** [comment]
https://blog.rust-lang.org/2022/07/19/Rust-1.62.1.html

Appears this issue is resolved with the latest version of stable. I upgraded and am no longer seeing the issue.
