### ISSUE TITLE
Dataloader usage and implementation question

### ISSUE THREAD

**Issue by lionkeng** [async-graphql/async-graphql#976]
Thank you @sunli829 for this awesome repo!

I have a question about how Dataloader should be implemented in practice.

From all the examples I have seen such as this one (https://github.com/async-graphql/examples/blob/master/tide/dataloader-postgres/src/main.rs), a Dataloader is created and stored as *global data* and then accessed via the schema's Context.

This is also documented here: https://async-graphql.github.io/async-graphql/en/dataloader.html

Since it is global struct, how does the Dataloader implementation actually ensure that batching and caching of data per graphQL request? By storing a Dataloader in the Context, wouldn't that end up batching and caching calls across multiple graphQL requests since there is only 1 global instance of a Dataloader?

Thanks!

**Comment by vamshiaruru-virgodesigns** [comment]
I have the same question, can @sunli829 help please? Thanks in advance :)
