### ISSUE TITLE
How to pass request context data to axum GraphQLSubscription

### ISSUE THREAD

**Issue by jrouaix** [async-graphql/async-graphql#977]
Hello,

I see a difference in actix-web & axum implementations that I cannot resolve :
examples here :
- `actix` : https://github.com/async-graphql/examples/blob/fa8fc5dde0e1f70dee67719eceecfc9ade250d1f/actix-web/subscription/src/main.rs#L21
- `axum` : https://github.com/async-graphql/examples/blob/fa8fc5dde0e1f70dee67719eceecfc9ade250d1f/axum/subscription/src/main.rs#L32

actix example a function handler, able to parse incoming request payload parts and pass them to the subscription, while `axum` example don't.

Fact is `actix` implementation can hold data : https://github.com/async-graphql/async-graphql/blob/3a69871b389ca1c7f73ab1d93e242cb15592c0ea/integrations/actix-web/src/subscription.rs#L34-L38
while `axum` implementation can't : https://github.com/async-graphql/async-graphql/blob/3a69871b389ca1c7f73ab1d93e242cb15592c0ea/integrations/axum/src/subscription.rs#L51-L53

Am I missing something ? Is it a feature missing in axum implementation ?
Without this how can I parse a `JWT` token (for example) in order to provide guards security for subscriptions in axum + async-graphql ?

**Comment by jrouaix** [comment]
Finally got something working, but it was way harder than with the `actix-web` integration 

![image](https://user-images.githubusercontent.com/2705498/178264626-d81adeb4-a693-4887-8d8a-aeba63e75841.png)

**Comment by sunli829** [comment]
Yes, `GraphQLSubscription` also uses `GralhQLWebSocket` internally, which is more convenient to use when you don't need to customize something.

**Comment by jrouaix** [comment]
Yet, but you handled `data()` on the actix side in `GraphQLSubscription` ? not on other integrations ...
Want a PR in this direction or it was on purpose ?
