### ISSUE TITLE
Any tips for using a non-Send or non-Sync future with Dataloader?

### ISSUE THREAD

**Issue by bbigras** [async-graphql/async-graphql#979]
I'm trying to use [include-postgres-sql](https://crates.io/crates/include-postgres-sql) in my dataloader and I get:

```
`dyn ToSql` cannot be shared between threads safely
```

or
```
the trait `Sync` is not implemented for `dyn ToSql`
```

I'm with `task::spawn_local` but I still get "`dyn tokio_postgres::types::ToSql` cannot be shared between threads safely".

**Comment by sunli829** [comment]
Wrap it in `tokio::sync::Mutex`?
