### ISSUE TITLE
Implement DataSource for Stream<T>

### ISSUE THREAD

**Issue by IcanDivideBy0** [async-graphql/async-graphql#98]
I'm planing to add a generic implementation of `DataSource` for `Stream`s in the same fashion it's done for slice. I'm using mongodb on m project, which returns a `Stream` of documents.

I think it's kind of wasteful to collect all stream results into a vec to then apply `query_operation` filter on this vec. I don't know about other database systems, but I think most of them are using stream also?

Does anyone have thoughts on this?

**Comment by phated** [comment]
`sqlx` uses streams of data too. I'm converting to it right now but haven't reach that point yet.

An aside: I'm probably going to be making DataSource implement static methods soon because `self` doesn't seem to be used and it doesn't currently work on enums due to requiring instance methods.

**Comment by IcanDivideBy0** [comment]
@phated I've just noticed that the slice impl uses the index in the original array to compute cursor. If the array changes (let's say an element is pushed front), all cursors are changed... which is a bit weird.
I think we should add something to allow users to map an element to a cursor and still using the generic `query_operation` logic

**Comment by sunli829** [comment]
I think this can be achieved, but it may only support one-way paging.

**Comment by sunli829** [comment]
I think OutputType should be implemented for Stream, it is a List type.

**Comment by IcanDivideBy0** [comment]
here is a first draft (I think those lifetimes can be simplified somehow...):
```rust
use crate::types::connection::{EmptyEdgeFields, QueryOperation};
use crate::{Connection, Context, Cursor, DataSource, FieldResult};
use futures::{Future, Stream, StreamExt};
use std::pin::Pin;

pub struct StreamDataSource<'a, T: 'a + Send + Sync> {
    stream: Pin<Box<dyn Stream<Item = (Cursor, EmptyEdgeFields, T)> + 'a + Send + Sync>>,
}

impl<'a, T: Send + Sync> StreamDataSource<'a, T> {
    pub fn new<S: 'a, F: 'a, Fut: 'a>(stream: S, mut f: F) -> Self
    where
        S: Stream<Item = T> + Send + Sync,
        F: FnMut(&T) -> Fut + Send + Sync,
        Fut: Future<Output = Cursor> + Send + Sync,
    {
        let stream = stream.then(move |element: T| {
            let fut = f(&element);
            async move { (fut.await, EmptyEdgeFields, element) }
        });

        StreamDataSource {
            stream: Box::pin(stream),
        }
    }
}

#[async_trait::async_trait]
impl<'a, T: 'a + Send + Sync> DataSource for StreamDataSource<'a, T> {
    type Element = T;
    type EdgeFieldsObj = EmptyEdgeFields;

    async fn query_operation(
        &mut self,
        _ctx: &Context<'_>,
        operation: &QueryOperation,
    ) -> FieldResult<Connection<Self::Element, Self::EdgeFieldsObj>> {
        let mut has_previous_page = false;
        let mut has_next_page = false;

        let edges: Vec<(Cursor, EmptyEdgeFields, T)> = match operation {
            QueryOperation::None => {
                let stream =
                    std::mem::replace(&mut self.stream, Box::pin(futures::stream::empty()));

                stream.collect::<Vec<_>>().await
            }
            _ => unimplemented!(),
        };

        Ok(Connection::new(
            None,
            has_previous_page,
            has_next_page,
            edges,
        ))
    }
}
```
@sunli829 I'll take a try at adding an implementation of `OutputType` for `Stream`

**Comment by IcanDivideBy0** [comment]
This draft requires `query_operation` to take a mutable reference to self. If anyone wants a custom implementation of DataSource, I think it can be useful to have the ability to mutate some data inside this function without having to put arcs and mutex everywhere

**Comment by IcanDivideBy0** [comment]
@sunli829 I'm having an issue adding `OutputType` for `Stream`:

`OutputType::resolve` takes an immutable reference to self, but stream can be consumed only by taking ownership of the stream. I see 2 possibilities:
- changing `OutputType::resolve` to `async fn resolve(self, ctx: &ContextSelectionSet<'_>, pos: Pos) -> Result<serde_json::Value>`. As far as I understand, values are droped right after serialization so it should not be problematic
- Having a stream wrapper with arc and mutex which implements the `OutputType` trait and `From<Stream>`

Do I missed anything?

**Comment by sunli829** [comment]
In fact, I also want the `OutputValueType::resolve` function receiver to be `self`, but I do n’t know how to support borrowed type data, I have tried this several times. 😭

```rust
#[async_trait::async_trait]
impl<T: OutputValueType + Send + Sync> OutputValueType for &T {
    #[allow(clippy::trivially_copy_pass_by_ref)]
    async fn resolve(&self, ctx: &ContextSelectionSet<'_>, pos: Pos) -> Result<serde_json::Value> {
        T::resolve(*self, ctx, pos).await
    }
}
```

This is  implement `OutputValueType` for all borrowed type. I don’t know if this is the correct way to do it.

**Comment by sunli829** [comment]
I encountered this problem when I implement `OutputValueType` for `Iterator`.

**Comment by sunli829** [comment]
Let me write an example to explain why this is `&self`, not `self`.

**Comment by sunli829** [comment]
```rust
#[Object]
struct MyObj { ... }

impl OutputValueType for MyObj {
    async fn resolve(self, ctx: &ContextSelectionSet<'_>, pos: Pos) -> Result<serde_json::Value> {
         ....
    }
}

impl OutputValueType for &MyObj {
    async fn resolve(self, cox: &ContextSelectionSet<'_>, pos: Pos) -> Result<serde_json::Value> {
         //!!!!!!!!! Must be clone
         OutputValueType::resolve(self.clone(), ctx, pos)
    }
}

```

**Comment by IcanDivideBy0** [comment]
Here is a draft for Stream -> OutputType
```rust
use crate::{registry, ContextSelectionSet, OutputValueType, Pos, Result, Type};
use futures::lock::Mutex;
use futures::{Stream, StreamExt, TryStreamExt};
use std::borrow::Cow;
use std::pin::Pin;
use std::sync::Arc;

pub struct StreamOutput<'a, T: Type> {
    stream: Arc<Mutex<Pin<Box<dyn Stream<Item = T> + 'a + Send + Sync>>>>,
}

impl<'a, S, T: Type> From<S> for StreamOutput<'a, T>
where
    S: Stream<Item = T> + 'a + Send + Sync + Sized,
{
    fn from(stream: S) -> Self {
        StreamOutput {
            stream: Arc::new(Mutex::new(Box::pin(stream))),
        }
    }
}

impl<'a, T: Type> Type for StreamOutput<'a, T> {
    fn type_name() -> Cow<'static, str> {
        Cow::Owned(format!("[{}]", T::qualified_type_name()))
    }

    fn qualified_type_name() -> String {
        format!("[{}]!", T::qualified_type_name())
    }

    fn create_type_info(registry: &mut registry::Registry) -> String {
        T::create_type_info(registry);
        Self::qualified_type_name()
    }
}

#[allow(clippy::ptr_arg)]
#[async_trait::async_trait]
impl<'a, T> OutputValueType for StreamOutput<'a, T>
where
    T: OutputValueType + Send + Sync + 'a,
{
    async fn resolve(&self, ctx: &ContextSelectionSet<'_>, pos: Pos) -> Result<serde_json::Value> {
        let stream = std::mem::replace(
            &mut *self.stream.lock().await,
            Box::pin(futures::stream::empty()),
        );

        let items = stream
            .enumerate()
            .then(|(idx, item)| async move {
                let ctx_idx = ctx.with_index(idx);
                OutputValueType::resolve(&item, &ctx_idx, pos).await
            })
            .try_collect::<Vec<_>>()
            .await?;

        Ok(items.into())
    }
}
```

And the test works fine
```rust
use async_graphql::*;

#[async_std::test]
pub async fn test_stream_type() {
    struct Root;

    #[Object]
    impl Root {
        async fn value_stream(&self) -> StreamOutput<'_, i32> {
            futures::stream::iter(vec![1, 2, 3, 4, 5]).into()
        }
    }

    let schema = Schema::new(Root, EmptyMutation, EmptySubscription);
    let query = "query { valueStream }";

    assert_eq!(
        schema.execute(query).await.unwrap().data,
        serde_json::json!({
            "valueStream": vec![1, 2, 3, 4, 5],
        })
    );
}
```

**Comment by IcanDivideBy0** [comment]
@sunli829 this would be a huge breaking change, but maybe we should not allow resolvers to return borrowed content?

**Comment by sunli829** [comment]
This is a solution, can it be more concise? 😁

**Comment by sunli829** [comment]
Disallowing the return of borrowed content may not be good. For example, a string must be cloned every time.

**Comment by sunli829** [comment]
If I change `&self` to `&mut self`, will it solve the problem?

**Comment by IcanDivideBy0** [comment]
By the way, I think `Arc`, `Box` and `&T` impl of `OutputType` can all be replaced by a single:
```rust

use std::ops::Deref;

impl<R, T> OutputValueType for R
where
    R: Deref<Target = T> + Send + Sync + 'static,
    T: Type + Send + Sync + 'static,
{
    fn type_name() -> Cow<'static, str> {
        T::type_name()
    }

    fn create_type_info(registry: &mut Registry) -> String {
        T::create_type_info(registry)
    }
}

#[async_trait::async_trait]
impl<R, T> OutputValueType for R
where
    R: Deref<Target = T> + Send + Sync + 'static,
    T: OutputValueType + Send + Sync + 'static,
{
    async fn resolve(&self, ctx: &ContextSelectionSet<'_>, pos: Pos) -> Result<serde_json::Value> {
        OutputValueType::resolve(self.deref(), ctx, pos).await
    }
}
```

@sunli829 changing `&self` to `&mut self` would allow to remove the `Arc<Mutex<_>>`, but the `mem::replace` will still be required, I don't think it's a huge deal

**Comment by sunli829** [comment]
@IcanDivideBy0 Then do we make changes in this way?

**Comment by IcanDivideBy0** [comment]
@sunli829 I'll send these tomorrow I think so I can write some doc as well

**Comment by sunli829** [comment]
Thank you very much! 😄

**Comment by IcanDivideBy0** [comment]
@sunli829 I have bad news concerning both of the mentioned improvements

## impl OutputType for Stream
There's two ways to collect the stream into a vec:

### Option 1
```rust
        let items = stream
            .enumerate()
            .then(|(idx, item)| async move {
                let ctx_idx = ctx.with_index(idx);
                OutputValueType::resolve(&item, &ctx_idx, pos).await
            })
            .try_collect::<Vec<_>>()
            .await?;
```
each item is resolved independently, this is the more efficient way to process the stream, but I'm pretty sure it will completly breaks dataloader integration

see the [dataloader trick](https://github.com/cksac/dataloader-rs/blob/master/src/cached.rs#L164)
(even worst, we'll probably not notice it util the stream have 10 elements: https://github.com/cksac/dataloader-rs/blob/master/src/non_cached.rs#L68)

### Option 2
```rust
            let v = stream.collect::<Vec<_>>().await?;
            let futures = v.iter().enumerate().map(|(idx, item)| {
                OutputValueType::resolve(item, &ctx_idx, pos)
            });
            let items = futures::future::try_join_all(futures).await?;
```
There isn't any benefit to use the stream then, I think most people can call the `.collect()` function on their own. In fact, letting users collect their stream into a vec is better for performance since it avoid all the mutex and arc mess for the stream wrapper required to implement this functionality.


## impl DataSource for Stream
I have everything working except for one point.
Let's assume a query with only the `after` variable set, relay connection spec states that if the `afterEdge` is not found, then all edges should be returned. My current implementation is something like:
```rust
    async fn query_operation(
        &mut self,
        _ctx: &Context<'_>,
        operation: &QueryOperation,
    ) -> FieldResult<Connection<Self::Element, Self::EdgeFieldsObj>> {
        let stream = std::mem::replace(&mut self.stream, Box::pin(futures::stream::empty()));

        let stream = match operation {
            QueryOperation::After { after }
            | QueryOperation::Between { after, .. }
            | QueryOperation::FirstAfter { after, .. }
            | QueryOperation::FirstBetween { after, .. }
            | QueryOperation::LastAfter { after, .. }
            | QueryOperation::LastBetween { after, .. } => {
                let after = after.clone();
                stream
                    .skip_while(move |(cursor, ..)| futures::future::ready(*cursor != after))
                    .boxed()
            }
            _ => stream,
        };

        // ...
    }
```
There's no way to know if the cursor is present in the stream until the stream is entirely processed, so i'd need to store all items in a vec to handle this case. Using streams for this becomes again useless, I think it's easier to let users collect an array on their stream an use the slice implementation of DataSource.

## Alternatively...
We can propose an **almost** relay implementation for stream which return an empty array in case the before/after cursor specified doesn't exists in the stream. On large stream this would be really beneficial, and I think many people may end up implementing like it so on their own otherwise...

Have I missed some obvious solution?

**Comment by IcanDivideBy0** [comment]
I think I've found a way for stream connection...

**Comment by sunli829** [comment]
It seems pointless to implement OutputType for Stream. 😂

**Comment by sunli829** [comment]
> Here is a draft for Stream -> OutputType
> 
> ```rust
> use crate::{registry, ContextSelectionSet, OutputValueType, Pos, Result, Type};
> use futures::lock::Mutex;
> use futures::{Stream, StreamExt, TryStreamExt};
> use std::borrow::Cow;
> use std::pin::Pin;
> use std::sync::Arc;
> 
> pub struct StreamOutput<'a, T: Type> {
>     stream: Arc<Mutex<Pin<Box<dyn Stream<Item = T> + 'a + Send + Sync>>>>,
> }
> 
> impl<'a, S, T: Type> From<S> for StreamOutput<'a, T>
> where
>     S: Stream<Item = T> + 'a + Send + Sync + Sized,
> {
>     fn from(stream: S) -> Self {
>         StreamOutput {
>             stream: Arc::new(Mutex::new(Box::pin(stream))),
>         }
>     }
> }
> 
> impl<'a, T: Type> Type for StreamOutput<'a, T> {
>     fn type_name() -> Cow<'static, str> {
>         Cow::Owned(format!("[{}]", T::qualified_type_name()))
>     }
> 
>     fn qualified_type_name() -> String {
>         format!("[{}]!", T::qualified_type_name())
>     }
> 
>     fn create_type_info(registry: &mut registry::Registry) -> String {
>         T::create_type_info(registry);
>         Self::qualified_type_name()
>     }
> }
> 
> #[allow(clippy::ptr_arg)]
> #[async_trait::async_trait]
> impl<'a, T> OutputValueType for StreamOutput<'a, T>
> where
>     T: OutputValueType + Send + Sync + 'a,
> {
>     async fn resolve(&self, ctx: &ContextSelectionSet<'_>, pos: Pos) -> Result<serde_json::Value> {
>         let stream = std::mem::replace(
>             &mut *self.stream.lock().await,
>             Box::pin(futures::stream::empty()),
>         );
> 
>         let items = stream
>             .enumerate()
>             .then(|(idx, item)| async move {
>                 let ctx_idx = ctx.with_index(idx);
>                 OutputValueType::resolve(&item, &ctx_idx, pos).await
>             })
>             .try_collect::<Vec<_>>()
>             .await?;
> 
>         Ok(items.into())
>     }
> }
> ```
> 
> And the test works fine
> 
> ```rust
> use async_graphql::*;
> 
> #[async_std::test]
> pub async fn test_stream_type() {
>     struct Root;
> 
>     #[Object]
>     impl Root {
>         async fn value_stream(&self) -> StreamOutput<'_, i32> {
>             futures::stream::iter(vec![1, 2, 3, 4, 5]).into()
>         }
>     }
> 
>     let schema = Schema::new(Root, EmptyMutation, EmptySubscription);
>     let query = "query { valueStream }";
> 
>     assert_eq!(
>         schema.execute(query).await.unwrap().data,
>         serde_json::json!({
>             "valueStream": vec![1, 2, 3, 4, 5],
>         })
>     );
> }
> ```

This code gave me great inspiration, I used it in these places. 😁

https://github.com/async-graphql/async-graphql/blob/906bcce9323fa3d41a37cc188106fa00af453c6d/src/types/deferred.rs#L13

https://github.com/async-graphql/async-graphql/blob/906bcce9323fa3d41a37cc188106fa00af453c6d/src/types/streamed.rs#L14
