### ISSUE TITLE
Give key ownership to Loader

### ISSUE THREAD

**Issue by sidju** [async-graphql/async-graphql#986]
## Description of the feature
For when you use a String or similar non-Copy type as key for a loader you currently need to .clone() each key into the returned HashMap. By having the ownership of the key given to the loader a move could be used instead, possibly saving some performance and granting some ergonomics.

This may not be practical depending on DataLoader implementation, but it would be nice if possible.

**Comment by sunli829** [comment]
Cloning is inevitable, but `Arc` can be used to wrap the key to reduce the cost of clone.
