### ISSUE TITLE
Impossible to specify both name and input_name

### ISSUE THREAD

**Issue by sunli829** [async-graphql/async-graphql#987]
### Discussed in https://github.com/async-graphql/async-graphql/discussions/985

<div type='discussions-op-text'>

<sup>Originally posted by **dspicher** July 14, 2022</sup>
I am trying to derive both `SimpleObject` and `InputObject` on a struct, and would like to rename both objects to something different than the struct name.

Looking at the [source](https://github.com/async-graphql/async-graphql/blob/2a6abe7cae481595e267414a0a0a7a9f1f808d25/derive/src/input_object.rs#L43-L47), this seems impossible, as `name` is given preference over `input_name` for the `InputObject`, leading to a name collision. I would have expected this to be the other way around.

Do you consider this a bug or a feature? :)</div>

**Comment by sunli829** [comment]
Fixed in `v5.0.0`

**Comment by dspicher** [comment]
Great stuff, thanks @sunli829 for the rapid fix!
