### ISSUE TITLE
Subscription requests get silently dropped when received in bursts greater than 8 at a time

### ISSUE THREAD

**Issue by nicolaiunrein** [async-graphql/async-graphql#99]
_EDIT: I found the bug. Details below the example code._ 

When sending start and stop requests to subscription handlers with the same id and a high frequency in order to restart the subscription the requests get dropped and I do not get any response at all. This only happens when repeated like 6 times or more and also not always. This is really annoying and I spend almost a week finding the bug in my code. However if I put a delay in between the calls it works as expected. I guess that requests get out of order when processed inside the library and the stop request get processed last.

**Comment by nicolaiunrein** [comment]
I am using `websocket-lite`. The same happens with `async-tungstenite` so I guess its not a client issue. I figured out that when sending a burst like below `handle_subscription` inside `SubscriptionTransport` is only called on first request.

Here is some test code:
```rust
async fn test_ok() {
    let builder = websocket_lite::ClientBuilder::new("ws://127.0.0.1:5001").unwrap();

    let ws_stream = builder
        .async_connect()
        .await
        .map_err(MyError::ConnectError)
        .unwrap();

    let (mut ws_sink, mut ws_stream) = ws_stream.split();

    let group_id = "231765ca-8e7f-4c1c-a1dd-8cfcac5aca72".to_owned();
    let payload = Payload {
        query: QUERY.to_owned(),
        variables: json!({ "groupId": group_id }),
        ..Default::default()
    };

    let start = Request {
        id: 1.to_string(),
        payload: Some(payload),
        r#type: RequestType::Start,
    };

    let stop = Request {
        id: 1.to_string(),
        r#type: RequestType::Stop,
        payload: None,
    };

    for x in 0..100_usize {
        println!("sending {}", x);
        //tokio::time::delay_for(std::time::Duration::from_millis(1)).await;
        ws_sink
            .send(Message::text(start.to_string()))
            .await
            .map_err(|_| "Faild to send")
            .unwrap();

        //tokio::time::delay_for(std::time::Duration::from_millis(1)).await;
        ws_sink
            .send(Message::text(stop.to_string()))
            .await
            .map_err(|_| "Faild to send")
            .unwrap();
    }

    // when not using at least one delay in between the calls a response is never received!
    let item = ws_stream.next().await.unwrap().unwrap();
    println!("{:?}", item);
}

```

**Comment by nicolaiunrein** [comment]
I found the bug. In file `src/subscription/connection.rs` we are opening a `mpsc::channel` with a capacity of 8 which leads to silently dropping requestes. The question is how do we solve this?
- We could make it an unbounded channel. This may be a vulnerability though.
- We could make it user configurable.
- We could implement a some sort of throttling.

At least we should not silently drop the requests :laughing: But I am really happy I found this nasty bug. Tell me what you think how we should solve this.

**Comment by nicolaiunrein** [comment]
My use-case might be a bit weird. To explain: I am multiplexing subscriptions and need to restart the subscriptions in order to get the first event wich is the initial state. I did not check if the limit of 8 is per ID but I assume its per TCP connection. This would mean that starting many different subscriptions at client startup would also lead to this problem. My tendency is to make the channel unbounded and let the user deal with implementing security features because every use-case is different. I am exposing my API internally only and would rather not have a limit at all but I know most people expose their API to the web but then again maybe it's the responsibility of a gateway to deal with these kind of problems.

**Comment by sunli829** [comment]
Bounded channel should not be the cause of this problem. Even if the buffer is full, the requested message should not be discarded.

I suspect it's something else. Are you using async-graphql-actix-web？

**Comment by nicolaiunrein** [comment]
Yes but I tried it. I set the limit to 1000 and no problems at all.

**Comment by sunli829** [comment]
It seems that you have been sending messages without receiving them?

**Comment by sunli829** [comment]
If you do not perform the `poll` operation on `SubscriptionStream`, you can no longer send any requests after the send buffer is full.

**Comment by nicolaiunrein** [comment]
I think this bit inside the handle function leads to a dead lock when channel is full. 
```rust
Message::Text(s) => {
    if let Some(mut sink) = self.sink.clone() {
        async move { sink.send(s.into()).await }
            .into_actor(self)
            .then(|_, actor, _| async {}.into_actor(actor))
            // we are waiting to send a message but channel is full.
            // Maybe this future should be spawned so we can continue processing incoming messages?
            .wait(ctx); 

    }
```

**Comment by sunli829** [comment]
Because the processing request is in the `poll` of `SubscriptionStream`.

**Comment by sunli829** [comment]
```rust
struct QueryRoot;

    #[Object]
    impl QueryRoot {}

    struct SubscriptionRoot;

    #[Subscription]
    impl SubscriptionRoot {
        async fn values(&self) -> impl Stream<Item = i32> {
            futures::stream::iter(0..10)
        }
    }

    let schema = Schema::new(QueryRoot, EmptyMutation, SubscriptionRoot);
    let (mut sink, mut stream) = schema.subscription_connection(WebSocketTransport::default());

    sink.send(
        serde_json::to_vec(&serde_json::json!({
            "type": "connection_init",
            "payload": { "token": "123456" }
        }))
        .unwrap()
        .into(),
    )
    .await
    .unwrap();

    assert_eq!(
        Some(serde_json::json!({
        "type": "connection_ack",
        })),
        serde_json::from_slice(&stream.next().await.unwrap()).unwrap()
    );

    ////////////////////////////////////////////////////////////////////////////////////////////////////////////
    // If you comment this line, the request will never be processed.
    // The following sending loop will block for the 8 time.
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////
    async_std::task::spawn(async move { while let Some(_) = stream.next().await {} });

    for i in 0..1000 {
        sink.send(
            serde_json::to_vec(&serde_json::json!({
                "type": "start",
                "id": format!("{}", i),
                "payload": {
                    "query": "subscription { values }"
                },
            }))
            .unwrap()
            .into(),
        )
        .await
        .unwrap();
    }
```

**Comment by sunli829** [comment]
https://github.com/async-graphql/async-graphql/blob/e949cb441c3a1b7e1f1deec9be99d0c104edad9f/src/subscription/connection.rs#L130

I am processing requests here.

**Comment by sunli829** [comment]
This is a throttle, if you can't receive messages quickly, you can't send messages quickly.

**Comment by nicolaiunrein** [comment]
Sorry I don’t know if I understand what you are saying. So you say I need to receive on the client side?

**Comment by nicolaiunrein** [comment]
But isn’t the WsActor sending messages to itself? As I understand correctly it is "waiting" to send a message to the sink but the channel is full and can only be processed if the handle function returns but since we are "waiting" instead of "spawning" we can never return and thats a dead lock.

**Comment by sunli829** [comment]
Sorry, I may not have described clearly.

After creating a subscription connection, you should start receiving messages immediately, rather than sending all requests before you start receiving messages.

```rust
let builder = websocket_lite::ClientBuilder::new("ws://127.0.0.1:5001").unwrap();

let ws_stream = builder
        .async_connect()
        .await
        .map_err(MyError::ConnectError)
        .unwrap();

let (mut ws_sink, mut ws_stream) = ws_stream.split();

task::spawn(async move {
   // receive messages
});

  for x in 0..100_usize {
        println!("sending {}", x);
        //tokio::time::delay_for(std::time::Duration::from_millis(1)).await;
        ws_sink
            .send(Message::text(start.to_string()))
            .await
            .map_err(|_| "Faild to send")
            .unwrap();

        //tokio::time::delay_for(std::time::Duration::from_millis(1)).await;
        ws_sink
            .send(Message::text(stop.to_string()))
            .await
            .map_err(|_| "Faild to send")
            .unwrap();
    }

```

**Comment by sunli829** [comment]
I can change this to an unbounded channel, and the receiver throttler can also work normally.

**Comment by nicolaiunrein** [comment]
Well I guess that only works if the tokio executor in my client code switches the task to receive messages after each send message.
But your theory would mean sending 100 stop messages followed by a start and one receive should work even with a channel capacity with 8, right? I will test it when I’m at the office.

**Comment by sunli829** [comment]
Yes, this is fine. 😁

**Comment by sunli829** [comment]
No, you cannot guarantee that no message push will arrive halfway.
And I thought about it, I changed to unbounded channel can actually solve this problem. 😂

**Comment by sunli829** [comment]
I made a change in the master branch, you can try it later.

**Comment by nicolaiunrein** [comment]
Thank you! 😄

**Comment by nicolaiunrein** [comment]
Works like a charm! :heart: 
As a side note I also tried to change `.wait(ctx)` to `.spawn(ctx)`. But that does not seem to solve it. It does not get stuck anymore and delivers more messages but still drops some.
